### ISSUE TITLE
Lexical > Blocks > Labels disappear when zoom level changes in Safari

### ISSUE THREAD

**Issue by robinscholz** [payloadcms/payload#10043]
### Describe the Bug.

When changing the browser zoom level the block dropdown stops rendering labels in Safari:

![Image](https://github.com/user-attachments/assets/0ed7e62b-aebb-45db-8d8f-96f03a509161)

### Reproduction Steps

1. Add lexical editor to Payload
2. Open Safari
3. Zoom in our out
4. Try to add a block

### Environment Info

```text
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 9.14.2
Relevant Packages:
  payload: 3.8.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
```

**Comment by GermanJablo** [comment]
Oh, sweet Safari! 🫠😆 

Fixed in https://github.com/payloadcms/payload/pull/10072, thanks for reporting!
