### ISSUE TITLE
Creating a plugin from the template fails

### ISSUE THREAD

**Issue by robotex82** [payloadcms/payload#10076]
### Describe the Bug

When following the documentation at https://payloadcms.com/docs/plugins/build-your-own and trying to create a new plugin from the template with the given command `npx create-payload-app@latest -t plugin -n my-new-plugin` the command fails with:

```
❯ npx create-payload-app@latest -t plugin -n multi-tenancy


┌   create-payload-app 
│
◇   ────────────────────────────────────────────╮
│                                               │
│  Welcome to Payload. Let's create a project!  │
│                                               │
├───────────────────────────────────────────────╯
│
■  'plugin' is not a valid template.
│
◇  Valid templates: blank, website
```
The expected output would be a success with a created plugin folder structure.

Any ideas?

Thanks in advance!

### Link to the code that reproduces this issue

-

### Reproduction Steps

Execute `npx create-payload-app@latest -t plugin -n multi-tenancy`. See it fail with:

```
❯ npx create-payload-app@latest -t plugin -n multi-tenancy


┌   create-payload-app 
│
◇   ────────────────────────────────────────────╮
│                                               │
│  Welcome to Payload. Let's create a project!  │
│                                               │
├───────────────────────────────────────────────╯
│
■  'plugin' is not a valid template.
│
◇  Valid templates: blank, website
```

### Which area(s) are affected? (Select all that apply)

area: docs, plugin: other, area: core

### Environment Info

```text
Node.js: v22.12.0
```

**Comment by denolfe** [comment]
Thank you for bringing this up. We need to bring this back into create-payoad-app.

As of now, the [plugin-template](https://github.com/payloadcms/plugin-template/tree/beta) repo has a functioning version for 3.0 on the `beta` branch.
