### ISSUE TITLE
plugin-vercel-blob: Error When Accessing Files with Unicode Characters

### ISSUE THREAD

**Issue by RikuManninen** [payloadcms/payload#10077]
### Describe the Bug

After updating from version 3.8.0 to 3.9.0, the @payloadcms/storage-vercel-blob adapter fails when accessing files that have special characters (like ö) in their filename. This functionality worked correctly in version 3.8.0 but breaks in 3.9.0. The error occurs specifically with Unicode decomposed characters, suggesting an issue with Unicode normalization in the blob storage adapter.

`TypeError: Cannot convert argument to a ByteString because the character at index 20 has a value of 776 which is greater than 255.`

https://github.com/user-attachments/assets/24f02784-b37b-4fe6-b929-bae860699bed

### Link to the code that reproduces this issue

https://github.com/RikuManninen/payload-vercel-blob-special-chars-repro

### Reproduction Steps

1. Create a new Payload project using the website template
2. Install and configure Vercel Blob adapter
3. Upload media with filename containing 'ö' or 'ä'

### Which area(s) are affected? (Select all that apply)

plugin: other

### Environment Info

```text
Binaries:
  Node: 20.6.1
  npm: 9.8.1
  Yarn: N/A
  pnpm: 9.13.2
Relevant Packages:
  payload: 3.9.0
  next: 15.1.2
  @payloadcms/db-postgres: 3.9.0
  @payloadcms/email-nodemailer: 3.9.0
  @payloadcms/graphql: 3.9.0
  @payloadcms/live-preview: 3.9.0
  @payloadcms/live-preview-react: 3.9.0
  @payloadcms/next/utilities: 3.9.0
  @payloadcms/payload-cloud: 3.9.0
  @payloadcms/plugin-cloud-storage: 3.9.0
  @payloadcms/plugin-form-builder: 3.9.0
  @payloadcms/plugin-nested-docs: 3.9.0
  @payloadcms/plugin-redirects: 3.9.0
  @payloadcms/plugin-search: 3.9.0
  @payloadcms/plugin-seo: 3.9.0
  @payloadcms/richtext-lexical: 3.9.0
  @payloadcms/storage-vercel-blob: 3.9.0
  @payloadcms/translations: 3.9.0
  @payloadcms/ui/shared: 3.9.0
  react: 19.0.0
  react-dom: 19.0.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 10
```

**Comment by denolfe** [comment]
Likely due to https://github.com/payloadcms/payload/pull/10062. @paulpopus

**Comment by RikuManninen** [comment]
Yes, 3.10 seems to fix this. This issue can be closed, thanks!
