### ISSUE TITLE
First edit does not fire autosave

### ISSUE THREAD

**Issue by PP-Tom** [payloadcms/payload#10111]
### Describe the Bug

When editing a document, the first edit you make does not fire an autosave, this is especially problematic for checkboxes and select fields.

### Link to the code that reproduces this issue

https://github.com/PP-Tom/payload-first-modify-bug

### Reproduction Steps

1. Create a new 'Bookings' document.
2. Change status from 'New Request' to 'Confirmed'
3. Go back to collection list.
4. Go back to the document you created
5. It's still on 'New Request'

Check for autosave, it doesn't happen until you make a second change.

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

```text
Payload: 3.10.0
Node: 22
Next: 15.1.0
```

**Comment by jmikrut** [comment]
@PP-Tom thank you for the report and for the reproduction! It helps us a LOT when we get those, and yours pointed me in the right direction immediately. So thank you.

This is now fixed and will be merged / released once the PR tests pass.
