### ISSUE TITLE
Creating User via UI stores confirm-password field in DB

### ISSUE THREAD

**Issue by tylkomat** [payloadcms/payload#10161]
### Describe the Bug

When creating a User via admin UI the `confirm-password` parameter is not filtered out before storing the data into the database. This is a security risk as the user password stored in plain text.

Generally, only configured fields should be stored into the DB.

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload/tree/main/templates/blank

### Reproduction Steps

1. create a new User via UI
2. Check user data in db

### Which area(s) are affected? (Select all that apply)

area: ui, area: core

### Environment Info

```text
Binaries:
  Node: 20.12.2
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  payload: 3.10.0
  next: 15.0.4
  @payloadcms/db-mongodb: 3.10.0
  @payloadcms/graphql: 3.10.0
  @payloadcms/next/utilities: 3.10.0
  @payloadcms/richtext-lexical: 3.10.0
  @payloadcms/translations: 3.10.0
  @payloadcms/ui/shared: 3.10.0
  react: 19.0.0
  react-dom: 19.0.0
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 15125
  Available CPU cores: 12
```

**Comment by r1tsuu** [comment]
This was fixed in 3.11.0 - https://github.com/payloadcms/payload/releases/tag/v3.11.0
