### ISSUE TITLE
Parsing "where" field in searchParams in CustomComponent

### ISSUE THREAD

**Issue by breadam** [payloadcms/payload#10164]
# Documentation Issue

Hey, I believe this is a documentation issue. I added a CustomComponent to afterListTable hook that shows subtotal of amount fields in the returned docs. What I want to do is to take subtotal of filtered documents, not all collection. I can't find any thing related in documentation. Is there any way to access fetched documents from CustomComponent? Or is there a function to parse where field in searchParams? 

Thank you

**Comment by jacobsfletch** [comment]
@breadam you can access the current data and query within the List View via the `useListQuery` hook. Looks like we need to add documentation for this which I've started in #10186. It looks something like this:

```tsx
'use client'
import { useListQuery } from 'payloadcms/ui'

function MyComponent() {
  const { data, query } = useListQuery();
} 
```

If you need to parse the `where` params yourself, like within another view altogether, you can do so using the `qs` package, like this:

```tsx
'use client'
import * as qs from 'qs-esm'
import { useSearchParams } from 'next/navigation'

function MyComponent() {
  const searchParams = useSearchParams()
  const parsedSearchParams = qs.parse(searchParams.toString())
}
```

But I realize this can be a bit cumbersome, so I went ahead and exported the same `parseSearchParams` utility that we use internally in #10185. Once released, you'll be able to use it like this:

```tsx
'use client'
import { useSearchParams } from 'next/navigation'
import { parseSearchParams } from '@payloadcms/ui'

function MyComponent() {
  const searchParams = useSearchParams()
  const parsedSearchParams = parseSearchParams(searchParams)
}
```
