### ISSUE TITLE
req.json() throws when reading empty body

### ISSUE THREAD

**Issue by max-degterev** [payloadcms/payload#10173]
### Describe the Bug

In my codebase I was sending a POST action with an empty body via native `fetch` (body variable is present with no value, so `undefined` passed to the request). This produces some sort of weird request with an empty body that undici is unable to parse.

```
[21:08:37] ERROR: Unexpected end of JSON input
    err: {
      "type": "SyntaxError",
      "message": "Unexpected end of JSON input",
      "stack":
          SyntaxError: Unexpected end of JSON input
              at JSON.parse (<anonymous>)
```

I had to instead get req.text() and JSON.parse in a try/catch block. req.text() reads it as an empty string, either `&& body` check is insufficient or .json() just buggy, not sure.

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload/blob/main/packages/next/src/utilities/addDataAndFileToRequest.ts#L22

### Reproduction Steps

Create a custom endpoint, use `addDataAndFileToRequest.ts`, send a POST request with an empty body, see crashes in the console.

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
v3.11
```

**Comment by max-degterev** [comment]
Yup,

move `const bodyByteSize = parseInt(req.headers.get('Content-Length') || '0', 10);` up and replace `&& body` with `&& bodyByteSize`, thats it. You're trying to JSON.parse empty body

**Comment by r1tsuu** [comment]
I was playing with this and that check wasn't sufficient, it breaks some other things.
But I can see this error _only_ when i send the Content-Type application/json header and I think it's expected if you send this header you should also send an actual JSON body or you should remove it.
