### ISSUE TITLE
Rest-api overview documentation not showing properly the operations

### ISSUE THREAD

**Issue by jvpg5** [payloadcms/payload#10202]
# Documentation Issue

In the [documentation for the restApi](https://payloadcms.com/docs/rest-api/overview) in the parts of Collections, Auth Operations, Globals and Preferences, is not showing properly the operations that can be done in the restApi, instead, it seems to be showing some unrendered front-end code.

**Comment by jacobsfletch** [comment]
@jvpg5 this is a result of this change to the way we manage docs internally here: https://github.com/payloadcms/website/pull/412. This will be resolved shortly. Related #10201.
