### ISSUE TITLE
Unable to update a related collection within an afterChange hook when using postgres

### ISSUE THREAD

**Issue by CCoffie** [payloadcms/payload#10222]
### Describe the Bug

There seems to be a bug within the postgres implementation that's not allowing afterChange hooks to update other collection items. I created a test project that shows the bug. The test project works when I switch to using mongo as the backend but when using postgres, the action times out.

### Link to the code that reproduces this issue

https://github.com/CCoffie/payload-bug

### Reproduction Steps

1. Run the test project with `npm run dev`. (I currently have a docker compose up command for postgres running as a predev command)
2. Go to the admin panel and create a credit transaction
3. Set the required fields and submit and the action will freeze

It seems to freezing on this section of the hook:
```
const updatedUser = await payload.update({
      collection: 'users',
      id: user.id,
      data: {
        credits: newCredits,
      },
    })
```

### Which area(s) are affected? (Select all that apply)

db-postgres, area: core

### Environment Info

```text
Binaries:
  Node: 22.11.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.12.3
Relevant Packages:
  payload: 3.9.0
  next: 15.1.0
  @payloadcms/db-mongodb: 3.11.0
  @payloadcms/db-postgres: 3.9.0
  @payloadcms/email-nodemailer: 3.9.0
  @payloadcms/graphql: 3.9.0
  @payloadcms/next/utilities: 3.9.0
  @payloadcms/payload-cloud: 3.9.0
  @payloadcms/richtext-lexical: 3.9.0
  @payloadcms/translations: 3.9.0
  @payloadcms/ui/shared: 3.9.0
  react: 19.0.0
  react-dom: 19.0.0
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-5 (2024-12-03T10:26Z)
  Available memory (MB): 16384
  Available CPU cores: 4
```

**Comment by akhrarovsaid** [comment]
Hey @CCoffie,

Can you try passing `req` to your `payload.update` call? [See here for info](https://payloadcms.com/docs/local-api/overview#transactions)

**Comment by CCoffie** [comment]
Ah, yep that fixed it! Thanks for the help. Should the `req` parameter always be passed?

**Comment by akhrarovsaid** [comment]
@CCoffie Generally yes, wherever you have access to a req you want to pass it in. It's highly recommended at least.
