### ISSUE TITLE
(UI) Hidden fields show up in the columns filter selector

### ISSUE THREAD

**Issue by paulpopus** [payloadcms/payload#10261]
### Describe the Bug

Fields with `admin.hidden: true` still show up in the columns selector

### Link to the code that reproduces this issue

-blank-

### Reproduction Steps

Add `admin.hidden`

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

```text
Latest payload
```

**Comment by jacobsfletch** [comment]
Duplicate of #10234

**Comment by paulpopus** [comment]
Closed in favour of ^
