### ISSUE TITLE
Custom admin css file is not loaded

### ISSUE THREAD

**Issue by ciokan** [payloadcms/payload#1050]
# Bug Report

Custom css file is not loaded. I even printed out `getBaseConfig.js` default exported schema to see if my custom file is being referenced (which it was, under the `payload-user-css` alias) but it is not being loaded. In the generated admin HTML I somehow still see the placeholder `custom.css`. The path is right, I tested it with the `cat` command on it.

My config:

```
import {buildConfig} from 'payload/config';
import path from 'path';

import Users from './collections/Users';
import Examples from './collections/Examples';


export default buildConfig({
	serverURL  : 'http://localhost:3000',
	admin      : {
		meta: {
			titleSuffix: '- test',
		},
		user: Users.slug,
		css : path.resolve(__dirname, 'styles.css'),
	},
	collections: [
		Users,
		Examples,
	],
	typescript : {
		outputFile: path.resolve(__dirname, 'payload-types.ts'),
	},
	graphQL    : {
		schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
	},
});
```

Debugged the `config` var on `getDevConfig.js` as well to see if it carries over and my custom path is under the alias as expected. I don't know how `custom.css` placeholder file gets added after this process.

**Comment by MinSomai** [comment]
try this
```js
css: path.resolve(__dirname, './styles.css')
```

this is my current configuration and its working fine.
```js
 admin: {
    user: Admins.slug,
    components: {
      beforeLogin: [BeforeLogin],
      afterDashboard: [AfterDashboard],
      graphics: {
        Logo: Logo,
        Icon: Icon,
      },
    },
    css: path.resolve(__dirname, "./styles/custom.scss"),
  },
  ```

**Comment by DanRibbens** [comment]
I'm not able to reproduce any bugs with the custom css feature. It sounds like your file is making it to webpack from your debugging. That is really all that needs to happen for the admin UI to get the extra styles.

To troubleshoot, what happens if you replace your css file with this? 
```css
.nav__controls:before {
  content: 'custom-css'
}
```

You should then be able to see the text "custom-css", after login, in the bottom corner: 
![image](https://user-images.githubusercontent.com/6434612/188151936-9b85f627-889a-4265-abb4-0079437f508b.png)

I'm not sure how useful this is, but I'd like to at least rule out that it isn't something in your css file. Thanks!

**Comment by DanRibbens** [comment]
I opened a PR to include an e2e test for custom css. You can review those changes to look for any differences between your project and the test changes.

https://github.com/payloadcms/payload/pull/1053/files

**Comment by ciokan** [comment]
I had to delete the `.cache` folder in `node_modules` to have it working. Don't know why webpack persisted the initial files but it did. I'm going to close this one and see of it emerges again somehow. Thanks.

**Comment by DanRibbens** [comment]
> I had to delete the `.cache` folder in `node_modules` to have it working. Don't know why webpack persisted the initial files but it did. I'm going to close this one and see of it emerges again somehow. Thanks.

Webpack cache is the real bug that we need to deal with here. Good catch!
