### ISSUE TITLE
Version 1.0.28 introduces a relationship validation bug

### ISSUE THREAD

**Issue by TomSmedley** [payloadcms/payload#1054]
# Bug Report
Since updating to 1.0.28 I'm no longer able to publish my fields if they have gone from having a relationship to `None`, it reports a validation error when validation isn't present on the field.

## Expected Behavior
It should set the field back to `None` (no value)

## Current Behavior
The error `The following fields are invalid` is shown

## Possible Solution
Downgrade to 1.0.27 until the bug is fixed

## Steps to Reproduce
1. Create a relationship (possibly inside a group on a global as that is my current setup)
2. Set the relationship and save / publish
3. Set the relationship back to `None` and save / publish
4. The error should display as not valid

## Detailed Description
This is in Chrome using Payload version >= 1.0.28

## Note
`None` now sits randomly inside the relationship list rather than at the top meaning that the editor will have to search through the list to look at removing the relationship. Consider having a "x" icon rather than "None" like "hasMany" setting has to clear out the value.

**Comment by MarkAtOmniux** [comment]
Second. However downgrading to 1.0.27 doesn't seem to be the fix.

**Comment by DanRibbens** [comment]
The fix was released in v1.0.32.
