### ISSUE TITLE
UI: Scroll issue with collapsible elements

### ISSUE THREAD

**Issue by Elliot67** [payloadcms/payload#1059]
# Bug Report

Any collapsible elements creates scroll issues on the interface. 

## Steps to Reproduce
1. Gets a page with collapsible elements
2. Collapse all elements
3. Reload the page
4. Expand all blocks (should be bigger than the viewport)
5. Scroll to the bottom

## Detailed Description

The problem seems to occur when first page render height is smaller or equal to a full viewport height (100vh). When expanding an element, the height of the page change but the interface keeps it's initial height `100%` of the `html`/`body`.

In my case : 
- The left sidebar start scrolling instead of sticking at the top
- The "Add block" popup gets an incorrect position blocking the user from selecting a block

https://user-images.githubusercontent.com/45725915/188281206-481e717e-dc25-4c26-9c6e-6361cd5aa777.mp4

**Comment by Elliot67** [comment]
Another note : The scroll appear/disappear when opening/closing collapsible element which gives a really bad UX, especially when you want to double click on the right arrow of the element topbar (see screen).
The sidebar moves to the left because of the scrollbar, which reduce the width of the main block and shift the arrow the left.

![image](https://user-images.githubusercontent.com/45725915/188281638-aca53ab6-6ee6-4e27-b889-03b27331b5d1.png)

**Comment by jmikrut** [comment]
Hey @Elliot67 — this has been fixed! Thank you for the report. Going to be released in an upcoming version shortly!
