### ISSUE TITLE
Problem with latin characters in labels and graphql mutation

### ISSUE THREAD

**Issue by anthonyivol** [payloadcms/payload#1064]
# Bug Report

When executing a graphql mutation I get an error : 
`"message": "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"Paramètres\" does not."`

## Expected Behavior

No error

## Current Behavior

Error

## Possible Solution

I think labels should be used only for display, or should be normalized.

## Steps to Reproduce

1. `npm i payload-webp` 
2. payload.config.ts : 

 ```
import { buildConfig } from 'payload/config';
import Page from './collections/Page';
import Media from './collections/Media';
import Settings from './globals/Settings';
import webp from "payload-webp";

export default buildConfig({
  serverURL: process.env.PAYLOAD_PUBLIC_SERVER_URL,
  
  plugins: [
    webp()
  ],
  admin: { webpack: (config) => config }, /** need this for webp plugin to works */

  collections: [
    Page,
    Media,
  ],
  globals: [
    Settings,
  ],
});
```
Settings.ts :
```
import { GlobalConfig } from 'payload/types';
import { Type as MediaType } from '../collections/Media';

export type Type = {
  location: string
  email: string
  phone: string
  logo?: MediaType
}

const Settings: GlobalConfig = {
  slug: 'settings',
  label: 'Paramètres',
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'logo',
      label: 'Logo principal',
      type: 'upload',
      relationTo: 'media',
      required: true,
    },
    ...
};

export default Settings;

```
4. Go to http://localhost:3000/api/graphql-playground
5. Execute this mutation :
```
mutation {
  WebpRegenerate(slug: String, sort: String) {
    currentFile
    current
    total
  }
}
```

## Detailed Description

I have looked into the payload-webp plugin repo but didn't find something using collections, globals, or fileds labels, so it is more a bug related to payload.

thanks !

**Comment by denolfe** [comment]
Thanks for the report @anthonyivol. Because GraphQL does not support accented characters, it looks like we'll need to do some additional sanitization on our end. We'll look into making that change.

**Comment by anthonyivol** [comment]
Thanks !
