### ISSUE TITLE
Non-latin (cyrrillic) symbols not supported?

### ISSUE THREAD

**Issue by yagee** [payloadcms/payload#1073]
# Bug report
Hi! 
I have 2 similar bugs, so I combine it in one issue:

1. Filter not working with records written non-latin symbols.
2. Can't reference records written with non-latin symbols from relationship collection

## Steps to Reproduce problem 1
1. Create a collection with text type fields.
2. Create record using Cyrillic symbols `Тест ` and Latin symbols `Test`
3. Type in filter field `Тест `- record didn't appear. But if you type `Test `- all is good. 

## Steps to Reproduce problem 2
4. Create new collection, with relationship type field, set relation to collection above.
5. When you try to create new record in this collection - you are unable to pick `Тест` from previous collection, only `Test`

## Detailed Description
Node: v16.15.0
Payload: 1.0.32
Mongo: 3.6.8 and 4.4.4

Creating two records in Tags collection:
![01](https://user-images.githubusercontent.com/1481199/188676869-c84571f7-60e6-42f7-9a23-8d5135966c7b.png)

Filtering `Test`:
![02](https://user-images.githubusercontent.com/1481199/188676893-321621d3-28b3-4f5d-8148-1d1f13b8d904.png)

Filtering `Тест`:
![03](https://user-images.githubusercontent.com/1481199/188676906-cb15d442-1f6e-4579-a0e3-e9ffc60f90a3.png)

Trying to refer to Tags collection from Example collection:
![04](https://user-images.githubusercontent.com/1481199/188676920-9934c378-54d7-460b-9e82-b64cc7b3b201.png)

**Comment by denolfe** [comment]
Thanks for the report @yagee. This is related to how Cyrillic characters work with regular expressions. I've opened a PR to support Cyrillic characters with like queries.

**Comment by yagee** [comment]
Thank you!

**Comment by denolfe** [comment]
Released in [v1.0.33](https://github.com/payloadcms/payload/commit/0f671b1b354fd2aa3392b02da2ff4d6184f48858)
