### ISSUE TITLE
Upload filenames are saved with broken encoding

### ISSUE THREAD

**Issue by lksfrn** [payloadcms/payload#1098]
# Bug Report

When someone uploads a file with special filename, its name is being saved with wrong encoding. For example: `ščžříá řá šíř pplůúůú.jpg` is saved as `Å¡Ä\x8DÅ¾Å\x99Ã­Ã¡ Å\x99Ã¡ Å¡Ã­Å\x99 pplÅ¯ÃºÅ¯Ãº.jpg`. The former is sample of my alphabet :smile: 

## Expected Behavior

Save upload filename name as it should be.

## Current Behavior

It saves wrong filename, but it works when I try to access it through URL.

## Possible Solution

I do not know, how to fix it. In fact, I do not know what causes this.

## Steps to Reproduce

1. create Payload app
2. create upload with some weird characters

## Detailed Description

I can simulate the similar result with, but it is not the same

```js
Buffer.from('ščžříá řá šíř pplůúůú.jpg', 'utf-8').toString('latin1')
```

**Comment by lksfrn** [comment]
Is there at least a way of renaming the file before saving? I tried request handler, but it did not help.

**Comment by Shednandez** [comment]
discuss issues

**Comment by jmikrut** [comment]
Hey @lksfrn — this is a great question. But there's an easy solution! Payload exposes [`config.upload`](https://payloadcms.com/docs/upload/overview#payload-wide-upload-options) options which allow you to customize the options that Payload uses behind-the-scenes while uploading files. Being that Payload uses `busboy`, you can pass any options that `busboy` supports. With those options, you can keep `utf8` filename encoding.

Set up your config like this:

```js
export default buildConfig({
  upload: {
    defCharset: 'utf8',
    defParamCharset: 'utf8',
  },
  collections: [
    // Your collections here
  ],
  // etc
});
```

And you're golden! Love when stuff is easier than it seems!

**Comment by lksfrn** [comment]
Thank you very much, it works! 😍
