### ISSUE TITLE
Admin dashboard tile links to undefined Global entity

### ISSUE THREAD

**Issue by r0skar** [payloadcms/payload#1117]
# Bug Report

The admin dashboard tile that links to a global entity is broken. It links to `/admin/globals/undefined`

![image](https://user-images.githubusercontent.com/33655345/189839530-7d41415a-6f51-4179-b4bc-bc1ad030c1f0.png)

## Expected Behavior

The tile should link to the global entity `/admin/globals/intro`

## Steps to Reproduce

1. Open dashboard
2. Click on a global group
3. Observe 404 error

## Detailed Description

This started to happen with Payload 1.1.0 and the global group support (the global entity existed before). Note: the link in the sidebar works as expected.

**Comment by DanRibbens** [comment]
Taken care of in v1.1.1.
Thanks for the detailed report!
