### ISSUE TITLE
Collapsible with condition will crash the site

### ISSUE THREAD

**Issue by noctisyeung** [payloadcms/payload#1118]
# Bug Report

When I add the condition inside the `collapsible` type, the whole page will throw error and broken

## Expected Behavior

When I add the condition inside the `collapsible` type, the condition should work and the page won't crash.

## Current Behavior

When I add the condition inside the `collapsible` type, the whole page will throw error and broken

## Steps to Reproduce

1. Create a `collapsible` type in the fields
2. Add a `text` field inside the `collapsible` field's fields array
3. Add the admin property with condition property in `collapsible`
4. Return true/false in the condition property
5. Refresh and the page will crash

## Detailed Description

```
 "dependencies": {
    "payload": "^1.1.0",
    "dotenv": "^8.2.0",
    "express": "^4.17.1"
  }
```

#### Error from chrome:
![Screenshot 2022-09-13 at 3 40 20 PM](https://user-images.githubusercontent.com/18361072/189840629-31b65bf4-5efe-46c5-bc1e-dc750608dd15.png)

#### Sample code Fragment
```
{
      label: "Page Modules V3",
      type: "collapsible",
      fields: [
        {
          name: "dummy-title",
          label: "Title",
          type: "text",
          required: true,
          localized: true,
        },
      ],
      admin: {
        condition: () => true,
      },
    },
```

**Comment by DanRibbens** [comment]
Thanks for the issue!

https://github.com/payloadcms/payload/pull/1122
Released in v1.1.1
