### ISSUE TITLE
Error when installing `sharp` dependency

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#1134]
# Bug Report

I'm setting up Payload in Amazon Elastic Beanstalk on an arm64 architecture. The instance type is `t4g.medium`. On upload, EB automatically runs `npm --production install`, which fails.

## Expected Behavior

The install should be successful.

## Current Behavior

The following error occurs:

```
npm ERR! code 1
npm ERR! path /var/app/staging/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: Use with glibc 2.26 requires manual installation of libvips >= 8.11.3
```

## Possible Solution

The dependency could be updated or switched with another one?

## Steps to Reproduce

1. Create an AWS environment with a `t4g.medium` instance on an arm64 machine
2. Deploy the minimal Payload CMS starter template
3. See the error in the `/var/log/eb-engine.log` file

## Detailed Description

Here's the OS info:

```
$ cat /proc/version
Linux version 4.14.290-217.505.amzn2.aarch64 (mockbuild@ip-10-0-62-207) (gcc version 7.3.1 20180712 (Red Hat 7.3.1-13) (GCC)) #1 SMP Wed Aug 10 09:52:17 UTC 2022
```

**Comment by denolfe** [comment]
Hey @hdodov, thanks for the report. This appears to be a sharp-specific issue on EB. The workaround is documented on [this Sharp issue](https://github.com/lovell/sharp/issues/3221#issuecomment-1126528844).

**Comment by hdodov** [comment]
@denolfe oh, great! Thanks a lot for taking the time to help me out!
