### ISSUE TITLE
Customizable ID is not working in collapsible

### ISSUE THREAD

**Issue by cmngan** [payloadcms/payload#1143]
# Bug Report

Use Customizable ID inside collapsible is not working. 

Example of Collection Config

```
const Examples: CollectionConfig = {
  slug: "examples",
  admin: {
    useAsTitle: "someField",
  },
  fields: [
    {
      label: "Page Info",
      type: "collapsible",
      fields: [
        {
          name: "id",
          type: "text",
        },
        {
          name: "someField",
          type: "text",
        },
      ],
    },
  ],
};
```

## Expected Behavior
It should use the user input id instead of auto gen

## Current Behavior
It auto generated the id after saved. 

![image](https://user-images.githubusercontent.com/20035088/190943429-ac44a698-97b6-432d-813a-3cd810e6ca2c.png)

**Comment by DanRibbens** [comment]
Currently it is only possible to have a custom ID at a top level on a collection. This is a known limitation. We would consider accepting a PR that allows the custom ID to exist in a row, collapsible or tab with no name assigned.
