### ISSUE TITLE
Server URL is prepended to admin thumbnail path even when custom function is provided.

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#115]
# Bug Report

Just tried out the changes in #98 regarding admin thumbnail.

When using the `collection.upload.adminThumbnail` function, the view will always prepend the custom path provided with serverUrl. Resulting in paths like this:

    http://localhost:3000https://brightvision.fra1.cdn.digitaloceanspaces.com/bv-logo-1.svg

## Expected Behavior

When a custom path is provided, don't prepend it with the Server URL.

## Current Behavior

Adds http://localhost:3000 to the beginning of my paths.

## Possible Solution

Problem is in the Thumbnail component here: https://github.com/payloadcms/payload/blob/master/src/admin/components/elements/Thumbnail/index.tsx#L34

## Steps to Reproduce
1. Add new upload collection
2. Upload a file
3. Return a string from `adminThumbnail`
4. Check the path of the resulting admin thumbnails in both the listing and the view

**Comment by jmikrut** [comment]
Hey @richardvanbergen — good find. Thanks a ton.

Just merged in a fix, deploying `0.5.0` now!
