### ISSUE TITLE
Uploading xls file changes extension

### ISSUE THREAD

**Issue by TimLanzi** [payloadcms/payload#1156]
# Bug Report
In one of my upload types, when I upload a .xls file, it gets renamed to [filename].cfb after I save. Does not happen with .xlsx files. Seems to be renaming files based on mime-type.

## Expected Behavior
I expect the file name/extension to remain the same after I save.

## Current Behavior
The extension is converted to .cfb after I save.

## Steps to Reproduce

1. Create a basic upload type. Here is mine for reference:
```ts
import { CollectionConfig } from 'payload/types';
import path from "path";

const Data: CollectionConfig = {
  slug: 'data',
  admin: {
    useAsTitle: "filename",
  },
  upload: {
    staticURL: '/data',
    staticDir: path.resolve(__dirname, '../../data'),
  },
  fields: [],
};

export default Data;
```
2. Attempt to upload any .xls file in this collection
3. Save the collection entry. You should now see the file has a .cfb extension.

## Detailed Description
- Node.js version 16.15.0
- TypeScript version 4.1.3
- Payload version 1.1.3
- More-or-less a fresh Payload install. I have only added collections, fields, and utility functions.
- My payload.config.ts:
```ts
import { buildConfig } from 'payload/config';
import path from 'path';
import Users from './collections/Users';
import Media from './collections/Media';
import CatalogEntry from './collections/CatalogEntry';
import DataSource from './collections/DataSource';
import Data from './collections/Data';

export default buildConfig({
  serverURL: 'http://localhost:3000',
  admin: {
    user: Users.slug,
  },
  collections: [
    Users,
    Media,
    Data,
    CatalogEntry,
    DataSource,
  ],
  typescript: {
    outputFile: path.resolve(__dirname, 'payload-types.ts'),
  },
  graphQL: {
    schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
  },
});

```

**Comment by ahmedHusseinF** [comment]
I think we are dependent on the library `file-type` to detect a file's extension from looking at the buffer.

It seems they don't plan on supporting old types including `.xls` mentioned [here](https://github.com/sindresorhus/file-type#supported-file-types).

This [issue](https://github.com/sindresorhus/file-type/issues/349) in file-type github might be interesting.

**Comment by DanRibbens** [comment]
Good digging @ahmedHusseinF, you are correct.

The intention of our upload code was to fallback to preserving the file extension from the uploaded when the mime-type could not be detected from this package. That is what this line of code was meant to do:

https://github.com/payloadcms/payload/blob/051a0fad84df6c624745465a35a4af6f53759a23/src/uploads/uploadFile.ts#L81

Unfortunately it must be that the library is giving back the ext `cfb`. Based on their readme I had assumed this would return `undefined` instead. This is working for `svg` files, so I'm unsure why that library is returning `cfb` in this case.

Some ideas on how to fix this are: 

- Skip the file extension change and simply preserve the extension as it was when uploaded. That solves this problem, but wouldn't help in the case of having incorrect mimetypes. 
- Maintain a blacklist of extensions that this library doesn't work with and bypass only those few.

**Comment by jmikrut** [comment]
Hey @ahmedHusseinF and @TimLanzi — this is now closed and will be released in our next minor version, coming shortly!
