### ISSUE TITLE
Adding multiple relationships doesn't reset modal form and clears form events.

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#118]
# Bug Report

There's a couple of wonky behaviours around rich text relationships. I think they're related so I'm putting them as one issue. 

It seems to be that if you add a relationship, select somewhere else, and add another relationship:

1. The form is still populated with the previous values. 
2. The events that fetch the relationships are no longer bound to the select box.
3. The "Add relationship" button submits the main form rather than inserting a new relationship inline.

It's hard to explain so I've included a screen recording.

https://user-images.githubusercontent.com/3854592/112930401-2ab9cf00-9155-11eb-9df0-1b27f9f72e11.mov

## Steps to Reproduce

1. enableRichTextRelationship on a couple of different modules.
2. Try to insert a relationship, should be OK
3. Try to insert another.
4. See issues described above.

**Comment by jmikrut** [comment]
Hey @richardvanbergen — thank you for this. We have fixes applied to issues 1 and 2, but 3 we are still working on.

Going to continue to chase it down. It has to do with an inner working of React concerning event bubbling out of Portals:

https://github.com/facebook/react/issues/19637

Wild stuff. Will report back shortly as now that we have identified the issue, we will likely be able to implement a workaround and get all 3 issues fixed at once!

**Comment by richardvanbergen** [comment]
It's ok I understand how sometimes it can be weird esoteric interactions with the core framework. I've had plenty of those myself 😅

**Comment by jmikrut** [comment]
This has all been resolved in #120! Deploying `0.5.2` as we speak!
