### ISSUE TITLE
Save as draft for Globals not persisting as expected

### ISSUE THREAD

**Issue by elmage** [payloadcms/payload#1184]
# Bug Report

## Expected Behavior
When I click on "Save Draft" on a global, the draft is saved and the admin form is populated with the draft data.
It should also be possible to retrieve the draft via the api by appending `?draft=true` to the endpoint url.

## Current Behavior
When I click on "Save Draft" on a global, a version of the draft is saved and the admin form is populated with previously published data or the form is blank if there is no previously published version.
appending `?draft=true` to the endpoint url still retrieves the previously published version.

## Steps to Reproduce
1. Create a Global and/or navigate to an existing global in the Admin
2. populate the fields and click "Save Draft"
3. Try to retrieve the draft data using the URL provided at the bottom right on the screen

## Detailed Description
When I click on "Save Draft" on a global, a version of the draft is saved and the admin form is populated with previously published data or the form is blank if there is no previously published version.
appending ?draft=true to the endpoint url still retrieves the previously published version.

Note: I can see all draft versions under `Versions` and I can restore a draft version that automatically publishes.

Payload version: 1.1.4

**Comment by jmikrut** [comment]
HeY @elmage — thank you very much for the report. This was just fixed and will be released in our next patch version due out shortly!

James
