### ISSUE TITLE
Unable to customize admin CSS in dev mode

### ISSUE THREAD

**Issue by elmage** [payloadcms/payload#1213]
# Bug Report

I followed the [docs](https://payloadcms.com/docs/admin/customizing-css) and tried customizing the admin css but it doesn't work in dev mode. 
I Wasn’t able to override the variables listed as override-able. 
My styles weren’t even showing up at all in my devtools.

But my styles are applied when I build. 

Payload version: 1.1.4

**Comment by jmikrut** [comment]
Hey @elmage - can you try to do `rm -Rf node_modules/.cache` and then restart your server?

I'm willing to bet that this is related to cache.

Give that a shot!

**Comment by elmage** [comment]
> I'm willing to bet that this is related to cache.

You were absolutely right!

**Comment by gregwhitworth** [comment]
I'm hitting this on a Windows machine and while the above unix command won't work I went ahead and deleted everything in the `node_modules` folder and restarted and it's still not applying. Any other suggestions?

**Comment by gregwhitworth** [comment]
@jmikrut friendly ping on the above, there is no .cache file under `node_modules` and I do have hidden files enabled and VS Code shows `.` files so it isn't that. Any ideas?
