### ISSUE TITLE
Polyfill error in imageKit plugin setup

### ISSUE THREAD

**Issue by shubhamwebdesign** [payloadcms/payload#1265]
# Bug Report
![imagekit_polyfill_error](https://user-images.githubusercontent.com/68468708/196051186-3af57b8c-b058-4b3d-8f4d-9079103b3eab.png)

Getting polyfill error in imageKit plugin setup

## Current Behavior
Polyfill error

## Expected Behavior
Image should be uploaded to imageKit

## Possible Solution
Not sure

## Steps to Reproduce

1. install he payload imagekit plugin:  npm i payloadcms-plugin-imagekit
2. It was giving an error that imageKit module not found so i installed that: npm i imagekit
3. add the confiig as instructed on plugin's github repo: https://github.com/novanda1/payload-imagekit
4. After saving got polyfill error in console

Payload version: 1.1.15
imageKit version: 4.1.1
payloadcms-plugin-imagekit version: 0.2.3

Github Link: https://github.com/shubhamwebdesign/devstack_project_crm/tree/imagekit

**Comment by jmikrut** [comment]
Hey @shubhamwebdesign — this is an issue with that plugin and not with Payload. It appears that there is a Node package being imported which is not compatible with browsers, and should be removed using Webpack aliases [as seen in the docs here](https://payloadcms.com/docs/admin/webpack#aliasing-server-only-modules). 

You should re-open this issue and link to the above docs on that repo itself!

**Comment by shubhamwebdesign** [comment]
Opened the issue on the plugin repo - thanks @jmikrut for the quick response
