### ISSUE TITLE
'indexSortableFields' does not work

### ISSUE THREAD

**Issue by jakkan** [payloadcms/payload#1271]
# Bug Report

The documentation lists `indexSortableFields` as an option: https://payloadcms.com/docs/configuration/overview. This option is recommended as a fix for Azure Cosmos: https://payloadcms.com/docs/production/deployment.

## Current Behavior

The option does not cause fields to be indexed.

## Expected Behavior

The option causes all fields to be indexed.

## Possible Solution

All application logic related to the option was removed in: https://github.com/payloadcms/payload/pull/942

**Comment by DanRibbens** [comment]
Confirmed, this is a regression. We are working on a fix. Thanks for reporting @jakkan!

**Comment by DanRibbens** [comment]
This was merged and deployed in v1.1.16.
