### ISSUE TITLE
Local API access

### ISSUE THREAD

**Issue by chladog** [payloadcms/payload#1273]
# Documentation Issue

Docs state info regarding access quite confussing and I believe invalid:
```
overrideAccess | Skip access control. By default, this property is set to false.
user | If you re-enable access control, you can specify a user to use against the access control checks.
```
```
Note:
By default, all access control checks are disabled in the Local API, but you can re-enable them if you'd like, as well as pass a specific user to run the operation with.
```

It's not clear how to actually re-enable the access control in local API. 
What I understood initially is that I just need to pass user object to ```user``` prop, as overrideAccess is said to be ```false``` by default, however this doesn't re-enable it. I also have to explicitly set ```overrideAccess: false``` along with user object.

So is overrideAccess ```true``` by default ?

**Comment by jmikrut** [comment]
Hey @chladog — this is correct. We'll work in some clarification to the docs. But your assumptions are absolutely accurate.

I'll close this once docs are clarified!

**Comment by jmikrut** [comment]
Hey @chladog I just updated the docs to be accurate here. Thanks for the report!
