### ISSUE TITLE
richtext relationship element bugs

### ISSUE THREAD

**Issue by zhounewz** [payloadcms/payload#1276]
# Bug Report

## Current Behavior

bug1 and bug2: 
<img width="1537" alt="image" src="https://user-images.githubusercontent.com/16400882/196583388-5a78f997-eda8-44ba-82a3-893e70764cc3.png">

bug3: When Relation To is changed, the behavior of the new add button does not follow the change.

https://user-images.githubusercontent.com/16400882/196588016-0467326f-595c-4dc9-94ab-910861bbbf7b.mov

[test link url](https://demo.payloadcms.com/admin/collections/posts/634f5a2120f2c83732fa2ca2)

## Expected Behavior

1. Whether to insert blank lines between consecutive relationships, support configuration, it is best to have no blank lines by default.
2. If the content of the relationship is too long, truncate the display or wrap.
3. When Relation To is changed, the behavior of the new add button should follow the change.

## Steps to Reproduce

1.
4.
5.
6.

**Comment by 0ahsan1** [comment]
can you assign me this bug i can solve

**Comment by zhounewz** [comment]
@denolfe Can you help me assign this issue to 0ahsan1， thanks~

**Comment by jmikrut** [comment]
Done! Thanks guys!

**Comment by jacobsfletch** [comment]
Hi @zhounewz, this has been fixed in PR https://github.com/payloadcms/payload/pull/1668
