### ISSUE TITLE
Default depth doesn't apply to GQL fields

### ISSUE THREAD

**Issue by chladog** [payloadcms/payload#1286]
# Bug Report

Setting default ```depth``` in payload config doesn't apply to relevant fields in GQL queries, like ```richtext``` or ```upload```.

To make it work we have to explicitly set depth as a field argument on EVERY field of the relevant type. **Which is lengthy and prone to forgetting when writing additional queries.**

First I thought of FE solution to this, unfortunatelly I did not find any way to apply _default field arguments_ in Apollo client.

## Current Behavior

The prop doesn't alter GQL behavior.

## Expected Behavior

Should apply to all gql fields that take ```depth``` field. Or introduce additional prop ```gqlDepth```, keeping original prop applied to REST only. Any argument passed in query would override the default option.

payload@1.1.15

**Comment by jmikrut** [comment]
Hey @chladog thank you for the report! You're right. But I actually only see that this applies to the `richText` field, right? I fixed just now in that scenario. It will be released shortly in an upcoming patch version.

Thanks again!

**Comment by chladog** [comment]
Hi @jmikrut 
perfect!
You are right, sorry I confused the topic with ```richtText / upload``` as I meant to say ```upload``` and ```relationship``` elements IN the ```richText```.
