### ISSUE TITLE
Apply both bold and italic to content, display only bold

### ISSUE THREAD

**Issue by zhounewz** [payloadcms/payload#1290]
# Bug Report

## Current Behavior

![image](https://user-images.githubusercontent.com/16400882/197482892-bad960ac-5191-47f0-bdbb-c2db2fb52e9d.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jmikrut** [comment]
Hey @zhounewz — thank you for the report! This is now fixed and will be published shortly.
