### ISSUE TITLE
bug: `value` can still be undefined for `textarea` and `password` when performing minLength and maxLength validation.

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#13]
## Expected Behavior

Don't throw errors 😉

## Current Behavior

When creating a new page the `value` in the validation for `minLength` can throw an error when trying to access `value.length`.

## Possible Solution

same fix needs to be applied as for text in this commit https://github.com/payloadcms/payload/commit/5e60b8617e715378831f10b90dedd017ed8d4a8c

## Steps to Reproduce

1. Create field with textarea type and min/max length validation
2. Create new document
3. See error

**Comment by denolfe** [comment]
@richardvanbergen Thanks for the report 👍 Fix incoming
