### ISSUE TITLE
Adding the first items to an empty [blocks] field 

### ISSUE THREAD

**Issue by ARkrOSClou** [payloadcms/payload#1307]
# Bug Report

## Current Behavior

an error occurs when adding the first blocks in a field with the "blocks" type

## Steps to Reproduce

1. clear any blocks field
2. reload page
3. try adding any block and save

## Detailed Description

```
[12:39:12] ERROR (payload): CastError: Cast to embedded failed for value "1" (type number) at path "blocks" because of "ObjectParameterError"
    at model.Query.exec (***\node_modules\mongoose\lib\query.js:4789:21)
    at model.Query.Query.then (***\node_modules\mongoose\lib\query.js:4888:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

v1.1.18

**Comment by bencun** [comment]
I've noticed similar behavior. Usually blocks using type: 'upload' are creating issues for me.
So the behavior goes like this:
- no blocks added
- add a block or multiple blocks
- click Publish (using versions here)
- get an error from payload that looks very similar to the one in the original bug report but my path is "content" not "blocks", same thing, though.

This is the outgoing JSON:
```json
{
  "title": "My Test Page!",
  "parent": null,
  "content": 1,
  "_status": "published",
  "meta": {
    "title": "My Test Page!"
  },
  "breadcrumbs": 0
}
```

Afterwards I make any kind of change (type a letter into one of the fields in the block, for example), click "Publish" and it works!
Outgoing JSON now looks like this:
```json
{
  "title": "My Test Page!",
  "parent": null,
  "_status": "published",
  "meta": {
    "title": "My Test Page!"
  },
  "breadcrumbs": 0,
  "content": [
    {
      "id": "635d33d958d7a127019366a6",
      "media": "635c1a35121da619bea5924d",
      "layout": "imageLeft",
      "content": [
        {
          "children": [
            {
              "text": "Test!!!"
            }
          ]
        }
      ],
      "blockType": "imageContent"
    }
  ]
}
```

**Comment by bencun** [comment]
Can confirm this happens in 1.1.16, 1.1.17 and 1.1.18.

**Comment by jmikrut** [comment]
Hey all,

Thank you very much for the detailed info here. This was indeed due to implementing the `useContextSelector` changes that we recently pushed, but we've got a fix out now. Will be published ASAP!
