### ISSUE TITLE
[15:52:53] ERROR (payload): APIError: No User when i logout

### ISSUE THREAD

**Issue by Giovni** [payloadcms/payload#1309]
# Bug Report

## Current Behavior

[15:52:53] ERROR (payload): APIError: No User

When i logout from admin panel, an error appears on the console
[15:52:53] ERROR (payload): APIError: No User

## Steps to Reproduce

1.
2.
3.
4.

**Comment by DanRibbens** [comment]
Just logging out shouldn't send that error. There is likely another request happening after you logout. Is there an extra tab open or something else making an additonal request?

Can log the incoming request out to know what request is being made to throw the error?

**Comment by Giovni** [comment]
@DanRibbens i have the same error
![Sin título](https://user-images.githubusercontent.com/96594306/199634336-804ada75-3f20-4cfa-ad9a-e67fb69c0fe8.png)

**Comment by mrobst** [comment]
I've got this error too in production on a site I haven't touched for a month. I can login but cannot save any content, all the requests throw 401 or 403. I can read content OK. Restarted the server and the database but no change. Cleared cookies etc. Will investigate further tomorrow but haven't found a way round it yet. 

<img width="790" alt="image" src="https://user-images.githubusercontent.com/20040193/201443306-e4d2d860-ddfd-4ec2-8999-cb08fa75f44d.png">

**Comment by jmikrut** [comment]
Hey @Giovni @mrobst — thank you for the reports! 

I just found a small optimization in the admin UI and tweaked accordingly. This did rectify a duplicative `logout` operation, so this should be resolved.

It will be released shortly!

**Comment by mrobst** [comment]
I've updated to latest version with the fix but it hasn't resolved my issue yet. After logon as soon as I go into a collection I get a 401 on /api/_preferences/collection-name . None of the collections will save. Will investigate further, any pointers on what to check appreciated

**Comment by jmikrut** [comment]
OK - this is a different issue then. Is this happening locally, or in production?

**Comment by mrobst** [comment]
Production - Digital Ocean App platform - shall I open a different issue for it?

**Comment by mrobst** [comment]
I cleared cookies and logged in. New cookie is set ok. No error. Then navigated to the first collection and I get a 401 error from /api/_preferences/categories-list with this log

<img width="781" alt="image" src="https://user-images.githubusercontent.com/20040193/201496432-0c962205-5592-413b-8180-892957d0663e.png">

**Comment by Erudition** [comment]
> Hey @Giovni @mrobst — thank you for the reports!
> 
> I just found a small optimization in the admin UI and tweaked accordingly. This did rectify a duplicative `logout` operation, so this should be resolved.
> 
> It will be released shortly!

Does this mean it was in 1.2.0 (2 days ago?)

I still get the "No User" APIError whenever I try to log out (via graphql mutation)

**Comment by saaymeen** [comment]
I can observe a similar behaviour with payload@
