### ISSUE TITLE
Search In "Select Existing" Modal Doesn't Always Update

### ISSUE THREAD

**Issue by KGZM** [payloadcms/payload#1311]
# Bug Report

## Current Behavior

1. Open select the "Select Existing" modal to search for an existing upload.
2. Enter a search term "cat" (or other search term) and see the filtered results. 
3. Delete search term. 
4. Continue to see filtered results.

Typing a space character into the search field and hitting enter will again show the unfiltered results but this is very quirky and confusing to users.

## Expected Behavior
1. Open select the "Select Existing" modal to search for an existing upload.
2. Enter a search term "cat" (or other search term) and see the filtered results. 
3. Delete search term. 
4. See unfiltered results again. 

## Possible Solution

I would suspect this has something to do with a truthiness check on an empty string to determine if there is content in the search field and thus if the search should be sent to the server _but_ things do seem to work correctly in the list view for collections with uploads. I don't know how much overlap there is between the two implementations to say for sure.

## Steps to Reproduce
☝🏿 See above.

## Detailed Description
Versions:
Payload: 1.1.18
Browser: Chrome 106

**Comment by jmikrut** [comment]
Hey @KGZM — thank you for the report! This is now fixed. Will be published shortly.
