### ISSUE TITLE
Reordering Blocks Doesn't Enable The Save Button

### ISSUE THREAD

**Issue by KGZM** [payloadcms/payload#1314]
# Bug Report

## Current Behavior

Going into and changing the order of blocks in a block field without other changes doesn't seem to mark the record as having been edited.

## Expected Behavior

Reordering blocks is a meaningful change and should be sufficient to enable saving.

## Steps to Reproduce

1. Visit a record withs a blocks field in the admin UI
2. Reorder the blocks by dragging and dropping.
3. Make no other changes.
4. Notice that you can't save the reordering.

## Detailed Description

Payload version: 1.1.18

**Comment by bencun** [comment]
Can confirm this bug on Payload 1.1.18
