### ISSUE TITLE
slugs in camelCase throws error

### ISSUE THREAD

**Issue by MoSattler** [payloadcms/payload#1316]
# Bug Report

When using a camelCase slug, I get this error
>  TypeError: Cannot read properties of undefined (reading 'graphQL')

When changing it to kebab-case it works fine though.

## Steps to Reproduce

1. Try adding a collection with a kebab case slug

## Detailed Description

payload@1.1.4

**Comment by ronan18** [comment]
I haven't experienced this type error, however I have experienced errors creating relationships to collections with camelCase: #1306

**Comment by denolfe** [comment]
#1322 was reverted by #1325  to allow for more testing.
