### ISSUE TITLE
Block selection UI popup positioning issues related to the window width

### ISSUE THREAD

**Issue by bencun** [payloadcms/payload#1318]
# Bug Report

The UI component showing a block selection popup doesn't display properly depending on the window width.

## Current Behavior

Position of the pop-up is wrong on certain screen widths.

## Expected Behavior

Pop-up placement should be correct.

## Possible Solution

Not aware of how it works in the codebase ATM.

## Steps to Reproduce

1. Create at least 14 blocks (in my case that's the number).
2. Open the Blocks UI and start resizing the browser window.

## Detailed Description
Demonstration of the issue:
![kj9lStwXr9](https://user-images.githubusercontent.com/15714548/198881849-dcb451a1-24ae-451d-ad1b-3821f1f138fc.gif)

**Comment by DanRibbens** [comment]
It doesn't look like a sizing issue to me. Instead the breadcrumb nav should have a lower z-index than the tooltip component that opens for the blocks menus.

**Comment by bencun** [comment]
Did you notice how the UI "jumps" around when resizing in the screen recording? I don't think it's a z-index issue, why would the UI change its position only because of the z-index? I may be missing something, but I'd be glad to dig in and try fixing it

**Comment by DanRibbens** [comment]
The tooltip tries to find the most ideal position between going above or below the element it opens from. The resize jumping situation is atypical and doesn't seem like a concern to me.

I get that it might seem odd, but how often are you really resizing your viewport and needing that consistency?

To me the bigger problem is seeing that breadcrumb over the menu cutting off what the user should be able to interact with.

**Comment by bencun** [comment]
That's true but it's not about resizing but the inconsistent behavior where the Popup seems to be jumping on every different screen width, as if the calculations are off.
I was looking at the source of the Popup and wanted to try fixing the calculations that apply top/bottom classes onto the tooltip but I have no idea how to get the development version of the Payload frontend up and running, I was unable to find anything in the docs. Any pointers? I'd love to contribute.

**Comment by DanRibbens** [comment]
Have you read the contributing doc in the repo?

https://github.com/payloadcms/payload/blob/master/contributing.md

After you fork and pull down the repo, you can run `yarn dev fields` which has a config for blocks ready to roll. Open localhost:3000 and login with the test credentials:
dev@payloadcms.com // test.

If you have a fix we will gladly review your PR.

Thanks!

**Comment by bencun** [comment]
I did but that doc is very confusing TBH. I think I ran `yarn dev admin` (or some other command), got some tests running but no dev server of any kind spun up, so I figured it's just a test setup (although I do admit that didn't make sense).

Thanks, I'll be looking at it asap

**Comment by jmikrut** [comment]
OK I've done some digging here and figured out what the problem is.

Your viewport does not have enough room either above NOR below for the popup to appear appropriately. When you resize your window, the popup looks for the best it can render, and it considers neither great. So it pops back and forth between top and bottom.

I've gone ahead and improved the logic here to resolve this flickering.

One thing though, regarding the sticky positioning: that could get tricky and the UX could start to get messy very quickly. I think in the future we might consider more of a modal pattern for the "block selector" specifically, as it's a bit larger, but for now, I think that my fix improves this well enough.

Will be released shortly. Let me know what you think!

**Comment by bencun** [comment]
The new behavior is more consistent and there's no more flickering, looks better to me!

**Comment by JarrodMFlesch** [comment]
> I did but that doc is very confusing TBH. I think I ran `yarn dev admin` (or some other command), got some tests running but no dev server of any kind spun up, so I figured it's just a test setup (although I do admit that didn't make sense).
> 
> 
> 
> Thanks, I'll be looking at it asap
> 
> 
> 
> EDIT: Got it running, it's too late for me to be looking at it now but I at least realized what you were talking about. Since this actually seems to be the desired behavior here (instead of the popup being "sticky" when the user scrolls past the popup) then modifying the `z-index` would result in a very ugly overlap with the nav.
> 
> 
> 
> A suggested "fix" would be to actually change the behavior of the popup to be sticky and never leave the viewport (and also z-index should be fixed in that case). This would work much better for popups that have a lot of blocks to display.

Hey @bencun! Glad @jmikrut was able to resolve your issue. 

I would love to know what part of the contributing doc was confusing to you? We can improve it to make it more clear for others in the future. Any feedback would be amazing!

**Comment by bencun** [comment]
The entire [code](
https://github.com/payloadcms/payload/blob/master/contributing.md#code)
section is barely understandable, it speaks of testing while it doesn't
really touch on spinning up the development environment at all. Some of the
commands do seem to spin up tests only, some actually spin up the
development environment of that specific part of the Payload.
