### ISSUE TITLE
Frontend hard-crash (and/or only errors logged to console in other cases) when adding multiple new blocks when there are no previously added blocks

### ISSUE THREAD

**Issue by bencun** [payloadcms/payload#1321]
# Bug Report

I believe this to be related to #1307 and similar issues that I've experienced myself.

The issue is reproducible in `1.1.17` and `1.1.18` and **does not** occur on `1.1.16` and lower so something must've been broken in the meantime.

The issue does not occur if you do the following:
1. Add a single block
2. Save
3. Keep adding blocks
...so, it only happens when there are zero blocks to start with.

## Current Behavior

Adding multiple blocks in a new collection entry when there are no previously added blocks basically crashes the frontend.

## Expected Behavior

Adding multiple blocks should work fine.

## Possible Solution

Check what the behavior was in 1.1.16 since this works properly there and what broke it in the meantime.

This [commit ](https://github.com/payloadcms/payload/commit/c929725dd565de08871dad655442ee9ac4f29dd5) by @jmikrut  looks like it _might have_ introduced the issue. Didn't have the time to delve into it, unfortunately, as I'm not yet familiar with the codebase.

## Steps to Reproduce
Same as #1307

## Detailed Description
Recording of the issue:
![chrome_LtKP0K9wPJ](https://user-images.githubusercontent.com/15714548/198901954-ee2aaeb1-4c02-4051-ae29-44294747965d.gif)

Console output:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'disableFormData')
    at reduceFieldsToValues.js:7:1
    at Array.forEach (<anonymous>)
    at reduceFieldsToValues (reduceFieldsToValues.js:6:1)
    at WithCondition (index.js:45:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
```

The provided screen recording is using the forms plugin but I have reproduced this with my own custom fields and blocks - no hard crash but the error still looks very similar:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disableFormData')
    at reduceFieldsToValues.js:7:1
    at Array.forEach (<anonymous>)
    at reduceFieldsToValues (reduceFieldsToValues.js:6:1)
    at index.js:229:59
    at validateField (index.js:72:1)
    at index.js:89:1
    at useThrottledEffect.js:8:1
```

**Comment by jmikrut** [comment]
Hey all,

Thank you very much for the detailed info here. This was indeed due to implementing the `useContextSelector` changes that we recently pushed, but we've got a fix out now. Will be published ASAP!
