### ISSUE TITLE
hasMany relationship input does not fetch results as you type and only fetch results on scroll.

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#133]
# Bug Report

This confused me at first because I would start typing, looking for one of my `client` entries and the name wasn't showing. It quickly became clear that it wasn't fetching the results as I type like I was expecting but rather on scroll this leads to some very strange behaviour like:

1. Results not being able to be found unless you scroll down the list.
2. When there's only item and you scroll it continuously loads from the API, resulting in duplicated entries in the dropdown.

## Expected Behavior

As I type, after a de-bounced length of time and maybe a certain number of characters. The API performs a search for the title of the related record and populates the dropdown based on that.

## Current Behavior

Results are paginated and only available when the user scrolls down the list, which they might not do.

## Steps to Reproduce

1. Create collection A
2. Create collection B with `hasMany` relationship field to collection A
3. Create ~20 collection A entries with different names
4. Try to add relationships by searching for it in the combo box. Half of them will be missing until you scroll down in the dropdown.

Also:

1. Create collection C
2. Create collection D with `hasMany` relationship field to collection C
3. Add 1 entry to collection C
4. Scroll down the dropdown in the relationship on collection D

**Comment by jmikrut** [comment]
Hey @richardvanbergen — good call. This is on our radar and we will deploy a fix ASAP. Should be within this week.

Thank you as always for reporting these bugs! We're on it!

**Comment by Ontopic** [comment]
I'm not sure if this related, but I can at the moment not get `relationTo` to work with an array of slugs anymore, it just lists the first slug in the array in the panel.

```
    {
      name: 'target',
      type: 'relationship',
      // hasMany: true,
      // required: true,
      relationTo: [
        'tags',
        'posts',
        'users',
      ]
    },
```

**Comment by jmikrut** [comment]
@Ontopic if you scroll down in the input, the next few relations should load. Do they not? 

In any case my testing with the above PR this AM definitely works with multiple relations. I thought that was fully functional in the released version now too. Just let me know if scrolling down reveals the additional choices!

**Comment by Ontopic** [comment]
When I built the latest branch it doesn't work in the demo. After I created something in the `all-fields` and `localized-posts` collections I do not see both, just the one that is listed first in `relationTo` in the `postLocalizedMultiple` field in `demo/collections/RelationshipA.ts`

It only shows `localized-posts` when using this
```
    {
      name: 'postLocalizedMultiple',
      label: 'Localized Post Multiple',
      type: 'relationship',
      relationTo: ['localized-posts', 'all-fields'],
      hasMany: true,
      localized: true,
    },
```
It only shows `all-fields` when using
```
 ...
   relationTo: ['all-fields', 'localized-posts'],
...
```

**Comment by jmikrut** [comment]
@Ontopic this field looks like it's working perfectly for me. See below video:


https://user-images.githubusercontent.com/6651896/115149647-03a73c80-a033-11eb-971b-3e495a8c9943.mov


Are you seeing something different?

**Comment by Ontopic** [comment]
https://user-images.githubusercontent.com/1599991/115154617-21e55a80-a07c-11eb-9c94-3463f90e2b6c.mov

You're right, scrolling on the dropdown does reveal all options, but this not seem like the best UX - or something I'd like to explain to our editors every time they have change in their staff 🙃 

When the amount of items in a collection are not limited by screen size, it still folds the other collections and there is no indicator that if you scroll down on the dropdown other collections will be made available.

**Comment by jmikrut** [comment]
@Ontopic totally. We will address this in the PR referenced above. Thanks for pointing it out and for helping me get on the same page!

**Comment by Ontopic** [comment]
Thanks for - again - a swift response and action. I'll consider this fixed for now then and hopefully get some PR's in later tonight 🤞

**Comment by jmikrut** [comment]
All deployed in `0.6.0`!

@richardvanbergen / @Ontopic — if either of you attempt updating, there is one breaking change in this release. May or may not apply to you but best to be safe and double-check.

[Check out the migration steps here](https://github.com/payloadcms/payload/blob/master/CHANGELOG.md#migration-instructions-to-06x).

**Comment by richardvanbergen** [comment]
Hi @jmikrut , thanks for the fix! I haven't had time to check yet. I'll see if I can give it a go tomorrow sometime and let you know.

**Comment by Ontopic** [comment]
Working fine on this end 🙃
