### ISSUE TITLE
GraphQL API for the Access query doesn't return the correct data

### ISSUE THREAD

**Issue by nborko** [payloadcms/payload#1338]
# Bug Report

The GraphQL API for the Access query doesn't return the correct data.

## Current Behavior

A current GraphQL query for Acesss will return null for everything, including canAccessAdmin, which generates an error

## Expected Behavior

Get the correct results from the query.

## Possible Solution

Submitting a PR that corrects the problem.

**Comment by jmikrut** [comment]
@nborko THANK YOU for the report and the PR. We're gonna clean sweep through the PRs open shortly and will get yours merged! 👍
