### ISSUE TITLE
Media Relationship field not being populated

### ISSUE THREAD

**Issue by shubhamwebdesign** [payloadcms/payload#1341]
# Bug Report

I have a **page** collection which has a banner block field and that banner block field has an upload field with relationTo:media
I have added the depth query parameter in the endpoint as instructed in docs but when i try to access the endpiont in postman sometime it does not populate the media and only shows the **ID**
http://localhost:5000/api/pages/6363fcf79ce002ca8de78d7e?depth=2

## Current Behavior
Data not being populated - media relationship

Instead of populated data its showing the media ID
## Expected Behavior
It should populate the data and it is populating it sometime (in postman) but not always

## Steps to Reproduce

1. Create a media collection as instructed in docs
2. Create  a Block with having upload field: relationship to media
3. Create a new collection and add the Block field there
4. Fetch the data with fetch() - the media relationship data is not populated instead it just shows the media ID
![postman](https://user-images.githubusercontent.com/68468708/199800777-50e5e8d1-8e2f-4d2d-8c7f-de1ebf3b7570.png)

![console](https://user-images.githubusercontent.com/68468708/199801055-7640c723-8115-4de4-b194-23085e51265a.png)

![incog](https://user-images.githubusercontent.com/68468708/199801218-0930fbb2-c651-4245-9e77-058cea690260.png)

**Comment by shubhamwebdesign** [comment]
When i'm logged in, in postman then its populating the data and when i dont then it just shows the media relationship id, i have added the access in media collection: read: () => true, but still its only populating when logged in. 

And sometime its not populating even if i am logged in (in browser)
I have tried to pass the response token to that endpoint headers
Authorization: Bearer token 
and also tried 
Authorization: token (just in case)
But it's still showing 403 error

**Comment by jmikrut** [comment]
Hey @shubhamwebdesign — it appears to me that this is indeed related to access control preventing you from being able to read the media. It's strange though that this would be the problem if you do indeed have `access.read: () => true` set on your `media` collection.

Just so I understand—you're saying that even when logged in, sometimes the media does not populate? This would certainly be strange, and we have not yet seen this before, so it would be great if you could provide a minimally reproducible repo or code that demonstrates the problem. In our testing we can't replicate.

One other thing I could think of is that if you have deleted the media file, then it will not populate of course, and will only show the ID of the deleted item. 

Anything you're able to provide that can help us further diagnose here?

**Comment by shubhamwebdesign** [comment]
The error was not properly set access control, also i had removed the media collection from database but the media folder still had the images inside it. After removing the media folder, collection from database and setting up read access its working again.
