### ISSUE TITLE
Show validation error: "Value must be unique"; "Handle uniqueness error from MongoDB."

### ISSUE THREAD

**Issue by agenteAND** [payloadcms/payload#1353]
# Bug Report
slug.js
```
{
      name: 'slug1',
      label: 'Slug',
      type: 'text',
      unique: true,
      admin: {
        position: 'sidebar',
      },
      hooks: {
        beforeValidate: [
          formatSlug('title'),
        ],
      },
 }
```

```
 ERROR (payload): ValidationError: The following field is invalid: slug1
    at new ExtendableError (/Users/solis/Documents/WebProjects/payload-test/node_modules/payload/dist/errors/APIError.js:22:15)
    at new APIError (/Users/solis/Documents/WebProjects/payload-test/node_modules/payload/dist/errors/APIError.js:38:9)
    at new ValidationError (/Users/solis/Documents/WebProjects/payload-test/node_modules/payload/dist/errors/ValidationError.js:10:9)
    at create (/Users/solis/Documents/WebProjects/payload-test/node_modules/payload/dist/collections/operations/create.js:142:19)
    at process.processTicksAndRejections

 (node:internal/process/task_queues:95:5)
    at async createHandler (/Users/solis/Documents/WebProjects/payload-test/node_modules/payload/dist/collections/requestHandlers/create.js:11:21)
```
## Current Behavior
![show errors](https://user-images.githubusercontent.com/44445475/200390534-0067ce65-95e5-46b9-bdc9-01b84c28cdf6.gif)

## Expected Behavior
<img width="703" alt="Captura de Pantalla 2022-11-07 a la(s) 2 43 45 p m" src="https://user-images.githubusercontent.com/44445475/200389895-649ce663-5f6b-47ad-bc25-099e0bffc847.png">

## Steps to Reproduce
1. in field schema set option unique: true
2. try add duplicate value

## Detailed Description
When I try to add a value to a field whose database restriction is that it does not allow duplicate values, I receive a Bad Request 400 response from the server, but the field that should not be duplicated does not remain showing the error message, so a content creator will not know why the validation is failing and saving in the database is not possible.

Could you explain why this occurs and, if possible, provide an immediate solution?

[![Generic badge](https://img.shields.io/badge/Node-v18.10.0-green.svg)](https://shields.io/)

Project dependencies:

```
"dependencies": {
    "@babel/register": "^7.17.0",
    "dotenv": "^16.0.0",
    "escape-html": "^1.0.3",
    "express": "^4.18.0",
    "next": "^12.1.0",
    "payload": "^1.1.21",
    "react": "^18.1.0",
    "sass": "^1.52.0",
    "slate": "^0.72.8",
    "typescript": "^4.7.0"
  },:
```

**Comment by jmikrut** [comment]
Hey @agenteAND — thank you for the report! This is now fixed and will be released shortly. 👍
