### ISSUE TITLE
Can't save Global with nested lists

### ISSUE THREAD

**Issue by PegasisForever** [payloadcms/payload#1357]
# Bug Report

If a global have nested lists, it can't be saved.

## Current Behavior

If a global have nested lists, it can't be saved.

## Expected Behavior

It should be saved.

## Steps to Reproduce

1. Create a payload server with this ["MemberGroup" global](https://gist.github.com/PegasisForever/6ab49c350b8b2ce9159b01bac8658678)
2. Add the first group with one member and save: (this step should work correctly) 
![image](https://user-images.githubusercontent.com/39028532/200485113-86a83671-ad69-4d00-8703-da0263d831a9.png)
3. Don't refresh the page, add the second group and save: 
![image](https://user-images.githubusercontent.com/39028532/200485426-6205ad80-5535-4e4e-bb73-c68decfb3fd1.png)

## Detailed Description

Payload version: 1.1.21

**Comment by jmikrut** [comment]
Hey @PegasisForever — thanks for this report! This is now fixed and will be released shortly in our next patch version.
