### ISSUE TITLE
listSearchableFields and useAsTitle not working in search bar when field is in a tab

### ISSUE THREAD

**Issue by gonzam88** [payloadcms/payload#1358]
# Bug Report

If I have a collection whose fields structure is like this
```
{
      type: 'tabs',
      tabs: [
        {
          label: 'General',
          description: 'Basic experience settings',
          fields: [
               name: 'username',
               type: 'text'
          ]
         }
    ]
}
```

then setting `listSearchableFields: ['username'],`  doesn't work, in the collection view search bar I will only have the option to search by ID. But if I moved the username field outside the tab, in the root of the fields array, it works perfectly.

Running on latest Payload v1.1.21
The explanation is pretty straight forward. Please let me know if there's more information I could provide.

**Comment by jmikrut** [comment]
Hey @gonzam88 — thank you for the report! This is now fixed and will be released shortly. 👍

**Comment by Etheliene** [comment]
I understand that this is a closed issue but just wanted to throw in that the same applies if the searchable field is nested within a row
