### ISSUE TITLE
"admin.components" is not allowed for Globals

### ISSUE THREAD

**Issue by zcylla** [payloadcms/payload#1367]
# Documentation Issue

Both the documentation and the typescript types say that you can provide a custom component for a global's edit view, but the globals validation schema doesn't seem to allow it.

When providing a custom component for a global edit view i get the following error:
`1: Globals "test_global" > "admin.components" is not allowed`

**Comment by jmikrut** [comment]
Hey @zcylla — thank you for the report! This is fixed and will be released shortly!
