### ISSUE TITLE
Collapsible field does not show errors

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#1377]
# Bug Report

Collapsible field does not show errors which results in a suboptimal UX.

## Current Behavior

After saving, a generic error is shown, the user cannot see what's wrong.

## Expected Behavior

After saving, the user sees the first error.

## Possible Solution

Open any relevant collapsible/tab and scroll to the field with the validation error.

## Steps to Reproduce

1. Add a collapsible field with a subfield
2. Add a validation rule to the subfield
3. Add a record and collapse the collapsible
4. Hit save

**Comment by jmikrut** [comment]
Hey @thgh — this is actually on our radar and is planned to be released ASAP:

https://github.com/payloadcms/payload/discussions/881

I'm going to defer conversation to that discussion, but we're on it!
