### ISSUE TITLE
Redirect to not-found during development

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#1392]
# Bug Report

There is a race condition during development, where the server is restarting and the admin page is refreshing. This results in poor DX.

## Current Behavior

When refreshing the Edit page shortly after updating some code, sometimes the page redirects to `/admin/not-found`

## Expected Behavior

Stay on the same page no matter what. (except logout, which should remember the original page and redirect you afterwards.

## Possible Solution

[This error check catches lots of cases.](https://github.com/payloadcms/payload/blob/5f5c7ba7bf83dd2f7de98a9ea0948d1cd0ab3fd1/src/admin/components/views/collections/Edit/index.tsx#L122-L126) If the error is recoverable, it should show a temporary screen and retry.

## Steps to Reproduce

1. Something with nodemon, ts-node and the Edit screen

**Comment by PatrikKozak** [comment]
@thgh I am unable to reproduce this but would like to help you. Can you possibly give a little more information, like what kind of file are you editing - custom component or config or something else?

**Comment by thgh** [comment]
Will check more closely, but it could take some time. I think it was while developing custom components.

**Comment by DanRibbens** [comment]
I was not able to reproduce this either. I tried making a custom component that throws an error while on the page. It did not redirect me even when that happens:
![live-updates](https://user-images.githubusercontent.com/6434612/207936047-6bea8f6b-f20d-43f2-b201-67952be2b337.gif)

If you have more info for us to go on, feel free to open up the issue again.
Thanks!
