### ISSUE TITLE
Cursor jumps to end of input

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#1393]
# Bug Report

When typing the first letter in a Text field, the cursor jumps to the end of the line. This only happens in the first edit of a page.

## Current Behavior

The cursor jumps to the end of the line.

## Expected Behavior

The cursor is behind the typed letter.

## Possible Solution

Will create a PR

## Steps to Reproduce

https://user-images.githubusercontent.com/1109982/201519702-8b36d491-53fb-460c-9813-5171c597c84a.mov

**Comment by thgh** [comment]
Ow, it was just fixed, may I suggest a different fix though?

**Comment by jmikrut** [comment]
I love your new fix, mind blown. I thought for sure the cursor jumping was to do with my new `use-context-selector` updates, maybe just being out of sync or something. But thank you for the issue and for the PR! I'm gonna test it later today and put it through its paces.

In the meantime, gonna close up this issue!
