### ISSUE TITLE
Can't remove all array elements from global

### ISSUE THREAD

**Issue by ahmedHusseinF** [payloadcms/payload#1400]
# Bug Report

I have an array in a global. I can add elements to it and can remove elements from it as long as it still has elements.
But if i am removing ALL the elements in the array, the save does nothing and the global reverts back to its state before saving.

I think this is a MAJOR issue as this is blocking a normal flow.

## Current Behavior
Removing the last element(s) in an array in a global doesn't work and global revert to its last state before saving.

## Expected Behavior
Removing the last elements in an array in a global should make an empty array.

## Steps to Reproduce

1. Open attached project
2. Navigate to the example global and create some elements in the array
3. Try to delete only one element (works)
4. Try to delete all remaining elements in the array (fails)

## Detailed Description
Project: [payload-global](https://github.com/ahmedHusseinF/payload-global)

**Comment by jmikrut** [comment]
Good catch @ahmedHusseinF – just deployed a fix for this. Update Payload and give it a shot! 👍
