### ISSUE TITLE
Draft created using REST API is non loaded in the UI collection editor

### ISSUE THREAD

**Issue by manuelebagnolini** [payloadcms/payload#1415]
# Bug Report

Draft created using REST API with `PATCH` method is not loaded in the UI collection editor as the most recent version.

## Current Behavior

If I create a draft using the REST API `PATCH` method with the `draft=true` in the url, the new draft version is created in `published` state and the changes are not shown in the collection editor in admin UI.

The `Publish Changes` button is enabled but if I press it, the changes in the draft created with the API are not published.

## Expected Behavior

The new draft is loaded in the collection editor UI so that the user can see the changes and publish them.

## Possible Solution

If I manually change the state ot the draft version on the DB from `published` to `draft` then it works so maybe the problem is that the draft version is created in the wrong state.

## Steps to Reproduce
1. Create the draft using REST API, `PATCH` method and `draft=true`.

```typescript
let url = http://localhost:3000/api/homepage/63511e5b03f3a5092d821a44?depth=0&locale=fr&fallback-locale=null&draft=true
let payload = {"title": "Nouvelle vague"}

const httpResponse = await fetch(url, {
  method: 'PATCH',
  body: JSON.stringify(payload),
  headers: {
    'Content-Type': 'application/json',
  },
});
```
2. Verify that the new version has been created in published state with the title change for the given locale:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/45173102/201954945-fb87a36b-08b5-41e0-acc0-eaa0cccde3a5.png">
<img width="886" alt="image" src="https://user-images.githubusercontent.com/45173102/201955158-a5089af2-b734-443a-bd18-6ff0e7063e78.png">

3. Open the editor and verify that the changes are not shown, click on `Publish changes` and the document will be published with the old title.
<img width="939" alt="image" src="https://user-images.githubusercontent.com/45173102/201955836-e0137c26-118f-4bb5-ab28-326b6fdcf1aa.png">

## Detailed Description

Payload version: 1.1.15

Localization configuration:
```typescript
localization: {
  locales: ['en', 'it', 'fr', 'de'],
  defaultLocale: 'en',
  fallback: true,
},
```
Collection versioning configuration:
```typescript
versions: {
  drafts: true,
},
```
Extras: SEO plugin installed

**Comment by jmikrut** [comment]
Hey @manuelebagnolini — I can reproduce this. Have not yet worked to the bottom of it but should be simple. Looks like the new draft _**is**_ being stored in the `_versions` collection, but just not surfacing in the frontend UI.

Will report back here shortly with more.
