### ISSUE TITLE
Updating a localized field via multiple REST API async call only saves one value 

### ISSUE THREAD

**Issue by manuelebagnolini** [payloadcms/payload#1419]
# Bug Report

If I try to save multiple localized values for a document field using multiple REST API `PATCH` method async calls (one for each locale) is resulting in some of the updates to be ignored.

## Current Behavior

I don't get any errors but only a localized value is persited on DB.

## Expected Behavior

All the given localized values for the field are persisted on DB.

## Possible Solution

Using a breakpoint between the API calls to increase the time distance between them it worked correctly so I presume it's a concurrency problem.

Could be related to issue #1406 ?

## Steps to Reproduce
1. Save the same collection field in 2 locales using 2 API calls

```typescript

const saveLocale = async (id: string, collection: string, locale: string, payload: { [key: string]: unknown }) => {
  const url = `http://localhost:3000/api/${collection}/${id}?depth=0&locale=${locale}&fallback-locale=null`;

  const httpResponse = await fetch(url, {
    method: 'PATCH',
    body: JSON.stringify(payload),
    headers: {
      'Content-Type': 'application/json',
    },
  });
};

await saveLocale('63511e5b03f3a5092d821a44', 'homepage', 'fr', {'title': 'Nouvelle vague'});
await saveLocale('63511e5b03f3a5092d821a44', 'homepage', 'de', {'title': 'Neue Welle'});
```
2. Verify that only one value has been saved on DB. In my case only the last one (locale 'de') has been saved.

## Detailed Description

Payload version: 1.1.15

Localization configuration:
```typescript
localization: {
  locales: ['en', 'it', 'fr', 'de'],
  defaultLocale: 'en',
  fallback: true,
},
```
Collection versioning configuration:
```typescript
versions: {
  drafts: true,
},
```
Extras: SEO plugin installed

**Comment by jmikrut** [comment]
@JessChowdhury please get an environment set up to reproduce this within Payload, and once you have it, we can pair on figuring out what is happening here!

**Comment by manuelebagnolini** [comment]
I have an update on this issue.

Actually calling the 2 APIs like in the oversimplified example I shared is working.

Calling them in a cycle like in our actual code is not working:

```typescript
const saveLocale = async (id: string, collection: string, locale: string, payload: { [key: string]: unknown }) => {
  const url = `http://localhost:3000/api/${collection}/${id}?depth=0&locale=${locale}&fallback-locale=null`;

  const httpResponse = await fetch(url, {
    method: 'PATCH',
    body: JSON.stringify(payload),
    headers: {
      'Content-Type': 'application/json',
    },
  });

  const response = await httpResponse.json();

  return response;
};

const test = async () => {
  const updates = [{
    id: '63511e5b03f3a5092d821a44',
    collection: 'homepage',
    locale: 'fr',
    payload: {'title': 'Nouvelle vague from test'}
  },
  {
    id: '63511e5b03f3a5092d821a44',
    collection: 'homepage',
    locale: 'de',
    payload: {'title': 'Neue Welle from test'}
  }];

  const saveAllLocales = updates.map(x => saveLocale(x.id, x.collection, x.locale, x.payload));

  const responses = await Promise.all(saveAllLocales);
};
```

**Comment by siccifolium** [comment]
I understand that this issue is closed as it makes sense that parallel updates can be problematic. The usecase of updating a complete document with all its translations at once however still exists.
Is there a ways to update a whole document with all its translations in one call?
I mean just like I can receive the complete document with all its translations when I specify `locale=all` via the api, is there a way to update a document like that?
