### ISSUE TITLE
Incorrect Theme for syntax higlight in light theme

### ISSUE THREAD

**Issue by thekip** [payloadcms/payload#1425]
# Bug Report

Dear dark-theme lovers, please don't forget about us, light theme lovers  😄

<img width="862" alt="image" src="https://user-images.githubusercontent.com/1586852/202148426-45363170-dadb-48b3-90c1-ee198ab54053.png">

## Current Behavior

Code editor uses highlighting theme more suitable for dark-theme which mostly not readable on light theme.

**Comment by JarrodMFlesch** [comment]
Wow. My eyes are bleeding, we will fix this.

**Comment by JarrodMFlesch** [comment]
@thekip a fix (#1521) has been merged into master and will go out with the next release.
