### ISSUE TITLE
Accessibility issues in "npx create-payload-app"

### ISSUE THREAD

**Issue by hmmhmmhm** [payloadcms/payload#1437]
# Documentation Issue

<img width="408" alt="스크린샷 2022-11-17 오후 5 11 09" src="https://user-images.githubusercontent.com/38493722/202391746-b8a74bc6-4b7c-4088-8cbe-7c2697c18427.png">

The cmd + click that cli uses to access the address moves to Chrome, including the closing sign behind the address.

<img width="1583" alt="스크린샷 2022-11-17 오후 5 11 35" src="https://user-images.githubusercontent.com/38493722/202391761-9a77c968-8d33-40f4-b3ea-8a285dbc9f15.png">

This is why there are problems that the majority of CLI users cannot read even though they are clearly documents that exist.
It need to prevent this by deleting parentheses or leaving spaces between parentheses.

**Comment by denolfe** [comment]
Hey @hmmhmmhm thanks for the report. What terminal are you using to recreate this?

I'm not able to recreate this on Mac OS with iTerm2 or stock Terminal.

<img width="381" alt="CleanShot 2022-11-18 at 15 19 04@2x" src="https://user-images.githubusercontent.com/65888/202795055-634b0f98-9f74-4895-b75d-066c521d1865.png">
<img width="625" alt="CleanShot 2022-11-18 at 15 19 42@2x" src="https://user-images.githubusercontent.com/65888/202795114-eb24a7f0-e053-4fc9-90cc-1b2128a81cfe.png">

**Comment by denolfe** [comment]
It appears this is a known issue with terminal-link https://github.com/sindresorhus/terminal-link/issues/18.

I've implemented the suggested workaround and released a beta version. @hmmhmmhm Can you try `npx create-payload-app@beta` to see if this resolves the issue?

**Comment by denolfe** [comment]
Fix released in latest.
