### ISSUE TITLE
Localized file upload and ?locale=all query parameter

### ISSUE THREAD

**Issue by wloodar** [payloadcms/payload#1444]
# Bug Report

Localized file upload with

```
?locale=all
```

<img width="407" alt="Screenshot 2022-11-18 at 03 09 28" src="https://user-images.githubusercontent.com/56487194/202600567-c1cc4f91-8e93-4aa1-922d-e8534a1ac1c2.png">

## Current Behavior

Localized file upload returns

```
"[object Object]"
```
while using query parameter ?locale=all

## Expected Behavior

Returning object with localized file details like other properties e.g.:
`
"title": {
"pl": "Instrukcja",
"en": "User guide"
},
`

## Detailed Description

Payload v1.1.19

**Comment by DanRibbens** [comment]
This was quite a difficult one to fix, but I got it all working!
PR is ready for review.
