### ISSUE TITLE
versionCount in Admin UI shows variable name and not the number of versions 

### ISSUE THREAD

**Issue by tobedamobe** [payloadcms/payload#1457]
# Bug Report

The Info Field versionCount does not show the versions for a collection. It seems like there is shown the variableName.

## Current Behavior

The info field versionCount does not show the versions for a collection.

<img width="334" alt="Bildschirmfoto 2022-11-19 um 00 40 57" src="https://user-images.githubusercontent.com/5109506/202821718-72c0b5ff-b3c1-4bed-944e-dcbec12bcbdf.png">

## Expected Behavior

Show number of versions 

## Steps to Reproduce

Create some versions inside a versioned collection.

## Detailed Description

Additionally I realized that the versions in the versions history ...

<img width="1217" alt="Bildschirmfoto 2022-11-19 um 00 52 01" src="https://user-images.githubusercontent.com/5109506/202821949-e00d52b8-0b24-4646-91bd-5564aa0b8ada.png">

...shows undefined if you click an unpublished or published version

<img width="1512" alt="Bildschirmfoto 2022-11-19 um 00 52 24" src="https://user-images.githubusercontent.com/5109506/202821951-7c91b725-bc07-460d-9165-84b2a4ca2e84.png">

**Comment by denolfe** [comment]
`versionCount` bug verified. Created a new issue for the admin crashing here #1464
