### ISSUE TITLE
Some translate issues

### ISSUE THREAD

**Issue by tobedamobe** [payloadcms/payload#1458]
# Bug Report

Some translations are not available. Maybe here is shown the variable name instead of its value.

## Current Behavior

draftSaveSuccessfully is shown in the toast after saving a collection item

<img width="1340" alt="Bildschirmfoto 2022-11-19 um 00 40 40" src="https://user-images.githubusercontent.com/5109506/202821674-db744a1f-569b-4b31-8adf-8050b92abbf3.png">

## Expected Behavior

Show "Entwurf erfolgreich gespeichert"

## Steps to Reproduce

1. Create a versioned collection item. 
2. Change a field. 
3. Save the draft

**Comment by DanRibbens** [comment]
Released in v1.2.1

Thanks @tobedamobe!
