### ISSUE TITLE
Unable to load draft if revisions are enabled

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#1464]
# Bug Report

Admin UI crashes when loading a draft

## Current Behavior

Loading any draft crashes the Admin UI

![CleanShot 2022-11-20 at 10 31 35@2x](https://user-images.githubusercontent.com/65888/202910906-29085fe8-63ed-4da4-955a-2007292bad87.png)

<img width="1076" alt="CleanShot 2022-11-20 at 10 26 01@2x" src="https://user-images.githubusercontent.com/65888/202910928-d632495b-1cdb-49d4-81c4-e9606d74af77.png">

## Steps to Reproduce

1. Create collection with drafts enabled
2. Create a few drafts
3. Try to load draft from UI

**Comment by denolfe** [comment]
Looked like the `RenderFieldsToDiff` component is not handling the translations of the internal `_status` field properly. Normally, field labels would be already translated at the time of diff, but the status field is being received with a `label` property of all the translated values.

<img width="864" alt="CleanShot 2022-11-20 at 14 18 53@2x" src="https://user-images.githubusercontent.com/65888/202921643-5be49834-b30c-4565-8c23-c3d285168ce3.png">

**Comment by DanRibbens** [comment]
Fixed for v1.2.1
