### ISSUE TITLE
Admin can't use root path for api

### ISSUE THREAD

**Issue by 383bd03d** [payloadcms/payload#1483]
If define root path for api in payload.config.ts `routes: {
    api: "/",
    admin: "/admin",
  },` for example i want to use payload cms on production with url such as api.example.com/collection/, not api.example.com/api/collection, but with root path admin cannot work properly and throws error in console
`api.js:8          GET http://users/init net::ERR_NAME_NOT_RESOLVED
get @ api.js:8
(anonymous) @ Routes.js:37
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
`

`GET http://localhost:4000//users/me 404 (Not Found)
get @ api.js:8
fetchMe @ index.js:59
(anonymous) @ index.js:72
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
`

`Uncaught (in promise) TypeError: Failed to fetch
    at Object.get (api.js:8:1)
    at Routes.js:37:13
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at react-dom.development.js:26769:1
get @ api.js:8
(anonymous) @ Routes.js:37
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Promise.then (async)
(anonymous) @ Routes.js:41
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
`

**Comment by DanRibbens** [comment]
It looks like with one line of code change this is possible.

Instead of using `api: '/'` we need to allow `api: ''` to be a valid URL.

I tested this locally and it seems to work if I allow empty string by changing the schema validation from `routes.api: joi.string()` to `routes.api: joi.string().allow('')`.

Interesting!

**Comment by DanRibbens** [comment]
We might want to prevent `'/'` too since that does not work.

**Comment by 383bd03d** [comment]
When I leave api empty I get error:
`[16:27:55] INFO (payload): Starting Payload...
[16:27:57] ERROR (payload): There were 1 errors validating your Payload config
[16:27:57] ERROR (payload): 1: "routes.api" is not allowed to be empty
[nodemon] app crashed - waiting for file changes before starting...`

Payload version 1.2.1
