### ISSUE TITLE
Creating Mongodb app in azure cosmos yields error

### ISSUE THREAD

**Issue by onionhammer** [payloadcms/payload#1506]
# Bug Report

`The index path corresponding to the specified order-by item is excluded`

## Steps to Reproduce

1. npx create-payload-app, choose empty template
2. Configure `indexSortableFields: true`
3. Run and create first user

## Other Details

This error shows in logs when trying to load the users collection

**Comment by onionhammer** [comment]
Workaround:

Manually add indexes on Users collection;

- createdAt.$**
- updatedAt.$**

**Comment by denolfe** [comment]
Thanks for the report. We've had to make adjustments for cosmos db in the past (#1272). This sounds like something that also needs to be accounted for.

**Comment by angelobartolome** [comment]
Maybe not the best workaround for auto-creating it but suffices my needs:


```ts
// Initialize Payload
payload.init({
    // ...
    onInit: () => {
        payload.logger.info(`Payload Admin URL: ${payload.getAdminURL()}`)

        // Workaround for CosmosDB and https://github.com/payloadcms/payload/issues/1506
        // Await for moongoose to connect
        mongoose.connection.on('connected', () => {
            payload.logger.info('Mongoose connected')
            ;(payload.collections.users.Model as any).collection.createIndex({ updatedAt: 1 }, { background: true })
            ;(payload.collections.users.Model as any).collection.createIndex({ createdAt: 1 }, { background: true })
        })
    },
})

```

**Comment by angelobartolome** [comment]
Hi @DanRibbens,

I saw you were assigned to this. 

I've started PR #1537, maybe helpful.
