### ISSUE TITLE
Localised draft is not correctly saved.

### ISSUE THREAD

**Issue by timay-talkbox** [payloadcms/payload#1512]
# Bug Report

I am not sure if it is intended or just a bug. 
When saving the draft content of a new locale, content of other locales is lost in some circumstances.
You can reproduce the issue on demo site [demo.payloadcms.com](demo.payloadcms.com)

## Steps to Reproduce

1. Make a draft in english, e.g. 
`{ data: { title: { en: "English Title" } } }`

2. Switch language to "de" and make a draft in German, e.g. 
`{ data: { title: { en: "English Title", de: "German Title" } } }`

3. Switch language to "es" and make a draft in Spanish. I expect to get something like this 
`{ data: { title: { en: "English Title", de: "German Title", es: "Spanish Title" } } }`
However, it gives me `{ data: { title: { en: "English Title", es: "Spanish Title" } } }`

I guess payload CMS only updates the content of the initial draft, but not the most recent draft.
That means, the changes made after the initial draft would be lost.

I expect that when i clicks the "save draft", it should save the document of the current locale only without affecting the draft content of other locale.

**Comment by DanRibbens** [comment]
Fixed in v1.2.2.

Thanks for reporting @timay-talkbox!

**Comment by timay-talkbox** [comment]
@DanRibbens Thanks for the fix.
