### ISSUE TITLE
blockName input is unnecessarily small

### ISSUE THREAD

**Issue by zerovox** [payloadcms/payload#1517]
Payload Version: 1.2.1. 

This is super minor, but when adding a new block, the auto-generated blockName input is pretty small and does not expand as the input does. This makes it hard to enter and edit medium-to-long sized titles. (And to get even more nit-picky, it's not vertically aligned with the other items in the section header :)

![block title truncated](https://user-images.githubusercontent.com/933064/204151776-3222e835-a823-42bc-9e4f-0778c0b0c577.png)

**Comment by JarrodMFlesch** [comment]
@zerovox, can you give me a sample config to recreate this issue? I am unable to replicate on my end. 

What browser? What OS?

**Comment by zerovox** [comment]
Ah, Firefox on Windows. This config repros for me:

```
const QuoteBlock: Block = {
  slug: "quote",
  fields: [
    {
      name: "quote",
      type: "richText",
    },
  ],
};

const Thing: CollectionConfig = {
  slug: "thing",
  access: {
    read: () => true,
  },
  fields: [
    {
      name: "extracts",
      type: "blocks",
      minRows: 0,
      blocks: [QuoteBlock],
    },
  ],
};

export default Thing;
```

**Comment by pooledge** [comment]
In Safari (at least v16.4) we still need this:

```css
.blocks-field__block-header {
    width: 100%;
}
.section-title {
    flex-grow: 1;
}
```
