### ISSUE TITLE
Dynamics option data on select field.

### ISSUE THREAD

**Issue by vince93290** [payloadcms/payload#1519]
I've got a problem when i want to set options data on select fields with dynamics data i've an error message.

![image](https://user-images.githubusercontent.com/44445302/204233594-3ad3d1ae-981c-44e2-9e84-0862acad0e5d.png)
![image](https://user-images.githubusercontent.com/44445302/204233661-9a47c917-b80b-4e1d-82eb-e38b67ef2aa6.png)
![image](https://user-images.githubusercontent.com/44445302/204233721-fcd42352-c93f-4fa9-bcdf-aa339d17f3d2.png)

Can anyone for help me

sorry for my bad english

**Comment by JarrodMFlesch** [comment]
@vince93290 Select options are not meant to be dynamic. You have a couple options though, if you were fetching data from an external source (not payload) you might opt for a custom `ui` component that renders it's own select. 

In your case, I think a `relationship` field would work best. You can read more about them [here](https://payloadcms.com/docs/fields/relationship)
