### ISSUE TITLE
Difficulties installing on M1 Apple Silicon

### ISSUE THREAD

**Issue by kerimhudson** [payloadcms/payload#153]
# Bug Report: Cannot install on M1 Apple Silicon due to Sharp version

Hey all. Was really looking forward to trying this CMS out, but instantly hit a snag. It doesn't seem like a big problem, but with the rise in Apple Silicon releases and popularity now, I thought it best to mention it.

## Expected Behavior

When trying to install payload via yarn or npm, I expect it to install successfully

## Current Behavior

When trying to install payload via yarn or npm, it fails as it is unable to compile the `sharp` package.

## Possible Solution

To get it to work currently on M1, you must ensure you have libvips installed first via brew: `brew install libvips`. However the latest version of `sharp` supports M1. Upgrade `sharp` to the latest version (0.28.1) which includes Apple Silicon support. More about this can be found [here](https://github.com/lovell/sharp/issues/2460).

**Comment by denolfe** [comment]
@kerimhudson This should be fixed in the latest release as we've updated sharp to the latest version 👍

**Comment by kerimhudson** [comment]
Thanks for letting me know, and the quick fix!
