### ISSUE TITLE
Relationships Not Bidirectional

### ISSUE THREAD

**Issue by rawkode** [payloadcms/payload#1530]
# Bug Report

I've got two collections: Show and Episode.

Show has a many relationship to Episode
Episode has a single relationship to a Show

When I save the Show on the Episode, the `episodes` field on the Show is empty.

## Steps to Reproduce

Episode field on Show

```ts
    {
      name: "episodes",
      type: "relationship",
      relationTo: "episodes",
      hasMany: true,
    },
```

Show field on Episode

```ts
    {
      name: "show",
      type: "relationship",
      relationTo: "shows",
      hasMany: false,
      required: true,
    },
```

## Other Details

Payload version is 1.2.0

**Comment by AlessioGr** [comment]
Payload doesn't do bi-directional relationships by default, sadly. You can
- Leave the relationships like that and adjust your queries to find them from "the other side"
- Use a plugin to handle bi-directional relationships. I'm using https://github.com/TimHal/pcms-backpop

**Comment by rawkode** [comment]
> Leave the relationships like that and adjust your queries to find them from "the other side"

This makes for pretty crappy queries.

I'll keep an eye on the plugin, but this is probably a blocker for my Payload adoption and I'll need to take some time to figure out which constraints and features are more important to me.

Thanks for your response.
