### ISSUE TITLE
Rich text can be saved as empty string ("") causing errors in admin panel when parsing data.

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#154]
# Bug Report

Currently the admin panel is crashing for us when we try to edit most collections and it's due to the rich text editor getting saved with an empty string as it's value.

I'm not sure how this data got set this way, so I'm not really able to give reproduction steps. It was reported to me by a content editor so I have no first hand account.

I'm fairly sure it's something to switching between locales on localized fields within blocks.

The error itself should be quite an easy fix, the underlying cause I'm not so sure about.

## Expected Behaviour

When a rich text area has it's value set as an empty string, it should render the text area as if had no content passed to it.

## Current Behaviour

It tries to run JSON.parse on an empty string and crashes the entire page.

## Detailed Description

Payload version: 0.6.5

VM141:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at RichText (RichText.js:89)
    at renderWithHooks (react-dom.development.js:14985)
    at updateFunctionComponent (react-dom.development.js:17356)
    at beginWork (react-dom.development.js:19063)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22779)

![image](https://user-images.githubusercontent.com/3854592/116242221-ac2a6e80-a7a0-11eb-8990-771d1fe8fe93.png)

**Comment by denolfe** [comment]
Thank you for the report @richardvanbergen. Are you able to provide the collection config or the subset that contains the localized field within a block?

**Comment by richardvanbergen** [comment]
Hi, it's basically a page collection that looks like this:

```
const PageCollection: CollectionConfig = {
  slug: 'page',
  admin: {
  },
  labels: {
    singular: 'Page',
    plural: 'Pages',
  },
  fields: [
    ...PageMetaFields,
    {
      name: 'content',
      label: 'Content Blocks',
      type: 'blocks',
      labels: {
        singular: 'Layout',
        plural: 'Layouts',
      },
      blocks: [
        HeroSchema,
        ClientListSchema,
        CarouselSchema,
        IllustratedCopySchema,
        ContentGridSchema, // <-- this guy right here caused the error
        HubspotFormSchema,
        CtaBannerSchema,
        ProcessStepsSchema,
      ],
    },
  ],
}

export default PageCollection
```

The block that caused the error looks like this:

```
const ContentGridSchema: Block = {
  slug: 'contentGrid',
  imageURL: 'https://brightvision.fra1.cdn.digitaloceanspaces.com/admin-preview-images/rows-and-columns.png',
  imageAltText: 'A component for organizing content into flexible rows and columns.',
  labels: {
    singular: 'Rows & Columns',
    plural: 'Rows & Columns',
  },
  fields: [
    {
      type: 'array',
      name: 'grids',
      fields: [
        {
          type: 'row',
          fields: [
            {
              type: 'number',
              label: 'Maximum Columns',
              name: 'numberOfColumns',
              admin: {
                width: '50%',
              },
            },
          ],
        },
        {
          type: 'array',
          name: 'columns', // <-- more specifically this guy
          fields: [
            {
              type: 'richText',
              name: 'content',
              localized: true,
            },
          ],
        },
      ],
    },
  ],
}

export default ContentGridSchema
```

And this is my payload config with the internationalization:

```
// ... bunch of imports

export default buildConfig({
  serverURL: process.env.PAYLOAD_PUBLIC_SERVER_URL,
  collections: [
    Page,
    Client,
    Testimonial,
    MediaVideo,
    MediaImage,
    APIUser,
    Link,
    HubspotFormEmbed,
  ],
  globals: [
    SiteConfig,
    MainMenu,
    Error404,
    Error500,
  ],
  localization: {
    locales: [
      'en',
      'dk',
      'sv',
      'no',
      'fi',
    ],
    defaultLocale: 'en',
    fallback: true,
  },
  admin: {
    components: {
      graphics: {
        Icon: Favicon,
        Logo: Logo,
      },
      views: {
        Dashboard,
      },
    },
  },
})
```

**Comment by richardvanbergen** [comment]
Let me know if you need any more information.
