### ISSUE TITLE
Crash when switching locale after saving edits to rich text field

### ISSUE THREAD

**Issue by nomadoda** [payloadcms/payload#1546]
# Bug Report

Uncaught error `Error: Cannot find a descendant at path [3] in node` when switching locale after saving a rich text field. Page goes blank.

## Steps to Reproduce

1. Enter https://demo.payloadcms.com/
2. Edit a rich text field in a page
3. Save draft
4. Switch locale

## Other Details

Related issue: https://github.com/payloadcms/payload/issues/568

**Comment by DanRibbens** [comment]
I was able to reproduce. It doesn't matter whether I save a draft or do this on a collection without versions.

It seems to only happen if you have a line return at the very end of your content.

**Comment by jmikrut** [comment]
Hey @nomadoda — we reproduced and fixed this. Will be released shortly!
