### ISSUE TITLE
Admin.components.graphics config property requires "v"

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#1578]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/70709113/205453040-dc88a50d-6eee-44e4-8e5c-8d6d887e7189.png">

Not defining v: here (whatever that is) throws a type error, as it's required.
Upgrading from v1.2.1 to v1.2.3 introduced this bug. Before, it worked as expected without having to specify a v: parameter.

**Comment by DanRibbens** [comment]
@AlessioGr, I noticed this yesterday. I fixed it as a "chore" so it isn't in the changelog, but it is fixed in v1.2.4. Thanks for reporting!
