### ISSUE TITLE
Relation fields don't show linked page titles - Seems to be empty

### ISSUE THREAD

**Issue by tobedamobe** [payloadcms/payload#1601]
# Bug Report

Relation fields with relation to pages don't show the title of the page, after reloading the AdminUI
If you open the relation dropdown you can see that the relation is there and the db is okay too but the title is missing and the fields wants me to "Set a value". See screenshots for details.

## Steps to Reproduce

1. Set a relation to a page on (for example) an global document (like "important pages")
2. save the global document
3. reload the global document

## Other Details

Payload 1.2.2, 1.2.3, 1.2.4

## Screenshots

1. Page relation not set
![Bildschirmfoto 2022-12-06 um 10 34 14](https://user-images.githubusercontent.com/5109506/205874228-768a8dcb-e9a1-4436-b2d2-694de734df9d.png)

2. Dropdown shows an active relation
![Bildschirmfoto 2022-12-06 um 10 34 25](https://user-images.githubusercontent.com/5109506/205874231-0538739c-29b3-45a0-9ac4-3b4231453c42.png)

3. When i save the document...
![Bildschirmfoto 2022-12-06 um 10 34 33](https://user-images.githubusercontent.com/5109506/205874237-1b062e51-768b-4904-951e-d64cbe7dfd17.png)

4. ... the relation label is still there
![Bildschirmfoto 2022-12-06 um 10 34 38](https://user-images.githubusercontent.com/5109506/205874246-45565cdc-5842-483a-8aed-604c5eee77f7.png)

5. After reload of the ui it is gone!
![Bildschirmfoto 2022-12-06 um 10 34 45](https://user-images.githubusercontent.com/5109506/205874252-e73d8b16-7fdc-4dd1-b9f0-8ba754250dd3.png)

**Comment by jacobsfletch** [comment]
Thanks for the report @tobedamobe! This was potentially fixed with https://github.com/payloadcms/payload/pull/1592 which is yet to be released. I'll post an update here once that happens to see if it resolves your issue.

**Comment by tobedamobe** [comment]
Thank you so much! Looking forward to it...

**Comment by jmikrut** [comment]
Hey @tobedamobe — this has now been released. Give it a go!

**Comment by tobedamobe** [comment]
Love it @jmikrut!!! Works like a charm! :D Thank you so much!!!!
