### ISSUE TITLE
RichText editor throwing error Uncaught Error: [Slate] editor is invalid! you passed:{"children":[],"operations":[],"selection":null,"marks":null,"history":{"undos":[],"redos":[]}}

### ISSUE THREAD

**Issue by alexthegoodman** [payloadcms/payload#1604]
# Bug Report

After updating my field configuration for the Posts collection, this error began displaying on Post edit and create pages. I'm not sure why it would start appearing but any help would be appreciated! Thank you

<img width="1975" alt="Screen Shot 2022-12-06 at 9 59 26 AM" src="https://user-images.githubusercontent.com/746071/205946792-55b030b5-3d43-4fab-b37b-cd2ef81dbfcd.png">

## Steps to Reproduce

```
import { CollectionConfig } from "payload/types";

const Posts: CollectionConfig = {
  slug: "posts",
  admin: {
    defaultColumns: ["title", "author", "category", "tags", "status"],
    useAsTitle: "title",
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: "title",
      type: "text",
    },
    {
      name: "slug",
      type: "text",
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "author",
      type: "relationship",
      relationTo: "users",
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "publishedDate",
      type: "date",
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "category",
      type: "relationship",
      relationTo: "categories",
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "tags",
      type: "relationship",
      relationTo: "tags",
      hasMany: true,
      admin: {
        position: "sidebar",
      },
    },
    {
      name: "content",
      type: "richText",
    },
    {
      name: "status",
      type: "select",
      options: [
        {
          value: "draft",
          label: "Draft",
        },
        {
          value: "published",
          label: "Published",
        },
      ],
      defaultValue: "draft",
      admin: {
        position: "sidebar",
      },
    },
  ],
};

export default Posts;
```

## Other Details

Payload Version: 1.2.3

**Comment by jmikrut** [comment]
Hey @alexthegoodman — I'm willing to bet that you may have changed your schema from a `text` field to a `richText` or similar somewhere. If so, you will need to write a migration script to take your old text / textarea / etc. content and convert it into the SlateJS rich text JSON shape. Right now, I am guessing that Payload is attempting to pass a string to a rich text field, which is not valid for the rich text field's expectations.

Is this what you think may have happened?

**Comment by alexthegoodman** [comment]
@jmikrut Not in this case. I only added the `slug` text field, but didn't convert any fields. It looks like this error displays for any Rich Text field, including new ones. It goes away if I remove all the Rich Text fields.

**Comment by jmikrut** [comment]
Does your database contain anything for the `content` field? Maybe left over?

I can use this exact collection with no issues at all so I'm thinking it's definitely something with your database having old data.

**Comment by alexthegoodman** [comment]
@jmikrut The error disappeared after upgrading to 1.2.5! Thank you for looking into it.

**Comment by iakshay** [comment]
Spent bunch of time on this, the solution that worked for me was deleting `node_modules` and reinstalling dependencies.

**Comment by bemayr** [comment]
I just had this problem as well and wanted to document the change that introduced it in this issue (I know it is closed, it is mainly for reference if somebody stumbled over this.

For me, the problem arose after switching from *pnpm* to *npm*, I had `slate` referenced like this in my package.json:

```json
    "slate": "^0.94.1"
```

After reverting back to `^0.91.4` (as in Payload CMS) everything worked again.

So @jmikrut, at first it felt extremely weird to me as well, but now I am 99% sure that it has got to do something with a newer `slate` version.
