### ISSUE TITLE
Relationship field filterOptions data object is outputting array fields without an array

### ISSUE THREAD

**Issue by gamellis** [payloadcms/payload#1605]
# Bug Report

Using the `data` object in a filterOptions like: 

```
{
     name: 'item',
     type: 'relationship',
     relationTo: 'ingredients',
     filterOptions: ({ data }) => {
     …
}
  
```

returns arrays as compound keys like:

```instructions.0.ingredient.0.id = ‘…’```

I expected the data object to return the array and group fields in arrays.

Docs:
https://payloadcms.com/docs/fields/relationship#filtering-relationship-options

## Steps to Reproduce

1. Create a group or array field with some fields.
2. Use a relationship field and a filterOption to access the data object of the current document

## Other Details

Payload: 1.2.4

Thanks for all your amazing work!

**Comment by jacobsfletch** [comment]
@gamellis great catch! I've got this a PR out for this right now. It was a pretty simple change. Thank you!

**Comment by gamellis** [comment]
@jacobsfletch Awesome, that's great! 🙂  I'll close the issue and watch your PR 👍

**Comment by gamellis** [comment]
Oops! I misunderstood. I thought this was a duplicate 😆
