### ISSUE TITLE
Provide search functionality

### ISSUE THREAD

**Issue by sampittko** [payloadcms/payload#161]
# Missing search functionality

Documentation is pretty robust and there is no way to browse quickly through it.

## Additional Details

`cmd + K` shortcut should display dialog with search bar and results that link to the destination with discovered information (e.g. [TailwindCSS](https://tailwindcss.com)).

**Comment by jmikrut** [comment]
Hey @sampittko — you will be happy to hear that we are actually almost done implementing Algolia Docsearch which is exactly what Tailwind uses!

Going to move this to a Discussion until we launch the search. Until then, keep an eye out!
