### ISSUE TITLE
Select with hasMany and localized is broken

### ISSUE THREAD

**Issue by cmngan** [payloadcms/payload#1610]
# Bug Report

I created a field, which is select with hasMany and localized are true. When save, it shows error: 
`[03:17:56] ERROR (payload): CastError: Cast to string failed for value "[ 'hollowSquare', 'classroom' ]" (type Array) at path "en-gl"`
Which `en-gl` is the locale, and 'hollowSquare', 'classroom' are the selected items. 

Sometimes, not sure how, it can be created. However, after editing some other fields, the select will become null. All previous input data are gone. 

## Steps to Reproduce

1. Enable localized
2. Add a field as below:
```
    {
      name: "functionRoomSetups",
      type: "select",
      options: [
        { value: "foo", label: "Foo" },
        { value: "boo", label: "Boo" },
      ],
      hasMany: true,
      localized: true,
    },
```
3. Create a record and enter the field
4. It fails to create. If it can, try to edit other fields and save. It will become empty after refresh.

## Other Details
Payload version: 1.2.4
Browser: Edge

**Comment by JarrodMFlesch** [comment]
Hey @cmngan! Can you try updating to v1.2.5, we merged some bug fixes specifically for relationship fields in that version.

**Comment by cmngan** [comment]
@JarrodMFlesch 
After updated to v1.2.5, the result is the same. 
Once I save, the value will become null. Although the admin ui is showing the correct value.
So if i edit some other fields and save, then refresh, the select field will become empty.

**Comment by JarrodMFlesch** [comment]
@cmngan ok, we will sort this out today 👍

**Comment by DanRibbens** [comment]
I was able to reproduce the issue.
