### ISSUE TITLE
Draft posts that's never published cannot be queried with slug operator anymore in 1.2.4

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#1611]
# Bug Report

## Steps to Reproduce

1. upgrade payload to 1.2.5 in public-demo
2. create a draft only post which never been published
3. query posts with two different queries

```
# Write your query or mutation here
query getPages {
  Posts(draft: true, where:{ title:{equals: "Draft only post"} }) {
    docs{
      title
      _status
      updatedAt
    }
  }
  allPosts: Posts(draft: true) {
    docs {
      title
      _status
      updatedAt
    }
  }
}
```

<img width="1739" alt="image" src="https://user-images.githubusercontent.com/5801015/206092316-49af6828-4573-4413-84c4-ea2b44de19bd.png">

4. as a contrast, it still works with 1.1.26 in online demo

https://demo.payloadcms.com/api/graphql-playground

<img width="1596" alt="image" src="https://user-images.githubusercontent.com/5801015/206092477-c32d48e5-786d-4423-9e03-b00d21abbb9d.png">

## ~~Steps to Reproduce~~

1. create multiple posts, 
<img width="987" alt="image" src="https://user-images.githubusercontent.com/5801015/206091357-7d717c7f-158e-413b-ae64-787c3bbaa6c0.png">

4. write a query in playground to fetch draft articles
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/5801015/206090612-fb2963ba-3afd-4189-9434-5c46eb30ac64.png">

```
query {
  Articles(draft: true, where:{ slug:{ like:"new-article-never-published"  } }) {
    docs {
      title
      slug
      _status
    }
  }
}
```

6. add a slug operator to filter the target slug `new-article-never-published-2`

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/5801015/206090896-48716f18-a1c4-4a8f-9563-d1642839d2f9.png">

7. try to use like operator instead

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/5801015/206091142-26c8e2e5-b372-468d-a5d7-de7c1315a749.png">

**Comment by JarrodMFlesch** [comment]
I would say 6 & 7 are the only potential bugs here, right? For the first example, the title you are attempting to match differs from the titles that are actually available "Draft only post" vs "Test draft only".

For 6, I do agree, it should return the matching doc.

For 7, I also agree, I do think the doc _should_ appear. As for the other ones appearing, we need to thread the where query through when we are replacing docs it looks like.

Do you agree with the above?

**Comment by jmikrut** [comment]
Hey @Stupidism — thank you, seriously, once again for your diligence here.

We just merged a fix that resolves this. Will be released shortly!!
