### ISSUE TITLE
Query Operators bug: does not support contains

### ISSUE THREAD

**Issue by zhounewz** [payloadcms/payload#1621]
# Bug Report

### Query Operators bug: does not support contains
<img width="1883" alt="image" src="https://user-images.githubusercontent.com/16400882/206346408-5de5c137-57f9-431a-a495-38c354328dbc.png">

<img width="748" alt="image" src="https://user-images.githubusercontent.com/16400882/206346738-530eefa8-e477-4099-bddf-d31407d9b2b2.png">

**Comment by JarrodMFlesch** [comment]
Hey @zhounewz using graphql with relationships is a known limitation and is on our roadmap to tackle. You can read more about it in the discussion [here](https://github.com/payloadcms/payload/discussions/761)! 👍 

I will be closing this issue, since we will be addressing it at a later date.
