### ISSUE TITLE
Wrong translation key in "Confirm revert to publish state" modal?

### ISSUE THREAD

**Issue by bombnp** [payloadcms/payload#1626]
# Bug Report

When trying to reverted a changed document (in a version and draft enabled collection), the modal shows the following:
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/24814968/206503116-73f88a5b-b023-4e1c-8a7b-e6da370880ad.png">  
  
The "published" button seems out of place. Likely a wrong translation key?

## Steps to Reproduce

1. Go to [Payload Demo](https://demo.payloadcms.com) website
2. Select a collection with versions and draft enabled (like Pages)
3. Publish a page document
4. Edit that document in a field, then save it. This should cause the document's state to change to "Changed" on the sidebar.
5. Click "Revert to published"
6. You should see the wrong button text ("published")

## Other Details

Code is located at `src/admin/components/elements/Status/index.tsx` at line 177.
  
Key should probably be "cancel" or something.

**Comment by DanRibbens** [comment]
You are correct, that should be "cancel". I will fix it.

**Comment by DanRibbens** [comment]
Released in v1.3.0.

Some of the translation files are out of date. Will need to be updated.
