### ISSUE TITLE
Closing a modal with the escape key stops modal from opening again

### ISSUE THREAD

**Issue by gamellis** [payloadcms/payload#1629]
# Bug Report

Hey! I've been using the modal library shipped in Payload (which has given a nice productivity gain, excellent work!). I noticed that when I use the escape key to close the modal, it stops it from opening again. I jumped on the demo site to confirm it wasn't something I changed with the modal, and it seems like the bug is present there too.

## Steps to Reproduce

1. Log into the [demo site](https://demo.payloadcms.com)
2. Open up one of the posts and click on the upload button in the rich text editor
3. Press escape to close the modal
4. Click on the upload button to open

Thanks for all your amazing work!

**Comment by jacobsfletch** [comment]
@gamellis this does appear to be a bug, I was able to replicate this locally on the latest branch. At first glance, `esc` is not fully unmounting the modal, I can see it's html leftover in the DOM. I will look into this deeper and get everything sorted. Huge thanks for the report!

**Comment by jacobsfletch** [comment]
@gamellis this is fixed in PR https://github.com/payloadcms/payload/pull/1668!
