### ISSUE TITLE
Image field returning null in GraphQL when value is present

### ISSUE THREAD

**Issue by alexthegoodman** [payloadcms/payload#1634]
# Bug Report

The Image fields are returning null in GraphQL when values are set.

GraphQL call:
<img width="1624" alt="Screen Shot 2022-12-08 at 7 35 57 PM" src="https://user-images.githubusercontent.com/746071/206595951-28d87c78-ff40-4414-81e1-9be6eb460f9d.png">

Database values:
<img width="1428" alt="Screen Shot 2022-12-08 at 7 36 17 PM" src="https://user-images.githubusercontent.com/746071/206595946-608b9247-2b43-4d8d-9f9d-8c964034a23d.png">

I can also verify that the media is properly displaying in the admin panel. However, the `image` and `featuredImage` fields are null in GraphQL.

## Steps to Reproduce

1. Create Posts collection with associated image fields
2. Populate images via admin panel
3. Make call from GraphQL API

## Other Details

Payload Version: 1.2.5

Thank you for your help!

**Comment by JarrodMFlesch** [comment]
Hey @alexthegoodman I am unable to repro this issue, do you by chance have any access control setup for these fields that  would prevent them from being populated? Does the REST response include them for you if you click the "api url" link when viewing one of your posts?

![Screen Shot 2022-12-09 at 8 45 36 AM](https://user-images.githubusercontent.com/30633324/206716629-f0ee8ca7-b282-436b-bc44-3f09697340c3.png)

**Comment by alexthegoodman** [comment]
I have only set:
```
access: {
    read: () => true,
  },
```
on the Posts. The image(s) comes through the REST API:
<img width="1631" alt="Screen Shot 2022-12-09 at 6 18 25 PM" src="https://user-images.githubusercontent.com/746071/206810807-b3c58abd-4570-4046-8f04-ddb5e9bb4ae9.png">

I upgraded to the latest Payload, but the image still returns null on the GraphQL API.

My concern with using the REST API is that I need to get my post via the slug field. Therefore I tried `http://0.0.0.0:3000/api/posts?where[slug][equals]=post-x` but that does not include the file URLs:
<img width="1540" alt="Screen Shot 2022-12-09 at 6 37 14 PM" src="https://user-images.githubusercontent.com/746071/206812500-2d142046-055f-44cb-bee1-c39a20f7acf7.png">

Is there any way to include the file URLs on that response?

**Comment by JarrodMFlesch** [comment]
I'm not saying you need to use rest for this, but want to validate that you can retrieve the same data. To get the image data you need to increase the depth of your request, add a query param 'depth=2" and let's see what data you get back?

**Comment by alexthegoodman** [comment]
@JarrodMFlesch At first, nothing more was coming back with the `depth` param. But after reading more of the docs, I was inspired to add the
```
access: {
    read: () => true,
  },
```
to the Media collection as well. Now the `depth` param is working! The data is coming through GraphQL now as well.

Thank you for your help!

**Comment by JarrodMFlesch** [comment]
Ah beautiful! Yeah that makes sense, the default access control if not set checks to see if a user is on the request. Glad you got it figured out 👍
