### ISSUE TITLE
'Dashboard' redirects to /admin instead of custom route

### ISSUE THREAD

**Issue by damtzi** [payloadcms/payload#1652]
# Bug Report
If you modify the admin panel's route and then in the admin panel navigate to the main dashboard by clicking 'Dashboard' you'll end up with a blank screen, because it redirects you to /admin.

## Steps to Reproduce
1. Create a payload app `npx create-payload-app`
2. Modify the admin path in `payload.config.ts` to '/foo'
3. Start payload `yarn dev` and navigate to `http://localhost:3000/foo`
4. Navigate to a nested route `http://localhost:3000/foo/collections/todos`
5. Click 'Dashboard' at the top of the screen which will redirect you to `http://localhost:3000/admin`
<img width="714" alt="Screenshot 2022-12-12 at 22 10 57" src="https://user-images.githubusercontent.com/37114132/207155310-ae1a130e-9aba-4ccf-a918-31e65e5303c6.png">

## Other Details
I believe the issue is on line 39 in this file -> https://github.com/payloadcms/payload/blob/master/src/admin/components/elements/StepNav/index.tsx. I noticed you already have a `useConfig` hook, which returns user's custom config, so replacing "/admin" with `${admin}` should fix this. Haven't seen this in any other part in the repo.

Happy to make a PR for this later this week if needed! 😃

**Comment by jmikrut** [comment]
Hey @damtzi — good find and yes, I agree with your proposed solution!

If you are up for a PR, that would be awesome! Otherwise I can have one of our team resolve this within the next few days as well. Could be a good one to get you on the list of contributors though 💰

**Comment by jmikrut** [comment]
Fixed with #1653 1653
