### ISSUE TITLE
Upload fields lose values when using async operations in validate function

### ISSUE THREAD

**Issue by svntime** [payloadcms/payload#1658]
# Bug Report

Hi! I try to make a gallery field with images validation (width, height and mimeType). My current approach looks like this:

```
export default buildConfig({
  serverURL: process.env.SERVER_URL,
  rateLimit: {
    skip: () => true
  },
  collections: [
    {
      slug: 'projects',
      fields: [
        {
          type: 'array',
          name: 'gallery',
          fields: [
            {
              type: 'upload',
              name: 'image',
              relationTo: 'media',
              required: true,
              validate: async (imageId, options) => {
                // call the default validation if something is missing
                if (!options || !imageId) {
                  return upload(imageId, options);
                }

                // get Media document with local API (server-side) or with fetch (client-side)
                if (options.payload) {
                  await options.payload.findByID({ id: imageId, collection: 'media' });
                } else {
                  const response = await fetch(/api/media/${imageId});
                  await response.json();
                  // await new Promise((res) => setTimeout(res, 20));
                }

                return true;
              }
            }
          ]
        }
      ]
    },
    {
      slug: 'media',
      admin: {
        useAsTitle: 'filename'
      },
      upload: {
        staticDir: path.resolve(__dirname, '../../media'),
        mimeTypes: ['image/*']
      },
      fields: [
        {
          name: 'alt',
          label: 'Alt Text',
          type: 'text'
        }
      ]
    }
  ]
});
```

However, when I use **client-side** fetch (or just simulate a request with simple sleep set to 20ms) to retrieve the details of media item, the selected images disappear in project edit view. 

Here is a video demonstrating the problem: https://streamable.com/n2yg5h

## Steps to Reproduce

1. use provided buildConfig
2. go to `/admin/collections/projects/create` and press `Add Gallery` button twice
3. upload new media in `Gallery 01` field
4. select already existing media in `Gallery 02` field (probably doesn't matter, you can also upload a new file)
5. click 'Save' button

Payload should redirect you to the project edit view and fields inside gallery should be empty as in the provided video. It doesn't matter if I use fetch or simulate request with simple sleep (however, there is a difference between 10ms and 20ms in setTimeout). 

To fix this you can comment out the `else` block inside validate function.

```
else {
   const response = await fetch(/api/media/${imageId});
   await response.json();
   // await new Promise((res) => setTimeout(res, 20));
}
```

## Other Details

Payload version: 1.3.0
Discord post: https://discord.com/channels/967097582721572934/1052189867179782144

**Comment by DanRibbens** [comment]
I looked into this with @PatrikKozak.

The field component validate function is getting called with a `value` of `undefined`. This only happens when the field is nested inside an array or group. 

I tried a few tweaks to src/admin/components/forms/useField/index.tsx to see if we can skip validation as it seems to be called too many times.
