### ISSUE TITLE
Incorrect schema for field of type "group" prevents translation of admin.description

### ISSUE THREAD

**Issue by svntime** [payloadcms/payload#1663]
# Bug Report

Schema for the `group` field only allows strings in `admin.description`, which is not compatible with the i18n update for admin panel. 

![image](https://user-images.githubusercontent.com/42152930/207437699-91e3b939-9f0c-47b7-ae2b-1f3e68a0674a.png)

I manually removed this override to allow the application to compile and I can confirm that the object here is supported (translations were displayed correctly depending on user's language).

## Steps to Reproduce

1. use following buildConfig:

```
export default buildConfig({
  localization: {
    defaultLocale: 'en',
    locales: ['en', 'pl'],
    fallback: true
  },
  collections: [
    {
      slug: 'news',
      fields: [
        {
          type: 'group',
          name: 'section1',
          admin: {
            description: {
              en: 'Lorem ipsum dolor EN',
              pl: 'Lorem ipsum dolor PL'
            }
          },
          fields: [
            {
              type: 'text',
              name: 'title'
            }
          ]
        }
      ]
    }
  ]
});
```
2. run `yarn dev`

You should see following error messsage:

![image](https://user-images.githubusercontent.com/42152930/207439187-f97e9493-8bb9-4def-8f9d-804468c157ae.png)

## Other Details

payload version: 1.3.0

I think that removing the `description` override from https://github.com/payloadcms/payload/blob/master/src/fields/config/schema.ts#L240 should fix this problem.

**Comment by DanRibbens** [comment]
> I think that removing the description override from [master/src/fields/config/schema.ts#L240](https://github.com/payloadcms/payload/blob/master/src/fields/config/schema.ts?rgh-link-date=2022-12-13T21%3A00%3A57Z#L240) should fix this problem.

That is accurate. I'm not sure why that field was given it's own `description` different from the inherited type, but it isn't needed.
