### ISSUE TITLE
Autosave is broken

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/payload#1687]
# Bug Report

Saving a Draft fails with the error:
`
There was an error while creating a draft Blog with ID 639ce1b9bfef43f47a6c4d68.
 _blogs_versions validation failed: version.card.description: Cast to Embedded failed for value "s" (type string) at path "description" because of "ObjectExpectedError"
ValidationError: _blogs_versions validation failed: version.card.description: Cast to Embedded failed for value "s" (type string) at path "description" because of "ObjectExpectedError"
`
and
`
TypeError: Cannot read properties of undefined (reading 'version')
`

## Steps to Reproduce

Just created a new document. It said it autosaved, but when going to the overview, then to this entry again, all changes I made were gone.
It works when disabling autosave and manually saving as draft.

## Other Details

Payload v.1.3.2 & v1.3.3

**Comment by jmikrut** [comment]
Thanks for the report @johannesschaffer — this is now fixed and will be released shortly. 👍
