### ISSUE TITLE
Radio Field with required false is not working

### ISSUE THREAD

**Issue by cmngan** [payloadcms/payload#1701]
# Bug Report

Create a radio field with required false, it will always required user input. Expected it is allowed to not inputting anything.

## Steps to Reproduce

1. Create a radio field with required false
```
          {
            name: "robotsIndex",
            type: "radio",
            options: [
              { label: "index", value: "index" },
              { label: "noindex", value: "noindex" },
            ],
            required: false,
          },
```
2. Click save
3. Error shown
![image](https://user-images.githubusercontent.com/20035088/208335186-9dccd379-8de8-43b6-890f-7a2fd3784f6d.png)

## Other Details

Payload: 1.3.4

**Comment by JarrodMFlesch** [comment]
Hey @cmngan, just merged a fix for this. It will go out with the next release 👍
