### ISSUE TITLE
Tabbed fields with common names reflect the same data.

### ISSUE THREAD

**Issue by ubercoolchicken** [payloadcms/payload#1712]
# Bug Report
When you use field type: 'tabs' and create a data point with the same name under both the tabs, the data isn't getting encapsulated.

## Steps to Reproduce

1. Use this Collection
const ExampleCollection: CollectionConfig = {
slug: 'example-collection'
  fields: [
    {
      type: 'tabs',
      tabs: [
        {
          label: 'Tab One',
          fields: [
            {
              name: 'foo',
              type: 'checkbox',
              label: 'Box 1',
              defaultValue: false,
            },
          ]
        },
        {
          label: 'Tab Two',
          fields: [
            {
              name: 'foo',
              type: 'checkbox',
              label: 'Box 2',
              defaultValue: false,
            },
          ]
        }
      ]
    }
  ]
}

2. Run Payload
3. Change first Checkbox, the second one will reflect the same value

## Other Details
Workaround: Use different names
According to the support documentation for Tabs, data should be accessible via {tabname}.{fieldname} but for some reason, it's not getting stored in the same way. Not sure if it's a conscious decision though.

**Comment by jmikrut** [comment]
Hey @ubercoolchicken — you need to add a `name` to your tabs if you want them to act as the "group" field and nest their child fields.

So for example, your `Tab One` would need to be formatted like this:

```
{
  label: 'Tab One',
  name: 'tabOne', // this prop forces the "tab" to act like a "group"
  fields: [
    // etc. 
    // Now the fields here will be `tabOne.fieldName`
  ]
}
```
