### ISSUE TITLE
Page is breaking when cleaning up upload order desc

### ISSUE THREAD

**Issue by cmngan** [payloadcms/payload#1736]
# Bug Report

Page is breaking when users click on the close icon in order desc in upload collection.

## Steps to Reproduce

1. Go to upload collection, e.g media collection
2. Click sort, click x in descending
<img width="835" alt="image" src="https://user-images.githubusercontent.com/20035088/208883898-b19015f7-003b-431b-a7d7-b2b23846c776.png">
3. Page is broken, i.e. become blank page

**Comment by jacobsfletch** [comment]
I was able to recreate this on my end and will get it patched up shortly. Thank you for the report @cmngan!
