### ISSUE TITLE
SVG files does not contain WIDTH / HEIGHT props after upload to S3

### ISSUE THREAD

**Issue by quornik** [payloadcms/payload#1738]
# Bug Report

SVG files uploaded via S3 adapters does not return width & height of the file. This functionality worked as usual prior to the PayloadCMS version 1.2

## Steps to Reproduce

I've tested importing via payload-s3-upload as well as with plugin-cloud-storage, and both are at this point returning the same error. File is written to the database, and the file is present on the S3 static hosting, however REST API endpoint does not return dimensions, and they are not written to the file props

this is what API returns at this point:
```
"id": "63a2f8a9508fc649ef3acd6a",
"filename": "icon-test-2.svg",
"mimeType": "image/svg+xml",
"filesize": 1526,
"createdAt": "2022-12-21T12:14:33.643Z",
"updatedAt": "2022-12-21T12:14:33.643Z",
```

and this is the exact same file, but uploaded while PayloadCMS was in earlier version, propably 1.1:
```
"id": "6366c56af92dec48d51193be",
"filename": "icon-test-1.svg",
"mimeType": "image/svg+xml",
"filesize": 1526,
"width": 24,
"height": 24,
"alt": "ikona kafla",
"createdAt": "2022-11-05T20:19:54.212Z",
"updatedAt": "2022-11-05T20:19:54.212Z",
```

## Other Details
```
"dependencies": {
    "@payloadcms/plugin-seo": "^1.0.9",
    "cross-env": "^7.0.3",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "nodemailer": "^6.8.0",
    "nodemailer-sendgrid": "^1.0.3",
    "payload": "^1.3.4",
    "payload-s3-upload": "^1.1.2"
  },
```

**Comment by jmikrut** [comment]
Hey @quornik — good call. Will be fixed shortly. Thanks for the report!

**Comment by quornik** [comment]
You welcome @jmikrut!
