### ISSUE TITLE
All the upload fields on a document page get broken, when any previously assigned media asset gets deleted

### ISSUE THREAD

**Issue by jankocian** [payloadcms/payload#1739]
# Bug Report
When you delete a previously assigned media file, it breaks all the upload files in related documents. 

The upload fields will allow to choose, but won't show any feedback that a file was actually selected. The field area remains empty after upload/selection. Though it seems like the selected file actually does get saved.

## Steps to Reproduce
1. Choose/upload a media file in any document's upload field.
2. Go to your media collection and delete the media file.
3. Go back to your document page and see the upload fields broken, after selecting a new media.

**Comment by jacobsfletch** [comment]
@jankocian I have reproduced this, thank you for the report! We'll have a fix for this soon.
