### ISSUE TITLE
Reordering array items with richtext leads to their content being overwritten if one entry was already there (published) and one is new (only autosaved)

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/payload#1747]
# Bug Report
E.g.
1: Content 1 - Published
2: New item - Autosaved
=> No drag item 2 before 1, and it will be overwritten with "Content 1 - Published"

**Comment by jmikrut** [comment]
Hey @johannesschaffer — thanks for the report! This was actually a newly introduced rich text field problem unrelated to autosave but it's fixed and will be released shortly!
