### ISSUE TITLE
Rich Text fields incorrectly set form to modified when clicking into them

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/payload#1761]
# Bug Report

That's still not fixed in 1.4?! I think it works in normal fields, but in arrays -> richtext it doesn't. Even just setting the cursor inside the richtext (which is inside an array) instantly reverts it from published to saved

# Other
It is by no means a priority to fix, just noticed it...

**Comment by jmikrut** [comment]
Hey @johannesschaffer — this is actually something different. I have updated the issue to reflect the actual issue and will investigate shortly!

**Comment by jmikrut** [comment]
@johannesschaffer this is now fixed and released in patch `1.4.1`.

Good catch. Slate has lots of "gotchas" but this one was relatively straightforward.

Relevant Slate issue:
https://github.com/ianstormtaylor/slate/issues/3567

We want to be as diligent as possible with resolving actual issues so feel free to bring it on 😎

**Comment by johannesschaffer** [comment]
This is a bit unrelated 🙈, but I'm doing a React project in the near future which involves a text editor and I was planning to use Slate, given its popularity. Would you recommend a different editor then, if Slate has so many hickups?
