### ISSUE TITLE
demo.payloadcms - runtime type error when creating a new alert 

### ISSUE THREAD

**Issue by k-sav** [payloadcms/payload#1762]
# Bug Report

## Steps to Reproduce

1. Visit https://demo.payloadcms.com and login
2. Click on **Alerts** in the sidebar menu
3. Click on **Create New Alert**

Causes an unrecoverable WSOD due to runtime type error 
> Cannot read properties of undefined (reading 'label')

## Other Details

**Browser**
Chrome - Version 108.0.5359.124 (Official Build) (x86_64)

**Comment by DanRibbens** [comment]
This was caused by having a `defaultValue` that was not in the options. I changed the code in the public demo:
https://github.com/payloadcms/public-demo/commit/c82bcade77ca1c3648c9adf46c183689f1988027

I also made a change in Payload so that the UI will not crash when this happens.
