### ISSUE TITLE
Date field cannot be cleared

### ISSUE THREAD

**Issue by sjj1991** [payloadcms/payload#1765]
# Bug Report

## Steps to Reproduce

1. Enter a date and click Save.
2. Click on X button on date field.
3. Date field is not cleared.
4. Press backspace in date field.
5. Date field is also not cleared.

## Other Details

Collection config
```
{
      name: "endDate",
      type: "date",
      admin: { date: { pickerAppearance: "monthOnly" } },
},
```

<img width="743" alt="image" src="https://user-images.githubusercontent.com/7578460/209433860-50459b62-c9d0-479d-9ac6-f6648f86de14.png">

`"payload": "^1.4.1",`
`Safari 16.2`

**Comment by jacobsfletch** [comment]
Thanks @sjj1991! I've this fixed in #1766 but I'd like to also add some e2e testing coverage to prevent regression going forward.
