### ISSUE TITLE
Can't get the API key working

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/payload#1769]
# Bug Report

Trying the access the url `http://localhost:3000/api/projects/` with the header
`Authorization: User API-Key f456e511-ee1f-4a1e-821e-9c4ff2cb7c6f` always returns
`You are not allowed to perform this action`. I didn't change the default Users collection for authorization

**Comment by DanRibbens** [comment]
We had a breaking change with the API key auth header. It is now the slug instead of the label.

**Comment by johannesschaffer** [comment]
Thanks. In this case, the documentation (https://payloadcms.com/docs/authentication/config#api-keys) should be updated

**Comment by DanRibbens** [comment]
> Thanks. In this case, the documentation ([payloadcms.com/docs/authentication/config#api-keys](https://payloadcms.com/docs/authentication/config#api-keys)) should be updated

Ah, yes. The docs on the site weren't updated. We'll take care of it.

Thanks!
