### ISSUE TITLE
"hash" as field name causes it to be empty

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#1777]
Giving a field of type "text" the name "hash", it turns empty when adding a text to the field. No warnings or errors.

This is what my collection looks like:
```ts
import { CollectionConfig } from 'payload/types';
import {commonAccessControlWithoutCreateAbility} from "../../Common";


const FingerprintedUsers: CollectionConfig = {
    slug: 'a_fingerprinted_users',
    admin: {
        useAsTitle: 'hash',
        group: "📈 Analytics"
    },
    access: commonAccessControlWithoutCreateAbility,
    fields: [
        {
            name: 'hash',
            label: 'Hash',
            type: 'text',
            required: true,
        },
        {
            name: 'request_count',
            label: 'Request Count',
            type: 'number',
            required: true,
        },
    ],
};

export default FingerprintedUsers;
```

Simply renaming the field to something other than "hash" fixes it

**Comment by jacobsfletch** [comment]
@AlessioGr nice find! It looks like `hash` is among a list of reserved field names that Payload strips during config sanitization [here](https://github.com/payloadcms/payload/blob/49fa5cb23a0bb57348d8cd7ec0b7805d651fda2d/src/utilities/sanitizeInternalFields.ts#L3). So the real issue here is a lack of documentation. I opened a PR for this just now!

**Comment by AlessioGr** [comment]
@jacobsfletch @jmikrut What about making it throw a warning/error during building when it detects a reserved block? Would make the issue more apparent compared to just adding it to the docs, as it still takes a bit to figure out that the name in fact was the issue if it happens

**Comment by jacobsfletch** [comment]
@AlessioGr I think this is a great idea!
