### ISSUE TITLE
Express-fileupload options

### ISSUE THREAD

**Issue by EKMN** [payloadcms/payload#180]
# Documentation Issue

The default upload behaviour is to load everything to memory. This is not really feasible when dealing with large files.

Further, the [docs](https://github.com/payloadcms/payload/blob/master/docs/upload/overview.mdx#payload-wide-upload-options) are confusing. It is implied that all valid `express-fileupload` options (like `useTempFiles`) are supported, however adding anything but `upload.limits.fileSize` throws an error due to validation failure.

If this limited behaviour is intended, then the docs should probably reflect that.

## Additional Details

none

**Comment by denolfe** [comment]
Thank you for the report @EKMN! We'll look into either supporting all options or a subset, then updating the docs accordingly.

**Comment by jmikrut** [comment]
Hey @EKMN —

Good call here. Just some bad schema validation. All `express-fileupload` options are available for your use and are now validated / typed accordingly.

Give the new version a shot and thank you!
