### ISSUE TITLE
Pino dependencies with Yarn 2+

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#1803]
# Bug Report

Pino's loading of pino-pretty is non-standard, which causes issues when starting payload with Yarn 2+

```
C:\Projects\payload-test\.pnp.cjs:27062
      Error.captureStackTrace(firstError);
            ^
Error: pino tried to access pino-pretty, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: pino-pretty
Required by: pino@npm:6.14.0
```

## Steps to Reproduce

1. Ensure yarn 2.X is default
2. Create new project with create-payload-app
3. Run `yarn dev`

## Other Details

We should adjust our usage as detailed here: https://github.com/pinojs/pino/issues/1106

**Comment by jacobsfletch** [comment]
Related discussion here: https://discord.com/channels/967097582721572934/1060201465907511377/1060201465907511377

**Comment by jacobsfletch** [comment]
Resolved with https://github.com/payloadcms/payload/pull/1890
