### ISSUE TITLE
Version 1.5.1 export error

### ISSUE THREAD

**Issue by kresogalic8** [payloadcms/payload#1806]
I've updated to the latest version and i got this error

<img width="1407" alt="Screenshot 2023-01-04 at 21 16 04" src="https://user-images.githubusercontent.com/7289406/210641893-66889851-076e-4971-b1bc-994f2dc220ae.png">

**Comment by jacobsfletch** [comment]
@kresogalic8 this was resolved in `v1.5.2`. Go ahead and bump to that version and try again!

**Comment by kresogalic8** [comment]
Resolved, thanks guys
