### ISSUE TITLE
Localized blocks fields have their content deleted in other languages upon reordering

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#1808]
# Bug Report

I have the following localization setup in my `payload.config.ts`:

```ts
localization: {
	locales: ["en", "es"],
	defaultLocale: "en",
	fallback: true,
},
```

In my `globals/about.ts`, I have:

```ts
import { GlobalConfig } from "payload/types";

export const About: GlobalConfig = {
	slug: "about",
	label: "About Page",
	fields: [
		{
			name: "blocks",
			type: "blocks",
			blocks: [
				{
					slug: "entry",
					fields: [
						{
							name: "text",
							type: "text",
							localized: true,
						},
					],
				},
			],
		},
	],
};
```

Then, in the admin, I add some content in English, like this:

```json
{
	"blocks": [
		{
			"text": {
				"en": "one english"
			},
			"id": "63b6a7b23f3abe08beb4cd75",
			"blockType": "entry"
		},
		{
			"text": {
				"en": "two english"
			},
			"id": "63b6a7bb3f3abe08beb4cd76",
			"blockType": "entry"
		}
	]
}
```

…after that, I also add content in Spanish:

```json
{
	"blocks": [
		{
			"text": {
				"en": "one english",
				"es": "one spanish"
			},
			"id": "63b6a7b23f3abe08beb4cd75",
			"blockType": "entry"
		},
		{
			"text": {
				"en": "two english",
				"es": "two spanish"
			},
			"id": "63b6a7bb3f3abe08beb4cd76",
			"blockType": "entry"
		}
	]
}
```

Up to this point, everything works as expected. However, if I switch the language back to English and put entry two above entry one, the Spanish values are now missing:

```json
{
	"blocks": [
		{
			"text": {
				"en": "two english"
			},
			"id": "63b6a7bb3f3abe08beb4cd76",
			"blockType": "entry"
		},
		{
			"text": {
				"en": "one english"
			},
			"id": "63b6a7b23f3abe08beb4cd75",
			"blockType": "entry"
		}
	]
}
```

## Steps to Reproduce

1. Set up localization
2. Add a blocks field with a nested localized field
3. Add content in one language
4. Add content in another language
5. Reorder the blocks
6. The content disappears in the other language

## Other Details

Before reordering, I made sure to do a hard refresh of the page, to make sure that it's not a front-end issue (due to bad state or something).

Payload version: **1.5.2**

**Comment by jmikrut** [comment]
Thanks for the detail here, as always. Very helpful for us when we try and reproduce. This one and #1809 are going to be reproduced / addressed very shortly!

**Comment by jmikrut** [comment]
@hdodov your very detailed descriptions made this a super quick one to fix and I have to say one again THANK YOU for being thorough with your reporting. This will be released shortly!
