### ISSUE TITLE
Field loses default value after being marked as localized and receiving content

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#1809]
# Bug Report

I have the following localization setup in my `payload.config.ts`:

```ts
localization: {
	locales: ["en", "es"],
	defaultLocale: "en",
	fallback: true,
},
```

In my `globals/about.ts`, I have:

```ts
import { GlobalConfig } from "payload/types";

export const About: GlobalConfig = {
	slug: "about",
	label: "About Page",
	fields: [
		{
			name: "title",
			type: "text",
		},
	],
};
```

Upon saving the field, I get the following in MongoDB, as expected:

```json
{
	"title": "About Us"
}
```

Then, I enabled localization for the field:

```ts
{
	name: "title",
	type: "text",
	localized: true, // this
},
```

The problem is that if I switch the language to Spanish, add some content, then save, the original text is gone:

```json
{
	"title": {
		"es": "Sobre nosotros"
	}
}
```

If I switch the language back to English in the admin, the title field is empty and I have to fill it out again.

---

It's also worth noting that removing `localized: true` afterwards results in the field getting `[object Object]` as its value.

## Steps to Reproduce

1. Add two languages
2. Add a field without localization
3. Write something in the field
4. Enable localization for the field
5. Switch the language
6. Write something in the other language
7. Switch back to the original language
8. **The field will be empty**
9. Write something again
10. Disable localization
11. Refresh
12. **The field will contain `[object Object]`**

## Other Details

The `defaultLocale` should be used to:

1. Populate the default locale value. If you have `"title": "foo"` and the user adds a value in another locale, assume that the current value is for the default locale, resulting in:
    
    ```json
    {
    	"title": {
    		"{{ default locale }}": "foo",
    		"{{ updated locale }}": "bar"
    	}
    }
    ```

2. Extract the value from an object. If a previously localized field is no longer being localized, use the `defaultLocale` to extract the value from the old object. Once saved, the field will be of type `string`, as expected.

Payload version: **1.5.2**

**Comment by jmikrut** [comment]
Hey @hdodov — thanks for the report! We plan on digging in to try and reproduce ASAP.

**Comment by jmikrut** [comment]
Hey @hdodov — we've looked into this a bit further and this is actually expected behavior. We don't plan on supporting automatic migration of data from localized to non-localized because that could potentially be destructive if done automatically.

Instead, if you are changing a field from localized to non-localized or vice-versa, you need to write a migration script to manually update the fields' data in your database so that it can be parsed as localized or non-localized.

Does that make sense?

**Comment by hdodov** [comment]
I think the current behavior is even more destructive, because there is actual content getting **deleted**. It's pretty ironic to have your content management system delete your content.

On the flip side, the worst that could happen is to have Payload map the wrong translation to the wrong language. But you could still copy-paste it in the right place, because the content isn't *deleted*.

I agree that a script is always an option, but content getting deleted is just not an expected behavior and Payload, as a content management system, should do its best to not let that happen.

Imagine if Git, for example, would randomly delete parts of your history just because "something". You can never do anything destructive by accident. Payload should be like that as well.

**Comment by jmikrut** [comment]
I totally understand where you’re coming from but the right way to handle this type of data change is through migrations. We have an automated system / migration pattern / warning system for when your schema changes on our roadmap which will address this. It’s heavily connected to additional database support.

In the meantime, there are unlimited contexts where you could change your schema in a destructive way and Payload would never be able to automatically catch them.

Changing a field from non-localized to localized is the equivalent of updating a field to a group and then nesting new fields inside of it, which would absolutely be destructive when you go to re-save a document. 

Your automatic migration suggestions certainly make sense for localization changes specifically, but even still I would think the best Payload could do is to throw a warning, and then output a way to generate a migration script.

This is, like any other framework, something that should ultimately be handled consistently via migration scripts. It’ll definitely happen first-party from Payload but in the meantime the local API is very useful here!

**Comment by hdodov** [comment]
I see. It makes sense. If you make schema changes, you should know that you have to be careful anyways. This convinced me:

> there are unlimited contexts where you could change your schema in a destructive way and Payload would never be able to automatically catch them

Perhaps I'm too used to having that safety net from my prior use of other CMS.

I'm looking forward to that warning system you're talking about, then. I reckon that having some sort of notice that something's off with the schema will be enough. It would prompt editors to get in touch with the dev team and figure out what's what before content gets lost.
