### ISSUE TITLE
Rich Text Link fields in popup not filled

### ISSUE THREAD

**Issue by christian-reichart** [payloadcms/payload#1848]
# Bug Report

When setting a link inside Rich Text the Popup opens but the fields are not filled.
The text should be prefilled with the selected text and the radio buttons should have an initial value.

## Steps to Reproduce

1. Mark text in Rich Text
2. Click the Link Button
3. The fields in the popup are not filled

## Other Details

Payload 1.5.4 (also present in current Demo https://demo.payloadcms.com/)

**Comment by jacobsfletch** [comment]
@christian-reichart a fix for this was just merged. THANK YOU!
