### ISSUE TITLE
Aggregation project operator not supported using DocumentDB 4.0.0

### ISSUE THREAD

**Issue by naldertown** [payloadcms/payload#1869]
# Bug Report

Following the upgrade to 1.5.8 from 1.1.18 and updating the various collections and globals to avoid the Schema name breaking changes we are now finding that some of the collections do not work using DocumentDB 4.0.0. 

Everythig is working as expected using Mongo Atlas.

Here is the error:

`[12:56:08] ERROR (payload): MongoServerError: Aggregation project operator not supported: '$toObjectId'`

Not all collections fail to work. It looks like the ones that do fail have the following commonlity:

1. Contain blocks
2. The content blocks contain rich text fields

## Steps to Reproduce

1. Install Payload 1.5.8
2. Configure to run on DocumentDB
3. Create a collection with blocks which contain rich text fields

## Other Details

Payload version 1.5.8

**Comment by jmikrut** [comment]
Hey @naldertown — you're right. We have a PR open to address this here:

https://github.com/payloadcms/payload/pull/1866

We do want to keep compatibility with DocumentDB and older versions of Mongo so we have implemented a new approach.

Will be testing further today but this will be solved one way or another very quickly!

**Comment by naldertown** [comment]
That's great news @jmikrut - I'll keep an eye out for a new release.
