### ISSUE TITLE
Unique:true doesn't work in field

### ISSUE THREAD

**Issue by raffaeleparisi** [payloadcms/payload#1874]
# Bug Report

## Steps to Reproduce

	fields: [
		{
			name: 'nome',
			label: 'Nome',
			type: 'text',
			required: true,
			unique: true,
		},
	],

I can add unlimited entry.

## Other Details

payload@1.5.8

**Comment by DavidOliver** [comment]
Iirc, I think you need `index` set to true for the uniqueness to be enacted. If so, I guess this could be added to the relevant fields' documentation.

**Comment by raffaeleparisi** [comment]
cleared the cache: seems to have fixed it
