### ISSUE TITLE
Can't upload files anymore

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/payload#1877]
# Bug Report

Clicking on Upload New File causes the site to just fade out. Choosing from existing ones works
Error: TypeError: Cannot read properties of undefined (reading 'filename')

## Other Details
Worked in 1.5.4, doesn't work in 1.5.8
=> I'm using the Cloudinary plugin, don't know whether that's the cause

**Comment by TartagliaEG** [comment]
I think it is the same issue as this one: https://github.com/payloadcms/payload/issues/1867

**Comment by rupakhetibinit** [comment]
Same here. I even tried using the 1.5.4 version. It still fails to upload the image.

**Comment by jmikrut** [comment]
HeY @johannesschaffer and @rupakhetibinit thank you for opening this issue! 

It's now fixed and a patch is being released now.

Give the new version a shot!
