### ISSUE TITLE
npx create-payload-app throws Error

### ISSUE THREAD

**Issue by sitoftonic** [payloadcms/payload#190]
# Bug Report

When running "npx create-payload-app" throws an error after the initial prompt.

## Expected Behavior

It should prompt next steps and boilerplate the payload starter app.

## Current Behavior

When running the command "npx create-payload-app" it prompts:

```
Need to install the following packages:
  create-payload-app
Ok to proceed? (y) y
```
Then pressing enter gives the following error:
```
C:\Users\username\AppData\Local\npm-cache\_npx\2238e51406dcebe9\node_modules\create-payload-app\bin\cli.js:49
    error(`An error has occurred: ${e?.message}`);
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

## Possible Solution

I'm not sure if that error comes from my own computer, maybe deprecated packages? I have npm version 7.15.1 and node version v12.18.3 and I don't have any other issue with any other package.

**Comment by DanRibbens** [comment]
@sitoftonic A fix for this was just pushed if you want to give it another try. There was a line that used optional chaining that node 12 doesn't support. I tested and it is working for me using node 12.

If you're still having trouble let us know. Thanks!
