### ISSUE TITLE
Smaller screen heights hiding field options and search.

### ISSUE THREAD

**Issue by SceptreData** [payloadcms/payload#1909]
# Bug Report

Very minor issue but I've already had a user contact me about it. At smaller viewport heights I am unable to view all of field options when adding a new field. It also hides the field search bar.  Originally posted on the [plugin-form-builder](https://github.com/payloadcms/plugin-form-builder) issues tab but was told to post here.

Example:
![image](https://user-images.githubusercontent.com/15841748/213119985-205ffc80-0f4a-43e8-9581-cb02a5dc6f56.png)

It can get a little funky- sometimes when adjusting the window the select popup flickers back and forth from above the add button to below it. Happening to me on both Chrome and Firefox.

## Steps to Reproduce

1. Have the form builder be configured to use all available fields.
2. Try to add a field to a form when the screen height is small

## Other Details

"payload": "^1.5.4"
Happening on both Chrome and Firefox

**Comment by jacobsfletch** [comment]
Thank you @SceptreData! I'm thinking the best move here is to install a package for this. That way we can retrofit other components throughout the admin panel over time. Whatever we land on should be smart enough to respond to viewport boundaries and shift positions automatically to ensure the component is always usable no matter what.

**Comment by JarrodMFlesch** [comment]
@SceptreData - I think we will likely move to a drawer for this component. It will give us more room to breath and completely remove these fringe cases from popping up. Stay tuned!

**Comment by jacobsfletch** [comment]
@JarrodMFlesch that's a good idea
