### ISSUE TITLE
Pagination with per page bug

### ISSUE THREAD

**Issue by rayhan-wirjowerdojo** [payloadcms/payload#1912]
# Bug Report

**Demonstrated on the Payload Demo app**, when there's enough content for it to be paginated, you go to the last page and increase the per page count. There's a possibility that you won't see anything because you're still in the `page` that you're on

## Steps to Reproduce

1. Go to [Payload demo Categories collection](https://demo.payloadcms.com/admin/collections/categories?limit=25)
2. Add to **at least 6 categories**
3. Change per page to `5`
4. Go to 2nd page
5. Change per page to any number other than `5`
6. Bug: You'll see there aren't any categories

## Other Details
Following the steps above, I believe the bug happens because you're still on page 2 (you can see in the query params). And the content is shown all in page 1, therefore no longer needing a page 2

### Preview

https://user-images.githubusercontent.com/120351450/213397050-4e25538d-66be-4a1b-94a2-97dfad5c4f3d.mov

**Comment by JarrodMFlesch** [comment]
Closed with #1936
