### ISSUE TITLE
Validation of Font mimeTypes

### ISSUE THREAD

**Issue by owieth** [payloadcms/payload#1914]
# Bug Report

Currently the validation of font mimeTypes is off, especially for woff2 files. The only way to upload these files is to completely omit the mimeTypes array, allowing any fileType to be uploaded (not recommended).

## Steps to Reproduce

I tried different fontTypes in the mimeTypes array:

`mimeTypes: ['application/font-woff'],` -> works for .woff files
`mimeTypes: ['font/woff'],` -> doesn't work for .woff files

`mimeTypes: ['application/font-woff2'],` -> doesn't work for .woff2 files
`mimeTypes: ['font/woff2'],` -> doesn't work for .woff2 files

`mimeTypes: ['font/*'],` -> doesn't work for any font files

## Other Details

Payload Version 1.5.9

**Comment by jmikrut** [comment]
Hey @owieth — unfortunately there's nothing that we can do about this with Payload itself.

I just tested a few `woff2` files with this site:
https://www.htmlstrip.com/mime-file-type-checker

They all came back as `application/octet-stream` which is unspecific. I am betting that you would need to whitelist the `application/octet-stream` type if you want to upload `woff2` files.

We only use a simple mime type checker so there is no good way for Payload to handle this in our own code, unfortunately. Manually watching for `.woff2` extensions and setting mime type based on file extension would not be ideal and would also be applicable for many, many other filetypes as well.

Does this make sense?

**Comment by owieth** [comment]
> Hey @owieth — unfortunately there's nothing that we can do about this with Payload itself.
> 
> I just tested a few `woff2` files with this site: https://www.htmlstrip.com/mime-file-type-checker
> 
> They all came back as `application/octet-stream` which is unspecific. I am betting that you would need to whitelist the `application/octet-stream` type if you want to upload `woff2` files.
> 
> We only use a simple mime type checker so there is no good way for Payload to handle this in our own code, unfortunately. Manually watching for `.woff2` extensions and setting mime type based on file extension would not be ideal and would also be applicable for many, many other filetypes as well.
> 
> Does this make sense?

Sup @jmikrut 
Thanks for checking, that's a bummer but I will work with `application/octet-stream` 👀
