### ISSUE TITLE
Some entries disappear from collection page view table

### ISSUE THREAD

**Issue by Kikky** [payloadcms/payload#1963]
Hello!

# Bug Report

After I've added draft system to this collection, I've got a problem with view table of the collection:
![image](https://user-images.githubusercontent.com/614922/215273992-5e0698d9-3d57-4e05-9b9c-40cd372920ed.png)

12 entries from 14 don't appear in table:
![image](https://user-images.githubusercontent.com/614922/215273824-f111071c-2261-4362-a4cd-65763be48579.png)

But the view becomes ok if I sort with "-" by some field: 
![image](https://user-images.githubusercontent.com/614922/215273780-c8be5361-db43-48a4-896b-dc2c2db4deb8.png)

So this **/pages?sort=-_status&page=1** will be ok and this **pages?sort=_status&page=1** will lose 12 entries.

## Other Details

Payload version: 1.5.9

**Comment by joornby** [comment]
For what it's worth, I was experiencing this issue and had to go all the way back to version 1.5.4 before it worked as expected.  There were several version in between 1.5.4 and 1.5.9 that did slightly different things.

**Comment by jmikrut** [comment]
Hey @Kikky and @joornby — this is now resolved and released in `1.6.1`.

Note that there are some migration steps that you need to follow in order to get to the new version. See here:

https://github.com/payloadcms/payload/releases/tag/v1.6.1

**Comment by Kikky** [comment]
@jmikrut , I've updated to 1.6.3.

After created new collection with such versions options, because I just need draft system:

![image](https://user-images.githubusercontent.com/614922/216636296-ce094b19-21b6-4a42-b91f-47a3b27ab780.png)

And when I create new entry to this collection, edit it and click Publish - I get **1 version is found**. If I edit it and click Publish again I will get - **no versions found**.  One more time - **1 version is found**. One more -  **no versions found** ... etc.

I don't need versions, I just need draft system, but when a doc has no versions in DB when versions are enabled on collection I can't view them in collection's view table.
