### ISSUE TITLE
Text disappearing from fields when using Firefox

### ISSUE THREAD

**Issue by todor0v** [payloadcms/payload#1980]
# Bug Report

I have a problem that the text disappears from input fields within the Payload dashboard when using Firefox. I am not using a locale with the data missing and I have confirmed that the data exists in the database. Also if I use Chrome or Brave, the problem cannot be reproduced. 

I should mention that the problem is not consistent. Sometimes when you refresh the page texts from different inputs disappear or reappear. This makes it even worse since you are not sure if you have not filled something or it's because of the bug.

All of this happens when using Globals. I cannot reproduce the same behavior when it comes to collections. Here is a screenshot of the result:

![Dissapearing-text](https://user-images.githubusercontent.com/84301735/215593591-18c17e1c-0197-44ea-8ced-892a268de217.png)

## Steps to Reproduce

1. Open Payload 
2. Check some data with text inputs that is stored in Globals
3. Sometimes the data shows, but sometimes when you change between different GlobalConfigs or refresh the page, it disappears. It sometimes disappears on load too.

## Other Details

- The problem has been reproduced with Firefox versions: 108, 109 and 110.
- Payload Version: 1.5.9
- OS Version: macOS Ventura 13.2
- I have tested inside a private windows with no extensions. All the test have been done using localhost.

**Comment by jmikrut** [comment]
Hmmm - this is interesting. What OS are you on? I can't reproduce, unfortunately. Can you replicate this behavior with our public demo?

**Comment by todor0v** [comment]
OS Version: macOS Ventura 13.2

No. The public demo works fine. It is strange indeed. I will write again if I figure something out or notice any change.

**Comment by PatrikKozak** [comment]
Hey @todor0v - I went ahead and tried a few different things to try and reproduce the issue but unfortunately could not get it reproduced. 

If you can, I'd update your app to Payload's latest version (`1.6.4`) and let us know if this continues to be a reoccurring issue.

**Comment by todor0v** [comment]
Thank you @PatrikKozak! I have updated to the latest `1.6.4` version and I cannot reproduce the issue again. Problem solved.
