### ISSUE TITLE
Local API Update Inferred Types should be Partial<>

### ISSUE THREAD

**Issue by xHomu** [payloadcms/payload#2009]
# Bug Report

Payload allows for updating doc with only partial data, but the inferred type requires the whole collection object:

![image](https://user-images.githubusercontent.com/84349818/216474833-a450f38e-3ee8-4dbd-b71f-7a3c04082ac0.png)
![image](https://user-images.githubusercontent.com/84349818/216474945-a3e6a670-0379-4aaf-a155-7a306f377b3a.png)

## Steps to Reproduce

1. Create a document
2. Update document using Local API with partial data
3. Typescript errors, but the update posted correctly by Payload.

## Other Details

Payload v1.16.3

This can be fixed by changing from `MarkOptional<GeneratedTypes['collections'][TSlug], 'id' | 'updatedAt' | 'createdAt'>` to `Partial<GeneratedTypes['collections'][TSlug]>`:

https://github.com/payloadcms/payload/blob/master/src/collections/operations/local/update.ts#LL16

Posted a PR https://github.com/payloadcms/payload/pull/2010

**Comment by denolfe** [comment]
Thanks for the report @xHomu. We'll get this looked at soon.
