### ISSUE TITLE
No refresh of content after replacing a file in the upload collection.

### ISSUE THREAD

**Issue by webcredo** [payloadcms/payload#2011]
# Bug Report

Upon clicking 'Save' during media replacement in the upload collection, the content does not refresh and the drag zone persistently displays. The expected result is the display of the form with the replaced media.

![cda6e04321d465900a9fe39e128c9193](https://user-images.githubusercontent.com/2051941/216495481-714757d0-47a3-4afd-8cb2-d1a66e679034.png)

## Other Details

"payload": "^1.6.3",

**Comment by jacobsfletch** [comment]
@webcredo this is likely fixed by https://github.com/payloadcms/payload/pull/1978 but I will confirm. Thank you for reporting!
