### ISSUE TITLE
413 Request Entity Too Large on uploading specific image

### ISSUE THREAD

**Issue by Kikky** [payloadcms/payload#2014]
Can't upload image to the media collection on the server. Getting this response:

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```

But on Win 10 localhost everything is fine with this image.

 Payload version is 1.6.4

Config for uploads:

```
upload: {
    limits: {
      fileSize: 25000000, // 25MB, written in bytes
    },
  }
```

I've attached this image:

![xtb-1](https://user-images.githubusercontent.com/614922/216759941-3017883b-b646-481d-81ef-e019b58f3d96.png)

**Comment by denolfe** [comment]
This response looks like it is coming from NGINX, not Payload. Do you have `client_max_body_size` set in your nginx config? It looks like you need to bump that up.


Some more detail here: https://stackoverflow.com/a/28476755/1717697

**Comment by Kikky** [comment]
> This response looks like it is coming from NGINX, not Payload. Do you have `client_max_body_size` set in your nginx config? It looks like you need to bump that up.
> 
> Some more detail here: https://stackoverflow.com/a/28476755/1717697

Ok, understand. Thanks for help!
