### ISSUE TITLE
When using the `filterOptions`  with  `mimeType` filter in the upload field, uploading a new file is not restricted to the filtered MIME type. 

### ISSUE THREAD

**Issue by webcredo** [payloadcms/payload#2016]
When using the `filterOptions` with the `mimeType` filter in the upload field, uploading a new file is not restricted by the filtered MIME type, and the MIME type should be limited in the same way as it works in the 'Choose from existing' modal.

This means that any file type can currently be uploaded, regardless of the MIME type specified in the `filterOptions`.

**Comment by jmikrut** [comment]
Hey @webcredo — I can provide some explanation here.

The `filterOptions` property works when selecting an existing upload from the `upload` field type. It does not affect the process of creating / uploading a new upload document for the first time.

To restrict mime types while uploading for the first time, you'll need to specify `upload.mimeTypes` on the collection itself. From there, it will restrict and validate against selected mimeTypes.

Does that make sense?

**Comment by webcredo** [comment]
@jmikrut For example, I have a "Files" upload collection that supports both audio and media files. I also have two separate collections, "Audio" and "Media", each of which is related to the "Files" collection and has its own filter options, one for audio and one for video. The filters are only utilized for selecting files and not for uploading new ones.

**Comment by jmikrut** [comment]
Ah I see. Thanks for clarifying. The team and I will check into this right away.

Thanks for the report!

**Comment by jacobsfletch** [comment]
@webcredo after looking into this a bit more, the current behavior is expected. If you set `filterOptions` on a relationship field, you can continue to upload new media as long as it complies with the `upload.mimeTypes` property of your uploads collection. Then when you save the document, API validation errors prevent it from saving. Here's a quick screen recording of this behavior:

Uploading Screen Recording 2023-02-06 at 3.50.10 PM.mp4…

I've went ahead and [written a test for this anyway](https://github.com/payloadcms/payload/commit/26dfb40363fad6615cf5357692146064bd4d6387) based around your specific use case. In the test suite there is now an mp3 file uploaded to the `media` collection, and a new `audio` collection with a field that filters only `audio/mpeg` mime-types.

One thing we _could_ potentially do here is surface the API error sooner. For instance, when you upload a non-compliant file, we error when the that file is automatically selected, before saving parent document.

**Comment by webcredo** [comment]
@jacobsfletch I believe there is an issue with the UX. Users should not be able to select unsupported types, and they should receive an error message immediately on dragging, not after saving.

Here are some examples in the audio collection that only support audio and are related to files with both audio and video support.

1: Upon selection, only audio files are displayed. 
![e9c15ed0436f745f89d747ed91e6b69a](https://user-images.githubusercontent.com/2051941/217099760-40312adf-0696-4e62-90c4-bf5b92de4598.png)

2: When dragging unsupported files, an error message is shown.
https://user-images.githubusercontent.com/2051941/217100111-c795d84c-8ab7-4f4c-a3e2-b38dc20ad8e5.mp4
