### ISSUE TITLE
Empty values inside Tabs field in versions

### ISSUE THREAD

**Issue by nrezvoi** [payloadcms/payload#2020]
# Bug Report

Versions UI shows empty values for Tabs fields, however it seems to be saved correctly in the DB - API, single post UI and restoration of the versions correctly assign values.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/15609653/216927722-452a5f19-5cf2-410d-9c85-2e232f835527.png">

## Steps to Reproduce

1. Create new collection with tabs field, enable versions with drafts
2. Add some tabs with name and fields to them
3. Publish, do some changes, publish again, check versions
## Other Details
Example collection to check
```
    {
      slug: "versionsTest",
      fields: [
        {
          type: "tabs",
          tabs: [
            {
              label: "Tab1",
              fields: [
                {
                  type: "text",
                  name: "tab1Text"
                }
              ]
            },
            {
              label: "Tab2",
              name: "tab2",
              fields: [
                {
                  type: "text",
                  name: "tab2Text"
                }
              ]
            }
          ]
        }
      ],
      versions: {
        drafts: true
      }
    }
```

**Payload version**: 1.6.3

**Comment by JarrodMFlesch** [comment]
@nrezvoi Looks like this is specific to tabs with a `name` field. We will get this resolved, thanks for reporting!
