### ISSUE TITLE
Relationship Fields are empty when editing in drawer

### ISSUE THREAD

**Issue by raffaeleparisi** [payloadcms/payload#2040]
# Bug Report

When editing a relationship field inside a collection the fields are empty.

## Steps to Reproduce

1. Add a relationship field inside a collection
2. try to edit the relationship collection inside of the parent

## Other Details

Payload 1.6.6

**Comment by JarrodMFlesch** [comment]
@raffaeleparisi Thanks for the report, I was able to reproduce 👍

**Comment by jmikrut** [comment]
Hey @raffaeleparisi — this is fixed and will be released shortly.
