### ISSUE TITLE
Payload route is being overwritten by other express routes

### ISSUE THREAD

**Issue by MoSattler** [payloadcms/payload#2043]
# Bug Report

Payload route is not properly resolved when using in conjunction with other colliding express routes.

## Steps to Reproduce

This works as expected, and payload shows up on `/admin`.
```ts
import express from "express";
import payload from "payload";
import path from "path";
import compression from "compression";
import morgan from "morgan";
import { createRequestHandler } from "@remix-run/express";

require("dotenv").config();
const app = express();

// Initialize Payload
payload.init({
  secret: process.env.PAYLOAD_SECRET,
  mongoURL: process.env.MONGODB_URI,
  express: app,
  onInit: () => {
    payload.logger.info(`Payload Admin URL: ${payload.getAdminURL()}`);
  },
});

app.listen(3000);
```

But when adding other express routes, it creates problems:

```ts
import express from "express";
import payload from "payload";
import path from "path";
import compression from "compression";
import morgan from "morgan";
import { createRequestHandler } from "@remix-run/express";

require("dotenv").config();
const app = express();

// Initialize Payload
payload.init({
  secret: process.env.PAYLOAD_SECRET,
  mongoURL: process.env.MONGODB_URI,
  express: app,
  onInit: () => {
    payload.logger.info(`Payload Admin URL: ${payload.getAdminURL()}`);
  },
});

// NEW ROUTE HANDLER HERE!
app.all(
  "*",
  (req, res, next) => {
    res.send("Hello World");
  }
);

app.listen(3000);
```

Now it shoes "Hello World" on `/admin`. Since the second handler was defined after payload, it should actually still serve the admin interface.

I think this is some sort of race condition, cause if I add the handler with delay, everything works as expected
```ts
setTimeout(() => {
  app.all("*", (req, res, next) => {
    res.send("Hello World");
  });
}, 1000);
```

## Other Details

This only happened since I updated from 1.5 to 1.6.6

**Comment by jmikrut** [comment]
Hey @MoSattler — this is because you are not awaiting `payload.init`, and as of 1.6.0, it is now async-only.

Take a peek at the migration guide here for an example how to migrate!

https://github.com/payloadcms/payload/blob/master/CHANGELOG.md#-payload-init-is-now-always-async-and-payloadinitasync-has-been-removed
