### ISSUE TITLE
Dropdown Widget Returns item ID instead of field Label

### ISSUE THREAD

**Issue by ardiansyaherwin** [payloadcms/payload#2045]
# Bug Report
Hi, I followed your tutorial episode-1.

So I cloned the repository, install and setup.

Upon creating a new Study, the categories dropdown returns option's uuid/id instead of options' label.

**Comment by DanRibbens** [comment]
I don't think this is a bug. I'm assuming you're refering to a relationship field here and in the admin UI you are only seeing the ids to choose from.

You'll have to set the `admin.useAsTitle` to one of the field names in your categories collection.

Feel free to re-open the issue and include a config so we can reproduce it if I've made the wrong assumptions here.

**Comment by ardiansyaherwin** [comment]
Great it works, thanks for the advice.

I think the demo repo should be updated, or at least the useAsTitle key should be mentioned somewhere.
