### ISSUE TITLE
Date picker and dates don't follow users language

### ISSUE THREAD

**Issue by ChrisGV04** [payloadcms/payload#2046]
# Bug Report

Recently I reported the issue of the Date picker field not being localized and you released an update fixing it on the 1.6.6 release. However, the localization only occurs when you enable the `localization` option of the `payload.config.ts` file, but it doesn't localize it if you have it disabled and the user has their Admin UI language set to any other than English.

My customers mainly use Spanish-only content, so I don't need to enable the localization feature, but I do need the Admin UI to be in Spanish. So if I choose to have the Admin UI in Spanish under my account's preferences, all of the date pickers and every place where the date gets displayed is still in English. See video for context:

https://user-images.githubusercontent.com/47041342/217619798-6f34218b-9206-45b9-a136-2319137bc6e0.mp4

As you can see, I don't have content localization enabled, but I do have my user set to Spanish and I still get al of the dates formatted in English as well as the date picker. I hope I was able to explain myself correctly.

## Steps to Reproduce

1. Create a simple Payload project without localization enabled
2. Create a collection with a date field
3. In the Admin UI, set your user's language preference to Spanish.
4. Go to any place where a date is displayed or use a date picker, they're still in English.

## Other Details

- Payload: 1.6.6

**Comment by jmikrut** [comment]
Crystal clear. We're on it. Thank you for the detailed write-up. Expect a fix shortly!
