### ISSUE TITLE
RichText slate editor doesn't save text paragraphs as type 'p'

### ISSUE THREAD

**Issue by bobbyZ94** [payloadcms/payload#2048]
# Bug Report

When editing in the richText editor and writing text paragraphs (while using Enter or Enter+Shift), slate saves the paragraphs as simple 'text' nodes, instead of adding the type 'p' node, so the frontend can use paragraph tags. What works is copy&pasting text from e.g. MS Word -> paragraphs appear as type.

## Steps to Reproduce

1. Windows 10
2. npx create-payload-app@latest
3. Typescript
4. blog template
5. create new post
6. write in richText editor and check through rest api if type 'p' exists on nodes

**Comment by lucaslcode** [comment]
More here: https://discord.com/channels/967097582721572934/1072510637713920080

Unfortunately this may be hard to reproduce. For me some RichText fields correctly have type: 'p', and some do not.

**Comment by bobbyZ94** [comment]
Seems like this "bug" was taken into account for when writing the serializer function as seen in the richtext payload docs. Non p tag text nodes are defaulted to &lt;p&gt;, which solves the issue, atleast for me. I wasn't aware of that at first because i wrote my own serializer function for use with svelte.

**Comment by jmikrut** [comment]
Hey there - default nodes are actually intended to not have a type set at all. It’s possible that our “paste from Word” handler was not updated when we streamlined our handling of default nodes, and might ship with “p” still. I have not yet checked the code.

But this will be flattened and resolved shortly in any case, and all default nodes should have no type. 

In the interim, I guess it’s safest to handle both type “p” and “undefined” as paragraphs in your serializers. 

Will report back shortly and thanks for bringing this up!
