### ISSUE TITLE
CreatedAt after upgrade to 1.6 displayes incorrectly

### ISSUE THREAD

**Issue by johannesschaffer** [payloadcms/payload#2064]
CreatedAt shows the same as ModifiedAt after the upgrade. It's a problem with the Admin view, since the data is still correct (After downgrading it displayed correctly again)
Didn't test the API yet.

**Comment by denolfe** [comment]
Could you provide more info on this, so we can recreate? 

- What version of Payload did you upgrade from?
- Can you provide the JSON data you're using?
- I'm assuming you're referring to the bottom right of the Edit view?

**Comment by johannesschaffer** [comment]
Yeah, sorry;) 
I upgraded from 1.5.9 to 1.6.9
In the edit view (bottom right) it's actually displayed corrrectly. The problem is the list view where all documents of a collection are displayed
If have to collectionAdmin configured with `defaultColumns: ['title', '_status', 'updatedAt', 'createdAt']`

**Comment by jmikrut** [comment]
Hey @johannesschaffer we figured this out. It will be fixed on Monday. Thanks for the report!

**Comment by JarrodMFlesch** [comment]
Hey @johannesschaffer a fix was merged in and will be included in the next release! I wrote up a little migration script to help you adjust incorrect createdAt dates in your versions table. [See here.](https://github.com/payloadcms/payload/pull/2079#issuecomment-1428427401)
