### ISSUE TITLE
Populate data of field with relation

### ISSUE THREAD

**Issue by jmas** [payloadcms/payload#2067]
# Bug Report

Hello. I have an issue with Admin UI. I have field with relation with `defaultValue = <ID of current user>`. When I want to create new Record from Admin UI - UI doesn't pre-populate the field. Admin UI populates this field only after I open select dropdown.

I checked Network requests and see that Admin UI loads records for the field after first interaction.

## Steps to Reproduce

Create the following collection:

```ts
import { CollectionConfig } from "payload/types";

export const Reactions: CollectionConfig = {
  slug: "reactions",
  access: {
    read: () => true,
  },
  fields: [
    {
      name: "score",
      type: "number",
      required: true,
    },
    {
      name: "user",
      type: "relationship",
      relationTo: ["users"],
      required: true,
      defaultValue: ({ user }) => user.id,
    },
    {
      name: "post",
      type: "relationship",
      relationTo: ["posts"],
      required: true,
    },
  ],
};
```

Our attention is on field `user`. It has default value as ID of current logged-in user.

1.  Open collection `Reactions`
2.  Click `Create New`
3.  See that field `User` is empty
4.  Click on field `User` and see that it autopopulated with current logged-in user.

![payload_user_field_issue](https://user-images.githubusercontent.com/90701/218275743-b49bb1a8-e9fb-48e9-866b-4d673537c13d.gif)

## Other Details

Payload version: 1.6.9

Possible solution: pre-populate field that has relations and also has `defaultValue`.

Thank you.

**Comment by jmikrut** [comment]
Hey @jmas great catch. Easy fix too. We will take care of this on Monday 👍

**Comment by jacobsfletch** [comment]
@jmas I was able to recreate your error but found that it's actually an issue with your return value, I went ahead and wrote a couple e2e tests anyway, but here's an edited version of your query that will work for you:

```
defaultValue: ({ user }) => ({
  relationTo: 'users',
  value: user.id
})
```
 
Here's a screen recording to show you:

https://user-images.githubusercontent.com/15735305/218534356-850158b4-1fc7-4f77-9748-14cd12f50a64.mov

**Comment by jmas** [comment]
@jacobsfletch Oh, thank you very much! Works as expected.
