### ISSUE TITLE
net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by Glinduff** [payloadcms/payload#2068]
# Bug Report

Hi payload team, I'm having trouble doing a production deployment.

I followed the DigitalOcean tutorial in "Production > Deployment", but without success.

I have the following error message "GET http://localhost:3000/api/users/me net::ERR_BLOCKED_BY_CLIENT" 
for the url of /admin/create-first-user

<img width="1164" alt="Screenshot 2023-02-12 at 02 08 05" src="https://user-images.githubusercontent.com/2903346/218294216-eab0c6c8-d360-48d1-803c-e79d69454984.png">

I'd appreciate your help.

## Steps to Reproduce

Follow the DigitalOcean guide from the payloadcms website

Once the server is configured and the files loaded, start the npm build command and then the npm run serve command

You can watch it live at  [https://cdsl.beenary.cl/admin/create-first-user](https://cdsl.beenary.cl/admin/create-first-user)

## Other Details
Payload version : 1.6.9
Tested Browsers : Brave, Chrome, Safari and Firefox

**Comment by bobbyZ94** [comment]
Yea its a cors issue as seen in the network tab. I have the same problem with 1.6.7.
[Opend a discord post yesterday ..](https://discord.com/channels/967097582721572934/1074094192575389836)

**Comment by bobbyZ94** [comment]
While going through discord cors issue posts, one of the payload maintainers devs mentioned to delete the serverURL property in payload.config.ts. This solved the issue for me. This should be in the docs imho.

**Comment by Glinduff** [comment]
Ty @bobbyZ94! It works now!
