### ISSUE TITLE
Blocks with fields of type date and number are empty when fetched via graphql

### ISSUE THREAD

**Issue by itzaks** [payloadcms/payload#2071]
# Bug Report

When I create a block that contains a field of type number or date, it is showing up fine in the admin UI, but when fetched in the client via graphql it's returned as an empty object.

Admin fetch response
````js
[
    {
        "value": 10,
        "id": "63e9dfb38b69cd009592db2e",
        "blockName": "Test",
        "blockType": "numberInput"
    }
]
````

Graphql response
````js
specifications: [
    {}
]

````

Field definition:
````ts
export const NumberSpecification: Block = {
  slug: 'numberInput',
  fields: [
    {
      name: 'value',
      type: 'number',
    }
  ]
};

````

## Other Details

Payload 1.6.9

**Comment by denolfe** [comment]
Hey @itzaks, this appears to be working properly. It likely has to do with querying properly via GraphQL.

Here is what it looks like to query block data:

<img width="823" alt="CleanShot 2023-02-13 at 10 51 30" src="https://user-images.githubusercontent.com/65888/218506134-551aa455-633c-4f1e-9dea-cd68810708c5.png">
