### ISSUE TITLE
Image resizing not preserving aspect ratio

### ISSUE THREAD

**Issue by ggaidelevicius** [payloadcms/payload#2088]
# Bug Report

When resizing an image while trying to preserve aspect ratio by omitting either width or height, this omission isn't respected with files of certain expected output dimensions (seemingly where the ommitted value is expected to be <400px) and instead we're returned an image that is cropped by the dimension that is ommitted.

This happens irrespective of whether the ommitted value is ```null``` or ```undefined```

## Steps to Reproduce

1. Define an imageSize where one dimension is ommitted, e.g.
```     
{
  name: 'logo',
  height: 50,
  width: null,
  position: 'centre',
  formatOptions: {
    format: 'webp',
  },
}
```
2. Upload an image where the expected value of the ommitted dimension is <400
3. See that the image generated has incorrect dimensions, i.e., for an image that is uploaded with 6608x2500 dimensions, we'd expect an output of 132x50, but instead we receive 400x50

## Other Details

Payload v1.6.9

**Comment by ChrisGV04** [comment]
Hi @ggaidelevicius!

I tried to replicate your issue with the exact same image dimensions you mentioned and I got the correct expected resize of 132x50. I don't know if it could be that the `height` and `width` properties can't be `null`, only `undefined`. In the Payload source code they have a test for aspect rations with the following `imageSizes`:

```ts
imageSizes: [
  {
    name: 'maintainedAspectRatio',
    width: undefined,
    height: 50,
    crop: 'center',
    position: 'center',
    formatOptions: { format: 'png', options: { quality: 90 } },
  },
]
```

I also tried with `webp` and the aspect ratio was maintained correctly. I would recommend you either try setting `width: undefined` and/or update to the latest Payload version, since the test passes on **v1.6.12**.

Hope that can help!

**Comment by PatrikKozak** [comment]
Hey @ggaidelevicius! Would love to give some insight here - I went ahead and tried to replicate the behavior and was able to get the correct expected resize. Value wise - the `width` and `height` properties should either be a `number` or `undefined`.

As @ChrisGV04 mentioned, I would try updating Payload to latest (1.6.13) and give it another try! I am going to close this for now, but If you're still experiencing an issue with this after updating - please go ahead and reopen the issue and we will gladly help out.

**Comment by DeMaCom** [comment]
Hi,

I am experiencing the same problem when only defining height and setting width to undefined. I am using payload version 1.6.15. Aspect ratio is kept when specifying an undefined height, but not with an undefined width.
when uploading an image with a size of (w)865x(h)774, it is being resized to 1280x100. I have tried to add position and formatOptions parameters, but the result stays the same.

I am using this config:
`       imageSizes: [
      {
        name: "thumbnail",
        width: 150,
        height: 150,
        position: "centre",
      },
      {
        name: "Hero",
        width: 1280,
        height: 720,
        position: "centre",
      },
      {
        name: "background",
        width: 1920,
        height: 1080,
        position: "centre",
      },
      {
        name: "logo",
        width: undefined,
        height: 100,
      },
      {
        name: "blog",
        width: 1024,
        height: null,
      },
    ],`
