### ISSUE TITLE
Versioning uses `$facet` aggregation which is not supported in DocumentDB

### ISSUE THREAD

**Issue by evelynhathaway** [payloadcms/payload#2092]
# Bug Report

When using a DocumentDB database, versioned documents  with drafts cannot be listed in the UI.

The following error occurs in the console:
```
ERROR (payload): MongoServerError: Aggregation stage not supported: '$facet'
```

And the UI for listing a page is stuck in the loading state

![image](https://user-images.githubusercontent.com/38994283/218814367-3f7e67e0-4f1f-40b0-9974-05cfcb9a8575.png)

Creating and editing documents still works, provided you know how to get to those screens without being able to list the documents

## Steps to Reproduce

1. Create a Payload CMS project with a DocumentDB database
  - URL`mongodb://xxx.cluster-xxx.xxx.docdb.amazonaws.com:27017?retryWrites=false`
  - `mongoOptions` should include `ssl: true` and `sslCA: "path/to/certificate/file"`
2. Create a collection with versioning and drafts enabled
```ts
import {CollectionConfig} from "payload/types";

export const Pages: CollectionConfig = {
	slug: "pages",
	admin: {
		useAsTitle: "title",
	},
	versions: {
		drafts: true,
	},
	fields: [
		{
			name: "title",
			type: "text",
		},
	],
};
```
3. Try to list the pages in the Payload admin UI

## Other Details

Tested with Payload versions 1.6.6, 1.6.9, and 1.6.10

[`$facet` is listed as unsupported in the DocumentDB documentation](https://docs.aws.amazon.com/documentdb/latest/developerguide/mongo-apis.html)

**Comment by DanRibbens** [comment]
It appears that `facet` is coming from the plugin we use for paginating the aggregation used in collection lists with drafts. https://www.npmjs.com/package/mongoose-aggregate-paginate-v2

There is an option that we can pass to the plugin to `useFacet` which we can set to false to allow support for DocumentDB.

I wonder if there is a way to discern if facet is available to the connection or not so that engines that support this feature can still use it, otherwise it increases querying to the database.

**Comment by evelynhathaway** [comment]
Ahh, I see.

I don't see any way to detect operator support with MongoDB.

Maybe the `useFacet` option could be provided to payload in a similar way to `payload.init`'s `mongoOptions`? To use DocumentDB, we already have to add a custom SSL config and use a connection URL that disables retry writes, so I would be comfortable with that config option as an escape hatch.

**Comment by jmikrut** [comment]
Yes, @evelynhathaway this is the move. We will do this on this coming Monday, but if you're up for making a PR, we'd happily accept / merge it in the interim!

**Comment by DanRibbens** [comment]
Fixed in v1.6.14. 

You'll have to add `useFacet: false` in your `mongoOptions` for this change to work.

**Comment by evelynhathaway** [comment]
Thanks for patch! In `v1.6.14` it looks like a new error occurs since Payload is passing the `useFacet` to mongoose as a connection option too.

```
ERROR (payload): Error: cannot connect to MongoDB. Details: option usefacet is not supported
```

**Comment by DanRibbens** [comment]
OK, mongoose is not happy with extra property. I can fix this.

**Comment by DanRibbens** [comment]
Alright, v1.6.15 is released and addresses the error. Can you give this another shot @evelynhathaway?

**Comment by evelynhathaway** [comment]
I have verified that v1.6.15 works. Thank you!
