### ISSUE TITLE
Typing not working as expected on CRUD functions in local api

### ISSUE THREAD

**Issue by MoSattler** [payloadcms/payload#2094]
# Bug Report

There seems to be an issue with the typing of CRUD methods that leads to a bit of an inconvenience.  On cannot use the slug to reference a collection, due to a TS error.
```ts
  // This throws a TS error
  await payload.create({
    collection: Users.slug,
    data: { /* data */ }
  })
```

The error is:
```
$ tsc --noEmit
src/test.ts:7:5 - error TS2322: Type 'string' is not assignable to type '"users"'.

7     collection: Users.slug,
      ~~~~~~~~~~

  node_modules/payload/dist/collections/operations/local/create.d.ts:8:5
    8     collection: TSlug;
          ~~~~~~~~~~
    The expected type comes from property 'collection' which is declared here on type 'Options<"users">'


Found 1 error in src/test.ts:7

error Command failed with exit code 2.
```

it seems to be due to the fact that collections are very generically typed with `CollectionConfig`, hence the slug is typed as `string`, not as a constant (like `user`). The CRUD methods on the other hands are very specifically typed and expect an enum of all possible slugs.

## Steps to Reproduce

Check out my [reproduction repo](https://github.com/MoSattler/payload-repro). 

All I did was
1. run `npx create-payload-app appname`
2. commit [these changes](https://github.com/MoSattler/payload-repro/commit/5f56275d31416f4794c643f6336ac62c741558c5) to activate types
3. run `yarn typecheck`

## Other Details

```
"payload": "^1.6.10",
```

**Comment by jmikrut** [comment]
Hey there! Good catch. Here's some info:

First up our local API `slug` is actually not an enum, instead, it's a union of strings. And that's really the only way that we can accomplish this typing. BUT there is a way around this!

```ts
export const userSlug = 'users';

const Users: CollectionConfig = {
  slug: userSlug,
  auth: true,
  admin: {
    useAsTitle: 'email',
  },
  fields: [
    {
      name: 'name',
      type: 'text',
    }
  ],
}

export default buildConfig({
  collections: [
    Users,
  ],
  onInit: async (payload) => {
    const user = await payload.create({
      collection: userSlug,
      data: {
        email: 'test@test.com'
      }
    })
  }
});
```

You just need to define your collection slugs as const and then export them for re-use accordingly. Outside of that, there's little that we can do to improve this i'm afraid. 

What do you think?
