### ISSUE TITLE
Tsconfig alias issue on generate:types

### ISSUE THREAD

**Issue by HQ92** [payloadcms/payload#2096]
# Bug Report

I am getting an annoying error on one of the first things I have tried with merging in concepts from your public website repo at - https://github.com/payloadcms/website-cms.

<img width="808" alt="image" src="https://user-images.githubusercontent.com/9061823/218882348-286f87a5-d1e6-4be4-92ba-e3d51cc6c50e.png">

When trying to generate the types for the payload app using an alias defined in tsconfig:

`
{
  "exclude": ["node_modules", "dist", "build"],
  "compilerOptions": {
    "rootDir": "./src",
    "outDir": "./dist",
    "baseUrl": ".",
    "paths": {
      "@access/*": ["./src/access/*"],
      "@blocks/*": ["./src/blocks/*"],
      "@collections/*": ["./src/collections/*"],
      "@fields/*": ["./src/fields/*"],
      "@globals/*": ["./src/globals/*"],
      "@scripts/*": ["./src/scripts/*"],
      "@utilities/*": ["./src/utilities/*"],
      // Tell TS where to find your generated types
      // This is the default location below
      "payload/generated-types": ["./src/payload-types.ts"]
    }
  },
  "include": ["src"]
}
`

It errors, removing the @ in the import and replacing with a standard relative route works. VS Code is fine with mapping the modules using the aliases, it only errors once trying to run 'generate:types'.

## Steps to Reproduce

1. Duplicate https://github.com/payloadcms/website-cms
2. Add in tsconfig with path alias
3. Modify any import from '../access/isAdmin' to '@access/isAdmin'
4. Run 'yarn generate:types'

Or

1. Pull https://github.com/HQ92/payload-alias
2. Run 'yarn generate:types'

## Other Details

Payload version - 1.6.7. Yarn version 1.22.19.

**Comment by jmikrut** [comment]
Hey there - I see what's happening here. Give us a bit and we will figure out a solution. Thanks for the report!

**Comment by jmikrut** [comment]
Hey @HQ92 — thanks again for the report. This is now fixed and custom TS paths are now working as you'd expect.

This will be released in our next patch version tomorrow!

**Comment by HQ92** [comment]
That's great! Really liking PayloadCMS as I've always stayed away from most CMSs if possible because of the way they had to be setup and the restrcitions they imposed. Payload seems to be a much nicer way to move forward with full typescript support from front to back. The only thing I haven't quite worked out how to get working yet is grabbing Payload data on the server using TRPC and the NextJs 13 app directory. But I feel that's more of a TRPC issue with Next 13.

Thanks again.
