### ISSUE TITLE
Rich text toolbar tooltip appears below breadcrumbs bar (z-index issue)

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#2108]
# Bug Report

Tooltip incorrectly appears below the breadcrumbs bar when the page is scrolled:

![image](https://user-images.githubusercontent.com/5570098/219309259-c3e05b15-4483-486d-a2fd-bb84d7ef7eb2.png)

## Other Details

Payload version: 1.6.11

**Comment by jmikrut** [comment]
Thank you for the PR! I have added some notes accordingly.

**Comment by jmikrut** [comment]
Closed via a19c42f
