### ISSUE TITLE
Pagination config does not apply defaultLimit

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#2117]
# Bug Report

## Steps to Reproduce

1. Create collection with `admin: { pagination: { defaultLimit: 100 } },`
2. Or create collection with `admin: { pagination: { limits: [100] } },`
2. Add 101 items
3. Visit collection table overview

Expected: It shows 100 items
Actual: it shows 10 items

## Other Details

Payload v1.6.10 & 1.6.11

Related question: is it possible to disable the pagination? (as is possible in the local API?)

**Comment by jmikrut** [comment]
Hey there - we will do some digging here and get you some answers ASAP.

Will report back shortly!

**Comment by wiesson** [comment]
Btw, it looks the the issue is exists in `1.8.2`

```js
pagination: {
  defaultLimit: 100,
  limits: [100, 250, 500, 1000],
},
```

And I only see 10 items

**Comment by DanRibbens** [comment]
Hi @wiesson,
You could still see 10 because of a saved user preference. If you delete your user and create a new one, or drop the `_preferences` table are you still seeing only 10?

You could also change the limit in the UI, but that won't tell us if the problem persists.

**Comment by wiesson** [comment]
Cleaning `_preferences ` solved the problem immediately!
