### ISSUE TITLE
Generated type of JSON fields is Object only.

### ISSUE THREAD

**Issue by chladog** [payloadcms/payload#2119]
# Bug Report

Payload generates an JSON field type strictly as Object, however JSON can be top level array as well by specification RFC 4627 or any JSON value ({}, [], number, string... etc) by specifications RFC 7159, RFC8259, ECMA-404.

## Other Details
"payload": "^1.6.10",

**Comment by jmikrut** [comment]
Hey there - this is a good call. We will update this accordingly.

Thank you!

**Comment by chladog** [comment]
Additional finding to consider when implementing this.
When I ignored the type and forced the top-level Array into ```JSON field``` it crashes with a loop at payload\src\utilities\deepCopyObject.ts:18:20 during collection update.  It's probably being infinitely duplicated.
