### ISSUE TITLE
Custom Endpoint on Collection Breaks Values in Admin UI

### ISSUE THREAD

**Issue by badjr13** [payloadcms/payload#2123]
# Bug Report

When creating a custom endpoint on a collection, if only a `/:parameter` is passed as the `path` value, a record in this collection values disappears in the Admin Panel.

## Steps to Reproduce

1. Create a custom endpoint on a collection
2. For the endpoints `path` value, use a path that is just a parameter, such as `{ path: "/:id", ... }`
  - For example, if you had a collection of `Stores`, you would call `http://localhost/api/stores/13`
4. Navigate to the Admin Panel and select a record in the collection and notice its values are missing

## Other Details

- If you put additional pathing before or after the parameter, the bug goes away, for example:
  - `{ path: "/grocery/:id", ... }` or `{ path: "/:id/grocery", ... }`
  - ... will not cause this bug
- If constructed properly, the endpoint will still work even with the UI bug present.

**Comment by jmikrut** [comment]
This is expected. What you are doing by adding that endpoint is _**replacing**_ the existing endpoints mounted on `/api/:collection/:id` - like PATCH for `update`, GET for `findByID`, etc.

Does that make sense?
