### ISSUE TITLE
GQL Update mutations createdAt & updatedAt not working

### ISSUE THREAD

**Issue by chladog** [payloadcms/payload#2125]
# Bug Report

After update to 1.6 **graphql update mutations** on any collection throw ```Cannot return null for non-nullable field on``` ```createdAt```, ```updatedAt```.

When not querying for those fields (in update mutation) everything works as expected. Normal query of collection works as well.

By the way, these hard fails without returning any partial data are quite unpleasant, as basically whole application becomes unavailable. Would be great if we could configure an option to not be so strict regarding data types on api/persistence and to throw soft error with partial data.

## Other Details
1.6

**Comment by jmikrut** [comment]
Hey @chladog — thanks as always for this report. I was able to reproduce. I improved tests to catch this and fixed the bug in 1.6.13, just released.

> By the way, these hard fails without returning any partial data are quite unpleasant, as basically whole application becomes unavailable. Would be great if we could configure an option to not be so strict regarding data types on api/persistence and to throw soft error with partial data.

I totally agree and have run into this myself a few times. Is there a GraphQL setting that we could use maybe? We will look into this. Off the top of my head, this is just how GraphQL functions, but maybe there are settings we can expose to allow users to opt out of that default behavior.

THANK YOU!

**Comment by chladog** [comment]
hello @jmikrut, according the specs it indeed behaves correctly as non-nullable field can't be null as thats its purpose http://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability, however I still don't like the way it's handled for the reasons mentioned. 
IMHO it would be great if payload catches the error and removes the field altogether from the response or even set it to null BUT send the error along with partial data. Then it would be up to the App if it renders the partial data, shows an error or do a hard stop.
I love types and benefits they bring, but I believe this is one of those situations where overly-strict pedant typing works against you and especially the UX.
