### ISSUE TITLE
unverified users can login using the password-reset flow

### ISSUE THREAD

**Issue by berndb** [payloadcms/payload#2131]
# Bug Report

unverified users can login using the password-reset flow.

## Steps to Reproduce

1. create a user in an auth collection which has "verify" enabled
2. use "forgot-password" to receive a password reset token for this user
3. use "reset-password" to set a new password for the user

--> the user is automatically logged in, although not being verified
--> the user is still not able to login using the login form, because he is not verified

## Other Details

the expected behavior would be that an unverified user cannot gain access to the application. 

#### a) do not allow reset-password for unverified users
this could solve the problem, but the password-reset functionality seems currently to be the only way to prevent locked out users which did not receive or have lost their verification email. that means that if this option is implemented, a `resendVerificationEmail()` functionality is required from my point of view.

from my understanding, it is currently not possible to configure this behavior over the payload config, as there is no `beforePasswordReset` hook which could throw an error if the user is not verified. maybe there are ways to configure it i have not thought of?

#### b) do not perform auto-login after password-reset
this would definitely have a negative impact on the user experience. it could be limited to unverified users, but it could get hard for users to understand why they are not able to login with their updated credentials. this would require an explicit login error message. 

and again, the problem with lost verification emails must be solved somehow.

#### c) trigger `beforeLogin` and `afterLogin` hooks after password is reset
this could make it possible to configure the desired behavior over the payload config: if an error is thrown in `beforeLogin`, the user is not automatically logged in. 

it would be nice to have an additional parameter in the hooks to be able to distinguish between "normal logins" and "password-reset" logins. 

#### d) auto-verify on password reset
one could argue that if the user was able to receive the forgot-password email, the user is implicitly verified. then the `_verified` flag should automatically be set to `true` on password-reset if the collection has "verify" activated. 

from my understanding this is currently not configurable over the payload config because there is no `afterPasswordReset` hook and the `afterLogin` hook is not triggered. 

--
ps: thank you so much: payload is an amazing project! keep up the excellent work!

**Comment by jmikrut** [comment]
Hey @berndb — this is a great catch. And thank you for the compliments! Payload is just getting started. LOTS more in store, especially in the next ~30 days. Keep an eye out.

I've implemented your suggestion in D. It's great.

PR will be merged and this will be released likely tomorrow!
