### ISSUE TITLE
Incorrect behavior of depth with richText internal link

### ISSUE THREAD

**Issue by Elliot67** [payloadcms/payload#2134]
# Bug Report

The richText `link` element is not correctly populated in the API response according to the  `depth` parameter. The problem occurs when the content uses internal link and the `relationship` element isn't enabled.

## Steps to Reproduce

1. Create a new Global document with the following configuration
```ts
const MyGlobal = {
  slug: "my-global",
  access: {
    read: () => true,
  },
  fields: [
    {
      type: "richText",
      name: "content",
      admin: {
        elements: [
          "link",
          //"relationship"
        ],
      },
    },
  ],
};
```
2. Create an internal link inside the richtext field from the admin interface.
2. Access the API endpoint `http://localhost:3000/api/globals/my-global?depth=1`, the `depth` parameter is not taken into account.
3. Uncomment the `relationship` element from the richtext field configuration.
4. The `depth` parameter is now working properly !

## Fix

I have no idea about the possible implications, but it looks like it can be fixed by just adding a check to the `link` element inside `src/fields/hooks/afterRead/promise.ts`

```diff
    case 'richText': {
+      if (((field.admin?.elements?.includes('relationship') || field.admin?.elements?.includes('upload') || field.admin?.elements?.includes('link')) || !field?.admin?.elements)) {
-      if (((field.admin?.elements?.includes('relationship') || field.admin?.elements?.includes('upload')) || !field?.admin?.elements)) {
        populationPromises.push(richTextRelationshipPromise({
          currentDepth,
          depth,
          field,
          overrideAccess,
          req,
          siblingDoc,
          showHiddenFields,
        }));
      }

      break;
    }
```

**Comment by jmikrut** [comment]
Hey @Elliot67 — great catch!

Your suggested fix was exactly what was needed also. Good stuff all around. Merged a fix and will be released shortly.

Thank you!
