### ISSUE TITLE
Changes in src/mongoose/buildQuery.ts broke ApiKey strategy

### ISSUE THREAD

**Issue by lilnotes** [payloadcms/payload#2148]
# Bug Report

I have a typical collection of users with ApiKey enabled.
A few days ago req.user started returning random(indeed, the last) user, when I send requests using Api Key.

I found that this commit broke ApiKey strategy
https://github.com/payloadcms/payload/commit/1930bc260e721c5c7a10793b5d2a7809694089f3
and exactly this part of code:
```
      if (['salt', 'hash'].includes(path) || schemaType?.options?.hidden) {
        return undefined;
      }
```
It just removes where-clause to search user, because
ApiKey schemaType.options look like this:
```
..
  options: SchemaStringOptions {
    unique: false,
    required: false,
    index: false,
    hidden: true,   <==============================Pay attention to this!!!
    type: [Function: String]
  },
..
}
```

And here:
```
    async function buildQuery(rawParams, locale) {
        const paramParser = new ParamParser(this, rawParams, locale);
        const params = await paramParser.parse();
        return params.searchParams;
    }
```
instead of getting `{ apiKeyIndex: { '$eq': 'SECRET KEY' } }`
I get :  `{}`

As a result this request https://github.com/payloadcms/payload/blob/master/src/auth/strategies/apiKey.ts#L40
```
      const userQuery = await find({
        where,
        collection: {
          Model,
          config,
        },
        req: req as PayloadRequest,
        overrideAccess: true,
        depth: config.auth.depth,
      });
```
returns all users
and put into req.user the last one (in my case)

## Steps to Reproduce
1. create 2 users
2. enable ApiKey for the oldest one
3. create endpoint or hook where you will be able to check headers and req.user
4. send request with ApiKey => you'll get wrong user in req.user

**Comment by jmikrut** [comment]
Hey @lilnotes — thank you for the report! You are exactly right. We've added a fix and will be releasing it tomorrow. 

Keep an eye out!
