### ISSUE TITLE
Querying second nested collection value

### ISSUE THREAD

**Issue by jpmadrigal07** [payloadcms/payload#2150]
# Bug Report

I have these collections,

Location Group
Location
Post

Location Group has a value "title" string.
Location has a value "group" which relates to Location Group and "title" string.
Post has a value "location" which relates to Location.

When I'm trying to use dot notation on REST query on Post using location.locationGroup.title, it's not working, but when I use location.title, its working.

## Steps to Reproduce

I also found the same issue with @jacobsfletch's "website-cms" (https://github.com/payloadcms/website-cms)

This is the file that I'm having problem:
https://github.com/payloadcms/website-cms/blob/main/src/collections/Posts.ts

1. Create a Post record with the author filled
2. Create a query for "author.photo.alt", it will shows nothing
3. Create a query for "author.firstName", it will shows the record

If you notice it, photo is the second nested collection and I'm suspecting that is the cause of the issue.

## Other Details

Payload Version: 1.2 and 1.6

**Comment by jacobsfletch** [comment]
Thanks for the report @jpmadrigal07! The query we expect to work here is `?where[author.photo.alt][equals]=Write%20for%20the%20Community%20Blog%20Image`. Related discussion: https://discord.com/channels/967097582721572934/1076804860969754695

**Comment by itsjxck** [comment]
This may or may not be directly related to this issue, but I also notice this behaviour when trying to query a `Block` that has a `relationship` field. Related discussion to this: https://discord.com/channels/967097582721572934/1077903102159618068

**Comment by mat-twg** [comment]
Not working with `[or][and]`
