### ISSUE TITLE
Relationship field with `relationTo` array bug

### ISSUE THREAD

**Issue by nrezvoi** [payloadcms/payload#2153]
# Bug Report

Cannot remove relationship in the UI when the field has an array in `relationTo`

![image](https://user-images.githubusercontent.com/15609653/220347658-6bfd7edf-47d3-43b2-9e5b-f500f43b97ec.png)

Clicking on the remove button produces the following error
![image](https://user-images.githubusercontent.com/15609653/220348072-af1921b0-06c7-46d6-958b-753a7aa6ad3f.png)

## Steps to Reproduce

1. Create relationship field in a collection
2. Set `relationTo` to array with collection slugs (can set 1 but it must be an array)
3. Select relation in the UI picker and try to remove by clicking on the remove button
## Other Details

Payload version: 1.6.13

**Comment by DanRibbens** [comment]
Accidentally tagged #2196 on this yesterday, that is unrelated.

This was completed with 2188, look for it in the next release.
