### ISSUE TITLE
Required fields on draft-enabled collections flash red before successfully saving

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#2160]
# Bug Report

If you have a collection with `versions.drafts` enabled and you try to create a new entry or update an old one, the fields flash in red before they're successfully updated.

https://user-images.githubusercontent.com/5570098/220632967-6bf6e120-f420-4c76-81b2-b2bb90943cc4.mov

Here's a sample collection config for reproduction:

```ts
import { CollectionConfig } from "payload/types";

export const BlogPosts: CollectionConfig = {
	slug: "blog-posts",
	versions: {
		drafts: true,
	},
	fields: [
		{
			name: "title",
			type: "text",
			required: true,
			localized: true,
		},
	]
};
```

## Expected Behavior

Since you're authoring a draft, it's obviously incomplete and the required checks should probably be ignored. In other words, the user shouldn't see any errors.

However, if the user tries to publish the document, empty required fields should display errors and the operation should fail.

## Other Details

Payload version: 1.6.15

**Comment by jmikrut** [comment]
Good call. 

Fix incoming! Thank you!
