### ISSUE TITLE
Strange behaviour when pressing return in bullet point lists

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#217]
# Bug Report

When you are working in a bullet or unordered list most rich text editors will allow you to add a new bullet point by pressing enter. Pressing backspace on an empty bullet point would end or split the list formatting.

## Expected Behavior

Pressing enter would create a new bullet point.

Pressing backspace when no text in bullet will end list.

## Current Behavior

Pressing enter creates an indented line just bellow the bullet point.

![image](https://user-images.githubusercontent.com/3854592/124222152-2a5a1700-db3c-11eb-9c22-91234290f1f6.png)

Pressing CTRL + Z will restore the bullet point... for some reason

Pressing backspace removes the item entirely but puts the cursor back on the line above.

## Reproduction steps

1. Go to any slate editor in payload
2. Create a bullet list
3. Press enter
4. Try to backspace

## Detailed Description

Payload 0.7.2

**Comment by jmikrut** [comment]
Hey @richardvanbergen — this is now released, including the backspace optimization, in `0.7.5`!
