### ISSUE TITLE
Fields that do not get populated through `defaultValue` get cleared.

### ISSUE THREAD

**Issue by ccz82** [payloadcms/payload#2179]
# Bug Report

For example, a collection has at least 2 relationship fields with `hasMany: true` and for its `defaultValue`, has an async function which retrieves the collection IDs using fetch() to prefill the relationship fields. The collection also has a simple `text` field.

The relationship fields get populated properly, however when the collection is saved, the `text` field is cleared in the admin panel. The same thing occurs when trying to edit the collection. However, the original document is not modified so values in the `text` field still gets saved properly.

This does not happen when the collection only has one of these relationship fields.

## Steps to Reproduce

Collection fields
```javascript
fields: [
    {
      name: 'title',
      type: 'text',
    },
    {
      name: 'categories',
      type: 'relationship',
      relationTo: 'categories',
      hasMany: true,
      defaultValue: async () => {
        const response = await fetch(`/api/categories`);
        const { docs } = await response.json();
        const categories = docs.map((category) => category.id);
        return categories;
      },
    },
    {
      name: 'colors',
      type: 'relationship',
      relationTo: 'colors',
      hasMany: true,
      defaultValue: async () => {
        const response = await fetch(`/api/colors`);
        const { docs } = await response.json();
        const colors = docs.map((color) => color.id);
        return colors;
      },
    }
  ]
```

## Other Details

Payload version 1.6.15

**Comment by jmikrut** [comment]
Wow, typically I have a pretty good understanding of why something would happen, but in this case, I have no idea. We will try and replicate on Monday to see what we can come up with.

Thanks for the report!
