### ISSUE TITLE
useField() hook validation option causes infinite re-renders.

### ISSUE THREAD

**Issue by msoyka** [payloadcms/payload#2180]
# Bug Report

https://user-images.githubusercontent.com/16545161/221286264-af67324a-5646-4003-8d03-930e823067b7.mov

useField() hook validation option causes infinite re-renders when creating a custom react component.

## Steps to Reproduce

1. Add validation function to useField() options, with console.logs for visuals.
2. Turn on React Dev Tools profiler option to show re-renders. (outlines it if it re-renders)
3. Look at number of logs and the fact that the outline from re-render debugger never goes away, which shows it is in a constant state of re-rendering.
4. remove validate function, and see that it stops the infinite re-rendering.

## Other Details

**Example Hook**
```
const field = useField<string>({
    label,
    name,
    path,
    validate: (value, options) => {
      console.log("validate value: ", value);
      console.log("validate options: ", options);
      return "not working";
    },
  } as Options);
```

- Google Chrome

Assuming there is a bug in a useEffect() hook that related to the validation option of the useField() hook. Would be ideal if it was triggered  only on input value changed.

**Comment by jmikrut** [comment]
Hey @msoyka this is not a bug in Payload and is instead a bug with your code. What’s happening is that you are defining a _new_ validate function every time that your component renders, which causes the hook to execute again every time _it_ renders. 

You should define your validation using useCallback or useMemo and then you’ll be good!
