### ISSUE TITLE
images loosing animations

### ISSUE THREAD

**Issue by chaoky** [payloadcms/payload#2181]
# Bug Report

Animated images, in gifs or webps are being processed as a single frame, sharp supports resizing and compressing these without loosing animations since v0.30.0.

It should be fairly straight forward to support this and I could take a stab later.

**Comment by pooledge** [comment]
It is still creating stills on resize of a gif for me in 2.5.0

**Comment by matteo-naif** [comment]
I have still the same problem with Payload 2.12.1
