### ISSUE TITLE
Media in RichText editor loose file unexpectedly after edit and save existed media without changes

### ISSUE THREAD

**Issue by jmas** [payloadcms/payload#2185]
# Bug Report

Hello! I found small issue that related to RichText editor > Edit media behaviour.  
What I do: I created item in collection `Posts`, this item has Rich Text field `body`, I added media into `body` field, saved `Post`, then open this post again, click Edit media, press save media, close media editor, save post, refresh page - see that media still present in `body`, but image (file) of this media is absent (also absent on the disk). I expect that image (file) still present.

![payload_media_issue](https://user-images.githubusercontent.com/90701/221425971-36ee5ed1-fd84-4a9c-91c8-f1cfa7dcf5c4.gif)

```ts
// payload.confid.ts

// in collection `Posts.fileds`
{
  name: "body",
  type: "richText",
  required: true,
  admin: {
    elements: [
      "h2",
      "h3",
      "link",
      "ul",
      "ol",
      "blockquote",
      "upload",
    ],
    leaves: ["bold", "italic", "strikethrough", "code"],
  },
},

// in collection `Media`
{
  slug: "media",
  admin: {
    useAsTitle: "id",
    defaultColumns: ["id", "createdAt"],
    group: "Uploads",
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: "caption",
      type: "textarea",
    },
  ],
  upload: {
    staticURL: "/media",
    staticDir: "media",
    imageSizes: [
      {
        name: "thumbnail",
        width: 400,
        height: 300,
        position: "centre",
      },
      {
        name: "card",
        width: 768,
        height: 1024,
        position: "centre",
      },
      {
        name: "tablet",
        width: 1024,
        // By specifying `null` or leaving a height undefined,
        // the image will be sized to a certain width,
        // but it will retain its original aspect ratio
        // and calculate a height automatically.
        // height: null,
        position: "centre",
      },
    ],
    adminThumbnail: "thumbnail",
    mimeTypes: ["image/*"],
  },
}
```

## Steps to Reproduce

1.  Add `Posts`
2.  Add image
3.  Save post
4.  Open created post for edit
5.  Edit image
6.  Save image
7.  Save post
8.  Refresh post and see that image is absent, file deleted from the disk

## Other Details

Payload version: 1.6.9

Possible solution: I see that when we save media we send `PATH` request, I think server expect to see `file: (binary)` in request, but get nothing and probably thatwhy it delete file from the disk. I guess we can send URL of current file to determinate that we do not want to delete file.

**Comment by ChrisGV04** [comment]
I had this issue as well and it was solved on the 1.6.13 version if I'm not mistaken. Maybe you should give it a try with the latest Payload version

**Comment by jacobsfletch** [comment]
@jmas yea I think @ChrisGV04 is right here. There have been a number of recent fixes around uploads and rte and I think this is one of them. I went ahead and went through the same steps you've outlined but on the latest branch, but I cannot recreate this. Here's a screen recording of my working instance: 

https://user-images.githubusercontent.com/15735305/221673596-271b51dc-1ee0-4f3f-9078-284cffa5ab79.mp4

**Comment by jmas** [comment]
@ChrisGV04 @jacobsfletch Thanks, guys for point me to install new version. I updated to V 1.6.15 and the bug is gone. I'll change my approach of posting issues to GitHub, I'll test bugs on latest version before do post. Thanks!

**Comment by lucaceck95** [comment]
Hi everyone
I'm having a same issue.

I'm adding a Link in my rich text field. The Link will be a relation with Media collection.
On first save, everything is ok.
On second save, i've got an empty link with "null" value. 

I'm using payload 1.15.8

**Comment by jacobsfletch** [comment]
Roping @AlessioGr in here ^

**Comment by lucaceck95** [comment]
Hello, any updates here?
I can't find a workaround for this issue

**Comment by AlessioGr** [comment]
Hey @lucaceck95 , you're on a very old version of payload. Can you try if v2 of payload resolves the issue for you? It's likely fixed there already.

**Comment by lucaceck95** [comment]
just updated to v2.3.0
it works ;)

thank you
