### ISSUE TITLE
Example "virtual fields" broken

### ISSUE THREAD

**Issue by vimkat** [payloadcms/payload#2186]
# Bug Report

When running the [`virtual-fields`](https://github.com/payloadcms/payload/tree/master/examples/virtual-fields) example, "virtual" fields get saved to the database despite the [`README.md`](https://github.com/payloadcms/payload/tree/master/examples/virtual-fields#how-it-works) stating otherwise.

Thanks for helping out and all your awesome work on Payload!

## Steps to Reproduce

1. Follow the [Getting Started](https://github.com/payloadcms/payload/tree/master/examples/virtual-fields#getting-started) section
2. Check the MonogDB collection for `locations` (document 1)
3. Navigate to the "Grand Rapids" location in the admin panel
4. Click "save"
5. Check the MongoDB collection for `locations` again (document 2)

### document 1
```json
{
  "_id": {
    "$oid": "63fba46e7fa46d725c39100c"
  },
  "city": "Grand Rapids",
  "state": "MI",
  "country": "USA",
  "events": [],
  "createdAt": {
    "$date": {
      "$numberLong": "1677436014476"
    }
  },
  "updatedAt": {
    "$date": {
      "$numberLong": "1677436014476"
    }
  },
  "__v": 0
}
```

### document 2
```json
{
  "_id": {
    "$oid": "63fba46e7fa46d725c39100c"
  },
  "city": "Grand Rapids",
  "state": "MI",
  "country": "USA",
  "events": [
    "63fba46e7fa46d725c391020",
    "63fba46e7fa46d725c391021"
  ],
  "createdAt": {
    "$date": {
      "$numberLong": "1677436014476"
    }
  },
  "updatedAt": {
    "$date": {
      "$numberLong": "1677436455152"
    }
  },
  "__v": 0,
  "location": "Grand Rapids, MI, USA",
  "nextEvent": "63fba46e7fa46d725c391020",
  "staff": [
    "63fba46e7fa46d725c39101c"
  ]
}
```

**Comment by jacobsfletch** [comment]
Thanks @vimkat! A fix for this was merged in just now.
