### ISSUE TITLE
Can't create more than 1 document with REST API using API Key

### ISSUE THREAD

**Issue by sixers** [payloadcms/payload#219]
# Bug Report

I'm not able to create objects with REST API + API Keys. Somehow, Payload checks for `email` field, and wants it to be unique. Because my Collection model doesn't have email field, I can't create more than one document.

## Expected Behavior

I should be able to create multiple documents with REST API

## Current Behavior

The POST request is successful for the first document (if there are no other documents of given type in database), the subsequent API requests fail with the following error:

```json
{
    "errors": [
        {
            "name": "ValidationError",
            "message": "The following field is invalid: email",
            "data": [
                {
                    "message": "Value must be unique",
                    "field": "email"
                }
            ]
        }
    ]
}
```

Stacktrace:

```
[14:10:08] ERROR (payload): ValidationError: The following field is invalid: email
    at new ExtendableError (/Users/mateusz/Projects/Bestool/bestool/node_modules/payload/dist/errors/APIError.js:22:15)
    at new APIError (/Users/mateusz/Projects/Bestool/bestool/node_modules/payload/dist/errors/APIError.js:38:9)
    at new ValidationError (/Users/mateusz/Projects/Bestool/bestool/node_modules/payload/dist/errors/ValidationError.js:10:9)
    at Payload.create (/Users/mateusz/Projects/Bestool/bestool/node_modules/payload/dist/collections/operations/create.js:151:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Payload.create (/Users/mateusz/Projects/Bestool/bestool/node_modules/payload/dist/collections/requestHandlers/create.js:10:21)
```

## Steps to Reproduce

1. Add the following collections:

```typescript
const Admin: CollectionConfig = {
  slug: "admins",
  labels: {
    singular: "Admin",
    plural: "Admins",
  },
  auth: {
    tokenExpiration: 7200, // 2 hours
    verify: false,
    maxLoginAttempts: 5,
    lockTime: 600 * 1000, // lock time in ms
    useAPIKey: true,
    depth: 0,
    cookies: {
      secure: false,
      sameSite: "lax",
      domain: undefined,
    },
  },
  fields: [],
  timestamps: true,
  admin: {
    useAsTitle: "email",
  },
};

const Producer: PayloadCollectionConfig = {
  slug: "producers",
  fields: [
    {
      name: "name",
      type: "text",
      unique: true,
      required: true,
    }
  ],
};

```

2. Create an admin user, and enable API Key access

3. Issue a POST request to `http://localhost:3000/api/producers`, with the following header:

```
Authorization: Admin API-Key <my-key>
```

with the following data:

```json
{
    "name": "some name"
}
```

4. Issue another POST request, with different data

## Detailed Description

Payload version: 0.7.4

**Comment by jmikrut** [comment]
Hey @sixers — quick thought here. We'll do some further digging but this sounds like your database _**might**_ have a leftover index from an earlier time where you may have created a `producers` collection as auth-enabled, but then went in and removed auth.

Using MongoDB Compass, you should be able to connect to your Mongo DB and then check its Indexes. I bet you have a leftover `email` index that is set to unique.

![image](https://user-images.githubusercontent.com/6651896/124615995-bc676580-de43-11eb-8455-93612b4dc830.png)

Will you check there and let me know? If this is not it, we will continue to dig!

**Comment by sixers** [comment]
@jmikrut That's it, thanks!

**Comment by jmikrut** [comment]
Nailed it - good stuff!

**Comment by piavgh** [comment]
> Hey @sixers — quick thought here. We'll do some further digging but this sounds like your database _**might**_ have a leftover index from an earlier time where you may have created a `producers` collection as auth-enabled, but then went in and removed auth.
> 
> Using MongoDB Compass, you should be able to connect to your Mongo DB and then check its Indexes. I bet you have a leftover `email` index that is set to unique.
> 
> ![image](https://user-images.githubusercontent.com/6651896/124615995-bc676580-de43-11eb-8455-93612b4dc830.png)
> 
> Will you check there and let me know? If this is not it, we will continue to dig!

This is exactly the issue that I had today. Thanks a lot
