### ISSUE TITLE
Encountered two children with the same key, `tags-id:r0:`

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#2221]
# Bug Report

```
Warning: Encountered two children with the same key, `tags-id:r0:`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

## Steps to Reproduce

1. Add a custom id field to any collection
2. Open the list page of the collection

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/5801015/222462327-3f606f65-1539-4f20-aae4-d076c2809b17.png">

## Other Details

payload@1.6.16

**Comment by jacobsfletch** [comment]
@Stupidism thanks for bringing this up! This was likely introduced in that latest release and related to the columns selector. We'll get a patch out for this asap.
