### ISSUE TITLE
Type issue with validations

### ISSUE THREAD

**Issue by jonas-de** [payloadcms/payload#2243]
# Bug Report

### Context
I need to implement some additional validation logic, i.e. making a field required (or optional) based on other fields in the document. I achieve this by using a custom validation function that accesses the provided document and depending on the state of the document the default validation function is called with changed arguments.

### Problem
As far as I checked it seems that data in ValidateOptions should have the Partial<Document> as type but instead has the type Partial<Field>. 

Validate has the following signature: 
`export type Validate<T = any, S = any, F = any> = (value: T, options: ValidateOptions<F, S, Partial<F>>) => string | true | Promise<string | true>;`

and ValidateOptions this one:

```
export type ValidateOptions<T, S, F> = {
    data: Partial<T>;
    siblingData: Partial<S>;
    id?: string | number;
    user?: Partial<User>;
    operation?: Operation;
    payload?: Payload;
    t: TFunction;
} & F;
```

So `F` of Validate should be the type of the field that is validated but at the same time the type of the entire document.

## Steps to Reproduce

1. Create a simple collection with custom validation

```
const Collection: CollectionConfig = {
  slug: 'some-collection',
  fields: [
    {
      name: 'foo',
      type: 'text',
      required: true,
    },
    {
      name: 'bar',
      type: 'text',
      validate: customValidation,
    }
}
```

2. Try to create a properly typed validation function:

```
const customValidation: Validate<unknown, unknown, TextField> = (value, args) => {
  if (args.data.foo === 'someSpecialValue') {
    return text(value, { required: true, ...args });
  }
  return text(value, args);
}
```

3. Check error "TS2339: Property 'foo' does not exist on type 'Partial '."

4. If instead the document type is used (`Validate<unknown, unknown, SomeCollection>`, where SomeCollection is the auto-generated with payload generate:types, the error in the `text(value, args)`call is the following: "TS2345: Argument of type 'ValidateOptions<SomeCollection, unknown, Partial<SomeCollection>>' is not assignable to parameter of type 'ValidateOptions<TextField, unknown, Partial<TextField>>'."

## Other Details

- Payload version: 1.6.16
- One probably needs to add a 4th type variable to Validate to pass the actual type of the document

**Comment by jmikrut** [comment]
Hey @jonas-de — good find. I just pushed a fix. It will be released later today.

👍

**Comment by dustbort** [comment]
@jmikrut Unfortunately, defaulting `TFieldConfig = any` results in `Validate = (value: any, options: any) => [snip]` -- it has erased the type of the `options` parameter so it gives us no help when defining `validate` on any field!  What is the purpose of `TFieldConfig`? If it is the config of the field itself, would it be better to put it as a prop, like so?

```
export type ValidateOptions<TData, TSiblingData, TFieldConfig> = {
  data: Partial<TData>
  siblingData: Partial<TSiblingData>
  id?: string | number
  user?: Partial<User>
  operation?: Operation
  payload?: Payload
  t: TFunction
  config: TFieldConfig
};
```
