### ISSUE TITLE
Media Edit Page throws error because sizes are removed from response

### ISSUE THREAD

**Issue by mirko-tomhave-abi** [payloadcms/payload#2253]
# Bug Report

The Media Edit Page can't get loaded because there is a error within the FileDetails Component. 

```
imageSizes.forEach(({ name }) => {
        if (sizes[name]) {
            orderedSizes[name] = sizes[name];  // <-- Cannot read properties of undefined
        }
    });
```

I did some debugging and found out that in `iterateFields` our `sizes` get removed because of this line: 

```
if (!fieldIsPresentationalOnly(field) && !field?.admin?.disabled) {
```

the `sizes` seem to have `{ hidden: true, disabled: true }`

which results in removing them from the Object being passed to FileDetails later on. 
when setting `disabled: false` everything works as expected. (manually while debugging)

## Steps to Reproduce

1. Set `imageSizes` in `upload` for Media Collection:

```
...
upload: {
    adminThumbnail: 'xs',
    formatOptions: { format: 'webp' },
    imageSizes: [
      {
        name: 'xs',
        width: 640,
        height: 360,
        formatOptions: { format: 'webp' },
      },
      ...
    ],
  },
...
```
2. A configured S3Adapter from the cloud-storage-plugin. ( `disableLocalStorage` is set to `true` )
3. upload a image
4. validate that `sizes` is set within the Database
5. go to admin/collections/media/ and select the uploaded Media 
6. Run in to described error.

## Other Details

Payload version: 1.6.16
Cloud Storage Plugin version: 1.0.12

It seems like setting `disabled` to false for `sizes` results in the Page being loaded. 
I haven't figured out where it is set and how to change it.

**Comment by jmikrut** [comment]
Hey there - try and update your cloud storage plugin to the newest version. This was fixed about 4 weeks ago.

If the issue persists, we can re-open this issue but I'm pretty sure you'll have a fix there!
