### ISSUE TITLE
Dragging and Dropping (New) Blocks Causes "Cannot find descendant" Error

### ISSUE THREAD

**Issue by TheDunco** [payloadcms/payload#2272]
# Bug Report

I've found that dragging and dropping blocks in a blocks field under certain conditions will cause a "Cannot find descendant" error. I'm not sure if this is coming from whatever drag and drop library Payload's using, or if this is from custom code.

<details>
<summary>Text version of first error</summary>

Do note that the content in the first node here is what's in the paragraph above (not shown in video), the content in the second (that I've bolded) is in the Paragraph block I just added in the video.

Uncaught Error: Cannot find a descendant at path [0,14] in node: {"children":[{"type":"ul","children":[{"children":[{"text":"Hardness","bold":true},{"text":": a material's resistance to wear and scratching"}],"type":"li"},{"children":[{"text":"Strength","bold":true},{"text":": a material's ability to be stressed without becoming permanently deformed."}],"type":"li"},{"children":[{"text":"Ductility","bold":true},{"text":":  a material's ability to become permanently deformed under stress before it breaks."}],"type":"li"}]}],"operations":[],"selection":{"anchor":{"path":[0,14],"offset":189},"focus":{"path":[0,14],"offset":189}},"marks":null,"id":5,"history":{"undos":[{"operations":[{"type":"remove_node","path":[0],"node":{"children":[{"text":""}]}},{"type":"insert_node","path":[0],"node":**{"children":[{"text":"Lorem ipsum "},{"text":"dolor","bold":true},{"text":" sit amet, consectetur adipiscing elit. Sed lacus ligula, faucibus sit amet mauris sed, dapibus viverra risus. Donec sit amet efficitur dui. Quisque id "},{"text":"volutpat","bold":true},{"text":" "},{"text":"purus","italic":true},{"text":", vel interdum dolor. Nam ornare leo nunc. Sed at eros nec nunc vehicula posuere ac at libero. Etiam sed sollicitudin nunc. Donec efficitur eros nec nibh porttitor, efficitur tempus lectus gravida. Pellentesque mollis, enim non bibendum imperdiet, "},{"text":"diam","bold":true},{"text":" sem malesuada velit, ut vestibulum nibh dolor id dui. Vivamus "},{"text":"cursus","bold":true,"italic":true},{"text":" eleifend justo pulvinar mollis. Vestibulum pretium massa et rhoncus pretium. Fusce odio dolor, tristique non ultricies eu, faucibus vitae nibh. Suspendisse potenti. Mauris tellus mi, hendrerit sed commodo vel, "},{"text":"fermentum","bold":true},{"text":" "},{"text":"cursus","bold":true,"italic":true},{"text":" mi. Integer sodales convallis feugiat. Fusce aliquam pretium urna rutrum laoreet. Fusce hendrerit, odio et facilisis vestibulum, nunc arcu congue augue, at volutpat eros odio finibus urna."}]}}],**"selectionBefore":{"anchor":{"path":[0,0],"offset":0},"focus":{"path":[0,0],"offset":0}}}],"redos":[]}}
    at Object.get (index.es.js:2487:1)
    at Object.common (index.es.js:2349:1)
    at getCommonBlock (getCommonBlock.js:7:1)
    at isListActive (isListActive.js:8:1)
    at ListButton (ListButton.js:45:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)

</details>

## Steps to Reproduce

[Video showing this behavior](https://streamable.com/74d1sy) - Note that the video was too big for GitHub. This link will expire in 24hrs, so please contact me if you need another copy of it.

I haven't tried this in a fresh/clean instance, but the way I was able to reproduce it consistently is by...
1. Have a blocks field (mine's in a collapsible)
2. Add a new block of content to the array of pre-existing content.
3. Before saving, attempt to drag and drop to move the old block below the new content.
4. The above step doesn't seem to work as it should the first time (as shown by the click and drag not doing anything in the video), so...
5. Attempt to perform step 3. again
6. The screen will go blank and the errors are logged to the console.

This has happened before by dragging the new content as well.

## Other Details

Payload version < v1.16.11 -> v1.16.17
Browser is the latest version of Chrome on MacOS

Let me know if you need more info, but this is causing some serious frustration for our team. They're scared their work will be lost so they've resorted to hitting save constantly like early 2000's Microsoft Word 😆

**Comment by jmikrut** [comment]
Hey @TheDunco — figured this out! Thanks for the issue and the details. That is super helpful when we go to recreate and we really appreciate it.

It ended up being a strange Slate side-effect but the fix was simple.

Releasing a patch version now!

**Comment by TheDunco** [comment]
Awesome, that's great to hear! Thanks for the quick fix, y'all rock! 🥇
