### ISSUE TITLE
Global setting for pagination seems to be wrongly typed

### ISSUE THREAD

**Issue by wiesson** [payloadcms/payload#2282]
# Bug Report

It looks like I can't set the pagination globally despite the types allow it.

I'd like to add

```Typescript
pagination: {
    defaultLimit: 100,
    limits: [100, 250, 500, 1000],
}
```

to the global configuration but some errors prevents that:

```Zsh
[15:47:44] ERROR (payload): There were 1 errors validating your Payload config
[15:47:44] ERROR (payload): 1: "admin.pagination" is not allowed
[nodemon] app crashed - waiting for file changes before starting...
```

## Other Details

Latest version of Payloadcms (1.6.19)

**Comment by PatrikKozak** [comment]
Hey @wiesson  - we are removing the `pagination` type from the top level admin config types for now as global pagination is not implemented just yet - but I went ahead and created a feature request ([here](https://github.com/payloadcms/payload/discussions/2303)) - we will get to this as soon as we can!
