### ISSUE TITLE
The preview function is not available in the relationship collapsed window

### ISSUE THREAD

**Issue by zhounewz** [payloadcms/payload#2314]
# Bug Report

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/16400882/224873230-118bcb5a-11a6-49ea-ad1e-2f8c2ebb26d8.png">

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/16400882/224872910-b7a7ace6-fc25-4be3-b6f8-d03f43364ca4.png">

## Steps to Reproduce
1. Create an "Article" collection; create a "DynamicTable" collection, this collection enables the preview function.
2. On the DynamicTable collection page (/admin/collections/dynamic-tables/640d897913b5be1d8ffb7060), the preview function works normally
    
<img width="1554" alt="image" src="https://user-images.githubusercontent.com/16400882/224873973-b19f3c4c-c548-48ac-959c-6a50ae606675.png">

3. In the article page, insert a "DynamicTable" through the relationship, and preview it directly on the article page. The doc parameter in the preview function callback is an error
    
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/16400882/224874150-652b10d2-f658-4c0c-8862-02e955681811.png">
 
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/16400882/224874948-56ecb4f0-9121-42ca-a6b7-8cf3050ef7b6.png">

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/16400882/224875049-cbbd4209-7a8a-40c5-90fa-75d212b8aa18.png">

## Other Details
**payload version**
"payload": "1.6.17",

**Comment by jacobsfletch** [comment]
@zhounewz thank you for the detailed description here 👍. I'm not able to recreate this, though. Here's a quick screen recording so you can see exactly what I've got on my end:

Uploading Screen Recording 2023-03-14 at 12.15.51 AM.mp4…

Closing for now. Feel free to provide more information and we can reopen if needed.

**Comment by jacobsfletch** [comment]
This was on latest `master` branch.

**Comment by zhounewz** [comment]
@jacobsfletch Thanks!
I have tested with the latest version V1.6.20 and this version does not have this problem. Upgrading the version should solve this problem
