### ISSUE TITLE
Regenerating image sizes deletes original images

### ISSUE THREAD

**Issue by slavanossar** [payloadcms/payload#2315]
# Bug Report

I'm returning to a project that was paused and was running `1.0.36`. I successfully upgraded `payload` and other packages (also ran [the migration script in `1.6.1`](https://github.com/payloadcms/payload/blob/master/CHANGELOG.md#161-2023-02-01)).

I wanted to add an `opengraph` size to the `imageSizes` for an existing `images` collection, but when running [this `regenerateMediaSizes` script](https://github.com/payloadcms/payload/discussions/1834) all images are deleted except for:

* The transforms for the newly defined `opengraph` image size, for all images.
* Three placeholder images and their transforms (not including new `opengraph` size) that were uploaded prior to upgrading from `1.0.36`.

### Before
<img width="358" alt="image" src="https://user-images.githubusercontent.com/7077600/224910834-cf389c81-9c58-49a6-a891-1a3d352a53c2.png">

### After
<img width="367" alt="image" src="https://user-images.githubusercontent.com/7077600/224910858-4e0072a1-e7e8-4cd3-a85a-f07a639a0ca9.png">
<img width="369" alt="image" src="https://user-images.githubusercontent.com/7077600/224912108-c098844d-6cbd-49c7-be08-2d23d5b50337.png">

## Steps to Reproduce

Don't think I can articulate how to reproduce this, but the CMS data isn't sensitive, so happy to create a reproduction repo and provide a DB dump and archive of the images directory if needed.

Here is my adapted `regenerateMediaSizes` script that references my collection handle and specifies the correct `staticDir`:

```js
const payload = require('payload')
const path = require('path')

require('dotenv').config()

const { PAYLOAD_SECRET, MONGODB_URI } = process.env

const regenerateMediaSizes = async () => {
  try {
    await payload.init({
      secret: PAYLOAD_SECRET,
      mongoURL: MONGODB_URI,
      local: true,
    })

    const images = await payload.find({
      collection: 'images',
      depth: 0,
      limit: 300,
    })

    await Promise.all(images.docs.map(async (imageDoc) => {
      try {
        const staticDir = path.resolve(__dirname, './uploads/images')

        await payload.update({
          collection: 'images',
          id: imageDoc.id,
          data: imageDoc,
          filePath: `${staticDir}/${imageDoc.filename}`,
          overwriteExistingFiles: true,
        })

        console.log(`Media ${imageDoc.alt || imageDoc.id} regenerated successfully`)
      } catch (err) {
        console.error(`Media ${imageDoc.alt || imageDoc.id} failed to regenerate`)
        console.error(err)
      }
    }))
  } catch (err) {
    console.log('Unable to find documents with payload')
    console.error(err)
    process.exit(0)
  }

  console.log('Media size regeneration completed!')
  process.exit(0)
}

regenerateMediaSizes()
```

## Other Details

`payload@1.6.20`

**Comment by jmikrut** [comment]
Hey @slavanossar — figured out what was happening here and we will be adding tests / releasing in a patch version shortly.

As always, thank you for the level of information you provide! It makes solving the issue very quick and we appreciate it.

**Comment by slavanossar** [comment]
And thank you for the lightning fast responses and fixes!
