### ISSUE TITLE
DateField.admin.date is not documented well

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#2331]
# Documentation Issue

<img width="506" alt="image" src="https://user-images.githubusercontent.com/5801015/225780969-0d1fad6a-577a-4722-a276-5228ec89c375.png">

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/5801015/225780935-561c41a3-e90b-4234-97b9-b0cc392d5a13.png">

**Comment by andwrobs** [comment]
also on this, added a PR to fix the ambiguous default formatting of "dayOnly" to better reflect what the user is actually selecting: https://github.com/payloadcms/payload/pull/2344

**Comment by AlessioGr** [comment]
I really hate the naming overall. Would prefer "MMM d, yyy" to be "date", and "MMM d, yyy time" to be "dateAndTime" or something like that.

Then "day" can just be the day

**Comment by andwrobs** [comment]
> I really hate the naming overall. Would prefer "MMM d, yyy" to be "date", and "MMM d, yyy time" to be "dateAndTime" or something like that.
> 
> 
> 
> Then "day" can just be the day

i'd say if the usecase is to capture the numeric value of day- aka a standalone number 1-31, a number input with max as 31 works fine.

i'd expect a non-dated "day" input to be "Mo/Tu/W/..." day of week style picker
