### ISSUE TITLE
relationship filter don't work

### ISSUE THREAD

**Issue by zhenxianchen** [payloadcms/payload#2332]
# Bug Report

## Steps to Reproduce

1. open the relationship filter pannel
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/20765130/225803650-3f1914e4-0f6b-4896-be44-fc80a3702830.png">
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/20765130/225803591-724c945f-38c4-4e5d-bb86-6a655c278db8.png">
2. filter with name, dosen't work
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/20765130/225803457-37d39dea-a324-4a66-bfa0-888d1f8fd776.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/20765130/225803396-252b40e7-fd59-44eb-98e4-f6883db39ecc.png">

3. but the collection has the "title" field will work
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/20765130/225847708-217c1c52-ba2a-491c-8db0-f270f900f32b.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/20765130/225847766-4c624099-6571-4397-ac6d-146ae0a99119.png">

4. it's normal in the List view
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/20765130/225849139-840586a4-7faf-4fdd-a17d-31ad549927bf.png">

## Other Details
version: 1.6.17
browser: chrome

**Comment by jmikrut** [comment]
Thanks @zhenxianchen — we're on it. Will try and reproduce ASAP and get a fix out!

**Comment by JessChowdhury** [comment]
Hi @zhenxianchen - I am getting the correct behavior when reproducing this. 

> 2. filter with name, dosen't work

In this screenshot, you search for 'farmers-signal-app-1' which appears to be a value of the slug field **not** the name field. If you type in just 'farmers', then what does it return?
