### ISSUE TITLE
graphql issue: Filter by id, expect to return one piece of data, and return multiple pieces of data as a result

### ISSUE THREAD

**Issue by zhounewz** [payloadcms/payload#2339]
# Bug Report

## Steps to Reproduce

**graphql issue: Filter by id, expect to return one piece of data, and return multiple pieces of data as a result**

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/16400882/225876697-ee519059-09d9-4ac0-9e31-72e770d578c3.png">

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/16400882/225878486-8d0d239e-26a1-4020-8e2b-5264c950886d.png">

**Comment by jmikrut** [comment]
I believe this is duplicative of #2323 - correct? Same underlying idea - just affecting both REST and GraphQL APIs the same, which makes sense. 

I will close this to keep conversation going on #2323.
