### ISSUE TITLE
Can't Access PUBLIC_PAYLOAD env variables in preview function in production build

### ISSUE THREAD

**Issue by foopis23** [payloadcms/payload#2378]
# Bug Report
I want to add a preview button to a collection that redirect to an external website. I setup a public env variable and created the preview function. Everything works fine in development, but in production the env variable is undefined. It tries to redirect me to `undefined/path/to/somewhere` instead of `${PAYLOAD_PUBLIC_PREVIEW_URL_BASE}/path/to/somewhere`

## Steps to Reproduce
Collection Config
```ts
const News: CollectionConfig = {
  slug: 'news',
  admin: {
    preview: (doc) => {
      return process.env.PAYLOAD_PUBLIC_PREVIEW_URL_BASE + `/news/${doc.id}?preview=true`;
    }
  },
  fields: []
}
```

And .env
```
PAYLOAD_PUBLIC_PREVIEW_URL_BASE=https://google.com
```

1. Create a new payload project
2. Add a collection like listed above
3. Add the env variable to the .env file
4. See that it works when using npm run dev
5. Then, run `npm run build && npm run serve` and see that the preview link is now undefined

## Other Details

I took a look at the code and saw how the env variables are being injected. I think the problem is just that the docs recommends loading the .env file in the server.ts file, but when running a production build for the admin portal, server.ts doesn't get loaded. My first thought is that the build CLI can just take an argument or env variable for where the .env file actually is and load that

**Comment by jmikrut** [comment]
If you load your `.env` file using `dotenv` or similar, you can load it in the actual Payload config as well. No harm in duplicating that, and that will make sure that even your `build` process gets your env variables. I will tag this as `documentation` though and leave it open until we add clarity to the docs!

**Comment by foopis23** [comment]
Okay, that makes sense. I wasn't sure if you could add it to the config safely or not.

My work around solution ended up being that I installed the env-cmd package and changed my build:payload command to.

```
"build:payload": "env-cmd cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload build"
```

**Comment by ballermatic** [comment]
@foopis23 Have you tried this in production? I am getting build failure on Railway but not locally. I tried adding your solution to the [preview example](https://github.com/payloadcms/payload/tree/master/examples/preview) but that only seems to work with local builds.

Here's what I see on Railway…

`#11 1.539 $ env-cmd cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload build
 
#11 1.671 Error: Failed to find .env file at default paths: [./.env,./.env.js,./.env.json]
#11 1.671     at getEnvFile (/home/node/app/node_modules/env-cmd/dist/get-env-vars.js:58:11)
#11 1.671     at async Object.EnvCmd (/home/node/app/node_modules/env-cmd/dist/env-cmd.js:39:15)
#11 1.671     at async Object.CLI (/home/node/app/node_modules/env-cmd/dist/env-cmd.js:19:16)
#11 1.698 error Command failed with exit code 1.`

The ENV variables are added in the Railway interface, but env-cmd seems to want an actual file. 

That said, before adding cmd-env, payload:build was not picking up the ENV variables at all. They append in dev, but not on build.

**Comment by jmikrut** [comment]
Hey @ballermatic — have you tried adding `dotenv` to the top of your Payload config? I just added some more docs that talk about this but that should solve your issue as well.

**Comment by ballermatic** [comment]
@jmikrut dotenv worked, thanks!

**Comment by IlyasM** [comment]
@jmikrut hi, but how to make serverURL in buildConfig dynamic, we want to build it once, and run with different environment variables. For now it seems we are not able to run it with different variables, it fallbacks to the build process ones.
