### ISSUE TITLE
registerFirstUser doesn't auto-verify the user 

### ISSUE THREAD

**Issue by jmikrut** [payloadcms/payload#2384]
### Link to reproduction

N/A

### To Reproduce

- Start with a blank users collection with no users
- Enable email verification on that users collection
- Visit admin panel
- Create first user
- See that the auto-login fails because the user is not auto-verified

### Describe the Bug

A user created via `registerFirstUser` should be auto-verified if `verify` is set to `true`.

### Payload Version

1.6.22

**Comment by notchris** [comment]
To add onto this issue as it may be related, I noticed an oddity where if I create a new user and check the verified checkbox, the checked state of the checkbox is not preserved on save. However, once the user is saved/created, the checkbox will function as expected (state is saved). @jmikrut mentioned this may be related. 

For some background, we have users who can create an account but are approved by a manager manually. In addition, this manager populates accounts for existing customers and mentioned this issue to me.
