### ISSUE TITLE
Filtering documents using `where` with virtual fields doesn't work as expected

### ISSUE THREAD

**Issue by svntime** [payloadcms/payload#2398]
### Link to reproduction

https://github.com/payloadcms/payload/tree/master/examples/virtual-fields

### To Reproduce

1. Clone vritual-fields repo from https://github.com/payloadcms/payload/tree/master/examples/virtual-fields
2. Run the app and go to http://localhost:3000/api/graphql-playground
3. Try to query all `Events` having `totalPrice <= 100` (or other documents containing a virtual field)

All documents:
![image](https://user-images.githubusercontent.com/42152930/227797926-d60df570-911f-4c60-94aa-090645e927e0.png)

Filtered documents:
![image](https://user-images.githubusercontent.com/42152930/227797957-99e6fa88-aaee-4f10-825c-561e68006512.png)

Rest API example: http://localhost:3000/api/events?where[totalPrice][less_than_equal]=100

### Describe the Bug

Hi there! I'm not sure if this should be a bug report or rather a feature request but current behavior can be quite confusing for someone.

When someone tries to dynamically calculate the value of a field on each request (as described in https://payloadcms.com/blog/learn-how-virtual-fields-can-help-solve-common-cms-challenges), they may also want to use that field inside the "where" filter. The problem is that the filtering is done before the correct hooks are run, so the result will always be wrong. Of course I tried to set `beforeRead` hook on the entire collection (and update the value here instead of the `afterRead` hook) but it didn't work either. The only one that was run every time was `beforeOperation`.

I'm afraid this works as expected, but it could be a great feature request then. If there is a better way to filter documents using such abstractions, I would be more than grateful for any tips. Thanks!

### Payload Version

1.6.11

**Comment by DanRibbens** [comment]
If you need to query on data, best practice is to persist it for efficiency. Consider any database system, Payload aside, in order to calculate a value from some fields to query for, you we've got to read every record and do the calculation to know which to filter. It isn't a good idea to do this. The cost to store that data quickly pays for itself in IO and compute costs.

For that reason this isn't a good candidate for a new feature and I wouldn't describe it as a big either. Perhaps a documentation change to the readme could be accepted to avoid any confusion.

What do you think?

**Comment by svntime** [comment]
I see, thanks for clarification Dan. Since this was mainly my misunderstanding, I think a simple note in the docs would be more than enough (somewhere around the `where` filter, maybe here: https://payloadcms.com/docs/queries/overview#graphql-find-queries) but it's not necessary.

**Comment by b00y0h** [comment]
> If you need to query on data, best practice is to persist it for efficiency. Consider any database system, Payload aside, in order to calculate a value from some fields to query for, you we've got to read every record and do the calculation to know which to filter. It isn't a good idea to do this. The cost to store that data quickly pays for itself in IO and compute costs.

do you simply mean not using a `beforeChange` hook to delete the data? I'm not clear on what you mean by persisting the data. I'm in a similar boat in that I'm needing to query another collection (A) to grab a value out of it and populate a field in another collection (B). My graphql where query is not working on that field

**Comment by JarrodMFlesch** [comment]
@b00y0h You could use the beforeChange hook to instead _save_ the data on the collection. So when the document is saved it will calculate and store the value and you will be able to filter on it.

You either use a virtual field to create data on-the-fly as it exits the DB and is sent back to you, or you use a real field that is persisted in the DB.

If you already have data saved you would need to write a little script that loops and saves data so the beforeChange hook has a chance to save the data to the DB. Heres [an example](https://github.com/payloadcms/payload/discussions/434).

**Comment by b00y0h** [comment]
@JarrodMFlesch thanks! that's super helpful. Would that be a field level hook or a collection hook? (i'm still not clear on when to use which one)

**Comment by JarrodMFlesch** [comment]
@b00y0h You would use a collection hook, so when the doc is updated/created it has access to all the data on the doc for you to create your new field based on the doc data.
