### ISSUE TITLE
Collection List View: Relationship titles not displayed when "en" localization is not localized

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#2437]
### Link to reproduction

https://github.com/AlessioGr/payload/tree/repro

### To Reproduce

1. Make sure you are in the "de" locale
2. Create a document in the "Posts" and a document in the "Collection2s" collection. Make sure the Collection2s collection document has a relationship to the document in the Posts collection.

### Describe the Bug

![Arc 2023-04-02 at 22 30 02@2x](https://user-images.githubusercontent.com/70709113/229377465-28325a12-a565-4f45-8c81-64f11871632e.jpg)

Now, you should see that the relationship for the Collection2s collection in the list view does not show the title of the referenced posts relationship.

The moment you add a translation for the "en" locale, it works - despite "en" not being the default locale.

It seems that when looking for the title of a referenced relationship in the collection's list view, it only looks for the "en" locale and not the current locale. Ref: https://discord.com/channels/967097582721572934/1091805251344019609

### Payload Version

1.6.29

**Comment by ssyberg** [comment]
Bumping this for support, related PR is open and ready for review.

**Comment by JarrodMFlesch** [comment]
Hey @ssyberg got around to reviewing, that has been merged in! Thanks again @AlessioGr 👍 

Will be released in the next version.

**Comment by ssyberg** [comment]
Woot!
