### ISSUE TITLE
Add documentation for JWT Token encryption / decryption

### ISSUE THREAD

**Issue by notchris** [payloadcms/payload#2441]
# Documentation Issue

The JWT token that Payload creates is encrypted using the Payload secret key. However, the key is first encrypted using sha256 and then truncated to 32 characters. This information is not provided in the documentation for people who would like to decrypt the JWT stored in session cookies (among other scenarios). I wrote a small example function that I use in an express route (separate API) to decrypt the JWT's (it's really just the Payload encryption logic but reversed).  I think this information will be helpful to folks who would otherwise think the payload secret itself is sufficient for decryption.

```ts
// Token verification
const verifyToken = (
  req: express.Request,
  res: express.Response
): string | false => {
  if (req.cookies["payload-token"]) {
    const hash = crypto
      .createHash("sha256")
      .update(process.env.PAYLOAD_SECRET)
      .digest("hex")
      .slice(0, 32);

    try {
      const decoded = jwt.verify(req.cookies["payload-token"], hash, {
        algorithms: ["HS256"],
      });

      if (!decoded) return false;

      const { repid } = decoded as jwtResponse;

      return repid;
    } catch (err) {
      console.log("Invalid token request.", err);
      return false;
    }
  } else {
    console.log("Missing token in request.");
    return false;
  }
};
```

## Additional Details

https://discord.com/channels/967097582721572934/1090945883836792862

**Comment by jmikrut** [comment]
Hey @notchris — Jess and I worked on adding a bit to the docs re: how we handle secrets. 

Good call - thank you for the report!
