### ISSUE TITLE
Collections on `Config` are not compatible with exported `CollectionConfig` that is exported from `payload/types`

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#245]
# Bug Report

I'm trying to implement my plugin as a plugin so that I can release it and get some feedback on it. But I've hit a bit of a roadblock in the form of a typescript error.

My plugin uses `CollectionConfig` of `payload/types` to return the modified collection but the incomming `Config` collections are  not compatible.

The full error is pasted bellow

![image](https://user-images.githubusercontent.com/3854592/127154343-06b68458-7dae-49f0-b086-4a1f4acfd07b.png)

```
Type 'PayloadCollectionConfig[]' is not assignable to type 'CollectionConfig[]'.
  Type 'PayloadCollectionConfig' is not assignable to type 'CollectionConfig'.
    Types of property 'auth' are incompatible.
      Type 'boolean | IncomingAuthType' is not assignable to type 'Auth'.
        Type 'boolean' is not assignable to type 'Auth'.ts(2322)
types.d.ts(134, 5): The expected type comes from property 'collections' which is declared here on type 'Config'
```

**Comment by jmikrut** [comment]
Ah, yes, this has to do with an inner complexity of Payload's TS implementation. We are going to come up with a better naming pattern for our internally used types to be more clear.

The long story short is that _**incoming**_ configs are allowed to be partially complete, thus need their own types where some (not all) properties are optional. Internally, incoming config types are called `PayloadConfig`, `PayloadCollectionConfig`, `PayloadGlobalConfig`, etc. Then, validated and sanitized configs are internally used as simply `Config`, `CollectionConfig`, etc.

You are importing the "partial" collection config, which really should only be used by end users when they are authoring partially complete configs. Plugins, on the other hand, are provided with a fully sanitized and validated config, so a plugin will expect to return the full `CollectionConfig`, which can, for now, be imported like this:

```js
import { CollectionConfig } from 'payload/dist/collections/config/types';
```

We are pushing a release later today, and we will expose this type more "officially" and document it accordingly. I will update this issue at that time.

How's that?

**Comment by richardvanbergen** [comment]
That's great and thanks for the quick reply. I guess the documentation was written that way for a reason. I thought it was a mistake 😆 

One other slight issue though it's now saying that the way I'm assigning hooks is incorrect.

```
Type '{ beforeOperation?: BeforeOperationHook[]; beforeValidate?: BeforeValidateHook[]; afterChange?: AfterChangeHook[]; beforeRead?: BeforeReadHook[]; ... 7 more ...; afterDelete: CollectionAfterDeleteHook[]; }' is not assignable to type '{ beforeOperation: BeforeOperationHook[]; beforeValidate: BeforeValidateHook[]; beforeChange: BeforeChangeHook[]; afterChange: AfterChangeHook[]; ... 7 more ...; afterForgotPassword: AfterForgotPasswordHook[]; }'.
  Property 'beforeOperation' is optional in type '{ beforeOperation?: BeforeOperationHook[]; beforeValidate?: BeforeValidateHook[]; afterChange?: AfterChangeHook[]; beforeRead?: BeforeReadHook[]; ... 7 more ...; afterDelete: AfterDeleteHook[]; }' but required in type '{ beforeOperation: BeforeOperationHook[]; beforeValidate: BeforeValidateHook[]; beforeChange: BeforeChangeHook[]; afterChange: AfterChangeHook[]; ... 7 more ...; afterForgotPassword: AfterForgotPasswordHook[]; }'.ts(2322)
```

```ts
export function withS3Storage (
  s3Configuration: AWS.S3.ClientConfiguration,
  fileOptions: FileOptions,
  collection: CollectionConfig,
  getUrl: (filename: string) => string,
): CollectionConfig {
  init(s3Configuration, fileOptions)

  collection.fields = [
    ...collection.fields,
    {
      label: 'S3 URL',
      name: 's3Url',
      type: 'text',
      admin: {
        readOnly: true,
      },
      hooks: {
        beforeChange: [
          (): undefined => undefined,
        ],
        afterRead: [
          ({ data }): string => {
            return getUrl(String(data.filename))
          },
        ],
      },
    },
  ]

  const {
    beforeChange = [],
    afterDelete = [],
    ...rest
  } = collection.hooks || {}

  collection.hooks = { // <-- error at this line
    beforeChange: [
      uploadToS3,
      ...beforeChange,
    ],
    afterDelete: [
      deleteFromS3,
      ...afterDelete,
    ],
    ...rest,
  }

  if (isUploadObject(collection.upload)) {
    collection.upload.adminThumbnail = ({ doc }: Doc) => doc.s3Url
  }

  return collection
}
```

**Comment by jmikrut** [comment]
OK - so, this could be a stupid TS error. Your logic works, but it looks to me like TS can't interpret the `...rest` spread that you're doing within the `collection.hooks` object. TS knows that the `hooks` object should be filled with **_at minimum_** empty arrays, but it can't see that the `...rest` spread would be actually handling that for you, so TS thinks that you're missing the rest of the hook arrays (your collection config at this point needs to be fully sanitized.)

Can you try to simply spread `...collection.hooks` there, instead?

**Comment by Ontopic** [comment]
Did you perhaps upgrade recently? I'm also facing validation errors that were not there in previous verions. The logging is much better, still guide an adventure

```
[20:45:14] ERROR (payload): There were 8 errors validating your Payload config
[20:45:14] ERROR (payload): 1: Collection "demos" > Field "blocks" > "value" does not match any of the allowed types
[20:45:14] ERROR (payload): 2: Collection "articles" > Field "blocks" > "value" does not match any of the allowed types
[20:45:14] ERROR (payload): 3: Collection "templates" > Field "sidebar" > "value" does not match any of the allowed types
[20:45:14] ERROR (payload): 4: Collection "pages" > Field "blocks" > "value" does not match any of the allowed types
[20:45:14] ERROR (payload): 5: Collection "reviews" > Field "blocks" > "value" does not match any of the allowed types
[20:45:14] ERROR (payload): 6: Collection "previews" > Field "blocks" > "value" does not match any of the allowed types
[20:45:14] ERROR (payload): 7: Collection "strategies" > Field "blocks" > "value" does not match any of the allowed types
[20:45:14] ERROR (payload): 8: Collection "competitions" > Field "blocks" > "value" does not match any of the allowed types
```

**Comment by DanRibbens** [comment]
@Ontopic Can you share one of your block fields so I can confirm we didn't introduce a bug in the validation?
The last release shouldn't have had any breaking changes.

**Comment by Ontopic** [comment]
I switched back to `0.7.8` for now, to look at it more carefully later. I was able to pinpoint it to one block, not sure the code is useful though 😅

```
export const Newslist = {
  slug: 'Newslist',
  fields: [
    createRow({
      sidebar: true,
      fields: [
        createInteger('offset', 0, 0),
        createInteger('limit', 5, 1, 250),
      ],
      widths: ['50%', '50%'],
    }),
    {
      type: 'row',
      fields: [
        createBoolean('includePreviews', true, { readOnly: true }),
        createBoolean('includeStrategies', true, { hidden: true }),
      ]
    },
    {
      name: 'tags',
      type: 'relationship',
      relationTo: ['tags'],
      hasMany: true,
      required: false,
    },

    {
      type: 'row',
      admin: {
        hidden: true,
      },
      fields: [
        createBoolean('showThumbnail', false),
        createBoolean('showFlag', true),
        createBoolean('showVotes', true),
        createBoolean('showDate', false),
        createBoolean('showCategory', true),
      ]
    },
    
    createFoldable({
      title: 'Dates',
      sidebar: true,
      isOpen: true,
      fields: createPostDateFields(false, '100%'),
    }),
  ],
}
```

**Comment by Ontopic** [comment]
Could very well be something broke in the codebase somewhere or an issue we had with our DB server. I'll let you know tomorrow if it was just a stupid mistake on my end or if something in the validation changed.

**Comment by jmikrut** [comment]
@Ontopic let us know. The demo config boots up, as do a few of our super complex projects using the new version of Payload. The validation may have gotten more strict, which might be surfacing some invalidities in existing configs. 

Usually what I do when I need to troubleshoot something like this is to simply blow away fields until the error goes away.. then reverse-engineer from there. We'll be on standby tomorrow for more updates!

**Comment by jmikrut** [comment]
Also - @richardvanbergen - we've got those new TypeScript naming conventions all in place!

Take a look at the docs for more info on how to use:

- https://payloadcms.com/docs/configuration/overview#typescript
- https://payloadcms.com/docs/configuration/collections#typescript
- https://payloadcms.com/docs/configuration/globals

**Comment by Ontopic** [comment]
I think I found it. After upgrading again (to 0.8.0 👻) and slowly commenting my way through this turn about to be the part breaking everything.

```
...
fields: [
  {
    type: 'row',
    admin: {
      hidden: true,
    }
...
```

So looks like before I could hide a Row. now it throws. Just glad I found it, because I can work around this not being hidden.

**Comment by richardvanbergen** [comment]
Yes @jmikrut those work for me thank you once again for the quick update.

I'm going to close this thread now 👍

**Comment by DanRibbens** [comment]
Hey @Ontopic, with https://github.com/payloadcms/payload/pull/250, you will get a type error for having the wrong admin properties for rows.

We're always trying to improve our typings, I'll try and catch these earlier in the future.

**Comment by Ontopic** [comment]
I kinda knew it wasn't meant to be used like that, but I love looking for edge-case abuse of what's possible. Thanks again from my side as well for the prompt replies, clever solutions and clean structure you keep up over there.
