### ISSUE TITLE
Considering extending docs referencing Payload sections with image examples

### ISSUE THREAD

**Issue by notchris** [payloadcms/payload#2456]
# Documentation Issue

Many of the documentation pages are very detailed and provide great code examples. However, in some cases there are references to Payload areas that may benefit from a screenshot of the area.

For instance, the [API Key](https://payloadcms.com/docs/authentication/config#api-keys) documentation includes the following paragraph. 
`To enable API keys on a collection, set the useAPIKey auth option to true. From there, a new interface will appear in the Admin panel for each document within the collection that allows you to generate an API key for each user in the Collection.`

This is a solid message, however a screenshot of the new interface would be helpful because people would know what to expect when learning about this feature.

There are other areas in the documentation that could benefit as well from a few screenshots. An added benefit is people will get to see the beautifully designed interfaces as well. 

Let me know your thoughts.

Thank you,

Chris

**Comment by juwoncaleb** [comment]
Hello . I will like to check this out and add a screenshot

**Comment by JessChowdhury** [comment]
Need to merge [this PR](https://github.com/payloadcms/website/pull/175) on the website repo - then I can upload the images.
