### ISSUE TITLE
No spacing between version status/autosave and render fields in the sidebar

### ISSUE THREAD

**Issue by qbeauperin** [payloadcms/payload#2478]
### Link to reproduction

default `versions` test

### To Reproduce

- Clone the Payload repo
- In the `versions` test, add a new field in the sidebar of the `Drafts` and `Autosave` collections, for example:
  ```javascript 
  {
      name: 'date',
      label: 'Date',
      type: 'date',
      admin: {
        position: 'sidebar',
      }
    },
    ```

- Run the test (`yarn dev versions`)
- Check the various collection pages and notice how there's no spacing between the version status/autosave status and the sidebar fields.

### Describe the Bug

There's no spacing between the version status/autosave status and the sidebar fields.
I'd suggest adding a `$baseline` margin between the two.

---

Autosave (before/after):
![image](https://user-images.githubusercontent.com/1763338/231271054-22b43647-0649-4c14-b096-f226d999442f.png) ![image](https://user-images.githubusercontent.com/1763338/231271808-ca57fd78-ae63-4b44-9541-1b46472581e3.png)

Versions (before/after):
![image](https://user-images.githubusercontent.com/1763338/231271240-6b589981-13d2-47da-847b-73e3ff3165cb.png) ![image](https://user-images.githubusercontent.com/1763338/231271468-9b1a6ec6-3942-47b6-ba55-fa5845fa13f2.png)

 ---
 
 Happy to make a PR for it, but wondering about the best approach. I can see a couple options:
1. **Apply `margin-bottom` to `&:has(+ .render-fields)` on both `.status` and `.autosave`:** this would keep the spacing logic confined to their respective components. The issue is that `:has` isn't yet [fully supported](https://caniuse.com/css-has).
2. **Apply `margin-top` to `& + .render-fields` on both `.status` and `.autosave`:** alternative to 1.
3. **Wrap both `.status` and `.autosave` into a common div or component:** both 1. and 2. wouldn't be very future proof and adding another element in between or renaming the `.render-fields` div would break the fix, so given how logically tied these two elements are, I feel like the best solution would be to wrap them into their own components, and have the bottom margin applied to it.

### Payload Version

1.6.32

**Comment by jacobsfletch** [comment]
@qbeauperin thank you taking the time to report on this! Much appreciated. The simplest fix here was to use CSS `display: flex` along with the `gap: $baseline;`. This is essentially the same as `> *:not(:last-child) { margin-bottom: $baseline; }` which also would have done the trick. Check it out https://github.com/payloadcms/payload/commit/a45ab8bd7671be76f99e29852c739e858f47885c

**Comment by qbeauperin** [comment]
Ha, much better solve indeed! 🎉
