### ISSUE TITLE
Documentation Search includes "next page" titles

### ISSUE THREAD

**Issue by notchris** [payloadcms/payload#2490]
# Documentation Issue

I noticed that when searching the docs for a specific term, in some situations I would get unrelated results because the next page would include the search term. For instance, search for "rich text" and you'll notice that the [Relationship](https://payloadcms.com/docs/fields/relationship#doc) page is included in the results because of the "Next" page link at the bottom.

![image](https://user-images.githubusercontent.com/1944433/231758257-ead3d7b1-264b-44a1-a588-d8cb3d01f3e4.png)

## Additional Details

It's really nice outside today, I wish I were outside

**Comment by PatrikKozak** [comment]
Hey @notchris - this is now resolved. The `Next` component won't show up in the search results anymore. Thanks for bringing this up!
