### ISSUE TITLE
`AND` query does not work correctly with `drafts: true`

### ISSUE THREAD

**Issue by diesieben07** [payloadcms/payload#2521]
### Link to reproduction

https://github.com/diesieben07/payload/tree/where-and-drafts-reproduction

### To Reproduce

1. Create a collection and enable versions on it.
2. Attempt to use an `AND` query combined with `drafts: true` via GraphQL. For example given the above reproduction case:
    ```gql
    query {
        Posts(
            draft: true,
            where: {
                AND: [
                    {
                        text: { equals: "exampsle post" }
                    }
                ]
            }
        ) {
            docs {
                text
            }
        }
    }
    ```
    Note the intentional misspelling of "example", so no posts should be returned.

### Describe the Bug

`AND` queries combined with `drafts: true` are completely ignored by Payload. The above query returns all posts.

The reason for this is as follows:
The internal API uses `and` and `or` (defined [here](https://github.com/payloadcms/payload/blob/b80478d4b46da17cb3e953e2b33daad0c9584646/src/types/index.ts#L27-L28)). The GraphQL API however uses `AND` and `OR` (defined [here](https://github.com/payloadcms/payload/blob/85b7a490eb6fa53424986d78b893284096c040d4/src/graphql/schema/buildWhereInputType.ts#L73-L84)). Payload attempts to rectify this unfortunate discrepancy, but only for `AND` and in an insufficient manner. This is handled not in the GraphQL resolver like I would expect, instead the internal API has a special case for the `AND` key, which is not documented.
1. Internal operation `find`: https://github.com/payloadcms/payload/blob/2d0441a72e19297a5ce76b636d55141a15c43321/src/collections/operations/find.ts#L87-L92
2. Internal operation `findVersions`: https://github.com/payloadcms/payload/blob/2d0441a72e19297a5ce76b636d55141a15c43321/src/collections/operations/findVersions.ts#L58-L59

So far this is just code that isn't very pretty, but doesn't cause any problems (as far as I can tell, except potential collisions with fields named `AND` or `OR`, but that will cause problems anyways).
The bug now occurs when setting `drafts: true`, because [`appendVersionToQueryKey`](https://github.com/payloadcms/payload/blob/a703e0582df3f4706ee051cf1752c79ff4b551ef/src/versions/drafts/appendVersionToQueryKey.ts#L3-L21) is called with the unaltered `Where` parameter from the internal operation `find` (without the `and` / `AND` normalization applied) and thus fails to properly prefix the filters with `version.`. This causes a query such as `version.AND: [{text: {equals: "example post"}}]` to be generated, which is obviously nonsense.

### Payload Version

1.7.0

**Comment by jmikrut** [comment]
Daaanng good find! Fix incoming. 👍
