### ISSUE TITLE
`condition` callback has inconsistent access to `data.id`

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/payload#2524]
### Link to reproduction

n/a

### To Reproduce

1. Create a new payload app
2. Update the Example collection as below
3. Save an entry to Example

```
import { CollectionConfig } from 'payload/types';

// Example Collection - For reference only, this must be added to payload.config.ts to be used.
const Examples: CollectionConfig = {
    slug: 'examples',
    admin: {
        useAsTitle: 'someField',
    },
    fields: [
        {
            name: 'foo',
            type: 'text',
        },
        {
            name: 'someField',
            type: 'text',
            admin: {
                condition: (data, _) => {
                    if (data && data.id) {
                        return true;
                    } else {
                        console.log('Hide it!');
                        return false;
                    }
                },
            },
        },
    ],
};

export default Examples;
```

### Describe the Bug

`condition` callback has inconsistent access to `data.id`, when rendering the collection create endpoint the condition callback appears to run multiple times (2 or more) and it appears on the first run `data.id` is properly populated but all subsequent runs it is not

### Payload Version

1.7.1

**Comment by jmikrut** [comment]
Hey @ssyberg good catch. I can see how / why this might happen. Will investigate shortly!
