### ISSUE TITLE
Local API update operation doesn't respect `drafts: true` with respect to required fields

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/payload#2536]
### Link to reproduction

n/a

### To Reproduce

Create a new Payload app and update the Example collection below as follows:
```
import { CollectionConfig } from 'payload/types';

// Example Collection - For reference only, this must be added to payload.config.ts to be used.
const Examples: CollectionConfig = {
    slug: 'examples',
    versions: {
        drafts: true,
    },
    fields: [
        {
            name: 'fieldNotRequired',
            type: 'text',
        },
        {
            name: 'fieldRequired',
            type: 'text',
            required: true,
        },
    ],
    hooks: {
        afterChange: [
            async ({ doc, operation, req }) => {
                await req.payload.update({
                    collection: 'examples',
                    id: doc.id,
                    data: {
                        fieldNotRequired: 'foo',
                    },
                });
            },
        ],
    },
};

export default Examples;
```

### Describe the Bug

Local API update operation doesn't respect `drafts: true` with respect to required fields. When attempting to save a draft on the below collection a "required" error is thrown.

### Payload Version

1.7.1

**Comment by ssyberg** [comment]
JFYI setting `_status: doc._status` appears to resolve this but not ideal...

**Comment by ssyberg** [comment]
Got it thanks @JessChowdhury - I caught and fixed that infinite loop right after posting this. 

>  Also we are setting draft: true so Payload will preserve the status.

Can you clarify if this preserves the current status (draft or published) or if it only writes changes to a draft state? The docs seem to indicate the latter.

**Comment by JessChowdhury** [comment]
@ssyberg just tested and it sure does write it as a draft every time 👎 I would set `draft: doc._status` similar to your previous work around, and I'll look into this further because I don't think you should have to redeclare it.

**Comment by ssyberg** [comment]
> draft: doc._status

Yup that was going to be my solve, thank you!
