### ISSUE TITLE
RichText Internal Link autocomplete drop down filtration error

### ISSUE THREAD

**Issue by jakehopking** [payloadcms/payload#2568]
### Link to reproduction

https://github.com/jakehopking/elkli-and-hart/tree/dev

### Video of bug
https://user-images.githubusercontent.com/3432643/234507285-c17b489f-45eb-42fc-b329-35ebc3843245.mov

Try to input any character with the 'Internal Link' autocomplete dropdown input option, on any RichText field implementation on any collection / layout block.

P.S. @DanRibbens has access to the linked repo.

### Describe the Bug

- Causes the autocomplete box to fail. 
- Writes a 404 log to the browser console:
```
GET http://10.0.1.236:3000/payload/orders?where%5Band%5D%5B1%5D%5Borders%5D%5Blike%5D=h&limit=10&page=1&sort=orders&locale=en&depth=0 400 (Bad Request)
```
- Same error can be see in the browser's network tab:
```
Request URL: http://10.0.1.236:3000/payload/orders?where%5Band%5D%5B1%5D%5Borders%5D%5Blike%5D=h&limit=10&page=1&sort=orders&locale=en&depth=0
Request Method: GET
Status Code: 400 Bad Request
```

> **Note:** I do not have localisation enabled anywhere within the global or local configs.
> Therefore it's odd that `locale=en` is in this payload generated query 👈 

### UI in error state with console error
<img width="1748" alt="Screenshot 2023-04-25 at 16 14 45" src="https://user-images.githubusercontent.com/3432643/234508803-af56271a-78c9-4476-91f2-4ad18e8c257f.png">

### Payload Version

1.7.1

**Comment by jakehopking** [comment]
@DanRibbens I've updated to `1.7.3` and this issue still persists. Exactly the same errors as reported above. Any thoughts?
I would like to be able to use this feature again, and not be stuck manually entering urls.

If we can't figures this out, then can you point me to some docs where I can remove `orders` appearing in the links dropdown?

Thanks,.

**Comment by DanRibbens** [comment]
Thanks for trying the fix. We must have missed an edge-case that yours falls under. 
We don't yet have a way to omit certain collections from being queried in richtext links individually - https://github.com/payloadcms/payload/discussions/2567. We do have a way if you want to filter out some using this new feature: #2166.

Either way we need to fix the underlying problem. I fixed the same issue from happening in a few places in our tests. I'll look at it again, it might not be until Monday when I have time.
