### ISSUE TITLE
Local API Query Error updatedAt / createdAt

### ISSUE THREAD

**Issue by edtorba** [payloadcms/payload#2582]
### Link to reproduction

https://github.com/edtorba/payload

### To Reproduce

Use local API query - can be any operation, find, find by, delete, so on.

Within your query add where clause for `createdAt` or `updatedAt` properties.

e.g.
```js
const tenMinutesAgo = new Date(Date.now() - 1000 * 60 * 10);
// ...
where: {
  createdAt: {
    less_than_equal: tenMinutesAgo,
  },
},
```
Expected result: successful run.
Actual result: `QueryError: The following path cannot be queried: createdAt` (& `updatedAt`)

Failing test can be found [here](https://github.com/edtorba/payload/blob/master/test/_community/int.spec.ts)

### Describe the Bug

Have noticed when upgraded to 1.7.2 from 1.6.28 version. Relatively straight forward bug. Not much can be added here to describe it further.

### Payload Version

1.7.2

**Comment by DanRibbens** [comment]
Thanks for the report. I've confirmed this is a bug.

**Comment by x052** [comment]
I've also got a similar error for none-timestamp queries.

We have a `Group` schema with a `name` and with a relation called `site`

Query: ```
{
    "and": [{
        "name": {
            "equals": "Test"
        }
    }, {
        "site.id": {
            "equals": "xxx"
        }
    }]
}
```

Response: ```
{
    "errors": [{
        "name": "QueryError",
        "message": "The following path cannot be queried: ",
        "data": [{
            "path": ""
        }]
    }]
}
```

**Comment by x052** [comment]
Error resolved by changing `site.id` to `site`
