### ISSUE TITLE
Typescript: Local API `delete` cannot infer `docs` properly

### ISSUE THREAD

**Issue by junwen-k** [payloadcms/payload#2585]
### Link to reproduction

https://github.com/junwen-k/payload/tree/local-api-typescript-issue

### To Reproduce

1. Clone repository
2. Check types with VSCode under file `test/_community/int.spec.ts` line 50.

Type is inferred as `const docs: (TypeWithID & Record<string, unknown>)[]`, whereas it should be `const docs: MyCollection[]`.

`src/collections/config/types.ts`

I've noticed that if I change this line 
```ts
import { Config as GeneratedTypes } from '../../generated-types';
```

to

```ts
import { Config as GeneratedTypes } from 'payload/generated-types';
```

The typescript will be inferred properly.

### Describe the Bug

Types of `docs` cannot be inferred properly while using Local API's delete multiple entries.

A video is worth a thousand words, please take a look at this demo:

https://user-images.githubusercontent.com/40173716/235295388-af58201f-8da5-4e57-a8d4-ff495215ee61.mov

### Payload Version

1.7.2

**Comment by DanRibbens** [comment]
Good catch @junwen-k!
