### ISSUE TITLE
Generic documentation refinements

### ISSUE THREAD

**Issue by JarrodMFlesch** [payloadcms/payload#2594]
# Documentation Issue

@notchris has a thread going in discord [here](https://discord.com/channels/967097582721572934/1102571187336388639).

## Additional Details

We should address these and then close this issue when they are completed.

- [x] export `MyGlobal` [here](https://payloadcms.com/docs/configuration/globals#preview)
- [x] import `CollectionConfig` [here](https://payloadcms.com/docs/configuration/i18n)
- [x] export `Page` [here](https://payloadcms.com/docs/configuration/i18n)
- [x] export `Orders` [here](https://payloadcms.com/docs/configuration/i18n)

**Comment by JessChowdhury** [comment]
Changes made, added to this existing docs PR https://github.com/payloadcms/payload/pull/2589

**Comment by jacobsfletch** [comment]
Is this duplicative of https://github.com/payloadcms/payload/issues/2456?

**Comment by notchris** [comment]
@jacobsfletch The sentiment from #2456 is that some of the pages could use some images of referenced UI areas, so it could be combined with this one to consolidate issues

**Comment by JarrodMFlesch** [comment]
I think doc issues should be scoped, it is unreasonable to put all documentation issues/improvements into 1 issue. I don't think we should move the goalposts.
