### ISSUE TITLE
Querying nested properties of nested properties not working

### ISSUE THREAD

**Issue by linobino1** [payloadcms/payload#2611]
### Link to reproduction

https://github.com/linobino1/payloadcms-repro

### To Reproduce

queries like the following won't work:

```
payload.find({
    collection: 'screenings',
    where: {
      'movie.director.name': {
        equals: director.name,
      },
    },
  })
```

The query will run without raising an error, but it will not return any documents.

### Describe the Bug

`payload.query()` is not properly functioning when a nested property in a nested property is used in the `where` clause.
I would expect the above query to work, no matter how many levels of nesting are involved.

### Payload Version

1.7.4

**Comment by JarrodMFlesch** [comment]
We can look into this Monday. But thank you for the detailed server.ts file, it's much appreciated 🙏
