### ISSUE TITLE
Incorrect typescript type on `PayloadRequest.payloadAPI`

### ISSUE THREAD

**Issue by andrejpavlovic** [payloadcms/payload#2624]
### Link to reproduction

n/a

### To Reproduce

```
export const Media: CollectionConfig = {
  access: {
    read: ({req: {payloadAPI}}) => {
      switch(payloadAPI) {
        case 'graphQL': // this is what typescript shows as a possible value

        case 'GraphQL': // this is the actual value
      }
    }
  },
}
```

### Describe the Bug

`req.payloadAPI` defines `graphQL` as possible value, but it should be `GraphQL`

https://github.com/payloadcms/payload/blob/4a49640c3fc22ee74a2666cb90588b03de68644d/src/express/types.ts#L30

should be

```typescript
payloadAPI: 'REST' | 'local' | 'GraphQL';
```

It also looks like it could be undefined, such as when the uploaded file is accessed directly http. So this would probably be more correct:

```typescript
payloadAPI?: 'REST' | 'local' | 'GraphQL';
```

### Payload Version

1.7.4

**Comment by JarrodMFlesch** [comment]
100% good catch, I have seen this before but got sidetracked and never fixed. Thanks for reporting 👍
