### ISSUE TITLE
List item is very buggy

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#2645]
### Link to reproduction

https://demo.payloadcms.com/admin/collections/forms/645b61a2c76a997a0c0952eb

### To Reproduce

<img width="474" alt="image" src="https://github.com/payloadcms/payload/assets/5801015/729ff0cf-16c2-4d7f-946f-69984e33c700">

### Describe the Bug

As the text in screenshot describes

### Payload Version

demo(latest?)

**Comment by JarrodMFlesch** [comment]
I updated the demo to latest, but there is still a list issue. It's a bit different than what you are experiencing, now when you click the list toggle it will add the first list item but pressing `enter` goes to a new line without adding another list item.

**Comment by JessChowdhury** [comment]
Hi @Stupidism - I replied to your [discussion ](https://github.com/payloadcms/payload/discussions/2643) regarding the changes in `1.7.1`. In short, it's not likely the changes in this version will affect you so go ahead and update to latest then this issue will be resolved for you 👍
