### ISSUE TITLE
Richtext can't be edited after rearranging blocks

### ISSUE THREAD

**Issue by christoph-reps** [payloadcms/payload#2647]
### Link to reproduction

https://github.com/christoph-reps/payload/tree/richtext-cant-edit

### To Reproduce

- Add new item to `Seite` collection
- Add Richtext Block with some text
- Add a second Richtext Block with some text
- Move second Richtext Block before the first one
- Try to edit the text

### Describe the Bug

After carrying out these steps the richtext editor no longer accepts inputs and the console reports following error. 

```
Uncaught TypeError: editor.selection is null
    onKeyDown RichText.tsx:369
    isEventHandled index.es.js:4640
    onKeyDown index.es.js:4289
    React 15
        callCallback
        invokeGuardedCallbackDev
        invokeGuardedCallback
        invokeGuardedCallbackAndCatchFirstError
        executeDispatch
        processDispatchQueueItemsInOrder
        processDispatchQueue
        dispatchEventsForPlugins
        dispatchEventForPluginEventSystem
        batchedUpdates$1
        batchedUpdates
        dispatchEventForPluginEventSystem
        dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay
        dispatchEvent
        dispatchDiscreteEvent
2 RichText.tsx:369:44
```

### Payload Version

1.7.5

**Comment by jmikrut** [comment]
Hey @christoph-reps — thank you for the report! Fix incoming. Gonna do some further testing but expect this to be merged shortly. 

Especially thanks for the REPRODUCTION repo! That is so helpful, you have no idea.
