### ISSUE TITLE
draft = true ignores where clause with id in api call

### ISSUE THREAD

**Issue by christoph-reps** [payloadcms/payload#2662]
### Link to reproduction

https://github.com/christoph-reps/payload/tree/repo-filter-with-drafts-true

### To Reproduce

Query the posts endpoint with a id specified in the where clause
 `http://localhost:3000/api/posts/?draft=true&where[id][equals]=64623cee40db9ddbbc4b0756`

### Describe the Bug

When you call the posts endpoint with `draft`s set to true and add an `where` clause with `id` `equals` set. The endpoint returns all items from the collection. It doesn't matter if the id is a valid id.

### Payload Version

1.8.2

**Comment by jmikrut** [comment]
Hey @christoph-reps — thank you for the report and ESPECIALLY thank you for the recreation repo. That is so helpful. 

PR open, fix will be coming shortly! Thank you again!
