### ISSUE TITLE
Language picker is cut-off when there are too many languages

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#2703]
### To Reproduce

Add this to payload config:
```ts
locales: [
      'de-DE',
      'de-AT',
      'de-CH',
      'fr-CH',
      'it-CH',
      'nl-NL',
      'nl-BE',
      'fr-BE',
      'fr-FR',
      'fr-CA',
      'it-IT',
      'no-NO',
      'dk-DK',
      'se-SE',
      'fi-FI',
      'en-UK',
      'en-IE',
      'en-CA',
      'en-AU',
      'en-NZ',
      'en-US',
      'es-US',
      'es-ES',
      'en-MY',
      'pt-PT',
      'br-BR',
      'pl-PL',
      'cz-CZ',
      'hu-HU',
      'ro-RO',
      'sk-SK',
      'hr-HR',
      'sl-SL',
      'sr-RS',
      'es-CL',
      'es-MX',
      'es-AR',
      'gr-GR',
    ],
```

### Describe the Bug

![Screenshot 2023-05-24 at 11 27 55@2x](https://github.com/payloadcms/payload/assets/70709113/d184172f-cd6e-4cdb-b020-565d45776b52)

de-DE is not visible there, for example.

### Payload Version

1.8.2

**Comment by JarrodMFlesch** [comment]
Would love to see a small dialog be introduced. Wondering if others think that would be a good addition to core 🤔

**Comment by AlessioGr** [comment]
Tbh I think it'd be enough to add a small search field, as well as a scrollbar. I do like that it's just a dropdown - feels quicker and more learn than a dialog.

**Comment by DanRibbens** [comment]
We could use react-select to make it filter and scrollable. That will also be good to use when we allow multiple locales to be editable.

**Comment by JessChowdhury** [comment]
As discussed, this is an interim solution until we overhaul this localization popup: [PR here](https://github.com/payloadcms/payload/pull/2737)
