### ISSUE TITLE
RichText link custom fields are not getting saved

### ISSUE THREAD

**Issue by DanRibbens** [payloadcms/payload#2716]
Hey @DanRibbens & @mvarendorff , thanks a lot for the approach. This is excactly what I was looking for. The only thing is, that my added custom fields are not getting saved anymore. For example, I want to replace the url field with custom one, that is validating the input for https/http. Moreover I'd like to extend the fields with a link-style-field: 

``` javascript
{
      name: 'richTextContent',
      type: 'richText',
      required: true,
      localized: true,
      admin: {
        link: {
          fields: ({defaultFields}) => {
            const theDefaultFields = defaultFields.filter((field) => (field as any).name != 'url')
            const urlField = defaultFields.find((field) => (field as any).name === 'url')
            return [
              ...theDefaultFields,
              {
                name: 'url',
                type: 'text',
                required: true,
                admin: {condition: urlField?.admin?.condition, placeholder: 'https://'},
                validate: (val, options) => {
                  const errorText = options?.t('fieldValidation:invalidUrl')
                    ? options.t('fieldValidation:invalidUrl')
                    : 'Error'
                  const valid = /^(http|https):\/\/[^ "]+$/.test(val)
                  if (valid) {
                    return true
                  }
                  return errorText
                },
              },
              {
                name: 'style',
                label: 'Link Style',
                type: 'select',
                options: ['button', 'icon-link'],
              },
            ]
          },
        },
      },
    }
```

Every Field will be shown correctly:
![Screenshot 2023-05-26 145410](https://github.com/payloadcms/payload/assets/25500828/ee34aa67-fa79-4156-95e1-c793499bb166)

The only problem I have now is that as soon as I submit the link, my "link style" won't be saved. I tried it with other field types and field names - it's just not working. The new url field is working perfectly (guess because of the same name as the field before: "url") as well as the other default fields. Guess there is a problem with the payload state?

_Originally posted by @MarvinVrdoljak in https://github.com/payloadcms/payload/issues/2559#issuecomment-1564354812_

**Comment by DanRibbens** [comment]
I updated the e2e test coverage to reproduce the issue https://github.com/payloadcms/payload/commit/c3732ca9659bb7181f6f2805304c9ea4992a5533

@mvarendorff Are you available to work on this by chance? If not we can address it in our routine Monday bugfixes.

**Comment by mvarendorff** [comment]
@DanRibbens I am unfortunately not available as I am recovering from a surgery, sorry! My apologies for that error slipping through!

**Comment by DanRibbens** [comment]
> @DanRibbens I am unfortunately not available as I am recovering from a surgery, sorry! My apologies for that error slipping through!

Oh man! Get better. Don't worry about this one bit!
