### ISSUE TITLE
Restore this version does not work for docs in draft

### ISSUE THREAD

**Issue by jankocian** [payloadcms/payload#2726]
### Link to reproduction

-

### To Reproduce

1. Create a new doc
2. Save as a draft, do not publish
3. Make some changes, save another draft
4. Try to revert back to the first version
5. See how the content remains unchanged

### Describe the Bug

When a document is in Draft mode, rollback to the previous versions does not work - a new revision is created but content remains the same.

### Payload Version

1.8.3

**Comment by denolfe** [comment]
I'm not able to recreate this issue. The version rolls back correctly for me. 

Open to any extra info that you have that would allow recreation. Closing for now.
