### ISSUE TITLE
Relationship required-but-non-localized field validation error when updating global through API

### ISSUE THREAD

**Issue by qbeauperin** [payloadcms/payload#2766]
### Link to reproduction

https://github.com/qbeauperin/payload/blob/bug/global-localization-required-field/test/localization/config.ts

### To Reproduce

- run payload with this config ^
- go to the "Required Relationship Global" global, and add content in English
- run the following code to try and update Spanish through the API: 
```typescript
const response = fetch("http://localhost:3000/api/globals/required-relationship-global?locale=es", { method: 'POST', headers: { 'Content-Type': 'application/json', }, cache: 'no-cache', body: JSON.stringify({text: "some different Spanish text"}) });
```
- notice how it returns a validation error: `The following field is invalid: nonLocalizedRequiredRelationship`

### Describe the Bug

On the other hand, the exact same config has been duplicated in a collection and work as expected:
- create a new item in the "Required Relationship Collection" collection and add content in English
- run the following code to try and update Spanish through the API:
```typescript
const response = fetch("http://localhost:3000/api/required-relationship-collection/[yourdocidgoeshere]?locale=es", { method: 'PATCH', headers: { 'Content-Type': 'application/json', }, cache: 'no-cache', body: JSON.stringify({text: "some different Spanish text"}) });
```
- notice how the update went through properly

### Payload Version

1.8.5

**Comment by JarrodMFlesch** [comment]
Hey @qbeauperin! This has been reported (just linking for clarity, not like you would have known) [here](https://discord.com/channels/967097582721572934/1111375988438347846/1111375988438347846). You can install `1.8.4-canary.2` to get the fix, or wait until 1.8.4 is released 👍

**Comment by JarrodMFlesch** [comment]
Wow. Long day, closed the wrong issue. 😵‍💫

**Comment by qbeauperin** [comment]
Oh sweet, I'll pull 1.8.4 right now and test it out. Thanks Jarrod! 😄

**Comment by qbeauperin** [comment]
Issue still occurs unfortunately, same repro steps. 😢

**Comment by jacobsfletch** [comment]
@qbeauperin wow good catch here. THANK YOU for your detailed report, too. I was able to clone down your repository and easily recreate the bug. I've got the fix in PR https://github.com/payloadcms/payload/pull/2776 which will go out in the next  release.
