### ISSUE TITLE
useAuth is sometimes the latest user data and sometimes the decoded token

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#2784]
### Link to reproduction

https://github.com/thgh/payload/tree/test/2784

### To Reproduce

1. Set `saveToJWT` to a field in the `users` collection (with auth enabled)
2. Print the return value of `useAuth()`
3. Notice everything is fine
4. Update the currently logged in user in the auth collection
5. Print the return value of `useAuth()`
6. It's outdated
7. Request /api/users/refresh-token
8. Still outdated

### Describe the Bug

It's not clear why `useAuth()` returns the outdated token instead of the most recent user document.

Based on the code below, it was meant to return the user document at some point in the past. setUser and setToken both update the same state.
https://github.com/payloadcms/payload/blob/3677cf688d0e456c42068b4eab0086e64407d938/src/admin/components/utilities/Auth/index.tsx#L109-L113

### Payload Version

1.8.4

**Comment by DanRibbens** [comment]
I've seen this before and come to the same conclusion. `useAuth` should have the full user object insetead of being reassigned to the decoded JWT user object.

**Comment by thgh** [comment]
I would suggest something like this:

```
const user = useUser()
const { user, token, decoded } = useAuth()
```

Potentially even removing user from useAuth as it has a different lifecycle than auth.

**Comment by jacobsfletch** [comment]
Hey @thgh take a look at #2813 and let me know what you think! As I wrote in the PR, we're considering this a feature request because the current behavior is the intended one, where refreshing the token does _exactly_ what it's named after, it only refreshes the _expiration date_ of the given token.

**Comment by thgh** [comment]
Reviewed!

If the changes to src/admin/components/utilities/Auth/index.tsx make it in Payload, that would be great! That means users see the UI after a page refresh.

Refreshing the full token is lower prio as that will only resolve the short blink when the token and user object are out of sync. Ideally, the useAuth hook detects mismatches between user object and token and refreshes when needed.
