### ISSUE TITLE
`req` not persisted in local API

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/payload#2795]
### Link to reproduction

n/a

### To Reproduce

I've created the following two collections in a vanilla payload install:

Examples:
```
export default {
    slug: 'examples',
    fields: [
        {
            name: 'test',
            type: 'text',
            hooks: {
                afterRead: [
                    async ({ req }) => {
                        console.log('req.args in Examples', req.args);
                        const related = await req.payload.findByID({
                            collection: 'related',
                            id: '6481dd025b553a53e3d2c850',
                        });
                    },
                ],
            },
        },
        {
            name: 'related',
            type: 'relationship',
            relationTo: 'related',
        },
    ],
};
```

Related:
```
export default {
    slug: 'related',
    fields: [
        {
            name: 'related',
            type: 'text',
            hooks: {
                afterRead: [
                    ({ req }) => {
                        console.log('req.args in Related', req.args);
                    },
                ],
            },
        },
    ],
};
```

Create a record in each, add a relationship from Examples to Related, and use the Related ID in the findByID above. Access the Example record via API and watch the console, you should see the following:
```
req.args in Examples { foo: 'bar' }
req.args in Related undefined
req.args in Related { foo: 'bar' }
```

### Describe the Bug

The express `req` object is not persisted in local API calls during a single request. 

### Payload Version

1.8.2

**Comment by jmikrut** [comment]
Hey @ssyberg — just dropping a note to acknowledge the report. Will be looking into this on Monday.

Thanks for opening the issue!

**Comment by jmikrut** [comment]
Hey @ssyberg - so, this is actually a funny thing.

We _**used to**_ spread the `req` and persist the entire thing through local API operations, but Node 18 introduced a very obscure bug with certain aspects of the `req` not being able to be copied to a new object.

We deliberately moved toward instead recreating a _**new**_ `req` instead.

And being that there is no way for us to know which custom properties you are using on a given `req`, we unfortunately can't predict which properties to maintain / carry over to newly constructed `req`s within Payload's Local API.

BUT

Instead, we're introducing a `req.payloadContext` approach here:

https://github.com/payloadcms/payload/pull/2796

This is a deliberate pattern meant to not only expose custom properties that Payload knows about, but to indeed thread them through to additional Local API calls.

Anything you bind to that pattern will be passed through, as you'd expect.

I will make a note on that PR to ensure that we pipe the context through additional Local API calls, but that will be the way forward here. So I will close this issue and defer to that new PR.

Thank you!
