### ISSUE TITLE
Upload Field resizing

### ISSUE THREAD

**Issue by JosefBredereck** [payloadcms/payload#2804]
### Link to reproduction

#

### To Reproduce

1. create a new collection
2. include upload field
3. set up the different sizes
4. upload an image with ratio 200x200

### Describe the Bug

I have created a media collection to upload images in different sizes.

After I uploaded different images, I encountered the problem that some of them were not cropped and resized as expected.

I uploaded an image with the ratio of 200x200 and the output gave me only:

- file-name-62x46.jpg
- file-name-64x64.jpg
- file-name-120x120.jpg

I know that sharp can also upscale images. For 200x200 it maybe not be the best idea, but if the image has different ratios and the UI is relying on specific sizes that could cause an issue.

```typescript
upload: {
    adminThumbnail: 'highlight',
    staticDir: path.resolve(__dirname, '../../media'),
    staticURL: '/media',
    mimeTypes: ['image/png', 'image/jpeg'],

    imageSizes: [
      { name: 's', width: 320, height: undefined },
      { name: 'm', width: 480, height: undefined },
      { name: 'l', width: 780, height: undefined },
      { name: 'preview', width: 62, height: 46, position: 'attention' },
      { name: 'card_list', width: 64, height: 64, position: 'attention' },
      { name: 'highlight', width: 120, height: 120, position: 'attention' },
      { name: 'category', width: 384, height: 512, position: 'attention' },
      { name: 'xs_16_9', width: 480, height: 270 },
      { name: 's_16_9', width: 720, height: 480 },
      { name: 'm_16_9', width: 1280, height: 720 },
      { name: 'l_16_9', width: 1920, height: 1080 },
    ],
  },
```

After further investigation I came accros this code https://github.com/payloadcms/payload/blob/4b2b4c3f9f7283e795ec9483640170163d7c4157/src/uploads/imageResizer.ts#L129-L133
where payload checks against the various sizes and if a resize is required.

I would like to request something like a `forceResize: boolean` property, which would override the result of this function.

### Payload Version

1.9.1

**Comment by anthonyivol** [comment]
I had a similar issue : https://github.com/payloadcms/payload/discussions/1638. 
I still can set upload.resizeOptions.withoutEnlargement, but it does nothing.
<img width="654" alt="image" src="https://github.com/payloadcms/payload/assets/19983700/63e3013f-d1a2-4d2b-8a32-f924460415bc">
It would be just great if developers can choose to allow upscale or not...

**Comment by JosefBredereck** [comment]
I will create a PR and see whether they let it through or not.
