### ISSUE TITLE
Field in drawer cannot be edited

### ISSUE THREAD

**Issue by MarvinVrdoljak** [payloadcms/payload#2815]
### Link to reproduction

https://demo.payloadcms.com/admin/collections/posts/64883e2234c3643f6004d016

### To Reproduce

- Login to your demo website
- Go to "Posts"and click on a post
- Click on the edit icon next to the selected category (so the edit-dialog opens)
- Try to edit field "Name"

### Describe the Bug

Some fields in a dialog are not possible to edit. This text field of your category collection in your demo website is only an example.

### Payload Version

1.9.1

**Comment by AlessioGr** [comment]
Thank you! Reproduced it in the demo with v1.9.1

**Comment by s4847043** [comment]
But the problem persist I have version 1.10.2, and I cannot still edit

**Comment by MarvinVrdoljak** [comment]
> But the problem persist I have version 1.10.2, and I cannot still edit

Yes, still having the same issue. This is still not working. Can't click into the Text-Field. Attached a video I just recorded with the official payload demo version: 

https://github.com/payloadcms/payload/assets/25500828/e05a3e11-e59c-43cc-bf5f-200b3c2491ff

**Comment by jacobsfletch** [comment]
Hey @s4847043, @Stupidism, and @MarvinVrdoljak this should be fixed with [1.11.0](https://github.com/payloadcms/payload/releases/tag/v1.11.0). Give that a shot and let me know how it goes!

**Comment by MarvinVrdoljak** [comment]
@jacobsfletch Cheers, will give it a go!
