### ISSUE TITLE
Slow text queries with large amounts of documents

### ISSUE THREAD

**Issue by rymate1234** [payloadcms/payload#2832]
### Link to reproduction

https://github.com/rymate1234/payload/tree/064aea763b329a9cfbd9b8421e79df37ad7b89b2

### To Reproduce

1. Load CMS
2. Go to posts collection
3. Search for a string
4. Note the slow loading times
<img width="568" alt="image" src="https://github.com/payloadcms/payload/assets/581104/0aa8e556-28d2-4844-b730-6278667efa5a">

### Describe the Bug

When searching a large collection, the default regex it uses to search is very slow, taking 30s with only 10k records

```
Mongoose: posts.countDocuments({ '$and': [ { '$or': [ { text: { '$regex': /(?=.*(?:(?:[^\p{L}\p{N}])|^).*sit.*(?=[^\p{L}\p{N}]|$)).+/i } } ] } ]}, {})
Mongoose: posts.find({ '$and': [ { '$or': [ { text: { '$regex': /(?=.*(?:(?:[^\p{L}\p{N}])|^).*sit.*(?=[^\p{L}\p{N}]|$)).+/i } } ] } ]}, { limit: 10, sort: { createdAt: -1 }, skip: 0, projection: {} })
```

### Payload Version

1.7.5, but reproduced in latest master

**Comment by JessChowdhury** [comment]
Hey @rymate1234 thanks for reporting, I'm looking into this 🔎

**Comment by denolfe** [comment]
I was able to recreate this. The issue is the regex changes that were introduced to support cyrillic characters for the like operation in https://github.com/payloadcms/payload/pull/1078

We'll brainstorm options to avoid this being a breaking change.

**Comment by Asheboy** [comment]
@denolfe I spoke to @rymate1234 about this and I suggested, as MongoDB's regex engine is PCRE compatible, that we could separate this regex into one used in the JS and one used in the Mongo query.
