### ISSUE TITLE
Pressing backspace closes drawer

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#2840]
### Link to reproduction

-

### To Reproduce

Open any drawer, and press backspace

### Describe the Bug

https://github.com/payloadcms/payload/assets/70709113/3f6d98a2-dbd1-4c32-819a-3d950b511151

This shouldn't happen, as backspace is also used to edit fields inside the drawer.

### Payload Version

1.9.5

**Comment by mattddean** [comment]
I'm seeing this on 1.10.5

**Comment by jacobsfletch** [comment]
Hey @mattddean this should be fixed with [1.11.0](https://github.com/payloadcms/payload/releases/tag/v1.11.0). I've included a test that covers backspace keyboard event so this should prevent any future regression. Let me know how it goes!

**Comment by mattddean** [comment]
@jacobsfletch seems to be fixed on my instance, thanks!
