### ISSUE TITLE
Relationship field shows no result with lots of content in CMS

### ISSUE THREAD

**Issue by mvdve** [payloadcms/payload#2859]
### Link to reproduction

https://github.com/mvdve/payload-relationship-issue

### To Reproduce

- Clone the repo
- Set up the project as normal by initializing the docker mongodb database and adding default user
- Run `npm run seed:articles` and `npm run seed:tags`
- Go to the cms and create a page
- Within the content field, search for an article which is not loaded by default, for example one which starts with a letter
- And there it is, no result

### Describe the Bug

When payload has a lot of content for a relationship field, the UI shows no result.

The issue was introduced in [Payload 1.8.6](https://github.com/payloadcms/payload/releases/tag/v1.8.6) Maybe [this commit](https://github.com/payloadcms/payload/commit/8b767a166aa16659d8880cc68da546251725b20b)

Related discussions:
[Relationship field missing some results](https://discord.com/channels/967097582721572934/1117668374521073745)
[Unable to add internal links to "some" collections via richtext link component](https://discord.com/channels/967097582721572934/1113407854288834601)
[Relationship Field in the admin panel does not load some results unless you scroll down](https://discord.com/channels/967097582721572934/1031993785971900556/threads/1118385770147893248)

### Payload Version

1.9.5

**Comment by wiesson** [comment]
> When payload has a lot of content for a relationship field, the UI shows no result.

I have noticed that the query sometimes has a "and-1" `where[and][1][title][like]:`, which doesn't look right. 

Sometimes, the page= query param is pointing to e.g. page 24, while I only have 8 results:
```
/api/pages?limit=10&page=24&sort=title&locale=de&depth=0
```

therefore it doesn't return anything:
```JSON
{
  "docs": [],
  "totalDocs": 8,
  "limit": 10,
  "totalPages": 1,
  "page": 24,
  "pagingCounter": 231,
  "hasPrevPage": true,
  "hasNextPage": false,
  "prevPage": 23,
  "nextPage": null
}
```

I'm not sure if that is related to the topic, but happens as well with the relation field
