### ISSUE TITLE
Nested tab with conditional rendering cause endless looping of condition function

### ISSUE THREAD

**Issue by slavanossar** [payloadcms/payload#2877]
### Link to reproduction

https://github.com/slavanossar/payload/tree/repro/nested-conditional-tab-loop

### To Reproduce

1. Go to the `Menu` global
2. Observe tab field isn't rendering
3. Meet condition by typing `abc` into `globalText` field.
4. Check console for endless `console.log('loop')`

### Describe the Bug

When creating a nest `tabs` field, if `admin.condition` is set the function is run in an endless loop and the field never display, even if the result of the function is `true`.

Just started happening in 1.10.0, maybe related to https://github.com/payloadcms/payload/commit/967f21734600de1fec8c1227a354ef5a417e54c5

### Payload Version

1.10.0

**Comment by DanRibbens** [comment]
Thanks for reporting @slavanossar!

This should be fixed with https://github.com/payloadcms/payload/pull/2890. Please update to https://github.com/payloadcms/payload/releases/tag/v1.10.1 and reopen if you still have trouble.
