### ISSUE TITLE
Improve error messaging for bad reqs

### ISSUE THREAD

**Issue by JessChowdhury** [payloadcms/payload#2879]
### Link to reproduction

https://github.com/payloadcms/plugin-sentry

### To Reproduce

Send forgot password request without body:

```
const req = await fetch('http://localhost:3000/api/users/forgot-password', {
  method: 'POST',
  credentials: 'include',
  headers: {
    'Content-Type': 'application/json',
  },
})
```

Send unlock req without body:

```
const req = await fetch('http://localhost:3000/api/users/unlock', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
})
```

This is setup and can be reproduced in the sentry plugin demo.

### Describe the Bug

Both of these bad requests return a TypeError:

> TypeError: Cannot read properties of undefined (reading 'toLowerCase')

We should update to throw a more informative error.

### Payload Version

1.9.2

**Comment by Victory-M** [comment]
@JessChowdhury The link to reproduction is broken
![Screenshot_2023-06-21-17-57-28-516_com.github.android.jpg](https://github.com/payloadcms/payload/assets/93453319/dbe15377-a965-41e2-a1c4-733aa4828555)

**Comment by JessChowdhury** [comment]
@Victory-M the repo was private but has now been made public.

**Comment by Victory-M** [comment]
@jmikrut kindly assign me to this
