### ISSUE TITLE
Conditions not working in 1.10.0

### ISSUE THREAD

**Issue by NardiniA** [payloadcms/payload#2886]
### Link to reproduction

https://github.com/NardiniA/mueller-payload-nextjs

### To Reproduce

1. Install dependencies, add .env variables and start the project.
2. Navigate to the Pages collection.
3. Create a new document in the Pages collection.
4. Under the "Hero" tab, there is a select field that should reveal a group with more fields inside. Under this tab, if the bug is present, only the select field will be there. The other fields will be hidden.

### Describe the Bug

This code is taken from the [Payload Demo](https://demo.payloadcms.com/admin) in the Pages collection. 

When using the code from the demo for a test for a new project, the condition on the group fields is not working. What is suppose to happen is the select field will show a group of fields that will be the hero/header on the frontend. This is the same as how it works on the [Payload Demo](https://demo.payloadcms.com/admin). 

However, this is not happening instead nothing happens although when you `console.log` the values they match and when you compare them with `===` they return true but still nothing happens.

I have tried refactoring my code into one file, hardcoding everything and reversing the condition to show the fields if the select doesn't match but I have had no success. 

### Payload Version

1.10.0

**Comment by jakehopking** [comment]
Can confirm I am experiencing the same bug:

https://discord.com/channels/967097582721572934/1121425799678017617

**Comment by JarrodMFlesch** [comment]
Hey everyone! Looking into this today 👀

**Comment by DanRibbens** [comment]
Fix released https://github.com/payloadcms/payload/releases/tag/v1.10.1. Thanks for reporting @NardiniA!
