### ISSUE TITLE
Importing Payload default components leads to loader errors

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/payload#2888]
### Link to reproduction

n/a

### To Reproduce

1. `npx create-payload-app` (blank app)
2. Add code from **Custom Collection List View Example** (https://payloadcms.com/docs/admin/components#collections)
3. `yarn dev` will fail with:

```
webpack built 86a0d2b7b6fdb5678bf9 in 5384ms
ERROR in ./node_modules/payload/components/views/List.ts 2:7
Module parse failed: Unexpected token (2:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { default as List } from '../../dist/admin/components/views/collections/List/Default';
> export type { Props } from '../../dist/admin/components/views/collections/List/types';
```

Using Node 18.5 and have tried on payload 1.6.2, 1.9.2, and 1.10.0

### Describe the Bug

Unable to import default component view

### Payload Version

1.10.0

**Comment by JarrodMFlesch** [comment]
This is an odd one and I am looking into it. To get around this:
- Go directly to the file in your node_modules and comment out this line:
   ```ts
   export type { Props } from '../../dist/admin/components/views/collections/List/types';
   ```
- Save the file
- Un-comment the line
- Save
- Watch webpack re-compile correctly

It has something to do with webpack and it's cache _I think_. Still looking into it...
