### ISSUE TITLE
Export of entityToJSONSchema broken

### ISSUE THREAD

**Issue by teunmooij** [payloadcms/payload#2893]
### Link to reproduction

none

### To Reproduce

Just look closely at the `src/utilities/configToJSONSchema.ts` file to see that the `entityToJSONSchema` is not exported.

### Describe the Bug

`entityToJSONSchema` is explicitely exported from `payload/utilities`. In a recent change due to an internal refactor, `configToJSONSchema` was moved to the same module and `entityToJSONSchema` is no longer exported from the module.

### Payload Version

1.10

**Comment by jacobsfletch** [comment]
@teunmooij I see what you mean, I'm on it!

**Comment by teunmooij** [comment]
@jacobsfletch , thanks. I've already created a PR

**Comment by jacobsfletch** [comment]
Aha, very good! I'll get that merged up and it'll go out in the next release 🙌

**Comment by TopHatCroat** [comment]
Awesome stuff, thank you both @teunmooij and @jacobsfletch for the rapid response ❤️
