### ISSUE TITLE
Richtext Error when fields nested in blocks have same name

### ISSUE THREAD

**Issue by puck3000** [payloadcms/payload#2897]
### Link to reproduction

/

### To Reproduce

1. Add a block with a text-field  and a block with a richtext-field to a collection. Give both fields the same name:
 
``` js
import { CollectionConfig } from "payload/types";

export const CollectionBugRedux: CollectionConfig = {
slug: 'bugRedux',
  fields: [
    {
      name: 'repeater',
      type: 'blocks',
      blocks: [
        {
          slug: 'textblock',
          fields: [
            {
              name: 'text',
              type: 'text',
            }
          ]
        },
        {
          slug: 'richtextblock',
          fields: [
            {
              name: 'text',
              type: 'richText',
            }
          ]
        }
      ]
    },
  ]
}
```

2. Add content
add content in the admin field, for example a text followed by a richtext followed by a text. 
safe the entry. 

3. Try to remove content
try to remove the first text. 
Console will error out something in the likes of 

```
Uncaught Error: [Slate] value is invalid! Expected a list of elements but got: "text"
```

### Describe the Bug

Having two fields with the same name nested in two different Blocks can lead to an uncought Error in Slate. 
Namespacing the field Names to their Blocks (ie: name: "textblockText") serves as a workaround, but a real solution would be greatly appreciated. 

### Payload Version

1.10.1 (also tested with 1.8.5

**Comment by JessChowdhury** [comment]
Hi @puck3000, I was not able to reproduce the error with the collection config you shared. Could you create a basic project (`npx create-payload-app` and choose the blank template) and try to recreate this error? If you are unable to recreate this error in a fresh project, it is possible that the error is being caused by something else in your project.

**Comment by puck3000** [comment]
Hy @JessChowdhury 

Thank you very much for taking the time to check this issue out. 
I did as you explained, this time i also uploaded the repo to github: 

https://github.com/puck3000/bugreporter

I can still reproduce the error. 
I made a short video, which you can find here: 

https://github.com/puck3000/bugreporter/blob/master/bugreport/Bugreport.mp4

Any help would be appreciated. 
Best regards
Daniel

**Comment by MarvinVrdoljak** [comment]
@JessChowdhury @jmikrut

**Comment by JessChowdhury** [comment]
@puck3000 thank you for the reproduction, I'm looking into this now 🔍
