### ISSUE TITLE
Possible type problem in payload.create with generated types

### ISSUE THREAD

**Issue by dlfk99** [payloadcms/payload#2900]
### Link to reproduction

https://github.com/payloadcms/access-control-demo

### To Reproduce

The easiest way to reproduce the problem:

- Clone the access demo repository `https://github.com/payloadcms/access-control-demo`
- update PayloadCMS to version 1.10.1
- open the file `seed.ts`

### Describe the Bug

There is a TypeScript error regarding the `create` calls:

```
  const site1 = await payload.create<Site>({
    collection: 'sites',
    data: {
      title: 'Site 1',
    }
  });
```

The error is: `Type 'Site' does not satisfy the constraint 'string | number | symbol'.ts(2344)`

I stumbled upon this in my own project and realised that the access-control-demo has the same issue. To run the type generator (payload generate:types) slightly changes the types. The error remains though.

### Payload Version

1.10.1

**Comment by JessChowdhury** [comment]
Hi @dlfk99, as of `v1.6.1` you don't need to pass your types to local API methods, instead Payload will automatically infer them for you. Read more about this change [here](https://github.com/payloadcms/payload/releases/tag/v1.6.1).

<img width="907" alt="Screenshot 2023-06-26 at 11 42 39 AM" src="https://github.com/payloadcms/payload/assets/67977755/d9f369e9-0b1e-49a5-8098-cdeea5ed3628">

**Comment by dlfk99** [comment]
Hi, thank you for the clarification. Maybe someone should update the access-control-demo? And so far I really like Payload :)
