### ISSUE TITLE
Weird regex search causing database 100%

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#2922]
### Link to reproduction

Not for now

### To Reproduce

No reproduce for now.

### Describe the Bug

We found a weird search query in database log. It takes about <100ms to run but called a large amount of times

```
{"$match":{"$and":[{"$or":[{"version.name":{"$regex":{"$regularExpression":{"pattern":"(?=.*(?:(?:[^\\p{L}\\p{N}])|^).*illinois.*(?=[^\\p{L}\\p{N}]|$)).+","options":"i"}}}}]}]}}
```

![image](https://github.com/payloadcms/payload/assets/5801015/b37c5e5e-62cf-470c-ac8a-ec88bed972af)

![image](https://github.com/payloadcms/payload/assets/5801015/cf8d5aed-6ac9-4259-84fb-5c64776145c6)

![image](https://github.com/payloadcms/payload/assets/5801015/c7c174f5-ca38-4297-ac7e-ef380d4fa4f9)

Is this regex pattern looks familiar to you guys? I tried to search in payload source code but got no luck.

### Payload Version

1.9.5

**Comment by jmikrut** [comment]
This is actually recently fixed. Just update to latest and you should be good to go!
