### ISSUE TITLE
Field in drawer cannot be edited

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#2945]
### Link to reproduction

Not for now

### To Reproduce

This is just a reminder for a closed issue.: https://github.com/payloadcms/payload/issues/2815. More than one of us are reporting this but we got no replies. I guess the reason is the ticket is closed.

### Describe the Bug

https://github.com/payloadcms/payload/issues/2815

### Payload Version

1.10.2

**Comment by jacobsfletch** [comment]
Hey @Stupidism this should be fixed with [1.11.0](https://github.com/payloadcms/payload/releases/tag/v1.11.0), can you give this a shot and let me know how it goes?
