### ISSUE TITLE
breaking change or bug? tags type changed in graphql, hasMany relationship field

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#2946]
### Link to reproduction

Not for now

### To Reproduce

Open graphql-playground 

Write a query like this:

```
query articleCardList(
    $tags: [String]
  ) {
    articles: Articles(
      where: {
        tags: { in: $tags }
      }
    ) {
      docs {
        id
      }
    }
  }
```

<img width="830" alt="image" src="https://github.com/payloadcms/payload/assets/5801015/02d1f8aa-e140-4285-a5cf-71b7e2ba165e">

<img width="901" alt="image" src="https://github.com/payloadcms/payload/assets/5801015/57a35c41-f493-483d-bdb7-6461d3f8588d">

### Describe the Bug

Not sure if this is a breaking change or bug?

### Payload Version

1.10.4

**Comment by JarrodMFlesch** [comment]
Hey @Stupidism was definitely a bug. I opened a PR to fix it immediately after it was reported. Apparently I never got around to merging it in, just did! Thanks for bringing it to my attention 👍
