### ISSUE TITLE
GraphQL number type fields now come through as Int instead of Float

### ISSUE THREAD

**Issue by edtorba** [payloadcms/payload#2953]
### Link to reproduction

https://github.com/edtorba/payload/commit/06d24e2c88713efbe164b0284be11597e9a0411e

### To Reproduce

Add numeric field to your collection. e.g.
```js
{
  name: 'foo',
  type: 'number',
  required: true,
  min: 1,
  max: 5000,
  defaultValue: 1,
},
```
Write GraphQL query with parameters
```gql
query Posts(
  $foo: Float
) {
  posts: Posts(
    where:{
      foo: { equals: $foo }
    }
  ) {
    page
    hasNextPage
    nextPage
    hasPrevPage
    prevPage
    totalDocs
    docs {
      id
    }
  }
}
```

Following error is then thrown:
```
"message": "Variable \"$foo\" of type \"Float\" used in position expecting type \"Int\".",
```

### Describe the Bug

Type changed from Float to Int, no idea if that was an intentional change or accidental.

### Payload Version

1.10.5

**Comment by JarrodMFlesch** [comment]
That certainly is odd, we can fix this on Monday. Along with writing some tests to prevent things like this going forward, as you suggested in the other issue!

**Comment by edtorba** [comment]
Just for the record - no new tests were added as part of the merged PR 👀

**Comment by AlessioGr** [comment]
> Just for the record - no new tests were added as part of the merged PR 👀

We have the tests on our radar, don't worry! The initial PR came without tests, as fixing the issue itself as fast as possible had the highest priority
