### ISSUE TITLE
The function condition parameter in admin changes unexpectedly

### ISSUE THREAD

**Issue by zhounewz** [payloadcms/payload#2960]
### Link to reproduction

https://payloadcms.com/

### To Reproduce

The hierarchical relationship is as follows: 

root 
- layout
  - blocks
  - styleCustomized
  - responsive
  - ...
- seo
- name
- ...

<img width="927" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/5be4226e-e28c-4668-b6c1-1de0044a5dbf">

**In the output log, the first entry is correct; the rest are root data, which is not expected.**
<img width="1452" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/37e7adb6-5ef8-47f1-8d7c-8b6cce9806d8">

### Describe the Bug

The siblingData in the condition function parameter accidentally becomes the root data, which is a bug

### Payload Version

1.9.5

**Comment by DanRibbens** [comment]
Thank you for reporting @zhounewz. 

Can you see if this is still reproducable on the latest version of Payload? 

We made changes to conditionals in both v1.10.0 and 1.10.1.

**Comment by zhounewz** [comment]
Thank you for your prompt answer. @DanRibbens 
Tried version 1.10.5, problem persists.

**Comment by PatrikKozak** [comment]
Hey @zhounewz - I went ahead and tried to reproduce this based on your images and matching up the fields as closely to yours as possible and I was unable to reproduce. `SiblingData` is always returning the expected data for me.

Can you create a reproducible repo that I can clone down and test? Thank you!
