### ISSUE TITLE
Apparent Bug: Document Title defaults to "Dashboard" for custom components

### ISSUE THREAD

**Issue by DanRibbens** [payloadcms/payload#2961]
### Discussed in https://github.com/payloadcms/payload/discussions/2926

<div type='discussions-op-text'>

<sup>Originally posted by **wrobson-lllow** June 28, 2023</sup>
I have several globals that have custom react components as the view. There seems to be a bug that doesn't pick up the "slug" of "label" to use as the document title when using a custom component. Instead of "collection name" appearing as the title, it defaults to "Dashboard". I attempted to set "document.title"  as the "slug" within the custom react component, however, upon load the correct title will appear before it is shortly overridden and replaced by "Dashboard."

![image](https://github.com/payloadcms/payload/assets/132296416/cfbb675c-db7f-4c49-89ad-452e3f2e86ac)
</div>

Thanks for reporting @wrobson-lllow! Are you able to link us to a reproduction to help us resolve this issue faster?

**Comment by JessChowdhury** [comment]
Hi @wrobson-lllow, I tried to replicate your issue by making a basic global with a custom component:

```ts
const CustomGlobal: React.FC = ({ global }) => {
  const { slug, label } = global;
  return (
    <React.Fragment>
      <h1>
        {slug || label.en}
      </h1>
    </React.Fragment>
  );
};

export default CustomGlobal;
```

This worked and allowed me to access the global slug and label(s).  Can you show us your `CustomComponent` from the screenshot above?

**Comment by wrobson-lllow** [comment]
@JessChowdhury accessing "slug" || "label" via "global" allows me to use them as an <h1> however it still has no effect on the document.title (i.e. the title that appears in the browser tab)  it is still appearing as "Dashboard." 

![image](https://github.com/payloadcms/payload/assets/132296416/12a64b9b-f293-4249-9bf7-0210de099749)


Also are there any plans for updating/improving documentation? I've been working with Payload on an almost daily basis for a little over 2 months now, and overall I'm a fan. However, the documentation seems to be lacking, especially when it comes to custom components and custom css. The only in-depth example is the "custom color picker" whose use case seems rather limited to me. Also I would have saved a great deal of time these last few months if more in-depth descriptions and syntax examples were given for just about everything. For example the section on "Local-API" does not have a single example response.
As of right now, the only thing that would keep me from recommending or choosing Payload for a future project is the documentation.

**Comment by JessChowdhury** [comment]
@wrobson-lllow yep now I see what you're trying to do - the text you're referring to is a **meta title**, you can overwrite this by setting your own. For simplicity, you can reuse the existing `Meta` Payload component. Take a look at [this example](https://github.com/payloadcms/payload/blob/master/test/admin/components/views/CustomDefault/index.tsx) for how to implement it.

Regarding documentation improvements, short answer is absolutely yes! We are actively working on and keen to improve the existing documentation. For example, we recently overhauled the [REST API](https://payloadcms.com/docs/rest-api/overview) docs to include full sample requests and responses - this improvement is on our radar for the Local API docs  too 👀  We prioritize our documentation improvements based on community input, so please do share anything you would like to see added by opening a [feature request](https://github.com/payloadcms/payload/discussions/categories/feature-requests-ideas) with the `documentation` tag.

One last note, have you joined us on [Discord](https://discord.com/invite/r6sCXqVk3v)? Our lovely community and team is always around to help if you have questions or need examples.
