### ISSUE TITLE
Possible Globals AfterChangeHook parameter mismatch when seeding with Local API

### ISSUE THREAD

**Issue by anthonyivol** [payloadcms/payload#2964]
### Link to reproduction

https://github.com/anthonyivol/payload-cms-issue-report

### To Reproduce

- Clone the repo
- pnpm install
- pnpm seed

### Describe the Bug

I am trying to seed the database by creating a page (that will be my homePage) and update a Global that save the homePage id in a RelationField.

There is an AfterChangeHook on the Global that set the CheckboxField of the selected Page to true. So whenever I want I can change the homePage and that way I can fetch my home like this : 

`fetch( env.PUBLIC_SERVER_URL + '/api/pages?where[isHome][equals]=true' ).then( ... )`

The Global hook :
```
import type { AfterChangeHook } from 'payload/dist/globals/config/types'

const setHomePageField:AfterChangeHook = async ({ doc, req: { payload } }) => {
    
    const homePageID = doc.homePage
    
    console.log(`##########################################`)
    console.log(homePageID)
    console.log(`##########################################`)
    
    await payload.update({
        collection : 'pages',
        where: { homePage: { equals: true } },
        data: { homePage: false }
    })

    await payload.update({
        collection: 'pages',
        id : homePageID,
        data : {
            homePage : true
        }
    })
    
}

export default setHomePageField
```

When using the admin panel there is no problem the hook is called and all the fields are updated :
`console.log(homePageID)` return the id :

<img width="302" alt="image" src="https://github.com/payloadcms/payload/assets/19983700/8b31c78b-dd9e-46ea-9c22-6272af8ec28a">

But using the local API by running pnpm seed, it seems that the hook get as parameter the Page object and not the ID,
`console.log(homePageID)` return :

<img width="307" alt="image" src="https://github.com/payloadcms/payload/assets/19983700/ef805cfb-2845-4671-bfdd-d9cb4ee05efb">

And I get a mongodb error :
<img width="1223" alt="image" src="https://github.com/payloadcms/payload/assets/19983700/f650556a-60e8-44d2-8059-e728aa7f977c">

Here is the seeding code :
```
  const homeJSON = JSON.parse(
    JSON.stringify(home),
  )
  
  const homePage = await payload.create({
    collection: 'pages',
    data: homeJSON,
  })
  
  await payload.updateGlobal({
    slug: 'settings',
    data: {
      homePage: homePage.id,
    },
  })
```

I actually can check if `doc.homePage` is an object or a string in the hook, but It is odd to get sometimes the full object and sometimes only the ID.

### Payload Version

1.10.5 (get the problem with 1.9.1 also)

**Comment by tylandavis** [comment]
Hi @anthonyivol, I took a look at your issue and have some info for you.

This is due to how relationships are handled depending on depth and access. With the local API, you will always have access to the full document in a relationship, which is why `console.log(homePageID)` returns the document object instead of just a string.

While technically you could specify `defaultDepth=0` on your Payload config to have the local API return just the `id` of a relationship, a better way to handle this would be to add a type check:

```js
let homePageID = doc.homePage

if (typeof homePageID !== 'string') {
  homePageID = homePageID.id
}
```

This would ensure you always get the ID of the document.

**Comment by anthonyivol** [comment]
Thanks for your answer.
I assumed after a while that there was something about a relationship depth and/or the API used.
I finally added a condition like this.
