### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.  Check the render method of `BlocksField`.

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#2965]
### Link to reproduction

Not for now

### To Reproduce

Not sure how to reproduce, I guess it occurs for any blocks field

### Describe the Bug

<img width="686" alt="image" src="https://github.com/payloadcms/payload/assets/5801015/4eac3714-62ef-43d1-a901-0ec9d6c455fc">

### Payload Version

1.10.5

**Comment by JarrodMFlesch** [comment]
@Stupidism I was able to recreate this when using initialData, is that true for you as well? I am unable to reproduce it when just using blocks/array rows.
