### ISSUE TITLE
Relationship type is not populated if it is inside a localised array with ?locale=all

### ISSUE THREAD

**Issue by horsehcj** [payloadcms/payload#2980]
### Link to reproduction

https://p01--demo--qx6bfsv879s8.code.run/api/examples/64a7927d09f1787bbf64b90c?locale=all

### To Reproduce

https://p01--demo--qx6bfsv879s8.code.run/api/examples/64a7927d09f1787bbf64b90c?locale=zh-tw

The city field is being populated

https://p01--demo--qx6bfsv879s8.code.run/api/examples/64a7927d09f1787bbf64b90c?locale=all

The city field is not being populated

### Describe the Bug

```
fields: [
  ...,
  {
      name: "arrayField",
      label: "Array Field",
      type: "array",
      localized: true,
      fields: [
        {
          type: "relationship",
          name: "city",
          label: "City",
          relationTo: "cities",
        },
      ],
    }
]
```

If a localized array field contains a relationship type field in the array item, the REST API will not return populated city data if ?locale=all

### Payload Version

1.11.0

**Comment by JessChowdhury** [comment]
Hi @horsehcj, thank you for including a reproduction 🙏 

> the REST API will not return populated city data if ?locale=all

I am not seeing this behavior. Here is what I get from the REST API using `?locale=all`:

<img width="773" alt="Screenshot 2023-07-10 at 10 05 13 AM" src="https://github.com/payloadcms/payload/assets/67977755/b7ca2386-6a82-480a-b238-a65ff16fdbec">


Can you show me what you are getting or what you mean by '_The city field is not being populated_'?

**Comment by horsehcj** [comment]
hi @JessChowdhury , thank you for your reply

In the first API call with ?locale=zh-tw
![Screenshot 2023-07-10 at 5 22 04 PM](https://github.com/payloadcms/payload/assets/2873831/a85b0e2f-716c-4665-8216-1b0c956630cf)
You can see the city is being populated

But with ?locale=all, like what it is shown in your screenshot, the city key only contains the id

**Comment by jmikrut** [comment]
Hey @horsehcj — thank you for the report! This is now fixed and will be released shortly.

We appreciate it!
