### ISSUE TITLE
RichText link customization not working properly on first initialization

### ISSUE THREAD

**Issue by MarvinVrdoljak** [payloadcms/payload#2985]
### Link to reproduction

-

### To Reproduce

```Javascript
import {Field, GlobalConfig, TextField} from 'payload/types'

export const GlobalTest: GlobalConfig = {
  slug: 'test',
  label: 'Test',
  fields: [
    {
      name: 'content',
      type: 'richText',
      admin: {
        link: {
          fields: ({defaultFields}) => {
            // Customize Url Field
            const urlFieldIndex = defaultFields.findIndex(
              (field: Field) => (field as TextField).name == 'url'
            )
            ;(defaultFields[urlFieldIndex] as TextField).validate = (val, options) => {
              const valid =
                /^(http|https):\/\/[^ "]+$/.test(val) ||
                /^(mailto):[^ "]+$/.test(val) ||
                /^(tel):[^ "]+$/.test(val)
              if (valid) return true
              return 'Invalid Url'
            }
            ;(defaultFields[urlFieldIndex] as TextField).admin = {
              ...(defaultFields[urlFieldIndex] as TextField).admin,
              placeholder: 'https://',
            }

            return [...defaultFields]
          },
        },
      },
    },
  ],
}
```

### Describe the Bug

I have extended the RichText link field so that I can validate external urls. The url must now start with "https://", "mailto:" or "tel:".
In my example I have inserted a new global showing my extension.
However, this validation does not work when I create a new link, but only when I edit an existing link. See video below. You can also avoid the error by first clicking on "Inernal Link" and then switching back to "Custom URL".

https://github.com/payloadcms/payload/assets/25500828/bc71b57d-ef85-4441-8e7d-4470ea99f445

### Payload Version

1.11.0

**Comment by JarrodMFlesch** [comment]
Thanks for reporting @MarvinVrdoljak. I just merged a fix that will be available in the next release - likely today.
