### ISSUE TITLE
templates/ecommerce doesn't show anything on localhost:3000

### ISSUE THREAD

**Issue by Snailedlt** [payloadcms/payload#3033]
### Link to reproduction

https://github.com/Snailedlt/payload-ecommerce-template/tree/2ead46073d0cc40cfdec03a7274c6046d89715ab/src

### To Reproduce

1. Clone the repo linked above
2. Create a local mongoDB database called `payload-ecommerce-template-db` and with the collection `payload-ecommerce-template-collection`
3. copy `.env.example` into `.env`
4. Replace MONGODB_URI with `MONGODB_URI=mongodb://127.0.0.1/payload-ecommerce-template-db`
5. Run `yarn && yarn dev`

### Describe the Bug

Localhost:3000 is not operational after running the code from https://github.com/payloadcms/payload/tree/master/templates/ecommerce.

![image](https://github.com/payloadcms/payload/assets/43886029/e44ee552-5c01-455b-bc80-eb1c0456952f)
![image](https://github.com/payloadcms/payload/assets/43886029/c470b118-656e-4c24-b140-f084d05af383)
![image](https://github.com/payloadcms/payload/assets/43886029/b789efe9-a8fd-4530-92e2-830731e79967)

Full payload version info:
```sh
> yarn list --pattern payload
yarn list v1.22.11
├─ @payloadcms/eslint-config@0.0.1
├─ @payloadcms/plugin-cloud@2.1.0
├─ @payloadcms/plugin-nested-docs@1.0.5
├─ @payloadcms/plugin-seo@1.0.13
├─ @payloadcms/plugin-stripe@0.0.13
├─ payload-admin-bar@1.0.6
└─ payload@1.10.2
```

### Payload Version

1.10.2

**Comment by jacobsfletch** [comment]
@Snailedlt looks like the .env.example in that template was incorrect. I fixed that just now so give it another shot! Also, there is a _big_ PR about to merge soon which overhauls the front-end of this template: https://github.com/payloadcms/payload/pull/2991

**Comment by Snailedlt** [comment]
@jacobsfletch That fixed it, thanks!
Would love to see an example in a turborepo as well. That way it's easier to see which dependencies are needed for the frontend and which are needed for the backend.
