### ISSUE TITLE
Possible Regression of #2257 useAsTitle and defaultColumns not showing in list view

### ISSUE THREAD

**Issue by absolutegravitas** [payloadcms/payload#3043]
### Link to reproduction

See https://github.com/payloadcms/payload/issues/2257

### To Reproduce

See instructions on https://github.com/payloadcms/payload/issues/2257

### Describe the Bug

Same bug as cross-referenced item. Fix appears to have regressed.

fields referenced in admin.defaultColumns that are nested inside a group , tab or row do not appear on list view / are not selectable in list view. payload ecommerce repo used.

**works**
![image](https://github.com/payloadcms/payload/assets/124488796/63102801-33de-463f-94ac-124abf9c15ba)

**does not work**
![image](https://github.com/payloadcms/payload/assets/124488796/47bc6182-10a8-4278-9c2e-a23ea9960ce4)

### Payload Version

1.11.3

**Comment by JessChowdhury** [comment]
Hi @absolutegravitas, I have been unable to replicate this so far - here is what I am getting for `defaultColumns` using a group / row / tab field in `1.11.3`:
<img width="1300" alt="Screenshot 2023-07-24 at 10 44 57 AM" src="https://github.com/payloadcms/payload/assets/67977755/31b1e3c8-c16c-403e-aabc-e518097ad95a">

Can you send a screenshot of what the _**not working**_ collection that you shared looks like when you pull up the collection view?

**Comment by jmikrut** [comment]
Hey @absolutegravitas — actually it was never possible to show columns for fields nested within groups, and we have a roadmap item to enable this:

https://github.com/payloadcms/payload/discussions/1617

We do plan on adding it as a feature, though. 

For now, let's defer conversation to the above Discussion - and we will get this implemented!
