### ISSUE TITLE
Internal server error when filtering array field using REST

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#3056]
### Link to reproduction

https://discord.com/channels/967097582721572934/1126111493570691135/1132995258494496868

### To Reproduce

1. Create Array field with subfield `tag`
2. Request `GET /api/products?where[tags][contains][tag]=electronics`

Actual: `{"errors":[{"message":"$regex has to be a string"}]}`
Expected: filtered result: `[]`

AI thinks this should work ^^ https://discord.com/channels/967097582721572934/1126111493570691135/1132995258494496868

### Describe the Bug

The contains query only supports strings and does not properly validate input.

It should either support objects or result in status code 400.

### Payload Version

1.7 - 1.11.3

**Comment by JessChowdhury** [comment]
Hi @thgh - you can filter results based on an array field by using dot notation. For example, the query you shared would work like this: `/api/products?where[tags.tag][contains]=electronics`

The AI assistant gathers intel from the Payload docs and unfortunately some areas that are not extensively documented can be inaccurate. We briefly cover querying nested properties with the REST API [here](https://payloadcms.com/docs/queries/overview#nested-properties), however it probably wasn't explicit enough for the AI 🤖
