### ISSUE TITLE
Relational field inside of collection, when queried, crashes UI if related collection has many characters

### ISSUE THREAD

**Issue by eddDev1** [payloadcms/payload#3079]
### Link to reproduction

https://www.youtube.com/watch?v=DPB1PQ2sL3E

### To Reproduce

1. Create two collections - First with a text field. Second with a relational text field (such as localization).
2. Make sure that the second collection (relational field such as localization) is related to the first text field.
3. Create around 10-20 collection entries for localization or any other relational collection.
4. When adding these collections, try to add lorem ipsum with character lengths of around 3500 per.
5. Create a new collection entry for the First collection that was created. 
6. Inside of the input field, start typing a related collection field name (in this example we will use a name from the localization collection).
7. Observe how after about entering 4 characters, the UI will freeze and the user is unable to click on anything.
8. User is forced to manually refresh the page.

### Describe the Bug

When querying a search term inside of a relational field when creating or editing a collection, the UI is unable to retrieve data and freezes the user out from being able to click on anything on the client.

Tested on versions:
1.10.0
1.11.5

References:
https://discord.com/channels/967097582721572934/1118385770147893248
https://discord.com/channels/967097582721572934/1129105246073929889

### Payload Version

1.11.5

**Comment by DanRibbens** [comment]
Hi @eddDev1,

I've narrowed this issue down to the way in which we handle filtering on the frontend. We have a regex that handles word boundaries and cyrillic characters which is very expensive to run on larger patterns.

The strange thing is that this function execution does not seem to scale linearly with the length of the label like I would expect.

I've made a code sandbox of JUST the function we use for this operation here:

https://codesandbox.io/s/thirsty-keller-jgdql3?file=/src/main.js

I attempted to improve the execution time by splitting the label being searched into smaller chunks. It did perform faster, but I ran into issues where the results weren't as accurate specifically. There may be other ways to optimize this further.

**Comment by DanRibbens** [comment]
I was able to split the string up differently and this seems to have fixed the perf problem and still work as expected in my testing.

**Comment by eddDev1** [comment]
> I was able to split the string up differently and this seems to have fixed the perf problem and still work as expected in my testing.

Hey Dan! Thank you so much for looking into this! Per your latest comment, does this mean you have found a workable solution?
