### ISSUE TITLE
Access - Nested Collection Queries with IDs

### ISSUE THREAD

**Issue by rugulous** [payloadcms/payload#3091]
### Link to reproduction

https://github.com/rugulous/payload-bug

### To Reproduce

Attempt to access the `Posts` collection from the admin panel, which uses a custom, nested `access` query:
```
access: {
    read: ({ req }) => {
	return {
		"associatedMedia.createdBy.id": {
			equals: req.user.id
		}
	}
}
```
You will get a 400 request and a console error

### Describe the Bug

I'll be honest, I'm not 100% sure if it's a "me" issue or a `payload` issue - however, I haven't been able to find anything in the docs to help with what I am trying to do!

Following the steps above gives you a `400 (Bad Request)`, citing the following issue
![image](https://github.com/payloadcms/payload/assets/13632306/ab7b55a3-b546-433b-a406-19afafc897e3)

It appeared to me that I needed to add the `id` property to my `User` collection, however this yielded a new `UnauthorizedError`
![image](https://github.com/payloadcms/payload/assets/13632306/5717780a-7b84-410e-84ed-e46740ce4974)

On my actual project it prevented me from logging in, giving me this error
![image](https://github.com/payloadcms/payload/assets/13632306/e50a3783-6b6e-4fd8-b9f1-4a61c84bf776)

I think it is an issue to do with not fully detecting the auto-generated fields in `src/mongoose/buildQuery.ts`, [on line 500](https://github.com/payloadcms/payload/blob/master/src/mongoose/buildQuery.ts#L500). 

Without a full understanding of the project, I have been able to manually edit my local package to the following to get it to work:

```
let matchedField = lastIncompletePath.fields.find((field) =>fieldAffectsData(field) && field.name === segment);

if(!matchedField && segment === "id"){
    matchedField = {
	name: 'id',
	type: 'text'
    };
}
```

...however, looking further into it, it looks like the actual issue is coming from [line 570](https://github.com/payloadcms/payload/blob/master/src/mongoose/buildQuery.ts#L570), where we are loading the `relatedCollection` directly by its config. I am assuming that this just picks up exactly what I've declared in my model and so the auto-generated fields like `id` are not picked up here

### Payload Version

1.11.6

**Comment by DanRibbens** [comment]
@rugulous, I don't think this is a bug. 

You have a `hasMany` on the relationship field, was that intentional? Since the relationship is an array, `equals` will not match the `id`.

Either remove `hasMany` or to keep `hasMany` you will want to use `in: [req.user.id]` in your `where` query.

Does this help?

**Comment by rugulous** [comment]
@DanRibbens thanks for getting back to me so quickly :)

I updated the access in my reproduction as you suggested to
```
access: {
	read: ({ req }) => {
	  return {
		"associatedMedia.createdBy.id": {
			in: [req.user.id]
		}
	}
}
```

... however I still got the same error

![image](https://github.com/payloadcms/payload/assets/13632306/8c390202-a558-4831-be28-badebdfda14f)

Admittedly the `hasMany` doesn't make much sense in the context of the demo, but for the way I am using it in my production app it follows the same semantics. However, for the avoidance of doubt I removed the `hasMany` too and am still getting the same error

**Comment by rugulous** [comment]
I've found another way I can get it to work (although it still isn't pretty so I'm not convinced it's not a me issue)

I've added the `id` to the collection config so that satisfies the query builder (when it loads `relatedCollection` the `config` now contains an `id` field).

In order to get this to work, I had to comment out the [code dealing with ID fields in `buildSchema` ](https://github.com/payloadcms/payload/blob/master/src/mongoose/buildSchema.ts#L90C2-L98C4) (I noticed `allowIDField` was always `undefined` so it was always falling into this branch, perhaps setting that to `true` may be a nicer approach)

**Comment by DanRibbens** [comment]
Hey @rugulous,

I don't know how I missed this earlier. Your access query is the problem and it is very easy to fix. All you need is to remove your the `.id` from your access control. It should be: 

```
access: {
    read: ({ req }) => {
	return {
		"associatedMedia.createdBy": {
			equals: req.user.id
		}
	}
}
```

The reason is because when you use the dot notation it is looking to related documents field and that was where you ran into your problem. By removing the `.id` your query only uses the associatedMedia collection, of which the `createdBy` field is storing the `id`.

Let me know if you have any other issues with this.
