### ISSUE TITLE
if Provided staticURL and serverURL is different url for thumbnail in media 

### ISSUE THREAD

**Issue by chz** [payloadcms/payload#3097]
### Link to reproduction

.

### To Reproduce

If Provided staticURL and serverURL is different url for thumbnail in media 

staticURL: 'https://cms.chz.dev/media'

serverURL: 'http://localhost:3001'

Thumbnail url is: 'http://localhost:3001https://cms.chz.dev/media' but must be 'https://cms.chz.dev/media'

### Describe the Bug

If Provided staticURL and serverURL is different url for thumbnail in media 

staticURL: 'https://cms.chz.dev/media'

serverURL: 'http://localhost:3001'

Thumbnail url is: 'http://localhost:3001https://cms.chz.dev/media' but must be 'https://cms.chz.dev/media'

screenshot:
![Screenshot 2023-07-30 at 00 45 55](https://github.com/payloadcms/payload/assets/3233370/386d1867-6ec0-49ae-b01f-3f40a6de0f39)

### Payload Version

1.11.7

**Comment by JessChowdhury** [comment]
Hi @chz - what does your media collection config look like?

We typically import `path` and set the `staticDir` relatively like this:

```
import path from 'path';

export const MediaCollection: CollectionConfig = {
  slug: 'media',
  upload: {
    staticDir: path.resolve(__dirname, '../../media'),
  },
};
```
That way it will append your current server URL so when you are working locally, your admin thumbnail would be `http://localhost:3001/media`, and when you're running in production you should see the live URL `https://cms.chz.dev/media`.

Let me know if this works for you!

**Comment by JessChowdhury** [comment]
@chz to replicate using Payload version `1.11.7`, I've added a serverURL to my payload.config:

```ts
serverURL: 'http://localhost:3000',
```

And defined the staticURL in my uploads collection:

```ts
upload: {
  staticURL: 'https://cms.chz.dev/media',
},
```

Then I uploaded a test image and checked the src:

<img width="1576" alt="Screenshot 2023-07-31 at 3 30 59 PM" src="https://github.com/payloadcms/payload/assets/67977755/e97bcac6-874d-4cb5-a21f-18c46926f42f">

As you can see, the src here is correct.

Could you create a minimal production of your issue using `npx create-payload-app` or by forking the Payload repo and updating the `_community` test suite?

We'd like to get to the bottom of this today!

**Comment by chz** [comment]
Can you produce not upload: { } but only via .env? here is my config: 
```

export default buildConfig({
  serverURL: process.env.PAYLOAD_PUBLIC_SERVER_URL,
  cors: clientURLS,
  csrf: clientURLS,
  defaultDepth: 1,
  maxDepth: 5,
  admin: {
    user: Users.slug,
  },
  globals: [
    Home
  ],
  collections: [
    Users,
    Blogs,
    Media
  ],
  typescript: {
    outputFile: path.resolve(__dirname, 'payload-types.ts'),
  },
  graphQL: {
    schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
  },
})
```

Env file: 
```
PORT=3001
PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3001
PAYLOAD_PUBLIC_STATIC_URL=https://cms.chz.dev/media
```

And also define port as 3001

**Comment by JessChowdhury** [comment]
Thank you @chz I am able to reproduce this now - looking into it 🔎
