### ISSUE TITLE
Filter checkbox fields

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#3138]
### Link to reproduction

demo.payloadcms.com -> Categories

### To Reproduce

- Open list view
- Filter by checkbox field

### Describe the Bug

When attempting to filter checkbox fields in the list view, you have to type "true" or "false". We should provide a dropdown or radio button for this type of field.

![CleanShot 2023-08-07 at 16 31 56](https://github.com/payloadcms/payload/assets/65888/1aad6e96-7ef9-4ebc-ba42-790eded8a21c)

### Payload Version

latest

**Comment by JarrodMFlesch** [comment]
Fixed with https://github.com/payloadcms/payload/issues/3114
