### ISSUE TITLE
Array in Tab is not working if tab-names are defined

### ISSUE THREAD

**Issue by MarvinVrdoljak** [payloadcms/payload#3156]
### To Reproduce

```js
import {CollectionConfig} from 'payload/types'

export const CollectionTest: CollectionConfig = {
  slug: 'test',
  fields: [
    {
      type: 'tabs',
      tabs: [
        {
          name: 'tabOne',  // <-- if you remove this line, it would work
          label: {de: 'Tab Eins Label', en: 'Tab One Label'},
          fields: [
            {
              name: 'text',
              type: 'text',
              required: true,
            },
          ],
        },
        {
          name: 'tabTwo', 
          label: {de: 'Tab Zwei Label', en: 'Tab Two Label'},
          fields: [
            {
              name: 'array',
              type: 'array',
              fields: [
                {
                  name: 'text',
                  type: 'text',
                  required: true,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}
```

### Describe the Bug

I have created a tab-navigation with two tabs, in my second one is an array. Since I want to group the fields within each tab I added a name for both of them. As soon as I add a name to my first one, the array in the second one is not working anymore. I can't add any new items. See video below, clicking on "Add Array" is not doing anything before I comment out the name of the first tab:

https://github.com/payloadcms/payload/assets/25500828/bb3823f6-77e6-4903-bd52-d65612936b89

Note: The same issue occurs with blocks.

### Payload Version

1.13.2

**Comment by mooxl** [comment]
Our instances are experiencing the same problem.

**Comment by JarrodMFlesch** [comment]
I can look into this! Thank you both for reporting.

**Comment by JarrodMFlesch** [comment]
Hoping to get a release out today!

**Comment by mooxl** [comment]
Thanks you for the quick response:)

**Comment by JarrodMFlesch** [comment]
@MarvinVrdoljak @mooxl please update to 1.13.3!
