### ISSUE TITLE
Open-Redirection in login page

### ISSUE THREAD

**Issue by ashokasec** [payloadcms/payload#3165]
### Link to reproduction

https://payloadcms.com/login?redirect=https://google.com

### To Reproduce

Click on the link provided and login with your credentials!! then you'll be redirected to _https://google.com_

### Describe the Bug

An open redirection vulnerability exists within the "redirect" parameter. It allows the user to be sent to potentially malicious websites by manipulating the crafted login link.

### Payload Version

Latest Website

**Comment by ashokasec** [comment]
i guess its not resolved yet! right?
i tried reproducing and its doing like before.

**Comment by AlessioGr** [comment]
> i guess its not resolved yet! right? i tried reproducing and its doing like before.

Nope, it's not merged yet. Will be merged in later today!

**Comment by ashokasec** [comment]
the PR is merged but the bug still exists :)
