### ISSUE TITLE
The type of array field should be required if minRow > 0

### ISSUE THREAD

**Issue by horsehcj** [payloadcms/payload#3198]
### Link to reproduction

--

### To Reproduce

```
{
      name: "arrayField",
      type: "array",
      minRows: 1,
      maxRows: 10,
      fields: [
        {
          name: "title",
          type: "text",
        }
      ]
}
```

### Describe the Bug

When I generate the type using https://payloadcms.com/docs/typescript/generating-types

I'm expecting the type is
```
arrayField: {
  title: string;
}[];
```
but currently it generates
```
arrayField?: {
  title: string;
}[];
```
Because the minRow is 1, user is not able to save if they haven't inserted any row

Thank you

### Payload Version

1.13.4

**Comment by JarrodMFlesch** [comment]
Do we think this is necessary? I feel like the required property should just be set on the field.

**Comment by JessChowdhury** [comment]
This feels like an easy trip-up for people and there isn't a scenario where you would set minRows but also need the type be non-required, isn't this just the correct typing?

**Comment by JarrodMFlesch** [comment]
@DanRibbens I think it functions that way now. The user is saying that the generated types are just "incorrect" because minRows is 1. But validation does pass, I believe.

**Comment by DanRibbens** [comment]
> Do we think this is necessary? I feel like the required property should just be set on the field.

So this isn't a bug at all and you're suggesting people should add their own `required: true`, correct? I agree that this is the case.

When fields are not required, they could be `undefined` and that is separate from `minRows` which enforces validation. That is to  say, if this is array exists, it must have _n_ items. This is more control to enforce the validation and the types that are currently accurate without any changes.

**Comment by JarrodMFlesch** [comment]
> > Do we think this is necessary? I feel like the required property should just be set on the field.
> 
> So this isn't a bug at all and you're suggesting people should add their own `required: true`, correct? I agree that this is the case.
> 
> When fields are not required, they could be `undefined` and that is separate from `minRows` which enforces validation. That is to say, if this is array exists, it must have _n_ items. This is more control to enforce the validation and the types that are currently accurate without any changes.

Yes, I am suggesting that they just use the required flag on the field config.

**Comment by JessChowdhury** [comment]
@horsehcj so we've established that this is intended behavior for your array type to be non-required regardless of `minRow`, and you should add the `required: true` flag if you want the types to show required. Dan's explanation above should clarify the distinction between these properties. If you have anymore questions, feel free to reach back out!
