### ISSUE TITLE
totalDocs & totalPages do not change based on filter

### ISSUE THREAD

**Issue by alexbechmann** [payloadcms/payload#323]
# Bug Report

If you have a filter in your GraphQL query, the totalDocs and totalPages don't match the total for that query.

```graphql
articles(where: { title: { equals: "non-existant-title" } }) {
    totalDocs
    totalPages
    docs {
      id
      title
    }
  }
```

results in:

```json
"articles": {
    "totalDocs": 3,
    "totalPages": 1,
    "docs": []    
}
```

## Expected Behavior

totalCount & totalPages should be the total based on current query.

## Current Behavior

totalCount & totalPages is for all docs.

## Possible Solution

Include requested query parameters in the count query to mongodb.

## Steps to Reproduce
1. Create article type with title field
2. Create some articles
3. Execute a query with a filter 
4. Notice that the counts returned do not match what you would expect.

## Detailed Description

payload version: 0.10.0

**Comment by jeanbmar** [comment]
This is breaking stuff for us too .e.g:
https://github.com/jeanbmar/payload-hash-upload/blob/d305378e0f0b8c9e399cb1a44cb2adc0c22b31b4/lib/file-exists.js#L1-L9)

**Comment by jeanbmar** [comment]
I've just checked and the problem comes from this change:
https://github.com/payloadcms/payload/commit/30f17509ea9927d923ffd42c703adefc902b66ea#diff-800414a60f0fb0fa2abd83dca912237d1cf87877818a7901c345d30d497bf840

Removing `useEstimatedCount` fixes the issue

**Comment by DanRibbens** [comment]
Thanks everyone! The fix will be released either today or tomorrow.

**Comment by DanRibbens** [comment]
https://github.com/payloadcms/payload/releases/tag/v0.10.5 Released. Let us know if you experience further issues.
