### ISSUE TITLE
collection.upload.staticURL is optional but is actually required

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#3237]
### Link to reproduction

https://github.com/payloadcms/payload/commit/cf8b836f72011a80f92eabedb49a35d970652974

### To Reproduce

1. `payload.init({ serverUrl: undefined })`
2. Create collection "test" without upload.staticURL
3. Add a document
4. Query the collection and notice the url property

Option 1: 
Expected: `url: "/test/example.png"`
Actual: `url: "undefined/test/example.png"`

Option 2: 
Expected: invalid payload config, staticURL was empty
Actual: valid payload config, image urls are broken

### Describe the Bug

This worked upto 1.13, it broke it 1.14.0

Ideally it should use the server origin + collection slug (as it did before?)

### Payload Version

1.14 - 1.15.2

**Comment by JessChowdhury** [comment]
Hey @thgh - I'm not able to replicate the issue you described, I just tried with Payload `v1.15.2` and am seeing the correct media url even though `staticURL` is undefined. If you could add a reproduction repo that would be super helpful!

**Comment by thgh** [comment]
Hi, the actual issue is that collection sanition happens before server url sanition. The issue appears only when server url is undefined. I updated the repro steps and added a testcase over here: https://github.com/payloadcms/payload/pull/3238/commits/bf19afa7d2f8399f021a9410eb62bcc9af9c87d5

**Comment by thgh** [comment]
Oh, it's more specific: serverUrl must be actually set to `undefined`

**Comment by thgh** [comment]
PR updated with two commits: first a failing testcase, then a fix.

**Comment by PatrikKozak** [comment]
Hey @thgh - we appreciate the time you put into finding this issue and adding a PR. Prior to reviewing your [PR](https://github.com/payloadcms/payload/pull/3238), I was unable to reproduce the issue with your reproduction steps.

Having `serverURL` set to undefined and providing no `staticURL` for uploads in a collection still output the expected `url`.

Could you please provide a reproduction repo that I could pull down that way my configuration is matching yours? Thank you!

**Comment by thgh** [comment]
OK, here it is: https://github.com/thgh/payload/tree/fix/3237-server-url
Run `yarn test:int -t uploads` and it will succeed, revert the sanitize fix to trigger the bug

Or check out this [action](https://github.com/payloadcms/payload/actions/runs/5998851506/job/16267864144) (see log below)

[(here are some notes on the root cause)](https://github.com/payloadcms/payload/pull/3239#issuecomment-1695816583)

```
Summary of all failing tests
FAIL test/uploads/int.spec.ts (14.899 s)
  ● Collections - Uploads › REST › create › creates from form data given a png

    expect(received).not.toContain(expected) // indexOf

    Expected substring: not "undefined"
    Received string:        "undefined/media/image-1.png"

      58 |         expect(sizes).toHaveProperty('mobile');
      59 |         expect(sizes).toHaveProperty('icon');
    > 60 |         expect(doc.url).not.toContain('undefined');
         |                             ^
      61 |       });
      62 |
      63 |       it('creates from form data given an svg', async () => {

      at Object.toContain (test/uploads/int.spec.ts:60:29)


Test Suites: 1 failed, 24 passed, 25 total
Tests:       1 failed, 1 skipped, 2 todo, 452 passed, 456 total
Snapshots:   0 total
Time:        94.596 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by thgh** [comment]
Hi, here is the command to check out the reproduction:

```
git checkout cf8b836f72011a80f92eabedb49a35d970652974
```

Is everything clear?

**Comment by JarrodMFlesch** [comment]
Confirmed bug while debugging #3275. @PatrikKozak or @JessChowdhury, make sure you are on latest when testing this.

**Comment by jmikrut** [comment]
@JessChowdhury please pick back up on this work and ensure this is resolved.

Thank you!
