### ISSUE TITLE
Localized fields are not indexed

### ISSUE THREAD

**Issue by jeanbmar** [payloadcms/payload#324]
# Bug Report

We are using Next.js [slugs](https://nextjs.org/docs/routing/dynamic-routes) in order to display our users friendly routes which don't rely on technical ids.
In order to query records in Payload using Next.js slugs, we defined a slug field in Payload collections which has to be indexed for performance reasons.
In addition, our Next.js slugs are localized, so the slug field we defined in Payload is localized as well.

What our collection fields look like:
```js
{
// ...,
fields: [
    {
      name: 'id',
      type: 'text',
    },
    {
      name: 'slug',
      type: 'text',
      localized: true,
      index: true,
    },
    //...
}
```

After checking in Mongodb, we noticed that indexes are not created when specified on localized fields.

## Expected Behavior

When an index is applied to a localized field, either one of the two following situations should happen:
  1. A single index equivalent to `collection.createIndex({ slug: 1 })` should be created.
  1. As many indexes as there are locales should be created i.e.:
    - `collection.createIndex({ 'slug.fr': 1 })`
    - `collection.createIndex({ 'slug.en': 1 })`

Solution 1 is probably the best one in the context of Payload.
In order to leverage the index, API has to query using something like: `collection.find({ slug: { $eq: { 'en': 'foo' } } })` or `collection.find({ slug: { en: 'foo' } })`. Both queries seem fine after checking Mongodb explain plan.

## Current Behavior

`src/mongoose/buildSchema` generates a schema like this:
```js
{
  _id: [Function: String],
  slug: {
    type: {
      en: {
        sparse: undefined,
        unique: false,
        required: false,
        default: undefined,
        index: true,
        type: [Function: String]
      },
      fr: {
        sparse: undefined,
        unique: false,
        required: false,
        default: undefined,
        index: true,
        type: [Function: String]
      }
    },
    localized: true
  },
}
```

## Possible Solution

Index properties should probably remain on the parent level (like the `localized` property).

## Detailed Description

Payload version: 0.10.4

**Comment by DanRibbens** [comment]
Thanks for your work documenting the issue @jeanbmar!

**Comment by DanRibbens** [comment]
https://github.com/payloadcms/payload/releases/tag/v0.10.5 Released. Let us know if you experience further issues.
