### ISSUE TITLE
`beforeOperation` `depth` changes break related fields / save

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/payload#3246]
### Link to reproduction

n/a

### To Reproduce

I've seen a variety of odd behavior so I'm not completely sure if this will be precisely reproducible, but I think you should be able to see somewhat similar behavior.

Create the Sandbox collection below, create a new record, select a related record in the relationship field, and click save multiple times, you should see some variation of this behavior:

- On the first Save click, you will get no errors, but your selected record will disappear
- Press Save again and it will save with no errors
- Press Save a third time an you will get an error like below

<img width="397" alt="image" src="https://github.com/payloadcms/payload/assets/1661046/cd4817f4-ab0b-4f93-8142-e3f6b4f22889">

```
const Sandbox = {
    slug: 'sandbox',
    fields: [
        {
            name: 'posts',
            type: 'relationship',
            relationTo: 'posts',
        },
    ],
    hooks: {
        beforeOperation: [
            ({ args, operation }) => {
                if (operation === 'update' || operation === 'create') {
                    args.depth = 2;
                }
                return args;
            },
        ],
    },
};

export default Sandbox;
```

### Describe the Bug

As described above

### Payload Version

1.14.0

**Comment by JarrodMFlesch** [comment]
@ssyberg We recently rolled out a fix for this issue but are going to be reverting it in 2.0.

The admin panel uses depth=0 when submitting data, hooks will need to account for any depth by type checking the relationship and fulfilling them if needed.

**Comment by ssyberg** [comment]
@JarrodMFlesch 
> hooks will need to account for any depth by type checking the relationship and fulfilling them if needed.

I don't have my head in this right now, but isn't that effectively what my beforeOperation is doing? Will that work now?

**Comment by JarrodMFlesch** [comment]
I could likely leave some of the PR intact that safely builds form state if relationships are resolved with depth.
