### ISSUE TITLE
Inconsistent data returned from hooks

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#3248]
### Discussed in https://github.com/payloadcms/payload/discussions/3218

<div type='discussions-op-text'>

<sup>Originally posted by **wrobson-lllow** August 23, 2023</sup>
This is something I have come across several times over the last several months, but has never been a big issue, and typically the fix is as easy as checking the type before accessing the value. However, it definitely seems off...

I have a CollectionAfterChangeHook on my "license" collection where I need to access the value for "customer" (in this case "DDD") however depending where the hook is invoked changes the format of the data. The following data is from console.logging the "doc" arg:

If the hook is invoked from a direct change on the "license" collection (i.e. a user updates a value manually) the following is passed to the hook as the "doc" argument:

```javascript
doc: {
  id: '64e66538d008409ec5830cc4',
  customer: 'DDD',
  server: 'DDD_test-server-d',
  product: 1,
  database: 'test-db',
  tier: 'A',
  options: { attachments: true, futureFeature: false },
  createdAt: '2023-08-23T19:59:52.796Z',
  updatedAt: '2023-08-23T20:05:57.808Z'
}
``` 

However, I have a CollectionAfterDeleteHook on a separate collection that updates the "options" field on the "licenses" collection. When the "licenses" CollectionAfterChangeHook is invoked via a change made by the CollectionAfterDeleteHook the following is what  is passed to the hook as the "doc" argument:

```javascript
 doc: {
  id: '64e66538d008409ec5830cc4',
  customer: {
    id: 'DDD',
    name: 'test d',
    type: 'school',
    county: {
      id: 'IN-2',
      state: 'IN',
      name: 'Allen',
      code: 2,
      timezone: 'US/Eastern'
    },
    createdAt: '2023-08-09T16:47:52.824Z',
    updatedAt: '2023-08-09T16:47:52.824Z'
  },
  server: {
    id: 'DDD_test-server-d',
    customer: 'DDD',
    machineName: 'test-server-d',
    createdAt: '2023-08-11T18:57:58.606Z',
    updatedAt: '2023-08-11T18:57:58.606Z'
  },
  product: { id: 1, name: 'Financial System' },
  database: 'test-db',
  tier: 'A',
  options: { attachments: false, futureFeature: false },
  createdAt: '2023-08-23T19:59:52.796Z',
  updatedAt: '2023-08-23T20:06:03.449Z'
}
``` </div>

**Comment by JarrodMFlesch** [comment]
We are going to revert the fix in 2.0.

The admin panel uses depth=0 when submitting data, hooks will need to account for any depth by type checking the relationship and fulfilling it if needed.
