### ISSUE TITLE
`isFieldNullable` returns `true` when `force` is set to `false` due to negation scoping

### ISSUE THREAD

**Issue by bdalenoord** [payloadcms/payload#3259]
### Link to reproduction

https://github.com/TribeAgency/payload/tree/reproduction/false-negation-of-nullability

### To Reproduce

1. Create a new collection/global with a group- or array-field
2. Mark the field as `required`
3. Add a nested required text-field in that group/array-field
4. Run the application and observe the GraphQL schema, where the nested field will have a `nullable` type even though both itself and it's parent are required.

### Describe the Bug

After digging around with breakpoints for quite some time, I do believe that the behavior I'm observing is incorrect.

Given a collection config:
```ts
export const Example: CollectionConfig = {
  slug: "examples",
  fields: [
    {
      name: "direct",
      type: "text",
      required: true,
    },
    {
      type: "group",
      name: "group",
      fields: [
        {
          name: "inAGroup",
          type: "text",
          required: true,
        },
      ],
      required: true
    },
    {
      name: "array",
      type: "array",
      fields: [
        {
          name: "nested",
          type: "text",
          required: true,
        },
      ],
      required: true,
    },
  ],
};
```
This config has:
 * a required text-field directly under the CollectionConfig. In GraphQL, this results in 
 ```graphql
type Example {
  ...
  direct: String!
  ...
}
```
* a required array and group, both with required text fields. These result in the following schema:
```graphql
type Example {
  ...
  group: Example_Group
  array: [Example_Array!]!
  ...
}

type Example_Group {
  inAGroup: String
}

type Example_Array {
  nested: String
  id: String
}
```

The nullability of the `nested` and `inAGroup`-fields are a bit unexpected: they are required and should not be nullable AFAIK. Having them nullable requires our frontend to handle multiple cases that should never occur.

---

I think I found the possible culprit in the `isFieldRequired`-function (https://github.com/payloadcms/payload/blob/master/src/graphql/schema/isFieldNullable.ts): the `force`-flag is set to `false` in the case that I described, but it's made part of a larger set of requirements here and that complete set is negated. If I move the `force`-flag out of the scoped list of other requirements, the behavior in the GraphQL schema changes.

I've pushed a second branch https://github.com/TribeAgency/payload/tree/possible-fix/false-negation-of-nullability which moves the negation out of the brackets and that results in the GraphQL schema that I expect.

With that fix, the schema changes to the following:
```graphql
type Example {
  ...
  direct: String!
  group: Example_Group
  array: [Example_Array!]!
  ...
}

type Example_Group {
  inAGroup: String!
}

type Example_Array {
  nested: String!
  id: String
}
```
where all three `String`-fields are marked non-nullable.

### Payload Version

1.15.2

---

**Sidenote**: I've had some issues getting the reproduction to start against my MongoDB, so I've had to modify the `dev.ts` config to add credentials... I could not figure out what the preferred way for that would be...

**Comment by JarrodMFlesch** [comment]
@bdalenoord I think your change makes sense! Would you be up for making a PR and tagging this issue in it?
