### ISSUE TITLE
Image in the media collection returns 'undefined' in the URL.

### ISSUE THREAD

**Issue by nodeproject** [payloadcms/payload#3275]
### Link to reproduction

N/A

### To Reproduce

1. Quickstart new project using `npx create-payload-app`
2. Select 'website - Website Template' when generating payload project
3. In your `package.json` file, ensure that the Payload version is set explicitly to "1.15.2" rather than relying on "latest." It appears that the template installation process may use the version specified in the yarn.lock file instead of the latest version.
4. Run yarn install
5. Run dev

### Describe the Bug

When uploading a new media file under 'Media,' an issue arises where the link is broken in preview mode, displaying 'undefined' in its URL. However, the image can still be accessed via http://localhost:3000/media/test.svg. The API query for media also returns 'undefined' in the 'url' field, as shown below:

API Query:
http://localhost:3000/admin/collections/media/64f740c3241f3614ad956373

Response:
```
{
  "id": "64f740c3241f3614ad956373",
  "alt": "test",
  "filename": "test.svg",
  "mimeType": "image/svg+xml",
  "filesize": 4589,
  "width": 4975,
  "height": 4975,
  "createdAt": "2023-09-05T14:52:51.116Z",
  "updatedAt": "2023-09-05T14:52:51.116Z",
  "url": "undefined/media/test.svg"
}
```
<img width="1140" alt="Screenshot 2023-09-05 at 17 56 25" src="https://github.com/payloadcms/payload/assets/10492535/67f71787-d938-48cb-9490-e0fe7409a2e2">

After downgrading Payload to version 1.14.0, everything appears to be functioning correctly.

**Here are some other steps I attempted before composing this issue:**

I deleted the `yarn.lock` file along with the `node_modules` folder and then reinstalled the packages using yarn install. However, the issue persist. My current yarn version is 1.22.19.

### Payload Version

1.15.2

**Comment by JarrodMFlesch** [comment]
@nodeproject the initial issue you brought up is being tracked [here](https://github.com/payloadcms/payload/issues/3243).

Please refrain from grouping issue together. Separating them makes it easier to track and easier for people to find if they go searching through issues.

If you could adjust the title/body of this issue, removing the first issue your pointed out that would be great! 👍

**Comment by nodeproject** [comment]
@JarrodMFlesch Done, sorry for the mix-up, will make separate issues for future references.

**Comment by JarrodMFlesch** [comment]
@nodeproject thanks!

So this issue sounds like you are missing an env var `PAYLOAD_PUBLIC_SERVER_URL`. You should add that to your env file and be all set 👍
