### ISSUE TITLE
Running `payload build` outputs different chunk names every time

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#3289]
### Link to reproduction

https://github.com/payloadcms/payload

### To Reproduce

1. Run `PAYLOAD_CONFIG_PATH=test/_community/config.ts npx ts-node src/bin/build.ts`
2. Run `PAYLOAD_CONFIG_PATH=test/_community/config.ts npx ts-node src/bin/build.ts` again
3. You'll see two different `main.*.js` and `styles.*.js` files in the `build` folder

### Describe the Bug

It's unexpected that Payload outputs differently named artifacts when the code hasn't changed.

I host Payload on AWS with Elastic Beanstalk using multiple load-balanced EC2 instances. This is a problem because whenever a new instance is launched - its build artifacts have different names compared to the other instances, leading to occasional 404s. This happens because one instance serves the admin HTML pointing to CSS/JS files with certain file names, but another instance serves the actual CSS/JS files and can't find them, because they have different names there.

I did a `git diff --word-diff` of the `main.*.js` file and here's the output:

```diff
{+t)n.o(t,r)&&!n.o(e,r)&&Object.defineProperty(e,r,{enumerable:!0,get:t[r]})},n.hu=e=>""+e+"."+n.h()+".hot-update.js",n.miniCssF=e=>"styles.48ee18ea472aef49eba9.css",n.hmrF=()=>"main."+n.h()+".hot-update.json",n.h=()=>"45abc77eaa2c6b2ed84d",n.g=function(){if("object"==typeof+}
[-t)n.o(t,r)&&!n.o(e,r)&&Object.defineProperty(e,r,{enumerable:!0,get:t[r]})},n.hu=e=>""+e+"."+n.h()+".hot-update.js",n.miniCssF=e=>"styles.48ee18ea472aef49eba9.css",n.hmrF=()=>"main."+n.h()+".hot-update.json",n.h=()=>"346700734f7770cf18e2",n.g=function(){if("object"==typeof-]
```

As you can see, there seems to be a hardcoded hash in the file contents. My guess is that this hash is time-based, leading to different content of the JS and therefore, a different chunk hash.

You can search for "`n.h=()=>`" in the `main.*.js` file to easily find the hash in question.

### Payload Version

1.15.4

**Comment by hdodov** [comment]
This might be related: https://github.com/webpack/webpack/issues/8419

**Comment by hdodov** [comment]
As a workaround, I was able to fix this with a custom build config that removes the hot reload plugin:

```ts
export default buildConfig({
	admin: {
		webpack(config) {
			config.plugins = config.plugins.filter(
				(p) => p.constructor.name !== "HotModuleReplacementPlugin"
			);
			return config;
		},
	},
});
```

**Comment by hdodov** [comment]
@JarrodMFlesch I had already made a PR here #3295. It was the exact same change you did. Was there something wrong with the PR or have you just missed it? I want to know if I did something wrong, so I can avoid it in the future.

Thank you very much anyways!

**Comment by JarrodMFlesch** [comment]
@hdodov ah sorry! I just missed it! Maybe if you tag the PR inside the original post comment it would be easier to not miss? 

Really just my fault though as I did not see the PR. Would have totally merged yours in 😢

**Comment by hdodov** [comment]
@JarrodMFlesch it's okay! I'll know better next time. Thanks again! 🙌
