### ISSUE TITLE
Using me always returns null

### ISSUE THREAD

**Issue by dylankuipers** [payloadcms/payload#3297]
### Link to reproduction

Not relevant

### To Reproduce

Use me with REST API with a set payload cookie after logging in.

### Describe the Bug

After logging a user in it sets a cookie with a token.

Later on I need to check whether a user is logged in so I use the "users/me" from REST API to get back a user.

If the user is null, I know there is no logged in user. Although it always returns null.

If I manually set a JWT Token in the localstorage it does work, but I figure that payload should automatically use it's own set token to get the logged in user.

My call: 

  const data = await fetch(`http://localhost:3000/api/users/me`)

  console.log(await data.json()) // "{user: null}"
  
  My cookie:

Name: payload-token
Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjVmdHN3aGQzdnZpdHQ4cHkxdGR5em1pbm15aGJ5c0BmdWxsZGV2Lm5sIiwiaWQiOiI2NGZhZTg5YjI4ZmI5Nzg3YjcxY2E2ZDQiLCJjb2xsZWN0aW9uIjoidXNlcnMiLCJpYXQiOjE2OTQxNjUxNDcsImV4cCI6MTY5NDE3MjM0N30.7v5tgj5wIQJPPB9ELDkk-ihxUUr4l6hkMP0Vt6xMOAM

### Payload Version

1.15.3

**Comment by dylankuipers** [comment]
@JarrodMFlesch Thanks for your reply!

I tested it both on 1.15.4 and 1.15.5 and it did not work on either of them unfortunately.

After creating an account and logging the user in it does set a cookie with a payload token. As well as when I checked my payload admin page the account I created is actually there, though when I try to use "users/me" it still returns null.

The code I used is still the same as I provided previously.

**Comment by JessChowdhury** [comment]
@dylankuipers I just spun up a blank project and am not able to reproduce the behavior you described.

In the screen recording below, you can see I haven't set any tokens manually, only the `payload-token` cookie that gets provided by Payload is present.

First, I am able to go to `/api/users/me` in the browser and see all the correct data - does this work for you?

To test with the REST API, I hit the **Fetch ME** button to make the following request: 
```const req = await fetch(`${api}/users/me`)``` - and this also returns the data correctly for me.

If you can reproduce this behavior and provide a minimal repo, that would be super helpful and we can take another look. 

For the moment, I'm marking this as `cannot-reproduce`.

https://github.com/payloadcms/payload/assets/67977755/28c96f7c-0c4e-40ef-89d4-f8047a37acb6

**Comment by JarrodMFlesch** [comment]
@dylankuipers also, are you adding the "credentials: include" to your request? https://payloadcms.com/docs/authentication/overview#http-only-cookies

**Comment by JessChowdhury** [comment]
@dylankuipers and was `PAYLOAD_PUBLIC_SERVER_URL` defined in your `.env` file? 

I just added `serverURL: process.env.PAYLOAD_PUBLIC_SERVER_URL` to the project I was testing with earlier - it still working as expected for me. Can you replicate this issue on your other projects by adding a `serverURL`? I'd like to figure out if this does in fact happen across the board or is specific to your one project.

**Comment by dylankuipers** [comment]
@JessChowdhury Thanks again for your reply,

I took my .env file and my config from a different project onto a fresh new project and found out that if I include this line: `serverURL: process.env.PAYLOAD_PUBLIC_SERVER_URL` in my config, that like you mentioned, it still works.

Although, I then started looking into my .env and when I add this line: `PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3000` into my .env file that in fact the "users/me" REST API call stops working. Could you test this in your repo?

I am still unsure how that specific line of code manages to break the "/users/me" call, but not any other call.

**Comment by JarrodMFlesch** [comment]
@dylankuipers could you provide a video of your issue? Are you attempting to fetch data from a different domain? Is that domain listed in your `cors` property on your payload config?

**Comment by dylankuipers** [comment]
@JarrodMFlesch I can try to provide a video tomorrow. And yes, it's from another domain, though I have it listed with cors in my config. If you don't have it listed you get a message saying that the request was blocked by CORS Policy. That's not the problem.

**Comment by dylankuipers** [comment]
@JessChowdhury @JarrodMFlesch Below is a video showing the issue.

First I have this line: `PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3000` in my .env file and I then test to press the "Test this" button which does a request on "/api/users/me" with the code below:

`		
const data = await fetch("http://localhost:3000/api/users/me", {
	credentials: "include",
});

console.log(await data.json());
`
and as you saw, it returned: `user: null`

Then I remove this line `PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3000` from my .env file and press the button again. And as shown in the video it successfully returns a user. (with the cookie I set right before starting the recording)


https://github.com/payloadcms/payload/assets/117176031/04063142-48e6-44c4-9a19-42ab38b50a56

**Comment by JarrodMFlesch** [comment]
What does your config file look like? You are using the cors array, are you using the 
csrf array as well?

**Comment by dylankuipers** [comment]
@JarrodMFlesch No that project didn't., but when I add a csrf path it does work. 

I read online the csrf to allow cookie auth, though that means there's still a bug. Since if you don't have a csrf path and don't have this line: `PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3000` in your .env file that the auth through "/api/users/me" still works.

I would expect the "api/users/me" request to never work even if you don't have that line in your config.

Is that intended then?

**Comment by JarrodMFlesch** [comment]
@dylankuipers can you make the repo public so we can easily spin up the same environment as you?

**Comment by dylankuipers** [comment]
@JarrodMFlesch Here: https://github.com/dylankuipers/emptyastro

It wasn't a repo, so I quickly made one. Let me know if it works.

**Comment by JessChowdhury** [comment]
Hi @dylankuipers - apologies for the delay here. It looks like the repo that you shared is no longer available. If you are still experiencing this, could you re-share your repo?

**Comment by dylankuipers** [comment]
@JessChowdhury I've not been experiencing anymore issues with the me call. I'm going to close the issue now.
