### ISSUE TITLE
admin.isSortable: false, breaks when attempting to sort

### ISSUE THREAD

**Issue by JarrodMFlesch** [payloadcms/payload#3299]
### Link to reproduction

N/A

### To Reproduce

With the following config:

```ts
{
  name: 'items',
  type: 'array',
  fields: [
    {
      type: 'select',
      name: 'select',
      options: [
        {
          label: 'Option 1',
          value: 'option-1',
        },
        {
          label: 'Option 2',
          value: 'option-2',
        },
      ],
      admin: { 
        isSortable: false
      },
      hasMany: true,
    },
  ],
}
```

### Describe the Bug

When attempting to sort a select field within an array where the select field has `isSortable: false` set, the admin panel explodes 💣 .

https://github.com/payloadcms/payload/assets/30633324/e384408e-4da5-441d-85d5-20de4b9b18db

### Payload Version

1.15.4

**Comment by limistah** [comment]
Hi @JarrodMFlesch 

I can take this up. If it is open.

Regards.

**Comment by JarrodMFlesch** [comment]
@limistah I say give it a shot! You'll probably want to start in /src/admin/components/forms/field-types/select

**Comment by limistah** [comment]
Great.

**Comment by limistah** [comment]
@JarrodMFlesch 

I have tried replicating this issue with no success.

I added the config as a field here: 

https://github.com/limistah/payload/blob/f8e0e3315f75dee334e3a47a4175e7e798b3be73/test/versions/collections/Versions.ts#L53-L71 

And added a few version posts in the admin.

Could you tell if the amount of posts you have could impact this?

**Comment by JarrodMFlesch** [comment]
@limistah 1 post.

Add 2 options to your non sortable select field, and then attempt to sort them by clicking and trying to drag one of the options.

**Comment by limistah** [comment]
This is a my experience

![payloadcms](https://github.com/payloadcms/payload/assets/30846935/11a37469-47f7-413f-9762-7b5d09c315bd)

**Comment by JarrodMFlesch** [comment]
@limistah ah, I just recreated it. It is specifically when the select field is inside an array or block field.

**Comment by limistah** [comment]
Great, I can replicate this now.

The error comes from the API, and I have been able to trace it down to asking MongoDB to sort an array of object.

So, this calls for specification I believe, do we need to sort by individual fields of the nested object?

Or we want to sort by all the keys in the nested object. 

This is an interesting case considering that the duplication code has implemented an array of objects having an array field.

I would expect a decision here, this would affect how the bug can be fixed.

Pending the time, I would say, disabling sort on an array field containing nested object instead of `string` | `boolean` | `number`

**Comment by limistah** [comment]
So, to further replicate without the UI

Visit this test URL using the reproduction config on the `versions` post type

http://localhost:3000/admin/collections/version-posts?limit=10&sort=items

**Comment by limistah** [comment]
Digging deeper, I found that this url works: 

http://localhost:3000/admin/collections/version-posts?sort=-items.select&limit=10

For block/tab/array fields, the UI has to pass the field to sort by. If not, the API can't determine the sort property hence it generates an empty string. Check this line: 

https://github.com/payloadcms/payload/master/src/mongoose/buildSortParam.ts#L33C37-L33C37

**Comment by limistah** [comment]
Since the definition of an object inside of an array can have multiple keys, for example:
```
{
  name: 'items',
  type: 'array',
  fields: [
    {
      type: 'select',
      name: 'select field 1',
      options: [
        {
          label: 'select field 1 Option 1',
          value: 'select-field-1-option-1',
        },
        {
          label: 'select field 1 Option 2',
          value: 'select-field-1-option-2',
        },
      ],
      admin: { 
        isSortable: false
      },
      hasMany: true,
    },
    {
      type: 'select',
      name: 'select field 2',
      options: [
        {
          label: 'select field 2 Option 1',
          value: 'select-field-2-option-1',
        },
        {
          label: 'select field 2 Option 2',
          value: 'select-field-2-option-2',
        },
      ],
      admin: { 
        isSortable: false
      },
      hasMany: true,
    },
  ],
}
```

For a configuration like this, it might be better to have a way of selecting the actual field to sort by.

I believe this should be an ideal solution to solve this bug.

**Comment by JarrodMFlesch** [comment]
@limistah I think you might be misunderstanding the issue I am trying to describe. The issue at hand is a react error that is being thrown on the frontend.

I have updated the PR with a video to make it clearer!

**Comment by limistah** [comment]
Oh, then I might also have caught a bug.

**Comment by limistah** [comment]
Thank you for the video

**Comment by jmikrut** [comment]
@JarrodMFlesch please take a peek at the PR and merge accordingly. Thank you!
