### ISSUE TITLE
Locale selection doesn't work on demo site

### ISSUE THREAD

**Issue by okasi** [payloadcms/payload#3302]
### Link to reproduction

https://demo.payloadcms.com/

### To Reproduce

<img width="720" alt="image" src="https://github.com/payloadcms/payload/assets/42962282/08a46460-821b-4e5f-8cb3-0c33b30a5e70">

Select a locale from the sidebar

### Describe the Bug

When you select another locale other than English, it doesn't change to the translated copy on the site

### Payload Version

1.15.2

**Comment by JessChowdhury** [comment]
Hi @okasi - it appears to be working correctly for me. Could you share a screen recording of the behavior you are seeing?
https://github.com/payloadcms/payload/assets/67977755/4c34bcd4-3836-4310-9d02-17639aa46797

**Comment by JarrodMFlesch** [comment]
@okasi I think what you are referring to is the _language_ of the admin panel, that can be set from the users account/profile screen. You can navigate there by clicking the avatar icon and then selecting a language from there.

Changing the _locale_ on a document will not change the copy on the page, it will allow saving and loading content for specific locales.

**Comment by bodyguardcomnp** [comment]
> Hi @okasi - it appears to be working correctly for me. Could you share a screen recording of the behavior you are seeing? https://github.com/payloadcms/payload/assets/67977755/4c34bcd4-3836-4310-9d02-17639aa46797



> @okasi I think what you are referring to is the _language_ of the admin panel, that can be set from the users account/profile screen. You can navigate there by clicking the avatar icon and then selecting a language from there.
> 
> Changing the _locale_ on a document will not change the copy on the page, it will allow saving and loading content for specific locales.

Would not it be nice if Changing the _locale_ on a document will also trigger the _language_ of the admin panel ?

Also I want to contribute adding Nepali locale. how can I do that?
