### ISSUE TITLE
Getting Bad Gateway and Upstream Errors for the images that are being pulled from Amazon S3

### ISSUE THREAD

**Issue by farasatstar** [payloadcms/payload#3308]
### Link to reproduction

https://star-dev.vercel.app/

### To Reproduce

No Steps

### Describe the Bug

I have a payload connected with AWS S3 and payload cms is deployed on AWS App Runner.

This payload was working fine; one day, it started giving 502 and 504 errors for the images. I changed all the backend keys and created a new S3 bucket, the CMS began working. Now after 4 days, the issue arises again. I have not changed or updated anything; no error log for this is coming in the logs section.

I checked the CMS in development and it is working fine.

**_Edit: Redeployed and it started working and no configuration changed! and this is what has happened two times before. CMS works correctly for 2 - 3 days then it starts giving errors!_** 

### Payload Version

1.11.7

**Comment by jmikrut** [comment]
Hey @farasatstar — I think we're going to need more details to be able to address this issue as we can't replicate in our own projects. I believe this may have to do with your S3 policies or similar and I don't suspect it has to do with Payload itself.

If you can provide a reproducible environment for us to be able to debug ourselves, we would be happy to address this but as of now this seems to be a configuration issue with your S3 environment. Thank you!
