### ISSUE TITLE
Autosave relative time only shows last update in minutes

### ISSUE THREAD

**Issue by ChrisGV04** [payloadcms/payload#3314]
### Link to reproduction

Any Payload project with autosave enabled

### To Reproduce

Create any collection and enable auto save with `versions: { drafts: { autosave: true } }`. Then, create a document for that collection and start editing and save the changes. Now, wait for a few hours or days and go back to the document to check the "Last saved" label and it will show many minutes, instead of formatting a relative timestamp.

<img width="342" alt="Screenshot 2023-09-11 at 5 00 07 p m" src="https://github.com/payloadcms/payload/assets/47041342/fbcb26fb-ad85-4e1a-99be-868fc8392bdf">

### Describe the Bug

The label that indicates how long ago the document got saved always show the time in "minutes ago", when maybe it should display a relative timestamp such as "1 hour ago", "2 days ago" or the full date for when it was a long time ago.

It is not very useful seeing "Last saved 8,538 minutes ago", but maybe "5 days ago" or "September 6 2023, 6:31 PM".

I know it's not a big deal, but it is kind of weird seeing so many minutes.

### Payload Version

1.15.5

**Comment by jmikrut** [comment]
@JarrodMFlesch please review the PR and merge accordingly. Thank you!
