### ISSUE TITLE
React datepicker partially folds under collection edit actions

### ISSUE THREAD

**Issue by kariyngva** [payloadcms/payload#3323]
### Link to reproduction

https://github.com/kariyngva/payload/tree/bug/datepicker-z-index-issue

### To Reproduce

1. Create a collection
2. Add two fields to the collection with `position: 'siderbar'`
```ts
    {
      name: 'someFieldInSidebar',
      type: 'text',
      admin: {
        position: 'sidebar',
      },
    },
    {
      name: 'otherFieldInSidebar',
      type: 'text',
      admin: {
        position: 'sidebar',
      },
    },
```
3. Add a date field to the collection, with `position: 'siderbar'` 
```ts
{
      name: 'publishedDate',
      type: 'date',
      admin: {
        position: 'sidebar',
        date: {
          displayFormat: 'dd-MM-yyyy',
        },
      },
    }
```
4. Edit the collection with your window height below 790px
5. Try and click the year or month select

### Describe the Bug

When you have a datepicker in the sidebar, the "popper" can partially fold under the collection edit action, in some screen resolutions/window sizes (height < 790px).

This causes the user to be unable to click the month and year select elements.

![image](https://github.com/payloadcms/payload/assets/1204564/fe84069e-0c8a-47b3-afeb-46a99d949179)

[.collection-edit__document-actions](https://github.com/payloadcms/payload/blob/8ca67d5aaa99f0f45eac56766fe42e07ab4a41f1/src/admin/components/views/collections/Edit/index.scss#L76) gets z-index from `var(--z-nav)`. Either removing the `z-index` from actions or bumping [.react-datepicker-popper](https://github.com/payloadcms/payload/blob/8ca67d5aaa99f0f45eac56766fe42e07ab4a41f1/src/admin/components/elements/DatePicker/index.scss#L256) to the same value would resolve this issue.

### Payload Version

1.15.5

**Comment by jmikrut** [comment]
Hey @kariyngva — this is likely fixed in 2.0 due to the new UI changes we've made. Will you update and give it a shot?
