### ISSUE TITLE
Upload static url access does not populate id field for access args

### ISSUE THREAD

**Issue by AaronVr** [payloadcms/payload#3325]
### Link to reproduction

https://github.com/AaronVr/payload-upload-static-url-id-bug

### To Reproduce

1. Download the reproduction repository.
2. Adjust the media  collection `test/_community/collections/Media/index.ts` as follows:
```
import type { CollectionConfig } from '../../../../src/collections/config/types';

export const mediaSlug = 'media';

export const MediaCollection: CollectionConfig = {
  slug: mediaSlug,
  upload: {
    staticURL: '/media',
    staticDir: './media',
  },
  access: {
    read: (args) => { console.log("args.id: ", args.id); return true; },
    create: () => true,
  },
  fields: [],
};
```
3. Use the static URL to fetch a media file. E.g., for an image with name `<image_name>` do a GET request to `localhost:3000/media/<image_name>`.
4. Look at the terminal, the `args.id` field will be shown as undefined.

### Describe the Bug

The `args.id` field is undefined when a GET request is made to the static URL of an upload collection. As the semantics of fetching from the static url would seem similar to a normal `findById` request, I would expect the id field to be set for the request. 

### Payload Version

1.15.5

**Comment by jmikrut** [comment]
Hey @AaronVr — there's unfortunately nothing Payload can do about this.

https://github.com/payloadcms/payload/blob/main/packages/payload/src/auth/getExecuteStaticAccess.ts#L19

As you can see in the file above, the _only_ thing we have to go on when we execute access control for static files is the `filename`, which means that we don't have access to the `id` until _after_ the access control is run.

But you can work around it in your own access control by fetching the document in your access control using the filename, and then retrieving its ID from there.

Does that make sense?
