### ISSUE TITLE
Can't add block with certain condition on field

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3326]
### Link to reproduction

/

### To Reproduce

1. Create the following block:
```
const Block: Block = {
  slug: 'Cta',
  interfaceName: 'Cta',
  fields: [
    {
      name: 'fields',
      type: 'select',
      options: ['content', 'buttons', 'image'],
      hasMany: true,
    },
]
}
```

Then create this block:
```
const Block: Block = {
  slug: 'Cta',
  interfaceName: 'Cta',
  fields: [
    {
      name: 'fields',
      type: 'select',
      options: ['content', 'buttons', 'image'],
      hasMany: true,
    },
    {
      name: 'content',
      type: 'richText',
      admin: {
        elements: ['h1', 'h2', 'h3'],
        leaves: ['bold', 'italic', 'strikethrough', 'underline'],
        hideGutter: true,
        condition: (data, siblingData) =>
          siblingData.fields.includes('content'),
      },
    },
]
}
```

### Describe the Bug

You will see that the first block renders fine in the 'block' field. However, the second one does not get added. please checkou my video below:

https://github.com/payloadcms/payload/assets/52583398/77282cfd-66cd-4a84-803c-bcb84b6bd37b

It seems to be caused by the condition being dependant on the field before it, because when I simply return false from the condition, it does work

### Payload Version

1.15.5

**Comment by silveltman** [comment]
Found the problem. When a block is added, the field are initially undefined. added a consolelog to debug and then found this error too:

```
{blockType: 'Cta'} // console.log of siblingData

Cta.ts:25 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at Object.condition (Cta.ts:25:37)
    at iterateFields.js:12:1
    at Array.forEach (<anonymous>)
    at iterateFields (iterateFields.js:8:1)
    at buildStateFromSchema (index.js:8:1)
    at index.js:368:1
```

as you can see, the field names 'fields' does not yet exist on the block when initiating

**Comment by JarrodMFlesch** [comment]
@silveltman I think your solution is the correct one, not sure this is a bug.

**Comment by silveltman** [comment]
Seems weird to be that a condition function runs before the field exists

**Comment by JessChowdhury** [comment]
@silveltman even after the field exists, it's value remains undefined until options have been selected. You could add an empty array as the default value, but I would still recommend adding the `?` or another way of checking that `fields` exists before calling `.includes()` just for safe coding practices.

Closing this issue - feel free to reach out again!
