### ISSUE TITLE
Cmd + S hotkey doesn't work sometimes due to `editDepth` check

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#3336]
### Link to reproduction

https://github.com/hdodov/payload/tree/bug-hotkeys

### To Reproduce

1. Run `yarn dev _community`
2. Change the "Menu" global
3. Hit <kbd>Cmd + S</kbd>

### Describe the Bug

As I've demonstrated in https://github.com/payloadcms/payload/pull/1821#issuecomment-1683388162, the hotkey doesn't always work:

https://github.com/payloadcms/payload/assets/5570098/b8f91b38-9b90-44a7-80c2-f16dcaf03558

After digging a bit, it appears that `maxEditDepth` differs from `editDepth` upon pressing <kbd>Cmd + S</kbd>:

![image](https://github.com/payloadcms/payload/assets/5570098/62f79fc3-9c30-45e2-94f8-1345c9c0b5e6)

…so this check fails:

https://github.com/payloadcms/payload/blob/6754f55ce0a09b1a765f19426ef269d09e1191c0/src/admin/hooks/useHotkey.tsx#L91-L94

The logs I've shown on the screenshot can be seen on my branch: https://github.com/hdodov/payload/tree/bug-hotkeys

As a reminder, this happens in the original Payload repo, in the `_community` playground. This is not in my own project, so I believe it's genuinely a problem with Payload.

### Payload Version

1.15.6

**Comment by limistah** [comment]
I was able to replicate and provide a fix for the issue, might be able to look at it here https://github.com/payloadcms/payload/pull/3342

**Comment by JarrodMFlesch** [comment]
This has been fixed on the 2.0 branch. I left a comment for @limistah to see if he wanted to make the same change on 1.0.

**Comment by jmikrut** [comment]
@JarrodMFlesch — can you verify that this is now resolved? If so, please close this issue.

**Comment by hdodov** [comment]
I tried Cmd+S yesterday on Payload 2.0.0 and at one point the "save page as HTML" dialog appeared again. The reason might not be `editDepth` as it's in this issue, though. I haven't researched currently.
