### ISSUE TITLE
Select Field does not return correct value in GraphQL

### ISSUE THREAD

**Issue by TomDo1234** [payloadcms/payload#3354]
### Link to reproduction

https://evcarsales.co/research-an-ev/model-x-p90d-2016

### To Reproduce

1. create a select field, but make sure that the values are in the object form, {label: string, value: string}, also include spaces and parenthesis in the value, for example 
"Sports Utility Vehicle (SUV)"

2. Use graphql to query that field, and then get this displayed:
![image](https://github.com/payloadcms/payload/assets/37052068/fc5514b7-0f78-400b-af64-1e50de385814)

3. Then use REST instead and see that the value is displayed correctly

### Describe the Bug

I described it above

### Payload Version

1.15.6

**Comment by TomDo1234** [comment]
NOTE TO MAINTAINERS that I just switched my code to Rest so the reproduction link displays correctly.

**Comment by jmikrut** [comment]
Hey @TomDo1234 — yes, this is a limitation with GraphQL. GraphQL enums cannot have special characters in them so your `value` should always be a GraphQL-safe string if you plan to use GraphQL.

Thank you for bringing this up!

**Comment by JarrodMFlesch** [comment]
Just to add here, on your frontend you would just create a keyed object using your graphQL safe values as the keys.

i.e.

```ts
const valueKeyMap = {
  suv: "Sports Utility Vehicle (SUV)",
  rangeRover: "Amphibious Exploring Vehicle",
}

const valueYouWantToDisplay = valueKeyMap[selectValue]
```
