### ISSUE TITLE
Fetch user failed, cannot login/out or create new user

### ISSUE THREAD

**Issue by ballermatic** [payloadcms/payload#3360]
### Link to reproduction

https://github.com/ballermatic/backend
[Example running on Railway here](https://edit.gravybo.at/).

### To Reproduce

1. Install, create user.
2. Use normally: create collection content, etc
3. At some unknown point, auth will fail. This can take hours or 2-3 days. Persistent error `Fetch user failed` where api/users/me returns nothing: no server error codes, browser error is ERR_NAME_NOT_RESOLVED in Chrome or 400 in Firefox. 
4. Clear cookies, use a fresh browser, incognito, try to log in or out. Same result.

So far the only solution I have found to this is delete the users from Mongo DB then create a new user via localhost `run dev`.

### Describe the Bug

Cannot login or logout after some indeterminate period of time. Resetting cookies, browser session, browser, incognito mode, etc. seemingly have no effect.

### Payload Version

1.15.5

**Comment by b00y0h** [comment]
having the same issue and it only happens on the custom domain that was just setup on payload cloud.

This one works (gets login screen): [appily-cms.payloadcms.app](https://appily-cms.payloadcms.app/)
This is the new domain to point to the above: [advance-cms.appily.com](https://advance-cms.appily.com/)

Console shows CORS error on `https://advance-cms.appily.com/api/users/me` but is fine (returns a 304) when hitting `https://appily-cms.payloadcms.app/api/users/me` on `appily-cms.payloadcms.app`

**Comment by b00y0h** [comment]
turns out, for me, it was updating the `PAYLOAD_PUBLIC_SERVER_URL` env variable to the new domain. Seems like that should auto update?

**Comment by ballermatic** [comment]
This does appear to be a CORS issue! Good catch. Chrome was not showing it, however Firefox is. Thank you for the nudge! Working on a fix now.

**Comment by ballermatic** [comment]
Ok, it turns out the issue was indeed CORS. For anyone finding this in the future, note that Railway env such as `RAILWAY_PUBLIC_DOMAIN` do not render the custom domain, only the generated one provided by the service. Closing it out!
