### ISSUE TITLE
Upload images

### ISSUE THREAD

**Issue by dylankuipers** [payloadcms/payload#3397]
### Link to reproduction

Use REST API to upload an image

### To Reproduce

Upload an image using the create from REST API or formdata.

### Describe the Bug

I am trying to upload an image from a file (or link) to payload. I tried multiple things like content-types, different fetches, changing collections, formdata and some more, but I can't get it to work.

I keep getting the error: "MissingFile: No files were uploaded".

However, everything I tried including different images from both files and links, nothing seems to work.

Am I doing something wrong? or is this currently bugged?

I saw many others having issues with this and a couple of solutions that might work, but none have for me.

This is the latest thing I tried: `	const req = await fetch("http://localhost:3000/api/images", {
		method: "POST",
		credentials: "include",
		headers: {
			"Content-Type": "multipart/form-data",
		},
		body: JSON.stringify({
			image: "your-image-url (i emptied this myself)",
		}),
	});`

tried this solution both with and without the content-type. The image is a field in my collection, which has type: "upload".

### Payload Version

1.15.6

**Comment by silveltman** [comment]
I'm having the same issue

**Comment by orasik** [comment]
You need to use `file` for the file upload.

```
curl --location 'https://{BASE_URL}/api/media' \
--header 'Authorization: {slug} API-Key {key}' \
--form 'file=@"/path/to/file"' \
```

**Comment by dylankuipers** [comment]
@orasik Thanks!
