### ISSUE TITLE
/me endpoint is insecure

### ISSUE THREAD

**Issue by ericuldall** [payloadcms/payload#3405]
### Link to reproduction

https://github.com/ericuldall/payload-me-is-insecure

### To Reproduce

1. Run the docker-compose
2.  Browse to localhost:3000/admin
3. Create your first user (notice here it's showing the admin only field as well)
4. Once inside the admin you can add the admin role to your user and save
5. Check the admin only check box and save
6. Remove admin role and save user
7. Admin only field will not show in dashboard as expected, will also not show in the api call to /users/:userId, BUT it will show in the api call to /users/me

### Describe the Bug

Fields that are blocked by { access } show up in the /users/me api call.
Access used is here: https://github.com/ericuldall/payload-me-is-insecure/blob/main/src/collections/Users.ts#L13

### Payload Version

^1.15.6

**Comment by jmikrut** [comment]
Hey @ericuldall — thanks for opening this issue. We will take a look into this immediately and report back ASAP!

**Comment by ericuldall** [comment]
Let me know once you guys have the patch ready. I have a fairly complex integration I can test the new version with to see if there's any holes.

**Comment by ericuldall** [comment]
Not sure if the merge resolved the issue. I just tested 1.15.7 and i'm still seeing restricted fields in the user object.
