### ISSUE TITLE
Validation of large, auto-populated array with admin.hidden = true throws an error

### ISSUE THREAD

**Issue by svntime** [payloadcms/payload#3419]
### Link to reproduction

https://github.com/svntime/payload-reproduction

### To Reproduce

1. clone reproduction and run `yarn dev _community`
2. create new Post with random title
3. try to update the document by pressing "Save" button (you may need to increase the number of rows in `beforeChange` hook if 1000 is processed too fast on your computer)

Page should hang for a while and then you should get "The following field is invalid" error.

### Describe the Bug

Hi there, I implemented `beforeChange` hook which should auto-populate large array, but only when the `req.files.file` is available. This array is invisible in the dashboard (admin.hidden = true), but I noticed that validation is still called and takes some time (page hangs) + throws an error.

![image](https://github.com/payloadcms/payload/assets/42152930/c76fcc2d-d150-4ed9-8388-8a00938c66e0)
![image](https://github.com/payloadcms/payload/assets/42152930/eb71f9e9-bb14-4407-a5be-9f4a862d2a58)

I've provided a simple reproduction. Maybe it's not a bug, but my wrong approach to the problem and I should just use beforeValidation hook. 
I would appreciate your help. Thanks!

### Payload Version

1.15.6

**Comment by jmikrut** [comment]
Hey @svntime — apologies for this slipping off the radar. I just tested this on Payload 2.26.0 and I can no longer reproduce.

If you are still experiencing this, try and update to that version. The save action still takes a bit to complete, but there are no longer any validation errors. Should be fixed.
