### ISSUE TITLE
Var value of related collection null in richtext field within rest api

### ISSUE THREAD

**Issue by mvdve** [payloadcms/payload#3421]
### Link to reproduction

https://github.com/mvdve/payload-link-value-null

### To Reproduce

1. Start empty database `docker compose up`
2. Start the community test `npm run dev _community`
3. Open a new post
4. Create a couple of internal links to the event collection. For example four links to the four test event
5. Safe the post. Everything seems to be fine
6. Add a random character to one of the fields and save the post
7. Most or all links are now empty, calling the rest endpoint will result in a value: null instead of the event object

```json
"doc": {
    "value":null,
    "relationTo":"events"
}
```

### Describe the Bug

The relationship value variable from the link element within the richtext field is null after editing.

This results in empty links within the UI after an update (not the initial page load) and a missing content object within the rest api.

### Payload Version

1.15.7

**Comment by AlessioGr** [comment]
Hey, I cannot reproduce this issue in 2.0:

https://github.com/payloadcms/payload/assets/70709113/4baea684-88f5-429f-a469-d316206d51f4

Might have been fixed already! Please don't hesitate to re-open the issue if you manage to reproduce it in 2.0

**Comment by mvdve** [comment]
Hi @AlessioGr Thanks for checking. I'm not very keen on upgrading to 2.0 at this moment. On every upgrade i run into new major bugs. Would prefer to keep using 1.0 until 2.0 is a bit more stable.
