### ISSUE TITLE
Custom server example does not work

### ISSUE THREAD

**Issue by timboozle** [payloadcms/payload#3423]
### Link to reproduction

https://github.com/payloadcms/payload/tree/master/examples/custom-server

### To Reproduce

Follow the steps as provided in the Quick Start section.

### Describe the Bug

In development:
- Payload works on localhost:3000/admin
- Next.js on localhost:3000 does not work. 

The error:
`Cannot read properties of undefined (reading 'sources')`

Building for production:
- Everything works.

### Payload Version

latest

**Comment by PatrikKozak** [comment]
Hey @timboozle - we actually just pushed a couple updates to the `custom-server` example - can you pull in the latest changes from master and give it another try?

**Comment by timboozle** [comment]
Great stuff! Definitely working now.
