### ISSUE TITLE
Duplication of drafts does not work properly

### ISSUE THREAD

**Issue by jankocian** [payloadcms/payload#3431]
### Link to reproduction

https://github.com/jankocian/payload-repro-duplication

### To Reproduce

make changes to a post, save as draft, duplicate the post - the content will not correspond

### Describe the Bug

When duplicating documents saved as drafts, the duplicated docs' content is not coming from the latest saved draft. When publishing the page, the problem disappears.

Edit: Also, Payload lets me save as a draft a document without successful validation (not all the required fields are filled in, which is OK), but in that case Duplication ends up with an error, as the document gets validated. It should allow draft duplication without the successful validation as well.

https://github.com/payloadcms/payload/assets/20462234/d77cc7fd-e785-4695-9554-36d8e03c974e

### Payload Version

1.15.6

**Comment by jmikrut** [comment]
Good catch! Easy fix to ensure that the duplication pulls draft data. Will be coming to 2.0 shortly.

We are also planning on adding a feature to allow you to require validation for drafts. It will be opt-in but will be possible.

**Comment by jmikrut** [comment]
@JessChowdhury this one is an easy fix: 

https://github.com/payloadcms/payload/blob/main/packages/payload/src/admin/components/elements/DuplicateDocument/index.tsx#L48

In the above file, for all fetches to existing data, we just need to add `draft: true`. For the main doc and the locale fetches.
