### ISSUE TITLE
Module not found: Error: Can't resolve webpack-hot-middleware

### ISSUE THREAD

**Issue by smoglica** [payloadcms/payload#3437]
### Link to reproduction

N/A

### To Reproduce

- Use `pnpm` as package manager
- Start the dev server with `pnpm dev`
- You should see `Module not found: Error: Can't resolve 'webpack-hot-middleware/client?path=/admin/__webpack_hmr' in '/usr/src/app/apps/cms'`

### Describe the Bug

When using `pnpm` since version `1.11.6` and more precisely when pull request [3074](https://github.com/payloadcms/payload/pull/3074/files) was merged, I get the following error:

![Screenshot from 2023-10-04 23-07-32](https://github.com/payloadcms/payload/assets/17332096/632ad347-9e1e-403e-a288-55448163df99)

### Payload Version

1.11.6

**Comment by jmikrut** [comment]
Hey @smoglica — thank you for the report! Will look into this ASAP.

**Comment by denolfe** [comment]
Fixed by 65cdf6bfd in 2.0
