### ISSUE TITLE
Can't resolve 'fs' in website and ecommerce template

### ISSUE THREAD

**Issue by AsToNlele** [payloadcms/payload#3460]
### Link to reproduction

https://github.com/AsToNlele/payload-website-repro

### To Reproduce

1. `npx create-payload-app -t website` or ecommerce
2. `cd` into the project
3. `yarn dev`

Fails in docker as well.

node 18.16.1
(fails using any package managers)
yarn 1.22.19
npm 9.5.1
pnpm 8.7.4

### Describe the Bug

```
[14:59:36] INFO (payload): Connected to MongoDB server successfully!
[14:59:36] INFO (payload): Starting Payload...
[14:59:37] INFO (payload): Payload Admin URL: http://localhost:3000/admin
[14:59:40] INFO (payload): Starting Next.js...
[14:59:40] INFO (payload): Next.js App URL: http://localhost:3000
webpack built 26db4a1055948f5bc4c0 in 6156ms
ERROR in ./src/payload/seed/index.ts 235:0-20
Module not found: Error: Can't resolve 'fs' in '/Users/aston/dev/another-payload/src/payload/seed'

webpack compiled with 1 error
```

I was able to fix this by adding to the package.json
```json
  "browser": {
    "fs": false
  },
```

Can create a PR for this.

### Payload Version

1.15.7

**Comment by goigle** [comment]
this fixed the issue for me as well

**Comment by jmikrut** [comment]
Hey @goigle and @AsToNlele — I think we just fixed this.

Related issue #3494

Will you keep an eye out for a new version of the Webpack bundler to be released, and then test accordingly?

**Comment by AsToNlele** [comment]
Thanks for the quick fix!
