### ISSUE TITLE
Condition not working on tab

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3473]
### Link to reproduction

https://github.com/silveltman/payload-reproduction/tree/tab-condition

### To Reproduce

Create the following collection:
```
const Collection = {
    slug: 'pages',
    fields: [
        {
            type: 'tabs',
            tabs: [
                {
                    name: 'testtab',
                    fields: [
                        {
                            name: 'testfield',
                            type: 'text'
                        }
                    ],
                    admin: {
                        condition: () => false
                    }
                }
            ]
        },
    ],
}

export default Collection
```
Look in the admin panel if the tab is hidden

### Describe the Bug

The tab is not hidden, but also no TS error is given.

It seems like either a payload bug; not hiding the tab, or a ts config issue; not giving an error for something which is not intended to be possible

### Payload Version

1.15.6

**Comment by silveltman** [comment]
I want to add that all admin config does not work for a tab. This appears to be expected according to this part of the docs:

![Screenshot 2023-10-08 at 15 51 09](https://github.com/payloadcms/payload/assets/52583398/f7b128c0-b2b1-45d2-8717-4767b96e271d)

Therefore, there is probably something wrong with typescript. I looked into the tab types and found the following:
```
export type NamedTab = TabBase & {
    /** Customize generated GraphQL and Typescript schema names.
     * The slug is used by default.
     *
     * This is useful if you would like to generate a top level type to share amongst collections/fields.
     * **Note**: Top level types can collide, ensure they are unique among collections, arrays, groups, blocks, tabs.
     */
    interfaceName?: string;
};
export type UnnamedTab = Omit<TabBase, 'name'> & {
    label: Record<string, string> | string;
    localized?: never;
    interfaceName?: never;
};
export type Tab = NamedTab | UnnamedTab;
export type TabsField = Omit<FieldBase, 'admin' | 'name' | 'localized' | 'saveToJWT'> & {
    type: 'tabs';
    tabs: Tab[];
    admin?: TabsAdmin;
};
export type TabAsField = Tab & {
    type: 'tab';
    name?: string;
};
```

The weird things is though that these types do not seem to include 'admin' but still typescript does not give an error when adding an 'admin object to the tab. When adding a random field, like 'adminnnn' typescript DOES give the error.

**Comment by jmikrut** [comment]
Hey @silveltman — this is actually on our roadmap to enable!

https://github.com/payloadcms/payload/discussions/1840

I will close this as it is a duplicate, but this is coming soon. 

Thank you for bringing this up!

**Comment by silveltman** [comment]
Awesome! 

@jmikrut little sidequestion; I askes a quesiton using the form on your website a couple of times but have not heard back, even though it says 24-48 hours response time. 

I understand if you are busy atm with 2.0, but just checking if the form is working and you are at least receiving the messages.
