### ISSUE TITLE
RichTextAdapter types do not strictly match on blank template

### ISSUE THREAD

**Issue by joas8211** [payloadcms/payload#3491]
### Link to reproduction

https://github.com/joas8211/payload-editor-type-bug

#### From scratch
1. Create project from blank template.
    `npx create-payload-app payload-editor-type-bug -t blank`
2. Modify tsconfig.json to set `strict` to `true`.
3. Install and build.
    `yarn install && yarn build`

#### Using reproduction repository
1. Clone the repository.
    `git clone https://github.com/joas8211/payload-editor-type-bug`
2. Install and build.
    `yarn install && yarn build`

### Describe the Bug

When build is ran the following error is printed:
```
src/payload.config.ts:16:3 - error TS2322: Type 'RichTextAdapter<AdapterArguments>' is not assignable to type 'RichTextAdapter<unknown>'.
```

You can also see the error highlighted in VSCode. There also some other errors which are not strictly related to this issue.

### Payload Version

2.0.0

**Comment by joas8211** [comment]
# Workaround
```typescript
export default buildConfig({
  // ...
  editor: slateEditor({}) as RichTextAdapter,
  // ...
});
```

**Comment by AlessioGr** [comment]
Reproduced, this will be fixed today :)
