### ISSUE TITLE
2.0 Sidebar nav styling bug

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3496]
### Link to reproduction

/

### To Reproduce

Open payload admin panel and make window smaller (mobile/tablet size)

### Describe the Bug

When not opened:
![Screenshot 2023-10-09 at 13 44 51](https://github.com/payloadcms/payload/assets/52583398/24357292-9741-448f-a7ac-b40dc92312f6)

When clicking hamburger:
![Screenshot 2023-10-09 at 13 45 06](https://github.com/payloadcms/payload/assets/52583398/e87b9101-d7f1-41b4-a992-3621f73c5436)

### Payload Version

2.0

**Comment by denolfe** [comment]
Hey @silveltman . Thanks for the report. Unfortunately, I have not been able to reproduce this. What OS and browser are you using? Are you able to make a video reproducing?

https://github.com/payloadcms/payload/assets/65888/bdd477f9-7b5b-471d-96b7-3801f5939970
