### ISSUE TITLE
MongoURL information does not propagate to function call 

### ISSUE THREAD

**Issue by joecaraccio** [payloadcms/payload#350]
# Bug Report

Hi Everyone, I think this might be a bug, but won't rule out myself doing something dumb.

## Detailed Description

I specify the MongoURL I want to use in the init of the payload object
```
payload.init({
  secret: process.env.PAYLOAD_SECRET,
  mongoURL: "mongodb://localhost/9999",
  express: app,
  onInit: () => {
    payload.logger.info(`Payload Admin URL: ${payload.getAdminURL()}`);
    payload.logger.info(`Payload Mongo URL: ${payload.mongoURL}`);

  },
});
```

However, regardless of whatever value I send through, I get the same error in my log on startup:
` Error: cannot connect to MongoDB. Details: connect ECONNREFUSED 127.0.0.1:27017`

Which isn't correct for my usecase. Looking at the logic it is pretty simple.  Is there something I'm missing? Not sure why it is printing that. Any ideas?

**Comment by JarrodMFlesch** [comment]
Hey @joecaraccio, it sounds like mongoDB is not currently running on your maching. If you open a new terminal window you can type `sudo service mongod start` and that should start mongoDB locally for you and then you can re-run your command to start your express server. Can you give that a shot?

**Comment by joecaraccio** [comment]
@JarrodMFlesch  thanks for the reply!

Pretty sure MongoDB was running. It was running in a separate docker container but it should all be on the same network.

Should that connect string not update? Kinda my original issue is in theory I'm telling payload to connect to MongoDB on 9999, but the error it throws makes me feel like it's using the wrong port

**Comment by jmikrut** [comment]
Hey @joecaraccio I think i can shine some additional light on this for you.

Your Mongo URL is not actually specifying a port:

```
  mongoURL: "mongodb://localhost/9999",
```

That `9999` would be the name of the database that you are looking to connect to. If you wanted to instead specify a port, you'd do it like this:

```
  mongoURL: "mongodb://localhost:9999/yourDatabaseNameHere",
```

So the error message you're getting is legitimate. Payload is trying to connect to your local Mongoose using the default port of 27017 because you are not specifying a port. And it can't connect.

How's that?

**Comment by joecaraccio** [comment]
yikes. yup. wow thats bad. sorry about that! this can be deleted.

So sorry.. wow..

**Comment by jmikrut** [comment]
Ha no prob. It happens to the best of us. This will likely help others in the future anyway!
