### ISSUE TITLE
No preview button in 2.0

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3502]
### Link to reproduction

/

### To Reproduce

Create a collection and add the following to the config:
```
  admin: {
    preview: () => 'https://localhost:4321',
  },
```

### Describe the Bug

The 'Preview' button which was previously next to the 'Save' button is nowhere to be seen. 
This is both with or without the new livePreview enabled.

### Payload Version

2.0

**Comment by denolfe** [comment]
The preview button still shows. Can you compare your config to the one in our test/admin suite here? https://github.com/payloadcms/payload/blob/main/test/admin/config.ts#L101.

The following can be seen with `pnpm dev admin` on our repo.

![CleanShot 2023-10-09 at 11 22 42](https://github.com/payloadcms/payload/assets/65888/3a32b4af-63e7-4c8a-ae43-751980c5b738)

**Comment by silveltman** [comment]
I will compare the config.

"The following can be seen with pnpm dev admin on our repo."
>> I will try with pnpm. However pnpm is not supported yet by payload cloud, correct?

**Comment by silveltman** [comment]
I checked the config and set it allmost equal. The problem seems to go away when enabling drafts:
```
versions: {
    drafts: true,
  },
```

Previously I had just `versions: true`

Button disappears again when enabling autosave:
```
  versions: {
    drafts: {
      autosave: true,
    },
  },
```
