### ISSUE TITLE
No user settings in 2.0

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3503]
### Link to reproduction

/

### To Reproduce

Open the new payload admin

### Describe the Bug

The user setting, which were in the bottom-right, are not there anymore:
![Screenshot 2023-10-09 at 16 57 02](https://github.com/payloadcms/payload/assets/52583398/fa25b93b-e008-4098-9699-6bb71024dee3)

This prevents the user from changing:
- dashboard language
- light/dark mode

(Hope you don't mind me placing this many issues, just trying to help you guys out, hope you appreciate it :))

### Payload Version

2.0.2

**Comment by denolfe** [comment]
This has been relocated to the top right.

![CleanShot 2023-10-09 at 11 19 40](https://github.com/payloadcms/payload/assets/65888/f0dd302e-8513-43dd-b083-7d1be239474c)

**Comment by silveltman** [comment]
On viewports above 1440px it seems to fall behind the locale selector, thats why I didnt see it. Check screenshot below:

![Screenshot 2023-10-09 at 18 05 09](https://github.com/payloadcms/payload/assets/52583398/d402f00e-4893-404b-b77d-a3bbb603af83)

**Comment by silveltman** [comment]
Same cause as https://github.com/payloadcms/payload/issues/3496#issuecomment-1753296013
