### ISSUE TITLE
npm run payload -> npx payload ?

### ISSUE THREAD

**Issue by DavidOliver** [payloadcms/payload#3508]
# Documentation Issue

At https://payloadcms.com/docs/database/postgres and https://payloadcms.com/docs/database/migrations, we're instructed to run, for example, `npm run payload migrate:create`.

I'm running Node `20.8.0`/npm `10.1.0`, and this results in:

```plain
$ npm run payload migrate:create
npm ERR! Missing script: "payload"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in: /home/david/.npm/_logs/2023-10-09T15_48_45_654Z-debug-0.log

$ npm run
Scripts available in ac-payload@1.0.0 via `npm run-script`:
  dev
    cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts nodemon
  build:payload
    cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload build
  build:server
    tsc
  build
    npm run copyfiles && npm run build:payload && npm run build:server
  serve
    cross-env PAYLOAD_CONFIG_PATH=dist/payload.config.js NODE_ENV=production node dist/server.js
  copyfiles
    copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png}" dist/
  generate:types
    cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload generate:types
  generate:graphQLSchema
    cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload generate:graphQLSchema
```

Only the scripts specified in `package.json` are available via `npm run`.

Running `npx payload migrate:create` successfully executes the binary and generates the migration.

Apparently, `npx` has been available since npm `5.2.0`.

**Comment by DavidOliver** [comment]
@denolfe , thanks! I see that the script that should be added references the config. Do you happen to know if my having run `npx payload migrate:create`, without mentioning the config, is a problem? It seems to have picked up on the various collections based on a quick inspection of the resultant migration.

**Comment by denolfe** [comment]
@DavidOliver It is not required. Payload attempts to find the payload config in an intelligent way, so it may be able to find it and load it automatically.
