### ISSUE TITLE
Logging out is not possible when the domain option is set for auth cookies

### ISSUE THREAD

**Issue by mrvase** [payloadcms/payload#351]
# Bug Report

If one sets the cookie.domain property in the authentication config of a collection, the API route for logging out does not work.

## Possible Solution

I suppose the problem is in auth/operations/logout.ts, where no value is given for the domain property in cookieOptions used in res.clearCookie. But the domain option has to be similar to the value that was given at creation in order for clearCookie to work. That is, the domain property should be set to the value given in the collection config, if such a value is given.

**Comment by jmikrut** [comment]
Great catch @mrvase — you're exactly right. Cookie settings need to match 100% I believe. Fix incoming!
