### ISSUE TITLE
Document cannot be deleted when using drafts and localisation (Postgres adapter)

### ISSUE THREAD

**Issue by leonardstruck** [payloadcms/payload#3511]
### Link to reproduction

https://github.com/leonardstruck/payload/tree/versioned-docs-not-deletable

### To Reproduce

1. Add localisation config

```typescript
  localization: {
    locales: ['de', 'en'],
    defaultLocale: 'de',
  },
```

2. Create collection with any localised field and enable drafts.

```typescript
export const PagesCollection: CollectionConfig = {
  slug: pagesSlug,
  versions: {
    drafts: true,
  },
  fields: [
    {
      type: 'text',
      name: 'title',
      localized: true,
    },
  ],
}

```

### Describe the Bug

https://github.com/payloadcms/payload/assets/29303671/39b8776d-2a66-4f45-9026-50b97083aee2

All tests run fine...

### Payload Version

2.0.2

**Comment by jmikrut** [comment]
Thanks @leonardstruck — fixed. Gonna add a test, merge, and release. Keep an eye out!
