### ISSUE TITLE
Postgres: relationship with hasMany can't be cleared

### ISSUE THREAD

**Issue by Janisvb** [payloadcms/payload#3513]
### Link to reproduction

https://github.com/janisvb/payload-reproduction/tree/empty-relation

### To Reproduce

```
export PAYLOAD_DATABASE=postgres
yarn dev _community
```

### Describe the Bug

When having a relationship field with `hasMany: true`, it is not possible to clear the value:
```ts
{
  name: 'authors',
  type: 'relationship',
  relationTo: 'users',
  hasMany: true,
}
```

Clearing the value programmatically does not work

```ts
const post = await payload.create({
  collection: postsSlug,
  data: {
    text: 'example post',
    authors: [user.id],
  },
})

// not working
await payload.update<Post>({
  collection: postsSlug,
  id: post.id,
  data: {
    authors: [],
  },
})

// also not working
await payload.update<Post>({
  collection: postsSlug,
  id: post.id,
  data: {
    authors: null,
  },
})
```

Also manually clearing the value in the Admin UI does not work.

### Payload Version

2.0

**Comment by jmikrut** [comment]
Thanks @Janisvb — on it now
