### ISSUE TITLE
Global's page title not using the `label` from the config

### ISSUE THREAD

**Issue by ChrisGV04** [payloadcms/payload#3524]
### Link to reproduction

Any Payload project with v2.0

### To Reproduce

Create any Global document and set the `label` property to any string. Here's an example:

```ts
import type { GlobalConfig } from 'payload/types';

export const HomePage: GlobalConfig = {
  slug: 'homepage',
  access: { read: () => true },
  label: { en: "Home page", es: "Inicio" },

  fields: [
    // ...
  ],
};
```

When you go to the Admin UI, the page for that global document uses the title from the `slug`, not from the actual `label`, but the correct title is displayed on the breadcrumbs.

<img width="642" alt="Screenshot 2023-10-09 at 1 30 00 p m" src="https://github.com/payloadcms/payload/assets/47041342/036ed1f1-63da-4a69-9e4e-5ebafdb79cb2">

### Describe the Bug

The title of the page should be what's set in the `label` property of the config for the global document and only fallback to the slug when no label is provided. That was the original behavior on v1.x

### Payload Version

v2.0.2

**Comment by jacobsfletch** [comment]
Hey @ChrisGV04 I should have this patched up shortly. Thanks for the report!
