### ISSUE TITLE
Cannot use properties from `group` as `defaultColumns`

### ISSUE THREAD

**Issue by ChrisGV04** [payloadcms/payload#3526]
### Link to reproduction

Any Payload project with v2.0

### To Reproduce

Create a simple collection that has a group of fields:

```ts
import type { CollectionConfig } from 'payload/types';

export const Testimonials: CollectionConfig = {
  slug: 'testimonials',
  access: { read: () => true },
  admin: {
    useAsTitle: 'author.name',
    defaultColumns: ['author.name'],
  },

  fields: [
    // ...
    {
      name: 'author',
      type: 'group',
      label: { en: 'Author', es: 'Autor' },
      fields: [
        {
          name: 'name',
          type: 'text',
          required: true,
          label: { en: 'Name', es: 'Nombre' },
        },
      ],
    },
  ],
};
```

### Describe the Bug

If you create a document using a group and want a nested property from that group to be shown in the collection table, it won't work. It shows blank spaces.

<img width="1325" alt="Screenshot 2023-10-09 at 1 37 08 p m" src="https://github.com/payloadcms/payload/assets/47041342/ea3acda9-8f6e-4ad7-8b87-ca9f2712bb32">

### Payload Version

v2.0.2

**Comment by jacobsfletch** [comment]
Hey @ChrisGV04 afaik this was never possible BUT we've been [actively discussing this](https://github.com/payloadcms/payload/discussions/1617). Does this sound like the same feature you're describing? Feel free to throw your support in there.

**Comment by ChrisGV04** [comment]
Hey @jacobsfletch! I'm sorry... I completely forgot about that discussion. I'm even subscribed to get email notifications about it 🤦🏻‍♂️ that's the exact feature I was describing

**Comment by jacobsfletch** [comment]
@ChrisGV04 it's all good!! 👍 I'm trying to catch back up on everything post 2.0.
