### ISSUE TITLE
Admin width not working properly

### ISSUE THREAD

**Issue by NardiniA** [payloadcms/payload#3527]
### Link to reproduction

https://github.com/NardiniA/qurno-payload

### To Reproduce

I used a text field and select field inside of a row and added a width property (as a percentage, e.g: 30%). However, this causes unusual rendering. 

### Describe the Bug

When using both fields inside the row at 50%, they are not in a row rather both take up the full width.

If only one field is specified then, for example: 30%, then its a row but it makes the incorrect field 30% although the correct field has a width: 30% property on it. 

The screenshot below shows the bug,

![bug-screenshot)](https://github.com/payloadcms/payload/assets/66033717/0346ab29-b793-4fa7-b62a-de9ea40d649f)

### Payload Version

2.0.0

**Comment by jacobsfletch** [comment]
Thanks for the report @NardiniA! I should have this patched up shortly.
