### ISSUE TITLE
`@payloadcms/live-preview` should not have a dependency on `react`

### ISSUE THREAD

**Issue by diesieben07** [payloadcms/payload#3528]
### Link to reproduction

https://github.com/payloadcms/payload/blob/040f3a34d187fff380a8002cf83b4ed693b29cca/packages/live-preview/package.json#L20

### To Reproduce

Install `@payloadcms/live-preview`.

### Describe the Bug

The framework-agnostic SDK for live-preview (`@payloadcms/live-preview`) has an unnecessary dependency on `react`. No react code is used within the SDK (or if there is and I could not find it, that should not be the case).

### Payload Version

@payloadcms/live-preview@0.1.1

**Comment by jacobsfletch** [comment]
I also found some disparities in the `@payloadcms/live-preview-react` package that have been fixed up here: https://github.com/payloadcms/payload/pull/3545
