### ISSUE TITLE
Nested blocks don't work in Lexical

### ISSUE THREAD

**Issue by DrMint** [payloadcms/payload#3531]
### Link to reproduction

Sorry I don't have the time tonight

### To Reproduce

Very excited about blocks in rich text. However, I quickly found something unexpected.
I'm trying to use a `transcript` block inside Lexical Rich Text field. The `transcript` block has only one `lines` field which is also a block field (which can contain `cue` or `line` blocks).
I can create a `transcript` block without problems, but I can't add blocks to its `lines` field.

I'm tried in a minimal setup using create-payload-app, changing the RTE to Lexical, and adding the following `transcript` block:

```ts
export const transcriptBlock: Block = {
  slug: "transcriptBlock",
  labels: { singular: "Transcript", plural: "Transcripts" },
  fields: [
    {
      name: "lines",
      type: "blocks",
      required: true,
      admin: { initCollapsed: true },
      blocks: [
        {
          slug: "lineBlock",
          labels: { singular: "Line", plural: "Lines" },
          fields: [
            {
              name: "content",
              type: "richText",
              required: true,
            },
          ],
        },
        {
          slug: "cueBlock",
          labels: { singular: "Cue", plural: "Cues" },
          fields: [
            {
              name: "content",
              type: "textarea",
              required: true,
            },
          ],
        },
      ],
    },
  ],
};
```

I also have a collection to test the RTE called `Posts`

```ts
export const Posts: CollectionConfig = {
  slug: "posts",
  admin: {
    useAsTitle: "title",
  },
  fields: [
    { name: "title", type: "text", required: true },
    { name: "content", type: "richText" },
  ],
};
```

And here's my payload.config.ts:

```ts
export default buildConfig({
  admin: {
    user: Users.slug,
    bundler: webpackBundler(),
  },
  editor: lexicalEditor({
    features: ({ defaultFeatures }) => [
      ...defaultFeatures,
      BlocksFeature({ blocks: [transcriptBlock, sectionBlock] }),
    ],
  }),
  collections: [Users, Posts],
  typescript: {
    outputFile: path.resolve(__dirname, "payload-types.ts"),
  },
  graphQL: {
    schemaOutputFile: path.resolve(__dirname, "generated-schema.graphql"),
  },
  db: mongooseAdapter({
    url: process.env.DATABASE_URI,
  }),
});

```

### Describe the Bug

The following is a recording on Firefox 118 (Linux). I tested on Chrome too, same problem.

[Screencast from 2023-10-09 20-46-47.webm](https://github.com/payloadcms/payload/assets/29893320/d66f005a-964e-4e48-9e0f-cb7c6ffb0dfa)

### Payload Version

2.0

**Comment by jmikrut** [comment]
Hey there! We are very excited about this feature too and we will 100% support nested blocks. Let us figure this out and we will get back to you as soon as we can.

**Comment by DrMint** [comment]
Hey James, thanks for the message! I was giddy all week waiting to show my editors the brighter future that awaits them, it's almost there, just this one thing that'll come useful in our use case. Oh well, 2.0 is pretty fire nonetheless, I hope you all proud!

**Comment by NardiniA** [comment]
I have also found this issue when trying to add a block that contains an array (of uploads). It won't let me add any rows at all in this case. 

Link to repo: [https://github.com/NardiniA/qurno-payload](https://github.com/NardiniA/qurno-payload). 

It is located in the Pages collection on the About Block.
