### ISSUE TITLE
Less space for buttons in image editor

### ISSUE THREAD

**Issue by dkirchhof** [payloadcms/payload#3539]
### Link to reproduction

/

### To Reproduce

Set your language to german and go to image editor page.

### Describe the Bug

The apply button of the image editor has not enough space in some languages like german. 

![image](https://github.com/payloadcms/payload/assets/2778643/b44ee16e-edbf-430b-a07d-d842f316b716)

### Payload Version

2.0.3

**Comment by jmikrut** [comment]
@JessChowdhury let's patch this one up. @dkirchhof good catch!
