### ISSUE TITLE
Missing UI Field Type

### ISSUE THREAD

**Issue by ninahorne** [payloadcms/payload#354]
# Documentation Issue

I'm not sure if this qualifies as a documentation issue, but this seemed like the best way to categorize it.

Basically, I am trying to implement a [UI field](https://payloadcms.com/docs/fields/ui), but I'm getting a type error that 'ui' is not a valid field type. 

here's the error: 

```
Type '"ui"' is not assignable to type '"number" | "text" | "email" | "textarea" | "checkbox" | "date" | "blocks" | "group" | "radio" | "relationship" | "array" | "richText" | "select" | "upload" | "code" | "point" | "row"'.ts(2322)

types.d.ts(83, 5): The expected type comes from property 'type' which is declared here on type 'Field'
(property) type: "ui"
```

Here's my package.json

```
  "dependencies": {
    "axios": "^0.23.0",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "payload": "^0.10.11",
    "styled-components": "^5.3.1",
    "webpack": "^5.58.2"
  },
```

**Comment by DanRibbens** [comment]
Hi @ninahorne
Give your payload version an update, current is `0.12.3`. We only introduced the `ui` field as of `0.12.x`. Let me know if you have any other troubles!

**Comment by ninahorne** [comment]
Thanks. I thought that might be the case, but I was having trouble updating so I thought it might have been on the latest version... Anyways, thanks!

**Comment by DanRibbens** [comment]
Can I help you get updated? What is going on when you try the latest?

**Comment by DanRibbens** [comment]
I'm closing this since we know it is a version issue. Please open another issue for any update errors if you're still having them. 

We're around to help!
