### ISSUE TITLE
Postgres: array field in tab not working

### ISSUE THREAD

**Issue by Janisvb** [payloadcms/payload#3541]
### Link to reproduction

https://github.com/janisvb/payload-reproduction/tree/tab-array

### To Reproduce

````
export PAYLOAD_DATABASE=postgres
yarn dev _community
````

### Describe the Bug

If you have an array field inside a tab, the data is saved correctly in the database, but is not returned in the admin interface or the API.

https://github.com/payloadcms/payload/assets/7983986/70342f30-d470-41e1-8560-4cd6eddcb7c4

### Payload Version

2.0.2

### Adapters and Plugins

db-postgres, bundler-webpack

**Comment by jmikrut** [comment]
Hey @Janisvb thanks for reporting! We're on it.
