### ISSUE TITLE
Image Cropping not Working within Upload Field

### ISSUE THREAD

**Issue by glettl** [payloadcms/payload#3542]
### Link to reproduction

/

### To Reproduce

Create Collection with upload relation
upload an image
link the image to the collection field
try to edit and crop the image

https://github.com/payloadcms/payload/assets/8844059/60af1a7c-107e-4170-9877-b1e376a638e9

### Describe the Bug

Image is not cropped when edit it through upload relation

### Payload Version

2.0.3

### Adapters and Plugins

db-mongodb, bundler-webpack

**Comment by JessChowdhury** [comment]
Hi @glettl - thanks for reporting! I'll be looking into this shortly.
