### ISSUE TITLE
webpack Warning with local API

### ISSUE THREAD

**Issue by ClementLaval** [payloadcms/payload#3569]
### Link to reproduction

-

### To Reproduce

-

### Describe the Bug

[Discord thread](https://discord.com/channels/967097582721572934/1160967236920561767)

Hi, 
I'm using a custom endpoint on my Product Collection and get this webpack warning:

![image](https://github.com/payloadcms/payload/assets/82887830/fa7134c0-d16c-4817-a30f-d4005975cead)

And here is my endpoint:

![image](https://github.com/payloadcms/payload/assets/82887830/bbb36dae-0677-4a24-b926-3b6339ef676f)

I can also add a remark: between v1 and v2 the type returned by "findById" changed from "GeneratedType" to "TypeWithID & Record<string, unknown>".
Doesn't it make more sense to return the "Product" type instead?

![image](https://github.com/payloadcms/payload/assets/82887830/2cd426c8-5415-41d9-a333-be8953dc65cd)

Thx !

### Payload Version

2.0.3

### Adapters and Plugins

"payload": "^2.0.3",  "@payloadcms/bundler-webpack": "^1.0.2",  "@payloadcms/db-mongodb": "^1.0.1",

**Comment by jmikrut** [comment]
Hey @ClementLaval — I just did some testing and for me, the `findByID` operation result is typed as expected:

![image](https://github.com/payloadcms/payload/assets/6651896/b065d926-3fcf-4b3c-8ed2-a847fed19669)

It might have to do with the fact that you are passing a `PAYLOAD_COLLECTIONS.PRODUCTS`.

See the example below:

```ts
const PAYLOAD_COLLECTIONS = {
  PAGES: 'pages',
}

 // this one works because we say `as const`
const PAYLOAD_COLLECTIONS_AS_CONST = {
  PAGES: 'pages',
} as const

export default buildConfig({
  onInit: async (payload) => {
    // Works (result typed as Page)
    const page = await payload.findByID({
      collection: 'pages',
      id: 123
    })

    // Doesn't work (can't infer based on PAYLOAD_COLLECTIONS.PAGES)
    const page2 = await payload.findByID({
      collection: PAYLOAD_COLLECTIONS.PAGES,
      id: 123
    })

    // Works (PAYLOAD_COLLECTIONS_AS_CONST defined as const) 
    const page3 = await payload.findByID({
      collection: PAYLOAD_COLLECTIONS_AS_CONST.PAGES,
      id: 123
    })
  },
  // rest of config here
})
```

I think this should resolve your issue. Let me know!

**Comment by ClementLaval** [comment]
@jmikrut You got it! It's ok after generating again my types ! 💪
Thank you !

**Comment by henrituan** [comment]
I got the same issue, and declaring Collection as const , or using string does not work for me.
What works for me is downgrading typescript package, `typescript@5.5.2` gives me issue, but `typescript@5.1.3` works fine.
