### ISSUE TITLE
Lexical - Text Cursor missing on Safari

### ISSUE THREAD

**Issue by leonardstruck** [payloadcms/payload#3591]
### Link to reproduction

/

### To Reproduce

-

### Describe the Bug

The text cursor doesn't show in new paragraphs. It also doesn't appear when you click on "Start typing..."

Seems to be an issue only for Safari (using Version 17.0 (19616.1.27.211.1)), other Browsers work as expected.

https://github.com/payloadcms/payload/assets/29303671/7456e360-12eb-4678-b4df-bd54ca21fdc0

### Payload Version

2.0.4

### Adapters and Plugins

db-mongodb, bundler-webpack, richtext-lexical

**Comment by patricsgamma** [comment]
Reproducible for me

#### ✔️ Work for Newline within same paragraph
<img width="500" alt="image" src="https://github.com/payloadcms/payload/assets/87857953/0d4e8777-c14d-4831-b0a2-5b429ad8b517">

#### ✔️ Works for any line with text
<img width="552" alt="image" src="https://github.com/payloadcms/payload/assets/87857953/93b48b6e-99e2-4897-9fc3-9d6fc6d596d8">

#### ❌ Fails for empty Paragraph lines

Tested with a older Safari version
Version 15.3 (17612.4.9.1.8)
