### ISSUE TITLE
Lexical RichText toolbar hidden behind modal window

### ISSUE THREAD

**Issue by patricsgamma** [payloadcms/payload#3596]
### Link to reproduction

-

### To Reproduce

We have a payload project which we upgraded to **Payload 2.0** and started to use the lexical RichText editor

### Code Setup
The config for `payload.config` therefore includes a config like shown below.
```
  editor: lexicalEditorConfig,

export const lexicalEditorConfig = lexicalEditor({
  features: () => [
    HeadingFeature({
      enabledHeadingSizes: ['h1', 'h2', 'h3'],
    }),
    ParagraphFeature(),
    BoldTextFeature(),
    ItalicTextFeature(),
    StrikethroughTextFeature(),
    UnderlineTextFeature(),
    SubscriptTextFeature(),
    SuperscriptTextFeature(),
    LinkFeature({}),
    IndentFeature(),
    AlignFeature(),
  ],
}) as RichTextAdapter;
```

Whe have then 2 collection configs

#### 1️⃣ First Collection
```
export const EduXmlSimulations: CollectionConfig = {
...
Fields: [
...
    {
      name: 'salesAndMarketingInformation',
      label: 'Sales And Marketing Information',
      type: 'relationship',
      required: true,
      relationTo: SalesAndMarketingInformations.slug,
    },
]
```

#### 2️⃣ Second Collection
```
export const SalesAndMarketingInformations: CollectionConfig = {
  slug: 'sales-and-marketing-informations',
  ....
  fields: [
  ...
    {
      name: 'marketingDescription',
      label: 'Marketing Description',
      type: 'richText',
      localized: true,
      required: true,
    },
 ]
```

### User Interaction

- Start the Payload project and log in.
- Go and select the 1️⃣ Collection, then select the option to **Create** a new document.
- Find the **Sales And Marketing Information** field that holds the 2️⃣ Collection as `relationship` and select ➕  `create new`
<img width="741" alt="image" src="https://github.com/payloadcms/payload/assets/87857953/dc900177-70a0-44a0-928e-cd100f53dddb">

- The second **Sales And Marketing Information** will now open as a modal window on top of the first one.
- If I then find the `Marketing Description` `richText` field, I can type text, but the Toolbar will be hidden behind the modal window.
<img width="671" alt="image" src="https://github.com/payloadcms/payload/assets/87857953/2dd51543-7ff6-4799-a795-0bc880f3217e">

### Describe the Bug

As mentioed in To **Reporduce**, the `richText` toolbar is behind modal creation windows.

### Payload Version

^2.0.3

### Adapters and Plugins

```
"@payloadcms/bundler-webpack": "^1.0.2",    
"@payloadcms/db-mongodb": "^1.0.2",     
"@payloadcms/plugin-cloud-storage": "^1.0.19",    
"@payloadcms/plugin-sentry": "^0.0.4",     
"@payloadcms/richtext-lexical": "^0.1.4"
```

**Comment by AlessioGr** [comment]
Fixed by #3615
