### ISSUE TITLE
Lexical Richtext toolbar options failing on Firefox

### ISSUE THREAD

**Issue by patricsgamma** [payloadcms/payload#3598]
### Link to reproduction

- 

### To Reproduce

We have a payload project which we upgraded to Payload 2.0 and started to use the lexical RichText editor.

The config for payload.config therefore includes a config like shown below.

```
  editor: lexicalEditorConfig,

export const lexicalEditorConfig = lexicalEditor({
  features: () => [
    HeadingFeature({
      enabledHeadingSizes: ['h1', 'h2', 'h3'],
    }),
    ParagraphFeature(),
    BoldTextFeature(),
    ItalicTextFeature(),
    StrikethroughTextFeature(),
    UnderlineTextFeature(),
    SubscriptTextFeature(),
    SuperscriptTextFeature(),
    LinkFeature({}),
    IndentFeature(),
    AlignFeature(),
  ],
}) as RichTextAdapter;
```

### Issue
If I write a paragraph within the lexical RichText field and then try to assign any paragraph styles with 🔥🦊 Firefox. 
`Heading`, `BlockQuote` or `Alignments` all don't work 🐛 
<img width="600" alt="image" src="https://github.com/payloadcms/payload/assets/87857953/7f859928-0401-420c-a386-96e101f96dcc">

### Limit of the issue
If I use a different Browser to apply them, Firefox does correctly display them ✔️ 
<img width="600" alt="image" src="https://github.com/payloadcms/payload/assets/87857953/d54fe1c2-96c7-408b-9bcc-8a7d3cf1fc77">

### Results per browser
**Chrome** Version 117.0.5938.149 (Official Build) (arm64)
✔️ Setting Paragraph style works. 
✔️ Displaying Paragraph styles works.

**Safari** Version 15.3 (17612.4.9.1.8)
✔️ Setting Paragraph style works. 
✔️ Displaying Paragraph styles works.

**Firefox**  118.0.1 (64-bit)
❌ Setting Paragraph style fails.
✔️ Displaying Paragraph styles works.

### Payload Version

^2.0.3

### Adapters and Plugins

```
"@payloadcms/bundler-webpack": "^1.0.2",
"@payloadcms/db-mongodb": "^1.0.2",
"@payloadcms/plugin-cloud-storage": "^1.0.19",
"@payloadcms/plugin-sentry": "^0.0.4",
"@payloadcms/richtext-lexical": "^0.1.4",
```

**Comment by AlessioGr** [comment]
Fixed by #3615
