### ISSUE TITLE
Race condition with database transactions when multiple queries are issued through GraphQL

### ISSUE THREAD

**Issue by diesieben07** [payloadcms/payload#3605]
### Link to reproduction

https://github.com/diesieben07/payload-transactions-demo/tree/repro-graphql-multi-query

### To Reproduce

- Make sure database transactions are in use
- Create two globals, allow read access from everyone for both
- Log in to the Admin and save both globals
- Log out of the Admin (!)
- Attempt to query both globals in one GraphQL query

The above repository allows you to do this easily. Simply run `docker compose up --attach payload` and you will get a running Payload instance plus a MongoDB ReplicaSet in Docker. Create a dummy user in the Admin, save the Globals and log out. Go to the GraphQL Playground and run the following query:
```gql
query test {
  Global1 {
    testText
  }
  Global2 {
    testText
  }
}
```
You will see that only one of the queries succeeds and you get an internal server error. 
The repository uses `patch-package` to add some trace logging to see where transactions are begun and committed.
I would recommend to disable Schema-Polling in the GraphQL-Playground settings to avoid spamming the logs from Schema-Introspection requests.
If you look at the logs, you will see that Payload creates _two_ transactions, but then keeps using only one of them, attempting to commit and end it twice.

### Describe the Bug

Payload Transactions are bound to the PayloadRequest object. However, multiple operations can happen during one request. This leads to a race condition, because _all_ operations will try to create and commit the transaction as well as end the session.
If you are unlucky, the "asynchronous Gods" will decide that one operation tries to commit on a session which has already been ended.
If you are a little more lucky (I guess), things will "appear to work", but you're not really getting the benefit of transactions, because not everything will or will not be committed/rolled back.

Either Payload should reliably create a new transaction for every operation or it should use one transaction for the whole request, but only actually commit it at the end.

### Payload Version

2.0.4

### Adapters and Plugins

@payloadcms/db-mongodb@1.0.3

**Comment by xHomu** [comment]
This seems to be what's causing our payload server to crash in production for very large GraphQL queries, did you get the "rollbackTransaction called when no transaction exists" error too because of the race condition?

**Comment by diesieben07** [comment]
> did you get the "rollbackTransaction called when no transaction exists" error too because of the race condition?

Yes, this warning log also happens immediately before "TypeError: Cannot read properties of undefined" when this issue occurs.

**Comment by jmikrut** [comment]
Hey all, just quick update. This is first up on our radar to investigate this coming week. Will report back soon!

**Comment by xHomu** [comment]
The latest PayloadCMS release `2.0.10` seems to have shipped some changes to address this, @DanRibbens?

**Comment by xHomu** [comment]
#3795 didn't seem to completely resolve the race condition issue with mongodb graphql transactions:

<img width="913" alt="image" src="https://github.com/payloadcms/payload/assets/84349818/b1d30122-dbad-4dee-a081-087bfa93debb">

**Comment by denolfe** [comment]
@DanRibbens Re-validate fix

**Comment by Blankeos** [comment]
Same error here. For me it seems to only happen when I query on the clientside with GraphQL. I use the URQL client. When I query with SSR (getServerSideProps, etc.), it works just fine, no errors, doesn't crash my node server.

![image](https://github.com/payloadcms/payload/assets/38070918/86ab2063-4fbc-469f-b262-3f915f318055)

**Comment by xHomu** [comment]
I'm pretty sure it's any time when you bundle multiple queries in a single graphql request.

**Comment by Blankeos** [comment]
@xHomu Oh yeah you're right. Scratch what I said earlier. Thanks for this. Yeah just confirmed again it crashes when I bundle two queries in one request lol.

**Comment by revnelson** [comment]
Getting this a bunch with 2.0.14. All my gql requests are single queries. Downgrading to 2.0.13 (which also requires downgrading richtext-lexical from 0.1.16 to 0.1.15) fixes it, even when keeping the latest db-mongo v1.0.5

**Comment by xHomu** [comment]
What we need is a config that let us disable transactions altogether for Mongo.
