### ISSUE TITLE
Sidebar select field styling bug

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3610]
### Link to reproduction

/

### To Reproduce

1. Add a select field (or relation in my case) to the sidebar
2. Open it

### Describe the Bug

As you can see the content of the sidebar does not take up the full height. This the select field options to be only partially visible + it causes a scrollbar to appear:

![Screenshot 2023-10-12 at 20 13 25](https://github.com/payloadcms/payload/assets/52583398/50aff816-a4fa-4391-823f-16809b2b5b92)

### Payload Version

2.0.4

### Adapters and Plugins

mongo, vite

**Comment by jacobsfletch** [comment]
Hey @silveltman this should have been fixed with https://github.com/payloadcms/payload/issues/3639

Are you running the latest version of Payload?

**Comment by silveltman** [comment]
I am now, fixed ✅ 👌
