### ISSUE TITLE
[plugin-cloud]: Getting an `unlink` error after upgrade to Payload 2.0

### ISSUE THREAD

**Issue by thompsonsj** [payloadcms/payload#3614]
Happens when uploading any image. Does not seem to impact the upload itself. Exiting and refreshing the upload collection shows that the image was uploaded complete with `imageSizes` transforms...etc.

Anyone else getting this error? I'm on the Payload Cloud service using this plugin.

![Screenshot 2023-10-12 at 14 09 37](https://github.com/payloadcms/plugin-cloud/assets/44806974/6b2b19c7-2db3-4115-a84a-3d09fa0c08f8)

**Comment by kariyngva** [comment]
Hey @denolfe, my coworker and I are also seeing this `unlink` issue. Did you manage to reproduce?

**Comment by denolfe** [comment]
@thompsonsj @kariyngva Attempting to recreate this morning.

**Comment by denolfe** [comment]
Thank you for the reports! Released in [v2.0.12](https://github.com/payloadcms/payload/releases/tag/v2.0.12)

**Comment by thompsonsj** [comment]
Thanks @denolfe ! Error no longer appears.
