### ISSUE TITLE
Nested doc plugin mix doc_versions id

### ISSUE THREAD

**Issue by ClementLaval** [payloadcms/payload#3625]
### Link to reproduction

none

### To Reproduce

none

### Describe the Bug

A quick video to show you an issue I found with the nested doc plugin.
It seems that page_versions take the wrong parent ID while it is saving, as nested-doc plugin has is own "parent" key, I suppose that versionning use the wrong key. Or it's maybe a total another problem, I don't know.

https://github.com/payloadcms/payload/assets/82887830/ca7c67f8-6324-46ee-82bc-c81c384c46bd

The home page ID: 6528f141ff8c43627a1f0c7b
My last record in page_versions, as you can see, it's the home page ID, but with the wrong content.

![image](https://github.com/payloadcms/payload/assets/82887830/9a040d7c-98ef-4bea-96d8-91c4475d44a3)

![image](https://github.com/payloadcms/payload/assets/82887830/c8fbefee-a0cf-4ba2-9d13-a9694759377d)

### Payload Version

2.0.4

### Adapters and Plugins

"@payloadcms/db-mongodb": "^1.0.3", "@payloadcms/bundler-webpack": "^1.0.3",

**Comment by ClementLaval** [comment]
I updated to 2.0.5 after the post, I can't reproduce this issue actually, do you fixed it with the last version?

**Comment by jmikrut** [comment]
It's possible! We have been making moves in all sorts of places. Let's close this and if it happens to you again, we can re-open. Thank you Clement!
