### ISSUE TITLE
Payload 2.0 Cannot Remove Block with Nested Blocks

### ISSUE THREAD

**Issue by tophermurphy** [payloadcms/payload#3635]
### Link to reproduction

https://github.com/tophermurphy/payload-2-bug

### To Reproduce

 have attempted to use the forked community branch but could not get this to work. I am using the MongoDB via the Docker Compose file. I have also tried a separate PostgreSQL DB.

1. Create a new Page in Pages collection.
2. Add at least two new Section Blocks, with one nested block. Either Paragraph or Heading Block.
3. Save the Page.
4. Remove a Section Block.
5. Save the Page.
6. Error message appears and the Block reappears on refresh.

### Describe the Bug

I cannot remove a block with nested blocks. When you try to remove a block there is a casting error. I have tried this with both MongoDB and PostgreSQL DB.

### Payload Version

Payload 2.0.5

**Comment by sburgpit** [comment]
+1  I'm facing the same problem. Error: `duplicate key value violates unique constraint "tasks_blocks_exercice_read_pkey"`

**Comment by JarrodMFlesch** [comment]
This has been fixed as of `v2.0.6`, run `yarn add payload` to receive other patch fixes and to get the latest version.

**Comment by tophermurphy** [comment]
@JarrodMFlesch and @JessChowdhury  Thanks so much!
