### ISSUE TITLE
How to use vite is not documented (apart from a brief mention in a video)

### ISSUE THREAD

**Issue by artemis-prime** [payloadcms/payload#3644]
# Documentation Issue

How to use vite needs to be documented.

## Additional Details

1. Install  @payloadcms/bundler-vite,
2. import it into the payload.config.ts,
3. replace the webpack bundler with viteBundler()
4. ... anything else?

**Comment by barthy-koeln** [comment]
Here's an entire page about vite: https://payloadcms.com/docs/admin/vite

And a more general page about bundlers: https://payloadcms.com/docs/admin/bundlers

Are you looking to do anything not mentioned in there?

**Comment by jmikrut** [comment]
Hey @artemis-prime — we are happy to expand documentation if something is missing but I would also like to know what you need to know outside of what is already documented so we can prioritize.

@barthy-koeln — thank you for chiming in here! I appreciate it!

**Comment by ssyberg** [comment]
@jmikrut I think this was closed prematurely, the docs seem to be contradictory / incomplete ☝🏼

**Comment by jmikrut** [comment]
Hey @ssyberg let me reopen this and take a look.

Thanks for the heads-up!

**Comment by JarrodMFlesch** [comment]
Hey @ssyberg the docs have been updated, see here: https://payloadcms.com/docs/admin/vite
