### ISSUE TITLE
custom-server: Next.js middleware does not work in production

### ISSUE THREAD

**Issue by r1tsuu** [payloadcms/payload#3653]
### Link to reproduction

https://github.com/r1tsuu/payload-custom-server-middleware/tree/middleware-custom-server/examples/custom-server

### To Reproduce

See src/middleware.ts, should call console.log on every Next.js request and it works in development mode.
```ts
import type { NextRequest } from 'next/server'

// This function can be marked `async` if using `await` inside
export function middleware(request: NextRequest): void {
  // eslint-disable-next-line no-console
  console.log('HELLO FROM NEXT MIDDLEWARE', request.url)
}

// See "Matching Paths" below to learn more
export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
}
```
Production
Run 
```sh
yarn build
yarn serve
```
Console doesn't called

I fixed it with just using `next build` for build instead of code in server.ts
To run with fixed issue:
```sh
yarn build-fixed
yarn serve
```
Console shows:
<img width="546" alt="image" src="https://github.com/payloadcms/payload/assets/64744993/25c3166a-464c-40f8-a19b-ec6ccce4ef22">

### Describe the Bug

Next middleware does not work with custom server in production mode. Without this we can't use libs like next-intl, next-auth etc

Is there a reason why custom-server template doesn't use `next build` by default? seems like everything is ok without it

### Payload Version

2

**Comment by jmikrut** [comment]
Hey @r1tsuu — good questions. I have no idea why Next is not building middleware with the pattern that we use to build, but I can tell you why we do it like we do.

If you want to build your Next site and statically generate pages with content coming directly from the Payload API, you need to have the Payload server _**running**_ to accept those fetches by your Next code.

This might not apply to you I take it. We will see if we can get middleware to work some other way with the way we're building, but yes, you could adjust your script to just start Payload first, and then build Next as you've done in a separate script. This approach might work for all cases, too, which in that case, I think we should update our boilerplate.

We'll keep this open until we can do some recon there.

Thank you!

**Comment by JarrodMFlesch** [comment]
Hey @r1tsuu I was able to replicate and fix. The example has been updated in this [PR](https://github.com/payloadcms/payload/pull/3771).

If you want to implement the fix on your end, you need to edit your server file with [this change](https://github.com/payloadcms/payload/pull/3771/files#diff-33de1d1b2e358d4786fae6fbd8c623085150e17ab6cf2330e2bfdf31661342b1R32)

**Comment by Pakue95** [comment]
I've just ran into the same issue while using the template/website project. It might be a good idea to apply these changes to the templates as well. 
For me the fix was to only remove the trailing "/" in server.ts. 

Happy to do a PR for the changes.
