### ISSUE TITLE
Actions like delete seem to be missing from mobile UI

### ISSUE THREAD

**Issue by joas8211** [payloadcms/payload#3663]
### Link to reproduction

https://github.com/payloadcms/payload

### To Reproduce

1. Create project with Payload 2.0.6.
2. Create first user.
3. Open a document, user for example.
4. Resize browser window small.
5. Observe that action menu (vertical "...") disappears.

### Describe the Bug

Medium size viewport:
![](https://github.com/payloadcms/payload/assets/6217024/00a4b5c8-c1fd-466c-9cfb-16d5dd023611)

Small viewport:
![](https://github.com/payloadcms/payload/assets/6217024/072aa442-3ac1-485d-9c41-6c07f867aeb1)

I can't find any way to delete a document in viewports with 1024px of width or smaller.

### Payload Version

2.0.6

### Adapters and Plugins

@payloadcms/bundler-webpack@1.0.3, @payloadcms/db-mongodb@1.0.3, @payloadcms/richtext-slate@1.0.5

**Comment by jacobsfletch** [comment]
@joas8211 this is fixed and will go out in the next release 👍
