### ISSUE TITLE
lexical large block scroll bug

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3683]
### Link to reproduction

/

### To Reproduce

1. Create a payload admin
2. add a lexical richtext field with the following config:
```
    {
      name: 'richtext',
      type: 'richText',
      editor: lexicalEditor({
        features: ({ defaultFeatures }) => [
          ...defaultFeatures,
          BlocksFeature({
            blocks: [Cta],
          }),
        ],
      }),
    },
```
3. Make sure the block you use is a large block that exceeds the viewport height
4. add the block and then scroll up/down

### Describe the Bug

The scrolling is bugging. It only happens when adding the large block. One it is closed and then opened again the scrolling behaves normal.

https://github.com/payloadcms/payload/assets/52583398/1df4fb5f-c07e-42ae-a871-c07c76dbeaf0

### Payload Version

2.0.7

### Adapters and Plugins

lexical 0.1.11

**Comment by AlessioGr** [comment]
What a weird bug. This seems to only happen when you have another lexical sub-editor in the Blocks node of your lexical editor. @silveltman does that apply for you?

Note to myself: it only seems to happen when the `useField` hook is called in the **sub**-lexical-editor

**Comment by silveltman** [comment]
I tested it with a completely empty block, just a load of textarea's. Same problem, but way less frequently scrolling down:
https://github.com/payloadcms/payload/assets/52583398/1e31a4da-2294-4b5d-93e4-0b48a4960072

I also noticed that when clicking esc on my keyboard it also scrolls down. Can this maybe have something to do with it?
