### ISSUE TITLE
ERROR (payload): NotFound: The requested resource was not found

### ISSUE THREAD

**Issue by exponent42** [payloadcms/payload#369]
# Bug Report

Pages collection not found inside Admin (404) despite there being documents inside the collection, visible inside MongoDB Compass / Atlas. 

## Expected Behavior

Pages collection should return the documents in the collection as normal (200). 

## Current Behavior

E.g. Pages collection appear blank inside Payload Admin and returns 404:
`http://localhost:3000/api/pages?locale=en&depth=1&page=1&where[title][like]=`

```json
{"errors":[{"message":"The requested resource was not found."}]}
```

`http://localhost:3000/api/pages` same thing. 

...despite there being documents inside MongoDB.

## Steps to Reproduce

Unknown, a content editor reported the issue. Everything was working well prior to this. May have been caused by a content editor though can't tell for certain as no changes where committed in the days leading the issue. 

Wondering if this is something obvious encountered before

Payload Version: 0.12.3

**Comment by jmikrut** [comment]
Hey @exponent42 - I think this probably has to do with data or custom functionality. 

First, try changing the page URL param to a different page, (2, 3, etc.) so you can retrieve a different set of page results. Can you get any to come back?

Next, does your Pages collection feature any custom hook or fields with hooks? If you are auto-populating data or searching for other docs within hooks, and a hook tries to find a doc but fails, you might see an error like you are describing. 

If this is the case, make sure you wrap your hook functions in try / catch clauses to swallow a Not Found error.

Last thing. Maybe try and update Payload to use the latest beta. 

Let me know!

**Comment by exponent42** [comment]
Hi James, thanks for this - I apologise as was off for a couple of days. 

> Maybe try and update Payload to use the latest beta.

Just updated to 0.13.2 now and the no longer an issue - thanks very much :) 

Really appreciate it.
