### ISSUE TITLE
Breadcrumbs field is stored in the database, contrary to what the docs say

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#3691]
The plugin's README states the following about the breadcrumbs field:

> It does not store any data in the database, and instead, acts as a virtual field which is dynamically populated each time the document is loaded.

However, in MongoDB Compass, I can see that there *is* an actual breadcrumbs field stored:

![image](https://user-images.githubusercontent.com/5570098/233049128-f9a9f11f-0bc5-4cb7-b4f7-96ca13f016c4.png)

Reproduction:

1. Clone my repo at this branch https://github.com/hdodov/payload/tree/nested-docs-breadcrumbs
2. Run `yarn dev _community`
3. Posts will be auto-generated (in `test/_community/config.ts`)
4. You'll be able to inspect the database and see the breadcrumbs field

**Comment by DanRibbens** [comment]
Thanks @MarkAtOmniux!
