### ISSUE TITLE
Can't update collections having password field.

### ISSUE THREAD

**Issue by subasshrestha** [payloadcms/payload#370]
# Bug Report

We can't update field named with password.

## Expected Behavior
The password field should be updated.

## Current Behavior
Shows error like: doc.setPassword is not a function

## Steps to Reproduce

1. Create a normal collection having a field password
2. Add this collection in config
3. Run project and create a data in this collection.
4. Then, try to update the values, you will get error.

**Comment by jmikrut** [comment]
Hey @subasshrestha - thanks for pointing this out. The `password` field name is internally reserved by Payload, so this is sort of expected not to work - but it might not need to be that way. We could only reserve that field name for auth-enabled collections instead.

Out of curiosity, can I ask what you’re using that field for?

**Comment by subasshrestha** [comment]
I am trying to separate admin users and normal users by two different collections.
Since, password field is reserved, I will rename this field in normal user collections.

**Comment by jmikrut** [comment]
@subasshrestha —

You should use the Payload `auth` functionality on _**both**_ your admin and normal users' collections. With Payload, you can have more than one auth-enabled collection. 

Make sure to never store user `password`s in plaintext in the database - using Payload's built in methods will be much easier for you - and more secure. 

Can you do that? Or am I misunderstanding?

**Comment by subasshrestha** [comment]
I already have login/signup functionality implemented for normal user. So, if i use collection auth and create a user from admin panel, i can't login on existing route.

**Comment by JarrodMFlesch** [comment]
@subasshrestha that is true, you would not be able to use the existing routes that you have created. However, you could use the payload routes that are automatically generated for you when you enable auth on a collection.

Enabling auth on a collection, will create routes for you so you can perform authentication easily. Login, Logout, Refresh routes can be found [here](https://payloadcms.com/docs/authentication/operations#login).

Along with those, it also enables forgot-password and reset-password routes, which are pretty handy and all you need to do is provide a transport which can be found [here](https://payloadcms.com/docs/email/overview)

> So, if i use collection auth and create a user from admin panel, i can't login on existing route.

If you created 2 collections with the following slugs `normal-users` & `admin-users`, you would be able to use the auto-generated payload routes like so

## Normal users
- `domain.com/api/normal-users` (A POST request will create a new user of this collection type, when you send `password` & `email` in the body of the request)
- `domain.com/api/normal-users/login`
- `domain.com/api/normal-users/logout`

## Admin users
- `domain.com/api/admin-users` (A POST request will create a new user of this collection type, when you send `password` & `email` in the body of the request)
- `domain.com/api/admin-users/login`
- `domain.com/api/admin-users/logout`

Maybe I am misunderstanding what you are attempting to accomplish. But I am just trying to save you from doing extra work than you need to, where payload already does what you are looking to do with your custom routes!

**Comment by subasshrestha** [comment]
Okay, I got it. Thank you all for your support.
