### ISSUE TITLE
Live editor shadow bug + ugly

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3704]
### Link to reproduction

/

### To Reproduce

1. Create a payload admin
2. enable live editing
3. go to a page and live edit

### Describe the Bug

First, in light mode the shadow is way too big and therefore quiet ugly:
![Screenshot 2023-10-17 at 10 35 37](https://github.com/payloadcms/payload/assets/52583398/782fbac6-bb90-4db3-bd9b-bfdbcc74ee10)

Second, for vw 1024px and below the shadow is not needed:
![Screenshot 2023-10-17 at 10 36 28](https://github.com/payloadcms/payload/assets/52583398/80d17d8a-6404-4837-98e2-b20ec813b5cb)
n mo

### Payload Version

2.0.7

**Comment by jacobsfletch** [comment]
Yep this has been on our radar @silveltman, we'll get these styles cleaned up. Thanks for the report as always 👍
