### ISSUE TITLE
Unable to start new project on M1 / arm

### ISSUE THREAD

**Issue by alexander-chi** [payloadcms/payload#371]
When trying to start a new project on an M1 Mac I receive the following error

/Users/alex/Git/starlink-mapper/node_modules/sharp/lib/constructor.js:32
  throw new Error(error);
        ^
Error: 
Something went wrong installing the "sharp" module

dlopen(/Users/alex/Git/project_name/node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: /opt/homebrew/opt/openexr/lib/libIlmImf-2_5.25.dylib
  Referenced from: /usr/local/lib/libvips-cpp.42.dylib
  Reason: image not found

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

As far as I can tell this is because it depends on sharp v0.28.xx which does not have prebuilt binaries for M1,

Upgrading to use sharp v0.29.0 would resolve this issue as it has prebuilt binaries.

**Comment by denolfe** [comment]
Thanks for the report @alexander-chi. We'll look at getting this upgraded.

**Comment by jmikrut** [comment]
Hey @alexander-chi — we just deployed a new version with an updated Sharp - `0.13.3`.

Give it a shot!

**Comment by alexander-chi** [comment]
All working for me now!  Thanks for the quick response.
