### ISSUE TITLE
Live preview on globals doesn't show anything

### ISSUE THREAD

**Issue by wSzki** [payloadcms/payload#3715]
### Link to reproduction

https://github.com/wSzki/payload_livepreview_bug

### To Reproduce

- `yarn dev`
- navigate to http://localhost:3000/admin/globals/TestGlobal/preview

![livepreviewbug](https://github.com/payloadcms/payload/assets/59784520/e28f7a22-15f9-4c9b-ab2b-db359fe31a6c)

### Describe the Bug

Hello,

Live preview isn't showing anything on globals
Collections work fine and shows an error if the URL to the front end is invalid.

No error logs are shown in the server or web browser's console

Noticed the issue on 2.0.7

### Payload Version

2.0.9

### Adapters and Plugins

default plugins from blank template

**Comment by jacobsfletch** [comment]
@wSzki got this fixed with #3801. It will go out in the next release. Thank you for reporting this 👏 there's a test written to prevent future regression as well.
