### ISSUE TITLE
Next build failing for website template

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#3723]
### Link to reproduction

.

### To Reproduce

- `npx create-payload-app -t website -n recreate-issue`
- `yarn build`

### Describe the Bug

Unused @ts-expect-error directive when running `yarn build`. _However_, this error does not show in the IDE. In fact, the IDE  shows an error when you remove it.

<img width="603" alt="CleanShot 2023-10-17 at 20 06 49" src="https://github.com/payloadcms/payload/assets/65888/14cab9c7-de7e-48c2-8186-c51c4663863c">
<img width="520" alt="CleanShot 2023-10-17 at 20 11 57" src="https://github.com/payloadcms/payload/assets/65888/26598228-4c92-4b92-9851-d273718447e0">
<img width="1012" alt="CleanShot 2023-10-17 at 20 12 09" src="https://github.com/payloadcms/payload/assets/65888/506fa0be-0bf2-4fa8-bd22-931e2a5fa460">

### Payload Version

2.0.10

### Adapters and Plugins

db-mongodb, bundler-webpack

**Comment by jacobsfletch** [comment]
@kalon-robson your PRs are potentially the fix for this although when I pulled them down I was seeing other unexpected ts errors

**Comment by kalon-robson** [comment]
Hi @jacobsfletch The two PR's do fix this by adding the @types/react to tsconfig path.

I however, couldn't find the other errors, both lint and build work on both templates. Could you point me to a specific file and line for one of the errors.

- Kalon

**Comment by denolfe** [comment]
Resolved by #3652
