### ISSUE TITLE
Disabling GraphQL on a global causes Payload to generate an invalid GraphQL schema

### ISSUE THREAD

**Issue by diesieben07** [payloadcms/payload#3727]
### Link to reproduction

https://github.com/diesieben07/payload/tree/issue/disable-graphql

### To Reproduce

Set `graphQL: false` on a global

### Describe the Bug

When GraphQL is disabled, Payload generates an invalid GraphQL schema for the `Access` type. It creates a field for the global in the Access type, but sets its type to `null`, which GraphQL then rightfully complains about.

### Payload Version

2.0.10

### Adapters and Plugins

n/a

**Comment by DanRibbens** [comment]
This will be released in 2.0.11
