### ISSUE TITLE
Unable to delete media that isn't stored locally

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#373]
# Bug Report

I'm trying to delete a file but it's crashing as it's trying to delete it locally off the file system. I'm getting the following error:

➤ YN0000: ErrorDeletingFile: There was an error deleting file.
➤ YN0000:     at new ExtendableError (/Users/richard/Code/Brightvision/brightvision/node_modules/payload/src/errors/APIError.ts:26:11)
➤ YN0000:     at new APIError (/Users/richard/Code/Brightvision/brightvision/node_modules/payload/src/errors/APIError.ts:43:5)
➤ YN0000:     at new ErrorDeletingFile (/Users/richard/Code/Brightvision/brightvision/node_modules/payload/src/errors/ErrorDeletingFile.ts:6:5)
➤ YN0000:     at /Users/richard/Code/Brightvision/brightvision/node_modules/payload/src/collections/operations/delete.ts:113:10

I've tracked it down, as a result of this method returning true:

https://github.com/payloadcms/payload/blob/a0fb48c9a37beceafc6f0638604e9946d0814635/src/uploads/fileOrDocExists.ts#L9

unlink() is called on a file that doesn't exist here:

https://github.com/payloadcms/payload/blob/a0fb48c9a37beceafc6f0638604e9946d0814635/src/collections/operations/delete.ts#L109

## Expected Behavior

Document should be deleted without attempting to unlink the file that doesn't exist.

## Detailed Description

0.13.0

Thanks for fixing the duplicate upload bug though! That seems to be working for me.

**Comment by jmikrut** [comment]
Thanks Richard - good catch! `0.13.2` on its way with a fix right now! Sorry about that!
