### ISSUE TITLE
Duplicate item results into primary key conflict when using Blocks [Postgres adapter]

### ISSUE THREAD

**Issue by DennisSnijder** [payloadcms/payload#3734]
### Link to reproduction

https://github.com/DennisSnijder/payload-bug-report

### To Reproduce

1. Run the payload-bug-report project using `docker compose up`.
2. Create a new post with at least 1 block in the "Layout" field.
3. Duplicate the created post using the UI

Results into:
```sh
[13:59:21] ERROR (payload): error: duplicate key value violates unique constraint "posts_blocks_example_block_pkey"
```

### Describe the Bug

When using postgres and using Block fields in Postgres, duplicating an item results into a primary key error. Likely due to the frontend(?) generating id's for the blocks and re-using those id's when duplicating the post (and not re-generating the id's).

### Payload Version

2.0.10

### Adapters and Plugins

Postgres DB adapter

**Comment by DanRibbens** [comment]
This can be reproduced on `main` right now from the `dev fields` by trying to duplicate the seeded blocks collection.
