### ISSUE TITLE
Migration Draft versions not working

### ISSUE THREAD

**Issue by matteo-naif** [payloadcms/payload#3735]
### Link to reproduction

-

### To Reproduce

I followed the documentation of the page https://github.com/payloadcms/payload/releases/tag/v2.0.0.

```
1. First, make sure you have a payload npm script in your package.json

{
  "scripts": {
    "payload": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload"
  }
}
Adjust the PAYLOAD_CONFIG_PATH to point to your Payload config file if necessary.

2. Create a migration, using the new Payload migration API

npm run payload migrate:create --file @payloadcms/db-mongodb/versions-v1-v2
The above command will output a migration file into your ./src/migrations folder (default migrations location). It contains a migration script to automatically add a latest: true flag to each of your newest drafts, for all draft-enabled collections. It works out of the box!

3. Run migrations

From there, you need to run migrations. Run the following command to execute your new migration:

npm run payload migrate
```

The migration file contains the following code:

```ts
// src/migrations/20231018_131005__payloadcms_db_mongodb_versions_v1_v2.ts

import {
  MigrateUpArgs,
  MigrateDownArgs,
} from "@payloadcms/db-mongodb";

export async function up({ payload }: MigrateUpArgs): Promise<void> {
  // Migration code
};

export async function down({ payload }: MigrateDownArgs): Promise<void> {
  // Migration code
};

```

And when I run `npm run payload migrate` nothing happens because in the UI I'm seeing the docs of the collections.

If I try to change the draft value in the collection config to false, I see all the docs in the UI.

### Describe the Bug

I followed the migration tutorial but I can't see the docs in the UI.
I use NPM to install packages.

### Payload Version

2.0.10

### Adapters and Plugins

db-mongodb,  bundler-webpack

**Comment by denolfe** [comment]
It looks like there are differences in how each package manager finds the predefined migration that need to be accounted for. 

The current workaround is to copy the contents of this file into your migration: https://github.com/payloadcms/payload/blob/main/packages/db-mongodb/predefinedMigrations/versions-v1-v2.js

**Comment by matteo-naif** [comment]
I imported the script in the migration file and it works, thanks!

**Comment by denolfe** [comment]
More reports of this not working properly with npm. Need to look into this more.

**Comment by ZdenT** [comment]
It works with `npm run payload migrate:create -- --file @payloadcms/db-mongodb/versions-v1-v2`.  Focus on "--" before file argument.

**Comment by denolfe** [comment]
Looks like this is just a limitation of `npm` requiring `--` in order to pass additional args. Not sure what we can do here beyond documenting it.

<img width="841" alt="CleanShot 2023-11-03 at 18 56 47" src="https://github.com/payloadcms/payload/assets/65888/f5c58186-3c35-4c29-aa73-340ec34ad633">

**Comment by denolfe** [comment]
`migrate:create` will now also check the migrationName for the package prefix and search for the predefined migration that way.

**Comment by cbratschi** [comment]
@denolfe could you please update the release notes (https://github.com/payloadcms/payload/releases/tag/v2.0.0)? I was just getting this issue and then found this ticket.

**Comment by denolfe** [comment]
@cbratschi With the next release, the `--` workaround for npm will not be necessary
