### ISSUE TITLE
doc created with custom ID cant be deleted when field removed

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3741]
### Link to reproduction

/

### Describe the Bug

Docs (images in my case) are not deleted when a custom ID field is removed after the doc has been created with that custom id field. 

I think the remove operation does not know what image to remove, because the id is not there anymore. But this seems weird, because old fields that are removed from the config stay stored right?

### To Reproduce

1. Set a custom id field on my an uploads collection:
```
{
  name: 'id',
  type: 'text',
},
```

2. Create assets (in my case via rest api)
3. remove the custom id field from the collection config
4. try to remove the images via de admin panel.

(I can provide better explanation and reproduction if needed, but it's late here now haha)

### Payload Version

2.0.8

**Comment by silveltman** [comment]
I used the custom ID field because I could not get an image uploaded via rest with a custom id. My function:
```
let formData = new FormData();
  formData.append('file', file, doc.filename);
  formData.append('alt', doc.alt);
  formData.append('id', doc.id);
    const req = await fetch(`my-database-url`, {
      method: 'POST',
      body: formData,
    });
  const data = await req.json();
  return data;
```

alt works, but not id. Is this expected or should I make another issue for this not working?

**Comment by jmikrut** [comment]
Hey @silveltman — I don't think there's anything that Payload can do here. If you remove a custom ID field, you need to migrate your existing data to have IDs once again. This would be something where migrations are necessary and is specific to your case. 

Does that make sense?

**Comment by silveltman** [comment]
Makes sense, thanks!
