### ISSUE TITLE
Searchbar gets stuck on page reload

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3742]
### Link to reproduction

/

### Describe the Bug

Tiny bug...

When you refresh the page after searching through a collection via the searchbar, it gets stuck on that search query. See video below:

https://github.com/payloadcms/payload/assets/52583398/09b95039-803a-408f-8ebb-27b18212e9f4

Like I said, tiny bug, not a big deal. Can be a bit annoying during dev though, since we refresh a lot.

### To Reproduce

1. go into a collection
2. search via de searchbar
3. refresh
4. The input is gone but the collection is still filtered

### Payload Version

2.0.8

**Comment by Nwakaego-Ego** [comment]
Hi @silveltman If this is beginner-friendly I am interested in working on it else, I wouldn't mind shadowing the assignee while working on this, please. Thank you
