### ISSUE TITLE
Upload Type Collections

### ISSUE THREAD

**Issue by Jeluda** [payloadcms/payload#375]
# Bug Report

It is related to "upload" type collections. First of all, it is impossible to upload new media files into the collection. Here is the error message:
![image](https://user-images.githubusercontent.com/55448320/143838833-060a54d5-21ce-4b49-89ea-2ff9fe79f0c5.png)

In addition, already uploaded media files are not shown in the collection. There are a few requests with 500 errors. 
Looks like an issue is in sorting by the "id" field (which is applied by default).
![image](https://user-images.githubusercontent.com/55448320/143839149-a7e26d02-361f-4634-8147-b320773606c8.png)

![image](https://user-images.githubusercontent.com/55448320/143839459-dc8806f0-0137-4666-9aff-b39278d40956.png)
In the database, this property is called "_id" and everything works fine if I make the same request but with the correct name.
![image](https://user-images.githubusercontent.com/55448320/143839811-5a68616e-62ca-438d-9602-6d16cd25679d.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jmikrut** [comment]
Hey @Jeluda — thank you for the report! We've [identified the issue](https://github.com/payloadcms/payload/commit/ded891e390a93f71963762c0200c97a0beec5cad) with sorting by ID and have just deployed a patch version of Payload that includes a fix (`0.13.1`).

As for the error related to uploading files, we can't replicate on our end just yet but we are continuing to explore why this might be.  Will report back shortly on that one!

**Comment by zaplvlad** [comment]
Hello @Jeluda . Thanks for quick fix. Now upload collections works fine with Cosmos DB. But there are [new](https://github.com/payloadcms/payload/issues/378) issue appeared related to media id.

**Comment by jmikrut** [comment]
Hey @zaplvlad — #378 has been resolved in `0.13.5`.

Thank you very much for reporting these items! Keep it coming!
