### ISSUE TITLE
Lexical h2 & h3 are capitalized

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3751]
### Link to reproduction

/

### Describe the Bug

The lexical editor shows h2 and h3 tags as fully capitalized. This is probably default lexical behaviour, but the content is not stored as capitalized. 

This leads to confusion for the user + inconsistency between the editor / stored json / frontend design.

### To Reproduce

Use the new lexical editor and add h2 and h3 tags. Then look at the API tab and you'll see that it is not stored in caps.

### Payload Version

2.0.8

### Adapters and Plugins

@payloadcms/richtext-lexical: "^0.1.13"

**Comment by jmikrut** [comment]
Hey @silveltman I agree. This is something we need to dial in.

@tylandavis let's provide @AlessioGr with some design direction for built-in elements within Lexical. Our direction should include margins, font sizes, etc.

We should not capitalize certain headings in Lexical.

**Comment by AlessioGr** [comment]
This has been addressed in 072f7febd259ca1538329be73abfd3aeb5f5c64d - H2 and H3 headings are no longer capitalized
