### ISSUE TITLE
[Admin UI] Issue registering a collection was saved using Lexical editor with blocks

### ISSUE THREAD

**Issue by hjbugajski** [payloadcms/payload#3764]
### Link to reproduction

https://github.com/hjbugajski/payload/commit/3c5e3790eabde3d4f17ef53110870b0772667ee2

### Describe the Bug

When the Lexical editor has blocks present, the admin UI does not register that a save/publish occurred and will prompt the user that changes have not been saved, even though they have.

https://github.com/payloadcms/payload/assets/22182454/9e1a8776-9b55-4d08-8a16-29180c5e0f02

### To Reproduce

1. Have a MongoDB instance running locally
2. [Clone forked repository](https://github.com/hjbugajski/payload)
3. Run `pnpm run dev _community`
4. Open example Post
5. Insert block in lexical editor
6. Click "Save Draft" or "Publish Changes"
7. Navigate away from page

### Payload Version

2.0.10

### Adapters and Plugins

db-mongodb, bundler-webpack, richtext-lexical

**Comment by AlessioGr** [comment]
Fixed by 156eae2551d8116f8eb9f4b9a8b8989c2728e135
