### ISSUE TITLE
Has many relationship field in Lexical editor block is null in API response

### ISSUE THREAD

**Issue by hjbugajski** [payloadcms/payload#3766]
### Link to reproduction

https://github.com/hjbugajski/payload/commit/bdf82e2b4ed888bea53829c7bd9c62df993aa676

### Describe the Bug

When a block in the Lexical editor has a relationship field with `hasMany: true` set, `null` is returned for that field in the API.

https://github.com/payloadcms/payload/assets/22182454/1e8b4780-ca73-4f98-9109-7f97340271a9

### To Reproduce

1. Have a MongoDB instance running locally
2. [Clone forked repository](https://github.com/hjbugajski/payload)
3. Run `pnpm run dev _community`
4. Open example Post
5. Insert block in lexical editor and add Tags
6. Click "Save Draft" or "Publish Changes"
7. Navigate to API tab
8. `tags` field in block object is `null`

### Payload Version

2.0.10

### Adapters and Plugins

db-mongodb, bundler-webpack, richtext-lexical

**Comment by AlessioGr** [comment]
Fixed by e197e0316f9c01f945dc7f6d21ac28f9f0420f1d
