### ISSUE TITLE
Upload thumbnails not displaying in admin

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#378]
# Bug Report

After upgrading to 0.13.0 (and subsequent releases) it's now no longer fetching thumbnails in the admin. The issue seems to be straight forward. The ID value is not being passed into the `Upload` field so the request to fetch the document is being made to `http://localhost:3000/api/media/` instead of `http://localhost:3000/api/media/[someID]` and obviously, the upload can't render a collection of documents.

The value [here](https://github.com/payloadcms/payload/blob/cef06e3c7983f02e20944fa797a82570688ab82f/src/admin/components/forms/field-types/Upload/index.tsx#L69) is empty string ('') so it will make the wrong request and fetch everything rather than a single document in the `useEffect` call.

![image](https://user-images.githubusercontent.com/3854592/143977973-11c30d43-6d96-407e-9808-353bbf28a14e.png)

![image](https://user-images.githubusercontent.com/3854592/143978012-e8ec0cb3-89fd-436f-b695-b1fd0564617f.png)

**Comment by jmikrut** [comment]
Ahhhh, good catch. This was related to a new feature where we're trying to make our internal fields more easily reusable within custom components (including the Upload field).

It has been fixed in `0.13.5`!
