### ISSUE TITLE
Description shows up twice for Lexical editor fields

### ISSUE THREAD

**Issue by emma-sg** [payloadcms/payload#3793]
### Link to reproduction

https://github.com/emma-sg/payload/tree/reproduction/lexical-double-description

### Describe the Bug

Description text is rendered twice when using the new Lexical rich text editor.

### To Reproduce

Using a rich text field, set the `admin.description` property to something. The text or component that you specify will be rendered twice under the rich text editor, rather than once.

<img width="216" alt="Screenshot 2023-10-20 at 3 23 08 PM" src="https://github.com/payloadcms/payload/assets/5727389/294cd951-d519-4749-a1d9-0a93279c8480">

### Payload Version

payload@2.0.11

### Adapters and Plugins

@payloadcms/richtext-lexical@0.1.14

**Comment by AlessioGr** [comment]
Good catch! Fixed in 931f6ff519672069db2e3ff7b106054d6dda35a8
