### ISSUE TITLE
Missing env vars in templates/website env.example file

### ISSUE THREAD

**Issue by ballermatic** [payloadcms/payload#3794]
### Describe the Bug

The following vars are called in collections, next config, revalidate, hooks, etc but are not indicated in the env.example file. While we're on the subject, should NEXT_PUBLIC_IS_LIVE have a value? Also, it seems that the REVALIDATION_KEY vars should be the same value, correct?

PAYLOAD_PUBLIC_DRAFT_SECRET
NEXT_PUBLIC_IS_LIVE
REVALIDATION_KEY
NEXT_PRIVATE_REVALIDATION_KEY

### To Reproduce

Clone and install the website template locally with the DB of choice. 

### Payload Version

2.0.11

**Comment by jacobsfletch** [comment]
@ballermatic thank you for pointing this out 🙏 you're exactly right, these vars had gone missing probably as a result of migrating to 2.0. Just merged a fix.
