### ISSUE TITLE
dayOnly times being set with hour

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#3800]
### Link to reproduction

test/fields/date

### Describe the Bug

[Discord  Thread](https://discord.com/channels/967097582721572934/1163972088030310460)

When setting a date field to be `dayOnly`, it is being saved as UTC with an hour of `04`. This causes issues across timezones.

For instance:
In EST, I save a date of 10/20, this saves to the DB as `2023-10-20T04:00:00.000+00:00`. If someone from a timezone 5 hours to the West, they would see a date of `10/19`.

_I do not know the right answer here or if this is an issue at all_, but it seems like we should do some investigation on how this should be handled. It _makes sense_ that it would be adjusted per timezone, but it seems like there is a use-case there where setting a date of 10/20 would _stay_ 10/20 in all cases.

### To Reproduce

- `pnpm dev fields`
- Save `dayOnly` date
- View record in DB

### Payload Version

2.x

### Adapters and Plugins

Not relevant

**Comment by JarrodMFlesch** [comment]
We should be able to set the time to 12:00 UTC, which will result in the same **day** for everyone.

**Comment by steveafrost** [comment]
@JarrodMFlesch that is what I've done manually in the database for the 100+ entries we have. To answer Elliots question in the thread, this behavior is happening with the date field with default config.

```
{
  name: 'date',
  type: 'date',
  required: true,
  admin: {
    date: {
      displayFormat: 'MMMM d, yyyy',
    },
  },
}
```

I am honestly ready to discover I am parsing the datetime wrong, or any host of causes that usually comes along with datetime. The one standout thing to me is that our editors are on the east coast and each time they save they get an offset particular to their timezone which can vary depending on when they enter content: during daylight savings or outside of daylight savings. This creates inconsistencies I think (again, datetime hurts the head) so a default of 12:00UTC would be helpful.

**Comment by steveafrost** [comment]
Thanks to you both for the help. Sorry for the limited replies in the past few days on Discord – been tied up with work.
