### ISSUE TITLE
Postgres - Cannot rename select fields on schema change

### ISSUE THREAD

**Issue by Ali-Parandeh** [payloadcms/payload#3807]
### Describe the Bug

I was trying to split a flat collection that contains a SELECT field into a collection with two tabs.
If there is already data in the database, the migration fails and also hangs the server with a node error because of the select field.

I get asked to rename the columns of the collection one by one to reflect the fields being nested inside tabs now but the SELECT field cannot be renamed if it already has data in its column. Postgres won't allow the rename because of the ENUM constraint.

### To Reproduce

1. Make sure to have the postgres version of payload installed with a local postgres db
2. Create a flat collection that contains a select field
3. Populate a few records in this collection via the admin UI
4. Now change the schema of the collection to split fields into two tabs (using tab fields)
5. Payload now should ask you to rename db columns via the CLI
6. Accept column renames and you will get a postgres migration error because of the ENUM column constraint not being resolved (even if you accept data loss)

### Payload Version

^2.0.0

### Adapters and Plugins

    "@google-cloud/storage": "^7.3.0",     "@payloadcms/bundler-webpack": "^1.0.0",     "@payloadcms/db-postgres": "^0.x",     "@payloadcms/plugin-cloud": "^2.0.0",     "@payloadcms/plugin-cloud-storage": "^1.1.1",     "@payloadcms/richtext-slate": "^1.0.0",

**Comment by jmikrut** [comment]
Hey @Ali-Parandeh — this is more of a Drizzle issue vs. something Payload could solve. I would say that you should [open an issue here](https://github.com/drizzle-team/drizzle-orm) and they will have a better answer for you than I could give. 

It might be something simple that they can check into regarding renaming `enum` columns.

Will you mention this issue when you open the Drizzle issue?

I will continue to monitor this thread!

**Comment by Ali-Parandeh** [comment]
Thanks @jmikrut 
Posted https://github.com/drizzle-team/drizzle-orm/issues/1409
