### ISSUE TITLE
Reverting to previous document version while outside of the default locale results in the document's data being replaced by the default locale's instead of the correct locale.

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload#3810]
### Describe the Bug

Reverting to previous document version while outside of the default locale results in the document's data being replaced by the default locale's data, instead of the correct locale's.

It also does not properly recognize the data's changes, resulting in possibilities for unexpected side effects with field, or document hooks. ex; if my data is synced to a 3rd party, or another application, reverting to a different version will not trigger those effects in the same manner that simply changing the data would.

In the step where I revert to the published version (see "To Reproduce " steps), it does sync the data with my other application, but when I then go to the versions tab and restore a previous (and correct version), it will then take the correctly localized data, but it does not trigger the hook effect.

So, it appears to me that restoring to published version behaves differently than restoring to a previous version as well, which I'm not sure it should?

I really don't understand the codebase, so I think rambling further about edge case scenarios will not be so helpful. Hopefully this is enough to reproduce, as well as possibly reconsider the way that all of this works, in order to ensure document and application integrity.

### To Reproduce

Enable more than two, or more locales, however, for this instance, lets say we're using two.

Create a collection document, preferably with `nested-docs`, as it will be most fitting to real-world scenarios. (a Page, for instance)

Make a version for both locales.

Go to the document and edit the version which is not the default locale.

Save Draft

Revert to published.

Boom. All of your content for the non-default locale is now equal to the default locale's.

Furthermore;

Revert to a previous version, where the data for that locale is correct.

At first, it shows the incorrect locale's data, until you refresh the page. Upon refreshing the page, you appear to have the correct data again. However, you should note that things like hooks do not run as expected.

In my instance, I have a custom "pathname" field, which upon updating, will sync with my frontend in to a json file, which contains all of the localized pathnames. In these instances, it does not get triggered. 

The condition which triggers the sync looks like this:
```
  if (
    originalDoc?.pathname !== finalData.pathname ||
    originalDoc?.defaultPathname !== finalData?.defaultPathname
  ) {
    const syncPathnamesWithWeb = async () => {
```

Even if I resave the document, my condition will not trigger. I must either make it so that **every** document save will trigger this expensive operation (which syncs ALL of the pathnames for my entire project), or I must change my pathname to something else, then back to the correct pathname to trigger the condition.

I believe that changing document versions should behave **exactly** as if you were to manually enter all of the data and simply save/publish the document, this way, any possible side effects and normal behavior will function exactly as a developer would intend.

### Payload Version

2.0.5

### Adapters and Plugins

richtext-lexical, db-mongodb, plugin-nested-docs, plugin-seo, bundler-webpack

**Comment by JarrodMFlesch** [comment]
@HarleySalas thanks for reporting and the detailed reproduction steps! I was able to reproduce on my end and get a fix out, will be in the next release 👍
