### ISSUE TITLE
Autosave saves version to the wrong doc

### ISSUE THREAD

**Issue by dacgray** [payloadcms/payload#3817]
### Describe the Bug

Have a collection with autosave on.

Create 2 docs in that collection.  The latest doc saves a latest version to the first.

Video below.

### To Reproduce

https://github.com/payloadcms/payload/assets/12794616/005f8c1b-20d0-4c9b-b2dd-c8eda4e4569f

### Payload Version

2.0.11

### Adapters and Plugins

bundler-webpack db-mongodb plugin-cloud-storage plugin-sentry richtext-slate

**Comment by ClementLaval** [comment]
@dacgray Do you use the nested-docs-plugin too or not ?

**Comment by dacgray** [comment]
nope, i don't use the nested doc plugin.

**Comment by ClementLaval** [comment]
Ok then it's a core problem 👍

**Comment by jmikrut** [comment]
Hey @JessChowdhury — please get this pulled up and able to be reproduced with a debugger, and I will help identify the cause / fix.

Thank you everyone!

**Comment by JessChowdhury** [comment]
Hey @dacgray + @ClementLaval, this issue has been resolved [here](https://github.com/payloadcms/payload/pull/3981) and you can expect it with the next release - which will go out today. Thank you for raising this issue, I'm impressed this bug snuck by us for so long 🐛
