### ISSUE TITLE
Payload cloud initial deployment failed error when using website template

### ISSUE THREAD

**Issue by ballermatic** [payloadcms/payload#3823]
### Link to reproduction

https://github.com/ballermatic/payloadcloud-website

### Describe the Bug

I am getting initial deployment failed error with a MONGODB_URI warning when launching a new project using website template on cloud. The source code example.env indicates DATABASE_URI, rather than MONGO_URI.

It is also complaining about a missing PAYLOAD_SECRET yet that exists in the project settings tab. Does this deserve a Github issue or would flagging it here be sufficient? Or should I delete the project and give it a fresh try?

Please see the attached error screenshot.
<img width="1025" alt="Screenshot 2023-10-23 at 1 20 58 PM" src="https://github.com/payloadcms/payload/assets/2367305/91509de7-65e1-4043-ba19-660261cfc208">

I will attempt to capture the build logs but they do not persist. I see a build error 1, then a 2, before it quits. I don't think it's actually building fully but cannot say for sure. It builds locally as expected.

### To Reproduce

1. Create new payload cloud project, select website template
2. Wait for build process
3. After numerous warnings, see "initial deployment filed" message 

### Payload Version

latest

**Comment by ballermatic** [comment]
Additional context: creating a completely fresh project suffers from the same issue. Also tried manually adding those two ENV variables to no effect. Also tried changing the DATABASE_URI to MONGODB_URI in config.

**Comment by msbeeman** [comment]
Same issue happened to me

**Comment by ballermatic** [comment]
Managed to capture a screenshot of the build error before logs disappear. There was an update yesterday to the example.env files for both the website and ecommerce templates, but that obviously doesn't change the build. I manually added the necessary values to the cloud project to no avail.

<img width="1090" alt="Screenshot 2023-10-25 at 10 28 16 AM" src="https://github.com/payloadcms/payload/assets/2367305/5248d7a0-9e77-4bda-8548-bcdaf662a231">

**Comment by DanRibbens** [comment]
This error was because the template was importing the incorrect type for the hook and wasn't caught until that type in Payload changed in a recent update, surfacing the error.

We just tested the templates both locally with postgres and mongodb and on cloud for mongodb and everything appears to work.

Thanks for reporting!

**Comment by ballermatic** [comment]
Thank you. Will close on Discord.

**Comment by ballermatic** [comment]
@DanRibbens I had to reopen this on Discord. The website template for Payload Cloud does not build in production. It does build locally.

Here's the repo I am using https://github.com/ballermatic/gb-prime
