### ISSUE TITLE
Point fields nested in a group field break when testing with Jest

### ISSUE THREAD

**Issue by JarrodMFlesch** [payloadcms/payload#383]
# Bug Report
I am unsure if this is something that can be fixed within Payload, but when using Jest & `MongoMemoryServer` (which payload does internally) it will error out when attempting to run a fetch query like
```javascript
fetch('localhost:8000/api/geolocation?where[location][near]=-81,40,1000')
```

## Expected Behavior

MongoMemoryServer should be able to handle a nested field that needs to be indexed, again not sure if this is a payload issue or a memory server one.

## Current Behavior

Jest tests fail because the nested point fields are not indexed properly
```
MongoServerError: error processing query: ns=payloadmemory.geolocations limit=10Tree: GEONEAR  field=address.nestedLocation maxdist=10000 isNearSphere=0
Sort: { createdAt: -1 }
Proj: {}
 planner returned error: unable to find index for $geoNear query
```

## Steps to Reproduce
Clone [this repo](https://github.com/JarrodMFlesch/payload/tree/bug/grouped-point-field)
Or reimplement the code from [here](https://github.com/JarrodMFlesch/payload/commit/ba03a4e31a9994c3bbbc09ca585fe66aa88a2545)

## Detailed Description

Payload version: 0.13.6

**Comment by DanRibbens** [comment]
I am able to recreate the error. It isn't just concerning the mongo memory server. It looks like the way we are calling our index creation isn't working with Mongoose schemas inside of groups. We just need to figure out the best solution for calling nested index creation in buildSchema.

**Comment by DanRibbens** [comment]
I was mistaken about everything I said yesterday! After dropping my collection, the indexes are being created correctly. I've added tests and extended the demo geolocation collection to match.

It appears in your query you are missing the group: 
`fetch('localhost:8000/api/geolocation?where[location][near]=-81,40,1000')`
Should be:
`fetch('localhost:8000/api/geolocation?where[address.location][near]=-81,40,1000')`

**Comment by DanRibbens** [comment]
Another update, it looks like there is actually a bug. In the configuration if a  `point` field is given `index: true` it will create an ascending index instead of a 2dsphere. When left undefined, the config will automatically make a `2dsphere` index for you.

The fix for this bug is to create a `2dsphere` index when `index: true` on a point field.
Longer term we should consider supporting more than just `boolean` to allow all index directions to be used:

The mongoose index directions we could support are: 
type IndexDirection = 1 | -1 | '2d' | '2dsphere' | 'geoHaystack' | 'hashed' | 'text';

**Comment by DanRibbens** [comment]
I'm ignoring the indexDirection complication for now, we could revisit this as a feature request.

I've pushed a [change](https://github.com/payloadcms/payload/pull/382/commits/28ee80a5499cfa5499ccce8be8bdfd71ef5435df) that makes it so `index: true` makes the 2dsphere index on a point field.

**Comment by DanRibbens** [comment]
Any further work on trying to support more index types can be a new feature later on. 

Closing with https://github.com/payloadcms/payload/pull/382
Will go in the next release.
