### ISSUE TITLE
buildSearchParam: field is undefined

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#3837]
### Describe the Bug

[02:36:15] ERROR (payload): TypeError: Cannot read properties of undefined (reading 'type')
    at sanitizeQueryValue (/Users/alessio/Documents/GitHub/payload/packages/db-mongodb/src/queries/sanitizeQueryValue.ts:43:13)
    at buildSearchParam (/Users/alessio/Documents/GitHub/payload/packages/db-mongodb/src/queries/buildSearchParams.ts:97:46)
    
The error is caused by an undefined field which is for some reason passed into the buildSearchParam function. We should figure out the root cause: why is an undefined field passed into this function?

### To Reproduce

1. Start _community test suite
2. Go to posts collection
3. Search something
4. Error in the server console appears

https://github.com/payloadcms/payload/assets/70709113/59cc6896-7bf8-4130-a0bf-5a56ca40d8c8

### Payload Version

2.0.12

### Adapters and Plugins

db-mongodb

**Comment by olarsson** [comment]
I have the same problem, using the same payload version, im using multiple locales. What i noticed is that it had suddenly (somehow) lost the reference to one of the language versions. I could only use one language, when switching to the other locale it couldn't find it at all. Im using nested-docs.

**Comment by olarsson** [comment]
The same error happened again when I tried to use the richtext slate editor to link to an internal document, identical error.

**Comment by mvarendorff** [comment]
@olarsson update your `@payload/richtext-slate` to `>=1.0.7`.

**Comment by DanRibbens** [comment]
I am not able to reproduce this as of Payload v2.5.0 and mongoDB v1.1.1.
