### ISSUE TITLE
Global page field isn't editable in live preview mode

### ISSUE THREAD

**Issue by wSzki** [payloadcms/payload#3846]
### Link to reproduction

https://github.com/wSzki/payload_livepreview_bug

### Describe the Bug

Hello

Fields in global live previews are greyed out.
They are editable as expected in regular `Edit` mode
Tried setting access controls explicitely but same result. 

![bug1](https://github.com/payloadcms/payload/assets/59784520/54a3c2c7-9825-4ba6-ac8e-d7ffdeff9375)
![bug](https://github.com/payloadcms/payload/assets/59784520/e433a7e2-a1f3-4724-ad3c-3f28bebe1734)

### To Reproduce

1. yarn dev
2. go to http://localhost:3000/admin/globals/TestGlobal/preview

### Payload Version

2.0.13

### Adapters and Plugins

default

**Comment by jacobsfletch** [comment]
@swenzel-arc thanks for the report on this 👍 I've got a fix started in #3854 with some tests to prevent future regression.
