### ISSUE TITLE
textarea fields in a row have different heights

### ISSUE THREAD

**Issue by nathanclevenger** [payloadcms/payload#3855]
### Describe the Bug

If you put 2 textarea fields inside a row, they are different heights

<img width="1309" alt="Screenshot 2023-10-24 at 5 58 40 PM" src="https://github.com/payloadcms/payload/assets/4130910/aca58ec0-47f5-4f81-a136-6bc22cb94322">

### To Reproduce

```javascript
        { type: 'row', fields: [
          { name: 'headline', type: 'textarea' },
          { name: 'description', type: 'textarea' },
        ]},
```

### Payload Version

2.0.11

**Comment by jacobsfletch** [comment]
It's possible this was fixed with #3822

**Comment by nathanclevenger** [comment]
@jacobsfletch Has that fix been published yet?  I've still seen that behavior on projects I created yesterday with create-payload-app@latest ... I've seen it in multiple brand new projects ... but I also just realized that I am not sure if I tested chrome as I use Safari as my primary browser ... can you check how it looks on Safari?

**Comment by jacobsfletch** [comment]
Yea after checking Safari again just now, it appears to be rendering correctly. Here's some screenshots:

Safari:
<img width="1198" alt="Screenshot 2023-11-01 at 1 28 28 PM" src="https://github.com/payloadcms/payload/assets/15735305/79233486-cfe1-4466-93f2-5fe06320f471">

Chrome:
<img width="1371" alt="Screenshot 2023-11-01 at 1 28 36 PM" src="https://github.com/payloadcms/payload/assets/15735305/82566142-ae2f-4eae-885f-9387187c043d">

**Comment by jacobsfletch** [comment]
@nathanclevenger I just installed a fresh payload app from npx to confirm that that these fields are rendering correctly. I'm going to mark this as closed but let me know if you're still experiencing this issue.
