### ISSUE TITLE
globalType not being returned in doc when revalidating

### ISSUE THREAD

**Issue by ficeco** [payloadcms/payload#3858]
### Describe the Bug

I'm trying to set up an afterChange hook to revalidate globals when they're updated, and would need to use globalType for the revalidate tag. When I console.log(doc) in the hook, I noticed that globalType is not included. I see in the API tab that globalType is there. I'm using next-payload connected to a Neon postgres database.

This is what I see when I console.log(doc) in the AfterChangeHook:
{
id: 1,
navItems: [
{
_order: 1,
id: '65330bb01c32b17fdf32cbf7',
link_type: 'reference',
link_newTab: null,
link_url: null,
link_label: 'Homyyy',
link: [Object]
},
{
_order: 2,
id: '65330784435e944854258af6',
link_type: 'reference',
link_newTab: false,
link_url: null,
link_label: 'About',
link: [Object]
},
{
_order: 3,
id: '653308c9435e944854258af8',
link_type: 'reference',
link_newTab: null,
link_url: null,
link_label: 'Solutions',
link: [Object]
},
{
_order: 4,
id: '65330bf31c32b17fdf32cbf9',
link_type: 'reference',
link_newTab: null,
link_url: null,
link_label: 'News',
link: [Object]
},
{
_order: 5,
id: '65330bfb1c32b17fdf32cbfb',
link_type: 'reference',
link_newTab: null,
link_url: null,
link_label: 'Contact',
link: [Object]
}
],
updatedAt: '2023-10-22T19:33:41.164Z',
createdAt: null
}

but in the API tab I see globalType: "header" after createdAt:null.

### To Reproduce

create-next-app
next-payload
add a global
add afterChangeHook to global and console.log(doc) in afterChangeHook:
```
import type { AfterChangeHook } from 'payload/dist/globals/config/types';

import { revalidate } from '../../utilities/revalidateGlobal'

// Revalidate the page in the background, so the user doesn't have to wait
// Notice that the hook itself is not async and we are not awaiting `revalidate`
export const revalidateGlobal: AfterChangeHook = ({ doc, req: { payload } }) => {
  console.log(doc)
  revalidate({ payload, title: doc.globalType })
  
  return doc
}
```
See that globalType is not returned in doc data.

### Payload Version

2.0.11 via next-payload

### Adapters and Plugins

db-postgres

**Comment by ficeco** [comment]
@JarrodMFlesch I noticed the fix adds globalType to global versions fields. I actually don't have versions enabled for globals and was having this issue. Not sure if that changes anything but just an FYI.

**Comment by JarrodMFlesch** [comment]
@ficeco ok I can reopen it, thanks!

**Comment by JarrodMFlesch** [comment]
@ficeco I just tested this and it looks like it is working as expected. If you are still having issues please open up a new issue with a reproduction, thanks 😄 

![CleanShot 2023-10-31 at 9  58 07@2x](https://github.com/payloadcms/payload/assets/30633324/bac2ec61-b738-4a87-99da-5200123f92b5)

**Comment by ficeco** [comment]
Thanks @JarrodMFlesch, I'm not sure how to test the fix before it's released, but will test once it is!
