### ISSUE TITLE
Using Postgres in production breaks deployment (Payload Cloud)

### ISSUE THREAD

**Issue by Davidvision** [payloadcms/payload#3866]
### Describe the Bug

Hello, I've setup a Cloud project using the Blank CMS template.
I then used the mongoose adapter to setup a db.
From this moment, every merges into the main branch got successfully deployed in production.
Then I wanted to give postgres adapter a try.
I set it up, created a pull request that got merged, and from this moment, no new merge got deployed. The deployed version of the app was the one prior to using postgres.
Either its a bug, or this is some configuration stuff I didn't catch in the docs (which I carefully read...) ?

### To Reproduce

- Create a Payload cloud project
- Use mongodb (mongooseAdapter) in this project
- Deploy it, see if your changes got deployed
- If yes and your project works :
- switch to using postgres (postgresAdapter)
- Deploy
- Apps stays at the pre-postgres commit

### Payload Version

2.0.13

### Adapters and Plugins

db-postgres, plugin-cloud, bundler-webpack, richtext-slate

**Comment by jmikrut** [comment]
Hey @Davidvision — Payload Cloud does not provide a Postgres database (yet) so this is expected. 

If you would like to deploy on Payload Cloud in the meantime, you need to make sure to provide your own Postgres connection string.

Does that make sense? Note - we will be adding Postgres support to Payload Cloud in the future. But until then, you'll have to manually provide your own.

Thank you for bringing this up!
