### ISSUE TITLE
Uploaded PNG images are not centered on crop

### ISSUE THREAD

**Issue by id3er0** [payloadcms/payload#3877]
### Link to reproduction

https://github.com/id3er0/payload-tests/tree/6ebefb69c0f43ecb35c25e7a63853ac774e7f301

### Describe the Bug

There is an issue with PNG files uploaded to a collection with `resizeOptions` or `imageSizes` settings:
`fit: 'cover'` and `position: 'centre'` does not work for PNG but works for JPEG files.

Demo for file converted from PNG:
<img width="1435" alt="image" src="https://github.com/payloadcms/payload/assets/50173439/ca96e8fb-075d-40cc-a6e4-08aa8a4c7826">

Demo for file converted from JPEG:
<img width="1435" alt="image" src="https://github.com/payloadcms/payload/assets/50173439/e28d4d80-7936-4913-aac8-e33cd88c3a12">

### To Reproduce

1. Run simple Payload project from https://github.com/id3er0/payload-tests/tree/6ebefb69c0f43ecb35c25e7a63853ac774e7f301.
2. Upload PNG image to `Images` collection.

### Payload Version

2.0.13

**Comment by JessChowdhury** [comment]
@id3er0 Thank you for providing a reproduction! I'm looking into this now.

**Comment by JessChowdhury** [comment]
NOTE: Also an issue with `withoutEnlargment` and `withoutReduction` props.
