### ISSUE TITLE
duplication of content causes incorrect checkbox value

### ISSUE THREAD

**Issue by olarsson** [payloadcms/payload#3878]
### Describe the Bug

when using the "duplicate" function from the menu for an item in a collection, it sometimes causes a checkbox to have an incorrect value.

### To Reproduce

checkbox:

```
 {
      name: 'showContactCta',
      label: 'Show contact CTA',
      type: 'checkbox',
      localized: true
    }
```

Steps:
1. Create localized checkbox
2. Save EN as checked
3. Save ES as unchecked
4. Switch to EN
5. Duplicate Doc
6. Switch to ES
7. Checkbox will be checked, but should be unchecked

### Payload Version

8.0.13

**Comment by DanRibbens** [comment]
I fixed a few errors related to duplicating localized fields. In 2.0.13 Payload is copying the currently selected locale to the defaultLocale due to a bug I fixed yesterday that isn't deployed yet. 

It could be related to that. Is the value the same for every locale when it happens?

**Comment by olarsson** [comment]
it happens both ways, if i duplicate from the default locale into another one, or from the other locale into the default locale. if the value was "true" to begin with when it gets duplicated, it becomes unchecked, and when you save it remains "true" when it should be "false".
