### ISSUE TITLE
Unaccurate error when trying to submit duplicate data into a field with 'unique: true'

### ISSUE THREAD

**Issue by Augigauki** [payloadcms/payload#3879]
### Describe the Bug

Using Payload 2.0 with Postgres. I have some fields (slugs to generate URLs) that I need to be unique across a collection, and while this works, the UX in the admin panel is lacking. 

In the console I get the error `ERROR (payload): error: duplicate key value violates unique constraint "slug_idx"`, but in the Admin UI all you get is a red error bar at the bottom that just says "Something went wrong", and the unique field that is the culprit is not highlighted. It is very confusing for a end user receiving this error, not knowing why their document failed to submit or what field to fix. 

"Sounds like a bug with the Postgres adapter" according to Elliot on Discord.

Slghtly unrelated, but an idea I had for slightly improved UX: designate unique field with an indicator similar to the red asterisk for required fields, so end users know that a field needs to be unique in relation to other documents in the collection while they are working on creating the data for the document. A little heads-up, maybe minimizing errors in the editing experience?

### To Reproduce

1. Create a Collection
2. Add a text field with `unique: true`
3. Create a Document in the Collection
4. Enter the value 'Test' in the text field with `unique: true`
5. Save the Document
6. Create a new Document
7. Enter the value 'Test' in the field with `unique: true` in the new Document
8. Save the new Document

### Payload Version

2.0.5

### Adapters and Plugins

db-postgres ^0.1.4, bundler-webpack "latest"

**Comment by DanRibbens** [comment]
> Slghtly unrelated, but an idea I had for slightly improved UX: designate unique field with an indicator similar to the red asterisk for required fields, so end users know that a field needs to be unique in relation to other documents in the collection while they are working on creating the data for the document. A little heads-up, maybe minimizing errors in the editing experience?

I like this idea. You may want to make a separate discussion to track it.

**Comment by Augigauki** [comment]
Created a dicussion for it here: https://github.com/payloadcms/payload/discussions/3895 :)
