### ISSUE TITLE
Disabling middleware on endpoints is broken

### ISSUE THREAD

**Issue by RickVM** [payloadcms/payload#3880]
### Link to reproduction

https://github.com/Byont-Ventures/payload-root-endpoint

### Describe the Bug

The bug occurs as soon as you add an endpoint to a collection, with the property root set to true. 
I need the raw request body in my endpoint handler, hence I must skip the payload middleware.

In addition, behavior is also faulty if you add the same endpoint to the global payload config. 
In this case there is no error and payload boots, but the endpoint is not made. Any requests show up as 404.
The exact same endpoint **does work** if you set `root: false`

### To Reproduce

See link to repository

1. Create app with dlx create-payload-app
2. Create an endpoint in a collection with the property `root: true` like so:

```
import { Endpoint } from "payload/config";
import { CollectionConfig } from "payload/types";

export const myEndpoint: Endpoint = {
  path: "/foo",
  method: "get",
  root: true, // This is the culprit
  handler: [
    (req, res, next) => {
      res.send("baz");
    },
  ],
};

const Users: CollectionConfig = {
  slug: "users",
  auth: true,
  admin: {
    useAsTitle: "email",
  },
  endpoints: [myEndpoint],
  fields: [
    // Email added by default
    // Add more fields as needed
  ],
};

export default Users;
```

3. `yarn dev`

```
/Users/rick/Documents/projects/payload/payload-root-endpoint/myapp/node_modules/payload/src/express/mountEndpoints.ts:10
      express[endpoint.method](endpoint.path, endpoint.handler)
             ^
TypeError: Cannot read properties of undefined (reading 'get')
    at forEach (/Users/rick/Documents/projects/payload/payload-root-endpoint/myapp/node_modules/payload/src/express/mountEndpoints.ts:10:14)
    at Array.forEach (<anonymous>)
    at mountEndpoints (/Users/rick/Documents/projects/payload/payload-root-endpoint/myapp/node_modules/payload/src/express/mountEndpoints.ts:6:13)
    at map (/Users/rick/Documents/projects/payload/payload-root-endpoint/myapp/node_modules/payload/src/collections/initHTTP.ts:37:19)
    at Array.map (<anonymous>)
    at initCollectionsHTTP (/Users/rick/Documents/projects/payload/payload-root-endpoint/myapp/node_modules/payload/src/collections/initHTTP.ts:13:51)
    at initHTTP (/Users/rick/Documents/projects/payload/payload-root-endpoint/myapp/node_modules/payload/src/initHTTP.ts:40:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Payload.init (/Users/rick/Documents/projects/payload/payload-root-endpoint/myapp/node_modules/payload/src/index.ts:17:21)
```

### Payload Version

The repo linked uses 2.0.0 but it also occurs with 2.0.13 and 1.15.8

### Adapters and Plugins

    "@payloadcms/bundler-webpack": "^1.0.0",     "@payloadcms/db-mongodb": "^1.0.0",     "@payloadcms/plugin-cloud": "^2.0.0",     "@payloadcms/richtext-slate": "^1.0.0",

**Comment by jacobsfletch** [comment]
Hey @RickVM the `root` property is only available on top-level endpoints, [here is the exact line](https://github.com/payloadcms/payload/blob/main/packages/payload/src/collections/config/types.ts#L363) that omits the this property from the collections config. Here's [what the docs say](https://payloadcms.com/docs/rest-api/overview#custom-endpoints):

> Note: this only applies to top-level endpoints of your Payload config, endpoints defined on collections or globals cannot be root.

It looks like you are importing `Endpoint` into your own config object, which _does_ contain `root`. Are you able to move your endpoint to the top-level?

**Comment by RickVM** [comment]
Hey Jacob, if with top-level endpoint you mean endpoints configured in the the global payload config then yes I have tried that but I am also not getting the result I would expect.  
Unlike before there's no errors, but the endpoint doesn't seem to be made.   
Requests show up as 404. If I turn off the root property, then it does give me the response I would expect.   
Code is the same, except that its now part of the buildConfig in payload.config.ts

**Comment by jacobsfletch** [comment]
Root endpoints _do_ appear to be working on my end. [Here's a root endpoint](https://github.com/payloadcms/payload/blob/main/test/endpoints/endpoints/root.ts#L35) from our "endpoints" test suite (we have unit tests for all endpoint configurations). I just did a simple `get` request using my browser, here's the result:

<img width="323" alt="Screenshot 2023-11-02 at 11 03 46 AM" src="https://github.com/payloadcms/payload/assets/15735305/33e9ba94-6a71-43ff-aa87-01deca4562fc">

Can you check that your setup is correct, and update your reproduction?

**Comment by jacobsfletch** [comment]
@RickVM I'm going to mark this as closed but let me know if you're still having troubles with this.
