### ISSUE TITLE
Cannot find documentation about editor

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#3881]
# Documentation Issue

Search for "editor" results in irrelevant pages. <-- this is the actual issue

## Additional Details

Why editor?

Homepage suggests `npx create-payload-app`
Running docker compose up results in this error:
```
cms-payload-1  | [12:49:26] ERROR (payload): There were 1 errors validating your Payload config
cms-payload-1  | [12:49:26] ERROR (payload): 1: "editor" is required
cms-payload-1  | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by jjaimealeman** [comment]
I too have run into the same issue.

Fresh install with `npx create-payload-app project-name`.

A Google brought me to this discussion https://payloadcms.com/community-help/discord/there-were-1-errors-validating-your-payload-config-1-editor-is-required

but I disagree with a user having to manually _"Migrate"_, when I thought that the `npx create` command, should already be creating a `2.0` app 🤔

**Comment by AlessioGr** [comment]
![Screenshot 2023-11-03 at 18 05 07@2x](https://github.com/payloadcms/payload/assets/70709113/6e06b5be-07f8-4072-ba64-e199a3964620)

You should be able to find something if you search for `editor` now!

As for `npx create-payload-app`, it seems that it sometimes uses an old version of create-payload-app. The new one definitely adds the `editor` field.

If that's still the case, try `npx create-payload-app@latest`
