### ISSUE TITLE
Payload cloud "too many requests error"

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#3882]
### Link to reproduction

payload cloud issue

### Describe the Bug

I was updating quiet a lot of image back to back, when suddenly the admin panel stopped working.
When refreshing the page, the admin panels gets stuck on 'loading'. Here are the console logs:
![Screenshot 2023-10-26 at 15 07 33](https://github.com/payloadcms/payload/assets/52583398/4df87900-eec3-4b95-99d7-09bbc0ea184d)

here are the cloud runtime logs:
![Screenshot 2023-10-26 at 15 08 22](https://github.com/payloadcms/payload/assets/52583398/fe0260b9-1cc2-445f-90d9-705dec834be5)

Also, when manually navigating to mydomain.com/api/pages for example, it displays "Too many requests, please try again later."

This obviously is a huge problem, because this means the entire database stopped working and therefore the website is not working at all.

### To Reproduce

Create a payload cloud instance
update a lot of images on pages (posts in my case) back to back. For me it happend after around 20-30 times

### Payload Version

2.0.12

### Adapters and Plugins

"@payloadcms/db-mongodb": "^1.0.3",     "@payloadcms/plugin-cloud": "^2.2.5",

**Comment by denolfe** [comment]
Hmm, it's interesting to me that you were getting a 429 in your browser console, but the logs were saying NotFound.

Have you adjusted your `rateLimit` options in your config at all? https://payloadcms.com/docs/production/preventing-abuse#rate-limiting-requests

If not, I'd be curious if bumping up from the defaults would resolve your issue.

**Comment by HarleySalas** [comment]
I experience the same thing in dev mode, while using the Live Preview.

I'm still trying to figure out some more details for a reproduction, but just thought I'd add the note.

**Comment by silveltman** [comment]
@denolfe I have not adjusted the rate limits, will do.

Getting the same error again now, after just 3 or 4 changes...

**Comment by denolfe** [comment]
> Getting the same error again now, after just 3 or 4 changes...

What values are you using now? I would try something abnormally large to see if this is even the cause.

**Comment by denolfe** [comment]
@silveltman Do you happen to be using a custom domain?

**Comment by silveltman** [comment]
@denolfe I am not using a custom domain. Also, I have not encountered the problem the last few days. I increased my limit from only 500 to 2000.

**Comment by silveltman** [comment]
I think I found the cause of this.

I use Astro as a build tool, which appearantly makes a very high number of requests during build. Reason for this is that I fetch payload in some of my base components, like a Social component. This results in a new fetch for every Social component for every page. 

Solution for me would be to fetch in a global layout and pass the data as props to the components.
