### ISSUE TITLE
Warning about React.createElement - invalid type

### ISSUE THREAD

**Issue by rafalnawojczyk** [payloadcms/payload#3893]
### Describe the Bug

When trying to run:
```npm run generate:types```
or simply trying to build/dev - I'm getting this set of warnings in the console:
<img width="1061" alt="Screenshot 2023-10-27 at 08 58 22" src="https://github.com/payloadcms/payload/assets/102222064/a7b4c2ff-ce38-458c-a832-18f79872a5e8">
I tried to roll back from Payload 2.0 to Payload 1.X and this does not show up in a console, so it's somehow connected with Payload. 

Seeing that it is even triggered while trying to generate types - it's looking like it is a problem specifically with Payload. 

I know it's not a breaking error, but still it is polluting console logs.

### To Reproduce

Simply run one of commands for Payload - either build or generate:types.

### Payload Version

2.0.12

### Adapters and Plugins

bundler-webpack, db-mongodb, s3Adapter, cloudstorage, seo, redirects,

**Comment by JarrodMFlesch** [comment]
@rafalnawojczyk can you reproduce this on a template using `npx create-payload-app`? I was unable to reproduce on the latest version of Payload. I am going to close for now, but if you have a reproduction and want to link it here we can reopen it!
