### ISSUE TITLE
Documents can be saved before blocks are finished rendering resulting in page content vanishing.

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#391]
# Bug Report

When modifying a document it's possible to click save before blocks and other fields have finished loading in. When this happens, the POST request will be missing the block information and the document will lose all of its block content.

I believe this also happens with relationship and upload fields. I can't confirm but I've had cases where a background image goes missing mysteriously and I suspect this is the cause of it.

## Expected Behavior

Either users shouldn't be able to save until all document content has finished loading or the admin interface shouldn't render until it has all the content in place.

## Steps to Reproduce

1. Add a bunch of blocks to a document
2. Go back to the index 
3. Click on the document and click save as soon as you see it
4. Reload the page and all the content is gone :(

## Detailed Description

Version 0.13.6

**Comment by jmikrut** [comment]
Hey @richardvanbergen — good call. We will address this shortly with a patch version.

Thanks for pointing this out!

**Comment by jmikrut** [comment]
Hey @richardvanbergen — sorry it took so long to address this one but we just released a beta version with a fix:

```
payload@0.14.19-beta.0
```

Give it a shot! It'll hit a minor release once we merge in Versions, Drafts, & Autosave coming up soon!
