### ISSUE TITLE
Custom Component Cell Props example is missing an import

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#3912]
# Documentation Issue

In the example: https://payloadcms.com/docs/admin/components#cell-component, the code is missing the import statement for `Props`, which seems to be `import {Props} from "payload/dist/admin/components/views/collections/List/Cell/types";`

**Comment by JarrodMFlesch** [comment]
This has been [fixed](https://github.com/payloadcms/payload/pull/3931), thanks for reporting!
