### ISSUE TITLE
Converting values from richText field to html

### ISSUE THREAD

**Issue by GregorGabric** [payloadcms/payload#3914]
# Documentation Issue

Currently im trying out the lexical rich-text editor, I was wandering, how could I convert the json/object to html

**Comment by rafalnawojczyk** [comment]
Here you can find some more informations:
https://lexical.dev/docs/concepts/serialization

**Comment by AlessioGr** [comment]
This is now documented here: https://payloadcms.com/docs/rich-text/lexical#lexical-html
