### ISSUE TITLE
@payloadcms/db-postgres Cannot Remove Blocks

### ISSUE THREAD

**Issue by steveninety** [payloadcms/payload#3918]
### Link to reproduction

-

### Describe the Bug

Inside a collecrion, removing a block and then saving the document, brings back the block.
The Patch request's payload excludes the to-be-deleted block, as should be,
but the response includes it once again.
No errors in the terminal or console.

This happens to all my blocks (not specifically nested like #3635).

### To Reproduce

- Create a new Page
- Add a block. 
- Save the Page.
- Remove the block.
- Save the Page.
- The block reappears

P.s. I'm a noob and couldn't follow along with the reproduction guide (e.g. how do I reproduce using specific package versions, where do I add env variables...)

### Payload Version

2.0.13

### Adapters and Plugins

"@payloadcms/bundler-vite": "^0.1.3", "@payloadcms/db-postgres": "^0.1.10", "@payloadcms/plugin-form-builder": "^1.0.15", "@payloadcms/plugin-nested-docs": "^1.0.8", "@payloadcms/richtext-lexical": "^0.1.15",

**Comment by dardanbujupaj** [comment]
Encountered the same issue.

Some more details:
It only happens with the postgres adapter, deleting blocks with mongodb works fine.
It can be reproduced, by setting up the website-template with `npx create-payload-app`.

**Comment by ficeco** [comment]
@JarrodMFlesch I'm still having this issue after updating to 2.0.15, I can add blocks but not remove them.

**Comment by dardanbujupaj** [comment]
@ficeco did you update `@payloadcms/db-postgres` to `0.1.12` as well?

**Comment by JarrodMFlesch** [comment]
@ficeco can you update the @payloadcms/db-postgres adapter and try again?

**Comment by ficeco** [comment]
@JarrodMFlesch That did the trick, thank you!
