### ISSUE TITLE
Redirection after save or update to collection view page

### ISSUE THREAD

**Issue by DhanshreeNagre** [payloadcms/payload#3925]
I am trying to redirect after save or update to collection view page but not able to achieve it. Any knows how to do it or is there any way to do it. Thanks.

**Comment by DhanshreeNagre** [comment]
@JarrodMFlesch  I tried that approach but not getting how to do it? can you provide any example it will be so helpful. Thanks.

**Comment by DhanshreeNagre** [comment]
I tried same but it is not working. It is showing  /collections/users/:userId 

code as below

`import { Button } from 'payload/components';
 
import * as React from 'react'
import {
    CustomSaveButtonProps,
  } from 'payload/types'
  import { useHistory  } from "react-router-dom";
 
export const CustomSaveButton: CustomSaveButtonProps = (props) => {
  const { DefaultButton, save } = props;
  const history = useHistory();
  const cancel = (e)=>{
    e.preventDefault();
    history.push({pathname:"/editor/collections/users?limit=10"});    
  }
  const saveOn = React.useCallback(()=>{
    save();
    history.push({pathname:"/editor/collections/users"});
   
  },[save, history]);
 
    return (<div className='user-btn'>
      <Button buttonStyle='secondary' onClick={cancel}>Cancel</Button>
      <DefaultButton label={'Add the User'} save={saveOn}/>
      </div>)
  }`

**Comment by JarrodMFlesch** [comment]
Sorry I am unable to recreate. You will need to link a reproduction for us to assist further!

Uploading CleanShot 2023-10-30 at 9 .57.57.mp4…

**Comment by JarrodMFlesch** [comment]
Sorry I am unable to recreate. You will need to link a reproduction for us to assist further!

https://github.com/payloadcms/payload/assets/30633324/e049153f-2ede-4597-8cec-5b9ca86aa5b9

**Comment by DhanshreeNagre** [comment]
After writing await on save it started working. Thanks for your help
