### ISSUE TITLE
Weird Backspace glitch in lexical editor

### ISSUE THREAD

**Issue by patricsgamma** [payloadcms/payload#3928]
### Link to reproduction

Happening with
`@payloadcms/richtext-lexical  0.1.11`

### Describe the Bug

I have some crapy demo text within lexical RT editor to test some automation and export options. 
Deleting a word I noticed a 🐛  

I selected the last word of a line and delete the last word with backspace. 
Which made the whole line get duplicated and placed at the end of the line instead of the original word.
It is only happening when its a multi-line paragraph and I delete the last word that is not a `.`

See recording

https://github.com/payloadcms/payload/assets/87857953/f8b52085-dcee-4168-a532-c6287fcca138

### To Reproduce

Please check the video
Also its happening on following browser
- Firefox: 119.0 (64-bit)
- OSX 12.2.1

### Payload Version

"payload": "^2.0.6"

### Adapters and Plugins

```
"@payloadcms/bundler-webpack": "^1.0.4",     
"@payloadcms/db-mongodb": "^1.0.4",     
"@payloadcms/plugin-cloud-storage": "^1.1.1",     
"@payloadcms/plugin-sentry": "^0.0.4",     
"@payloadcms/richtext-lexical": "^0.1.11",
```

**Comment by AlessioGr** [comment]
I can reproduce it on Firefox - and only on Firefox.

Looks like this happens in https://playground.lexical.dev/ as well, so I've filed an issue and linked yours there: https://github.com/facebook/lexical/issues/5233

Optimally, they will fix it, so I'll let this rest and wait for now

**Comment by denolfe** [comment]
Looks like there is some swirl on Lexical's side in that issue. Still keeping an eye on when it gets fixed and released.

**Comment by patricsgamma** [comment]
Have observed it as well, thx 🚀
