### ISSUE TITLE
Collection preview function doesn't receive new data until sidebar is refreshed

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#393]
# Bug Report

If I edit the page slug, save and try to click "preview" then it wont push the updated data into the preview function. This seems to apply in any situation where the sidebar UI isn't fully reloaded.

Also happens (or rather doesn't happen) when switching locales or when you switch to a not-yet-created locale and save.

## Expected Behavior

Preview function should receive new data when the page updates in any way and should re-render the button.

As a side note, it's also be nice to be able to return falsy from the function to hide the button.

## Current Behavior

Will not update until full page reload.

**Comment by jmikrut** [comment]
Hey @richardvanbergen — this one's a quick fix for us. Thanks for bringing it to our attention and watch out for a patch version with a fix shortly!

**Comment by jmikrut** [comment]
Beta deployed with fix:

```
0.13.7-beta.0
```

**Comment by richardvanbergen** [comment]
Thanks this one has been bothering me. Happy new year by the way!

**Comment by richardvanbergen** [comment]
Looking good to me!
