### ISSUE TITLE
Custom admin component views does not handle nested routes correctly

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#3941]
### Describe the Bug

PayloadCMS does not handle nested route routing in admin custom components correctly.

### To Reproduce

Create two custom views and nest one in the other's routes in `payload.config.ts`:

```ts
    admin: {
        components: {
            views: {
                GateListGenerator: {
                    Component: GateListGenerator,
                    path: "/collections/volunteers/gate-list",
                },
                GateListDocument: {
                    Component: GateListDocument,
                    path: "/collections/volunteers/gate-list/output",
                },
            },
        },
    },
```

This will cause `/admin/collections/volunteer/gate-list/output` to always go to `GateListGenerator`, completely ignoring `GateListDocument`.

However, this config _will_ lead to both routes being resolved correctly:
```ts
    admin: {
        components: {
            views: {
                GateListDocument: {
                    Component: GateListDocument,
                    path: "/collections/volunteers/gate-list/output",
                },
                GateListGenerator: {
                    Component: GateListGenerator,
                    path: "/collections/volunteers/gate-list",
                },
            },
        },
    },
```

### Payload Version

2.0.14

**Comment by jacobsfletch** [comment]
Hey @tyteen4a03 this appears to be working for me, I've added a test in #3962 for this. Here's my config:

```ts
admin: {
  components: {
    views: {
      MyCustomViewWithCustomTab: {
        path: '/custom-tab-component',
        Component: CustomView,
      },
      MyCustomViewWithNestedPath: {
        path: '/custom-tab-component/nested-view',
        Component: CustomNestedView,
      },
    },
  }
}
```

Just to be sure I'll also try it using paths that are nested one-level deeper, as your example shows.

**Comment by tyteen4a03** [comment]
Is your config "tacking-onto" a collection config as above?

**Comment by jacobsfletch** [comment]
Yea this config adds two new views to a collection

**Comment by jacobsfletch** [comment]
Would you be able to provide a reproduction [here](https://github.com/payloadcms/payload/tree/main/test/_community)?

**Comment by tyteen4a03** [comment]
> Yea this config adds two new views to a collection

Sorry I should have clarified, this only happens when I add them to `payload.config.ts`.

**Comment by jacobsfletch** [comment]
>  this only happens when I add them to payload.config.ts

Okay this is making more sense now. The route paths you've chosen are likely interferring with the internal routing of collections, i.e. `/collections`. I'll look into this a bit more. Thank you for the clarification here.

**Comment by tyteen4a03** [comment]
Sounds good - as long as this is documented!

**Comment by jacobsfletch** [comment]
The `exact` property is documented here: https://payloadcms.com/docs/admin/components#views but I will go ahead and add a little blurb to that page with a description of this behavior, good call. I'll throw it into my PR above.
