### ISSUE TITLE
MongoDB find performance hint causes errors in AWS DocumentDB

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#3947]
### Link to reproduction

N/A

### Describe the Bug

I upgraded to Payload v2.0.14 and it seems that #3836 introduced the following error:

```
10:58:05 0|server  | MongoServerError: Cannot use Hint for this Query. Index is multi key index , partial index or sparse index and query is not optimized to use this index.
10:58:05 0|server  |     at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:231:30)
10:58:05 0|server  |     at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:61:60)
10:58:05 0|server  |     at MessageStream.emit (node:events:517:28)
10:58:05 0|server  |     at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
10:58:05 0|server  |     at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
10:58:05 0|server  |     at writeOrBuffer (node:internal/streams/writable:392:12)
10:58:05 0|server  |     at _write (node:internal/streams/writable:333:10)
10:58:05 0|server  |     at Writable.write (node:internal/streams/writable:337:10)
10:58:05 0|server  |     at TLSSocket.ondata (node:internal/streams/readable:777:22)
10:58:05 0|server  |     at TLSSocket.emit (node:events:517:28) {
10:58:05 0|server  |   ok: 0,
10:58:05 0|server  |   operationTime: new Timestamp({ t: 1698749885, i: 1 }),
10:58:05 0|server  |   code: 2,
10:58:05 0|server  |   [Symbol(errorLabels)]: Set(0) {}
10:58:05 0|server  | }
```

With v2.0.13 and `mongoose.set("debug", true)` I see this:

```
11:46:50 0|server  | Mongoose: users.countDocuments({ '$and': [ { email: { '$eq': 'john@example.com' } } ]}, {})
```

…with v2.0.14 they look like this:

```
11:34:07 0|server  | Mongoose: users.countDocuments({ '$and': [ { email: { '$eq': 'john@example.com' } } ]}, { hint: { _id: 1 } })
```

In my opinion, the new and improved performance behavior should be opt-in and disabled by default.

### To Reproduce

1. Set up an Amazon DocumentDB database
2. Use it with Payload v2.0.14
3. Attempt to log in

### Payload Version

2.0.14

### Adapters and Plugins

db-mongodb

**Comment by denolfe** [comment]
Thank you for the report @hdodov. We're looking into this immediately. Sounds like we need to add DocumentDB to our test suite to prevent issues like this in the future as well.

**Comment by hdodov** [comment]
@denolfe I'd love that! Please, let me know if there's any way I can help. We plan on using DocumentDB on production, so I'm very interested in making sure that Payload is stable working with it.

Thank you very much for the speedy reaction!

**Comment by Bohooslav** [comment]
I have the same issue with DocumentDB

**Comment by denolfe** [comment]
We're looking at adding an opt-out flag for this functionality. It doesn't look like we can dynamically detect if DocumentDB is being used.

**Comment by AlessioGr** [comment]
Im not sure why this issue occurs in the first place. `id` is neither a multi key, nor a partial, nor a sparse index.

Maybe this is actually an issue in Amazon DocumentDB?

**Comment by hdodov** [comment]
@AlessioGr could be. In my opinion, you should make a minimum reproducible example and take Payload and Mongoose out of the picture. If the problem still occurs, then it's likely some weird issue with DocumentDB and we should raise it as such.

I could try to do that myself, but to be frank, I've had no prior experience with MongoDB up to this point. I believe you'd have better context of the whole issue. I mean, I don't even know what are multi-key, partial, and sparse indices… 😄

**Comment by hdodov** [comment]
@denolfe @AlessioGr this issue is preventing me from upgrading Payload to newer versions. If you've decided to tackle it with an opt-out flag, I can maybe contribute with a PR?

**Comment by AlessioGr** [comment]
There's a PR here: https://github.com/payloadcms/payload/pull/3997 just hasn't been merged yet

**Comment by dhaub-exelixis** [comment]
@hdodov I know your `mongoose.set("debug", true)` call was just a temporary fix, but I'm curious where you set that flag. I haven't been able to get that to work the way you described. I have some changes in my project that I really would like to test, but the issues with Amazon docdb are preventing me from working.

**Comment by hdodov** [comment]
@dhaub-exelixis adding `mongoose.set("debug", true)` doesn't fix anything. It's just a flag that tells Mongoose to output more information. I used it to diagnose the issue, not fix it.

**Comment by dhaub-exelixis** [comment]
> @dhaub-exelixis adding `mongoose.set("debug", true)` doesn't fix anything. It's just a flag that tells Mongoose to output more information. I used it to diagnose the issue, not fix it.

Ope, thanks for the clarification.

To get this to work, I did have to downgrade the mongoose adapter package to an earlier version, so it isn't just dependent on the payload version. I'll be eagerly awaiting the PR that's been opened though!
