### ISSUE TITLE
Live preview - relations are not fetched

### ISSUE THREAD

**Issue by RickGeersing** [payloadcms/payload#3990]
### Describe the Bug

Hey, I have an issue when implementing the live preview in svelte. I get the data just fine but when it comes to upload/relationship fields like media it only returns an ID. It seems to put the request depth to 0 even though I specify it to be 2. 

Here I have my `+page.svelte` for rendering the live-preview frontend-wise
```typescript
<script lang="ts">
    import { ready, subscribe, unsubscribe } from "@payloadcms/live-preview";
    import { getTemplateByPage } from "@src/util/getTemplateByPage.js";
    import { onDestroy, onMount } from "svelte";
    import Page from "../[...url]/+page.svelte";

    export let data;

    let pageData: any = undefined;
    let template: any = undefined;
    let subscription: any = undefined;

    async function handleChange(data: any) {
        pageData = data;
        template = await getTemplateByPage(data);
    }

    onMount(() => {
        const serverUrl = import.meta.env.VITE_PAYLOAD_EXTERNAL_URL;
        subscription = subscribe({
            callback: handleChange,
            depth: 2,
            serverURL: serverUrl,
            initialData: pageData,
        });
        ready({ serverURL: serverUrl });
    });

    onDestroy(() => {
        unsubscribe(subscription);
    });
</script>

{#if template !== undefined}
    <Page
        data={{
            header: data.header,
            footer: data.footer,
            template: template,
            url: "/live-preview",
            page: pageData,
        }}
    />
{/if}
```

### To Reproduce

1. Have a collection like `pages` in live preview config
2. Add an relationship field to that page.
3. Fill the relationship field
4. Log the data variable in the `handleChange` function.
5. You'll see that the relationship field is returned by id not by object

### Payload Version

2.0.14

**Comment by matthijs166** [comment]
What version of @payloadcms/live-preview is used here in the frond end?

**Comment by RickGeersing** [comment]
I will close this issue, since it's no longer an issue. Forgot to update the frontend package.. Latest version of `@payloadcms/live-preview` fixed this issue.

**Comment by timoconnellaus** [comment]
I was able to solve this by making sure the related tables had the correct access control. If you don't have access it returns the ID of the relation
