### ISSUE TITLE
Provided Dockerfile - Build missing `.next/BUILD_ID`

### ISSUE THREAD

**Issue by shutupflanders** [payloadcms/payload#3992]
### Describe the Bug

I've built the provided Dockerfile from `npx create-payload-app my-project -t website` pushed my image to dockerhub and I'm currently trying to deploy the sample app on Kubernetes to showcase to my team.

The container won't start, it fails with the following error:
```
(node:225) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
unhandledRejection [Error: ENOENT: no such file or directory, open '/home/node/app/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/node/app/.next/BUILD_ID'
}
```

Am I missing something? has anyone tested this recently? there are no code changes and the `.next` directory does not get added to the built container at all. (I've also ran the built container locally to verify)
![image](https://github.com/payloadcms/payload/assets/3372012/4646701d-a1fe-4925-be39-1705e6b6af99)

### To Reproduce

1. Create a new app using 
`npx create-payload-app my-project -t website`
2. Spin up mongo in the docker-compose stack so the payload build script can access it 
`docker compose up mongo`
3. Build the production container
`docker build --network host -t payloadcms:v0.0.1 --no-cache .`
4. Run the container
`docker run --rm --network=host --env NEXT_PUBLIC_SERVER_URL=http://localhost:3000 --env PAYLOAD_PUBLIC_SERVER_URL=http://localhost:3000 --env PORT=3000 --env DATABASE_URI=mongodb://localhost:27017/<<redacted>> --env PAYLOAD_SECRET=<<redacted>> REVALIDATION_KEY=<<redacted>> --env NEXT_PRIVATE_REVALIDATION_KEY=<<redacted>> --env PAYLOAD_CONFIG_PATH=/home/node/app/dist/payload/payload.config.js payloadcms:v0.0.1`

### Payload Version

the latest version that is produced from `npx create-payload-app my-project -t website`

### Adapters and Plugins

db-mongodb

**Comment by shutupflanders** [comment]
I've managed to get this working, adding `COPY --from=builder /home/node/app/.next ./.next` to the dockerfile solved it.
I'll open a PR over the weekend if I get chance, unless anyone wants to pop a hotfix in instead.

**Comment by jmikrut** [comment]
Hey @shutupflanders — thanks for pointing us to a fix!

My only thought is that we should we only copy if the `.next` folder exists. If you would like to make a PR for this, that would be absolutely fantastic. We would happily merge. I believe we have dockerfiles for each template, so this PR would need to address the dockerfile in 3 places.

Let's get you added as a contributor!

**Comment by shutupflanders** [comment]
Thanks @jmikrut - #4029 created.

There's no mechanism for Docker to fail gracefully if a directory does not exist when trying to copy, so I've done the next best thing - create it first.

**Comment by denolfe** [comment]
Responded to #4029 with feedback, waiting on updates.
