### ISSUE TITLE
Validate type don't allow async validation on fields.

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#40]
# Bug Report

I'm trying to get file information for an upload field so I can check for its filetype but typescript is complaining about not being able to return a promise.

## Expected Behavior

I can create validate functions using async as described here: https://payloadcms.com/docs/fields/overview#validation

## Current Behavior

I get typescript errors because the return type is `string | boolean` rather than `Promise<string | boolean>`.

## Detailed Description

Payload version: 0.2.4

![image](https://user-images.githubusercontent.com/3854592/105944370-86f56980-60a6-11eb-9ef7-93417b5a92dd.png)

**Comment by DanRibbens** [comment]
Hi @richardvanbergen, good catch! I'm looking at this now.
I was able to reproduce it and I can have a patch up for you soon.

**Comment by DanRibbens** [comment]
Should be good to go once you update to v0.2.9
