### ISSUE TITLE
Relationship field with hasMany saves to database but doesn't show value in admin

### ISSUE THREAD

**Issue by jakobpevec** [payloadcms/payload#4006]
### Describe the Bug

I'm using postgres adapter. Relationship field with hasMany creates an entry in products_rel table but doesn't show value in admin.

Example:
**Products collection:**
```js
{
      type: "relationship",
      name: "productVariants",
      label: "Variants",
      relationTo: ['productvariants'],
      hasMany: true
  }
```

https://github.com/payloadcms/payload/assets/69215693/cd02f42a-f84c-40e5-ac06-d3480ecda658

### To Reproduce

Create two collections and connect them with a relationship field that has hasMany set to true.

```js
{
      type: "relationship",
      name: "productVariants",
      label: "Variants",
      relationTo: ['productvariants'],
      hasMany: true
  }
```

### Payload Version

2.0.15

### Adapters and Plugins

db-postgres

**Comment by DanRibbens** [comment]
This was fixed in an earlier version.

**Comment by DanRibbens** [comment]
Please tag me if you still experience this issue on latest versions. I tested with Payload v2.5.0 and db-postgres v0.2.2
