### ISSUE TITLE
Resolving Query Errors in AfterChangeHook When Revalidating Pages with Updated Forms

### ISSUE THREAD

**Issue by ficeco** [payloadcms/payload#4008]
### Describe the Bug

Using next-payload, db-postgres, and form-builder.

When a form is updated in admin, I'm trying to revalidate the pages that have the form on them. To add the form to the different pages, I have a "form" relationship field to select the form, inside a "formBlock" block, that I am using in a "blocks" blocks field that's in a "layout" tabs field, so a user can drop in the "formBlock" block into a layout and select the form that should show.

In order to do this I'm trying to set up a "revalidateForm" AfterChangeHook with a query that looks for the pages that have the same form (via its ID) in the "formBlock" block in the "layout" tabs field, and will run a revalidateCollection function to revalidate those pages found in the query, but I can't seem to get the query to work.

My current query is 

```ts
const res = await payload.find({
    collection: "pages",
    depth: 0,
    where: {
      "layout.blocks.form": {
        equals: 1,
      },
    },
  });
```
  
  Though I've tried a bunch of variations and get either "TypeError: Cannot read properties of undefined" or "syntax error at or near "="]

### To Reproduce

create site via npm install create-next-app and npm install @payloadcms/next-payload payload 
using the db-postgres adapter
install form-builder plugin and set things up in config
set up "formBlock" Block with "form" relationship field
set up pages collection with "layout" tabs field, that has a "blocks" block field, with the "formBlock" block as its blocks.
create a page and add the "formBlock" block to the "blocks" block field in the "layout" tab field
create an AfterChangeHook, right now mine looks like this: 

```ts
import payload from "payload";
import type { AfterChangeHook } from "payload/dist/collections/config/types";

import { revalidate } from "../utilities/revalidateCollection";

export const revalidateForm: AfterChangeHook = async ({
  doc,
  req: { payload },
}) => {

  const res = await payload.find({
    collection: "pages",
    depth: 0,
    where: {
      "layout.blocks.form": {
        equals: 1,
      },
    },
  });

  console.log(res);

  return doc;
};
```

add the revalidateForm hook to the formsOverrides as an afterChange hook.

Update a form in the admin and see that there's a "TypeError: Cannot read properties of undefined" error logged. 

### Payload Version

2.0.15

### Adapters and Plugins

db-postgres, form-builder

**Comment by JessChowdhury** [comment]
Hi @ficeco, could you provide a basic reproduction of your project with the failing query so we can take a look?

**Comment by ficeco** [comment]
Hey @JessChowdhury, I've given you access to my repo.

**Comment by JessChowdhury** [comment]
@ficeco thanks for providing access to your repo, I'm able to replicate the same errors you saw - this appears to be a genuine bug with the postgres database adapter. I'm looking into it today and will get back to you with a resolution 👍

**Comment by ficeco** [comment]
@JessChowdhury any update on this?

**Comment by ficeco** [comment]
Thanks @JessChowdhury, looks like the "this related PR" link links back to this issue. Would it be [this PR](https://github.com/payloadcms/payload/pull/4237) that you're referencing?
