### ISSUE TITLE
relationship value sometimes flat, sometimes not

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#4012]
### Link to reproduction

/

### Describe the Bug

I find relationship fields being inconsistent in it's data structure. Sometimes it's flat, like this:
```
 {
      id: '653b76516caed0ceda172705',
      slug: 'diensten',
      path: '/diensten',
      url: 'http://localhost:4321/diensten',
      type: 'blocks',
      blocks: [Array],
      meta: {},
      _status: 'published',
      createdAt: '2023-10-27T08:35:29.764Z',
      updatedAt: '2023-10-31T11:35:30.731Z'
  },
```

And sometimes it's structured like this:
```
 {
    value: {
      id: '653b76516caed0ceda172705',
      slug: 'diensten',
      path: '/diensten',
      url: 'http://localhost:4321/diensten',
      type: 'blocks',
      blocks: [Array],
      meta: {},
      _status: 'published',
      createdAt: '2023-10-27T08:35:29.764Z',
      updatedAt: '2023-10-31T11:35:30.731Z'
    },
    relationTo: 'pages'
  },
```

I searched the docs, but can't find anything on this topic + i did not have this issue a couple of weeks ago.

Am I missing something, or is this is bug, therefore I should make a reproduction?

### To Reproduce

- Create a collection
- create a relationship field to that collection
- look at the data structure

### Payload Version

2.0.13

### Adapters and Plugins

/

**Comment by JarrodMFlesch** [comment]
The first one is the shape if you use relationTo: "some-collection"

The second is when you specify a relation to many collections, i.e relationTo: ["some-collection"]

If this really is an issue we will need a reproduction.

I will close for now, thanks!
