### ISSUE TITLE
Built in Lexical => HTML converter does not work

### ISSUE THREAD

**Issue by dylankuipers** [payloadcms/payload#4023]
### Describe the Bug

We had a custom serializer on our frontend and were now trying to switch to the built-in serializer. 

My field looks like this:

`import {
  HTMLConverterFeature,
  lexicalEditor,
  lexicalHTML,
} from '@payloadcms/richtext-lexical'
import type { Field } from 'payload/types'

export const writeup: Field = {
  type: 'row',
  fields: [
    {
      name: 'writeup',
      type: 'richText',
      editor: lexicalEditor({
        features: ({ defaultFeatures }) => [
          ...defaultFeatures,
          // The HTMLConverter Feature is the feature which manages the HTML serializers. If you do not pass any arguments to it, it will use the default serializers.
          HTMLConverterFeature({}),
        ],
      }),
    },
    lexicalHTML('writeup', {
      name: 'writeup_html',
    }),
  ],
}`

The field already existed when we switched to the built-in serializer. And now payload gives an error when trying to access the dashboard. This is the error that is provided:

`[14:05:41] ERROR (payload): Error: You cannot use the lexicalHTML field because the lexical field was not found
    at currentHook (C:\wamp64\www\bit-academy\fulldev\monorepo\payload\node_modules\@payloadcms\richtext-lexical\src\field\features\converters\html\field\index.ts:42:19)
    at C:\wamp64\www\bit-academy\fulldev\monorepo\payload\node_modules\payload\src\fields\hooks\afterRead\promise.ts:222:37
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async promise (C:\wamp64\www\bit-academy\fulldev\monorepo\payload\node_modules\payload\src\fields\hooks\afterRead\promise.ts:190:7)
    at async Promise.all (index 7)
    at async afterRead (C:\wamp64\www\bit-academy\fulldev\monorepo\payload\node_modules\payload\src\fields\hooks\afterRead\index.ts:67:3)`
    
  
  
  When I comment out the "lexicalHTML" field it does not give any errors.

### To Reproduce

- Use the built-in Lexical => HTML converter provided in the payload documentation

### Payload Version

2.0.13

**Comment by silveltman** [comment]
I'm having the same issue. Went through the code and added some consolelogs:
```
        hooks: {
            afterRead: [
                async ({ collection, context, data, originalDoc, siblingData })=>{
                    console.log('lexicalFieldName', lexicalFieldName) // <<<<<<<<< ADDED
                    console.log('collectionFields', collection.fields)  // <<<<<<<<< ADDED
                    const lexicalField = collection.fields.find((field)=>'name' in field && field.name === lexicalFieldName);
                    const lexicalFieldData = siblingData[lexicalFieldName];
                    if (!lexicalFieldData) {
                        return '';
                    }
                    if (!lexicalField) {
                        throw new Error('You cannot use the lexicalHTML field because the lexical field was not found');
                    }
```
it logs the following:
```
lexicalFieldName rich
collectionFields [
  { type: 'tabs', tabs: [ [Object], [Object] ], admin: {} },
  {
    name: 'updatedAt',
    admin: { disableBulkEdit: true, hidden: true },
    label: {
      ar: 'تم التحديث في',
      az: 'Yeniləndiyi tarix',
      bg: 'Обновен на',
      cs: 'Aktualizováno v',
      de: 'Aktualisiert am',
      en: 'Updated At',
      es: 'Fecha 
...
```

I think it can't find it because it is in tabs?

Another weird this is then when I log `console.log('siblingData', siblingData)`, it logs the doc data WITHOUT the richtext field.

I have the richtext field in a **unnamed** tab, just a label.

**Comment by AlessioGr** [comment]
Closing in favor of #4034 (duplicate issue), which explains the core issue a bit better
