### ISSUE TITLE
defaultSort breaks display of versions with PostgreSQL

### ISSUE THREAD

**Issue by DavidOliver** [payloadcms/payload#4027]
### Describe the Bug

When the `defaultSort` collection config is in use and versions are enabled, the versions cannot be loaded in the admin. (At least when using PostgreSQL.)

```plain
[15:46:24] ERROR (payload): APIError: Cannot find field for path at ordering
    at getTableColumnFromPath (/data/projects/ac/payload/node_modules/@payloadcms/db-postgres/src/queries/getTableColumnFromPath.ts:435:9)
    at buildQuery (/data/projects/ac/payload/node_modules/@payloadcms/db-postgres/src/queries/buildQuery.ts:67:89)
    at find (/data/projects/ac/payload/node_modules/@payloadcms/db-postgres/src/find/findMany.ts:44:80)
    at Object.findVersions (/data/projects/ac/payload/node_modules/@payloadcms/db-postgres/src/findVersions.ts:31:18)
    at findVersions (/data/projects/ac/payload/node_modules/payload/src/collections/operations/findVersions.ts:76:44)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at findVersionsHandler (/data/projects/ac/payload/node_modules/payload/src/collections/requestHandlers/findVersions.ts:40:20)
```

(Is this to do with the field names being prefixed with `version_` in the `_collection-name_v` tables?)

### To Reproduce

1. Use `db-postgres` and create a collection that uses versions.
2. Create and subsequently modify an entry/document in the aforementioned collection.
3. Observe that versions are successfully loaded in the admin.
4. Use the `defaultSort` config option.
5. Observe that versions cannot be loaded in the admin.

Some bits of my collection's config:

```ts
import { CollectionConfig } from 'payload/types';

const Interests: CollectionConfig = {
  slug: 'interests',
  defaultSort: 'ordering', // this 'ere!
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'ordering', '_status'],
    pagination: {
      defaultLimit: 100,
    },
  },
  versions: {
    drafts: true,
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      unique: true,
      index: true,
      required: true,
    },
    {
      name: 'ordering',
      type: 'number',
      label: 'Ordering (ascending)',
      unique: true,
      index: true,
      required: true,
      admin: {
        position: 'sidebar',
        description: 'Entries are ordered for visitors/users based on this field, in ascending order.',
        step: 1,
        placeholder: '(Positive integer)',
        autoComplete: 'off',
      },
    },
  ],
}
```

### Payload Version

2.0.15

### Adapters and Plugins

db-postgres, bundler-webpack, ricktext-lexical, plugin-cloud (installed by default)

**Comment by jmikrut** [comment]
Hey @DavidOliver — thanks for the report! We're on it!

**Comment by thompsonsj** [comment]
I wonder if this is related to the error I get when typing into a select field to search on a collection that has `defaultSort`.

```
{
    "errors": [
        {
            "name": "QueryError",
            "data": [
                {
                    "path": "-updatedAt"
                }
            ],
            "message": "The following path cannot be queried: -updatedAt"
        }
    ],
    "stack": "QueryError: The following path cannot be queried: -updatedAt\n    at validateQueryPaths (/workspace/node_modules/payload/dist/database/queryValidation/validateQueryPaths.js:74:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async find (/workspace/node_modules/payload/dist/collections/operations/find.js:97:13)\n    at async findHandler (/workspace/node_modules/payload/dist/collections/requestHandlers/find.js:29:24)"
}
```

**Comment by BrianJM** [comment]
> I wonder if this is related to the error I get when typing into a select field to search on a collection that has `defaultSort`.
> 
> ```
> {
>     "errors": [
>         {
>             "name": "QueryError",
>             "data": [
>                 {
>                     "path": "-updatedAt"
>                 }
>             ],
>             "message": "The following path cannot be queried: -updatedAt"
>         }
>     ],
>     "stack": "QueryError: The following path cannot be queried: -updatedAt\n    at validateQueryPaths (/workspace/node_modules/payload/dist/database/queryValidation/validateQueryPaths.js:74:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async find (/workspace/node_modules/payload/dist/collections/operations/find.js:97:13)\n    at async findHandler (/workspace/node_modules/payload/dist/collections/requestHandlers/find.js:29:24)"
> }
> ```

I am getting this error (in MongoDB) when searching a collection with `defaultSort` defined (in `2.4.0` and `2.5.0`. I could not find a related issue but I will create one when I have a moment.
