### ISSUE TITLE
Vite bundler adds `/undefined` prefix to admin API calls

### ISSUE THREAD

**Issue by ChrisGV04** [payloadcms/payload#4033]
### Link to reproduction

https://payloadcms.com/docs/admin/vite

### Describe the Bug

I created a project using the Vite bundler as described in the docs and for some reason when I build the production version, the admin UI never loads.

I inspected the network calls and it seems as if it's trying to call `http://localhost:3000/undefined/api`. Notice that it is adding `/undefined` to the request path, which obviously returns a 404 error.

Here is a small snippet of my payload config. I omitted other configs that seem irrelevant since I don't use any special configs nor bundler overrides.

```ts
import { viteBundler } from '@payloadcms/bundler-vite';
import { mongooseAdapter } from '@payloadcms/db-mongodb';
import { buildConfig } from 'payload/config';

export default buildConfig({
  db: mongooseAdapter({
    url: process.env.MONGODB_URI,
  }),

  serverURL: `${process.env.PAYLOAD_PUBLIC_SERVER_URL}`,
  routes: { api: '/cms', admin: '/admin' },

  admin: {
    bundler: viteBundler(),
  },
  // ...
});
```

Only changing the bundler to webpack makes everything work fine again.

### To Reproduce

Just create a blank payload project using the Vite bundler. Build the project and run `npm run serve`.

If you visit the admin panel, it never loads and the network inspector shows that the requests have an `/undefined` prefix added for some reason.

### Payload Version

2.0.15

### Adapters and Plugins

db-mongodb@1.0.6, bundler-vite@0.1.3

**Comment by JarrodMFlesch** [comment]
@jmikrut it feels like the payload config is not being transpiled. The issue is stemming from vite replacing env vars correctly in dev, but not when building. This is how we are [passing the config](https://github.com/payloadcms/payload/blob/main/packages/bundler-vite/src/entry.tsx#L3) now. Maybe we should sync up.
