### ISSUE TITLE
Live Preview serverURL not working

### ISSUE THREAD

**Issue by cbratschi** [payloadcms/payload#4046]
### Link to reproduction

private repo

### Describe the Bug

A serverURL has to be passed to the useLivePreview() hook. In our case we set routes.api in the Payload config to '/cms/api'. The current implementation seems only to work with '/api':

If we set serverURL to http://localhost:3000/cms the API calls are correct but the useLivePreview() hook never returns any new data. This is because the serverURL in https://github.com/payloadcms/payload/blob/main/packages/live-preview/src/handleMessage.ts#L16C18-L16C18 does not match to http://localhost:3000.

If we set serverURL to http://localhost:3000 all API calls go to http://localhost:3000/api which is wrong according to our configuration. In this case we got values from useLivePreview().

I guess we should use http://localhost:3000 as serverURL and the hook should respect the routes.api setting i.e. add /cms/api to the URL and not just /api.

### To Reproduce

Set routes.api to '/cms/api' and use live preview.

### Payload Version

2.0.15

### Adapters and Plugins

db-mongodb, bundler-webpack, live-preview

**Comment by jacobsfletch** [comment]
Hey @cbratschi you just need to pass your `apiRoute` through the `useLivePreview` hook. Turns out that argument was not in our documentation, so I've added it in #4073. Are you using TypeScript on your front-end? This argument would have appeared in your type hints despite the lack of documentation. Let me know if you're still having troubles after using adding this in. Here's an example:

```ts
  useLivePreview({
    serverURL: 'http://localhost:3000',
    apiRoute: '/cms',
  })
```

**Comment by cbratschi** [comment]
@jacobsfletch TypeScript shows me this:

```TS
export declare const useLivePreview: <T extends unknown>(props: {
    depth?: number;
    initialData: T;
    serverURL: string;
}) => {
    data: T;
    isLoading: boolean;
};
//# sourceMappingURL=index.d.ts.map
```

I don't see the apiRoute parameter.

**Comment by jacobsfletch** [comment]
@cbratschi ahhhh I see now. I will adjust this 👍 Thank you for pointing this out
