### ISSUE TITLE
consolidateHTMLConverters not published yet

### ISSUE THREAD

**Issue by hai-qiu-bpc** [payloadcms/payload#4049]
### Describe the Bug

Hi
The changes with this commit "chore: Better Lexical documentation, minor improvements to HTML converter feature" are not published in the newest version of the @payloadcms/richtext-lexical package yet.

I've tried to use consolidateHTMLConverters as mentioned in the documentation, but it shows me that the package is not exporting this member yet.

Could you please update the package so I can use that function.

### To Reproduce

    "@payloadcms/richtext-lexical": "^0.1.16",
    "payload": "^2.0.16",

### Payload Version

2.0.16

**Comment by AlessioGr** [comment]
@hai-qiu-bpc This should now be included in v0.1.17 which was published yesterday :)
