### ISSUE TITLE
The CollectionConfig type is typed wrongly for strict mode

### ISSUE THREAD

**Issue by zaunermax** [payloadcms/payload#405]
# Bug Report

When using the `CollectionConfig` type, it's not possible to provide `null` for the height or width parameter to maintain the aspect ratio in Typescript's strict mode.

## Expected Behavior

The `CollectionConfig` type should allow to pass null to `height` or `width` in Typescript strict mode.

## Steps to Reproduce

1. Setup new payload project
2. Set Typescript to strict mode
3. Create an upload collection
4. Try to pass `null` to `height` or `width` in the `imageSizes` array.

## Current workaround is to `@ts-ignore` the null param:

```
upload: {
  staticURL: '/media/profile',
  staticDir: './media/profile',
  adminThumbnail: 'card',
  imageSizes: [
    {
      name: 'tablet',
      width: 640,
      // payload is not typed for strict typing
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      height: null,
      crop: 'left top',
    },
    {
      name: 'mobile',
      width: 320,
      // payload is not typed for strict typing
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      height: null,
      crop: 'left top',
    },
  ],
},
```

**Comment by jmikrut** [comment]
Hey @zaunermax — beta published with fix!

```
payload@0.13.13-beta.0
```
