### ISSUE TITLE
Can not change ownership of Payload Cloud project

### ISSUE THREAD

**Issue by dylankuipers** [payloadcms/payload#4051]
### Link to reproduction

payload cloud

### Describe the Bug

I am trying to change the ownership of my payload cloud project, from my account to a team. After changing the ownership it continuously loads with the title: `INITIAL DEPLOYMENT IN PROGRESS` and the status: `Setting up your project`.

It never stops loading and if I refresh the page and go back to my projects it is still on my account and the ownership is set back to my email.

### To Reproduce

Change ownership of your payload cloud project from a user to a team.

### Payload Version

Cloud

### Adapters and Plugins

Payload Cloud

**Comment by denolfe** [comment]
@dylankuipers Can you please provide the project ID from Settings -> Billing? I can look into this.

**Comment by dylankuipers** [comment]
@denolfe Yes, this is my project ID: 654b6e7ca24033b20bf2b720

**Comment by dylankuipers** [comment]
@denolfe When I try to change ownership again now, it actually loads instantly and sends me back to my overview of projects (in my team), but then when I check the ownership again it's set back to my email.

**Comment by denolfe** [comment]
Hey @dylankuipers , if this is still an issue, please email info@payloadcms.com.

Moving projects to a different team can be done by support.
