### ISSUE TITLE
blockType missing on blocks in live preview

### ISSUE THREAD

**Issue by paulpopus** [payloadcms/payload#4056]
### Describe the Bug

When using a live preview setup, the blockType of a block inside a `blocks` field type is missing, causing issues with a serialiser setup that renders the frontend:

![image](https://github.com/payloadcms/payload/assets/35137243/a88266d8-7843-48c2-ba38-66fdd8e7d00b)

If you save the content, and _then_ edit the field the blockType is present, so this might be a bug with what the block's data is prior to being saved. ~~This only happens to new blocks.~~ Also happens when reordering blocks. Worth noting that I didn't see the same behaviour for blocks inside lexical.

### To Reproduce

Nextjs with Payload live preview enabled on a global with a `blocks` field.

The frontend will have a BlocksSerialiser that simply loops through the array of blocks and conditionally renders the correct block based on the blockType value.

### Payload Version

2.0.15

### Adapters and Plugins

db-postgres, db-lexical, livepreview

**Comment by jacobsfletch** [comment]
Hey @paulpopus this was potentially fixed with #4045. Hoping to get some new releases out today to include these changes. I'm going to go ahead and close out this issue, but let me know if you're still having issues with this one you've received the updates.
