### ISSUE TITLE
Make aliasing node dependent hooks more easy

### ISSUE THREAD

**Issue by zaunermax** [payloadcms/payload#406]
# Bug Report

Currently I am following [this documentation](https://payloadcms.com/docs/admin/webpack#aliasing-server-only-modules) to alias my node.js dependent hooks. Though it can get very messy once you have a lot of hook files going in your project. I decided to write a small helper script that resolves all files in my `collections` folder which uses the `fs` package. Now I know, that the `fs` package is not a browser friendly package (obviously) and the payload admin panel is built with webpack for the browser.

My question is, if it would be possible to [mock node.js](https://webpack.js.org/configuration/node/) and/or provide a [node alias fallback ](https://webpack.js.org/configuration/resolve/#resolvefallback) in the base webpack config which is used to transpile the `payload.config.ts` so convenience scripts as mine would be possible at least for build time? :thinking: Changing the webpack config in the `payload.config.ts` has obviously no effect, as setting the node mock property when already using it would make no sense, it would have to be a default webpack config from payload I guess? :thinking: 

Thanks in advance :raised_hands: 

## Expected Behavior

I would expect, that the `fs` package works at least in the config file of payload. Maybe I am wrong?

## Current Behavior

This is how my config looks like for a small sample project.

```typescript
import { buildConfig } from "payload/config";
import dotenv from "dotenv";
import path from "path";
import {
  VideoCollection,
  PersonCollection,
  ProfilePictureCollection,
  MessageCollection,
} from "./collections";
import { getEnvVarOrDefault, resolveHooksInDir } from "./utilities";

dotenv.config();

const mockModulePath = path.resolve(__dirname, "./collections/mock.module.js");

export default buildConfig({
  serverURL: getEnvVarOrDefault("PAYLOAD_PUBLIC_SERVER_URL", ""),
  collections: [
    VideoCollection,
    PersonCollection,
    ProfilePictureCollection,
    MessageCollection,
  ],
  typescript: {
    outputFile: path.resolve(__dirname, "./types/payload-generated.types.ts"),
  },
  admin: {
    webpack: (config) => ({
      ...config,
      node: {
        global: true,
      },
      resolve: {
        ...config.resolve,
        alias: resolveHooksInDir("collections").reduce(
          (alias, dirPath) => ({
            ...alias,
            [dirPath]: mockModulePath,
          }),
          config?.resolve?.alias
        ),
      },
    }),
  },
});

```

my utility looks like this:

```typescript
import { readdirSync } from "fs";
import { resolve } from "path";

const filterCollectionFiles = ({ files }: { files: string[] }) =>
  files.some((file) => file.includes("hook"));

export const resolveHooksInDir = (path: string): string[] =>
  readdirSync(path, { withFileTypes: true })
    .filter((file) => file.isDirectory())
    .map((dir) => resolve(path, dir.name))
    .map((resolvedPath) => ({
      parentDir: resolvedPath,
      files: readdirSync(resolvedPath),
    }))
    .filter(filterCollectionFiles)
    .flatMap(({ files, parentDir }) =>
      files.map((file) => resolve(parentDir, file))
    )
    .filter((fileName) => fileName.includes("hook"));

```

**Comment by jmikrut** [comment]
Hey @zaunermax — we do agree that the way Payload handles aliasing server modules can be a handful. In the future, we plan to more eloquently solve this but it's an extremely difficult problem that is quite difficult to solve in a bulletproof way. We tried all sorts of approaches to this issue before our beta release but ultimately landed on utilizing custom Webpack configs to allow our users to take control of exactly what should be included in their client bundle, and what should not.

In the interim, I think there is an easy solution here for you.

Write a small script to check if your code is running in the browser or the server, like so:

```js
const canUseDOM = !!(
  (typeof window !== 'undefined'
    && window.document && window.document.createElement)
);

export default canUseDOM;
```

Then in your Payload config, you can do something like this:

```js
  webpack: (config) => {
    if (canUseDOM) {
      return config;
    }

    return {
      ...config,
      node: {
        global: true,
      },
      resolve: {
        ...config.resolve,
        alias: resolveHooksInDir("collections").reduce(
          (alias, dirPath) => ({
            ...alias,
            [dirPath]: mockModulePath,
          }),
          config?.resolve?.alias
        ),
      },
    }
  },
```

That way you can use your convenience script, relying on `fs`, but it will only be executed on the server, where it'll work.

This is probably not a complete answer, and I have not tested this code, but this should be entirely possible with the right approach.

I think this belongs more in a discussion though vs. an issue. Do you mind keeping this going in our Discussions instead? I think it could definitely be valuable for others!

**Comment by zaunermax** [comment]
Yes you're of course right, this surely belongs into the discussions thread :raised_hands: Thanks for the quick answer.
