### ISSUE TITLE
Env variables undefined with vite bundlers in payload.config

### ISSUE THREAD

**Issue by xHomu** [payloadcms/payload#4060]
### Link to reproduction

https://github.com/manawiki/repay

### Describe the Bug

Bumping @payloadcms/bundler-vite to 0.1.4 cause `localhost:3000/admin` to trigger the dreaded vite process.env error in development:

<img width="484" alt="image" src="https://github.com/payloadcms/payload/assets/84349818/c225b407-b512-4947-af63-91d8a9ec1773">

Ironically, this works fine in production build.

### To Reproduce

1. Copy .env.example to .env and insert MONGODB_URI and PAYLOAD_SECRET 
2. yarn; yarn dev
3. Go to localhost:3000, navigate to the Admin interface
4. This should work so far!
5. update package.json `"@payloadcms/bundler-vite": "0.1.4" and rest console.
6. Repeat Steps 2 & 3
7. process.env is now undefined for Payload dashboard, causing /admin to break.

My best guess is this is related to #4057 ?

### Payload Version

2.1.0

### Adapters and Plugins

db-mongodb bundler-vite richtext-lexical

**Comment by smoglica** [comment]
I'm experiencing the same issue.

![Screenshot from 2023-10-17 22-38-47](https://github.com/payloadcms/payload/assets/17332096/65f3aabf-8b90-4270-b8df-2e96183c787a)

Seems that `process.env` get replaced first with `{}` then the replacement for the other envs is not possible because the string contains the unexpected `{}.`

**Comment by JarrodMFlesch** [comment]
I am looking into it 👀

**Comment by smoglica** [comment]
@JarrodMFlesch 

Thanks for your work.

I've updated to latest version of `payload` and `@payloadcms/bundler-vite`. I still have the issue. I see a blank page with this error.

![Screenshot from 2023-11-28 08-47-48](https://github.com/payloadcms/payload/assets/17332096/12b9d8db-b7fb-4b8f-9179-55ea662656e3)

This happens only when building payload and trying to serve. In development doesn't happen

**Comment by xHomu** [comment]
#4099 fixed this for us, thanks!
