### ISSUE TITLE
Edit SVG Uploads and Size Previews

### ISSUE THREAD

**Issue by cbratschi** [payloadcms/payload#4064]
### Link to reproduction

private repo

### Describe the Bug

SVG images can be edited in the Payload upload collection but the image is not shown in the edit dialog. It should not be possible to edit SVG and other vector formats. Only images (image/* content type) should be allowed to be edited.

The second issue is that preview sizes do not work for SVGs because those sizes are  all undefined. Payload should not list any missing image sizes. We have JPEG images which are not available in all resolutions e.g. to avoid upscaling of images. Here we see that /media/undefined is used as img src URL.

Sample SVG data:

```JSON
{
  "filename": "icon.svg",
  "mimeType": "image/svg+xml",
  "sizes": {
    "media": {},
    "standard": {},
    "tablet": {},
    "mobile": {}
  }
}
```

Sample JPEG:

```JSON
{
  "filename": "ArtShaker.jpg",
  "mimeType": "image/jpeg",
  "filesize": 419553,
  "width": 1080,
  "height": 1350,
  "sizes": {
    "media": {
      "width": null,
      "height": null,
      "mimeType": null,
      "filesize": null,
      "filename": null
    },
    "standard": {
      "url": "/media/ArtShaker-960x1200.jpg",
      "width": 960,
      "height": 1200,
      "mimeType": "image/jpeg",
      "filesize": 168948,
      "filename": "ArtShaker-960x1200.jpg"
    },
    "tablet": {
      "url": "/media/ArtShaker-640x800.jpg",
      "width": 640,
      "height": 800,
      "mimeType": "image/jpeg",
      "filesize": 90867,
      "filename": "ArtShaker-640x800.jpg"
    },
    "mobile": {
      "url": "/media/ArtShaker-320x400.jpg",
      "width": 320,
      "height": 400,
      "mimeType": "image/jpeg",
      "filesize": 29744,
      "filename": "ArtShaker-320x400.jpg"
    }
  }
}
```

### To Reproduce

Upload SVG to upload collection. Edit SVG and preview sizes.

### Payload Version

2.1.0

### Adapters and Plugins

db-mongodb, bundler-webpack, live-preview

**Comment by cbratschi** [comment]
Preview sizes looks like this:
<img width="812" alt="Bildschirmfoto 2023-11-08 um 22 59 16" src="https://github.com/payloadcms/payload/assets/3909121/64d6fa90-26fb-4307-ad72-e3d51b2055cd">

**Comment by cbratschi** [comment]
And the JPEG:
<img width="870" alt="Bildschirmfoto 2023-11-08 um 23 00 53" src="https://github.com/payloadcms/payload/assets/3909121/f7e7f556-56cc-48ed-b1d8-372e3af38d58">

**Comment by JessChowdhury** [comment]
Hi @cbratschi - thank you for catching this! These issues will be resolved when the following PRs are merged:

1. https://github.com/payloadcms/payload/pull/4071
2. https://github.com/payloadcms/payload/pull/3946

Let me know if you have any further questions or concerns.
