### ISSUE TITLE
Bug: backspace deletes two characters on android chrome for rich text editor

### ISSUE THREAD

**Issue by kirandash** [payloadcms/payload#4069]
### Link to reproduction

[Payload CMS demo](https://demo.payloadcms.com/)

### Describe the Bug

**Current behaviour:**
Hitting backspace in middle of content deletes two characters on Android chrome

**The expected behavior:**
Only the character before the cursor gets deleted

### To Reproduce

1. Open the page or post editor on Chrome on Android
2. Write a word
3. Put the cursor somewhere in the middle
4. hit backspace - two characters get deleted. One character from front and one from back

### Payload Version

2.1.0

### Adapters and Plugins

plugin:richtext-lexical

**Comment by JarrodMFlesch** [comment]
@kirandash are you using the lexical or slate RTE?

**Comment by kirandash** [comment]
> @kirandash are you using the lexical or slate RTE?

@JarrodMFlesch thanks for the response!
I am using lexical. You can reproduce the issue on the demo link too: https://demo.payloadcms.com/

**Comment by kirandash** [comment]
FYI, this is a lexical issue and as pointed out by lexical, the root cause is the issue from android chrome. 

https://github.com/facebook/lexical/issues/4941

But I am curious if you guys have a patch for this. Since the issue from lexical is there since almost a year and no fixes/patch is known ASFAI

**Comment by AlessioGr** [comment]
Looks like this was patched by lexical recently! Once the new lexical version is out, I'll update it. Closing this for now, as this mainly seems to be a lexical/chromium issue rather than an issue with payload's implementation.
