### ISSUE TITLE
PayloadRequest type not match the real request object

### ISSUE THREAD

**Issue by zaunermax** [payloadcms/payload#407]
# Bug Report

The `PayloadRequest` type has an optional `file` type but in reality the object contains something like this when inspecting the req object:

```
files: {
  file: {
    name: "foo-image.jpeg",
    data: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 84 00 09 06 07 08 07 06 09 08 08 08 0a 0a 09 0b 0e 17 0f 0e 0d 0d 0e 1c 14 15 11 ... 814259 more bytes>,
    size: 814309,
    encoding: "7bit",
    tempFilePath: "",
    truncated: false,
    mimetype: "image/jpeg",
    md5: "de01819bcb2b465f80dd6dc34321f749",
    mv: [Function: mv],
  },
}
```

## Expected Behavior

The `PayloadRequest` type should reflect the real req object.

## Steps to Reproduce

1. Create an upload collection.
2. Create a `beforeChange` hook for the collection.
3. Inspect the req object in the hook and see the difference

**Comment by jmikrut** [comment]
Thanks for the report @zaunermax! 

Closed in https://github.com/payloadcms/payload/commit/a09570c78dc923f3553f36d726e5cfac925290a0.

Released as beta in `payload@0.13.17-beta.0`. Will be publishing a minor version at some point over the next few weeks!
