### ISSUE TITLE
Focal point not exposed in REST API

### ISSUE THREAD

**Issue by RickGeersing** [payloadcms/payload#4070]
### Describe the Bug

When I change the focal point of an media item I want to have that focal point in my frontend. As of now there is no focal point data in the response of that media item. Or am I doing something wrong with the focal point settings?

### To Reproduce

1. Create a media collection that supports uploads
2. Set `focalPoint` to `true` on the `upload` section of that collection.
3. Upload an image
4. Click on `edit image`
5. Change the focus point a bit
6. Hit save
7. Switch to API tab
8. There should be no focal point data

### Payload Version

2.1.0

**Comment by JarrodMFlesch** [comment]
Hey @RickGeersing this is not a bug, currently the focal point data is only used to tell sharp how to crop the photo so we use it on the request and do not store it. I can see how it might be useful to store on the top level media though.

I think this is more of a feature request than a bug so I am going to move this to a discussion.
