### ISSUE TITLE
Local API showHiddenFields does not work with nested fields

### ISSUE THREAD

**Issue by zaunermax** [payloadcms/payload#408]
# Bug Report

The Property `showHiddenFields` in the local API does not work with nested fields as the title already says.

## Expected Behavior

When setting the property all hidden fields should be displayed, or there should at least be an option to turn this on.

## Steps to Reproduce

1. Create 2 collections that are related to each other, for example Person -> ProfilePicture
2. Make some field in ProfilePicture hidden
3. Try to load all Persons with their profile pictures with the `showHiddenFields` prop
4. See, that the hidden field in the ProfilePicture collection stay hidden

**Comment by jmikrut** [comment]
Hey @zaunermax keep 'em coming!

This one is fixed in `payload@0.13.19-beta.0`.

Thank you!

**Comment by jmikrut** [comment]
Hey @zaunermax — I originally misread this issue but it's now fixed and released as beta in `payload@0.13.20-beta.0`.

Thank you - keep 'em coming!
