### ISSUE TITLE
ID not working in listSearchableFields

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#4081]
### Link to reproduction

pnpm dev admin

### Describe the Bug

If `id` is included in `listSearchableFields`, the expected result is not returned.

### To Reproduce

Using the monorepo,

1. Add `id` to `listSearchableFields` in `test/admin/collections/Posts.ts`
2. `pnpm dev admin`
3. Open Posts list view, try searching for a document using an ID

### Payload Version

2.1.0

**Comment by wrobson-lllow** [comment]
I've been having the same issue as in this related bug-report: [#4227](https://github.com/payloadcms/payload/issues/4227) Any updates to this? 
A little extra detail:
This only seems to be an issue when searching by ID on collections whose ID's are created automatically by Payload. I have several collections where the ID is created based on required fields of that record and I'm not seeing any issues when searching by ID on those collections.
