### ISSUE TITLE
Lexical RT double click bug in Firefox

### ISSUE THREAD

**Issue by patricsgamma** [payloadcms/payload#4083]
### Link to reproduction

-

### Describe the Bug

The lexical RT editor has a small issue 🐛  in Firefox 🔥🦊  when selecting a formatted word 
This if selection includes the start of the formatted phrase.
Selection could be done by double-click or click and drag select.

**✔️  Works as expected**: First I can select a word with double-click.
![image](https://github.com/payloadcms/payload/assets/87857953/1fac5cd6-75ab-4327-b95c-e5d0116162a4)

**✔️ Works as expected**: Once I've selected a text altering format (example: subscript), it gets applied correctly
![image](https://github.com/payloadcms/payload/assets/87857953/72dbdb13-4454-4cdd-a0f1-8e60731fd2a3)

**✔️  Works as expected**: If I then remove the word highlighting, the toolbar disappears.
![image](https://github.com/payloadcms/payload/assets/87857953/3f8b9416-c838-405d-bf68-db94f2709514)

**❌ Not expected**: Once I re-select the formatted word with double-click, I can not disable the subscript format as its not toggled in the toolbar.
![image](https://github.com/payloadcms/payload/assets/87857953/b9b9e112-f906-4fe3-ad8d-23449c09561d)

**✔️ Works as expected**: Any click and drag selection with the cursor that does not involve the start of the word works correct.
![image](https://github.com/payloadcms/payload/assets/87857953/81b3f10f-ca4c-4aac-8287-a6339aa94de2)

**❌ Not expected**: Once I select the whole word with a click and drag, its the same as double-click, the option is not toggled.

### Expectation
If I select a formatted text section, I would expect the toggle of the format to be enabled. So that I'm able to disable the toggling.

Browser:
🔥🦊 119.0 (64-bit)
on 🍏 12.2.1 (21D62)

### To Reproduce

Please check Description above.

### Payload Version

`"payload": "^2.0.15",`

### Adapters and Plugins

```
"@payloadcms/bundler-webpack": "^1.0.5", 
"@payloadcms/db-mongodb": "^1.0.6",
"@payloadcms/plugin-cloud-storage": "^1.1.1", 
"@payloadcms/plugin-sentry": "^0.0.4", 
"@payloadcms/richtext-lexical": "^0.1.15",
```

**Comment by AlessioGr** [comment]
Hey, thank you for reporting this! It seems that this is actually an issue in the lexical core - not in the payload lexical plugin.

I have opened an issue in the lexical repository here: https://github.com/facebook/lexical/issues/5234

Let's wait for the lexical team to fix this

**Comment by AlessioGr** [comment]
Since it's a Firefox issue, rather than an issue with lexical, I'm going to close it here. I think it's best to open an issue in Firefox, like John mentioned in the lexical issue. Dirtily patching this for just Firefox is not worth the effort and extra complexity it would introduce.

I'm also not sure how dirty patching it would work. I could remove the first, incorrectly selected node for Firefox - but that would then cause incorrect behavior when you actually do select 2 nodes. If the Firefox API incorrectly reports the selected DOM nodes, I don't think there is a way to differentiate between those 2 scenarios.

**Comment by patricsgamma** [comment]
Noted, thx for finding out this much.
