### ISSUE TITLE
plugin-cloud-storage: Upload URLs used to return the full path. Now only return the relative path.

### ISSUE THREAD

**Issue by treturner** [payloadcms/payload#4096]
### Describe the Bug

There is a breaking change with media and the URLs the server sends through the REST API. I am using the cloud storage plugin with S3. 

This is the error I get whenever I try to access any of the media from my server on the frontend. 
Error: Failed to parse URL from /media/image.jpg

The change is that the URL for an image returned from the server using the REST API had the complete URL (including the host). Now it doesn't. Is there a way to fix this? I don't want to manually go in a prepend the server URL in front of every place I call for the image.url

This is what the server used to return
`"url": "http://localhost:8000/media/image.jpg"`

This is what the server now returns
`"url":` `"/media/image.jpg"`

These are my dependencies for my working version (before upgrading):
```
"payload": "^1.15.8"
"@payloadcms/plugin-cloud-storage": "^1.1.1"
```

These are my dependencies after I upgrade to 2.0
```
"payload": "^2.1.0"
"@payloadcms/plugin-cloud-storage": "^1.1.1"
```

I believe this is intended as it's specified in the docs that Payload only returns the relative path for the URL in a REST API call, but it used to give the full path.

### To Reproduce

Initializing any new 2.0 payload server now returns relative paths.

### Payload Version

2.1.0

### Adapters and Plugins

db-mongodb, bundler-webpack, cloud-storage-plugin, s3

**Comment by denolfe** [comment]
This should be able to be solved by utilizing the [`generateFileURL`](https://github.com/payloadcms/payload/blob/main/packages/plugin-cloud-storage/src/types.ts#L67) function in your plugin configuration:

```ts
cloudStorage({
  collections: {
    media: {
      adapter,
      generateFileURL: ({ collection, filename, prefix }) => {
        return `http://localhost:3000/${prefix}/${collection.slug}/${filename}`
      }
    },
  },
}),
```
