### ISSUE TITLE
tab styling error with name 'button'

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#4107]
### Describe the Bug

When naming a tab 'button' it get de wrong styling. See screenshot:
![Screenshot 2023-11-11 at 21 09 46](https://github.com/payloadcms/payload/assets/52583398/c0ead752-098e-45fa-acc4-202f282b6aaf)

### To Reproduce

Create a tab named 'button'.

### Payload Version

2.0.13

**Comment by JessChowdhury** [comment]
Hi @silveltman - wow nice catch! This has been fixed and will be in our next release.
