### ISSUE TITLE
A number field cannot be saved when clearing its value

### ISSUE THREAD

**Issue by oranoran** [payloadcms/payload#411]
# Bug Report

A number field which is not required can have a value of null.
However, changing its value from a number to null fails, due to a bug in creating the updated document.

## Expected Behavior

Should save successfully, and the field should have a null value.

## Current Behavior

Fails to save, with a Mongoose error: Cast to Number failed for value "NaN".

## Possible Solution

Will create a PR shortly.

## Steps to Reproduce
1. Define a number field
2. Using the admin, give it a value and save the entity
3. Clear the value and save again

## Detailed Description

Payload version 0.13.6 (but fixing it on the master)

**Comment by DanRibbens** [comment]
Thanks for your help @oranoran! This was a great find and good fix to have in. I did find one issue when testing that had to do with localized fields and I fixed that.

This is released now in v0.14.3-beta.0 and will be included in future releases.
