### ISSUE TITLE
Live Preview: image reference is null

### ISSUE THREAD

**Issue by cbratschi** [payloadcms/payload#4120]
### Link to reproduction

private repo

### Describe the Bug

I have an image gallery collection which contains an array and inside this array is an upload field. This field value is mandatory. The bug is that the upload field value is always null.

### To Reproduce

Use a collection with this field:

```JS
{
        //images
        name: 'images',

        label: {
            en: 'Images',
            de: 'Bilder'
        },

        labels: {
            singular: {
                en: 'Image',
                de: 'Bild'
            },

            plural: {
                en: 'Images',
                de: 'Bilder'
            }
        },

        type: 'array',

        fields: [{
            //image
            name: 'image',

            label: {
                en: 'Image',
                de: 'Bild'
            },

            type: 'upload',
            relationTo: Media.slug,
            required: true,

            //filter images
            filterOptions: {
                mimeType: {
                    like: 'image/'
                }

            }
        }, {
            //caption
            name: 'caption',

            label: {
                en: 'Caption',
                de: 'Legende'
            },

            type: 'text',
            localized: true
        }]
    }
```

Returned sample data from preview hook:

```JS
images: [
    { caption: 'Bild 1', id: '651ecda6f6b4e63add6e3cc6', image: null },
    { caption: 'Bild 2', id: '651ecdb5f6b4e63add6e3cc7', image: null },
    { caption: 'Bild 3', id: '651ecdbef6b4e63add6e3cc8', image: null },
    {
      caption: 'SVG Icon',
      id: '654c06c14de039ba4510efbf',
      image: null
    }
  ],
```

Here the image value is always null but a valid image (upload) is set.

### Payload Version

2.1.0

### Adapters and Plugins

db-mongodb, bundler-webpack, live-preview

**Comment by cbratschi** [comment]
Payload version is 2.1.1.

**Comment by jacobsfletch** [comment]
@cbratschi thank you for the report on this. Are you setting `depth` properly?

**Comment by RickGeersing** [comment]
Experiencing same issue, made an issue for it #3990. It was closed due to a potential fix. But still experiencing this in `2.1.1`.

**Comment by cbratschi** [comment]
@jacobsfletch don't want any depth here just the collection ID but always getting null.

**Comment by jacobsfletch** [comment]
Ok good to know @cbratschi 👍 I went ahead and reopened your issue @RickGeersing, it sounds like the same issue but we'll get to the bottom of it

**Comment by qbeauperin** [comment]
Having the same issue as well on both `2.1.0` and `2.1.1` (cf: [discord thread](https://discord.com/channels/967097582721572934/1174902157200330802)).

Getting `null` returned for both my upload fields and my relationship fields.

**Comment by qbeauperin** [comment]
So, after more investigation, I figured out that the issue was with my `cors` and `csrf` config, and adding my front-end domain to these two options solved it. 👍

**Comment by Cuzart** [comment]
I am experiencing the same issue as @RickGeersing reported that in live-preview the depth for rich text (lexical) seems to be ignored and relationships only get populated with their id although I would need the whole object (e.g. upload oder blocks feature in lexical).

Cors or csrf does not affect this at least in my setup. I am hosting frontend and payload on the same server and port (next-custom-server)

**Comment by cbratschi** [comment]
My case is different. No CORS and CSRF issues. The ID is not returned, just null.

**Comment by Bohooslav** [comment]
Images are loaded fine after I publish the page, but fresh image in draft loads as null in the live preview.

**Comment by Bohooslav** [comment]
After I added cors and csrf it works.

**Comment by cbratschi** [comment]
My issue is solved with the latest Payload version.

**Comment by klisfer** [comment]
Getting the same issue, I have added the frontend application url in cors and csrf settings in payload.config, still the image disappears. When I manually reload the iframe, the image loads but the real time update of live preview breaks completely. Even changing text after that throws error. Can someone please suggest a fix for the issue?

**Comment by jacobsfletch** [comment]
@klisfer can you confirm that your packages are all up-to-date? It's possible that your `@payloadcms/live-preview-react` module is out of sync with and `payload` and/or it installed an old version of `@payloadcms/live-preview`. Ensure that you've bumped `@payloadcms/live-preview-react` and `payload` to latest in your package.json, then try removing `yarn.lock` and run `yarn` again (if you're using Yarn) so that  the latest version of `@payloadcms/live-preview` is installed. More on that here: https://github.com/payloadcms/payload/issues/4362#issuecomment-1845466853
