### ISSUE TITLE
Website Template - archive block setting category caused type error

### ISSUE THREAD

**Issue by jayelg** [payloadcms/payload#4122]
### Describe the Bug

For the Website Template with Postgres.
When selecting 'Categories To Show' in the archive block it causes a type error:

`[12:53:10] ERROR (payload): error: invalid input syntax for type integer: ""
    at /dev/test-archive/node_modules/pg/lib/client.js:526:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /dev/test-archive/node_modules/src/node-postgres/session.ts:64:19
    at async find (/dev/test-archive/node_modules/@payloadcms/db-postgres/src/find/findMany.ts:96:28)
    at async find (/dev/test-archive/node_modules/payload/src/collections/operations/find.ts:144:16)`

### To Reproduce

create a new project
`npx create-payload-app@latest test-archive`
select the website template
select postgres and attach to a new database
run `yarn && yarn dev`
login to the admin site
seed the default content
open a page eg. home
on the archive block for posts, select a category from the 'Categories To Show' dropdown and 'Publish Changes'

### Payload Version

^2.0.0

### Adapters and Plugins

db-postgres, bundler-webpack, nested-docs,

**Comment by JessChowdhury** [comment]
Hi @jayelg, this error comes from the `populateArchiveBlock` hook in the `pages` collection. The hook contains a request which needs to be adjusted [here](https://github.com/payloadcms/payload/blob/main/templates/website/src/payload/hooks/populateArchiveBlock.ts#L20). The `id` is returned as a number with Postgres, so you need to update [line 29](https://github.com/payloadcms/payload/blob/main/templates/website/src/payload/hooks/populateArchiveBlock.ts#L29) to:
```ts 
if (typeof cat === 'string' || typeof cat === 'number') return cat
```

Let me know if you face any other issues - also I will update the `website` template with this change.
