### ISSUE TITLE
Lexical Context error in serverless Next.js app

### ISSUE THREAD

**Issue by wiggindev** [payloadcms/payload#4124]
### Link to reproduction

https://github.com/wiggindev/payload-lexical-rsc-repro

### Describe the Bug

@payloadcms/richtext-lexical imports `createContext`. Importing it into payload.config.ts will throw errors in server components.

### To Reproduce

1. `yarn create next-app`
2. Downgrade to latest v13.x (currently 13.5.6)
3. `yarn add @payloadcms/next-payload payload`
4. `yarn next-payload install`
5. `yarn add @payloadcms/richtext-lexical`
6. Add `editor: lexicalEditor({})` to payload.config.ts
7. Call `await getPayloadClient()` from any server component

When you open the admin panel, it will work as expected. When you open any server component page that interacts with `getPayloadClient`, it throws `createContext only works in Client Components. Add the "use client" directive at the top of the file to use it.`

### Payload Version

2.1.1

### Adapters and Plugins

richtext-lexical

**Comment by AlessioGr** [comment]
Thank you for reporting this! I've pushed out a fix which will be available in the next version :)
