### ISSUE TITLE
Missing translation key in the upload component

### ISSUE THREAD

**Issue by jm2097** [payloadcms/payload#4128]
### Describe the Bug

As mentioned in this [discord post](https://discord.com/channels/967097582721572934/1171458404544413696), there seems to be an issue with PayloadCMS not being able to recognize the translation key `or` for the upload component.

cc: @JessChowdhury 

### To Reproduce

1. Go the Media collection in the admin panel.
2. Click on "Create new".
3. Take a look at the dropzone label "or drag and drop a file".
4. Try changing the language to anything and see how the "or" remains as the translation key.

![image](https://github.com/payloadcms/payload/assets/64181348/529c2607-f59c-471f-86e8-e9b480f77bd8)
![image](https://github.com/payloadcms/payload/assets/64181348/c6b2e82c-df54-4113-9f01-1ffd38ff6232)
![image](https://github.com/payloadcms/payload/assets/64181348/7f26ea09-e52c-43e0-87f1-4fa4eaec0cc0)

### Payload Version

2.1.1

**Comment by denolfe** [comment]
Looks like translations that are using multiple namespaces are not retrieving the translations properly.

If multiple namespaces are retrieved ie. 

`const { t } = useTranslation(['upload', 'general'])`

The first namespace is used by default

`{t('dragAndDrop')}` will use the `upload` namespace.

To retrieve from the `general` namespace in this instance, it would be done like so:

`{t('or', { ns: 'general' })}`

We should address all multiple namespace scenarios in the codebase by searching for `useTranslate([`.

**Comment by JessChowdhury** [comment]
@denolfe when I started doing the search for `useTranslation([` I noticed we handle this in all other cases by adding the namespace before the key like this `t(general:or)`. I checked all the files with multiple i18n namespaces, this was the only broken instance - I have fixed it in [this PR.](https://github.com/payloadcms/payload/pull/4135)
