### ISSUE TITLE
Re-add limit=0 (or equivalent) to disable query pagination in REST and GraphQL APIs.

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#4143]
### Discussed in https://github.com/payloadcms/payload/discussions/4126

<div type='discussions-op-text'>

<sup>Originally posted by **dhaub-exelixis** November 13, 2023</sup>
As discussed in this discord thread: https://discord.com/channels/967097582721572934/1172339833381851176, my team and others make use of the now disabled `limit=0` feature to return all query results in one get request. Currently the documentation states that disabling pagination is only possible with the local API: https://payloadcms.com/docs/queries/pagination#disabling-pagination-within-local-api

In the case of my team, we make use of a very high volume of data, that could often have tens of thousands of entries returned in a single query. While we could use a very large number as the limit param, it would be nice to just disable limiting all together.</div>

**Comment by r1tsuu** [comment]
I'm using now `limit=0` for only getting count of total docs (i need this for filtering filter options that has no docs, very common case in ecommerce, or you can also show how many docs you will get if you apply this filter)
Though it probably still would be better to use Mongoose`Model.countDocuments()` unfortunately i need Payload query , but `limit=0` definitely better than `limit=1`

**Comment by denolfe** [comment]
Revisiting this now. Adding back `limit=0` functionality to return all docs.
