### ISSUE TITLE
Relation with deleted document break graphQL

### ISSUE THREAD

**Issue by matteo-naif** [payloadcms/payload#4159]
### Link to reproduction

-

### Describe the Bug

When I get data through graphQL and the document contains relation to other documents that doesn't exist anymore, it breaks and also the generation of the static page.

The error is the following:
``` 
[{"message":"Cannot return null for non-nullable field ConfiguratorBlock_Steps_ContentSteps.sensorSelected.","locations":[{"line":1620,"column":13}],"path":["Catalogs","docs",0,"layout",0,"steps",3,"contentSteps","sensorSelected",0],"extensions":{"name":"Error"}}]
```

The field is the following:
```ts
{
  name: "sensorSelected",
  label: {
      it: "Sensore",
      en: "Sensor",
  },
  type: "relationship",
  relationTo: "catalog-sensor",
  hasMany: true
},
```

Can you clean the relation when a document is removed? 

### To Reproduce

1. create document A in the collection A
2. select the relation with document B of the collection B
3. delete document B
4. request document A using graphQL
5. the response is the error message

### Payload Version

1.15.7

**Comment by DanRibbens** [comment]
Hi @matteo-naif,

I was not able to reproduce the issue. I wrote some tests against the latest version to try and reproduce the issue. I copied the tests to 1.x but they have the same result. 

This is the PR https://github.com/payloadcms/payload/pull/4229

We have plans to improve the experience of deletion of related documents, see: https://github.com/payloadcms/payload/discussions/2938.

If you have more info that could be relevant please let me know so we can look deeper into this.

**Comment by matteo-naif** [comment]
Hello @DanRibbens ,
I've tried to update the npm package payload and now seems to work properly, I don't know if it's up to other fix.
By the way thanks!
