### ISSUE TITLE
getIncomingFiles returns File with undefined filesizes after upgrading to 2.1.1

### ISSUE THREAD

**Issue by RickVM** [payloadcms/payload#4168]
### Describe the Bug

After upgrading to Payload v2.1.1 from 2.0.13, getIncomingFiles returns a File[] where file.fileSize is undefined.
Other fields are still defined (buffer, fileName, mimeType)

The interface exported by plugin-cloud-storage can be seen below

```
export interface File {
    buffer: Buffer;
    filename: string;
    filesize: number;
    mimeType: string;
    tempFilePath?: string;
}
```

### To Reproduce

Use a default media collection, add a beforeChangeHook like so

```
import { getIncomingFiles } from '@payloadcms/plugin-cloud-storage/dist/utilities/getIncomingFiles';
import { FileData } from 'payload/dist/uploads/types';
import { Media } from 'payload/generated-types';

const calculateSizeBeforeUpload: CollectionBeforeChangeHook<
  FileData & Media
> = async ({ data, req }) => {
  const files = getIncomingFiles({ req, data });

  // The following line now fails because fileSize is undefined
  const totalFileSize = files.reduce((acc, file) => acc + file.filesize, 0);
 
  
  return data;
};
```

Then upload a file, and you will see filesize is undefined

### Payload Version

2.1.1

### Adapters and Plugins

"@payloadcms/bundler-webpack": "^1.0.3",     "@payloadcms/db-mongodb": "^1.0.3",     "@payloadcms/plugin-cloud-storage": "^1.1.1",     "@payloadcms/richtext-slate": "^1.0.6",

**Comment by RickVM** [comment]
Working around this by calculating the fileSize length ourselves for now

```
fileSize = file.buffer.byteLength
```

**Comment by JessChowdhury** [comment]
Hi @RickVM - I was not able to replicate this, the req returned by `getIncomingFiles` did have the filesize. Could you share your upload config or provide a basic reproduction?

**Comment by JessChowdhury** [comment]
Closing - feel free to reopen if you are still experiencing this and can provide a reproduction or some detailed steps for us. Thanks!
