### ISSUE TITLE
Aliasing for vite is incorrectly documented

### ISSUE THREAD

**Issue by NetroScript** [payloadcms/payload#4205]
# Documentation Issue

The current vite aliasing configuration for server side files is described as follows:

```TS
export const buildConfig({
  collections: [],
  admin: {
    bundler: viteBundler(),
    vite: (incomingViteConfig) => ({
      ...incomingViteConfig,
      resolve: {
        ...(incomingViteConfig?.resolve || {}),
        alias: {
          ...(incomingViteConfig?.resolve?.alias || {}),
          // custom aliases go here
          '../server-only-module': path.resolve(__dirname, './path/to/browser-safe-module.js'),
        }
      }
    })
  }
})
```

However following this documentation leads to errors, as then the own aliases of `@payloadcms/bundler-vite` stop working.

Inspecting the values being passed to this function compared to the output created, we can observe something like:

```JS
{
	alias: {
		1: { find: '@payloadcms/bundler-vite', replacement: './mock.js') },
	    2: { find: '...', replacement: '...' }
	}
}
```

which then turns into:

```JS
{
	alias: {
		1: { find: '@payloadcms/bundler-vite', replacement: './mock.js') },
	    2: { find: '...', replacement: '...' },
		'../server-only-module': './path/to/browser-safe-module.js'
	}
}
```

which leads to errors. 

For my own project the following configuration works:

```TS
export const buildConfig({
  collections: [],
  admin: {
    bundler: viteBundler(),
		vite: (incomingViteConfig) => {
			const previousAlias = incomingViteConfig?.resolve?.alias || {};
			let aliasArray: { find: string | RegExp; replacement: string; }[] = [];

			// Check if it is an array of alias objects or an object with alias objects
			if (Array.isArray(previousAlias)) {
				aliasArray = previousAlias;
			} else {
				aliasArray = Object.values(previousAlias);
			}

			// Append own aliases
			aliasArray.push({
				find: '../server-only-module',
				replacement: path.resolve(__dirname, './path/to/browser-safe-module.js')
			});

			return {
				...incomingViteConfig,
				resolve: {
					...(incomingViteConfig?.resolve || {}),
					alias: aliasArray
				}
			};
		},
  }
})
```

## Additional Details

Related issue: #3644 

Using `@payloadcms/bundler-vite`@0.1.4

Additional remark: The documentation uses an incorrect http://localhost:3000 URL here:
https://github.com/payloadcms/payload/blob/724d80b7f463bf6d2fde94fc03a6314b659a5f7b/docs/admin/vite.mdx#L126

------

I am using PayloadCMS for the first time and just followed along the relevant documentation snippets when I needed it, until I started getting vite module errors in the browser when implementing a custom endpoint which makes use of the filesystem and sharp. 

Only then following GitHub issues and reading more about it, I saw the https://payloadcms.com/docs/admin/excluding-server-code page. (Seems like my brain conveniently just ignored that section previously and that of course the react code needs to be bundled).

But I still think that certain parts of the documentation (like custom endpoints) should show a reminder considering excluding server side code and link to the relevant documentation page.

A potential enhancement for user experience could involve adopting an approach similar to SvelteKit's `lib/server` folder. In SvelteKit, this folder helps by issuing warnings when server components are imported into the frontend. Similarly, in PayloadCMS, designating a subfolder for server files (or maybe a file suffix), which then automatically excludes these files from frontend bundling, could be beneficial. This change would help prevent accidental exposure of sensitive backend code.

After all for a similar reason `process.env` already gets (mostly) cleared. 

Just as an example:

In the https://github.com/payloadcms/public-demo, it is strange that almost the entire seed code gets bundled to the frontend, so even without logging in, all of that data is exposed.

**Comment by jmikrut** [comment]
Hey @NetroScript — thank you for pointing all of this out. We will fix documentation ASAP.

Also, _**the need to alias server-only modules**_ is going to be completely removed in an upcoming version of Payload. So all of this will become significantly easier. 

We'll keep this issue open until documentation is resolved, but, more from us soon regarding aliases in general. They suck, and we hate them, so we're fixing it entirely. Big win for Payload DX soon.
