### ISSUE TITLE
Postgres cannot handle localized text field in blocks

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#4208]
### Describe the Bug

On every start it asks to truncate this table:
```
· You're about to add GLOBALSLUG_BLOCKSFIELDNAME_BLOCKNAME_locales_locale_parent_id_unique unique constraint to the table, which contains 3 items. If this statement fails, you will receive an error from the database. Do you want to truncate home_blocks_book_session_carousel_locales table?

❯ No, add the constraint without truncating the table
  Yes, truncate the table
```

### To Reproduce

Create a global with a blocks field that contains a localized text field.

### Payload Version

2.1.1

### Adapters and Plugins

postgres, webpack

**Comment by r1tsuu** [comment]
Ran into the same issue but for me a localized field in a just block works. But if have structure:
block -> array -> localized text field
then i have this:
`You're about to add test_global_blocks_test_type_arr_locales_locale_parent_id_unique unique constraint to the table, which contains 1 items. If this statement fails, you will receive an error from the database. Do you want to truncate test_global_blocks_test_type_arr_locales table?`
It displays in admin panel, but doesn't save the value.

Here is reproduce https://github.com/r1tsuu/payload-blocks-array-localized-issue

**Comment by JanKups** [comment]
I'm facing this issue in Payload 3.0 beta 54.

Structure:
```
{
  name: "subLinks",
  type: "array",
  label: "Sub Links",
  fields: [
    {
      name: "text",
      type: "text",
      label: "Text",
      required: true,
      localized: true,
    },
    {
      name: "subLinksRow",
      type: "array",
      label: "Sub Link Row",
      fields: [
        {
          name: "text",
          type: "text",
          label: "Text",
          required: true,
          localized: true,
        },
        {
          name: "subtitle",
          type: "text",
          label: "Subtitle",
          required: true,
          localized: true,
        },
        {
          name: "pageLink",
          type: "relationship",
          relationTo: ["pages"],
          label: "Page",
          required: true,
          hasMany: false,
        },
      ],
    },
  ],
},
```


Result when changing content:

```
· You're about to add navigation_links_sub_links_sub_links_row_locales_locale_parent_id_unique unique constraint to the table, which contains 12 items. If this statement fails, you will receive an error from the database. Do you want to truncate navigation_links_sub_links_sub_links_row_locales table?

❯ No, add the constraint without truncating the table
  Yes, truncate the table
```

**Comment by christopherpickering** [comment]
@DanRibbens  I have the same message:
```bash
· You're about to add _products_v_blocks_content_columns_locales_locale_parent_id_unique unique constraint to the table, which contains 1 items. If this statement fails, you will receive an error from the database. Do you want to truncate _products_v_blocks_content_columns_locales table?

❯ No, add the constraint without truncating the table
  Yes, truncate the table
```

But I think the cause of mine and @JanKups is possible the length of the text?

I check my database and find the constraint added, but with a truncated name:
<img width="580" alt="image" src="https://github.com/user-attachments/assets/55568372-d87d-4f45-baed-74a612db2ba0">

**Comment by christopherpickering** [comment]
Tagging on here again, in postgres running `SHOW max_identifier_length;` return 63... which is the length the constraint was truncated to. It seems that this can't be updated? https://pgpedia.info/m/max_identifier_length.html

Is there a way to alias these constraints to a shorter name?
