### ISSUE TITLE
Migrations is ignored when running payload migrate

### ISSUE THREAD

**Issue by unoflavora** [payloadcms/payload#4219]
### Describe the Bug

If I delete the `/src` folder for the production environment, the `payload migrate` command will not detect any migrations, even though the migrations folder is already copied into `/dist/migrations`. This is important for those who are running Payload in a container environment, which tends to delete as many files as possible to reduce size. Since `/src` is only used in development, it should be ignored in the production environment.

It seems that payload.db.migrationDir should be updated when `payload migrate` is running on production environment.

### To Reproduce

1. run  npm install
2. set NODE_ENV=production
3. set ENV PAYLOAD_CONFIG_PATH=dist/payload.config.js
4. run npm run build
5. delete src folder
6. run npm run payload migrate

### Payload Version

2.0.0

### Adapters and Plugins

db-postgres

**Comment by denolfe** [comment]
Thanks for the report. The solution to this will be covered in #3746 .
