### ISSUE TITLE
Filter for field type "date" ignores admin.date options

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#4222]
### Describe the Bug

Date fields with `admin.date` options have their date options ignored in List filter context. Additionally, it is currently impossible to filter by time, only dates.

### To Reproduce

1. Add this field to a Collection:

```
{
                            name: "jobDate",
                            type: "date",
                            required: true,
                            admin: {
                                width: "50%",
                                date: {
                                    pickerAppearance: "dayAndTime",
                                    displayFormat: "dd/MM/yyyy",
                                },
                            },
                        },
```

2. Try to add a filter to the field on the list view (e.g. `equals`). The field will be shown without the time, and the display format `dd/MM/yyyy` will not be respected.

### Payload Version

2.1.1

**Comment by JarrodMFlesch** [comment]
@tyteen4a03 so I looked at this a bit more, @JessChowdhury has fixed your original issue in her PR where formatting was not applying to the filter field. 

I see what you are saying about the filtering not working for time fields. The problem being that the DB is storing milliseconds and the equality check looks for an _exact match_, most saved dates will likely have a non-zero ms timestamp which causes the equality check to fail. We need to figure out the best way to solve this from an API standpoint, allowing people to omit/round down ms from timestamps.

**Comment by tyteen4a03** [comment]
Thanks for the update! My original issue was that the time field doesn't show up because `admin.date` options are being ignored, therefore filtering by time is impossible. This should hopefully be fixed with the PR. 

I did notice that we seem to store milliseconds based on when `new Date()` is created (I don't have a reproduction for this right now) so doing an exact match becomes trickier. Hope this can be fixed as well, in a separate issue.
