### ISSUE TITLE
Locale switch issue

### ISSUE THREAD

**Issue by zaplvlad** [payloadcms/payload#423]
This issue happens with array type properties when you are switching language.

## Steps to reproduce
1. Configure CMS for two locales

`['en', 'da-DK']`

2. Create global collection with localized array type property and text field within it.

```
import { GlobalConfig } from 'payload/types'; 

export const globalCollection: GlobalConfig = { 
  slug: 'globalCollection', 
  label: 'Global Collection', 
  fields: [ 
    { 
      name: 'arrayProperty', 
      type: 'array', 
      localized: true, 
      fields: [ 
        { 
          name: 'someTextField', 
          type: 'text', 
        }, 
      ], 
    }, 
  ], 
}; 
```
 
3. Go to CMS and add two items to array property for "en" locale. Save changes.

![1](https://user-images.githubusercontent.com/43339104/150781929-7768f24b-5530-4694-9c45-2c9b1892845a.png)

4. **Reload page in browser.**
5. Switch locale to "da-DK".
6. Click "Add" button.

![2](https://user-images.githubusercontent.com/43339104/150782038-fc61eff6-b80f-41ef-8792-af6bdc857150.png)

7. You will see the text which was configured in first array item for "en" locale. This is strange behavior already.

![3](https://user-images.githubusercontent.com/43339104/150782083-9f05e2c3-004a-478f-add9-261741533911.png)

8. Click "Save" button.
9. **Reload page in browser.**
10. Now there are three items appeared. Some of them from "en" locale and some are empty.

![4](https://user-images.githubusercontent.com/43339104/150782148-2b7e7fe9-6db4-4fa4-a254-f9e6aa99698d.png)

There are even more strange things happens if you continue reload page and switch locale. I don't think I have to describe them all. One time we even brake DB data structure, so CMS stopped working at all (500 error on all CMS pages).

## Expected result
Array type properties shouldn't contain items from other locale after switching.

**Comment by jmikrut** [comment]
Hey @zaplvlad, this is certainly interesting. We will take a look. Probably something simple. Will report back tomorrow!
