### ISSUE TITLE
Stay logged in component shown in custom view only in production.

### ISSUE THREAD

**Issue by andr-ec** [payloadcms/payload#4235]
### Describe the Bug

I created a custom view react component on it’s own route:

in my payload config: 
```

      views: {
        EmailCampaign: {
          Component: EmailCampaignPreview,
          path: '/live-preview/email-campaign',
          exact: true,
          sensitive: false,
        },
      },
```

All of that works locally, the problem is that in production it shows the Stay logged in modal right below my actual component.  It shouldn't show that modal since I'm logged in. This happens when opening the route directly or viewing it through the live preview. 

```

My custom component text…
——

Stay logged in
You haven't been active in a little while and will shortly be automatically logged out for your own security. Would you like to stay logged in?

Log out
Stay logged in
```

Is there any more configuration to change or is this a bug? 

![Screenshot 2023-11-21 at 11 39 11 AM](https://github.com/payloadcms/payload/assets/16169185/9888ecb3-9e07-438e-a17d-68d282d132b3)

### To Reproduce

in my payload config: 
```

      views: {
        EmailCampaign: {
          Component: EmailCampaignPreview,
          path: '/live-preview/email-campaign',
          exact: true,
          sensitive: false,
        },
      },
```

### Payload Version

2.2.1

**Comment by JessChowdhury** [comment]
Hi @andr-ec, I am struggling to reproduce this, could you share your `EmailCampaignPreview` code? or if you could link us to the custom view in production that would be super helpful!

**Comment by andr-ec** [comment]
@JessChowdhury I think I tracked down the issue to a specific hook: 

```
export const EmailCampaignPreview: React.FC<any> = (props: any) => {
  // set to html to show finished render in preview

  React.useEffect(() => {
    // remove all scss styles from the website:
    const styles = document.querySelectorAll("style");
    styles.forEach((style) => {
      style.remove();
    });
  }, []);

  return (
    <div>
      <p>Preview</p>
    </div>
  );
};
```
I use this to remove payload's styling so I can use my own on this specific page. This works fine in development but not it production after running `npm run build`
```
  React.useEffect(() => {
    // remove all scss styles from the website:
    const styles = document.querySelectorAll("style");
    styles.forEach((style) => {
      style.remove();
    });
  }, []);
```

So I guess a better question is: is there a good way to remove styling from a custom view?

**Comment by andr-ec** [comment]
Looks like this works in production and in development: 

```
  React.useEffect(() => {
    // remove all scss styles from the website:
    const styles = document.querySelectorAll("style");
    styles.forEach((style) => {
      style.remove();
    });

    const links = document.querySelectorAll("link");
    links.forEach((style) => {
      if (style.rel === "stylesheet") {
        style.remove();
      }
    });
  }, []);
  ```

Seems a little hacky but it works for now. It would be great if there was a configuration option under the component for this though.
I'll close this since it's a separate feature request.
