### ISSUE TITLE
UI list a new documento twice

### ISSUE THREAD

**Issue by matteo-naif** [payloadcms/payload#4243]
### Link to reproduction

-

### Describe the Bug

When I create a new document and I return in the list, I see it twice. If I enter in the document and I save it, when I return in the list I see it only once.

### To Reproduce

1. From the list of the collection click "Create new"
2. Insert data you need
3. Click "Publish changes"
4. Return in the list view
5. The document is listed twice
6. Click on the document to enter in the detail
7. edit it and save it again
8. Return in the list view
9. The document is listed correctly only once

### Payload Version

2.2.1

### Adapters and Plugins

@payloadcms/bundler-webpack, @payloadcms/db-mongodb, @payloadcms/plugin-cloud-storage, @payloadcms/plugin-form-builder, @payloadcms/plugin-nested-docs, @payloadcms/plugin-seo, @payloadcms/richtext-lexical, @payloadcms/richtext-slate

**Comment by DanRibbens** [comment]
I can't recreate the problem. 

Could you create a reproduction by forking the repo and adding to the `test/_community`? If you can't provide that, then a screen recording with your network tab open could help us understand it better.

I tried with and without `plugin-nested-docs`. In both cases my document published once and was was only listed once.

I'll reopen this if we can demonstrate it.

**Comment by matteo-naif** [comment]
Hello @DanRibbens , I can share with you a screen recording: 
https://www.loom.com/share/83d3d70e96014fcaa4fdf5e663e0c612?sid=cf04ce29-d43e-4617-8845-7ab081d3dc81

Let me know if you need more details. Thanks!
