### ISSUE TITLE
vite plugin import

### ISSUE THREAD

**Issue by haliacmon** [payloadcms/payload#4249]
# Documentation Issue

https://payloadcms.com/docs/admin/vite
`import viteBundler from '@payloadcms/bundler-vite'
`

should probably be 
`import { viteBundler } from '@payloadcms/bundler-vite'
`
## Additional Details
![image](https://github.com/payloadcms/payload/assets/7809300/aef5afa7-b23c-4075-b5ea-c771f429bdb1)

**Comment by jacobsfletch** [comment]
Thank you for pointing this out @haliacmon 🙏
