### ISSUE TITLE
Suddenly started getting webpack error

### ISSUE THREAD

**Issue by dirums** [payloadcms/payload#4251]
### Describe the Bug

Hi team,
I'm using payload for the past 4 months and it was great but suddenly within a week it stated giving me webpack errors as follows:
```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "zlib": require.resolve("browserify-zlib") }'
        - install 'browserify-zlib'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "zlib": false }
```

I didn't installed any packages that will have conflict on it. Please help.

### To Reproduce

It's in the code so cannot tell how to reproduce the issue.

### Payload Version

1.13.4

### Adapters and Plugins

@payloadcms/plugin-cloud-storage

**Comment by jakehopking** [comment]
I've had this error for six months now (only on build, correct?). I've tried adding aliases with no joy. Perhaps these will work for you?



```ts
const mockModulePath = path.resolve(__dirname, './mocks/emptyObject.js');

export default buildConfig({
  ...
  admin: {
    // user: 'admins',
    bundler: webpackBundler(),
    webpack: (config) => ({
      ...config,
      resolve: {
        ...config.resolve,
        alias: {
          ...config.resolve?.alias,
          stripe: mockModulePath,
          express: mockModulePath,
          fs: mockModulePath,
          zlib: mockModulePath,
          stream: mockModulePath,
        },
      },
    }),
  },
  ...
});
```

`./mocks/emptyObject.js` has the following:

```
export default {};
```

**Comment by dirums** [comment]
it's giving this error now:
```Error: failed to handle: base_dir() must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.```

**Comment by jmikrut** [comment]
@JarrodMFlesch and I just tested with a relative `baseUrl` in `tsconfig.json` and it works as expected. So this is not an issue with Payload, and instead just a case of needing to alias out any server-side code from the Payload config.

Again - a reminder - the entire requirement of needing to alias server-only code is going to be removed soon. So bear with us until then! I know this is a pain in the ass and I personally hate it. But you DEFINITELY can solve your issue by making sure you alias out any server-only code.

**Comment by dirums** [comment]
Ok. So thank you for the replies. I resolved the issue by deleting yarn.lock, package-lock.json and node_modules and again reinstalling everything by using yarn install. Also I was using nodemailer to send custom emails on custom endpoints. That caused the issue of build errors.

**Comment by ChristopherNowlan** [comment]
@dirums nodemailer-sendgrid is causing me the same issue.  Ive added an alias, which I think is correct 
![Screenshot 2023-12-06 at 12 21 01 pm](https://github.com/payloadcms/payload/assets/12365706/3d22902b-b725-46e5-a061-45cf622220ca)

**Comment by iFoxtrot33** [comment]
Have the same issue, unfortunately removing node-modules & package-lock.json did not help to resolve the issue
