### ISSUE TITLE
Website template: document the significance of the environment variables in the .env.example folder

### ISSUE THREAD

**Issue by ChristianMay21** [payloadcms/payload#4272]
# Documentation Issue

Some of the environment variables in the .env.example file in the Website template have absolutely no context on what they are or what sort of values I should set. Some are labelled as "Next.js" variables but do not appear to be part of the Next.js framework, such as "NEXT_PUBLIC_IS_LIVE".

**Comment by jacobsfletch** [comment]
Thanks for the suggestion here @ChristianMay21, I've got #4276 queued up with some improvements.
