### ISSUE TITLE
possible regression - ValidationError - 2.1.1 to 2.2.1

### ISSUE THREAD

**Issue by iamacup** [payloadcms/payload#4274]
### Link to reproduction

https://github.com/iamacup/payload-regression

### Describe the Bug

I have attached a minimal reproduction, but when using the payload API, a set of working commands in 2.1.1 no longer work in 2.2.1 with no code changes.

error: `ValidationError: The following field is invalid: selector.0.default.0.matchNumber`

The minimal reproduction is very small and created with create-payload-app

### To Reproduce

- checkout https://github.com/iamacup/payload-regression
- yarn install
- yarn run

**NO ISSUES**

- checkout https://github.com/iamacup/payload-regression/pull/1
- yarn install
- yarn run

**ERROR with payload API validation**

It should be noted that if you change the value of matchNumber to a positive non zero integer in the seed function it seems to work, but the value 0 seems to be a problem.

### Payload Version

2.2.1 / 2.1.1

**Comment by JarrodMFlesch** [comment]
@iamacup this has been fixed since opening, please update payload by running `yarn add payload`. Thanks for reporting!
