### ISSUE TITLE
Missing references in custom server example

### ISSUE THREAD

**Issue by ChristianMay21** [payloadcms/payload#4289]
### Describe the Bug

@payloadcms/bundler-webpack and @payloadcms/db-mongodb are referenced in payload.config.ts in the "custom server" example, but are not included in package.json like other dependencies.

There is also an import from 'dotenv' - I'm not 100% sure if that means the dotenv npm package is a dependency, as there is a 'dotenv.js' file that this might be importing instead.

I know this 'dotenv.js' file is also fairly confusing as to what its purpose is - it might benefit from some helpful comments inside of it to tell developers why it exists/what it does.

These issues also exist in at least one other example, the website template.

### To Reproduce

See website template

### Payload Version

2.x

### Adapters and Plugins

N/A

**Comment by jacobsfletch** [comment]
Hey @ChristianMay21 I'm seeing those listed correctly in the custom server example here: https://github.com/payloadcms/payload/blob/main/examples/custom-server/package.json#L23 as well as the website template here: https://github.com/payloadcms/payload/blob/main/templates/website/package.json#L24

But I think you're right in that [this dotenv.js file](https://github.com/payloadcms/payload/blob/main/examples/custom-server/src/dotenv.js) can probably be removed. the `dotenv` package is still needed though. This is what loads the env itself into the environment.
