### ISSUE TITLE
db-postgres: cannot add the same block to multiple collections

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#4294]
### Describe the Bug

-

### To Reproduce

1. Create a block
2. Add the SAME block (so, same slug) to two block fields in different collections
3. Error in the console appears only when using postgres.

### Payload Version

-

**Comment by DanRibbens** [comment]
Fixed with https://github.com/payloadcms/payload/pull/4699 & https://github.com/payloadcms/payload/pull/4806
