### ISSUE TITLE
slate adapter is required

### ISSUE THREAD

**Issue by matteo-naif** [payloadcms/payload#4299]
`plugin-form-builder version: 1.0.15`
`payload version: 2.2.1`

When I install my dependencies in payload project I have the following error:

```bash
Error: Cannot find module 'slate'
Require stack:
-/node_modules/@payloadcms/plugin-form-builder/dist/utilities/serializeRichText.js
-/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/hooks/sendEmail.js
-/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/index.js
-/node_modules/@payloadcms/plugin-form-builder/dist/index.js
-/src/plugin/formBuilder.ts
-/src/payload.config.ts
-/node_modules/payload/dist/config/load.js
-/node_modules/payload/dist/payload.js
-/node_modules/payload/dist/initHTTP.js
-/node_modules/payload/dist/index.js
-/src/server.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/node_modules/@payloadcms/plugin-form-builder/src/utilities/serializeRichText.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/@payloadcms/plugin-form-builder/dist/utilities/serializeRichText.js',
    '/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/hooks/sendEmail.js',
    '/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/index.js',
    '/node_modules/@payloadcms/plugin-form-builder/dist/index.js',
    '/src/plugin/formBuilder.ts',
    '/src/payload.config.ts',
    '/node_modules/payload/dist/config/load.js',
    '/node_modules/payload/dist/payload.js',
    '/node_modules/payload/dist/initHTTP.js',
    '/node_modules/payload/dist/index.js',
    '/src/server.ts'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...    
```

If I install slate (`"@payloadcms/richtext-slate": "1.2.0"`) the error is resolved but I don't use it.

Maybe is up to the new version of payload? Can you check please?

**Comment by denolfe** [comment]
@matteo-naif This package has moved to the monorepo. Issue moved to here https://github.com/payloadcms/payload/issues/4299

**Comment by denolfe** [comment]
Thanks for the report. Looks like slate is in fact used in the serializer. We'll either need to update that or add slate as a peer dep.

**Comment by ChristopherNowlan** [comment]
@denolfe might need to resolve it. Sending emails fail and the confirmation message doesn't remove the the curly brackets.

I get this error when using the lexical editor in the CMS

`err: { "type": "TypeError", "message": "children.map is not a function", "stack": TypeError: children.map is not a function at serialize (node_modules/@payloadcms/plugin-form-builder/src/utilities/serializeRichText.ts:17:7) at /node_modules/@payloadcms/plugin-form-builder/src/collections/FormSubmissions/hooks/sendEmail.ts:54:40 at Array.map (<anonymous>) at node_modules/@payloadcms/plugin-form-builder/src/collections/FormSubmissions/hooks/sendEmail.ts:29:60 at step (/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/hooks/sendEmail.js:33:23) at Object.next (/node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/hooks/sendEmail.js:14:53) at fulfilled (node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/hooks/sendEmail.js:5:58) at processTicksAndRejections (node:internal/process/task_queues:95:5) }`

**Comment by ChristopherNowlan** [comment]
Could you force the plugin to use the slate editor? eg like this 

`  {
            type: 'richText',
            name: 'message',
            label: 'Message',
            localized: true,
            admin: {
              description: 'Enter the message that should be sent in this email.',
            },
            editor: slateEditor({})
          },`
