### ISSUE TITLE
(Cloud Storage): Preview sizes model does not show image previews

### ISSUE THREAD

**Issue by matthijs166** [payloadcms/payload#4305]
### Describe the Bug

Sizes modal uses wrong URL's for the thumbnail. It is still the internal media URL.
The rest of payload uses the file URL generated by the **generateFileURL** hook.

Here the thumbnail is correct:
<img width="646" alt="image" src="https://github.com/payloadcms/payload/assets/31346561/45743d29-37d0-4373-854e-0835ea9b8f64">
<img width="1012" alt="image" src="https://github.com/payloadcms/payload/assets/31346561/730898aa-16f5-488f-b7ac-2afd29e396f9">

Payload uses here the **adminThumbnail** hook.

When you open Preview Sizes you see that the thumbnails are not loaded:
![image](https://github.com/payloadcms/payload/assets/31346561/3bb52efe-1b8d-446a-be11-5076f2a26f29)
<img width="402" alt="image" src="https://github.com/payloadcms/payload/assets/31346561/5f8bdbb8-8865-40e6-a73b-cd2021a55ff9">

The API output is also correct:
<img width="1225" alt="image" src="https://github.com/payloadcms/payload/assets/31346561/d2d994e2-5df6-429b-9383-853e9172504c">

### To Reproduce

1. setup the cloud storage plugin
2. open a media item
3. click on Preview sizes
4. On the right all the media dont have loaded a thumbnail.

### Payload Version

"payload": "^2.2.0",

### Adapters and Plugins

@payloadcms/plugin-cloud-storage: 1.1.1

**Comment by matteo-naif** [comment]
I have the same issue. My packages are:
* "@payloadcms/plugin-cloud-storage": "1.1.1"
* "payload": "2.3.1"

**Comment by fabioquarantini** [comment]
Fixed with "payload": "2.4.0"

**Comment by matthijs166** [comment]
Yes this issue is fixed 🥳
