### ISSUE TITLE
 APIError: Cannot find field for path at title

### ISSUE THREAD

**Issue by larryro** [payloadcms/payload#4326]
### Describe the Bug

When we use the relationship field in an array, an 500 error occurs.

### To Reproduce

We have two collections, one is the parent collection, and the other is the media collection. When we access the parent collection in the admin panel, an error occurs.
```
{
  fields: [
    {
      name: 'image',
      label: 'Image',
      required: true,
      type: 'array',
      fields: [
        {
          name: 'file',
          type: 'relationship',
          relationTo: 'privateMedia',
        },
      ],
    },
  ],
};
```
![image](https://github.com/payloadcms/payload/assets/5787117/1cc6fb9a-dbbf-492e-b1aa-a7451a7dd6ef)

![image](https://github.com/payloadcms/payload/assets/5787117/f640b076-a9fc-4d9a-a941-56ff0e3ee171)

We can see that. There is no title in the private_media table.    

![image](https://github.com/payloadcms/payload/assets/5787117/551f937b-10c9-4909-a380-5d7ed167d833)

### Payload Version

2.2.1

### Adapters and Plugins

@payloadcms/db-postgres, @payloadcms/plugin-cloud-storage

**Comment by JarrodMFlesch** [comment]
@larryro can you provide a reproduction following this guide: https://github.com/payloadcms/payload/blob/main/ISSUE_GUIDE.md

I am unable to reproduce your error.

**Comment by JarrodMFlesch** [comment]
When you use the useAsTitle property, you need to have a field with the same name as that property. In this case you would want to add a title field inside your empty fields array.
