### ISSUE TITLE
postgresAdapter not work well with postgreSQL database created by digitalocean

### ISSUE THREAD

**Issue by larryro** [payloadcms/payload#4328]
### Describe the Bug

When we create a postgreSQL database via digitalocean and used it with postgresAdapter. It doesn't work. 

`[13:01:59] ERROR (payload): Error: cannot connect to Postgres. Details: self-signed certificate in certificate chain`

![image](https://github.com/payloadcms/payload/assets/5787117/740ff930-89de-4ff4-845e-cedb63fcea3e)

### To Reproduce

Create a postgreSQL database in digitalocean and used it in postgresAdapter.

Now it can be temporay fixed by specify the ca certificate like this below. But I guess there should be better solution. Because we are also using Prisma for our project at the same time. Switching from MySQL to PostgreSQL has been seamless. There is no need to do any hacks or modifications.

![image](https://github.com/payloadcms/payload/assets/5787117/264ca94b-1ce8-415e-b896-0d055d92ab14)

### Reference
https://github.com/brianc/node-postgres/issues/2558#issuecomment-1765441660
https://github.com/Budibase/budibase/issues/1967

### Payload Version

2.2.1

### Adapters and Plugins

@payloadcms/db-postgres

**Comment by jmikrut** [comment]
Hey @larryro - this is actually more of an issue for Drizzle than Payload as all we do is pass connection options straight to Drizzle for them to use.

Will you try looking on the Drizzle ORM GitHub repo to see if anyone else has any pointers for using a DigitalOcean Postgres droplet alongside of Drizzle?

https://github.com/drizzle-team/drizzle-orm
