### ISSUE TITLE
The document says that payload.init supports mongoOptions, but it does not actually support it.

### ISSUE THREAD

**Issue by liulian-13** [payloadcms/payload#4332]
### Link to reproduction

https://payloadcms.com/

### Describe the Bug

After upgrading the payload from v1.11.0 to v2.2.2, the previous mongoOptions option prompt is no longer supported.

<img width="1174" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/c352211b-ed53-4e75-89f4-cb99a83b7931">

<img width="1110" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/79723abe-b470-4500-8a92-52fde1cc4ca1">

**But [the document](https://payloadcms.com/docs/production/deployment#persistent-vs-ephemeral-filesystems) says that payload.init supports mongoOptions options**
<img width="1467" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/8dc8034a-0f03-49db-9af7-6829ec70e31c">

### To Reproduce

I want to know how to adjust the previous mongoOptions code under the new version (v2.2.2)? Thanks

### Payload Version

2.2.2

**Comment by DanRibbens** [comment]
Hello again @liulian-13,

This needs to be updated in the documentation. The property you are looking for is now specified in the mongooseAdapter in your config.

```ts
db: mongooseAdapter({
    connectOptions: {
      useFacet: false,
    },
    url: process.env.MONGO_URI
  }),
```
