### ISSUE TITLE
Lexical LinkFeature: phone link URL is not saved

### ISSUE THREAD

**Issue by pooledge** [payloadcms/payload#4358]
### Describe the Bug

Inside Lexical, I was hoping to save a link URL of type `tel:` similarly to its `mailto:` counterpart.

### To Reproduce

1. Create a link and assign its URL to `tel:+123`
2. Link is being properly formatted, by its URL remains `https://`

### Payload Version

2.3.1

### Adapters and Plugins

richtext-lexical v0.3.1

**Comment by MarkAtOmniux** [comment]
This is the code in charge of sanitising the URL, SUPPORTED_URL_PROTOCOLS does include 'mailto:'

```  sanitizeUrl(url: string): string {
    try {
      const parsedUrl = new URL(url)
      // eslint-disable-next-line no-script-url
      if (!SUPPORTED_URL_PROTOCOLS.has(parsedUrl.protocol)) {
        return 'about:blank'
      }
    } catch (e) {
      return 'https://'
    }
    return url
  }
  ```
  
  Are you getting any errors in the console? it might be that an error is being caught here

**Comment by AlessioGr** [comment]
https://github.com/payloadcms/payload/assets/70709113/c1727972-a64b-4a53-b72f-fc776f42cb23

I can't reproduce this at all, and like Mark mentioned, `SUPPORTED_URL_PROTOCOLS` does include `mailto:` and `tel:`.

Could you add a reproduction, as described in the [reproduction guide](https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md)?

**Comment by pooledge** [comment]
I was able to narrow it down: try using +12345. 0012345 works, but former is used to be a legit phone format afaik. And no, I don't see any errors server-/browser-side.

**Comment by AlessioGr** [comment]
Yep! I'm able to reproduce this for numbers prefixed with a + as well. Will fix this, thank you!
