### ISSUE TITLE
Live Preview: Rich text relationships not getting resolved properly

### ISSUE THREAD

**Issue by Cuzart** [payloadcms/payload#4362]
### Link to reproduction

https://github.com/Cuzart/live-preview-reproduction

### Describe the Bug

Using relationships in live preview does not resolve the relationship regardless of depth. The first render includes the full relationship (Media) object. The following rerenders only include the id. The issue occurs when using the UploadFeature or BlockFeature with relationships e.g. images. 

Here I am logging the stringified media object from the rich text node in the serializer. When the page is saved and reloaded you can see for a second how the first render includes the whole object (also logged to console). 

<img width="1512" alt="Bildschirmfoto 2023-12-03 um 15 30 44" src="https://github.com/payloadcms/payload/assets/60718229/31cb7d3d-bd3a-413d-85e1-f648e9840a1c">

The saved page works just as expected in the frontend and shows the whole object

<img width="1512" alt="Bildschirmfoto 2023-12-03 um 15 25 12" src="https://github.com/payloadcms/payload/assets/60718229/cb5b31a3-74c9-47fb-878b-a9e108231fba">

I have checked for similar issues and there were a few people reporting cases where the relationship is null or also only the id. All proposed solutions like adjusting depth, setting cors, or updating to the latest version do not solve this. It seems like the problem is not specific to lexical. 

Note: sometimes it seems to work just fine as long as you start editing the rich text editor for example inserting a paragraph above an upload block causes the relationship to only show the id again. 

Maybe related:
[https://github.com/payloadcms/payload/issues/4120](https://github.com/payloadcms/payload/issues/4120)
[https://github.com/payloadcms/payload/pull/4045](https://github.com/payloadcms/payload/pull/4045)

### To Reproduce

I have built a simple reproduction starting from the official website template in the payload repo. To reproduce just:
- replace the connection string in the .env file, install all dependencies and start the development server. 
- do not run the seed script but create an initial user at localhost:3000/admin
- create an index page at /home with all the required fields
- go to the content tab of the page and select the live-preview
- create a layout block with a rich text field e.g. Call to action
- create an upload or a block feature ( /upload, /Media Block)
- select an image from Media collection an see the logs in the console

first render is populated with the media object as expected the following renders only show the id. 

### Payload Version

2.3.1

### Adapters and Plugins

mongodb, webpack, lexical, live-preview

**Comment by kamilms21** [comment]
We got exactly the same problem

**Comment by jacobsfletch** [comment]
Turns out this was a problem in both Slate and Lexical. I've got a fix queued up in #4379.

**Comment by Cuzart** [comment]
Great, the fix solved this and it now populates the full object on every render. Unfortunately the live-preview itself is broken now. I just upgraded the payload versions on the reproduction repository. If you now start typing in the live preview the frontend won't receive the updates @jacobsfletch [Reproduction commit](https://github.com/Cuzart/live-preview-reproduction/commit/f18be8f49f61af6ad1cd2f14b2e15114c09ebf85)

**Comment by jacobsfletch** [comment]
@Cuzart this is likely due to the `live-preview-react` package is not downloading the latest version of `live-preview` due to a yarn.lock file or similar. If you're using yarn, can you delete your yarn.lock file and run `yarn` again? That should give you the most recent version which is compatible with the latest changes.

**Comment by Cuzart** [comment]
You're right. Thanks for the hint and the quick fix. It now works as expected for the upload feature but the problem seems to still exists for layout blocks. Tested both in my production project and in the provided reproduction.

<img width="733" alt="Bildschirmfoto 2023-12-08 um 16 03 53" src="https://github.com/payloadcms/payload/assets/60718229/8bb1bdff-7780-47d1-a4aa-377442949182">

**Comment by thijssmudde** [comment]
In my project i also use lexicalEditor with blocksFeature in which I have a TextImage block.

The following data is returned

```
{
  "format": "",
  "type": "block",
  "version": 2,
  "fields": {
    "id": "658f00811b31feb548e92fbc",
    "blockName": "",
    "blockType": "text-image",
    "text": "asdfasdf",
    "image": "6579b312c194d03a5802016c",
    "imagePosition": "top"
  }
},
```

**Comment by thijssmudde** [comment]
@Cuzart Are you also still running into this issue in which the value is an id and you cannot resolve the id to the object?

For any field using relationships the lexicalEditor does not return the entire structure:

```
{
    "value": "658c4fb94372ba6b8872f3dd",
    "relationTo": "news-pages"
}
```

I need value to be resolved to an object containing information about this newsPage

**Comment by Cuzart** [comment]
Yes but only for nodes with type "block".

I just tested this on the reproduction with relationships and it gets resolved as expected. Just double check if this could be due to depth set somewhere. If that does not work make sure that you are on the latest version of payload, lexical and live-preview, delete your yarn.lock and node_modules and try a fresh install @thijssmudde 

Sorry I don't see how #4120 should help with that I did a fresh install and all but this is still a bug for nodes with type "block". I guess the reason might be that you are checking for `result.value` in the traverseRichText but for blocks the nesting is a bit different `node.fields.<nameOfTheFieldWithRelationShip>`. So I think this should be reopened @jacobsfletch

**Comment by thijssmudde** [comment]
Rich text blocks data (either through live preview or published version).

<img width="583" alt="image" src="https://github.com/payloadcms/payload/assets/7371397/10e81b90-12a7-41dc-8e5b-3587a5c7ea88">

API data:
<img width="421" alt="image" src="https://github.com/payloadcms/payload/assets/7371397/f887720e-a42e-440e-8117-9d73c1588f8b">

Ive updated to the last version of all these packages.

**Comment by thijssmudde** [comment]
It seems like depth for GraphQL is not implemented in PayloadCMS. I need a depth of 1. The docs state ["Depth has no effect in the GraphQL API, because there, depth is based on the shape of your queries"](https://payloadcms.com/docs/getting-started/concepts#depth), however this is incorrect since richText has a depth in the GraphQL schema.

<img width="220" alt="image" src="https://github.com/payloadcms/payload/assets/7371397/5ecab01c-25c7-4256-ba88-55dabc7be5fb">

If I pass a depth of 1 or higher nothing happens to the GraphQL response.

**Comment by thijssmudde** [comment]
I switched to REST API to solve the depth issue.

**Comment by stefvw93** [comment]
Any news on this? We are also having this issue; rich text blocks are not consistently populated even though fetching with depth > 0

**Comment by stefvw93** [comment]
@jacobsfletch @thijssmudde @Cuzart I did some digging in the source code; I think the live preview package does not correctly resolve relations inside block type fields. I created an issue https://github.com/payloadcms/payload/issues/5285
