### ISSUE TITLE
Clarify if `plugin-nested-docs` supports parent/child relationships between two distinct collections

### ISSUE THREAD

**Issue by ChristianMay21** [payloadcms/payload#4367]
# Documentation Issue

The README for the `plugin-nested-docs` makes it clear that - at the very least - the plugin supports a parent/child relationship between two data items of the same collection type (for example, parent/child pages).

I may be missing something, in which case I apologize, but it does not seem clear to me while reading the README whether or not the plugin supports creation of parent/child relationships between two data items of different collections (for example, parent organizations and child employees).

## Expected Behavior
If the plugin does not support multi-collection parent/child relationships, I would personally expect a sentence in the README acknowledging as much.

If the plugin does support multi-collection parent/child relationships, I would personally expect an example of such usage - the current example appears to only demonstrate a relationship between parent/child pages.

**Comment by jacobsfletch** [comment]
Hey @ChristianMay21 currently no, you cannot create prent/child relationships between collections. But others have had a need for this as well, details here: https://github.com/payloadcms/plugin-nested-docs/discussions/22

**Comment by ChristianMay21** [comment]
Hi @jacobsfletch - I've made a PR with a minimal change to the plugin's README to clarify this limitation for other developers - please find it above.

**Comment by jaschaio** [comment]
@ChristianMay21 how did you solve this use case? e.G. parent/child relationships across collections like Organizations » Employees or Courses » Lessons

**Comment by ChristianMay21** [comment]
Hey @jaschaio - unfortunately I did not find anything super-simple.

What I ended up doing was: 
1. On the parent object, I added an array field - specifically an array of relationships to child objects. This makes it easy to get the child objects of any parent object.
2. On the child objects, I added a required relationship to a parent object.

The main flaw of this is that you have to set these two relationships separately - it's not too bad though, since you can directly edit child objects from the parent.

In the future, if Payload doesn't add parent/child functionality, I'll probably use some collection/field hooks to automate some of this/enforce consistency.

Let me know if you figure out something better - I was definitely disappointed that Payload didn't have any supported pattern for this very common use case.

In order t
