### ISSUE TITLE
createCollectionDoc api in Autosave is too slow

### ISSUE THREAD

**Issue by liulian-13** [payloadcms/payload#4386]
### Link to reproduction

https://payloadcms.com/

### Describe the Bug

<img width="1665" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/15af7392-5a22-4033-93d0-67bf639f5cee">

<img width="1649" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/fa3b8cfe-ffff-4a0d-906a-58eb8b2b5e5a">

<img width="1226" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/57945831-d335-4987-8bae-560612f2300b">

### To Reproduce

[source code locaiton](https://github.com/payloadcms/payload/blob/main/packages/payload/src/admin/components/elements/Autosave/index.tsx#L54):
<img width="1285" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/d42576f5-3c47-449e-9d58-4b05bf4aca67">

### Payload Version

1.11.1

**Comment by JarrodMFlesch** [comment]
Hey @liulian-13 we will need a bit more to reproduce this issue. If you want to create a reproduction that behaves like this consistently please link it here. There could be too many things going on that might be affecting this, i.e. hooks, access control etc. But it is really hard to diagnose without a reproduction or more info. For now I am going to close this issue.

We can re-open it if you are able to come up with a reproduction, thanks!
