### ISSUE TITLE
Media preview in admin UI list doesn't fallback to original size with plugin-cloud-storage

### ISSUE THREAD

**Issue by matteo-naif** [payloadcms/payload#4408]
### Link to reproduction

-

### Describe the Bug

If I use the plugin plugin-cloud-storage in the media list I can't see the thumbnail for images smaller than the crop I chose in the configuration.

### To Reproduce

1. Setup in the collection media the upload.imageSizes and the upload.adminThumbnail props
2. upload an image smaller than the upload.adminThumbnail size
3. open the collection media list in the admin ui
4. the system try to show the crop of the upload.adminThumbnail despite it doesn't exist

The config is the following
```ts
const Media: CollectionConfig = {
	slug: "media",
	admin: {
		group: "Media",
	},
	fields: [
		{
			name: "title",
			label: {
				it: "Titolo",
				en: "Title",
			},
			type: "text",
			localized: true,
		}
	],
	upload: {
		staticDir: path.resolve(__dirname, "../../media"),
		imageSizes: [
			{
				name: "squareSmall",
				width: 480,
				height: 480,
				position: "centre",
			},
			{
				name: "squareMedium",
				width: 900,
				height: 900,
				position: "centre",
			}
		],
		adminThumbnail: "squareSmall",
		mimeTypes: ["image/*", "application/pdf"],
	},
};
```

The cloud storage plugin config
```ts
cloudStorage({
    collections: {
        media: {
            adapter: s3adapter,
            disablePayloadAccessControl: true,
            prefix: process.env.S3_PREFIX_MEDIA,
            generateFileURL: ({ collection, filename, prefix, size }) => {
                if (!filename) return null;
                const folderPrefix = prefix ? `${prefix}/` : "";
                return `${process.env.S3_ENDPOINT_ORIGIN}/${folderPrefix}${filename}`;
            },
        },
    },
})
```

The workaround I found is to declare the upload.adminThumbnail property as function that check if the doc property of the crop exists. I expected this behaviour as default because it's the default without the plugin.

```ts
adminThumbnail: ({ doc }) => {
	return media.sizes.squareSmall.url || media.url;
}
```

### Payload Version

2.3.1

### Adapters and Plugins

		"@payloadcms/bundler-webpack": "1.0.5", 		"@payloadcms/db-mongodb": "1.1.0", 		"@payloadcms/plugin-cloud-storage": "1.1.1", 		"@payloadcms/plugin-form-builder": "1.0.15", 		"@payloadcms/plugin-nested-docs": "1.0.9", 		"@payloadcms/plugin-seo": "1.0.15", 		"@payloadcms/richtext-lexical": "0.3.1", 		"@payloadcms/richtext-slate": "1.2.1",

**Comment by JessChowdhury** [comment]
Hey @matteo-naif nice catch, this has been [fixed](https://github.com/payloadcms/payload/pull/4461) and will be out in our next release. Thanks for raising this!
