### ISSUE TITLE
Locale on `req` overwrites `locale` set on `findById`

### ISSUE THREAD

**Issue by RickGeersing** [payloadcms/payload#4409]
### Describe the Bug

I've implemented an afterRead hook that fetches all urls of the same document with different locales. However if I pass the `req` and `locale` in the same request. It chooses the locale on `req` over the one provided on `locale`. I expect this to be the other way around.

My afterRead hook:
```typescript
// findById request
const doc = await req.payload.findByID({
    collection: req.collection?.config?.slug as any,
    id: data.id,
    locale, // `en`
    req, // req.locale is set on `nl`
}) // Expect this to be in `en`
```

### To Reproduce

1. Create a `findById` call, and set it on a different locale that req.locale is 
2. You'll see that the document is fetched in the 'wrong' locale.

### Payload Version

1.11.7

**Comment by RickGeersing** [comment]
Haven't had the time to test this on 2.0, so could be fixed already. Not sure

**Comment by RickGeersing** [comment]
Problem was something completely else, changed the topic and contents.

**Comment by JarrodMFlesch** [comment]
@RickGeersing can you provide a reproduction? I threw together this example collection and it worked as I expected, prioritizing `en` instead of `es` which was on the request

```ts
{
  slug: 'test',
  access: {
    read: () => true,
  },
  hooks: {
    afterRead: [
      async ({ req, doc }) => {
        if (req?.context?.test) return
        const test = await req.payload.findByID({
          collection: req.collection?.config?.slug as any,
          id: doc.id,
          locale: 'en', // `en`
          req, // req.locale is set on `es`
          context: {
            test: 'test',
          },
          depth: 0,
        })

        console.log(test)
      },
    ],
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      localized: true,
    },
  ],
},
```

The request url looked like this:
```
http://localhost:3000/api/test?locale=es
```

The response consistently returns the english version of the document.

**Comment by RickGeersing** [comment]
In the meantime we've upgraded to 2.0, that seems to have fixed it.
