### ISSUE TITLE
There's a typo on the document. `https://payloadcms.com/docs/admin/components#views`

### ISSUE THREAD

**Issue by kuskhan** [payloadcms/payload#4428]
I'm sorry for that I don't know where I can report this typo.

https://payloadcms.com/docs/admin/components#views

dy -> by

You can easily swap entire views with your own by using the admin.components.views property. At the root level, Payload renders the following views ~~dy~~ default, all of which can be overridden:

You can easily swap entire views with your own by using the admin.components.views property. At the root level, Payload renders the following views **by** default, all of which can be overridden:

**Comment by jacobsfletch** [comment]
Got this fixed up, thank you for reporting this @kuskhan!
