### ISSUE TITLE
Defining internationalization (i18n) to `locales` in payload config breaks Version view in collections / globals

### ISSUE THREAD

**Issue by PatrikKozak** [payloadcms/payload#4429]
### Link to reproduction

Payload test suite - `admin`

### Describe the Bug

When defining locales in your payload config like the following:
```
locales: [
  {
    label: {
      es: 'Español',
      en: 'Spanish',
    },
    code: 'es',
  },
  {
    label: {
      es: 'Inglés',
      en: 'English',
    },
    code: 'en',
  },
],
```

The `version` view for version enabled `collections` / `globals` breaks with the following console errors:

![Screen Shot 2023-12-08 at 1 22 18 PM](https://github.com/payloadcms/payload/assets/35232443/b43e64ab-10d1-4dee-b6ae-f91075b740f6)

This issue stems from this merged [PR](https://github.com/payloadcms/payload/pull/4005)

### To Reproduce

The `admin` payload test suite has `locales` defined like this  in the payload.config already: 
```
locales: [
  {
    label: {
      es: 'Español',
      en: 'Spanish',
    },
    code: 'es',
  },
  {
    label: {
      es: 'Inglés',
      en: 'English',
    },
    code: 'en',
  },
],
```
 
Enable `versions` to any of the collections in this test suite. 

Run `pnpm dev admin`

Go to version enabled collection --> Versions view --> click into specific version --> breaks.

### Payload Version

2.4.0

**Comment by cbratschi** [comment]
@JarrodMFlesch yes, this is the same issue.

**Comment by PatrikKozak** [comment]
Closing since it's a duplicate of #4357
