### ISSUE TITLE
swc deserialize issue on ecommerce and website templates with new ts-node 10.9.2

### ISSUE THREAD

**Issue by arymoraes** [payloadcms/payload#4435]
### Describe the Bug

Since ts-node updated yesterday to version `10.9.2`, starting a new `payload` app using `npx create-payload-app@latest` and choosing either the `ecommerce` or `website` template will cause the following issue when trying to run `yarn dev`:

```
.../cmswebsitetemplate/node_modules/ts-node/src/transpilers/swc.ts:259
      throw new Error(
            ^
Error: @swc/core threw an error when attempting to validate swc compiler options.
You may be using an old version of swc which does not support the options used by ts-node.
Try upgrading to the latest version of swc.
Error message from swc:
Failed to deserialize buffer as swc::config::Options
JSON: {"sourceMaps":true,"module":{"type":"commonjs","noInterop":false,"strictMode":true,"ignoreDynamic":false},"swcrc":false,"jsc":{"parser":{"syntax":"typescript","tsx":false,"dynamicImport":true,"importAssertions":true},"target":"es5","transform":{"legacyDecorator":true,"react":{"throwIfNamespace":false,"useBuiltins":false},"useDefineForClassFields":false},"keepClassNames":false,"experimental":{"keepImportAttributes":true,"emitAssertForImportAttributes":true}}}

Caused by:
    unknown field `keepImportAttributes`, expected one of `plugins`, `keepImportAssertions`, `cacheRoot` at line 1 column 462

```

I believe this is caused by the new `ts-node` version being incompatible with `swc 1.3.76`, as swapping ts-node version from `^10.9.1` to `10.9.1` on `package.json` fixes the issue and `yarn dev` is able to run properly.

Updating `@swc/core` to the latest version (1.3.100) also fixes the issue.

### To Reproduce

1. run `npx create-payload-app@latest`
2. choose any project name
3. choose either `website` or `ecommerce` project template
4. choose a database
5. enter a connection string
6. cd into the project
7. run `yarn dev`

### Payload Version

2.4.0

**Comment by nheingit** [comment]
+1 encountered this today. found this when I was looking around

https://github.com/swc-project/swc/issues/7923

**Comment by AlessioGr** [comment]
I've pinned the ts-node versions for all affected templates - this shouldn't happen anymore. Thank you for reporting this!
