### ISSUE TITLE
Payload Cloud not compatible with pnpm

### ISSUE THREAD

**Issue by nheingit** [payloadcms/payload#4439]
### Describe the Bug

I tried to install the website-demo project and pulled it down from payload cloud to my local machine. I prefer to use pnpm so I tried to use that, but when pushing changes back up I get hit with this error since pnpm doesn't generate a `package-lock` or `yarn-lock` file, it generated a `pnpm-lock.yaml` file which it seems payload isn't looking for.

<img width="1527" alt="Screenshot 2023-12-10 at 4 09 45 PM" src="https://github.com/payloadcms/payload/assets/60185486/3bd37a76-e245-434a-9695-b7f625e9163e">

### To Reproduce

1. pull down project from payload cloud

2. try to switch package manager from yarn to pnpm

3. try to push up new changes and deploy project.

### Payload Version

^2.0.7

### Adapters and Plugins

db-postgres, bundler-webpack

**Comment by mhogeveen** [comment]
@nheingit Has this issue been resolved? Just tried to do the same thing and ran into this issue myself.
