### ISSUE TITLE
Date Picker months and years not visible in dark mode

### ISSUE THREAD

**Issue by dag0310** [payloadcms/payload#4443]
### Describe the Bug

The date picker does not support dark mode and so it shows the month and year select entries very light so that they aren't visible well:

![grafik](https://github.com/payloadcms/payload/assets/4202238/5800bfae-52ea-43d8-8fff-9ad7b8410026)

### To Reproduce

- Use a field with type: 'date' anywhere in the admin UI
- Make sure you have dark mode enabled for your backend user

### Payload Version

2.4.0

**Comment by AlessioGr** [comment]
![Screenshot 2023-12-11 at 14 38 43](https://github.com/payloadcms/payload/assets/70709113/30654baf-e829-4cbe-8fdb-2a657107b6b9)

At least on macOS, this works fine for me - it just uses the native <select> element for this.

What is your browser and operating system?

**Comment by jacobsfletch** [comment]
It's likely that the OS theme is different than Payload's selected theme.

**Comment by dag0310** [comment]
I have Windows 10 with dark mode enabled. Also it doesn't matter if in my Payload user profile I have set dark mode automatically or set manually. I guess the reason is that Windows 10 allows styling the select options while macOS/Safari does not(?) Happens in Chrome and Firefox.
