### ISSUE TITLE
Dependency in @payloadcms/db-postgres@0.2.1 is missing a license, preventing download in my organization

### ISSUE THREAD

**Issue by AshtarCodes** [payloadcms/payload#4454]
### Describe the Bug

I cannot get this package (@payloadcms/db-postgres@0.2.1 ) approved by my job because its dependency (@drizzle-team/studio@0.0.5) does not have a license.

Would it be possible to look into this / update it?

### To Reproduce

Cannot reproduce as it is internal to my job.

### Payload Version

2.4.0

### Adapters and Plugins

db-postgres@0.2.1

**Comment by JessChowdhury** [comment]
@AshtarCodes the license for that package can be found on [npm](https://www.npmjs.com/package/drizzle-orm), does this help you?

**Comment by JarrodMFlesch** [comment]
@AshtarCodes I am going to close this since you already opened an issue on their repo and there is nothing we can do on our end.
