### ISSUE TITLE
plugin-form-builder: A dependency in @payloadcms/plugin-form-builder@1.0.15 has a severe vulnerability

### ISSUE THREAD

**Issue by AshtarCodes** [payloadcms/payload#4455]
### Describe the Bug

I am attempting to download @payloadcms/plugin-form-builder@1.0.15, however my organization doesn't allow me due to a a severe vulnerability for a dependency (sharp@0.31.3).

<img width="495" alt="image" src="https://github.com/payloadcms/payload/assets/74083145/0f4d8fda-1b82-44c8-b3e6-cbbb9fdcffe0">

### To Reproduce

Install the plugin and note the security vulnerability reported by npm

### Payload Version

2.4.0

### Adapters and Plugins

@payloadcms/plugin-form-builder@1.0.15

**Comment by denolfe** [comment]
Sharp dep has since been bumped to `0.32.6`
