### ISSUE TITLE
_verified field is added to collection filter and column

### ISSUE THREAD

**Issue by JulianAtTheFrontend** [payloadcms/payload#4458]
### Describe the Bug

When enabling a verification Email a `_verified` field be added to the collections filter and column selection component. As it's also not translated I guess this is unintended behaviour.

### To Reproduce

Create a collection with auth enabled and add a custom email verification like [here](https://payloadcms.com/docs/authentication/config#email-verification)

### Payload Version

2.0.11

**Comment by JessChowdhury** [comment]
Hi @JulianAtTheFrontend, thanks for raising this - I have added a translated label for the `verified` field [here](https://github.com/payloadcms/payload/pull/4509).

The addition of this field is intentional when verification is enabled, however you can choose to hide it by overwriting the field in your auth collection, like this:

```ts
{
  name: '_verified',
  type: 'checkbox',
  hidden: true,
}
```

**Comment by JulianAtTheFrontend** [comment]
@JessChowdhury thanks for the quick fix. I noticed overwriting this field does work except for when it's placed in a tab. Other fields in tabs that are hidden will appear, too.

**Comment by JulianAtTheFrontend** [comment]
Yes, I have a sample collection with a hidden field in a tab


```
import {CollectionConfig} from "payload/types";

const Test: CollectionConfig = {
  slug: 'test',
  fields: [{
    type: 'tabs',
    tabs: [
      {
        label: 'Tab 1',
        fields: [
          {
            name: 'shouldBeHidden',
            type: 'text',
            hidden: true,
          },
        ]
      }
    ]
  }]
}

export default Test;
```

![Bildschirmfoto 2023-12-15 um 08 04 38](https://github.com/payloadcms/payload/assets/92525148/b51bbd43-da3c-43f9-8bda-897a84a2b63a)

**Comment by JessChowdhury** [comment]
@JulianAtTheFrontend fab thank you, I was able to replicate the issue and have opened a fix [here](https://github.com/payloadcms/payload/pull/4516).
