### ISSUE TITLE
Wrong type Payload.collections

### ISSUE THREAD

**Issue by chladog** [payloadcms/payload#447]
# Bug Report

## Expected Behavior

The exported type of Payload.collections should be: 
```JS
{
    [slug: string]: Collection;
}
```
## Current Behavior

Intellisense shows: ```(property) Payload.collections: Collection[]``` based on index.d.ts.

Actual type of Payload.collections is an Object:
```JS
  collections: {
    [slug: string]: Collection;
  } = {}
```
To read the collections we have to read object values Object.values(payload.collections), not an array.

payload 0.14

**Comment by chladog** [comment]
Also Collection type is missing "graphQL" property that exists on it.
I had to extend the type for [this usecase](https://github.com/payloadcms/payload/discussions/448) for example

**Comment by jmikrut** [comment]
Hey @chladog — these items are now revised as of `payload@0.14.24-beta.0`. Thank you!
