### ISSUE TITLE
Multiple locales in 1 aliased GraphQL query uses the bottom most locale in the query.

### ISSUE THREAD

**Issue by dacgray** [payloadcms/payload#4484]
### Describe the Bug

While I can use aliases to get multiple documents, I can't get different locale data per alias.  It always only pulls locale data for the bottom most locale in the query.

Hoping to use one query for a page language switcher.

### To Reproduce

`text` is a localized field.

```
{
  de: StaticPageV1(id: "6524e7d686ebc1443f5f88f4", locale: de_DE) {
    id
    title {
      text
    }
  }

  en: StaticPageV1(id: "6524e7d686ebc1443f5f88f4", locale: en_GB) {
    id
    title {
      text
    }
  }
}

```

![image](https://github.com/payloadcms/payload/assets/12794616/22e651c4-ce3e-4fdd-81e4-278fff7caf73)

![image](https://github.com/payloadcms/payload/assets/12794616/3aed6b17-ee10-40fc-8219-fb02eaf7f5d1)

### Payload Version

2.4.0

### Adapters and Plugins

"@payloadcms/bundler-webpack": "^1.0.5",     "@payloadcms/db-mongodb": "^1.1.0",     "@payloadcms/plugin-cloud-storage": "^1.1.1",     "@payloadcms/plugin-sentry": "^0.0.6",     "@payloadcms/richtext-slate": "^1.3.0",

**Comment by DanRibbens** [comment]
Fixed in PR https://github.com/payloadcms/payload/pull/4560, will be in the next release.
