### ISSUE TITLE
plugin-stripe: `StripeWebhookHandler` cannot be `async` with strict linter rules

### ISSUE THREAD

**Issue by allannnc** [payloadcms/payload#4492]
![image](https://github.com/payloadcms/plugin-stripe/assets/103010201/080e98a7-7e08-411a-897e-1d5676657fc4)

Hi, I've been updating my repos with new recommended linter rules from eslint v6 and am getting this error on `stripePlugin.webhooks` because of the type of `StripeWebhookHandler` screenshotted below. It does not include `Promise<void>` as a return type

![image](https://github.com/payloadcms/plugin-stripe/assets/103010201/8e7b7a50-c49c-4c4f-8bd6-c9632ff769d2)

I had a quick look at the code in this repo and it *seems* that async handlers should be properly handled (and this has been working in prod for us), just the type definition might be inaccurate

I believe all that needs to happen is `| Promise<void>` added to the return type of `StripeWebhookHandler`

Update: I have worked around the linter errors by adding this to my eslint config:
```ts
{
"@typescript-eslint/no-misused-promises": [
      "error",
      {
        /**
         * allow passing async functions to things without a `Promise<T>` return type e.g. allow
         * ```ts
         * type Endpoint = {
         *   handlers: (...args) => void; // no`| Promise<void>` in the return type, but `async` handlers work fine
         * }
         * ```
         */
        "checksVoidReturn": false
      }
    ],
}
```

**Comment by jacobsfletch** [comment]
@allannnc thank you for patience on this one, this should go out in the next release. I've got a duplicative PR pointing against beta as well, to prevent regression on v3.
