### ISSUE TITLE
Options to enable Sentry Integration for query performance profiling

### ISSUE THREAD

**Issue by darr1s** [payloadcms/payload#4499]
Hello, I noticed PluginOptions do not accept any sentry integrations. Is this intended, is there a way I can profile the slow query?

**Comment by JessChowdhury** [comment]
Hi @darr1s, this is how you can pass integrations to the plugin - with `options.init`:

```ts
const { ProfilingIntegration } = require("@sentry/profiling-node");

 plugins: [
    sentry({
      dsn: 'process.env.SENTRY_DSN',
      options: {
        init: {
          profilesSampleRate: 1.0, 
          integrations: [
            // Add your integration here
            new ProfilingIntegration(), // for example
          ],
        },
      },
    }),
  ],
```

The options are grouped based on the [Sentry function](https://docs.sentry.io/platforms/node/profiling/?original_referrer=https%3A%2F%2Fwww.google.com%2F#enabling-profiling) the props are being passed to. Let me know if you need anything else here!
