### ISSUE TITLE
[docs]: link shows 404

### ISSUE THREAD

**Issue by babakfp** [payloadcms/payload#4522]
Hi.

In this [file](https://github.com/payloadcms/payload/blob/main/packages/plugin-form-builder/README.md), the "Documentation" text, links to a [404 page](https://payloadcms.com/docs/plugins/form-builder).

**Comment by jacobsfletch** [comment]
Hey @babakfp you must have caught that page at the perfect time just as the website was being redeployed. It's now loading as expected 👍 thank you for pointing it out.
