### ISSUE TITLE
Suggestion to bump node versions

### ISSUE THREAD

**Issue by Surm4** [payloadcms/payload#4536]
### Describe the Bug

Hello I was facing installation issue, when I was trying to get started with payload.

I'd like to suggest to bump .node-version file and package.json > engines.node property because it confuses the new user.

### To Reproduce

1. I just wanted to run **npx create-payload-app** for the very first time on node version 18.7.1 and then I selected **ecommerce** template and in a result I got an installation error. Having ubuntu operating system might also be the case **but** it looks like on the current node LTS version it installed properly so I guess the problem is there.

![payload bump version](https://github.com/payloadcms/payload/assets/40576160/e6af307b-726b-42dd-a0c5-71bb725d99fe)

### Payload Version

2.4.0

**Comment by Surm4** [comment]
Have you tried to reproduce on ubuntu?

**Comment by paulpopus** [comment]
Hey @Surm4 I tried to reproduce this on Ubuntu 22 LTS with these steps:

1. `nvm install 18.17.1`
2. `nvm use 18.17.1`
3. `npx create-payload-app`
4. choose ecommerce and then defaults

And it installs successfully for me with no errors.

In your screenshots I see this error
![image](https://github.com/payloadcms/payload/assets/35137243/be716072-91bb-44f1-87ac-403f04de8f2c)
This suggests that it's instead an issue with the connection to npm instead

Are you able to reproduce this consistently? If so more information might be useful here, but I will mark it as can't reproduce for now
