### ISSUE TITLE
Setting a custom ID field inside a tab breaks the ability to set a custom ID for the collection

### ISSUE THREAD

**Issue by GeorgeHulpoi** [payloadcms/payload#4546]
Reproduction: https://github.com/GeorgeHulpoi/payload-seo-bug

1. Create a collection having a custom id.
2. Add this collection to seo plugin
3. Set tabbedUI equal with true.

From now, the id is no longer working, is using the ObjectId + the custom id.

**Comment by paulpopus** [comment]
Reproduced this bug outside the scope of the plugin, it's related to the custom ID field being placed inside a tab (unnamed included)
