### ISSUE TITLE
plugin-seo: Suggestion: better tabbedUI config 

### ISSUE THREAD

**Issue by hades200082** [payloadcms/payload#4549]
Use case: I'd like to have some fields appear above my tabs in the admin UI.

If this plugin either just looks for the _first tab field_ rather than just checking if the first field is `type: "tabs"` then it could add itself to the first set of tabs it finds.

Alternatively, you could extend the plugin config to allow selection of whether the user wants the SEO tab to be added to the first main tabs field, or the first sidebar tabs field.

**Comment by PatrikKozak** [comment]
@hades200082 Appreciate the suggestion, we'll keep this in mind  - going to convert to a feature request.
