### ISSUE TITLE
Can not search by ID

### ISSUE THREAD

**Issue by wrobson-lllow** [payloadcms/payload#4561]
### Describe the Bug

This seems related to bug #4464. I just updated to payload 2.5.0 (which fixed the issue with editing a JSON field, Thank you very much!) However, I'm still having an issue when searching for a record by ID. I'm getting the following error on the server:
`[20:12:20] ERROR (payload): Error: Can't use $regex
    at ObjectId.SchemaType.castForQuery (C:\Users\williamrobson\lllow\low-customer-management\lcm\node_modules\mongoose\lib\schematype.js:1632:13)     
    at ObjectId.SchemaType.castForQueryWrapper (C:\Users\williamrobson\lllow\low-customer-management\lcm\node_modules\mongoose\lib\schematype.js:1603:22)` 
    
  As before this error only occurs when searching on a collection where the ID is generated by payload. I have several collections where the ID is generated from user Input and I am able to search by those ID's no problem. Here is my "listSearchableFields" from the admin config of one of the collections where I'm experiencing this issue:
  
![image](https://github.com/payloadcms/payload/assets/132296416/c6b24403-6aa7-483b-ba21-adda1097b8bb)

### To Reproduce

Search by ID on a collection list view where "id" is included in searchable fields and  the ID is not a custom field, but generated automatically by Payload when the record is created.

### Payload Version

2.5.0

### Adapters and Plugins

bundler: webpackBundler,  db: mongooseAdapter

**Comment by PatrikKozak** [comment]
Hey @wrobson-lllow - what version of `@payloadcms/db-mongodb` are you on? 

On top of the release we just did for Payload (2.5.0) -

we also released a new version of `@payloadcms/db-mongodb` (1.1.1) as #4464 involved changes in `Payload` core and in the `db-mongodb` package

**Comment by wrobson-lllow** [comment]
@PatrikKozak I'm on ^1.1.0 i thought it would have used 1.1.1 automatically. I'll update that and give it a try. Thanks for the fast response! Much Appreciated!

**Comment by wrobson-lllow** [comment]
That did it! You're the best! That bug has been annoying me for weeks now.

**Comment by wrobson-lllow** [comment]
Update @payloadcms/db-mongodb to 1.1.1 when updating to payload 2.5.0 solves issue.
