### ISSUE TITLE
Endpoint doesn't have rate limiter

### ISSUE THREAD

**Issue by GeorgeHulpoi** [payloadcms/payload#4567]
### Link to reproduction

https://github.com/GeorgeHulpoi/payload-endpoint-rate-limiter

### Describe the Bug

Endpoints doesn't have rate limiter.

### To Reproduce

Open the server and call `/api/ping`. It doesn't contain the headers for rate limiter.

### Payload Version

2.5.0

### Adapters and Plugins

MongoDB + webpack

**Comment by jmikrut** [comment]
Hey @GeorgeHulpoi — from your repro, I figured out the discrepancy here. You're saying `root: true` which deliberately bypasses all Payload-provided middleware and adds the endpoint to the root Express app.

If you want your endpoint to inherit Payload middleware like rate limiting, you would need to remove `root: true`, and then remove the `/api` segment in the path:


```ts
export const PingEndpoint: Endpoint = {
	root: false,
	path: '/ping',
	method: 'get',
	handler: (req, res, next) => {
		res.send('pong');
	},
};
``` 

This should do it! I am pretty confident. But if for some reason I am lying here, please re-open the issue!
