### ISSUE TITLE
Tab `interfaceName` triggers schema error 

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/payload#4572]
### Describe the Bug

Setting an `interfaceName` on a `tab` and reusing that `tab` declaration triggers a schema error as follows:

```
/Users/seth/dev/backend/node_modules/graphql/type/schema.js:219
        throw new Error(
              ^
Error: Schema must contain uniquely named types but contains multiple types named "SyndicationsInterface".
```

I can confirm there are no naming collisions (unless I'm misunderstanding the usage here).

### To Reproduce

Create a tab as follows:
```
{
    type: 'tabs',
    tabs: [
        {
            label: 'Syndications',
            name: 'syndications',
            interfaceName: 'SyndicationsInterface',
            fields: [ ...
```

Add this tab to 2 collections and attempt to start the development server.

### Payload Version

2.5.0

### Adapters and Plugins

db-mongodb bundler-webpack

**Comment by ssyberg** [comment]
Wondering if anyone has ideas for a workaround in the meantime? We use this interface in like 20 collections and I think not having it will lead to some serious GraphQL havoc.

**Comment by ssyberg** [comment]
BTW this seems to only be broken for `tabs`, if I convert my tab field to a group it works (though ruins admin UX 😉 )

**Comment by jmikrut** [comment]
@ssyberg we are looking at this now, hoping to have a solution to you ASAP
