### ISSUE TITLE
Live Preview Renders off screen

### ISSUE THREAD

**Issue by ericuldall** [payloadcms/payload#4576]
### Describe the Bug

I've created a landscape & portrait version of a 1440x900 display and when using them they don't render entirely on my screen.

<img width="1394" alt="image" src="https://github.com/payloadcms/payload/assets/3223296/9cdb53e9-c24c-41c9-9b05-33c7767e58a2">

Nothing else extraordinary about my build. Just a basic payload 2.0 scaffolding. 

### To Reproduce

You don't even need a preview endpoint working to reproduce the behavior just set the following breakpoints:
```
livePreview: {
      url: 'http://localhost:3000/admin/does-not-matter',
      breakpoints: [
        {
          label: 'Landscape',
          name: 'landscape',
          width: 1440,
          height: 900,
        },
        {
          label: 'Portrait',
          name: 'portrait',
          width: 900,
          height: 1440,
        },
      ],
}
```

### Payload Version

2.5.0

**Comment by PatrikKozak** [comment]
Hey @ericuldall - so the `breakpoints` really depend on how much available screen size you have . If you don't have 1920 pixels available, then you can't preview all 1920 pixels - does this make sense?

However, there are a few approaches we could take to making this more functional. For example, adding overflow scroll or auto zoom/scale. 

These would be considered features to the `live-preview` package so if this is something you'd be interested in having - open a feature request in our Discussions tab and we'll get this added to our roadmap.

Let me know if you have any other issues or questions!

**Comment by JarrodMFlesch** [comment]
@PatrikKozak I think the idea would be to make the screen proportional, not sure of the side affects though. You can see how chrome does this in their mobile/table screen view.

I believe this is likely what @ericuldall is expecting.

![CleanShot 2023-12-21 at 3  07 46](https://github.com/payloadcms/payload/assets/30633324/eb946560-9fef-4d6e-9ba1-1a696ff98b1e)

**Comment by PatrikKozak** [comment]
@JarrodMFlesch I think this would be a good approach.

@ericuldall I went ahead and opened a feature request [here](https://github.com/payloadcms/payload/discussions/4588). Feel free to add to it!

I will ping you when we get this planned out - thank you for bringing this to our attention!
