### ISSUE TITLE
The postgres adapter's migrate:down downgrades all migrations instead of ones in the latest batch

### ISSUE THREAD

**Issue by stephaniesyed** [payloadcms/payload#4591]
### Describe the Bug

The [getMigrations function](https://github.com/payloadcms/payload/blob/8015e999cd5834f532a200ef03fd392d04b3209f/packages/payload/src/database/migrations/getMigrations.ts#L7) returns existingMigrations (all migrations in the db with a batch number != -1) and latestBatch (the batchId of the latest set of applied migrations). 

However, the postgres implementation of  [migrateDown](https://github.com/payloadcms/payload/blob/8015e999cd5834f532a200ef03fd392d04b3209f/packages/db-postgres/src/migrateDown.ts#L15) uses the existingMigrations variable as if it has been filtered by batchId -- it iterates through all migrations returned and runs their down function.

This means any time a user runs migrate:down, it will destroy the entire database rather than running down for the latest set of migrations.

I think all that needs to change is 
```
if (!existingMigrations?.length) {
    payload.logger.info({ msg: 'No migrations to rollback.' })
    return
  }

  let latestMigrations = existingMigrations.filter((m) => m.batch === latestBatch)

  payload.logger.info({
    msg: `Rolling back batch ${latestBatch} consisting of ${latestMigrations.length} migration(s).`,
  })

  for (const migration of latestMigrations) {
...
```

I tried to follow the reproduction guide, but had trouble finding a way to get the set up running in a way where I could use `payload` script commands.

I have a branch locally with the change implemented, and am trying to figure out how to write tests for this.

### To Reproduce

1. Create the inital migration for a payload app using the postgres db adapter.
2. Apply that migration
3. Create a second migration
4. Apply that migration (at this step, you can query the payload_migration table to verify they were applied in two different batches)
5. Run payload migrate:down
6. The log line will say "Rolling back batch 2 consisting of 2 migration(s)." and will downgrade both migrations, leaving you with an empty database. 

I can provide a video of me reproducing it, but it's too large to attach here

### Payload Version

2.4.0

### Adapters and Plugins

none

**Comment by gallexi** [comment]
Hey @denolfe, thanks for maintaining this project!

Just wanted to follow up on this issue- as far as we can tell, this bug prevents us from being able to do _any_ down migrations without dropping the whole database. As such, it's blocking us from confidently using Payload with Postgres in production.

Totally understand if this isn't your first priority, but I was wondering if we could get a sense of when this bug might be reviewed? This will help us prioritize either trying to upstream the change ourselves, or trying to work around it.

Thanks!

**Comment by gallexi** [comment]
Thank you so much @DanRibbens!
