### ISSUE TITLE
Postgres adapter apply only one unique constraints when there are more than one tables with the same unique fields.

### ISSUE THREAD

**Issue by xiaohanyu** [payloadcms/payload#4608]
### Link to reproduction

https://github.com/xiaohanyu/test-payload

### Describe the Bug

Postgres only respect one unique constraints when more than one collections with the same unique fields.

### To Reproduce

Steps to reproduce the bug:

- Init a new payload app by `npx create-payload-app@latest`, as of now, the latest payload app is 2.5.0
- Create two new collections, [Resumes](https://github.com/xiaohanyu/test-payload/blob/main/src/collections/Resumes.ts) and [Templates](https://github.com/xiaohanyu/test-payload/blob/main/src/collections/Templates.ts) and add these two new collections to [payload.config.ts](https://github.com/xiaohanyu/test-payload/blob/main/src/payload.config.ts#L19)
- Start payload app by `npm run dev`

Check postgres table, 

<img width="1054" alt="image" src="https://github.com/payloadcms/payload/assets/1164623/c0b20e2a-12f2-401f-b816-cc819b899b46">

You can see that `resumes` table has `"title_idx" UNIQUE, btree (title)` where `templates` do not have this unique index, however, the title field in both `Resumes` and `Templates` collection are the same:

```js
    {
      name: "title",
      label: "Title",
      type: "text",
      required: true,
      unique: true,
      minLength: 2,
      maxLength: 64,
    }
```

### Payload Version

^2.0.0

### Adapters and Plugins

db-postgres, bundler-webpack

**Comment by DanRibbens** [comment]
Hi @xiaohanyu!

This was fixed in https://github.com/payloadcms/payload/releases/tag/v2.10.0 via https://github.com/payloadcms/payload/pull/4967

Let us know if you have any issues.
