### ISSUE TITLE
[cli] incorrect caret position when using (`ctrl` + `a`)

### ISSUE THREAD

**Issue by babakfp** [payloadcms/payload#4609]
### Describe the Bug

https://github.com/payloadcms/payload/assets/44144724/f5ee2fb3-ba0c-470b-b302-d0906e0e0143

1. Write `abc`
2. Press (`ctrl` + `a`)
3. Press the right directional key
4. Now you can see the caret goes to right 3 times (3 spaces)

I'm using PowerShell version 7.

### To Reproduce

.

### Payload Version

.

**Comment by denolfe** [comment]
I'm not sure this is normal usage and likely has something to do with your terminal specifically. As long as normal usage is not affected, I don't see this being an issue.
