### ISSUE TITLE
When getting en error in the console, the same error must be shown on the client side too

### ISSUE THREAD

**Issue by babakfp** [payloadcms/payload#4613]
### Describe the Bug

Hi

I'm getting this error in the console:

```
GraphQLError: Names must only contain [_a-zA-Z0-9] but "birth-date" does not.
```

The problem is, that the client side should also throw/show the same error.

I added a custom field to the `User` collection and the dashboard stopped working, after wasting a bit of time, (after restarting the server) I realized there was an error on the console!

### To Reproduce

Just use `npx create-payload-app@latest`, choose the blank site, add the code below to the `User` collection.

```js
fields: [
    {
        type: "date",
        name: "birth-date",
    },
  ],
```

Versions:

```json
{
  "dependencies": {
    "@payloadcms/bundler-webpack": "^1.0.0",
    "@payloadcms/db-mongodb": "^1.0.0",
    "@payloadcms/plugin-cloud": "^2.0.0",
    "@payloadcms/richtext-slate": "^1.0.0",
    "cross-env": "^7.0.3",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "payload": "^2.0.0"
  },
  "devDependencies": {
    "@types/express": "^4.17.9",
    "copyfiles": "^2.4.1",
    "nodemon": "^2.0.6",
    "ts-node": "^9.1.1",
    "typescript": "^4.8.4"
  },
  "resolutions": {
    "jackspeak": "2.1.1"
  }
}
```

### Payload Version

.

**Comment by JarrodMFlesch** [comment]
Hey @babakfp there's a fundamental difference from server to client here, the client is not rendering because there is a server error. Therefore there is no way to show the error on the client.

More of a learning experience, if the dashboard is not rendering, check the server console! I am going to close this issue.

**Comment by babakfp** [comment]
> Hey @babakfp there's a fundamental difference from server to client here, the client is not rendering because there is a server error. Therefore there is no way to show the error on the client.
> 
> More of a learning experience, if the dashboard is not rendering, check the server console! I am going to close this issue.

Can't we catch it and send it to the client?
