### ISSUE TITLE
Dependency: Update `mongodb` package to v5 or v6

### ISSUE THREAD

**Issue by charkour** [payloadcms/payload#4617]
### Describe the Bug

Hi Payload Team,

Many Payload users are hosting their MongoDB instance on Atlas as per the [Payload Docs](https://payloadcms.com/docs/production/deployment#letting-someone-else-do-it). This works great, however, Atlas is updating their Mongo instances from v6 to v7 in February 2024 (see photo). Looking at the [Node.js MongoDB compatibility guide](https://www.mongodb.com/docs/drivers/node/current/compatibility/), to use v7, it's recommended to use v5 or v6 of the npm package `mongodb`; however, it's likely v4.17.1 (which is currently used in `@payloadcms/db-mongodb`) will continue to work with the v7 Mongo Atlas instance. When Atlas updates instance versions, there is a potential for bugs to occur for Payload users hosting Mongo on Atlas.

<details>
<summary>Email from Mongo Atlas</summary>

![image](https://github.com/payloadcms/payload/assets/33156025/576cc845-5e5d-4c1f-b868-58ac41e6e1d0)

</details>

Thank you

### To Reproduce

Visit https://github.com/payloadcms/payload/blob/657d14c07b4c6da4f168a6b6853f932c44527639/packages/db-mongodb/package.json#L36C3-L36C24 and note this version is v4.x and not v5 or v6 on the [Node.js MongoDB compatibility guide](https://www.mongodb.com/docs/drivers/node/current/compatibility/).

### Payload Version

^2.x

### Adapters and Plugins

db-mongodb

**Comment by cbratschi** [comment]
Payload is still using Mongoose 6.x where 8.x was just released: https://www.npmjs.com/package/mongoose.

I am using MongoDB 7.x and never had any issues with Mongoose 6.x.

**Comment by charkour** [comment]
Thanks for the info, @cbratsch!
