### ISSUE TITLE
GraphQL expects JSON type when querying on relationship field with variable

### ISSUE THREAD

**Issue by MarkAtOmniux** [payloadcms/payload#4632]
### Describe the Bug

When attempting to query on a relationship field with a variable using GraphQL, the expected variable type is JSON rather than String. However, the actual value being passed to the query is indeed a string.

![Screenshot 2023-12-29 at 14 08 38](https://github.com/payloadcms/payload/assets/90132604/54ab1c4f-3950-4b92-8148-63071f9fcf21)

As can be seen below, despite the type being a string, graphQL will throw an error if you specify it as such

![Screenshot 2023-12-29 at 14 09 42](https://github.com/payloadcms/payload/assets/90132604/e4034b73-86e3-4b56-a6dd-20a86e7743ef)

### To Reproduce

Create 2 collections (for example, Pages and Organizations). 

Add a relationship field to one of the collections.

Attempt to perform a query on the collection with the relationship field using the GraphQL playground. Specify the relationship field as the target field to query on. For example;

```graphql
query Page($organization: String) {
  Pages(where: { organization: { equals: $organization } }) {
    docs {
      id
      organization {
        id
      }
    }
  }
}
```

pass the following query variable;

`{ "organization": "organisation id here" }`

Run this query and see the error in the GraphQL playground. Change the type from String to JSON and re-run the query. It should succeed

### Payload Version

2.5.0

### Adapters and Plugins

db-mongodb, bundler-webpack, plugin-seo, plugin-nested-docs

**Comment by paulpopus** [comment]
Hey @MarkAtOmniux closing this one as per comment here: https://github.com/payloadcms/payload/pull/4660#issuecomment-1874601753

Looks like due to a lack of unions, JSON is the necessary evil here, so you should use `JSON` as the type and then typecast it in your frontend or ignore it if you need to

I made a note to add this bit of key information to the docs
