### ISSUE TITLE
Error while testing "live preview" dir with postgres

### ISSUE THREAD

**Issue by devhik0** [payloadcms/payload#4641]
### Describe the Bug

```sh
> pnpm dev:postgres live-preview

[nodemon] starting `ts-node ../../test/dev.ts -- -I live-preview`
[15:05:11] INFO (payload): ---- DROPPING TABLES ----
[15:05:12] INFO (payload): ---- DROPPED TABLES ----
[15:05:13] INFO (payload): Starting Payload...
[15:05:14] INFO (payload): Payload Dev Server Initialized
Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)        
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'install' ]
}
[nodemon] app crashed - waiting for file changes before starting...

```

### To Reproduce

clone repo, try to test live-preview with directions from CONTRIBUTING.md, run command and see error below

### Payload Version

latest

### Adapters and Plugins

db-postgres

**Comment by PatrikKozak** [comment]
Hey @devhik0 - I am able to get this running without issues. Do you have `yarn` installed on your system? 

The error seems to indicate that the system cannot find the file specified. In this case, it's trying to spawn a process with `yarn` but can't find it.

If this is the case, I will go ahead and update the `CONTRIBUTING.md` file to mention this.

**Comment by devhik0** [comment]
Yes, i have yarn installed. I can use it at other  apps properly. So I don't think adding yarn to contributing guide can solve this problem.

**Comment by DanRibbens** [comment]
I do think this is a windows compatibility issue, I'm also on Windows, but I haven't looked too deep at how to rework the spawn child process command. You may consider running using WSL. In my case I let live-preview tests get to CI.

**Comment by devhik0** [comment]
Something fun happened 😄  While i was looking a solution to this issue, i tried running another test folder, then i realized why i was trying to run live-preview. Next i checked the issue i was saved to fix, then while looking i fixed the issue via editing code 😃 
Now i ll push a PR about that to close that issue: Closes #4603 (hope). I m feeling different now !

**Comment by PatrikKozak** [comment]
@devhik0 Appreciate you taking the time to work on #4603 but the `display: none` style is actually an intended style. 

I converted the issue to a discussion [here](https://github.com/payloadcms/payload/discussions/4652) as there will need to be some design updates needed if we are to allow for tooltips to show in mobile views.

**Comment by devhik0** [comment]
Okay then, i will be following updates to see what will happen next.

**Comment by devhik0** [comment]
So, i fixed the problem via adding `yarn` to `$PATH`. Now everything working as expected.

**Comment by PatrikKozak** [comment]
@devhik0 That is great! Nice work!
