### ISSUE TITLE
Array gets duplicated when updating a document of another locale through api

### ISSUE THREAD

**Issue by syarkhan** [payloadcms/payload#4649]
### Describe the Bug

When updating a document of another locale through api, array gets duplicated from default locale to other locale if no array items are present.

I was using 2.1.1 version and upgraded to 2.5.0 but the issue is there.

My structure is like this:

![image](https://github.com/payloadcms/payload/assets/19317415/3be90948-3891-40c4-ba00-9d660979f777)

### To Reproduce

1. Create a document of "en" locale with array field and add some items into it
2. Update document via API of another locale such as "en-GB"
3. The updated document with "en-GB" locale gets the same array values as the "en" version.

### Payload Version

2.5.0

### Adapters and Plugins

db-mongodb

**Comment by paulpopus** [comment]
Hi @syarkhan, I wasn't able to reproduce this. Are you able to provide a reproducible repo example?

**Comment by AlessioGr** [comment]
Closing this, as no reproduction repo was provided. If this is still an issue on the **latest** version of payload, please open up a **new** issue with a reproduction repo, following our [reproduction guide](https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md).
