### ISSUE TITLE
Large `upload` collections unusable due to indexing issues

### ISSUE THREAD

**Issue by ssyberg** [payloadcms/payload#4651]
### Describe the Bug

We have an `images` collection with 520,000 records and there appears to be some sort of mismatch between the automatic indexes created and the way queries are being executed against this collection. It does look like Payload is automatically creating indexes for each `imageSize` we've specified:
<img width="271" alt="image" src="https://github.com/payloadcms/payload/assets/1661046/a16b18b5-126a-42a8-8796-70fff524185e">

But it does not look like these indexes are being used at all, every query on this collection examines all 520k records (and hence our ratio is 520,000:1)

Here's one of the offending queries:
```
{
  "type": "command",
  "ns": "project.images",
  "command": {
    "aggregate": "images",
    "pipeline": [
      {
        "$match": {
          "$and": [
            {
              "$or": [
                {
                  "filename": {
                    "$eq": "GettyImages-491433011.jpg"
                  }
                },
                {
                  "sizes.metaLarger.filename": {
                    "$eq": "GettyImages-491433011.jpg"
                  }
                },
                {
                  "sizes.metaSmaller.filename": {
                    "$eq": "GettyImages-491433011.jpg"
                  }
                },
                {
                  "sizes.hero.filename": {
                    "$eq": "GettyImages-491433011.jpg"
                  }
                },
                {
                  "sizes.large.filename": {
                    "$eq": "GettyImages-491433011.jpg"
                  }
                }
              ]
            }
          ]
        }
      },
      {
        "$group": {
          "_id": 1,
          "n": {
            "$sum": 1
          }
        }
      }
    ],
    "hint": {
      "_id": 1
    },
    "cursor": {},
    "$clusterTime": {
      "clusterTime": {
        "$timestamp": {
          "t": 1704210226,
          "i": 11
        }
      }
    },
    "$db": "project"
  },
  "planSummary": "IXSCAN { _id: 1 }",
  "keysExamined": 520981,
  "docsExamined": 520981,
  "cursorExhausted": true,
  "numYields": 567,
  "nreturned": 1,
  "queryHash": "C7173361",
  "queryFramework": "classic",
  "reslen": 253,
  "locks": {
    "FeatureCompatibilityVersion": {
      "acquireCount": {
        "r": 569
      }
    },
    "Global": {
      "acquireCount": {
        "r": 569
      }
    },
    "Mutex": {
      "acquireCount": {
        "r": 2
      }
    }
  },
  "readConcern": {
    "level": "local",
    "provenance": "implicitDefault"
  },
  "writeConcern": {
    "w": "majority",
    "wtimeout": 0,
    "provenance": "implicitDefault"
  },
  "storage": {},
  "protocol": "op_msg",
  "durationMillis": 10871,
  "v": "6.0.12"
}
```

### To Reproduce

n/a

### Payload Version

2.1.0

### Adapters and Plugins

db-mongodb, plugin-cloud-storage

**Comment by ssyberg** [comment]
I'm wondering if the auto hint here is getting in the way?

**Comment by DanRibbens** [comment]
> "durationMillis": 10871

Wow! This is not ideal. You might be right about the isssue being the "hint": _id.

Could you run the same query after setting `disableIndexHints: true` in the mongoose adapter?

**Comment by ssyberg** [comment]
> Could you run the same query after setting disableIndexHints: true in the mongoose adapter?

That was going to be my next step :)

**Comment by DanRibbens** [comment]
We can add some conditionality to the useage of hints when querying on indexed fields or something, but first I want to see if this is the fix.

**Comment by ssyberg** [comment]
@DanRibbens @AlessioGr that worked, though wondering if this will have a negative effect on performance elsewhere. Would it be possible to just update the hint for `upload` collections to include the fields used in that aggregate?

**Comment by DanRibbens** [comment]
A very quick fix would be to conditionally use hint only when there aren't any query params incoming. I think that is what we should do. It could be impacting other usage of indexes based on what you have determined from your testing.

**Comment by ssyberg** [comment]
@DanRibbens unfortunately we're still seeing this behavior on our images after upgrading to the latest payload and removing `disableIndexHints: true` from our config. Any ideas?

**Comment by ssyberg** [comment]
This may have even gotten worse, our max response time is now reflecting 2.85 minutes on the images collection:
![image](https://github.com/payloadcms/payload/assets/1661046/47b3633d-7576-4497-800e-8b968ac63783)

**Comment by DanRibbens** [comment]
Has the plan summary changed with the update?

It was "planSummary": "IXSCAN { _id: 1 }", I want to see it using those indexes.

Clearly we have more work to do. I wonder what results you get if you disable transactions by using: transactionOptions: false in your db adapter config.

**Comment by ssyberg** [comment]
>  transactionOptions: false

We already have this set to false in the above (we've had it off since #4350)

**Comment by DanRibbens** [comment]
Can you try changing your transactionOptions to have a read concern of "available". https://www.mongodb.com/docs/manual/reference/read-concern/

Your explanation from earlier said "local" which might not be practical given the document count. I'm still working through this myself so I appreciate your patience!

**Comment by ssyberg** [comment]
I'll give it a go and report back!

**Comment by ssyberg** [comment]
@DanRibbens can we reopen this?

**Comment by DanRibbens** [comment]
Sorry to have given you bad info on the readConcern. It seems that "majority" would be the best choice for speed + consistency within a transcation. "snapshot" may give better performance, but reading the docs it is unclear to me if that will be compatible with our operations or not so more testing is needed here.

I'll reopen while we figure this out.

**Comment by DanRibbens** [comment]
I shouldn't have suggested the readConcern change at all consider you have also tested with `transactionOptions: false`. Let me do some more research on this. I don't know why MongoDB wouldn't be using the proper index considering we made the change to remove the hint dynamically.

It is feeling like a lower level issue with the database driver. We are on an outdated version at the moment.

**Comment by ssyberg** [comment]
thanks!

**Comment by ssyberg** [comment]
@DanRibbens just checking in on this / seeing if you have any thoughts for a temporary workaround? We've got a big launch coming up next week and we're feeling pretty nervous this is going to take down the site...

**Comment by DanRibbens** [comment]
I appreciate the nudge! I'll set time aside this afternoon to reproduce this.

**Comment by DanRibbens** [comment]
I found the origin of the query you reported being slow and opened a PR that I'm hopeful will improve it. 

Do you know if there were other slow queries @ssyberg?

**Comment by ssyberg** [comment]
This is the only one I noticed so far, but this was blocking from my performance testing so I'll report back once this is live!

**Comment by BrianJM** [comment]
@ssyberg Are you still having this issue?

**Comment by ssyberg** [comment]
@BrianJM I'm still getting a bunch of alerts from Mongo Atlas but this particular ticket can be closed I think!
