### ISSUE TITLE
Hooks: Inconsistencies in args naming, wrong types and docs

### ISSUE THREAD

**Issue by chladog** [payloadcms/payload#468]
# Bug Report

This includes hooks of Collections and well as Globals.

1. Inconsistent naming - sometimes original document data is named ```doc``` sometimes ```data```, also for hooks that pass the previous data this can be quite confusing as we have ```data``` and  ```originalDoc```, ad [beforechange](https://payloadcms.com/docs/hooks/collections#beforechange)
2. Wrong types IDE on type ```CollectionAfterChangeHook``` expects ```doc```, in reality ```doc === undefined``` and data are in ```data```. Probably same problem with other hooks as well.
3. Wrong documentation - same as above point just in the docs, [afterChange](https://payloadcms.com/docs/hooks/collections#afterchange) snippet says ```doc, // full document data```.

## Expected Behavior

1. Consistent naming across all hooks would be more predictable, either one works, though IMHO ```data``` + ```originalData``` fits better in cases when we have only partial document data, as ```doc``` can evoke a full document.
2. Types should strictly reflect existing values. All hooks should be checked.

[0.14.28-beta.0](https://www.npmjs.com/package/payload/v/0.14.28-beta.0)

**Comment by chladog** [comment]
Also afterChange hook is not documented enough regarding what return value should be and what should be the effect.
Currently if I use afteChange hook like documented (just with actual "data" argument) I get an error:
```JS
const afterChangeHook = async ({
  data
}) => {
  return data;
}
```
```
Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'slug' closes the circle
```
When I don't ```return data;```   ( ```(data) => void``` ) everything works fine

**Comment by denolfe** [comment]
Hey @chladog, thanks for the write-up. I agree that there could be some improvements as far as naming and consistency of the hooks and associated types.

I'll take a deeper look into this and evaluate what can be done in the short-term vs. long-term.

**Comment by denolfe** [comment]
After digging into this, the properties within each hook argument were named in a specific way because of where the hook is at in the lifecycle.

For instance, on hooks which deal with updating data that occur before it hits the database - `data` stands for the incoming data, and `originalDoc` is the original. This would be for `beforeValidate` and `beforeChange` hooks.

Once the data is coming back from the database or is a read operation - `doc` stands for the full document coming back from the database.

Does that add any clarity to the property names?

Regarding your specific example, `data` is not a property passed into the args of an afterChange hook. Here is an example using the TS type that would _error_ with your example code:

```ts
import { CollectionAfterChangeHook } from 'payload/types';
const afterChangeHook: CollectionAfterChangeHook = async ({ data }) => { // Error: Property 'data' does not exist on type
  return data;
}
```

I'm taking a few things away from this investigation:

- In the documentation, we should better document the return types as well as note the proper TS type for each
- The properties of the TS hook types should all have proper comments on each property to better explain what each is

How does that sound?

**Comment by chladog** [comment]
If there's a clear practice when there is ```data``` and where there is ```doc``` it might be lil confusing though if everything is typed correctly it would work.
However the core problem here is the actual types and docs don't reflect properties in runtime:

On my collection:
```JS
hooks: {
  afterChange: [
    ({ data, doc }) => {     // <= if typed "CollectionAfterChangeHook" then as you say 'data does not exist on type'
      console.log(data);
      console.log(doc);
    },
  ];
}
```
However if we don't type the hook, or ignore TS error in runtime this gets logged:
```JS
{
  slug: 'xxxx',
  id: '62219888939e3b354d305e70',
  createdAt: '2022-03-04T04:41:44.392Z',
  updatedAt: '2022-03-04T04:41:44.392Z'
}
undefined
```
So the data are actually in ```data``` property which at the same time doesn't exist on type.
```doc === undefined``` where it should hold the data (doc).

This behaves same for both ```create``` and ```update``` operations.

**Comment by denolfe** [comment]
Hmm, this is not the behavior I'm seeing locally. I pasted in your hook, but my log is reflecting exactly what is in the documentation (flipped of yours) 🤔 

```
undefined
{
  slug: 'new',
  id: '62219dd6a719f115482289ac',
  createdAt: '2022-03-04T05:04:22.925Z',
  updatedAt: '2022-03-04T05:04:22.925Z'
}
```

Not sure if something else is at play. Could you paste your entire collection definition or make a small repo recreating this that I can clone down?

**Comment by chladog** [comment]
Aah I got it, what an uttery blind idiot I'm. 
So sorry.
I actually added hook to a ```field``` by mistake as I had one hook on the field already and my config object is quite big.

So I actually had
```JS
  fields: [
    {
      name: 'slug',
      type: 'text',
      localized: true,
      hooks: {
        beforeValidate: [(args) => makeSlug(args?.value || args?.data?.title || args?.originalDoc?.title || '')],
        afterChange: [flushSlugHook("/")],
      }
    },
```
where I should have:
```JS
  hooks: {
    afterChange: [flushSlugHook("/")],
  },
  fields: [
    {
      name: 'slug',
      type: 'text',
      localized: true,
      hooks: {
        beforeValidate: [(args) => makeSlug(args?.value || args?.data?.title || args?.originalDoc?.title || '')]
      }
    },
```

Though IDE nor compiler complained about this, even when hook was typed ```CollectionAfterChangeHook```, so maybe that would be a point for improvement to make Collection hook types incompatible with FieldHooks to prevent same mistakes.
