### ISSUE TITLE
Can't create a user

### ISSUE THREAD

**Issue by ToTheMoonAndDown** [payloadcms/payload#4683]
### Describe the Bug

I have created a payload app using npx create-payload-app@latest, added my db link and runed the app, when I go to localhost3000/admin I get directed to login page where I can't log in , I don't get introduce to create user page

### To Reproduce

run npx create-payload-app@latest
npm run dev

### Payload Version

2.0.0

**Comment by DasMergo** [comment]
you have to clear your database tables if using mongodb you need mongodb-compass to connect to your db and delete the user rows in users tables
![dqa](https://github.com/payloadcms/payload/assets/9856309/2e27abd8-cb82-4bb5-a49e-c769a12677cb)

**Comment by paulpopus** [comment]
Hey @ToTheMoonAndDown as mentioned above, if you already have an existing user in the database then you will not be prompted to create a new one.

If you're using mongodb, the last name in your connection string is the database, so you can change that and run your instance against a new database in the same mongodb instance.

**Comment by ToTheMoonAndDown** [comment]
@paulpopus  Thank you for the help , really appreciated!

**Comment by paulpopus** [comment]
No worries mate, join us on our discord as well if you haven't https://discord.com/invite/r6sCXqVk3v

There's an active community-help channel if you need further help!
