### ISSUE TITLE
When creating/editing a reference document via its 'parent' document, attempting to edit a radio button field on the 'child' document will change the value on the 'parent' document instead, if they both share a radio field with the same field name

### ISSUE THREAD

**Issue by ChristianMay21** [payloadcms/payload#4691]
### Link to reproduction

https://github.com/ChristianMay21/payload-radio-field-reproduction

### Describe the Bug

Please see a video demonstration of the bug using the provided reproduction here: 
https://streamable.com/8wmmzn

Please note that this video expires in 2 days - please let me know if it is still needed after these 2 days, and I will be happy to reupload it.

Let's say you have:
- Two collections - 'Collection 1' and 'Collection 2'
- Both collections have a radio field using the same name and values - we'll call this the 'shared radio field'
- Collection 1 contains a reference field to Collection 2

If you open a document in Collection 1, and there edit or create a document in Collection 2 using the reference field, attempting to edit the 'shared radio field' on the Collection 2 document will instead edit the value for the shared field on the 'parent' Collection 1 document.

## How do I reproduce it?
1. Clone the reproduction repo
2. Open root folder in terminal
3. Run `yarn install`
4. Run `yarn run dev`
5. Open admin backend at https://locahost:3000
6. Create a user and log in
7. Open Collection_1s
8. Click 'Create new Collection_1'
9. On the 'Related_collection_2' field, click the '+' button to create a related document in Collection_2
10. Attempt to edit Radio_field_2 - notice that this is successful
11. Attempt to edit Radio_field_1 - notice that this is unsuccessful, and the radio button UI does not update
12. Press the 'X' in the top right to dismiss the screen to create the Collection_2 document
13. Notice that Radio_field_1 on Collection 1 now has its value set to the value you selected for the Collection_2 document

Please note that this bug also occurs in arrays of references, and also occurs when editing existing references - not just creating new ones.

### Payload Version

2.6.0

### Adapters and Plugins

Default with the 'blank' payload template

**Comment by ChristianMay21** [comment]
Possibly related to https://github.com/payloadcms/payload/issues/3911

**Comment by ChristianMay21** [comment]
@AlessioGr seeing a lot of PR's regarding related functionality from you, so just letting you know about this one in case it's of any interest

**Comment by jmikrut** [comment]
My thought is that we may need to prefix the path used for radios / checkboxes / etc with the edit depth. 

What do you think, @AlessioGr? I can also reassign this to either @PatrikKozak or @JessChowdhury because I know you have your hands full at the moment.

**Comment by ChristianMay21** [comment]
If it helps at all in figuring out time-sensitivity, I'd say that this bug wasn't too bad for my developer experience.

It did take me a bit to figure out the nature of the bug, but not _too_ long.

And there's a more-tedious but simple-enough workaround of just editing the child collection's document directly, then popping back in to the parent document and selecting it as a reference.

**Comment by AlessioGr** [comment]
Should be fixed in the latest v3 beta release of richtext-lexical. If something like this happens again, please open a new issue and we'll fix ASAP!
