### ISSUE TITLE
scss overriding does not work

### ISSUE THREAD

**Issue by gtolarc** [payloadcms/payload#47]
https://github.com/payloadcms/payload/blob/master/src/admin/scss/vars.scss

I think !default should be added to all of the above variables. Like this,
```scss
$baseline-px         : 25px !default;
```

**Comment by DanRibbens** [comment]
Hey @gtolarc, good suggestion! I'll work that in soon.

**Comment by DanRibbens** [comment]
Released in v0.2.10.
