### ISSUE TITLE
Duplicate fields in API response when using group fields within an an array field

### ISSUE THREAD

**Issue by jayelg** [payloadcms/payload#4709]
### Describe the Bug

When using group fields within an array field eg.
```
import type { CollectionConfig } from 'payload/types'

export const Pages: CollectionConfig = {
  slug: 'pages',
  fields: [
    {
        name: 'layout',
        label: 'Layout',
        type: 'array',
        fields: [
            {
                name: 'group1',
                type: 'group',
                fields: [
                    {
                        name: 'text1',
                        type: 'text',
                    },
                    {
                        name: 'text2',
                        type: 'text',
                    },
                ],
            },
            {
                name: 'group2',
                type: 'group',
                fields: [
                    {
                        name: 'text3',
                        type: 'text',
                    },
                    {
                        name: 'text4',
                        type: 'text',
                    },
                ],
            },
        ],
    }
  ],
}
```
The API outputs duplicate data as shown below
```
{
   "id": 1,
   "layout": [
      {
         "_order": 1,
         "id": "6598cd55a22b18e2dc17cb1a",
         "group1_text1": "some text here.",
         "group1_text2": "some more text here.",
         "group2_text3": "even more text.",
         "group2_text4": "and even more text.",
         "group1": {
            "text1": "some text here.",
            "text2": "some more text here."
         },
         "group2": {
            "text3": "even more text.",
            "text4": "and even more text."
         }
      }
   ],
   "updatedAt": "2024-01-06T03:47:33.903Z",
   "createdAt": "2024-01-06T03:47:33.903Z"
}
```
As can be seen above, the data exists both within a group object and is also pulled up into the root of the array item.

### To Reproduce

1. create a blank project using create-payload-app.
2. create a collection containing an array field
3. within the fields array of the array field, add 1 or more group fields.
4. add a dummy field within the group eg. a text field.
5. in the /admin page, create a collection with dummy data and save.
6. observe the api response and note the duplicate fields.

### Payload Version

2.6.0

**Comment by paulpopus** [comment]
Similar issue reported here https://github.com/payloadcms/payload/issues/4649

However I was not able to reproduce this following those exact same steps and the config you shared. Are you able to put this in a reproducible repo for us please? @jayelg 

Until then I'll mark this as 'can't reproduce'

**Comment by jayelg** [comment]
Thanks @paulpopus for looking into it.
Ok, I'm very sorry but I've omitted the critical step - The database used was Postgres. I've just tested both mongo and postgres in a new blank starter project and can only reproduce the issue when running postgres.

Using mongo db:
```
{
    "id": "659c95875bec076815840184",
    "layout": [
        {
            "group1": {
                "text1": "hello",
                "text2": "there"
            },
            "group2": {
                "text3": "how ",
                "text4": "are"
            },
            "id": "659c9587964afa6e20fb9aa9"
        }
    ],
    "createdAt": "2024-01-09T00:38:31.942Z",
    "updatedAt": "2024-01-09T00:38:31.942Z"
}
```
using postgresdb:
```
{
    "id": 2,
    "layout": [
        {
            "_order": 1,
            "id": "659c97a70726e9e5294e5cf5",
            "group1_text1": "hello",
            "group1_text2": "there",
            "group2_text3": "how",
            "group2_text4": "are",
            "group1": {
                "text1": "hello",
                "text2": "there"
            },
            "group2": {
                "text3": "how",
                "text4": "are"
            }
        }
    ],
    "updatedAt": "2024-01-09T00:47:35.243Z",
    "createdAt": "2024-01-09T00:47:35.243Z"
}
```

(I was hoping to recreate the issue per the reproduction repo instructions however I hit a wall when running `pnpm dev _community` which errorred with `Error: cannot connect to MongoDB. Details: connect ECONNREFUSED 127.0.0.1:27017`. I assumed it is suppose to be using the mongo memory server so not sure why this is the case for me.)

**Comment by paulpopus** [comment]
Thanks @jayelg reproduced it!
