### ISSUE TITLE
No note in plugin-cloud-storage repo that it moved to this monorepo

### ISSUE THREAD

**Issue by devj3ns** [payloadcms/payload#4717]
The separate repository for [plugin-cloud-storage](https://github.com/payloadcms/plugin-cloud-storage) does not contain any hint that the code [moved to this monorepo](https://github.com/payloadcms/payload/pull/3847).

There are still people opening issues over there.

**Comment by paulpopus** [comment]
Thanks for bringing this to our attention! We've just moved over all the issues and archived that repo.
