### ISSUE TITLE
Collapsible and Row field cannot be localized

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#4720]
### Describe the Bug

```ts
{
  type: 'collapsible',
  fields: [
    {
      name: 'collapsibleFieldText',
      type: 'text',
    },
  ],
  label: 'Collapsible Field',
  localized: true,
},
```
    
This is not localized. Happens for both Collapsible and Row fields.

If this is intentional, there should be a typescript error when using the localized property for those fields - similar to unnamed tab fields.

### Payload Version

2.6.0

**Comment by jmikrut** [comment]
Should **_not_** be able to localize collapsible fields, but I believe group fields do work as localized. Right?

**Comment by AlessioGr** [comment]
Whoops I meant row fields, not groups fields. Corrected it
