### ISSUE TITLE
@payloadcms/plugin-seo 1.1.0 is missing dist/index.js 

### ISSUE THREAD

**Issue by wiesson** [payloadcms/payload#4751]
### Describe the Bug

I have updated to the latest version of the plugin (1.10) and the `dist/index.js` file is missing in the package. 

### To Reproduce

Could be checked on NPM

https://www.npmjs.com/package/@payloadcms/plugin-seo?activeTab=code -> dist - index.js is not present

### Payload Version

2.7

### Adapters and Plugins

plugin-seo

**Comment by rmartis** [comment]
The same after update 2.6.0 -> 2.7.0

**Comment by justinburrow** [comment]
Same issue, on a fresh create-payload-app using Postgres.

- npx create-payload-app@latest
- cd payload-blog
- yarn && yarn dev

Error: [nodemon] starting `ts-node src/server.ts -- -I`
unhandledRejection Error: Cannot find module '/Users/xxx/Sites/payload-blog/node_modules/@payloadcms/plugin-seo/dist/index.js'. Please verify that the package.json has a valid "main" entry

**Comment by denolfe** [comment]
We ended up unpublishing 1.1.0 of this package. There was a miscommunication on its readiness to be released from the monorepo. Normally, we'd fix forward on this type of thing, but there were also some issues with Payoad v1 support in this version.
