### ISSUE TITLE
Zero-byte uploads with `useTempFiles`

### ISSUE THREAD

**Issue by reiv** [payloadcms/payload#4783]
### Describe the Bug

When the `upload.useTempFiles` option is enabled, uploading any *non-image* file results in a zero-byte file in the local uploads folder.

I'm wondering if this is some kind of regression or if we're just not using it the intended way. Seeing as it was mentioned a few times on Discord I assume that this is a feature that Payload supports (albeit undocumented).

We need `useTempFiles` because buffering into memory with large uploads frequently causes us to run out of RAM.

### To Reproduce

- Start with a blank Payload project (`yarn create payload-app`)
- Create an upload-enabled collection
- Set `upload.useTempFiles = true` in `payload.config.ts`:

```ts
// imports omitted for brevity

export default buildConfig({
  admin: {
    user: Users.slug,
    bundler: webpackBundler(),
  },
  // added
  upload: {
    useTempFiles: true,
  },
  editor: slateEditor({}),
  collections: [Users, {
    // added
    slug: 'media',
    upload: true,
    fields: []
  }],
  typescript: {
    outputFile: path.resolve(__dirname, 'payload-types.ts'),
  },
  graphQL: {
    schemaOutputFile: path.resolve(__dirname, 'generated-schema.graphql'),
  },
  plugins: [payloadCloud()],
  db: mongooseAdapter({
    url: process.env.DATABASE_URI,
  }),
})
```

### Payload Version

2.7.0

**Comment by iorobertob** [comment]
+1 , experiencing this, following
