### ISSUE TITLE
A `.` (Period) in `id` will cause Admin 404

### ISSUE THREAD

**Issue by nathanclevenger** [payloadcms/payload#4812]
### Describe the Bug

If a document's `id` has a period in it ... for example `driv.ly` or `auto.dev` as a domain name, then refreshing that detail view, or navigating directly to it results in a 404.  I suspect it has something to do with the way the express router path is configured.

### To Reproduce

In a collection where `id` can be user specified, create a new document with `.` in the `id` ... then when viewing

### Payload Version

2.8.1

**Comment by JarrodMFlesch** [comment]
@nathanclevenger as of right now we are not going to dive into this. Obviously there are issues with having periods in the URL.

I would recommend not creating ID's that have periods. If you want to attempt to fix this then we can review a PR!
