### ISSUE TITLE
nested-docs: duplicate collection entry with digitalocean mongodb server

### ISSUE THREAD

**Issue by RickGeersing** [payloadcms/payload#4814]
### Describe the Bug

I have a collection called `pages` which `nested-docs` is enabled on. Whenever I create a new page (for example: `test1`), it shows up as a duplicate on the overview. And if I select one of them, both get selected. 
![Screenshot 2024-01-15 at 11 22 08](https://github.com/payloadcms/payload/assets/22543128/128a33cc-d6e1-47a3-aee9-3270e31ee2c8) But when I checkout te collection with a program such as mongodb compass, I only see one entry for `test1`
![image](https://github.com/payloadcms/payload/assets/22543128/8832d16d-b3a9-42f7-88b6-253d4a597bac)

This seems to only occur when I use the digitalocean mongodb server. When using a local instance of mongodb ( node wired tiger / docker mongo v6) it seems to work fine. Which is weird.

On further inspection `resaveSelfAfterCreate(collection)` afterChange hook seems to cause the issue. 

### To Reproduce

1. Have a mongodb instance running on digitalocean
2. Create a `pages` collection with some fields (for ex. title, description)
3. Include the collection in nested docs
4. Create new page
5. Go to the overview, It shows two entries for the same page

### Payload Version

2.8.1

### Adapters and Plugins

db-mongodb: 1.3.1, 
bundler-vite: 0.1.6, 
plugin-nested-docs: 1.0.11, 
plugin-cloud-storage: 1.1.1,
plugin-search: 1.0.1,
plugin-seo: 1.0.15

Digitalocean MongoDB server running on version 6
Node version: 18.19.0

**Comment by DanRibbens** [comment]
Do you have versions enabled @RickGeersing? A reproduction or just sharing your config will help us diagnose and fix the issue more quickly.

Thanks!
