### ISSUE TITLE
plugin-cloud-storage: Large number of Request Units in Cosmos DB during index creation

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#4836]
It was reported that the plugin is making a large number of requests initially to Cosmos DB. This could present provisioning challenges. Current workaround is to use serverless Cosmos DB.

[Source Discord Thread. Author: @moonfabian](https://discord.com/channels/967097582721572934/1049302738858676274/1049302738858676274)

> We want to deploy a payload instance with azure - but when registering or just saving a post - we're always reaching the RU limit for some reason

> Error message: 
Response status code does not indicate success: BadRequest (400); Substatus: 1028; ActivityId: ; Reason: (Message: {"Errors":["Your account is currently configured with a total throughput limit of 1600 RU\/s. This operation failed because it would have increased the total throughput to 2000 RU\/

> i actually switched to serverless cosmosdb - and now everything works pretty nice - i'll also post some screenshots - but it seems, that while creating the indexes - it got up to 2400 RUs - for a short time. - this would mean setting up cosmosdb for 2400RUs - about 200€/month & the problem is - that with cosmosdb - you cannot downsize the instance anymore.

> Maybe adding a notice to the docs would be good - or maybe in the future even optimising the setup

**Comment by thijssmudde** [comment]
Any progress on this? The workaround for going serverless with CosmosDB is not really a good idea for my situation.

**Comment by thijssmudde** [comment]
Is it that the combination of plugin-cloud-storage and Cosmos DB are leading to an immense number of RU?
