### ISSUE TITLE
plugin-cloud-storage: Avoiding Vercels upload limit by using PresignedUrls

### ISSUE THREAD

**Issue by Utzel-Butzel** [payloadcms/payload#4842]
When using https://github.com/payloadcms/next-payload each upload runs into the 4.5 MB limit on Vercel deployments (https://vercel.com/guides/how-to-bypass-vercel-body-size-limit-serverless-functions). Is there a way available to directly upload files to the cloud provider using signed urls or would you like a PR? If so do you think it is possible to build this with the current payload plugin system?

**Comment by denolfe** [comment]
Next-payload is being deprecated in favor of Payload 3.0, which will have optimized function sizes. Feel free to create a new issue if you see something like this when 3.0 is released.
