### ISSUE TITLE
plugin-cloud-storage: disablePayloadAccessControl not working for Preview Sizes

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#4846]
When `disablePayloadAccessControl` set to `true`, it correctly uses the bucket's (google cloud in my case) original url on the image list etc, but NOT on the modal/panel that opens when clicking the 'preview sizes' button. Please checkout the screenshot below:

![Screenshot 2023-11-25 at 11 26 29](https://github.com/payloadcms/plugin-cloud-storage/assets/52583398/a8bbc540-1fa5-4871-b152-866e05a85180)

**Comment by truumahn** [comment]
Same here, [the documentation](https://payloadcms.com/docs/upload/storage-adapters#payload-access-control) states:

> If this does not apply to you (your upload collection has read: () => true or similar) you can disable this functionality by setting disablePayloadAccessControl to true. When this setting is in place, this plugin will update your file URLs to point directly to your cloud host.

Instead of the cloud storage links, the location based on the staticdir configuration is returned.

**Comment by truumahn** [comment]
This issue still exists in Payload 3.
