### ISSUE TITLE
plugin-cloud-storage: Images not found on payload URL

### ISSUE THREAD

**Issue by silveltman** [payloadcms/payload#4847]
My images are uploaded correctly to Google Cloud, but the URL payload gives me return a 404. Tried all sorts of paths, not nothing to be found. 

Is there any wat to debug this? I would like to know if I am for some reason looking at the wrong path OR that something goes wrong with the connection with Google cloud. 

Temporary solution: `disablePayloadAccessControl: true`

**Comment by denolfe** [comment]
If you can provide some reproduction steps, we can look into this further.

I would expect you to be able to inspect the document in the DB which may indicate where it is looking for the file. You can then troubleshoot by cross-referencing this with where the file was actually stored in GCS.
