### ISSUE TITLE
plugin-cloud-storage: npm commands missing from readme

### ISSUE THREAD

**Issue by ChristianMay21** [payloadcms/payload#4848]
Hi - this isn't super-important, but i noticed that - there are a couple places in the Readme where the yarn command for adding dependencies is written inline, and the equivalent npm command is not. Most payload documentation I've seen provides both.

**Comment by denolfe** [comment]
I think at this point, most devs should have exposure to npm, yarn, and pnpm to be able to get the gist of what is going on.

PRs are always welcome to improve documentation, though, if you're up to it.
