### ISSUE TITLE
plugin-cloud-storage: Document where to find Access key, key id, etc. in AWS

### ISSUE THREAD

**Issue by ChristianMay21** [payloadcms/payload#4849]
Hi - I am trying to set up image storage in S3 after the official payload cloud storage had a lot of weird behavior.

In the README here, it appears that I'm meant to retrieve several pieces of information from my S3 bucket and set them as environment variables.

It is not immediately clear to me where I should be able to find that information - some information, such as the bucket region, can be easily located, but it's not immediately clear to me what in AWS S3 terminology "access key" and other terms mean - I've spent a good bit of time googling/consulting AI tools in case they have the answer, and I've unfortunately come up short.

**Comment by denolfe** [comment]
Some knowledge of S3 is assumed when configuring and using this plugin with the S3 adapter.

Additional documentation on this can be found [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/security-creds.html).
