### ISSUE TITLE
draftMode() expects to have requestAsyncStorage, none available.

### ISSUE THREAD

**Issue by denisorehovsky** [payloadcms/payload#4856]
### Describe the Bug

When I run `npm run dev` and then open `localhost:3000`, everything works perfectly. However, when I run debug mode from VSCode, I encounter this issue:
![image](https://github.com/payloadcms/payload/assets/9641784/bd599d97-c507-40f4-80d4-8600c84cfe91)

/admin is working btw.

### To Reproduce

Run the dev server from VSCode and open `localhost:3000`.

### Payload Version

2.8.2

### Adapters and Plugins

db-postgres

**Comment by awndrw** [comment]
What version of Next.js are you on? This issue is probably unrelated to Payload:
https://github.com/nextauthjs/next-auth/issues/6989
https://github.com/vercel/next.js/issues/46356

**Comment by denisorehovsky** [comment]
@awndrw Next is 13.5.2. As for Next-Auth, I don't think I have it installed.

**Comment by paulpopus** [comment]
Closing as it's no longer an issue in v3, let us know if it's a problem that persists with some reproduction
