### ISSUE TITLE
Local API: updating nested fields throws validation error

### ISSUE THREAD

**Issue by Cuzart** [payloadcms/payload#4857]
### Link to reproduction

https://github.com/Cuzart/live-preview-reproduction

### Describe the Bug

When using the local API for updating a collection field with relationships e.g. layout with a Media block in Page collection a ValidationError gets thrown and the update won't take effect. I tested the same for simple text fields like slug or the layout field with a simpler block (no relationship) which worked as expected. I guess there might be a bug in the traversing of relationships. 

The error: `ValidationError: The following field is invalid: layout.0.media at beforeChange`

### To Reproduce

I implemented a afterChange hook on another collection which just reads a collection with slug home and updates the layout data of the same collection (because that was how I discovered this)

from Categories.ts
```tsx
const { docs } = await payload.find({
  collection: 'pages',
  where: { slug: { equals: 'home' } },
  depth: 10,
})

const req = await payload.update({
  id: docs[0].id,
  collection: 'pages',
  data: {
    layout: docs[0].layout,
  },
  depth: 10,
})
```

To reproduce make sure you have a page with slug "home" and a layout block with a relationship in it e.g. Media block with a selected image.
Open the admin panel and go to the categories collection to create a new collection which should trigger the hook. See the ValidationError in the toast notification or logged to the server console.

### Payload Version

2.8.2

### Adapters and Plugins

db-mongodb

**Comment by SimYunSup** [comment]
I think It is not a bug, It has produced because you insert full data about related collection. If you want to insert data about relationship, refer to the documentation below to add your data.
https://payloadcms.com/docs/fields/relationship#how-the-data-is-saved

**Comment by Cuzart** [comment]
Thanks for pointing this out @SimYunSup. It wasn't really clear to me from the local API docs. Setting depth to 0 in the find request solved this issue for me.
