### ISSUE TITLE
Payload Cloud: No DNS Record generated for Custom Domain

### ISSUE THREAD

**Issue by ChristianMay21** [payloadcms/payload#4864]
### Describe the Bug

I am not sure where to report bugs related to Payload Cloud. If this is not the correct place, I apologize - please let me know a better place. In addition to this Github issue, I have also opened a thread on the #community-help channel in the Discord channel. Please find it here: https://discord.com/channels/967097582721572934/1197383086812450896

Now about the bug:
Hi - I am hosting a NextJS/Payload web app on Payload Cloud, based off of the `custom-server` template.

I am finally ready to connect my web app to a custom domain. I am following the directions at https://payloadcms.com/docs/cloud/projects#custom-domains:

```
With Payload Cloud, you can add custom domain names to your project. To do so, first go to the Domains page of the Settings tab of your project. Here you can see your default domain. To add a new domain, type in the domain name you wish to use.

Once you click save, a DNS record will be generated for your domain name to point to your live project. Add this record into your DNS provider’s records, and once the records are resolving properly (this can take 1hr to 48hrs in some cases), your domain will now to point to your live project.
```

After adding my domain name, Payload Cloud does not appear to generate a DNS record - at least not in the first hour or so after clicking it. I just get an empty table (see picture)

I understand that the process for *resolving* the record can take up to 48 hours, but the documentation does not seem to suggest that *generating* the record should entail a significant wait. Please let me know if I am incorrect with this assumption.

If not, this appears to be some sort of bug - could someone from the Payload team please assist? 

My project ID is 655f94cc483c37221dcc066d

### To Reproduce

Please see my live Payload Cloud project with ID 655f94cc483c37221dcc066d to see this bug

### Payload Version

2.5.0

### Adapters and Plugins

db-mongodb, bundler-webpack, payloadCloud

![image](https://github.com/payloadcms/payload/assets/45889402/fe598c4b-1eee-4aa3-8ea0-4a22f820a5dd)

**Comment by damnsamn** [comment]
Have you tried deleting and regenerating it? I set up a custom domain yesterday and it worked okay for me
![image](https://github.com/payloadcms/payload/assets/17864782/b7a83bdc-9126-4331-a8ca-f4e4b781a2a9)

**Comment by ChristianMay21** [comment]
@damnsamn great question! I did but unfortunately it still did not generate.

**Comment by denolfe** [comment]
Resolved over Discord/Email.
