### ISSUE TITLE
Search plugin won't install with Payload v2.

### ISSUE THREAD

**Issue by revnelson** [payloadcms/payload#4867]
### Describe the Bug

When trying to install @payload/plugin-search, dependency errors are thrown:

```
npm i @payloadcms/plugin-search
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: project-name@1.0.0
npm ERR! Found: payload@2.8.1
npm ERR! node_modules/payload
npm ERR!   payload@"2.8.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer payload@"^0.18.5 || ^1.0.0" from @payloadcms/plugin-search@1.0.1
npm ERR! node_modules/@payloadcms/plugin-search
npm ERR!   @payloadcms/plugin-search@"*" from the root project
```

### To Reproduce

Install payload ^2.0.0.

Attempt to install `@payload/plugin-search`.

### Payload Version

2.8.1

### Adapters and Plugins

db-mongodb, bundler-webpack, npm

**Comment by devhik0** [comment]
As a temporary solution you can try this shown here : 
```
Fix the upstream dependency conflict, 
or retry this command with --force or --legacy-peer-deps 
to accept an incorrect (and potentially broken) dependency resolution.
```
Also i checked deps of `@payloadcms/plugin-search` and saw 
```json
"peerDependencies": {
    "payload": "^0.18.5 || ^1.0.0 || ^2.0.0",
``` 
so it should work as is in my opinion. At this point `--force` option for install command will solve issue i think.

**Comment by LasseSiebert-WW** [comment]
Any update on this? This has been an issue for a while now and has not been addressed. 😕

**Comment by denolfe** [comment]
Looks like the source code is good to go, we just need to do a release. Should be released today or Tuesday.

**Comment by LasseSiebert-WW** [comment]
@denolfe That's great news! Thanks for answering.
