### ISSUE TITLE
Misspelling/discrepancies of names of Lexcial features between source and docs

### ISSUE THREAD

**Issue by robbie-hunt** [payloadcms/payload#4883]
### Describe the Bug

Unordered list feature: '"@payloadcms/richtext-lexical"' has no exported member named 'UnorderedListFeature'. Did you mean 'UnoderedListFeature'?

Treeview feature: the docs say "TreeViewFeature" but in the source it's named "TreeviewFeature". Not sure which spelling is the correct one to use, I'm mafia level 1 programmer.

Found these discrepancies while copy-pasting the names of the features from the docs at [https://payloadcms.com/docs/rich-text/lexical#features-overview](url)

### To Reproduce

In `paylod.config.ts`, try to import `UnorderedListFeature` and `TreeViewFeature` from `'@payloadcms/richtext-lexical'` and TS will give you errors highlighting the name discrepancies.

### Payload Version

2.8.2

**Comment by Spreizu** [comment]
If I remember correctly, the `UnoderedListFeature` was fixed quite a long time ago. Are you using the latest version of @payloadcms/richtext-lexical?

**Comment by AlessioGr** [comment]
Closing this, as this has already been fixed in the latest version
