### ISSUE TITLE
Inconsistent Array field validation

### ISSUE THREAD

**Issue by slavanossar** [payloadcms/payload#4886]
### Describe the Bug

When creating an `array` field and specifying `minRows` and/or `required`, behaviour is inconsistent.

1. Document can be saved when no rows are added, when field has `minRows` but no `required`

```ts
{
  name: 'team',
  labels: {
    singular: 'Person',
    plural: 'People',
  },
  type: 'array',
  minRows: 1,
  fields: [
     // ...
  ]
}
```

<img width="819" alt="image" src="https://github.com/payloadcms/payload/assets/7077600/50799db8-5a3e-44c5-a77b-3ae3d7682c6f">

2. Validation text doesn't include `count` value, when field has `required: true` and no `minRows` value

```ts
{
  name: 'team',
  labels: {
    singular: 'Person',
    plural: 'People',
  },
  type: 'array',
  required: true,
  fields: [
     // ...
  ]
}
```

<img width="751" alt="image" src="https://github.com/payloadcms/payload/assets/7077600/9ff80abd-fa11-427d-bcdb-0daad87befb8">

3. Validation text incorrectly uses plural label, when field has `minRows: 1` and `required: true`

```ts
{
  name: 'team',
  labels: {
    singular: 'Person',
    plural: 'People',
  },
  type: 'array',
  minRows: 1,
  required: true,
  fields: [
     // ...
  ]
}
```

<img width="757" alt="image" src="https://github.com/payloadcms/payload/assets/7077600/95c975fb-0d27-46be-93a1-3211fe49b945">

### To Reproduce

See field examples above.

I was reading the source and looking at the usage of `validation:requiresAtLeast`, but not entirely sure how it all works. I did notice that [this ternary expression](https://github.com/payloadcms/payload/blob/d5720bea7b7b58750eac9a39da64f78f608518e9/packages/payload/src/admin/components/forms/field-types/Array/index.tsx#L269) seems to be the wrong way around, and that [this validation](https://github.com/payloadcms/payload/blob/d5720bea7b7b58750eac9a39da64f78f608518e9/packages/payload/src/fields/validations.ts#L201) doesn't account for `minRow` size.

### Payload Version

2.8.2

### Adapters and Plugins

db-mongodb, bundler-webpack

**Comment by JarrodMFlesch** [comment]
@slavanossar The validation messages were incorrect! I have fixed those in https://github.com/payloadcms/payload/pull/6780. As for required/minRows, that is behaving as expected. If you want a field to be required you need to specify the required property.
