### ISSUE TITLE
Postgres: Sorting on localized fields returns wrong count

### ISSUE THREAD

**Issue by Janisvb** [payloadcms/payload#4889]
### Link to reproduction

https://github.com/Janisvb/payload-reproduction/tree/sort-localized

### Describe the Bug

When sorting on localized fields with postgres, the number of docs returned is not correct.

### To Reproduce

```
yarn dev:postgres _community
```

1) Sort by id (correct)
http://localhost:3000/api/posts?locale=en&depth=0&limit=10&sort=id
`{..., totalDocs: 100}`

2) Sort by localized text field
http://localhost:3000/api/posts?locale=en&depth=0&limit=10&sort=text
`{..., totalDocs: 200}`

3) Sort by localized date field
http://localhost:3000/api/posts?locale=en&depth=0&limit=10&sort=date
`{..., totalDocs: 5}` (and only 5 docs returned)

It works as expected with MongoDB.

### Payload Version

2.8.2

### Adapters and Plugins

db-postgres

**Comment by denolfe** [comment]
@Janisvb Another great bug report with recreation 🙌  

This fix will be in the next release.
