### ISSUE TITLE
PUBLIC_PAYLOAD_ environment variables not updated

### ISSUE THREAD

**Issue by sacha-c** [payloadcms/payload#4892]
### Describe the Bug

**Description**
`PUBLIC_PAYLOAD_` environment variables do not work as expected when using the production setup of the application.

I find two similar issues with the same root cause when making use of these environment variables:
1. If there is no environment file when running `yarn build`, my `PUBLIC_PAYLOAD_` variables will not be loaded on the frontend.
2. If change the value of a `PUBLIC_PAYLOAD_` variable, this change is not reflected in my frontend; the old value is still used.

**Analysis**
Digging a bit in the code, I noticed that after running `yarn build`, the build files in `build/main.*js` actually contain the `PAYLOAD_PUBLIC_MY_VARIABLE` in plain text.

Looking a bit further I noticed that the webpack plugin which takes the `PUBLIC_PAYLOAD_` variables [here](https://github.com/payloadcms/payload/blob/main/packages/bundler-webpack/src/configs/base.ts#L67) is only run in the [build stage](https://github.com/payloadcms/payload/blob/main/packages/bundler-webpack/src/scripts/build.ts#L10) and the [dev stage](https://github.com/payloadcms/payload/blob/main/packages/bundler-webpack/src/scripts/dev.ts#L19), but not in the [serve stage](https://github.com/payloadcms/payload/blob/main/packages/bundler-webpack/src/scripts/serve.ts#L12).

This seems to explain why the public payload variables work fine with `yarn dev` & after running `yarn build`, since the plugin is run. However since it is not run on `yarn serve`, then when in production mode it just keeps using what it was initially built with.

**Conclusion**
I'm not quite sure if this is how this was intended to work. In this case I think environment variables should be supplied at runtime, not build time, so they don't end up in build artifacts & they can be changed in subsequent runs.

So I *think* (but not quite sure) that this webpack plugin **should not** be run during the build stage, and **should** be run during the serve stage?

Looking forward to your feedback on this 🙂 

I am adding this issue which is related https://github.com/payloadcms/payload/discussions/3758

### To Reproduce

Here is an [example repository reproducing the issue](https://github.com/sacha-c/payload-public-env-issue-reproduction)

In it I have `PAYLOAD_PUBLIC_MY_VARIABLE` set in my .env file, and I am printing the value in `payload.config.ts`. By printing it there, I can expect it to show up when the server runs it & when the browser runs it as well.

For the happy flow, I perform the following steps:
1. Set `PAYLOAD_PUBLIC_MY_VARIABLE=hello_world` in my env file
2. `yarn build`
3. `yarn serve`
4. See that my server logs show `hello_world`
5. See that my browser console logs show `hello_world`

For the issue, I perform the following:
1. Set `PAYLOAD_PUBLIC_MY_VARIABLE=hello_world` in my env file
2. `yarn build`
1. Change my env file with `PAYLOAD_PUBLIC_MY_VARIABLE=bye_world`
2. `yarn serve`
3. See that my server logs show `bye_world`
4. See that my browser console logs show `hello_world` ⚠️ (?)

I was expecting my browser to also show `bye_world`, but it printed `hello_world`. This is the problem.

### Payload Version

^2.0.0

**Comment by SimYunSup** [comment]
You have to know payload's admin frontend is not SSR(If frontend is static, it is hard to insert variable in your frontend). So if you want to use environment variables without inlining, use [nextjs-template](https://github.com/payloadcms/payload/tree/main/templates/website) and see [this guide](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser).

I think it is not a bug.

**Comment by sacha-c** [comment]
If this is not a bug, then at the very least these details are missing in the documentation.

Also the fact that development & production setups do not behave the same way is quite unexpected, I would consider this part a bug.

With regards to the difficulty of inserting variables in the frontend, the environment is available when running `yarn serve`, so while it does require custom code to replace the `PUBLIC_PAYLOAD_` variables where necessary in the static files, it does sound possible to me, isn't it? (I'm not familiar with this setup, so please do correct me if I am wrong)

**Comment by SimYunSup** [comment]
> If this is not a bug, then at the very least these details are missing in the documentation.

I partially understand the lack of documentation. But I don't know if it needs to be explained in detail in the Payload documentation.

> Also the fact that development & production setups do not behave the same way is quite unexpected, I would consider this part a bug.

I don't think it's a bug just because the dev and production environments are different, just like you wouldn't call it a bug if you were developing with Vite in a SPA environment and it watches the env file, but doesn't watch the env file after the build.

Finally, the nextjs documentation says that Runtime Environment Variables are inlined in the env file that is passed to the frontend. This isn't problem that simply adding a webpack plugin to the serve function, and payload is not even running webpack in the serve function. It is possible to add runtime variables, but It is hard.

**Comment by sacha-c** [comment]
Understood, thanks for your feedback & additional details.

I may try to move to the next-js template in order to use runtime env vars and get this functionality.
