### ISSUE TITLE
Wrong Locale DateTime format

### ISSUE THREAD

**Issue by mat-twg** [payloadcms/payload#4915]
### Describe the Bug

Wrong locale format on dates, example on `ru`

![image](https://github.com/payloadcms/payload/assets/64251479/2e4b4e1e-2864-45ce-aa7c-f4183aa021fc)

![image](https://github.com/payloadcms/payload/assets/64251479/b49f886a-08fe-4440-bc47-6b99e6a74f29)

expected defaults:

![image](https://github.com/payloadcms/payload/assets/64251479/c095f467-d143-459e-be0f-d635acfaaa52)

or with options:

![image](https://github.com/payloadcms/payload/assets/64251479/3fe38e67-3c0b-4d79-822b-b1ca63373180)

**but not**:
```
января 12-е 2024, 6:28 ДП
```

see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl

### To Reproduce

change language in profile settings

### Payload Version

2.8.2

**Comment by SimYunSup** [comment]
Payload is using `date-fns` for date formatting, and you can change formatting display value.

https://github.com/payloadcms/payload/blob/b40e9f85a299789dfb35016f4ab4f6a9e97698b6/packages/payload/src/config/defaults.ts#L11

This is default dateFormat. Edit `admin.dateFormat` in `payload.config.ts`.

[format document](https://date-fns.org/v3.3.1/docs/format)

**Comment by mat-twg** [comment]
Thank you for reply!
So i can not use format, based on Locale in payload? I think it's no friendly... and unnecessary dependence...
