### ISSUE TITLE
Wrong placeholder on related search

### ISSUE THREAD

**Issue by mat-twg** [payloadcms/payload#4916]
### Describe the Bug

Wrong placeholder on related search

![image](https://github.com/payloadcms/payload/assets/64251479/7b3e2033-6b0d-4922-a92f-5fc82d6f4c94)

![image](https://github.com/payloadcms/payload/assets/64251479/1c97e480-54c8-418f-9de8-54a9936ebd8b)

Expected placeholder:

> Serach by  `Name`, `Type` Or `File Name`

### To Reproduce

Create two collections  and run:

```js
export const DocumentsTypes: CollectionConfig = {
  slug: 'documents-types',
  admin: {
    useAsTitle: 'name',
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
  ],
}

export const Documents: CollectionConfig = {
  slug: 'documents',
  admin: {
    useAsTitle: 'name',
    listSearchableFields: ['filename', 'name', 'type.name'],
  },
  upload: {
    staticDir: path.resolve(__dirname, '../../../../documents'),
    mimeTypes: ['application/pdf'],
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'type',
      type: 'relationship',
      relationTo: 'documents-types',
      required: true,
    },
    {
      name: 'name',
      type: 'text',
      required: true,
    },
  ],
}
```

### Payload Version

2.8.2

**Comment by SimYunSup** [comment]
I think Payload is not provide searching field value in related document.


> However, you **cannot** query on any field values within the related document. Since we are referencing multiple collections, the field you are querying on may not exist and break the query.
>
> https://payloadcms.com/docs/fields/relationship#querying-and-filtering-polymorphic-relationships

that placeholder is correct because related field value is not provided, so skip presenting.

**Comment by mat-twg** [comment]
> I think Payload is not provide searching field value in related document.
> 
> > However, you **cannot** query on any field values within the related document. Since we are referencing multiple collections, the field you are querying on may not exist and break the query.
> > https://payloadcms.com/docs/fields/relationship#querying-and-filtering-polymorphic-relationships
> 
> that placeholder is correct because related field value is not provided, so skip presenting.

provided as well by mongodb

![image](https://github.com/payloadcms/payload/assets/64251479/8bd97fcf-942b-4184-890d-fc36e068644f)
![image](https://github.com/payloadcms/payload/assets/64251479/51e6cc2b-6b78-4414-a15e-e5601f91ce6f)

**Comment by mat-twg** [comment]
What is there to think? the table(document/collecction) has a **type** (eg. **type**.name, **type**.anything.field) field, it is indicated in the **listSearchableFields**, it should be displayed in the *placeholder*, the errors you mention should be taken care of by the developer.
--
Just take first split by '.'

**Comment by SimYunSup** [comment]
1. It can produce a lot of bug because there is many edge cases. This is just working because relationship field in `where` is working. So I think it is not just developing problem.
  - nested value in relationship field.
  - Access denied field in relationship field.
  - relationship field in relationship field.
  - How about i18n?
2. I think it is better to use filter option. I think searching on field in relationship field must be disabled on `listSearchableFields`. And if you want to relationship field in `listSearchableFields`, It will be New Feature.

**Comment by mat-twg** [comment]
Everything you described is of course the case... but still it seems to me that this applies to relational databases as well, however we are discussing a simple thing - this is the value in the placeholder, no matter what the base is, it will be the same in all cases , for example: `field.name` -> `FieldName`
As for "i18n", it still does not work correctly or requires additional configuration of the search fields.

**Comment by SimYunSup** [comment]
I think this request should be categorized as New Feature as we need "additional configuration". The reason I listed the cases is that I need additional configuration for such edge cases.

If this is a bug, I think it is a bug that does not cause errors when the field (ex. `type.name` ) is put in `listSearchableFields`.
