### ISSUE TITLE
sendVerificationEmail error?

### ISSUE THREAD

**Issue by saher-elgendy** [payloadcms/payload#4939]
### Describe the Bug

the problem is described here
https://payloadcms.com/community-help/discord/sendverificationemail-error

### To Reproduce

this is the link of my project code in github
https://github.com/saher-elgendy/ShopVista

### Payload Version

2.9.0

### Adapters and Plugins

db-mongodb

**Comment by denolfe** [comment]
That thread appears to have a solution in it. 

> I had to post this issue only to find out where the error was! Had an error when setting up the server URL in the buildConfig...

It looks like you may have a mistyped env var in your config: `process.env.NEXT_PUBLICK_SERVER_URL`.
