### ISSUE TITLE
db-postgres: error: relation "main_navigation_items_topic_config_categories_external_links_lo" already exists

### ISSUE THREAD

**Issue by kahlstrm** [payloadcms/payload#4941]
### Link to reproduction

https://github.com/Tietokilta/web/commit/3e8b8378cf5d9fd6476bb124a91f79e8c42e5164

### Describe the Bug

I don't know if Drizzle generates the names of the relations or does the payload, so posting here. 
[The maximum of an identifier name in Postgres is 63 bytes](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS).
If there are both a table and the constraint for said table with such a long name, they both get truncated to the 63 byte identifier name and there comes a collision. Currently fix for this is to shorten the collection/field names, but this might be a good idea to document somehow at least, as the error itself is quite obscure.
Example commit where this happens is linked.

### To Reproduce

1. Clone the git repo at that specific commit
2. copy `.env.example` -> `.env`
3. `pnpm install` in repo root
4. `pnpm dev` in repo root
5. notice that the db push fails with error: relation "main_navigation_items_topic_config_categories_external_links_lo" already exists

### Payload Version

2.8.2

### Adapters and Plugins

db-postgres

**Comment by DanRibbens** [comment]
We have a workaroudn coming for this https://github.com/payloadcms/payload/pull/4525 which will let you provide your own db names.
