### ISSUE TITLE
Can't create more than 1 object with Auth set to True and then False - ValidationError: The following field is invalid: email

### ISSUE THREAD

**Issue by NicoPowers** [payloadcms/payload#4949]
### Link to reproduction

https://youtu.be/M8vHFAQh1Js

### Describe the Bug

Creating a collection with `auth: true` and then removing that statement, causes the Collection to not allow more than 1 object for that collection.

[Here is video showing this](https://youtu.be/M8vHFAQh1Js)

### To Reproduce

[Follow this video](https://youtu.be/M8vHFAQh1Js)

### Payload Version

2.0.0

### Adapters and Plugins

db-mongo, bundler-webpack, plugin-cloud, richtext-slate

**Comment by fr3fou** [comment]
+1, experienced the same issue a few days ago. Ended up working around this by deleting my entire database – thankfully I didn't have any important data.

**Comment by rklos** [comment]
+1. Payload doesn't remove the unused `email_1` index which is causing this error. For now you can delete this index manually

**Comment by jmikrut** [comment]
@rklos is correct - we don't delete indexes for you. That's something you need to do yourself. 

Thanks for bringing this up!
