### ISSUE TITLE
Difficulty setting access for Collection with versions enabled

### ISSUE THREAD

**Issue by ninahorne** [payloadcms/payload#495]
# Bug Report

I have two collections - Admins and Programs. Admins have a field called `programs` that is a relationship to many Programs. 
I save the `programs` field to JWT so that I can use this to allow Admins only access to the Programs to which they have a relationship.  The user request object looks like this:

I have set up my access Where query to look like this

```
  return {
      id: {
        in: programIds,
      },
    } as Where;

```
and I am getting this error: 

```
[12:53:00] ERROR (payload): CastError: Cast to Embedded failed for value "6243be881d7c11ccd98b4b71" (type string) at path "version" for model "_programs_versions"
    at model.Query.exec (/Users/*******/node_modules/mongoose/lib/query.js:4678:21)
    at model.Query.Query.then (/Users/*******node_modules/mongoose/lib/query.js:4777:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
webpack building...
```

I believe it has something to do with versions

## Expected Behavior
This query was working before enabling versions, and it works in a similar fashion for Collections that do no have versions enabled. 
I also filter access based on a different property of a Program (not the id) and it works as expected. I suppose this has something to do with the structure of the _program_versions object (the id is not nested in the `version` field)

## Current Behavior
No programs are returned and there is an error in the console. 

For now, i'm going to set a hidden field on the Program object to store it's ID again and filter on that.

**Comment by jmikrut** [comment]
Hey @ninahorne — we're on this right away. I have a sneaking suspicion as to what this is.

Thanks for the report!

**Comment by jmikrut** [comment]
Hey @ninahorne — thank you for this. It was a bug with versions just as you suspected. Deploying `0.15.2` with a fix now!

**Comment by ninahorne** [comment]
awesome! It's working now. Thanks
