### ISSUE TITLE
REST API / relationship filterOptions:  `where: { field: { equals: null } }` doesn't match any document

### ISSUE THREAD

**Issue by franciscolourenco** [payloadcms/payload#4959]
### Link to reproduction

https://github.com/franciscolourenco/payload/tree/reproduce-where-exists-equals-null/test/_community

### Describe the Bug

When returning `where: { fieldName: { equals: null } }` in a relationship field's `filterOptions()`, the select input doesn't show any documents where the fieldName is null.

It looks like it might be a problem with the REST API, specifically with [handling of null values by qs](https://github.com/ljharb/qs#handling-of-null-values). Using the qs `strictNullHandling: true` option on the client and server might fix the issue.

### To Reproduce

Open a the seeded post, and use the relationship fields.

<img width="1469" alt="image" src="https://github.com/payloadcms/payload/assets/208149/860022ed-9426-43b6-92cc-a9d58180003a">

I've created some tests as well. Seems like the local API returns 2 documents, where the field is null or undefined. Not sure if this is expected.

<img width="682" alt="image" src="https://github.com/payloadcms/payload/assets/208149/03fb68f0-622e-4028-9f3b-fb223de51efd">

Side note: As a new payload user, my expectation would be for `equals: null` to be a strict check and match only null values. And for `exists:false` to match both null and undefined. Independently of that, it looks like the relationship component and REST API work differently than the local API.

### Payload Version

2.9.0

### Adapters and Plugins

db-mongodb

**Comment by SimYunSup** [comment]
Additional: There is no null in text field when using mongodb.

- Create with no input: in mongodb, This is stored as `<No Field Value>`
- Update with input: This is stored what I input.
- Update with no input: This is stored as empty string.

**Comment by franciscolourenco** [comment]
@SimYunSup thanks for additional info. For context: I initially found this problem when referencing another relationship field. Used a text field in the reproduction to simplify.

**Comment by kendelljoseph** [comment]
We have a PR open that should fix the difference in recalling a null value using the REST API vs using the Local API. https://github.com/payloadcms/payload/pull/5241

**Comment by JarrodMFlesch** [comment]
Fixed from #5241. The responses now match the local API responses.
