### ISSUE TITLE
Credentals is missing from some POST APIs payload-preferences

### ISSUE THREAD

**Issue by hothanhson97** [payloadcms/payload#4971]
### Describe the Bug

I found that missing cookie when we called some POST method from payload-preferences. Maybe the same issue with this one #2704
![Screenshot 2024-02-02 at 13 39 50](https://github.com/payloadcms/payload/assets/111263969/a31d89af-f818-48d8-9bf0-0710fbba92c5)

### To Reproduce

- I found from your source code here you are missing credentials: "include" property here
![Screenshot 2024-02-02 at 13 42 23](https://github.com/payloadcms/payload/assets/111263969/5cab023d-4eb8-4efb-9140-7df4037818a7)

### Payload Version

1.15.0

**Comment by jmikrut** [comment]
Hey @hothanhson97 — credentials are indeed included within our `requests.post` method, and cookies are indeed included in the `{collectionSlug}-list` preferences fetch. I have just verified this on my end. 

This may be an issue with your CSRF or CORS settings, blocking the inclusion of cookies. Do you have CORS set to `*` by any chance? That prevents `Access-Control-Allow-Credentials` from being `true`.
