### ISSUE TITLE
pnpm run payload migrate:create - fail

### ISSUE THREAD

**Issue by ylahav** [payloadcms/payload#4975]
### Link to reproduction

CLI - pnpm run payload migrate:create

### Describe the Bug

pnpm run payload migrate:create

> site@1.0.0 payload E:\projects\payload\lashave\site
> cross-env PAYLOAD_CONFIG_PATH=src/payload/payload.config.ts payload "migrate:create"

[11:54:01] INFO (payload): Connected to MongoDB server successfully!
[11:54:01] INFO (payload): Starting Payload...
E:\projects\payload\lashave\site\node_modules\.pnpm\payload@2.9.0_@types+react@18.2.51_typescript@5.3.3_webpack@5.90.0\node_modules\payload\dist\bin\migrate.js:92
                throw new Error(`Error creating migration: ${err.message}`);
                      ^

Error: Error creating migration: Cannot read properties of undefined (reading 'startsWith')
    at migrate (E:\projects\payload\lashave\site\node_modules\.pnpm\payload@2.9.0_@types+react@18.2.51_typescript@5.3.3_webpack@5.90.0\node_modules\payload\dist\bin\migrate.js:92:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.0
 ELIFECYCLE  Command failed with exit code 1.

### To Reproduce

I have created a new payload project and connected it to an existing mongodb database (from payload 1)
and getting the issue when tring to migrate the database
BTW - execpt one collection - I can see all collection on the admin

### Payload Version

2.9

**Comment by denolfe** [comment]
Recreated. Looks like we need to safely check for the script.

To work around this, you can pass an additional parameter that will be used as the script name.
