### ISSUE TITLE
Memory Issue while uploading

### ISSUE THREAD

**Issue by GeorgeHulpoi** [payloadcms/payload#4981]
### Link to reproduction

https://github.com/GeorgeHulpoi/payload-memory-issue

### Describe the Bug

On local, it generates an error and takes a lot to return this error:

```
[Error: UNKNOWN: unknown error, open 'C:\Projects\payload-memory-issue\tmp\tmp-1-1706899451895'] {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'open',
  path: 'C:\\Projects\\payload-memory-issue\\tmp\\tmp-1-1706899451895'
}
[20:44:21] ERROR (payload): FileUploadError: There was a problem while uploading the file.
    at generateFileData (C:\Projects\payload-memory-issue\node_modules\payload\src\uploads\generateFileData.ts:253:11)
    at create (C:\Projects\payload-memory-issue\node_modules\payload\src\collections\operations\create.ts:127:57)
    at createHandler (C:\Projects\payload-memory-issue\node_modules\payload\src\collections\requestHandlers\create.ts:26:17)
```

On my EC2, seems like it's inside a loop because the CPU and VolumeReadBytes increase.
![image](https://github.com/payloadcms/payload/assets/7074307/09e8d995-bb77-4e5a-a747-68f79dc67fd9)
![image](https://github.com/payloadcms/payload/assets/7074307/2c420f8f-56ff-4e62-92a7-e16a2c961c02)

### To Reproduce

1. Upload in `Media` the file from `assets`

### Payload Version

2.9.0

### Adapters and Plugins

MongoDB

**Comment by GeorgeHulpoi** [comment]
After some debugging, this https://github.com/payloadcms/payload/blob/b392d656fe4d52f04cf88d9003a396b2e03b5ec7/packages/payload/src/uploads/generateFileData.ts#L146 takes a lot, I guess there is the increase in CPU.
But the error is produced here: https://github.com/payloadcms/payload/blob/b392d656fe4d52f04cf88d9003a396b2e03b5ec7/packages/payload/src/uploads/generateFileData.ts#L205

**Comment by paulpopus** [comment]
Hey @GeorgeHulpoi I pulled down the repo, and I tried uploading a 5MB image and didn't come across any errors or memory issues.

Are there more things I need to try to reproduce this?

**Comment by GeorgeHulpoi** [comment]
Hi @paulpopus. Seems like I can't reproduce the error on EC2/Ununtu, but the combination of GIF files with useTempFile seems to increase the CPU a lot, and the request takes a few seconds. Without using temp files, it's fast enough.

I still want to find out why I have that error on local. I use Windows 10, maybe somebody can reproduce this issue.

**Comment by GeorgeHulpoi** [comment]
Looking again at the code, I saw that where the error is thrown you try to rewrite an existing file, which may be locked by sharp or payload itself. While https://github.com/payloadcms/payload/blob/b392d656fe4d52f04cf88d9003a396b2e03b5ec7/packages/payload/src/uploads/generateFileData.ts#L218 waits to file to be released, it may create an infinite loop.
Wouldn't be safer to save it to a different file?

**Comment by paulpopus** [comment]
Hey George, is this still an issue with v3? I will close this issue as stale for now but we can re-open it if we get a reproduction
