### ISSUE TITLE
GraphQL: Cannot set draft on nested relations.  Can set draft where draft is not enabled.

### ISSUE THREAD

**Issue by dacgray** [payloadcms/payload#4985]
### Describe the Bug

We have 2 collections.

TopFooterV1 - versioning with draft is NOT enabled.

StaticPageV1 - versioning with draft IS enabled.

1st Issue:

We cannot set a draft argument on the relation:

![image](https://github.com/payloadcms/payload/assets/12794616/07b244f2-4006-40a0-a588-7c4167487df0)
![image](https://github.com/payloadcms/payload/assets/12794616/79d37b7e-5194-44a7-87e8-9aa8e2e855a5)

Would be very helpful if draft, where, locale, limit and sort are available.

2nd Issue:

The schema generator adds `draft` to a collection with versioning and drafts disabled:

```
  TopFooterV1s(draft: Boolean, where: TopFooterV1_where, fallbackLocale: FallbackLocaleInputType, locale: LocaleInputType, limit: Int, page: Int, sort: String): TopFooterV1s
```

### To Reproduce

As above

### Payload Version

2.9.0

### Adapters and Plugins

"@payloadcms/bundler-webpack": "^1.0.6",     "@payloadcms/db-mongodb": "^1.3.2",     "@payloadcms/plugin-cloud-storage": "^1.1.1",     "@payloadcms/plugin-sentry": "^0.0.6",     "@payloadcms/richtext-slate": "^1.3.1",

**Comment by evelynhathaway** [comment]
I was running into this with an without GraphQL in https://github.com/payloadcms/payload/discussions/3963#discussioncomment-8846692.

In Payload v2.16.1, I no longer experience it with the REST API and if I manually add the draft variable to each relationship; however, I am not getting the cascading behavior noted in #6141.

**Comment by JarrodMFlesch** [comment]
@evelynhathaway I just tested this and it seems to be working. Can you provide more context? Or possibly a small reproduction?

**Comment by evelynhathaway** [comment]
@JarrodMFlesch I think the difference is that I am using a global maybe?

With this repro: https://github.com/evelynhathaway/payload/commit/9bd24ffdbb89d0cb5feec98f11dc0d7867c65a54

And you open `http://127.0.0.1:3000/api/graphql-playground` and query:

```graphql
{
  Menu(draft: true) {
    relationship {
      text
    }
  }
}
```

The output is `published example post`, but if the draft variable is set on the relationship, it will return the draft:

```graphql
{
  Menu(draft: true) {
    relationship(draft: true) {
      text
    }
  }
}
```

**Comment by evelynhathaway** [comment]
I also ran into this with Rich Text links that are relationships. At least with the Slate editor and GraphQL, there isn't a `draft` variable, and will always return the published version ([or the first draft if no published version exists](https://github.com/payloadcms/payload/discussions/3963#discussioncomment-9438292)).

This prevents rich text relationship links from working if the linked document location changed since the linked document was last published (or since the first draft if no published version exists)

@JarrodMFlesch would it be best to reopen this issue, or shall I create new issues to track these sub-issues?

**Comment by JarrodMFlesch** [comment]
@evelynhathaway yes that would be super helpful actually!

**Comment by evelynhathaway** [comment]
Created #6642 and #6643 for the discussed sub-issues
