### ISSUE TITLE
Unable to edit images in upload collection

### ISSUE THREAD

**Issue by slavanossar** [payloadcms/payload#5000]
### Link to reproduction

https://github.com/slavanossar/payload-image-edit-bug

### Describe the Bug

In an upload-enabled Images collection, the focal point of the image can be set when creating the file:

![payload-image-edit-1](https://github.com/payloadcms/payload/assets/7077600/b26b0ff4-e1ad-441d-92cd-4342026f1bbb)

When going back and editing the image an error is displayed, with no changes being saved and no new images being generated:

![payload-image-edit-2](https://github.com/payloadcms/payload/assets/7077600/6b054cfa-ec14-489a-b77c-ed45a071aaf2)

Also note that the saved position of the focal point isn't shown when going back to edit the image.

The following error is displayed in the console:

```
ERROR (payload): FileUploadError: There was a problem while uploading the file.
    at generateFileData (/payload-image-edit-bug/node_modules/.pnpm/payload@2.9.0_typescript@5.3.3_webpack@5.90.1/node_modules/payload/src/uploads/generateFileData.ts:80:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateByID (/payload-image-edit-bug/node_modules/.pnpm/payload@2.9.0_typescript@5.3.3_webpack@5.90.1/node_modules/payload/src/collections/operations/updateByID.ts:142:57)
    at async updateByIDHandler (/payload-image-edit-bug/node_modules/.pnpm/payload@2.9.0_typescript@5.3.3_webpack@5.90.1/node_modules/payload/src/collections/requestHandlers/updateByID.ts:36:17)
```

The problem seems to occur due to the [`getExternalFile`](https://github.com/payloadcms/payload/blob/main/packages/payload/src/uploads/getExternalFile.ts) function generating an invalid `fileURL` value when it [prepends the `baseUrl` to a `url` that already includes it](https://github.com/payloadcms/payload/blob/2c71aaef7503d8b8e4923864aa103029edef6768/packages/payload/src/uploads/getExternalFile.ts#L14), resulting in:

```
http://localhost:3001http://localhost:3001/media/images/archology-feature-image.jpg
```

### To Reproduce

1. Clone reproduction repository
2. Install packages `pnpm i`
3. Create .env with `pnpm run configure-env`
4. Start dev server `pnpm run dev`
5. Navigate to `http://localhost:3001/admin` and create a user
6. Upload an image to the Images collection and save it
7. Edit the image and change the focal point or crop, and save it

### Payload Version

2.9.0

### Adapters and Plugins

bundler-webpack, db-mongodb

**Comment by cbratschi** [comment]
I reported this before: https://github.com/payloadcms/payload/issues/4421#issuecomment-1864867979

The transpiled TypeScript code is wrong and silently fails (exception is ignored).

**Comment by slavanossar** [comment]
I don't think I'm experiencing the same issue with imports/modules, in my case the `fileURL` being generated is invalid and causes `fetch` to fail.

**Comment by cbratschi** [comment]
@slavanossar my fetch URL is correct but then the fetch step fails. The TypeScript error should happen first, no fetch gets executed at all. Modify the code in node_modules and you will see the root cause.

**Comment by slavanossar** [comment]
@cbratschi I already tried modifying the code to see what was going on, which is why I included this in the issue

> The problem seems to occur due to the [`getExternalFile`](https://github.com/payloadcms/payload/blob/main/packages/payload/src/uploads/getExternalFile.ts?rgh-link-date=2024-02-05T23%3A44%3A05Z) function generating an invalid `fileURL` value when it [prepends the `baseUrl` to a `url` that already includes it](https://github.com/payloadcms/payload/blob/2c71aaef7503d8b8e4923864aa103029edef6768/packages/payload/src/uploads/getExternalFile.ts#L14), resulting in:
> 
> ```
> http://localhost:3001http://localhost:3001/media/images/archology-feature-image.jpg
> ```

Adding a `catch` to the `fetch` gives `TypeError [ERR_INVALID_URL]: Invalid URL`, as expected based on the invalid `fileURL`.

**Comment by denolfe** [comment]
Taking a look at this one 👀
