### ISSUE TITLE
filters on request by ID does not applies

### ISSUE THREAD

**Issue by mat-twg** [payloadcms/payload#5004]
### Describe the Bug

When request by id, filters does not applies

![image](https://github.com/payloadcms/payload/assets/64251479/40c328ff-b9a2-43a4-adbe-1269ff949c3a)

Request
```shell
http://192.168.10.156:3801/api/products/65c11a0ad07c400f312a7396?where[_status][equals]=published
```
Response: **200 OK**
```json
{
...
  "_status": "draft",
  "createdAt": "2024-02-05T17:25:30.554Z",
  "updatedAt": "2024-02-06T11:44:01.687Z",
  "publishedOn": "2024-02-05T17:25:35.401Z"
}
```

expected: **404 Not Found**

![image](https://github.com/payloadcms/payload/assets/64251479/3be97678-57ff-431f-ac49-03afd16f361b)

### To Reproduce

any collection, try request by Id with filters

### Payload Version

2.9.0

**Comment by jmikrut** [comment]
Hey @mat-twg — this is expected behavior. There is no reason for a filter to apply to a document when requested by ID because you are explicitly asking for that document by ID. Filters only apply to the `find` endpoint.

**Comment by mat-twg** [comment]
> Hey @mat-twg — this is expected behavior. There is no reason for a filter to apply to a document when requested by ID because you are explicitly asking for that document by ID. Filters only apply to the `find` endpoint.

In general, of course, you are right, but it is inconvenient. There are generally accepted practices that have been used for decades.
In fact, there are reasons, for example, I gave the publication `status`, there are a lot of cases...
Here's another example, say, deleting documents without physically deleting them from the database, they often use the `deleted: boolean` field
Of course I expect the backend to not give me the remote document, why would I need to introduce additional logic somewhere else if it's directly at the database level
