### ISSUE TITLE
After logging in, the `redirect` query param should be followed

### ISSUE THREAD

**Issue by gianpaj** [payloadcms/payload#5009]
### Describe the Bug

This redirect link is not followed
https://localhost:3000/admin/logout-inactivity?redirect=%2Fcollections%2Fpartners%2F65439cfe40a05354014086c6

### To Reproduce

Reduce the `tokenExpiration` to 5 mins ([docs](https://payloadcms.com/docs/authentication/config#options)). For example in `src/collections/Users.ts`
```ts
const Users: CollectionConfig = {
	slug: 'users',
	auth: {
		useAPIKey: true,
		disableLocalStrategy: true,
		tokenExpiration: 60 * 5 // Session expires in 5 mins - if you set it to 1 min there's a strange behaviour that looks it expires immediately
	},
```

1. login (this needs to happen after the `tokenExpiration` is changed)
2. open two tabs
3. navigate one tab anywhere inside the CMS
3. allow the session to expire (wait for the `You have been logged out due to inactivity.`)
4. login on the other tab
5. refresh the tab where the session expired (the one with `/logout-inactivity` path) and you'll see the redirect is not followed
6. it redirects to `/admin` 😢 

I believe the fix is to:
- When the `logout-inactivity` ([\<Logout \/\>](https://github.com/payloadcms/payload/blob/main/packages/payload/src/admin/components/views/Logout/index.tsx)) route is loaded again, check if you're logged in and redirect if so. Do not logout

PS: the `Log back in` button also doesn't respect the redirect

### Payload Version

latest

**Comment by gianpaj** [comment]
@kendelljoseph , i've update the description with a bit more context and easier steps to follow. Happy to clarify anything if needed

**Comment by kendelljoseph** [comment]
@gianpaj Thank you! I'll dig into this!
