### ISSUE TITLE
GraphQL types for required fields are optional and nullish.

### ISSUE THREAD

**Issue by matthewfleming** [payloadcms/payload#5016]
### Link to reproduction

https://github.com/matthewfleming/payload-playground

### Describe the Bug

TS and graphql types are not what I would expect given the Carousel collection for required fields:
```ts
// Collection
export const Carousel: CollectionConfig = {
    auth: false,
    slug: "carousel",
    admin: {
        useAsTitle: "carousel",
    },
    versions: {
        drafts: true,
    },
    fields: [
        {
            name: "heading",
            type: "text",
            required: true,
        },
        {
            name: "optional",
            type: "text",
            required: false,
        },
    // ...
```

Generated migration
```sql
CREATE TABLE IF NOT EXISTS "carousel" (
	"id" serial PRIMARY KEY NOT NULL,
	"heading" varchar,
	"optional" varchar,
	"sub_heading" jsonb,
	"cta_link" varchar,
	"cta_title" varchar,
	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
	"_status" "enum_carousel_status"
);
```
I would expect the required fields would be NOT NULL here (actually not that bothered about this).

Generated graphql schema:
```graphql
type Carousel {
  id: Int
  heading: String
  optional: String
  subHeading(depth: Int): JSON
  ctaLink: String
  ctaTitle: String
  mobileBanner(where: Carousel_MobileBanner_where): Media
  tabletBanner(where: Carousel_TabletBanner_where): Media
  desktopBanner(where: Carousel_DesktopBanner_where): Media
  updatedAt: DateTime
  createdAt: DateTime
  _status: Carousel__status
}
```
Here I would expect all of the fields to have a not null shebang except the optional one.

The impact of this is when I run this query in client.ts - the inferred types are all optional and nullish.
```graphql
export const GET_CAROUSELS = gql(`
    query Carousels($limit: Int) {
        Carousels(limit: $limit) {
            docs {
                id
                ctaLink
                ctaTitle
                optional
                heading
                subHeading
                desktopBanner {
                    url
                    alt
                }
            }
        }
    }
`);
```
<img width="812" alt="image" src="https://github.com/payloadcms/payload/assets/3954749/e30f581b-0ef9-4a8c-9e93-fda9ae6e9c81">

Instead the type of docs should look like this:

```ts
type docs = {
    __typename?: "Carousel" | undefined;
    id: number;
    ctaLink: string;
    ctaTitle: string;
    optional: string | null;
    heading: string;
    subHeading: any;
    desktopBanner: {
        //...;
    };
}[];
```

So that:
- all requested fields are returned (all props are defined)
- only the optional field is nullable
- null does not appear in the array

I believe at runtime the returned object matches this type I have defined, but this is not what is generated/inferred.

This makes using the types annoying in practise because you have to confirm everything exists or explicitly define all the types and do casts.

### To Reproduce

```sh
git clone git@github.com:matthewfleming/payload-playground.git
cd payload-playground
pnpm i
# Start the server (need graphql endpoint for codegen)
pnpm dev
# Generate types, graphql schema, graphql codegen, migration
pnpm generate:all
```

### Payload Version

2.9.0

### Adapters and Plugins

db-postgres

**Comment by jmikrut** [comment]
Hey @matthewfleming — so there are a variety of reasons why a field might be defined as `required: true`, but the GraphQL / database schema may not reflect it.

The reasons differ between GraphQL and the database, but for the DB, the following can make a field nullable, even if set as required:

- If the field has conditional logic applied to it (it only would act as required if the field was conditionally rendered)
- If drafts are enabled (drafts can be saved as partially complete, therefore the DB needs to be able to accept partially complete docs)

In GraphQL, this is a bit different:

- If you have read access control set on a field, some users might not have access to the field
- If the field is localized (might not be set in non-default locales yet)
- Conditional logic, as above
- Drafts enabled, as above

I am probably forgetting some of the reasons, but basically this is functioning as necessary right now. Does that make sense?

**Comment by matthewfleming** [comment]
Great meeting you yesterday @jmikrut.

I understand your response but I'm not really satisfied with it. I have confirmed that disabling drafts 'fixes' the optional/nullish issue but then we don't have the draft function. Or we have a bad draft experience.
Union types can fix this.

e.g. Something like this. My expectation would be that usually endpoints would return CarouselPublished, unless I'm querying CarouselVersions or specify `where: _status = "draft"` in the query.

```ts
type CarouselPublished {
  id: Int
  heading: String!
  optional: String
  subHeading(depth: Int): JSON!
  ctaLink: String!
  ctaTitle: String!
  mobileBanner(where: Carousel_MobileBanner_where): Media!
  tabletBanner(where: Carousel_TabletBanner_where): Media!
  desktopBanner(where: Carousel_DesktopBanner_where): Media!
  updatedAt: DateTime
  createdAt: DateTime
  _status: "Published"
}

type CarouselDraft {
    id: Int
    heading: String
    optional: String
    subHeading(depth: Int): JSON!
    ctaLink: String
    ctaTitle: String
    mobileBanner(where: Carousel_MobileBanner_where): Media
    tabletBanner(where: Carousel_TabletBanner_where): Media
    desktopBanner(where: Carousel_DesktopBanner_where): Media
    updatedAt: DateTime
    createdAt: DateTime
    _status: "Draft"
}

type Carousel = CarouselPublished | CarouselDraft
```

Also IMHO `docs` should never be `null[], null or undefined`. I don't think `[null]` should occur, and the default can be an empty array, eliminating `null | undefined`?

**Comment by jmikrut** [comment]
Good meeting you as well!

So, unfortunately it's not going to be that simple to implement a `CarouselPublished` / `CarouselVersions` approach.

Right now, as you've probably noticed, if drafts are enabled on a Carousel collection, we retain _two_ tables - one `carousels` and one `_carousels_v`. And that probably seems like on the surface level that we store published docs in the `carousels` table, and then drafts / all other versions in the `_carousels_v` table. 

But that's not how it works - rather, _**we always need a document in the main table itself**_ - regardless of if it is saved first as a draft or as published - to be able to tie all of its versions back to the main doc by ID.

So in the case where you save a document as `draft` for the first time you create it, you will end up with a partial document in the main table. That means at the very least, the database side of things will always need to maintain nullable columns for all fields due to the partial draft thing I mentioned earlier.

Now - in GraphQL, we could indeed create a union type for `Carousel` like you mentioned - we'll look into that.

But in the interim, one thing you could do is re-use Payload's built-in GraphQL schema generators to create your own `CarouselPublished` query that only returns published documents. 

I've opened up a feature request discussion here, and we can track progress accordingly one way or another on the feature request:

https://github.com/payloadcms/payload/discussions/5031

Thanks for following up here!

**Comment by matthewfleming** [comment]
Thanks that makes sense. By schema generators are you referring to https://payloadcms.com/docs/graphql/extending or something else?
