### ISSUE TITLE
using filterOptions on relationship field can cause infinite loop

### ISSUE THREAD

**Issue by felskov** [payloadcms/payload#5029]
### Describe the Bug

When adding filterOptions to a polymorphic relationship field, we're experiencing infinite loops in the frontend when doing any interaction with the content (ie. doesn't matter if we type characters inside a richtext field or anything else, as soon as content is updated the application enters an infinite loop).

### To Reproduce

1. Create a relationship field with multiple collections
2. Add filterOptions callback to the field on certain collections
3. Try to edit a document
4. The frontend UI will enter an infinite loop

### Payload Version

2.9.0

### Adapters and Plugins

db-mongodb, bundler-webpack, richtext-slate

**Comment by akhrarovsaid** [comment]
I'm currently experiencing this issue. Payload v. 2.20.0
