### ISSUE TITLE
error on deployment on vercel 

### ISSUE THREAD

**Issue by MauryaAnurag** [payloadcms/payload#5049]
### Describe the Bug

Error configuring redirects: SyntaxError: Unexpected token < in JSON at position 0
![image](https://github.com/payloadcms/payload/assets/78605303/cc9f6bc1-aa68-41eb-bb6c-70414588e122)
U can see the error in thsi image 
and any routes is not working and jsut shwoing 404 not found

Below is my deployment and build commands
![image](https://github.com/payloadcms/payload/assets/78605303/3b26dcb8-608c-4724-a04f-99ca63f721e8)

### To Reproduce

I HAVENT DONE anything just setup and build 

### Payload Version

latest

**Comment by timothylam1228** [comment]
I am having the same error, maybe it is problem about dynamic ip? Cause having the same result on different platform (Work fine on payload cloud)

**Comment by denolfe** [comment]
On Payload 2.x, deploying to Vercel will not work properly. Full support for this is available in the 3.x beta.
