### ISSUE TITLE
livePreview not populating upload in lexical block

### ISSUE THREAD

**Issue by carstenblt** [payloadcms/payload#5051]
### Describe the Bug

When using the lexicalEditor, upload fields inside a custom Block are not populated by @payloadcms/live-preview-react. Internal links are populated correctly. (Yes, I checked CORS. There is no request to populate the relationship)

### To Reproduce

Create a custom block like

```
import { Block } from "payload/types";
import { lexicalEditor } from "@payloadcms/richtext-lexical";

export const ImageBlock: Block = {
  slug: "Image",
  fields: [
    {
      name: "image",
      type: "upload",
      relationTo: "media",
      required: true,
      filterOptions: {
        mimeType: { contains: "image" },
      },
    },
    {
      name: "caption",
      type: "richText",
    },
  ],
};
```

Include it in the lexical config as a custom block. Then useLivePreview() from @payloadcms/live-preview-react.

### Payload Version

2.11.0

**Comment by tyteen4a03** [comment]
+1 - can reproduce.

**Comment by carstenblt** [comment]
Actually, no `relationship` fields at all are populated inside of blocks.
