### ISSUE TITLE
live preview not checking message type

### ISSUE THREAD

**Issue by carstenblt** [payloadcms/payload#5056]
### Describe the Bug
I have a chrome extension that also sends messages to the page. `@payloadcms/live-preview` subscribes to all these messages and triggers an update with this invalid data, resulting in a return of `initialData`.

`onMessage` in `subscribe.ts` should check if `data.type === 'payload-live-preview'` and otherwise discard the message.

### To Reproduce
Use `livePreview` and `@payloadcms/live-preview-react` with MetaMask.

### Payload Version
2.11.0

**Comment by carstenblt** [comment]
This is really bad style on so many levels but indeed this works:

```
  const { data } = useLivePreview({
    initialData: { title: "Loading..." },
    serverURL: process.env.NEXT_PUBLIC_PAYLOAD_URL,
  });
const [cachedData, setCachedData] = useState(data);
useEffect(() => {
    if (data.title !== "Loading...") setCachedData(data);
  }, [data]);
```

**Comment by jacobsfletch** [comment]
Hey @carstenblt, after looking into this a bit, I'm not sure this is an issue. The `@payloadcms/live-preview` subscription takes place _within the iframe or popup window_, meaning `window.postMessage` events on the parent page would not hit the event listeners attached in these contexts. To do that requires a DOM reference to the iframe or popup window, which extensions do not have. The parent page attaches a similar event listener, but this is already wrapped in a condition that checks the event type. You can easily test this by opening live preview in your browser, opening your developer tools, and running `window.postMessage('test')` in your inspector. Related: #3779

**Comment by jacobsfletch** [comment]
If this is still an issue for you, let me know. If you can provide me with a reproduction or more clearly reproducible steps, I will look into this further.
