### ISSUE TITLE
Lexical hyperlink feature wants 🥗 for its 🐛 

### ISSUE THREAD

**Issue by patricsgamma** [payloadcms/payload#5057]
### Link to reproduction

---

### Describe the Bug

Lexical Richtext editor has 2 issues with links.

### First the most usual working scenario
If you write a "Text" (That is not a hyperlink).
Select the "Text" and click the hyperlink toggle.
Then enter a Link: e.g.  `https://payloadcms.com/` and confirm this.
 This works ✔️

IF we now select the hyperlinked "Text" we get a toolbar that displays the link with `Edit` ✏️ and `Remove` ✖️ icon.
We can no edit the Hyperlink with the Edit ✏️ and it works ✔️ 
We can also Remove ✖️ the hyperlink, also a pass ✔️ 

But there is 2 unexpected Scenarios, that are or feel buggy.

### Removing the Hyperlink for a hyperlink text

Now we go to [https://payloadcms.com/](https://payloadcms.com/) and copy the Url.
Then we go to our RichText editor and past the url directly into it. This will create a hyperlinked url.

If we now point the cursor at our url and click the Remove ✖️ 
This has no effect and appears to fail ❌ 

Click on X is not having any effect.

https://github.com/payloadcms/payload/assets/87857953/79f22ee8-d2ec-4b5a-95cb-6dcd9b7ca859

The failure is also present in lexical Playground (so likely not Payload specific)

https://github.com/payloadcms/payload/assets/87857953/7a740207-435e-4fc9-b361-3bfe3f86cafe

### Editing a Hyperlink for a hyperlink text

We take the same state as previous failing scenario, having a url as text with a hyperlink.
If we now point the cursor at our url and click the Edit ✏️ 
We get the modal window to edit the text as well as the hyperlink.
If we change the Display Text now to e.g. Payload and apply the change, we get back to the RichtText editor.
But the Hyperlink is gone all together
This appears to fail as well ❌ 

Hyperlink is removed after Display Text is changed.

https://github.com/payloadcms/payload/assets/87857953/f7c9796e-5dfe-45c2-a668-74436b72890f

To me it appears that lexical has a bit of magic involved to turn urls directly into hyperlinks,  but this piece fails the edit and remove option.

### Payload Version

`"payload": "^2.10.0"`

### Adapters and Plugins

```
"@payloadcms/bundler-webpack": "^1.0.6",     
"@payloadcms/db-mongodb": "^1.4.0",     
"@payloadcms/plugin-cloud-storage": "^1.1.2",     
"@payloadcms/plugin-sentry": "^0.0.6",     
"@payloadcms/richtext-lexical": "^0.6.1",
```

**Comment by AlessioGr** [comment]
Pasting links will create `AutoLink`Nodes in the editor - not `LinkNode`s, which behave a bit differently.

Optimally, when you edit an AutoLink node, it should be converted into a LinkNode when you make any edits (like editing the DisplayName), though. I've reproduced this and will look into it
