### ISSUE TITLE
Cannot import internal validations from payload/fields/validations

### ISSUE THREAD

**Issue by paulpopus** [payloadcms/payload#5082]
### Describe the Bug

As per docs
it is expected that you can import validation functions from validations via `import { text } from 'payload/fields/validations'` however this errors as undefined

This does work however

```ts
import { number } from 'payload/dist/fields/validations'
```

### To Reproduce

Try

```ts
import { text } from 'payload/fields/validations'
```

### Payload Version

2.8.0

**Comment by snoopdouglas** [comment]
Just ran into this exact issue. Can confirm the above fix works.

The docs page which suggests using this is here: https://payloadcms.com/docs/fields/overview#validation
