### ISSUE TITLE
Generated Where type issue for text field with hasMany: true.

### ISSUE THREAD

**Issue by revnelson** [payloadcms/payload#5087]
### Describe the Bug

I have a collection field of type `text` with the `hasMany: true` option set. This is essentially an simple array and querying with `where[textField][contains]=targetText` does actually work, but the generated type does not include the `contains` parameter, which causes the TS engine to have a fit.

### To Reproduce

Create a text field on CollectionWithHasManyTextField. Enable `hasMany`. Generate types. Create an `where` object of type CollectionWithHasManyTextField_Where using the `contains` parameter.

### Payload Version

2.11.0

**Comment by AlessioGr** [comment]
This currently works as intended actually! The where object is not typed based on the generated types at all right now (although I think that would be a great feature request, feel free to open one in the discussions tab!).

There currently is no type error at all:

![CleanShot 2024-06-15 at 03 03 27@2x](https://github.com/payloadcms/payload/assets/70709113/1942fe6d-d373-4c34-8c31-21df0eeeb0fc)


If TypeScript is erroring out, this is likely an issue with your `CollectionWithHasManyTextField_Where` type.
