### ISSUE TITLE
Error installing dependencies 

### ISSUE THREAD

**Issue by unclehowell** [payloadcms/payload#5092]
### Describe the Bug

I get these errors   

```
Installing dependencies...{
  err: Error: Command failed with exit code 1: npm install --legacy-peer-deps
  npm WARN EBADENGINE Unsupported engine {
  npm WARN EBADENGINE   package: 'next@13.5.2',
  npm WARN EBADENGINE   required: { node: '>=16.14.0' },
  npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
  npm WARN EBADENGINE }
  npm WARN EBADENGINE Unsupported engine {
  npm WARN EBADENGINE   package: 'payload@2.11.0',
  npm WARN EBADENGINE   required: { node: '>=14' },
  npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
  npm WARN EBADENGINE }
  npm WARN EBADENGINE Unsupported engine {
  npm WARN EBADENGINE   package: 'css-minimizer-webpack-plugin@5.0.1',
  npm WARN EBADENGINE   required: { node: '>= 14.15.0' },
  npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
  npm WARN EBADENGINE }
```
 
I also get these errors 

      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@smithy/protocol-http@3.1.1',\n" +
      "npm WARN EBADENGINE   required: { node: '>=14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@smithy/smithy-client@2.3.1',\n" +
      "npm WARN EBADENGINE   required: { node: '>=14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@smithy/types@2.9.1',\n" +
      "npm WARN EBADENGINE   required: { node: '>=14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@smithy/util-base64@2.1.1',\n" +
      "npm WARN EBADENGINE   required: { node: '>=14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@smithy/util-body-length-node@2.2.1',\n" +
      "npm WARN EBADENGINE   required: { node: '>=14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@smithy/util-endpoints@1.1.1',\n" +
      "npm WARN EBADENGINE   required: { node: '>= 14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@smithy/util-middleware@2.1.1',\n" +
      "npm WARN EBADENGINE   required: { node: '>=14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@smithy/util-retry@2.1.1',\n" +
      "npm WARN EBADENGINE   required: { node: '>= 14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@smithy/util-utf8@2.1.1',\n" +
      "npm WARN EBADENGINE   required: { node: '>=14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@aws-sdk/util-locate-window@3.495.0',\n" +
      "npm WARN EBADENGINE   required: { node: '>=14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@aws-sdk/middleware-bucket-endpoint@3.511.0',\n" +
      "npm WARN EBADENGINE   required: { node: '>=14.0.0' },\n" +
      "npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }\n" +
      'npm WARN EBADENGINE }\n' +
      'npm WARN EBADENGINE Unsupported engine {\n' +
      "npm WARN EBADENGINE   package: '@aws-sdk/middleware-expect-continue@3.511.0',\n" +
      "npm WARN EBADENGINE   required: { node: '>=14.0.0' },\n" +
   

### To Reproduce

npx create-payload-app
✔ Choose project template › ecommerce
✔ Select a database › PostgreSQL (beta)
(OS is Mint 21.3)

### Payload Version

2.0

### Adapters and Plugins

n/a

**Comment by denolfe** [comment]
The error is pretty straight-forward here. It's saying you have node `v12.22.9`, and `>=16.14.0` is required.

Update your node version, and you will be good.
