### ISSUE TITLE
No documentation whatsoever on how to set Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by dhiegomaga** [payloadcms/payload#5105]
# Documentation Issue

When making a simple `POST` request using `withCredentials: true` on chrome v121, you will get this error: 

```
Request header field withcredentials is not allowed by Access-Control-Allow-Headers in preflight response
```

This is because `withCredentials` header is not set on the pre-flight response `OPTIONS` request: 

![image](https://github.com/payloadcms/payload/assets/25873377/5dedb26c-4c3d-4516-a26a-ebd4dcc4ca84)

Nowhere is explaining how to set this header, for such a simple and fundamental feature. You cannot develop anything that uses authentication without this feature with any modern browser.

**Comment by dhiegomaga** [comment]
After many hours wasted because you guys don't know how to set up a simple web server, here is the solution:

```
// @src/server.ts
// ...
var cors = require('cors');
var corsOptions = {
  origin: 'http://localhost:5173', // <- frontend address
  credentials: true, // <-- set this
  optionsSuccessStatus: 200
}

const start = async (): Promise<void> => {
  app.use(cors(corsOptions));
 // ...
```

**Comment by JarrodMFlesch** [comment]
@dhiegomaga you do not need the `cors` package to get this to work.

All you need to do is send your request from the frontend application with the `credentials: "include"` setting. You can see in the docs how this is done [here](https://payloadcms.com/docs/authentication/overview#using-fetch-or-other-http-apis).

If your frontend domain differs from your backend domain then you can configure cors [directly on your config](https://payloadcms.com/docs/configuration/overview#options).

**Comment by dhiegomaga** [comment]
@JarrodMFlesch 
> All you need to do is send your request from the frontend application with the credentials: "include" setting. You can see in the docs how this is done [here](https://payloadcms.com/docs/authentication/overview#using-fetch-or-other-http-apis).

I did this, it doesn't work if you only do that in case the frontend and backend have different URLs (as you probably already know)... 

> If your frontend domain differs from your backend domain then you can configure cors [directly on your config](https://payloadcms.com/docs/configuration/overview#options).

How exactly does one configure cors directly on the config to achieve the same as I did? Ie. set `credentials: true` on the backend configuration?
