### ISSUE TITLE
payload cloud documentation does not reveal how to create the content model. 

### ISSUE THREAD

**Issue by mpstaton** [payloadcms/payload#5109]
# Documentation Issue

After trying to monkey around with getting a Payload instance going on Local with Postgres using Docker (big fail, which I raised an issue about), I decided to just pay for Payload Cloud.  

Okay, so I created a Payload Cloud instance of Payload, nothing tricky just blank.  And, I cannot create the Content Model.  I have a User model, and I can create users.  But that's it.  

Your documentation doesn't say what to do from here. Am I supposed to clone the Git Repo on local and then....  use npm run develop or yarn develop like in Strapi?  

I just dug in again, and how to edit the Content Model is.... drumroll.... on the last page, for no logical reason: under "projects". 

I will follow those instructions, too.  But based on my current experience you all spend a lot of time on your fancy landing pages and branding and ZERO TIME on making your documentation legible for anyone who doesn't spend their whole life in code.  

2:01AM -- README wants me to `cd YOUR_PROJECT_REPO && cp .env.example .env`. I have no idea what that means. I think I'm copying your example environment file to my project environment file.  

2:05AM -- Now my .env file says PAYLOAD_SECRET=YOUR_SECRET_HERE.  Of course, I can't find "my secret" anywhere.  It doesn't say. 
Here's what my Payload Cloud instance looks like.  
<img width="1618" alt="Screenshot 2024-02-18 at 2 06 23 AM" src="https://github.com/payloadcms/payload/assets/5722/508f21a2-81e9-4d30-b2c8-ad6782f6f43c">

Okay, I installed the payload cloud plugin on local 
```
╭─mps@macSonoma ~/code/colearn/v02-payload-cloud/colearn-payload ‹main› 
╰─$ yarn add @payloadcms/plugin-cloud
info Direct dependencies
└─ @payloadcms/plugin-cloud@3.0.0
info All dependencies
└─ @payloadcms/plugin-cloud@3.0.0
✨  Done in 45.01s.
```
Let's see what happens. 

2:15AM I found your documentation for secret: 
https://payloadcms.com/docs/getting-started/installation#secret
It is, of course, at the beginning of the docs and not down where the Payload Cloud stuff is. 
To be honest, it makes less than zero sense. I read it and still have no idea if I am supposed to find my secret or just make one up. This matters.

2:19AM Okay, so I'm supposed to install legacy dependencies?  That sounds lazy on the Payload part. And create a server.ts file (um, why didn't you create that in my Payload Cloud instance?  I mean, I am going to pay you with a payload of a credit card transaction.) Your docs with code samples don't have the copy button on the upper right corner of the code block in your docs. That shit matters. 

And now I need to edit my PAYLOAD_SECRET -- still no idea what that is... what it should be... am I just writing a random password or something?  Some time ago I read about JWT, know what SHA-256 is. But, you spend more time telling me about that geekery than the important thing: is the PAYLOAD_SECRET a unique string I find on my Payload Cloud or am I just literally making it up like a password.  No idea. 

2:25AM you have a built in Pino logger. Good for you! I need to specify options for the Pino Logger. Need to go read Pino Docs. What?  I can't even read your Docs. Nothing is working, why would I go read more docs?  

2:26AM oh look!!!!  Now I can "test it out" https://payloadcms.com/docs/getting-started/installation#test-it-out
Does it say what commands I run to test it out on my local?  Nope. Gotta go dig again.  Hold on.  

2:30AM oh yay!  a bunch of error messages after running npm run build. 
```
╭─mps@macSonoma ~/code/colearn/v02-payload-cloud/colearn-payload ‹main●› 
╰─$ npm run build  

> template-blank@1.0.0 build
> yarn copyfiles && yarn build:payload && yarn build:server

yarn run v1.22.19
warning ../../../../package.json: No license field
$ copyfiles -u 1 "src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png}" dist/
✨  Done in 0.37s.
yarn run v1.22.19
warning ../../../../package.json: No license field
$ cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload build
assets by status 4.24 MiB [cached] 22 assets
Entrypoint main = styles.5ca2675644b251d3c90b.js styles.2f469d70da7bc7816241.css main.9f2d5805b6712f83c468.js 18 auxiliary assets
orphan modules 1.75 MiB [orphan] 897 modules
runtime modules 4.79 KiB 10 modules
javascript modules 9.32 MiB 1269 modules
css modules 235 KiB
  modules by path ./node_modules/payload/dist/admin/components/ 165 KiB 170 modules
  modules by path ./node_modules/@payloadcms/ 12.1 KiB 16 modules
  + 4 modules
json modules 451 KiB
  ./node_modules/payload/dist/translations/ar.json 14.8 KiB [built] [code generated]
  ./node_modules/payload/dist/translations/az.json 15.5 KiB [built] [code generated]
  ./node_modules/payload/dist/translations/bg.json 15.4 KiB [built] [code generated]
  + 27 modules
asset modules 84 bytes (javascript) 4.37 KiB (asset)
  ./node_modules/payload/dist/admin/assets/images/favicon.svg 42 bytes (javascript) 437 bytes (asset) [built] [code generated]
  ./node_modules/payload/dist/admin/assets/images/og-image.png 42 bytes (javascript) 3.94 KiB (asset) [built] [code generated]

WARNING in ./node_modules/@payloadcms/db-mongodb/dist/createMigration.js 46:33-51
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@payloadcms/db-mongodb/dist/index.js 18:25-53
 @ ./src/payload.config.ts 3:0-57 27:8-23
 @ ./node_modules/payload/dist/admin/Root.js
 @ ./node_modules/payload/dist/admin/index.js 9:53-70

WARNING in ./node_modules/payload/dist/database/migrations/readMigrationFiles.js 35:26-43
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/payload/database.js 223:28-84
 @ ./node_modules/@payloadcms/db-mongodb/dist/index.js 13:18-45
 @ ./src/payload.config.ts 3:0-57 27:8-23
 @ ./node_modules/payload/dist/admin/Root.js
 @ ./node_modules/payload/dist/admin/index.js 9:53-70

2 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./node_modules/@payloadcms/db-mongodb/dist/createMigration.js 11:51-64
Module not found: Error: Can't resolve 'fs' in '/Users/mps/code/colearn/v02-payload-cloud/colearn-payload/node_modules/@payloadcms/db-mongodb/dist'
 @ ./node_modules/@payloadcms/db-mongodb/dist/index.js 18:25-53
 @ ./src/payload.config.ts 3:0-57 27:8-23
 @ ./node_modules/payload/dist/admin/Root.js
 @ ./node_modules/payload/dist/admin/index.js 9:53-70

ERROR in ./node_modules/payload/dist/database/migrations/createMigration.js 11:51-64
Module not found: Error: Can't resolve 'fs' in '/Users/mps/code/colearn/v02-payload-cloud/colearn-payload/node_modules/payload/dist/database/migrations'
 @ ./node_modules/payload/database.js 214:25-78
 @ ./node_modules/@payloadcms/db-mongodb/dist/index.js 13:18-45
 @ ./src/payload.config.ts 3:0-57 27:8-23
 @ ./node_modules/payload/dist/admin/Root.js
 @ ./node_modules/payload/dist/admin/index.js 9:53-70

ERROR in ./node_modules/payload/dist/database/migrations/readMigrationFiles.js 11:51-64
Module not found: Error: Can't resolve 'fs' in '/Users/mps/code/colearn/v02-payload-cloud/colearn-payload/node_modules/payload/dist/database/migrations'
 @ ./node_modules/payload/database.js 223:28-84
 @ ./node_modules/@payloadcms/db-mongodb/dist/index.js 13:18-45
 @ ./src/payload.config.ts 3:0-57 27:8-23
 @ ./node_modules/payload/dist/admin/Root.js
 @ ./node_modules/payload/dist/admin/index.js 9:53-70

ERROR in ./node_modules/prompts/dist/elements/prompt.js 3:17-36
Module not found: Error: Can't resolve 'readline' in '/Users/mps/code/colearn/v02-payload-cloud/colearn-payload/node_modules/prompts/dist/elements'
 @ ./node_modules/prompts/dist/elements/text.js 9:15-34
 @ ./node_modules/prompts/dist/elements/index.js 4:14-31
 @ ./node_modules/prompts/dist/prompts.js 5:11-32
 @ ./node_modules/prompts/dist/index.js 19:16-36
 @ ./node_modules/prompts/index.js 13:6-32
 @ ./node_modules/@payloadcms/db-mongodb/dist/migrateFresh.js 12:56-74
 @ ./node_modules/@payloadcms/db-mongodb/dist/index.js 32:22-47
 @ ./src/payload.config.ts 3:0-57 27:8-23
 @ ./node_modules/payload/dist/admin/Root.js
 @ ./node_modules/payload/dist/admin/index.js 9:53-70

ERROR in ./node_modules/prompts/lib/elements/prompt.js 3:17-36
Module not found: Error: Can't resolve 'readline' in '/Users/mps/code/colearn/v02-payload-cloud/colearn-payload/node_modules/prompts/lib/elements'
 @ ./node_modules/prompts/lib/elements/text.js 2:15-34
 @ ./node_modules/prompts/lib/elements/index.js 4:14-31
 @ ./node_modules/prompts/lib/prompts.js 3:11-32
 @ ./node_modules/prompts/lib/index.js 3:16-36
 @ ./node_modules/prompts/index.js 14:6-31
 @ ./node_modules/@payloadcms/db-mongodb/dist/migrateFresh.js 12:56-74
 @ ./node_modules/@payloadcms/db-mongodb/dist/index.js 32:22-47
 @ ./src/payload.config.ts 3:0-57 27:8-23
 @ ./node_modules/payload/dist/admin/Root.js
 @ ./node_modules/payload/dist/admin/index.js 9:53-70

5 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.88.2 compiled with 5 errors and 2 warnings in 15095 ms
✨  Done in 18.63s.
yarn run v1.22.19
warning ../../../../package.json: No license field
$ tsc
✨  Done in 2.45s.
```

2:33AM I thought the Internet agreed we are no longer using Webpack, we are using Vite. Did I get that wrong?  
Okay, so, ran npm run serve...  And... You guessed it!  Errors!

```
╭─mps@macSonoma ~/code/colearn/v02-payload-cloud/colearn-payload ‹main●› 
╰─$ npm run serve        

> template-blank@1.0.0 serve
> cross-env PAYLOAD_CONFIG_PATH=dist/payload.config.js NODE_ENV=production node dist/server.js

[02:32:34] ERROR (payload): Error: cannot connect to MongoDB. Details: connect ECONNREFUSED 127.0.0.1:27017
```

2:35AM reinstalled latest mongodb with npm

```
╭─mps@macSonoma ~/code/colearn/v02-payload-cloud/colearn-payload ‹main●› 
╰─$ npm install mongodb                                                                                                              1 ↵

added 7 packages, changed 6 packages, and audited 1045 packages in 10s

202 packages are looking for funding
  run `npm fund` for details

11 vulnerabilities (9 moderate, 2 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

_**And nope, still got an error.**_

```
╭─mps@macSonoma ~/code/colearn/v02-payload-cloud/colearn-payload ‹main●› 
╰─$ npm run serve      

> template-blank@1.0.0 serve
> cross-env PAYLOAD_CONFIG_PATH=dist/payload.config.js NODE_ENV=production node dist/server.js

[02:35:55] ERROR (payload): Error: cannot connect to MongoDB. Details: connect ECONNREFUSED 127.0.0.1:27017
```

## Additional Details

I hope I'm conveying how infuriating it is to try to create a deployed instance of Payload where I can edit the Content Model.  This is less than fun.  I know I'm doing this at 2AM, but I tried yesterday as well.  I just didn't try to rant then.  I tried to get Strapi running for about 5 hours in the evening, same problems. 

Please: move the Beginner stuff to the top.  Go step by step.  Your documentation writers need to be paired with "know nothings" -- make it so a 5 year old could understand it, as the saying goes. Your documentation needs to be explicit and baby step by step even through obvious stuff to experienced devs -- experienced devs know how to skip content they don't need, n00bs don't know what they don't know. Stuff n00bs need, for instance: what the directory tree looks like at every step, in what file are you suggesting to add some code snippet, where in the file to put said code snippet,  and why? etc. 

If you're, say, a CEO or CMO or just a hustler that wants to use a CMS, your documentation is negative value.  **If your revenue model is that you think less technical people will pay for Payload Cloud -- you are right but you are also stepping on your own shoes.**  I would pay you WAY MORE RIGHT NOW just to have something working (doesn't mean I would pay way more on a monthly basis.) 

You need to make it WAY easier to engage and get started. Have your management re-read The Innovator's Dilemma. I shall give you the Cliff Notes of the Blinkest: you win on "expanding the market." 

I really want a great headless CMS. I really love the brand promise of Payload. But I've failed on getting it running with local with Postgres, I've failed on deploying to Vercel, and I've now failed on deploying to your own Payload Cloud.  And based on your founder's YouTube presentations and your branding and marketing, I had Payload at the top of my list.

Help or don't.  I don't care at 2:54AM.  But whatever your priorities are, shift them.  Expand the market. Make it so that numskulls like me can get started. 

Mic Drop.   

Design and document for dummies, please.

**Comment by denolfe** [comment]
Thank you for the feedback. Sorry you've found the experience frustrating. It sounds like you jumped in a bit too deep, too fast. Modifying your Payload Collections is done in the Payload config via code as detailed in the [Getting Started -> Payload Concepts](https://payloadcms.com/docs/getting-started/concepts) section of the documentation. It feels like this is pretty straight-forward and at the very top of the documentation.

Payload is a dev-first framework, and it does assume you have a bit of knowledge regarding Node, web development, etc. We try to make this as approachable as possible, but it sounds like we have some work to do to handhold users with experience different than our own.
