### ISSUE TITLE
Checkbox field error message covers checkbox

### ISSUE THREAD

**Issue by wbjohn** [payloadcms/payload#511]
# Bug Report

When a Checkbox field is required and has no default value, the error message "This field can only be equal to true or false." is displayed, covering up the input field itself and forcing the user to reload to continue creating a new document.

## Expected Behavior

Checkbox error message should be displayed above field.

## Current Behavior

Checkbox error message covers the field.

## Possible Solution

Override tooltip styles in Checkbox stylesheet eg:
`
  .tooltip {
    position: relative;
    right: auto;
    margin-bottom: .2em;
    max-width: fit-content;
  }
`

Alternatively, Checkbox defaultValue could be false by default or defaultValue could be a required option for Checkbox fields. This prevents the unnatural scenario where a user has to check a checkbox and then uncheck it to get a false value. 

## Steps to Reproduce
1. Set a Checkbox field to required
2. Create a new document and save without filling any fields

## Detailed Description

Payload version 0.15.1
Occurs in Chrome and Edge browsers

**Comment by jmikrut** [comment]
Good find @wbjohn — we'll get a fix out ASAP.

**Comment by DanRibbens** [comment]
Super big thanks for the solutions @wbjohn! I made changes to help with both problems you identified and I'd like to discuss the solution in the PR https://github.com/payloadcms/payload/pull/521 if you have any thoughts.
