### ISSUE TITLE
Documentation does not explain how to change payload-token cookie options

### ISSUE THREAD

**Issue by dhiegomaga** [payloadcms/payload#5111]
# Documentation Issue

When the frontend and backend URLs differ, and one wants to use the `payload-token` cookie for authentication, the cookie should be set using `sameSite: None; secure`. However, the documentation does not explain how to do that, if that is even possible. 

If that is not possible, this would be a feature request.

**Comment by jmikrut** [comment]
Hey @dhiegomaga — you can set these options in your config's `auth` property:

https://payloadcms.com/docs/authentication/config#options

You have control over `sameSite` and `secure` among other options. Take a look at that! In the future, we will do a video that focuses solely on how to use cookies effectively in misc. domain scenarios.
