### ISSUE TITLE
Uploads failing with "MissingFile: No files were uploaded" error.

### ISSUE THREAD

**Issue by zazz-ops** [payloadcms/payload#5118]
### Describe the Bug

I'm attempting to upload files via the RESTful API from within my `mocha` tests and no matter how I configure the `fetch` request to the create (`POST`) endpoint of my `media` collection I get the same error: `MissingFile: No files were uploaded`.

However I am very much providing the file in accordance with the "instructions" from the docs [here](https://payloadcms.com/docs/upload/overview) and from what I can glean from the tutorial [here](https://muffinman.io/blog/uploading-files-using-fetch-multipart-form-data/).

### To Reproduce

Here's what my test looks like in `mocha`:
<img width="702" alt="image" src="https://github.com/payloadcms/payload/assets/151117554/d88b1293-ae1b-40cb-8ce1-1a7df345571b">

Here's what the `console.log` results are when I log the `file` and `formData`:
<img width="707" alt="image" src="https://github.com/payloadcms/payload/assets/151117554/bfc385b0-5986-4a3b-a35a-1a442778186f">

And here's the result I get no matter what `Content-Type` I provide, no matter whether I use a `Blob` or a `Buffer` or format the `body` (called `data` in my `nova` sugar wrapper) to be `formData`:
<img width="1381" alt="image" src="https://github.com/payloadcms/payload/assets/151117554/d5dacc11-a752-4e61-9abf-05fd8a5dabd0">

How do I upload a file using the REST api in node.js/TypeScript?

I have to say, the more I use Payload the less I like it. The documentation is severely lacking and is wasting an enormous amount of my time to evaluate even the simplest of CMS functionalities, and the error-handling is Mickey Mouse at best. When can we expect Payload to be production-ready?

### Payload Version

2.8.1

**Comment by zazz-ops** [comment]
I found the "solution" to this ... similar to uploading in the browser, you need to explicitly remove the `Content-Type` header from you request before sending it.

This is contrary to what is stated in the docs:
<img width="750" alt="image" src="https://github.com/payloadcms/payload/assets/151117554/8a804cfa-0e6a-46b9-95bb-95ba39a8e31a">

Seems like the docs need to be corrected to state that a `Content-Type multipart/formdata` header should _not_ be included in your request at all.

Additionally, Payload's error messaging needs to be greatly improved. The error message "No files were uploaded" is uselessly vague. Especially considering that the issue had nothing to the do with the file being uploaded.

**Comment by iamacup** [comment]
in case anyone else comes across this - here is code i used to upload files to payload when you also have values on the collection that you need to be recorded - not just the file.

```
    const form = new FormData();
    const file = Bun.file(filePath);
    form.append("file", file);

    // OK so this is an undocumented feature i found after i pulled all my hair out
    // the below commented out assignments of the form.append for all values in the
    // body data works apart from for complex objects which just completely fuck up
    // so hopefully this carries on working i guess?
    form.append("_payload", JSON.stringify(bodyData));

    // Object.keys(bodyData).forEach((key) => {
    //   if (typeof bodyData[key] === "object" && bodyData[key] !== null) {
    //     form.append(key, JSON.stringify(bodyData[key]));
    //   } else {
    //     form.append(key, bodyData[key]);
    //   }
    // });

    const options = {
      method: "POST",
      body: form,
      headers: {
        Authorization: `JWT ${await getAuthToken()}`,
      },
    };

    const response = await fetch(url, options);
```
