### ISSUE TITLE
Json field with mongo disorder of keys

### ISSUE THREAD

**Issue by EvilaMany** [payloadcms/payload#5119]
### Describe the Bug

I have JSON field with almost no config. When I insert some to json to it and press SAVE it changes order to some mess. It's even not alphabetic order
Why and how to fix it?

### To Reproduce

I have JSON field with almost no config. When I insert some to json to it and press SAVE it changes order to some mess. It's even not alphabetic order
Why and how to fix it?
(if I set type of field as textarea there are no such a problem, but It's not comfortable to edit it without monaco editor)
### Payload Version

2.11.0

### Adapters and Plugins

mongodb as database and nothing other

**Comment by EvilaMany** [comment]
Probably the reason may be mongodb reordering object. But how can I force payload to serialize \ deserialize object to string before saving?

**Comment by denolfe** [comment]
JSON [written to spec](https://www.json.org/json-en.html) is an _unordered_ object and is stored as such with both MongoDB and Postgres. There is not a way currently to maintain the order of the JSON. You have a few options if you still want to go down this path:

1. Utilize the 'code' field with the admin syntax set to 'json'
2. Use a code block inside of a rich text field
3. Implement an `afterRead` hook on the field that will order the keys how you want. Note that this will not be able to take into account the original ordering that was entered.
