### ISSUE TITLE
GraphQL query with `draft: false` parameter returns draft data

### ISSUE THREAD

**Issue by ikenox** [payloadcms/payload#5142]
### Link to reproduction

https://github.com/ikenox/payload/tree/query-with-draft-false-returns-draft-data

### Describe the Bug

A result of GraphQL query with `draft:true` contains draft data that has never been published yet.

### To Reproduce

I created minimum reproducible example: https://github.com/ikenox/payload/tree/query-with-draft-false-returns-draft-data

1. start server

```
pnpm dev _community
```

2. open http://localhost:3000 to establish login session

3. open http://localhost:3000/api/graphql-playground and query this

```graphql
query {
  Posts(draft: false) {
    docs {
      id
      _status
    }
  }
}
```

4. The result contains draft data

```json
{
  "data": {
    "Posts": {
      "docs": [
        {
          "id": "65d5f181490649d779b1a4a1",
          "_status": "draft"
        }
      ]
    }
  }
}
```

### Payload Version

2.11.1

### Adapters and Plugins

db-postgres

**Comment by PatrikKozak** [comment]
Hey @ikenox - so basically the `draft` argument alone does not restrict who can see drafts. 

If you need that, you need to do that with access control. The `draft` arg simply does what is stated [here](https://payloadcms.com/docs/versions/drafts#controlling-who-can-see-collection-drafts) in the docs. We have a discussion on this that goes into more detail here:

[https://github.com/payloadcms/payload/discussions/1569](https://github.com/payloadcms/payload/discussions/1569)

Going to close this but let me know if you have any other questions!
