### ISSUE TITLE
filterOptions doesn't work on block fields

### ISSUE THREAD

**Issue by 60pfennig** [payloadcms/payload#5150]
### Describe the Bug

Where queries for filterOptions in a relationship field doesn't filter anything if the filter target is an array (blocks) attribute in an document. If I'm using the same where query in a find function, it filters as expected.

### To Reproduce

In a relationship field to a block containing collection add a filterOption which queries for a field in the block:
```typescript
filterOptions: {
      'blocks.0.number': {
        equals: 1
      }
    }
```
The won't be any options available eaven if the field number has the value 1. If you use the exact same query in a find funtion for the same collection it will return every entries as expected. Same for filterOptions for non block fields. Filtering for a top level title field for example works well.

### Payload Version

2.10

### Adapters and Plugins

db-mongodb, bundler-webpack

**Comment by WillFelisberto** [comment]
I have the same problem here

**Comment by georgecartridge** [comment]
I'm also having the same issue.

I have a relationship field within a block, and I'm trying to use `filterOptions` to filter the available documents. The filtering works fine when the relationship field is not inside a block, but it doesn't seem to function as expected when it's part of a block.

Here's a simplified example of what I'm trying to achieve:

```typescript
const MainCollection: CollectionConfig = {
  slug: 'main-collection',
  fields: [
    // other fields...
    {
      name: 'itemsList',
      type: 'blocks',
      blocks: [
        {
          slug: 'relatedItem',
          fields: [
            {
              name: 'item',
              type: 'relationship',
              relationTo: 'related-items',
              filterOptions: ({ data }) => {
                // this filtering doesn't work as expected when in a block
                if (data.selectedItems && data.selectedItems.length > 0) {
                  return {
                    id: {
                      in: data.selectedItems.map(item => item.value)
                    }
                  };
                }
                
                return false;
              },
            },
          ],
        },
        // other blocks...
      ],
    },
  ],
};
```

In the above I'm trying to filter the available `related-items` based on a `selectedItems` field that exists. This works fine when not in a block, but doesn't function in the block structure.

**Comment by DanRibbens** [comment]
This was reported as an issue on v3, reopening so we can better track it.

**Comment by paulpopus** [comment]
`filterOptions` is now supported on blocks as per this PR https://github.com/payloadcms/payload/pull/13801
