### ISSUE TITLE
Postgres: Sorting on localized fields returns wrong order

### ISSUE THREAD

**Issue by Janisvb** [payloadcms/payload#5152]
### Link to reproduction

https://github.com/Janisvb/payload-reproduction/tree/localized-sort

### Describe the Bug

When sorting on a localized field, the order of the returned elements is not correct

### To Reproduce

`yarn dev:postgres _community`

1. Sort by non-localized field (correct)
http://localhost:3000/api/posts?sort=text

2. Sort by localized field (wrong order)
http://localhost:3000/api/posts?sort=text_localized

### Payload Version

2.11.1

### Adapters and Plugins

db-postgres

**Comment by r1tsuu** [comment]
Fixed, I'll also port it to 2.0
