### ISSUE TITLE
Postgres: Filtering on select and text with hasMany:true not working

### ISSUE THREAD

**Issue by Janisvb** [payloadcms/payload#5153]
### Link to reproduction

https://github.com/Janisvb/payload-reproduction/tree/filtering

### Describe the Bug

Filtering on a select- or text-field with hasMany:true is not working with Postgres.

### To Reproduce

`yarn dev:postgres _community`

1. Equals filter on select-field with hasMany: false (correct)
http://localhost:3000/api/posts?where[type][equals]=post

2. Equals-filter on select-field or text-field with hasMany: true (error)
http://localhost:3000/api/posts?where[categories][equals]=ts or http://localhost:3000/api/posts?where[categories_text][equals]=ts
` ERROR (payload): error: syntax error at or near "="`

3. In-filter on select-field or text-field with hasMany: true (error)
http://localhost:3000/api/posts?where[categories][in]=js,ts or http://localhost:3000/api/posts?where[categories_text][in]=js,ts
`ERROR (payload): error: syntax error at or near "in"`

3. All-filter on select-field or text-field with hasMany: true (not supported)
http://localhost:3000/api/posts?where[categories][all]=js,ts or http://localhost:3000/api/posts?where[categories_text][all]=js,ts
`ERROR (payload): TypeError: _operatorMap.operatorMap[queryOperator] is not a function`

It is working as expected with MongoDB.

### Payload Version

2.11.1

### Adapters and Plugins

db-postgres

**Comment by PatrikKozak** [comment]
Hey @Janisvb - thanks for reporting this! The above has been fixed with these two PRs:

- https://github.com/payloadcms/payload/pull/5881
- https://github.com/payloadcms/payload/pull/5885
