### ISSUE TITLE
db-postgres: hasMany select field value of versioned collection is associated with wrong version on publish

### ISSUE THREAD

**Issue by ikenox** [payloadcms/payload#5157]
### Link to reproduction

https://github.com/ikenox/payload/tree/hasmany-select-field-value-is-upserted-into-wrong-version

### Describe the Bug

On a collection with `versions: { drafts: true }` config, hasMany select field value is associated with the wrong version on publish.

1. Save a draft with an empty select field
    <img width="960" alt="image" src="https://github.com/payloadcms/payload/assets/7638989/dfb8218b-7531-495c-badf-c56c2977252e">

2. Update the draft with an empty select field
    <img width="942" alt="image" src="https://github.com/payloadcms/payload/assets/7638989/013cb8ef-a99b-4225-ab9d-87a2b2bd9667">

3. Fill select field (`tag1` here) and publish data
    <img width="948" alt="image" src="https://github.com/payloadcms/payload/assets/7638989/285686c8-b16b-4187-bcf3-9eab53f777c9">

4. The tag is associated with the first draft version wrongly
    <img width="964" alt="image" src="https://github.com/payloadcms/payload/assets/7638989/f540bede-7224-41ee-aae6-314b1f403e50">

I found that selected tags are inserted into `_posts_v_version_tag` with `id=1`.
This `id=1` comes from the `posts` table. It should not be used to insert 
 into `_posts_v_version_tag` table. Instead, an id of the newly created version on `_posts_v` table should be used.

### To Reproduce

I added a [failing test](https://github.com/ikenox/payload/blob/hasmany-select-field-value-is-upserted-into-wrong-version/test/_community/int.spec.ts#L42-L76). This test case should be passed.

### Payload Version

2.11

### Adapters and Plugins

db-postgres

**Comment by ikenox** [comment]
This id should be the newly created version's id.

https://github.com/payloadcms/payload/blob/32ed95e/packages/db-postgres/src/transform/write/selects.ts#L15-L19

**Comment by DanRibbens** [comment]
I'm fairly certain this was fixed when we introduced UUID which made this issue very apparant. Closing this for now. Please tag me if you believe this hasn't been fixed and we will revisit.

**Comment by ikenox** [comment]
@DanRibbens 
I've confirmed that the problem has been fixed on the latest payload version. Thanks!
