### ISSUE TITLE
graphql: upload in lexical block not populated

### ISSUE THREAD

**Issue by carstenblt** [payloadcms/payload#5162]
### Link to reproduction

https://github.com/carstenblt/payload/tree/reproduction-block-population

### Describe the Bug

When creating a Block with an upload and using it in a lexical richtText field the upload field will not be populated in a graphql query:

```
{
              "format": "",
              "type": "block",
              "version": 2,
              "fields": {
                "id": "65d9c4591687b6a745d0803c",
                "blockName": "",
                "blockType": "Image",
                "image": "65d9c4669fa30fc6d6503002"
              }
```

The REST api will however return a populated result

May be related to #5051 

### To Reproduce

Create a block with upload:
```
export const TestBlock: Block = {
  slug: 'Image',
  fields: [
    {
      name: 'image',
      type: 'upload',
      relationTo: 'media',
      required: true,
      filterOptions: {
        mimeType: { contains: 'image' },
      },
    },
  ],
}
```

and using it in a lexical richtText field:

```
{
      name: 'test',
      type: 'richText',
      editor: lexicalEditor({
        features: ({ defaultFeatures }) => [
          ...defaultFeatures,
          BlocksFeature({
            blocks: [TestBlock],
          }),
        ],
      }),
    }
```

Create a doc and query it using graphql and rest.

### Payload Version

2.11.1

**Comment by AlessioGr** [comment]
Good news! Just tried to reproduce this in the latest 3.0 beta and it looks like this has been solved! Images within blocks within lexical are being populated properly

![CleanShot 2024-05-29 at 12 23 31@2x](https://github.com/payloadcms/payload/assets/70709113/2325d845-d16b-4148-ac7d-55144041eda6)

![CleanShot 2024-05-29 at 12 23 04@2x](https://github.com/payloadcms/payload/assets/70709113/df222daf-7a1e-47ba-9b8b-2d6c53cf2abd)
