### ISSUE TITLE
plugin-search: excerpt

### ISSUE THREAD

**Issue by Barklim** [payloadcms/payload#5173]
### Describe the Bug

    beforeSync: ({ originalDoc, searchDoc }) => ({
          ...searchDoc,
          // Modify your docs in any way here, this can be async
          excerpt: originalDoc?.excerpt || 'This is a fallback excerpt',
    }),

The plugin documentation describes a way to add an excerpt to a search collection instance. However, for some reason this method does not work. Tell me, is any additional data needed to describe the context?

      beforeSync: function({ originalDoc, searchDoc }) {
        const newDoc = searchDoc.doc;
        newDoc.link = 'some link'

        return {
          ...searchDoc,
          doc: newDoc,
          // this field don't updated in search collection
          link: originalDoc?.link || 'some link',
        };
      },

Now, to implement the search, I am forced to enter additional search fields into the doc object. I think it's better to try to solve the problem.

upd.

I'm think that i'm find solution. 😄
If you encounter a similar problem, then look at what you need to do. 
You need to add the field you need in the plugin settings (some "excerpt" field, for example isPublished).

      searchOverrides: {
        fields: [
          {
            name: 'isPublished',
            type: 'checkbox',
            label: 'Опубликовано',
            admin: { readOnly: true, },
            defaultValue: false,
          },
        ],
      },
      
and then you can manipulate this field via a hook beforeSync.

      beforeSync: ({ originalDoc, searchDoc }) => ({
        ...searchDoc,
        isPublished: originalDoc?.isPublished || false,
      }),

### To Reproduce

@payloadcms/plugin-search version is 1.1.0

Dependencies:

"@payloadcms/bundler-webpack": "^1.0.6",
"@payloadcms/db-mongodb": "^1.3.2",
"@payloadcms/plugin-cloud-storage": "1.0.19",
"@payloadcms/plugin-relationship-object-ids": "^0.0.4",
"@payloadcms/richtext-slate": "^1.3.1",

### Payload Version

2.8.2

**Comment by GermanJablo** [comment]
I'm glad you were able to resolve it and thanks for sharing the solution.

This could have been made clearer in the documentation, so I've created a PR to make it so: https://github.com/payloadcms/payload/pull/8946
