### ISSUE TITLE
Dark Button on footer background color

### ISSUE THREAD

**Issue by hamzamaqbool22** [payloadcms/payload#5180]
### Describe the Bug

The button background color and text color is white of Dark button and on hover the text color is set to black but it shold already be black without so the user can see 

### To Reproduce

Just change the text-white to text-black of dark mode button 

### Payload Version

latest may be

### Adapters and Plugins

db-mongodb

**Comment by PatrikKozak** [comment]
Hey @hamzamaqbool22 - thanks for the report. We need a bit more detail to understand this issue. Going to close this for now but I'll be happy to reopen it if more information or a reproducible example is provided. Thanks again!
