### ISSUE TITLE
Custom*ButtonComponent type mistakenly named as Custom*ButtonProps

### ISSUE THREAD

**Issue by franciscolourenco** [payloadcms/payload#5183]
# Type naming issue

While [DefaultPublishButtonProps](https://github.com/payloadcms/payload/blob/e9f550406ef1fe73d200b8c797212f1d8def7cbb/packages/payload/src/admin/components/elements/Publish/index.tsx#L17) is correctly named as props, [CustomPublishButtonProps](https://github.com/payloadcms/payload/blob/e9f550406ef1fe73d200b8c797212f1d8def7cbb/packages/payload/src/admin/components/elements/Publish/index.tsx#L12) is actually a component and shouldn't be named as Props. Maybe it should be named `CustomPublishButton` or `CustomPublishButtonComponent`?

All custom buttons are affected and this issue is reflected in the [docs](https://payloadcms.com/docs/admin/components#collections):

```typescript
import * as React from 'react'

import {
  CustomSaveButtonProps,
  CustomSaveDraftButtonProps,
  CustomPublishButtonProps,
  CustomPreviewButtonProps,
} from 'payload/types'

export const CustomSaveButton: CustomSaveButtonProps = ({ DefaultButton, label, save }) => {
  return <DefaultButton label={label} save={save} />
}

export const CustomSaveDraftButton: CustomSaveDraftButtonProps = ({
  DefaultButton,
  disabled,
  label,
  saveDraft,
}) => {
  return <DefaultButton label={label} disabled={disabled} saveDraft={saveDraft} />
}

export const CustomPublishButton: CustomPublishButtonProps = ({
  DefaultButton,
  disabled,
  label,
  publish,
}) => {
  return <DefaultButton label={label} disabled={disabled} publish={publish} />
}

export const CustomPreviewButton: CustomPreviewButtonProps = ({
  DefaultButton,
  disabled,
  label,
  preview,
}) => {
  return <DefaultButton label={label} disabled={disabled} preview={preview} />
}

export const MyCollection: SanitizedCollectionConfig = {
  slug: 'my-collection',
  admin: {
    components: {
      edit: {
        SaveButton: CustomSaveButton,
        SaveDraftButton: CustomSaveDraftButton,
        PublishButton: CustomPublishButton,
        PreviewButton: CustomPreviewButton,
      },
    },
  }
}```

## Additional Details

<!--- Provide any other additional details -->

**Comment by PatrikKozak** [comment]
Hey @franciscolourenco - thanks so much for taking the time to share your thoughts regarding our naming convention.

Regarding the suggestion to rename `CustomPublishButtonProps` - in our current setup, we use the suffix `Props` to specifically denote types or interfaces that define the properties a React component expects. This convention helps us distinguish between the components themselves and the types of their props.

So, `CustomPublishButtonProps` is intended to describe the shape of the props for a custom component, indicating that it is not a component but a type definition for the props that such a component would receive. 

Does this make sense? 

Really appreciate your feedback and always open to discussing our practices and exploring improvements.

**Comment by franciscolourenco** [comment]
Hi @PatrikKozak that makes sense, and the convention is perfect. The problem is that while `CustomPublishButtonProps` is _intended_ to describe the shape of the props for a custom component, in this case it is actually being used to _describe the component itself_.

```typescript
export type CustomPublishButtonProps = React.ComponentType
```

**Comment by PatrikKozak** [comment]
@franciscolourenco Ah yup I see what you're saying. `CustomPublishButtonProps` is actually a type for a component - not just props. 

I'm thinking a better name might be `CustomPublishButtonType` then, what do you think?

I'll relay this to the rest of the team and get back to you on this, thanks for bringing this up!
