### ISSUE TITLE
Postgres ValidationError w/ Unique constraints not including the field name

### ISSUE THREAD

**Issue by fr3fou** [payloadcms/payload#5207]
### Link to reproduction

https://github.com/fr3fou/payload-bug

### Describe the Bug

Creating an object in a collection with unique fields results in an incorrect error returned to the user when there're duplicate values. 

Expected:
```console
λ curl localhost:3000/api/users -X POST --json '{"email":"1234@1234.com", "password":"1234", "username": "1234"}' --silent | jq
```
```json
{
  "errors": [
    {
      "name": "ValidationError",
      "data": [
        {
          "field": "username",
          "message": "A user with the given username is already registered"
        }
      ],
      "message": "The following field is invalid: username"
    }
  ]
}
```

Actual:
```console
λ curl localhost:3000/api/users -X POST --json '{"email":"1234@1234.com", "password":"1234", "username": "1234"}' --silent | jq
```
```json
{
  "errors": [
    {
      "name": "ValidationError",
      "data": [
        {
          "message": "Value must be unique"
        }
      ],
      "message": "The following field is invalid: "
    }
  ]
}
```

Interestingly enough, Payload will return the correct error if the email is duplicate:

```console
λ curl localhost:3000/api/users -X POST --json '{"email":"existing-email@1234.com", "password":"1234", "username": "1234"}' --silent | jq
```
```json
{
  "errors": [
    {
      "name": "ValidationError",
      "data": [
        {
          "field": "email",
          "message": "A user with the given email is already registered"
        }
      ],
      "message": "The following field is invalid: email"
    }
  ]
}
```
I'm guessing this is because the `email` field is handled separately:

https://github.com/payloadcms/payload/blob/8104fac5ed3f35595c607cc32d5fb2af5609ca60/packages/payload/src/auth/strategies/local/register.ts#L33-L37

I haven't dug deeper into the `db-postgres` source code but I'm suspecting it's something related to this:

https://github.com/payloadcms/payload/blob/8104fac5ed3f35595c607cc32d5fb2af5609ca60/packages/db-postgres/src/upsertRow/index.ts#L313-L324

My first guess is that the `adapter.fieldConstraints` object is empty or the table lookup is incorrect.

A separate issue that I noticed while creating the reproduction example is that the CLI didn't generate the correct docker-compose for this project. I explicitly selected Postgres as the database and the generated docker-compose included MongoDB instead.

![image](https://github.com/payloadcms/payload/assets/1344906/3f7a4af4-7687-4e43-b6f9-05552a44895d)

The .env.example also included the wrong environment variable: 
`DATABASE_URI=mongodb://127.0.0.1/payload-template-blank`

### To Reproduce

1. Clone the Repo
2. Install dependencies
3. Use the following .env
```env
DATABASE_URI=postgres://postgres:bug@127.0.0.1:5432/bug
PAYLOAD_SECRET=52291754a160e027da63ac76
```
4. Run `docker compose up`
5. Run `yarn dev`
6. Create a user:
```console
λ curl localhost:3000/api/users -X POST --json '{"email":"1234@1234.com", "password":"1234", "username": "1234"}' --silent | jq
```
7. Create another user with the same username but a different email:
```console
λ curl localhost:3000/api/users -X POST --json '{"email":"other-email@1234.com", "password":"1234", "username": "1234"}' --silent | jq
```
The returned error won't include the duplicate field name.

### Payload Version

^2.0.0

### Adapters and Plugins

db-postgres

**Comment by henrik-d** [comment]
I think, i have the same issue. The error response does not contain the field name.
```
{
    "errors": [
        {
            "name": "ValidationError",
            "data": {
                "errors": [
                    {
                        "message": "Value must be unique"
                    }
                ]
            },
            "message": "The following field is invalid: "
        }
    ]
}
```

This is my field config:
```
{
    name: "slug",
    type: "text",
    required: true,
    label: "Slug",
    unique: true,
    validate: (value: string) =>
      /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value)
        ? true
        : "Der Slug darf nur Kleinbuchstaben, Zahlen und Bindestriche enthalten",
    admin: {
      placeholder: "z.B. my-slug",
    },
  }
```

I'm using payload 3.0.0-beta.65 and Postgres.

**Comment by chinmay-mehta** [comment]
We are facing the same issue using postgres.

**Comment by TomDo1234** [comment]
On 2.26 , Im not even getting a validation error at all, im just getting "Something went wrong"

**Comment by paulpopus** [comment]
Hey all, this will be fixed on the next beta release. It will display as best it can the right field name and the exact error. We will continue to improve validation here in the future
