### ISSUE TITLE
The "not_equals" doesn't return expected results when comparing relationship ID's

### ISSUE THREAD

**Issue by paper-krane** [payloadcms/payload#5212]
### Describe the Bug

When searching both inside the Payload dashboard using the built in Filter, and externally via rest API, the 'not_equals' operator almost acts as if there isn't a query at all. This issues **SPECIFICALLY applies to 'relationship' fields**. For example, I have a doc that references a user. When querying that document by looking up to see if the user's ID is 'not_equals' to xxxxxx, the result still returns the non-equaled result. I have tested in a few Payload instances, and the result was all the same.

Everything else is working beautifully of course. Love Payload and how much it has streamlined my workflow!

### To Reproduce

1. Create 2 collections, one of which has a 'relationship' field that references the other collection. In my current use case / example I have form-submissions with a relationship field of submittedBy that references a Users collection.
2. Create a form-submission referencing a user.
3. In the document list, filter all form-submissions where the submittedBy is 'not_equals' to the user's ID
4. Results will include the non-desired User's ID

### Payload Version

2.11.2

### Adapters and Plugins

db-mongodb, bundler-webpack, @payloadcms/richtext-lexical

**Comment by ssyberg** [comment]
I also seem to be experiencing this!

**Comment by RickGeersing** [comment]
Any update on this? I am experiencing the same.

**Comment by PatrikKozak** [comment]
Hey @paper-krane - thank you for your patience here - can you confirm for me if this is still an issue on latest?

Thank you!

If you are still experiencing it, I will be looking into this

**Comment by paper-krane** [comment]
@PatrikKozak , I am using version 2.25 of Payload and doesn't equal still isn't functioning as expected. Haven't tested on v3 yet.

**Comment by PatrikKozak** [comment]
@paper-krane Can you please provide a reproducible repo for me or your config?
