### ISSUE TITLE
Relationship field: Search causes error when minus (`-`) prefix used in `defaultSort` and/or `sortOptions`

### ISSUE THREAD

**Issue by BrianJM** [payloadcms/payload#5222]
### Link to reproduction

https://github.com/BrianJM/payload-bug-minux-prefix-relationship-fields

#### `defaultSort`
When searching (typing) in a `Relationship field` that has a `Collection` with `defaultSort` prefixed with a minus `-`, the following error occurs:
```
QueryError: The following path cannot be queried: -name
```
From the [docs](https://payloadcms.com/docs/configuration/collections#options):
> Prefix the name of the field with a minus symbol ("-") to sort in descending order.

Example:
```typescript
{
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
  ],
  slug: 'tags',
  defaultSort: '-name',
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'createdAt'],
  },
}
```

#### `sortOptions`
When searching (typing) in a `Relationship field` that has `sortOptions` prefixed with a minus `-`, the following error occurs:
```
TypeError: Cannot destructure property 'operator' of '(0 , _sanitizeQueryValue.sanitizeQueryValue)(...)' as it is undefined.
```
From the ([docs](https://payloadcms.com/docs/fields/relationship#admin-config)):
> You can prefix the field name with a minus symbol ("-") to sort in descending order.

Example:
```typescript
{
  name: 'category',
  type: 'relationship',
  relationTo: 'categories',
  admin: {
    sortOptions: '-updatedAt',
  }
},
```

### To Reproduce

1. Fork the reproduction repository.
2. Run `pnpm dev _community`
3. Open the `Admin URL`: http://localhost:3000/admin
4. View an existing `Post`
5. Type `test` in the `Category` field. View the error in the UI and server console.
> ![image](https://github.com/payloadcms/payload/assets/373755/7876f39a-6500-4479-bb68-937270764f66)
> ![image](https://github.com/payloadcms/payload/assets/373755/ae54e9a8-73ed-45f8-aabd-fcf22f319636)
6. Type `test` in the `Tag` field. View the error in the UI and server console.
> ![image](https://github.com/payloadcms/payload/assets/373755/9deeb0ec-31e7-4a5f-b254-f1bc529a890a)
> ![image](https://github.com/payloadcms/payload/assets/373755/16343d61-4924-4bd2-85d1-733826262bc4)

### Payload Version

main, 2.11.1

### Adapters and Plugins

db-mongodb

**Comment by denolfe** [comment]
Should be fixed by #5964
