### ISSUE TITLE
Can't resolve 'payload-config' error on admin page route during build

### ISSUE THREAD

**Issue by alexanderalmstrom** [payloadcms/payload#5230]
### Describe the Bug

I get "Module not found: Can't resolve 'payload-config'" when building the Next.js app.

I've got a (payload)/admin/page.tsx route according to this https://github.com/payloadcms/next-payload/blob/main/templates/app/(payload)/admin/page.tsx

Here is the full error:

`
   ▲ Next.js 14.1.1
   - Environments: .env

   Creating an optimized production build ...
[01:46:02] INFO (payload): Starting Payload...
[01:46:03] INFO (payload): Payload Admin URL: http://localhost:3000/admin
[01:46:03] INFO (payload): Next.js is now building...
Failed to compile.

./node_modules/.pnpm/payload@2.11.2_@types+react@18.2.61_esbuild@0.19.12_typescript@5.3.3_webpack@5.90.3/node_modules/payload/dist/admin/Root.js
Module not found: Can't resolve 'payload-config'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/app/(payload)/admin/page.tsx

unhandledRejection Error: Build failed because of webpack errors
    at webpackBuildImpl (/Users/alexanderalmstrom/Development/Playground/payload/node_modules/.pnpm/next@14.1.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack-build/impl.js:276:21)
    at async Object.workerMain (/Users/alexanderalmstrom/Development/Playground/payload/node_modules/.pnpm/next@14.1.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack-build/impl.js:313:20) {
  type: 'Error',
  code: 'WEBPACK_ERRORS'
}
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
`

### To Reproduce

Build the app with `pnpm build`

### Payload Version

2.11.2

### Adapters and Plugins

plugin-cloud, db-postgres

**Comment by mirite** [comment]
I had the same problem. Adding `nodeLinker: node-modules` to the yarnrc fixed it for me

**Comment by flancast90** [comment]
Same issue here. Adding the nodeLinker as suggested by @mirite unfortunately did not work for me

**Comment by deviro** [comment]
Please check if you do this step? 
4. Add withPayload to your next.config
Payload needs to inject some requirements into your Next config in order to function properly. To install withPayload, you need to import it into your next.config.js file.

**Comment by rajesh7688** [comment]
yarn add payload

**Comment by jmikrut** [comment]
Hey all, 

The `next-payload` package has been deprecated in favor of Payload 3.0. To see how you can run Payload within Next.js natively, check out this repo:

https://github.com/payloadcms/payload-3.0-demo

**Comment by Gold240sx** [comment]
I got this error when I installed Payload first then decided to move my app folder into a src folder so this error could be triggered by changes to the initial folder setup when Payload is installed ( using payload: ^3.0.0-beta.6
