### ISSUE TITLE
use-npm flag leaves yarn references behind

### ISSUE THREAD

**Issue by hades200082** [payloadcms/payload#5236]
### Describe the Bug

When creating a new PayloadCMS project using the command `npx create-payload-app@latest --use-npm` there are references to yarn left behind in various places in the resulting project.

- In the Dockerfile
- In the package.json scripts
- In the docker-compose.yml
- yarn.lock file left behind

All of these have to be fixed manually or things don't work as they should when deploying the Payload instance.

### To Reproduce

1. Run `npx create-payload-app@latest --use-npm`

Observe yarn references described still exist.

### Payload Version

any up to 2.11.2 so far

### Adapters and Plugins

n/a

**Comment by denolfe** [comment]
I'll need to think carefully about this. Ideally, we support npm, yarn, and pnpm with this command. However, this would require templatizing all of the above files.

I think this will likely happen for the 3.0 templates once that is released.
