### ISSUE TITLE
Error saving a localized field inside an array field inside a block on a collection with versions enabled (Postgres only)

### ISSUE THREAD

**Issue by joyceverheije** [payloadcms/payload#5240]
### Describe the Bug

On a collection that has `versions` enabled, if you have a block with a field of type `array` which contains a text field that is localized, and you try saving, it returns an error. 

Related to #5104. It should have been fixed in https://github.com/payloadcms/payload/pull/5117 but maybe the problem still applies to blocks.

### To Reproduce

- Make sure you are using the postgres adapter for database
- Add localization to the payload config
- Create a collection and enable the version property
- Add a block field with a block that contains a field of type `array`, itself containing a `text` field that is localized
- Try creating an entry with some text entered in the array item

Example block:
```
import type { Block } from "payload/types";

const testsBlock: Block = {
    slug: "tests",
    fields: [
        {
            name: "testItems",
            type: "array",
            fields: [
                {
                    name: "title",
                    type: "text",
                    label: "Title",
                    localized: true,
                },
            ],
            label: "Tests",
        },
    ],
    interfaceName: "TestsBlock",
};

export default testsBlock;
```

### Payload Version

2.11.2

### Adapters and Plugins

db-postgres

**Comment by AlessioGr** [comment]
Could be related to https://github.com/payloadcms/payload/pull/6540

**Comment by louisnt** [comment]
Hello @AlessioGr,

How can we circumvent this issue, please?


Happened on payload 2.24.0

```
  db: postgresAdapter({
    idType: "uuid",
    pool: {
      connectionString: process.env.DATABASE_URI,
    },
  }),
```

With localized field in an array block
- adding a new item works
- updating or saving crashes: duplicate key value violates unique constraint ..._locale_parent_id_unique
- impossible to edit via the admin UI because the payload contains all the fields, so it crashes

**Comment by siobahnschuck** [comment]
Parroting @louisnt -- seeing simular behavior on our project. `v3.0.0-beta.60` and this payload 3.0 demo fork [here](https://github.com/siobahnschuck/payload-3.0-demo-localization-err/pull/1 )

when localization is set to true within a versioned collection we are not able to add multiple of the same blocks. Citing the same `Cannot read properties of undefined (reading '_nlblock_v_items_locales_locale_parent_id_unique')` on publish. 

In addition, on our project but not in the demo, moving localization to the arr level prohibits migrations to run and we get this err: 
`ERROR (payload): Error: cannot connect to Postgres. Details: Cannot read properties of undefined (read
ing 'Symbol(drizzle:Name)')`

**Comment by DanRibbens** [comment]
I was not able to reproduce the original issue in the current `beta` branch. I think this can be closed when we release the new beta and I'm if there is enough interest, I will backport it to 2.x.

**Comment by siobahnschuck** [comment]
Just updated to `3.0.0-beta.70` in both my project codebase and the modified [demo](https://github.com/siobahnschuck/payload-3.0-demo-localization-err/pull/1 ) I think this is related to this issue [here](https://github.com/payloadcms/payload/issues/7371)

**Comment by HappyEmu** [comment]
@DanRibbens This seems to be fixed for collections, but does not appear to be fixed for globals. Should I make a new issue for globals?
