### ISSUE TITLE
TypeError: Cannot set properties of undefined

### ISSUE THREAD

**Issue by xin-ze** [payloadcms/payload#5249]
### Link to reproduction

https://github.com/xin-ze/nestjs_reproduction/tree/payload](https://github.com/xin-ze/nestjs_reproduction/tree/payload

### Describe the Bug

[code link](https://github.com/payloadcms/payload/blob/main/packages/payload/src/config/load.ts#L21)
<img width="1810" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/fb2c87a7-d64e-4bfe-9591-b6289339feb8">

<img width="1381" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/6a768859-cac9-4fc8-9e93-018bfca6edb7">

### To Reproduce
github link: [https://github.com/xin-ze/nestjs_reproduction/tree/payload](https://github.com/xin-ze/nestjs_reproduction/tree/payload)
**branch: payload**
node version: 18.16.0

```
npm install
npx nx run seo-payload:serve --verbose
```
<img width="1537" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/8022ed89-40d9-4421-8bfb-61326a8d2f79">

### Payload Version

2.3.1

**Comment by xin-ze** [comment]
@denolfe This problem has been blocking me for a long time. Can you help me check it out? Thank you.

**Comment by LoiLock** [comment]
So this issue was closed, but did you find any solution @blueMountain007 ?
