### ISSUE TITLE
Rate Limit Default Doesn't Add Up

### ISSUE THREAD

**Issue by TheDunco** [payloadcms/payload#5260]
# Documentation Issue

On the [rate limiting requests](https://payloadcms.com/docs/production/preventing-abuse#rate-limiting-requests) page the `window` property says `Time in milliseconds to track requests per IP. Defaults to 90000 (15 minutes).` 

According to my calculations ([Google conversion](https://www.google.com/search?q=90000+milliseconds+to+minutes&sca_esv=7fb4d62672696752&ei=RkPqZbLcIs60ptQPhfCg0Ac&oq=90000+milliseconds+to+minutes&gs_lp=Egxnd3Mtd2l6LXNlcnAiHTkwMDAwIG1pbGxpc2Vjb25kcyB0byBtaW51dGVzKgIIADILEAAYgAQYigUYkQIyCxAAGIAEGIoFGIYDMgsQABiABBiKBRiGAzILEAAYgAQYigUYhgMyCxAAGIAEGIoFGIYDSKciUOwMWJQbcAN4AZABAJgBY6ABmgeqAQIxMrgBA8gBAPgBAZgCD6ACwwfCAgoQABhHGNYEGLADwgINEAAYgAQYigUYQxiwA8ICBhAAGAcYHsICChAAGAgYBxgeGA_CAgcQABiABBgNmAMAiAYBkAYKkgcEMTQuMaAHxj4&sclient=gws-wiz-serp) 😆) 90000ms = 1.5 minutes, not 15 minutes.

My questions are as follows:
- What is the actual default rate limit **number**? Is it `90000`?
- What is the actual default rate limit **unit**? Is it seconds (seems most likely)? Or milliseconds like the docs say?

**Comment by thijssmudde** [comment]
@TheDunco

> What is the actual default rate limit number? Is it 90000?

15 * 60 * 1000 = 900 000

> What is the actual default rate limit unit? Is it seconds (seems most likely)? Or milliseconds like the docs say?

It is milliseconds. You can see the defaults are being used from the express-rate-limit package.
https://www.npmjs.com/package/express-rate-limit

**Comment by TheDunco** [comment]
Roger that. In that case the docs should be updated to say "Defaults to `900,000` (15 minutes)" instead of the current, errant `90,000`.
