### ISSUE TITLE
[V3] Locale switcher does nothing

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload#5267]
### Describe the Bug

When switching locales with v3, the anchor tag appears to be created properly; hovering it does display the correct url in the bottom left of the screen. However, upon clicking it, nothing happens. Manually entering the query param and refreshing the page will switch locales. Switching pages afterwards results in the locale being reset to the `defaultLocale`

### To Reproduce

Just create more than 1 locale with the v3 demo and attempt to change locales.

### Payload Version

3.0.0-alpha.34

**Comment by JarrodMFlesch** [comment]
Fixed in https://github.com/payloadcms/payload/pull/5273
