### ISSUE TITLE
ERROR (payload): Error: cannot connect to Postgres. Details: SSL/TLS required

### ISSUE THREAD

**Issue by justoverclockl** [payloadcms/payload#5284]
### Describe the Bug

Tried PayloadCms for the first time...can't start app in dev mode. i get the error:

I've created a postgres db on onrender.com, this is my string:
postgres://<MYNAME>:<MYADDRESS>@dpg-cnmap3021fec739681bg-a.frankfurt-postgres.render.com/payloadcms
`ERROR (payload): Error: cannot connect to Postgres. Details: SSL/TLS required`

### To Reproduce

-Create a new project
-Run yarn dev
-The error appear in terminal

### Payload Version

@latest

### Adapters and Plugins

db-postgres

**Comment by ThomasAunvik** [comment]
Add ?sslmode=require at the end of the connectionstring
