### ISSUE TITLE
Browsing through pagination of filtered collections leads to infinite loop

### ISSUE THREAD

**Issue by militsa-tsvetkova** [payloadcms/payload#5312]
### Describe the Bug

Browsing through pagination of filtered collections leads to infinite loop

When changing how many records to be displayed per page, the app crashes and starts sending over and over the same request

<img width="1532" alt="Screenshot 2024-03-13 at 09 45 51" src="https://github.com/payloadcms/payload/assets/127120564/733a3535-cf02-456e-8076-8c11466e99bc">
[Recording](https://www.youtube.com/watch?v=wW3Qj-FL0_w)

### To Reproduce

1. Add filter to a collection
2. Change Pagination options from 100 to 5 per page
3. Select second page
4. Change back pagination to 100 per page

### Payload Version

latest

**Comment by kasipavankumar** [comment]
+1

Can confirm that this is an issue that even I am facing. I am running Payload version 2.14.2.

**Comment by kasipavankumar** [comment]
> +1
> 
> Can confirm that this is an issue that even I am facing. I am running Payload version 2.14.2.

This seems to be fixed in v2.26.0
