### ISSUE TITLE
Website Template - Webpack Cache Error (No Serializer registered for ConcatSource)

### ISSUE THREAD

**Issue by final-developer** [payloadcms/payload#5313]
### Describe the Bug

When cloning the github repo with the website template (or installing via npx) to local, webpack caching does not work.
Following errors occure and make development painful due to compiling durations of 30 seconds after each change:

```
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: No serializer registered for ConcatSource
<w> while serializing webpack/lib/util/registerExternalSerializer.webpack-sources/ConcatSource -> Array { 2 items } -> ConcatSource
```

### To Reproduce

Clone the website template repo: https://github.com/payloadcms/payload/tree/main/templates/website via CLI to local.
Run it with `yarn dev / npm run dev`.

### Payload Version

2.0.0

### Adapters and Plugins

bundler-webpack

**Comment by cgarempire** [comment]
Same for me. All i did was clone the example repo, seed the database, and i get this error while trying to delete the seeded demo users

**Comment by unknownterritory** [comment]
The same happens when trying to run `docker compose up` from the website template installation. It gets stuck on a loop after throwing these two lines:
```
payload-1  | <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: No serializer registered for ConcatSource
payload-1  | <w> while serializing webpack/lib/util/registerExternalSerializer.webpack-sources/ConcatSource -> Array { 2 items } -> ConcatSource
```

**Comment by jmikrut** [comment]
Hey all, you should use the new beta website template from this point on as the one on the `main` branch will no longer be supported. Run `npx create-payload-app@beta -t website` to get the latest and greatest!
