### ISSUE TITLE
Form builder plugin formOverrides info incorrect

### ISSUE THREAD

**Issue by frederico-taramaschi** [payloadcms/payload#5316]
# Documentation Issue

The documentation states that the formOverrides property can be used to override anything but it appears to be impossible to change existing fields such as confirmationMessage, submitButtonLabel, ... and it also seems impossible to use the property to override the react hooks for example.

## Additional Details
Not sure if this classifies as a documentation issue or if it is menat to be possible and this is a bug/unimplemented feature. But looking at the code the use cases written above are in fact not possible right now.

**Comment by paulpopus** [comment]
You're right that this wasn't previously possible. But in the [latest v3 of the plugin](https://payloadcms.com/docs/beta/plugins/form-builder#options) we've moved to a new pattern where you can map over the existing fields and therefore modify them exactly as needed.

In the docs see the `formOverrides` or `formSubmissionOverrides` section specifically for fields.
