### ISSUE TITLE
Blocks - defaultValue does not work

### ISSUE THREAD

**Issue by mvmendes** [payloadcms/payload#5332]
### Describe the Bug

I'm using a field Blocks and it working as expected when I click on Add [xxxx] Button. But, for UX, I need to start de create register page with a preconfigurated default block, in order to avoid user's useless clicks, like this: click in Add button-> Open Blocks popup -> Select a single option of Block (I have no other types of blocks yet) and then get block enabled for filled by the user.
From this:
![image](https://github.com/payloadcms/payload/assets/18039308/03165fe2-d435-466f-9842-9fd96943ae6f)
I want to get this, by default:
![image](https://github.com/payloadcms/payload/assets/18039308/987f4c29-b3c2-425a-bfa0-5743a8d6b779)

Field config:
`{
      admin: {

        condition: (data, siblingData, { user }) => {
          if (!data?.aceiteTermo) {
            return false;
          }
          return true;
        }
      },
      name: 'registroCotas',
      label:'Registro de Cotas',
      labels: {
        singular: 'Cota',
        plural: 'Cotas'
      },
      minRows: 1,
      defaultValue:[{}],
      type: 'blocks',
      blocks: [Cotas],

    },`
    
 I tried to use documented property *defaultValue* (https://payloadcms.com/docs/fields/blocks), but doesn't worked as I wanted to.

### To Reproduce

Create a Collection with a Field of type Blocks and a single Block option, with a defaultValue array

### Payload Version

payload@^2.0.0:   version "2.11.2" (from yarn.lock)

### Adapters and Plugins

db-postgres

**Comment by rafalnawojczyk** [comment]
I'm not sure if that's achievable that easily. It's not a simple field.

The one workaround that I found trying to create a 'Blocks' field that has a defaultValue already set is to define it that way:

`  defaultValue:[{...CotasDefinition.fields, blockType: 'CotasBlock'}],
  type: 'blocks',
  blocks: [Cotas],`
  
  Ofc I just assumed that your definition/blockType is named that way, but you will probably need to adjust it. Doing it like that should resolve your problem. If that will work for you - I will try to contribute and make it clearer in DOC's, as right now it's not explicitly stated I think.
  
  
 To payload pros:
 maybe I should contribute and add a function that will help users to create a defaultValue for block field, and create a helper function for that

**Comment by mvmendes** [comment]
Hi Rafał !

With a little change I can get it working! Thank you for your code sample based on my context.

My working code:

I've changed the blockType (block's defined slug) to cotas, and CotasDefinition (CollectionConfig instance) is only "Cotas": 

`
defaultValue: [{ ...Cotas.fields, blockType: 'cotas' }],
`
A helper function will be a great tool!

**Comment by damnitrahul** [comment]
Hi there, 

I'm trying to achieve the same thing with my config. I'm getting type error with my config. 

```typescript
const StudioUseCases: CollectionConfig = {
  slug: 'studio-use-cases',
  admin: {
    useAsTitle: 'title',
    group: 'Studio Use Cases Pages'
  },
  access: {
    read: () => true
  },
  fields: [
    textField('title'),
    slugField(),
    blockField('content', [blockHero(), blockFaq(), blockVideo(), blockImage()], {
      defaultValue: [{ ...blockImage().fields }]
    })
  ]
};

export default StudioUseCases;

// block image
export function blockImage() {
  return block(
    'block-image',
    [
      themeField('image'),
      backgroundField('image'),
      mediaField('image'),
      textField('maxWidth', {
        required: false,
        admin: { description: 'e.g. "100%" or "100px"' }
      })
    ],
    {
      interfaceName: 'IBlockImage'
    }
  );
}

// block
export function block(slug: string, fields: Field[] = [], options?: Omit<Block, 'fields' | 'slug'>): Block {
  return {
    slug,
    fields,
    ...options
  };
}

```
Error

```
Argument of type '{ defaultValue: { blockType: string; length: number; toString(): string; toLocaleString(): string; pop(): Field; push(...items: Field[]): number; concat(...items: ConcatArray<Field>[]): Field[]; concat(...items: (Field | ConcatArray<...>)[]): Field[]; ... 34 more ...; [Symbol.unscopables]: { ...; }; }[]; }' is not assignable to parameter of type 'Omit<BlockField, "name" | "type">'.
  Property 'blocks' is missing in type '{ defaultValue: { blockType: string; length: number; toString(): string; toLocaleString(): string; pop(): Field; push(...items: Field[]): number; concat(...items: ConcatArray<Field>[]): Field[]; concat(...items: (Field | ConcatArray<...>)[]): Field[]; ... 34 more ...; [Symbol.unscopables]: { ...; }; }[]; }' but required in type 'Omit<BlockField, "name" | "type">'.ts(2345)
types.d.ts(545, 5): 'blocks' is declared here.
```

I'm quite confused what's expected as defaultValue for the blocks field. There isn't an example on the docs I can follow.

**Comment by rafalnawojczyk** [comment]
Well, first thing is that Payload usually doesn't work well when you use hyphens in slugs. You shoud stick to letters/numbers and underscore _. These are usually the safest choices.

Your default value should have declared `blockType: 'your_image_block_slug'`.

I cannot see your implementation of `blockField()` thus it's hard to dive deeper. It looks like you are not creating a `blocks` property in `blockField` definition.

**Comment by damnitrahul** [comment]
Hey @rafalnawojczyk 

Thank you for the response.  I'm adding more definition below for blockField. 
I'm creating the blocks property in the blockField. Not sure what i'm doing wrong. 

Noted your feedback about slug. I hope that's not the issue here in this case?


```typescript
export function blockField(name: string, blocks: Block[], options?: Omit<BlockField, 'name' | 'type'>): BlockField {
  return {
    name,
    type: 'blocks',
    required: true,
    blocks,
    ...options
  };
}

```

**Comment by rafalnawojczyk** [comment]
@damnitrahul Have you tried to `Omit` a `blocks` property also? Right now if options has a `blocks` property - it will overwrite your defined one
