### ISSUE TITLE
@payloadcms/plugin-search - "Search Results" collection does not show up when using Next.js 14

### ISSUE THREAD

**Issue by AshtarCodes** [payloadcms/payload#5336]
### Describe the Bug

Problem is on Next.js 14 with Payload 2.11.0.

I used the website template and I have two branches - one with Next 13.5, and another with Next 14. 

The search plugin creates the "search results" collection on the admin panel, when on Next 13.5. It does not create it when on Next 14. 

However all other plugins continue working as expected. I would like for search plugin to work on Next.js 14 if possible. 

### To Reproduce

1. Clone and Use the website template 
2. upgrade payload to 2.11.0
3. upgrade to Next.js 14
4. Validate it loads with existing plugins / libraries
5. Install the search plugin
6. Check if the admin panel displays the "Search Results" collection

**Package.json dependencies:** 
![image](https://github.com/payloadcms/payload/assets/74083145/3e8f35d7-6916-42ed-a0c3-a64e51c5e4a1)

### Payload Version

2.11.0

### Adapters and Plugins

db-postgres, bundler-webpack, plugin-cloud-storage, plugin-nested-docs,plugin-redirects, plugin-search, plugin-seo, richtext-slate

**Comment by paulpopus** [comment]
I managed to get this working on the latest versions of the plugins with v2 of payload website template.

Will close this issue for now but we can re-open if there's a reproduction
