### ISSUE TITLE
Name contains illegal characters in package.json

### ISSUE THREAD

**Issue by slavakurilyak** [payloadcms/payload#5351]
### Describe the Bug

When creating a new Payload CMS project, the installation process fails during the dependency installation step with an error related to illegal characters in the `package.json` name field. This happens when the name contains spaces or uppercase letters, which is against npm's naming conventions. This can be confusing for users, especially those who might not be familiar with these specific requirements.

### To Reproduce

1. Run the command to create a new Payload CMS project (e.g., `npx create-payload-app`).
2. When prompted, enter a PostgreSQL connection string.
3. Provide a name for the project that contains spaces or uppercase letters (e.g., "Payload CMS").
4. Observe the failure during the "Installing dependencies" step, with the error message `error package.json: Name contains illegal characters`.

### Payload Version

2.0.0

**Comment by denolfe** [comment]
With 3.0 so close, this will be fixed on 3.0 release.
