### ISSUE TITLE
Pagination on polymorphic relationship field requesting entries with page parameter set to NaN

### ISSUE THREAD

**Issue by schaschjan** [payloadcms/payload#5362]
### Link to reproduction

https://github.com/schaschjan/payload-has-many-relationship-pagination-query-issue

### Describe the Bug

Then configuring a relationship field with multiple collection relations, entires from the first configured collection are requested as expected, following collections are requested with query parameter page=NaN.

### To Reproduce

Start the reproduction environment:
`pnpm dev _community`

![Screenshot 2024-03-19 at 14 26 56](https://github.com/payloadcms/payload/assets/6285839/d65e0296-047b-4cd8-a30a-01baa6bc2717)

In the posts collection, scroll through the relations select.

### Payload Version

main

**Comment by ohueter** [comment]
Hi, we ran into this bug as well. Merging the associated PR or working out another solution would be highly appreciated @DanRibbens  Thanks a lot for your work on Payload everyone!
