### ISSUE TITLE
Failure when running build with disableDbConnect=false

### ISSUE THREAD

**Issue by AshtarCodes** [payloadcms/payload#5370]
### Link to reproduction

https://github.com/AshtarCodes/payload-build-error-repro

### Describe the Bug

I have set disableDbConnect to `true` using an environment variable. The intention is to use this during a Docker build. When running `npm run build`, the `npm run build:payload` part of the script works but the `npm run build:next` fails with : 
```bash
> mds-docs-payload-2@1.0.0 build:next
> cross-env PAYLOAD_CONFIG_PATH=dist/payload/payload.config.js NEXT_BUILD=true node dist/server.js

[12:52:57] INFO (payload): Starting Payload...
[12:52:58] INFO (payload): Payload Admin URL: http://localhost:3000/admin
[12:52:58] INFO (payload): Next.js is now building...
[12:52:58] ERROR (payload): Error: cannot begin transaction: Cannot read properties of undefined (reading 'transaction')
```

### To Reproduce
1. [Clone this repo](https://github.com/AshtarCodes/payload-build-error-repro)
2. Follow steps in the README.md

### Payload Version

4.11.0

### Adapters and Plugins

db-postgres, bundler-webpack, plugin-cloud-storage, plugin-nested-docs,plugin-redirects, plugin-search, plugin-seo, richtext-slate

**Comment by AshtarCodes** [comment]
What I tried: 
If "NEXT_PUBLIC_SERVER_URL" environment variable is commented out, the build succeeds.

I think Next.js is hitting the payload API during the build and payload tries to hit the database but instead throws this error about a transaction - since db connection is disabled.

**Comment by denolfe** [comment]
I pulled down your repo, followed the steps, and was able to build just fine. 

<img width="621" alt="CleanShot 2024-04-18 at 15 16 14" src="https://github.com/payloadcms/payload/assets/65888/a7a219f8-86ee-4456-9845-3fd2e662f411">

What version of node are you running? What version of postgres are you connecting to?

**Comment by AshtarCodes** [comment]
@denolfe Sorry I misspelled the ENV variable in the server.ts file. I just pushed up changes. Can you try running it again?

I am on Node v 20.10.x, using Postgres 13, on M1 Macbook Pro.

**Comment by denolfe** [comment]
✅  Error reproduced in provided repo
