### ISSUE TITLE
Problem with Relationship fields

### ISSUE THREAD

**Issue by upcase-chefs** [payloadcms/payload#54]
# Bug Report

When I create a collection that has a relationship field, I'm not able to select one option.

## Expected Behavior

When I set a new field relationship, the dropdown let me select the option and save my object.

## Current Behavior

When I create a field with relationShip, but with hasMany set to False, I'm not able to select the object from the list dropdown

## Possible Solution

Fiz the react component. Looks like a little bug.

## Steps to Reproduce

1.Create a new relationship field like this one:
    {
      name: 'cuisineRelated',
      label: 'Culinária',
      type: 'relationship',
      relationTo: ['cuisine', 'users'],
      hasMany: false,
      required: false
    },

2. Go to admin and try to pick one option from the Cuisine collection
3. The dropdown list don't allow me to select the option.

## Detailed Description

I'm using the latest available Payload version from npm and my Browser is Google Chrome.

**Comment by jmikrut** [comment]
Hey @upcase-chefs — this is now fixed. We'll be publishing a new version of Payload for you shortly!

Thank you for the bug report!

**Comment by DanRibbens** [comment]
v0.2.10 is published now and includes this fix.
