### ISSUE TITLE
autoComplete property of Email field's admin config not populating HTML autocomplete attribute

### ISSUE THREAD

**Issue by wrobson-lllow** [payloadcms/payload#5408]
### Link to reproduction

https://github.com/wrobson-lllow/payload/tree/autoComplete-bug-reproduction

### Describe the Bug

In the docs "autoComplete" is listed as an additional property for the admin configs of  [Email](https://payloadcms.com/docs/fields/email#admin-config), [Text](https://payloadcms.com/docs/fields/text#admin-config), and [Number ](https://payloadcms.com/docs/fields/text#admin-config) fields.

First, the documentation for this property is a bit vague. After reading it I assumed it was for setting an "autocomplete" HTML attribute and looking at the [source code for the Email field](https://github.com/payloadcms/payload/blob/1c0d43c61a0e29bc9de50a4e608cb7dff9d5cd48/packages/payload/src/admin/components/forms/field-types/Email/index.tsx#L73) confirmed it, but IMO if the documentation is properly complete one should almost never have to look in the source code to understand how to use a feature.

Second, although listed in the Docs for the three fields, it only works for Email fields. No autocomplete attribute is given to Text or Number fields: [Text Field Source Code](https://github.com/payloadcms/payload/blob/1c0d43c61a0e29bc9de50a4e608cb7dff9d5cd48/packages/payload/src/admin/components/forms/field-types/Text/index.tsx), [Number Field Source Code](https://github.com/payloadcms/payload/blob/1c0d43c61a0e29bc9de50a4e608cb7dff9d5cd48/packages/payload/src/admin/components/forms/field-types/Number/index.tsx)
 
Finally, adding an option for adding an autoComplete attribute for the Users collection would be helpful as well, as the email field is generating automatically from the auth config, there doesn't seem to be a way to manage autoComplete. 

Text Field:
![image](https://github.com/payloadcms/payload/assets/132296416/8be6463d-cb03-4c43-bcb8-a86567f8d2a4)

Number Field:
![image](https://github.com/payloadcms/payload/assets/132296416/5280c736-bb07-4143-ba6f-8f252026f7aa)

Email Field:
![image](https://github.com/payloadcms/payload/assets/132296416/853b97f7-9f60-4f09-a34d-b1d712199dd2)

### To Reproduce

This can be seen on any Number or Text fields with an autoComplete property given to the field admin config. In the linked reproduction I have added a collection "Auto Complete Examples" where you can inspect the three fields and see that the attribute 
'autocomplete="example-attribute"' only appears for the email field although defined on all three fields.

### Payload Version

2.11.2

**Comment by paulpopus** [comment]
This will be fixed in v3: https://github.com/payloadcms/payload/pull/7322
