### ISSUE TITLE
Duplicate button can be pressed multiple times.

### ISSUE THREAD

**Issue by dacgray** [payloadcms/payload#5465]
### Describe the Bug

There is a delay between when the duplicate button is pressed and the page loads the new collection.

Often users click `Duplicate` multiple times creating more than one new collections.

The button should be disabled after one click.

### To Reproduce

As above.

### Payload Version

2.11.2

### Adapters and Plugins

"@payloadcms/bundler-webpack": "^1.0.6",     "@payloadcms/db-mongodb": "^1.3.2",     "@payloadcms/plugin-cloud-storage": "^1.1.1",     "@payloadcms/plugin-sentry": "^0.0.6",     "@payloadcms/richtext-slate": "^1.3.1",

**Comment by rafalnawojczyk** [comment]
I've tried to reproduce this bug, and it's working exactly as @dacgray stated here. User can click "duplicate" button multiple times. I will try to look at the code responsible for this behavior today, and maybe include PR here.

**Comment by PatrikKozak** [comment]
Hey @dacgray - I'm currently unable to reproduce this as clicking the duplicate button causes the popup to close, preventing you from duplicating a document multiple times in quick succession. 

Could you send a video / a reproducible repo that shows this behavior? Thank you!

**Comment by rafalnawojczyk** [comment]
@PatrikKozak  It is easy to reproduce, but you need to first save your document and after doing that - try to duplicate multiple times. 

While your doc is modified - you will get this popup, which prevents you from duplicating multiple times.

**Comment by denolfe** [comment]
> Could you send a video / a reproducible repo that shows this behavior? Thank you!

@rafalnawojczyk Can you provide this?

**Comment by rafalnawojczyk** [comment]
Repro video here:

https://github.com/payloadcms/payload/assets/102222064/aa7fc402-833d-4a3a-ada7-d50e704f9bd9
