### ISSUE TITLE
Data from nested lists in richt text is incorrect

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#551]
# Bug Report

Nested lists from the rich text fields are rendering incorrectly.
In Payload:
![image](https://user-images.githubusercontent.com/70709113/166122576-e375ae7b-5565-4997-aecd-374dce8ad61a.png)
In my frontend:
![image](https://user-images.githubusercontent.com/70709113/166122577-2336f840-df29-48a0-9519-3741c45beead.png)
This is the incorrect HTML it generates:
![image](https://user-images.githubusercontent.com/70709113/166122707-e7e32bc7-1458-43af-89ff-aad0f8ea4c80.png)
And this is what it's supposed to generate (ignore the ::marker or spans, just look at the structure):
![image](https://user-images.githubusercontent.com/70709113/166122641-c454c9fc-dc0b-4a8a-825d-4f23ea523930.png).

The `<ul>` of the second level would kinda need to be part of the first level; however, it's not. This is the relevant part of the data from the rest API.

```json
{
    "type":"li",
    "children":[
        {
            "text":"A"
        }
    ]
},
{
    "type":"li",
    "children":[
    {
        "type":"ul",
        "children":[
            {
                "type":"li",
                "children":[
                {
                    "text":"B"
                }
                ]
            },
            {
                "type":"li",
                "children":[
                {
                    "type":"ul",
                    "children":[
                        {
                            "type":"li",
                            "children":[
                            {
                                "text":"C"
                            }
                            ]
                        },
                        {
                            "type":"li",
                            "children":[
                            {
                                "text":"C"
                            }
                            ]
                        }
                    ]
                }
                ]
            }
        ]
    }
    ]
},
```
As you can see, "B" is not part of "A" here. Not sure if that's an issue with what the rest API outputs or with how it's rendered (I just followed what's explained in your docs there).

**Comment by jmikrut** [comment]
Hey @AlessioGr — Payload I believe is currently outputting correctly formatted JSON for nested lists — however, browsers have weirdness with nested lists, which is what you're showing in your screenshot. Basically, if you have an `li` within an `li`, you'll get two bullets.

The solution is to use CSS, and to do something like this in your HTML serializer, which disables list style if there is an embedded list:

```js
case 'li':
  const hasListChildren = node.children ? node.children.find((child) => child?.type && ['ul', 'ol'].includes(child.type)) : false;
  return (
    <li
      key={i}
      style={{ listStyle: hasListChildren ? 'none' : undefined }}
    >
      <Serialize
        customRenderers={customRenderers}
        overrides={overrides}
        content={node.children}
      />
    </li>
  );
```

**Comment by AlessioGr** [comment]
> Hey @AlessioGr — Payload I believe is currently outputting correctly formatted JSON for nested lists — however, browsers have weirdness with nested lists, which is what you're showing in your screenshot. Basically, if you have an `li` within an `li`, you'll get two bullets.
> 
> The solution is to use CSS, and to do something like this in your HTML serializer, which disables list style if there is an embedded list:
> 
> ```js
> case 'li':
>   const hasListChildren = node.children ? node.children.find((child) => child?.type && ['ul', 'ol'].includes(child.type)) : false;
>   return (
>     <li
>       key={i}
>       style={{ listStyle: hasListChildren ? 'none' : undefined }}
>     >
>       <Serialize
>         content={node.children}
>       />
>     </li>
>   );
> ```

Hey, that could work visually. Semantically I don't think it's correct too, though. Shouldn't the second-level `<li>` be nested inside an `<ul>` in the top-level` <li>`? Because right now, they are on the same level.
So instead of:
```html
<li>
  A
</li>
<li>
  <ul>
    <li>
      B
    </li>
  </ul>
</li>
```

It should be:
```html
<li>
  A
  <ul>
    <li>
      B
    </li>
  </ul>
</li>
```
to be semantically correct, shouldn't it?

**Comment by katywings** [comment]
@jmikrut Do you think the weird behaviour about the indent/outdent feature, that I show in the video below, might be related to this issue :)?

![](https://user-images.githubusercontent.com/4012401/188283007-92e96d94-2dc9-4b51-8d4b-2c924c5e1b41.mp4)
(https://user-images.githubusercontent.com/4012401/188283007-92e96d94-2dc9-4b51-8d4b-2c924c5e1b41.mp4)

**Comment by jmikrut** [comment]
@katywings it sure is!

We are going to tackle this issue next. Give us a few days here and I will report back with our progress. Thanks for the video - this is super helpful!

**Comment by jmikrut** [comment]
Hey @Stupidism we're going to address this after launch week! Got some other features prioritized over this issue at the moment. But it is indeed on our radar.

**Comment by jamov** [comment]
> When is launch week? a week in a month? @jmikrut 

I think this was referred: https://payloadcms.com/blog/launch-week

**Comment by TomDoFuture** [comment]
this resolved yet? @jmikrut

**Comment by jmikrut** [comment]
Hallelujah it's a Christmas miracle.

I just wasted about 1,000,000 brain cells on fixing this issue but it is now done and will be released shortly!

**Comment by falko100** [comment]
🤩🎉

**Comment by katywings** [comment]
@jmikrut Thank you so much for your work! I wish you an amazzzing Christmas with lots of payload in form of Christmas presents 🥳

**Comment by jamov** [comment]
Awesome, thank you @jmikrut! Happy holidays to you and everyone 🎄
