### ISSUE TITLE
Number field set to zero evaluates as null in collection list

### ISSUE THREAD

**Issue by thom801** [payloadcms/payload#5510]
### Describe the Bug

If I have a number field and show it in a collection list it will show as null but should show 0.

I am guessing the logic here is like `!number` or something instead of `number === undefined || number === null`

<img width="1218" alt="image" src="https://github.com/payloadcms/payload/assets/2018441/83ab0346-4e0d-4dbe-858f-0273ef1195bc">

<img width="787" alt="image" src="https://github.com/payloadcms/payload/assets/2018441/a3a7339e-38a6-42c8-9d3c-0c724b641838">

### To Reproduce

- Create a collection item with a number field and set the number to zero.
- Go to the collection list and show that column.

### Payload Version

2.11.2 (latest version as of today)

### Adapters and Plugins

I don't really know I just started evaluating payload yesterday.

**Comment by rafalnawojczyk** [comment]
It is implemented exactly as you expected. 
In file:
`payload\packages\payload\src\admin\components\views\collections\List\Cell\index.tsx`
there is a condition:
`if (!cellData && 'label' in field)`

I think your condition could work better in this particular situation, but I think, that this should be further discussed with PayloadCMS team, as we should really take all possibilities into account, here so this topic will never returns here.

I can see multiple ones:


1. String:
a) empty string - now shows <No %Field-name%> 

2. Number:
a) number === 0 - now shows <No %Field-name%>

3. Array:
a) [] (empty array) - now shows just [] 

What I could suggest is to add there a simple function that will first:
1. Check for null/undefined and if it meets condition - show <No %Field-name%>
2. Create multiple if statements for different types of values. 
a) empty string should probably still show <No %Field-name%>
b) number === 0 shouldn't show <No %Field-name%>, and if it's a number -always show as value
c) array - if empty - show <No %Field-name%>

I can create PR for this if this gets approval from any payloadCMS member.

**Comment by SimYunSup** [comment]
If second suggestion is adopted, must add conditonal logic for boolean logic like #4621 (I accidentally deleted).
