### ISSUE TITLE
Visual Bugs in Payload CMS when Displaying Embedded Images from MongoDB

### ISSUE THREAD

**Issue by evoreign** [payloadcms/payload#5566]
### Describe the Bug

I am encountering visual bugs in the Payload CMS when attempting to display images with long embeddings stored in MongoDB. Despite successfully uploading and storing the image data in MongoDB, the CMS exhibits visual discrepancies, especially with images containing lengthy embeddings.

Possible Solution:
One potential approach to address this issue is to implement a mechanism within the Payload CMS to truncate the embedding data if it exceeds a certain character length. By limiting the length of the displayed embedding, we can prevent visual bugs caused by excessively long embeddings.

Is this a good issue? I'm just a junior dev.
![image](https://github.com/payloadcms/payload/assets/64061171/63e76125-0f4e-4b77-b0fb-8016dc1629a4)

### To Reproduce

- Upload an image to Cloudinary using the provided code.
- Extract the image embedding and store it in MongoDB using the provided code.
- Access the Payload CMS and attempt to display the embedded image.

Code:
https://pastebin.com/n9Vd04Dt

Image:
![Screenshot_2024-03-30_13-40-42](https://github.com/payloadcms/payload/assets/64061171/b9641217-54c6-432c-adf1-7d07addf6c16)

### Payload Version

1.0

**Comment by denolfe** [comment]
Storing images in MongoDB is [not recommended](https://www.mongodb.com/community/forums/t/storing-images-in-mongodb/152599) by Mongo. I would say this is something that we are unlikely to address, especially since Payload has [dedicated upload functionality](https://payloadcms.com/docs/upload/overview#uploads) that can be leveraged.

**Comment by evoreign** [comment]
> Storing images in MongoDB is [not recommended](https://www.mongodb.com/community/forums/t/storing-images-in-mongodb/152599) by Mongo. I would say this is something that we are unlikely to address, especially since Payload has [dedicated upload functionality](https://payloadcms.com/docs/upload/overview#uploads) that can be leveraged.

I am currently working on a project involving an image similarity search engine. In this project, each image undergoes processing through the SIFT algorithm to obtain its descriptor, represented as an array. Subsequently, the descriptor is converted into a base64 string. The reason behind this conversion is to streamline the storage process in MongoDB, as directly storing the descriptor without conversion results in significantly increased storage requirements. Essentially, this descriptor serves as a compact representation of the image. The actual images are stored in a Cloudinary Content Delivery Network (CDN), while MongoDB stores only the corresponding Cloudinary URL along with the converted string that represents the image. The image search algorithm operates by taking an image descriptor and seeking matches within the database's embeddings. To clarify, the images themselves are hosted on the CDN rather than in MongoDB; MongoDB solely manages the storage of the image embeddings, which are lengthy strings. Any visual anomalies experienced likely stem from attempts to display these lengthy strings.
