### ISSUE TITLE
Why are there @payloadcms/db-mongodb packages in the front-end bundle?

### ISSUE THREAD

**Issue by blueMountain007** [payloadcms/payload#5577]
### Link to reproduction

https://payloadcms.com/

### Describe the Bug

<img width="1695" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/88752e5c-fd78-44ad-bb06-bbcaa0b0a628">

### To Reproduce

see above   

### Payload Version

2.3.1

### Adapters and Plugins

@payloadcms/db-mongodb

**Comment by AlessioGr** [comment]
Hey! This is due to mocking, you can find more information here: https://payloadcms.com/docs/admin/excluding-server-code#aliasing-server-only-modules

The fact that you see the mock file in the bundle and not the _actual_ db-mongodb adapter means that it's working and working as expected!

**Comment by blueMountain007** [comment]
@AlessioGr  Thank you, I am upgrading the payload version (from 1.11.1 to 2.3.1) and encountered this error locally:
<img width="1570" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/1d21782b-3393-41dc-bc97-c4cf5d4308e4">
