### ISSUE TITLE
How to replace payload-s3-upload with @payloadcms/plugin-cloud?

### ISSUE THREAD

**Issue by blueMountain007** [payloadcms/payload#5580]
# Documentation Issue

### Before 
payload version: 1.11.1
payload-s3-upload: 2.1.0

```
// Media collection
export const Media: MediaConfig = {
  slug: 'media',
  upload: {
    staticURL: '/assets',
    staticDir: 'assets',
    disableLocalStorage: true,
    s3: {
      bucket: environment.aws.s3UploadsBucket,
      prefix: `payload-cms/collections/media`,
      commandInput: {
        // optionally, use here any valid PutObjectCommandInput property
        // https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/putobjectcommandinput.html
        ACL: 'public-read',
      },
    }
  },
}
```

payload.config.ts
```
import s3Upload from 'payload-s3-upload';

export default buildConfig({
  plugins: [s3Upload()],
  // rest of config
})
```

[plugin-cloud doc link](https://github.com/payloadcms/payload/tree/main/packages/plugin-cloud)

**Comment by denolfe** [comment]
Hey @blueMountain007 , `payload-s3-upload` is actually a community project not maintained by the Payload team.

What are you looking to achieve? 

If you're wanting to deploy on Payload Cloud, you'll need [@payloadcms/plugin-cloud](https://www.npmjs.com/package/@payloadcms/plugin-cloud)

If you're wanting to bring your own cloud storage, you'll want to use [@payloadcms/plugin-cloud-storage](https://www.npmjs.com/package/@payloadcms/plugin-cloud-storage)
