### ISSUE TITLE
Adding a required field to a user collection either adds a null value or returns an error when creating the first user

### ISSUE THREAD

**Issue by RATIU5** [payloadcms/payload#5601]
### Describe the Bug

The `required` attribute causes an error when creating a user when it's set to true, and when it's set to false, the data is null. Allow me to elaborate.

When the name field on the users collection has `required` set to `true`, I get the following error:
```
The following field is invalid: name
```
So I tried changing it's value to `false` as well as omitting it entirely.  Each time I get no error, however, the name's value is `null` in the database even after entering some data into it's field.

The odd thing is that this doesn't happen on the select input or the email input when `required` is set to `true`. Once it had happened on the email field but I have not been able to replicate it again.

**Edit**: When adding/changing the name on the Payload interface, it updates correctly without errors. The problem only occurs when creating the first user only.

### To Reproduce

1. Clone the [3.0 Demo](https://github.com/payloadcms/payload-3.0-alpha-demo)
2. Replace the `payload.config.ts` with the following:
```ts
import { postgresAdapter } from '@payloadcms/db-postgres'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import path from 'path'
import { buildConfig } from 'payload/config'
import { fileURLToPath } from 'url'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

export default buildConfig({
  editor: lexicalEditor(),
  collections: [
    {
      slug: 'users',
      admin: {
        defaultColumns: ['name', 'email'],
        useAsTitle: 'name',
      },
      auth: true,
      fields: [
        {
          name: 'name',
          label: 'Full Name',
          type: 'text',
          required: true, // try changing this to false
        },
        {
          name: 'email',
          type: 'email',
        },
        {
          name: 'role',
          defaultValue: 'viewer',
          hasMany: false,
          options: [
            {
              label: 'super',
              value: 'super',
            },
            {
              label: 'admin',
              value: 'admin',
            },
            {
              label: 'viewer',
              value: 'viewer',
            },
          ],
          type: 'select',
        },
      ],
    },
  ],
  secret: process.env.PAYLOAD_SECRET || '',
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
  db: postgresAdapter({
    pool: {
      connectionString: process.env.POSTGRES_URI || '',
    },
  }),
})
```
3. Fill out your `.env` file and run the server with the config above

### Payload Version

3.0.0-alpha.49

### Adapters and Plugins

db-postgres

**Comment by paulpopus** [comment]
Fixed for next release
