### ISSUE TITLE
[plugin-search] `afterDelete` hook fails to delete stale search entries

### ISSUE THREAD

**Issue by wkentdag** [payloadcms/payload#5709]
### Link to reproduction

https://github.com/wkentdag/payload-search-delete-bug

### Describe the Bug

When you delete an item from a search-enabled collection, the stale search results are not deleted. [This request](https://github.com/payloadcms/payload/blob/main/packages/plugin-search/src/Search/hooks/deleteFromSearch.ts#L5-L14)  in the `afterDelete` hook returns 0 results when there should be 1.

I was able to fix to fix the issue by copying the existing `afterDelete` hook into my collections and removing the `req` option from the aforementioned query [[ref](https://github.com/wkentdag/payload-search-delete-bug/commit/e81851cab70a2f4e650e91aba836333777f592fc)]. It looks like that line was introduced recently in #5068 to support transactions.

https://github.com/payloadcms/payload/assets/3254957/b5b7f453-4f57-494b-b5a5-5449d1ab8ef7

### To Reproduce

1. Clone [my example repo](https://github.com/wkentdag/payload-search-delete-bug) and run it
2. create a new Page, note its search result entry, then delete it, note the stale search result entry
3. do the same thing for Pages with custom hooks, note that it works

### Payload Version

2.12.1

### Adapters and Plugins

bundler-webpack, db-postgres, plugin-search

**Comment by paulpopus** [comment]
Never mind it's isolated to postgres, I will keep this closed as it's a postgres problem specifically and we'll track progress in the other issue
