### ISSUE TITLE
Vite bundler: Changing "outDir" results in no build

### ISSUE THREAD

**Issue by joshuatazrein** [payloadcms/payload#5714]
### Describe the Bug

Changing "outDir" in the Vite config results in running `payload build` rendering no folder.

### To Reproduce

Use the following config:
```
import { mongooseAdapter } from '@payloadcms/db-mongodb'
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import { viteBundler } from '@payloadcms/bundler-vite'
import { buildConfig } from 'payload/config'
import Users from './cms/collections/Users'

export default buildConfig({
  admin: {
    user: Users.slug,
    bundler: viteBundler(),
    vite: incomingViteConfig => {
    return {
       ...incomingViteConfig,
       build: {
          ...incomingViteConfig.build,
          outDir: 'admin'
        }
```

### Payload Version

2.11.2

### Adapters and Plugins

bundler-vite, db-mongodb, richtext-lexical

**Comment by paulpopus** [comment]
Hey @joshuatazrein thanks for opening the issue.

The beta vite bundler is no longer going to be maintained as of 3.0 (beta out soon) as we've moved over to Nextjs. We recommend using webpack in the meantime

**Comment by kwabe007** [comment]
Try using `path.resolve` with the predefined `__dirname` variable, it worked for me:

```
outDir: path.resolve(__dirname, 'admin')
