### ISSUE TITLE
/reset-password 500 network server error 

### ISSUE THREAD

**Issue by palak-convivity** [payloadcms/payload#5715]
### Link to reproduction

https://github.com/palak-convivity/payloadcms

### Describe the Bug

payloadcms.com is showing this error.

![image](https://github.com/payloadcms/payload/assets/141804445/568f9483-3814-4254-bb83-a42b20d4ff81)

while I am doing same request on my project but its giving me 500 network server error "something went wrong"

![image](https://github.com/payloadcms/payload/assets/141804445/bc21d954-789e-4b2e-a650-7f9503a19f07)

### To Reproduce

hit POST req on /api/users/reset-password 
with invalid token in it's body 
```
body:{
    password:password,
    token:token
  }
```

### Payload Version

2.12.1

**Comment by paulpopus** [comment]
Are you saying that you're running a POST request to `/api/users/reset-password` from your frontend to your API?

I believe your frontend should be catching the error and handling it if that's the case. If you believe this is an issue with payload could you provide a reproduction repo please?

**Comment by palak-convivity** [comment]
https://github.com/palak-convivity/payloadcms

Create a new Payloadcms project 
Create a user
Reset the password of user using forget password
Set the email server 
You will get the mail of reset password
Reset the password using that token
If you again try to use that token
the error should be something like
```
Error: Token is either invalid or has expired.
```
but it is showing 
```
500 Internal Server Error
message: "Something went wrong."
```

https://jam.dev/c/395e3fd0-fbe8-424b-addd-081668f98997

**Comment by palak-convivity** [comment]
> https://github.com/palak-convivity/payloadcms
> 
> Create a new Payloadcms project Create a user Reset the password of user using forget password Set the email server You will get the mail of reset password Reset the password using that token If you again try to use that token the error should be something like
> 
> ```
> Error: Token is either invalid or has expired.
> ```
> 
> but it is showing
> 
> ```
> 500 Internal Server Error
> message: "Something went wrong."
> ```
> 
> https://jam.dev/c/395e3fd0-fbe8-424b-addd-081668f98997
