### ISSUE TITLE
Passing `req` in LocalAPI calls mutates `req.[config | collection | context | etc?]` resulting in possible unexpected runtime exceptions.

### ISSUE THREAD

**Issue by franciscolourenco** [payloadcms/payload#5720]
### Link to reproduction

https://github.com/franciscolourenco/payload/commit/35f427888c13f239f75eb7377bfdbaab6bd6678f

### Describe the Bug

Passing the `req` object along in LocalAPI calls causes the `req` object to be mutated outside of the LocalAPI call. This can cause different bugs resulting from mutated `req.config`, `req.context`, `req.collection` and possibly others. The reproduction demonstrates an issue with a mutated `req.collection` property.

```
[15:43:20] ERROR (payload): TypeError: Cannot read properties of null (reading 'config')
    at createHandler ((...)/packages/payload/src/collections/requestHandlers/create.ts:38:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Possibly related to https://github.com/payloadcms/payload/issues/3417, https://github.com/payloadcms/payload/issues/2831

### To Reproduce

1. Checkout the reproduction branch
2. `pnpm run test:int -- test/_community/int.spec.ts`
3. Or run the app and create a new Post manually 

### Payload Version

2.12.1

**Comment by paulpopus** [comment]
Running this code on posts as per your given example I can fire the hook without any issues

```ts
hooks: {
    beforeChange: [
      async ({ req, data }) => {
        await req.payload.findGlobal({
          slug: 'menu',
          req,
        })
        return data
      },
    ],
  },
```
Do you perhaps have something else mutating `req`? Your reproduction branch is 179 commits behind, can you reproduce it on the latest?

**Comment by franciscolourenco** [comment]
@paulpopus just rebased on latest main.

There is nothing else mutating the req, the only change made is the one in the commit. 


Tests should fail like this:

```
 FAIL  test/_community/int.spec.ts (8.608 s)
  _Community Tests
    ✓ local API example (7 ms)
    ✕ rest API example (15 ms)

  ● _Community Tests › rest API example

    TypeError: Cannot read properties of undefined (reading 'text')

      68 |     }).then((res) => res.json())
      69 |
    > 70 |     expect(newPost.doc.text).toEqual('REST API EXAMPLE')
         |                        ^
      71 |   })
      72 | })
      73 |

      at Object.text (test/_community/int.spec.ts:70:24)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        8.644 s
Ran all test suites matching /test\/_community\/int.spec.ts/i.
 ELIFECYCLE  Command failed with exit code 1.
```

The hook executes successfully. It's the creation operation that throws an error (even though data is actually written to the DB). Note that the creation operation is not the issue, any kind of code that uses the req object subsequently could fail / use incorrect data.

**Comment by paulpopus** [comment]
I see it now, thanks for clarifying @franciscolourenco
