### ISSUE TITLE
The Ukrainian translation code (UA) is wrong and incompatible with ISO-639 language code of Ukrainian language (UK)

### ISSUE THREAD

**Issue by BohdanK-W32** [payloadcms/payload#5740]
### Describe the Bug

Labels translations (or any other custom translations) are not shown if you create it under Ukrainian language with the code spelled in the correct way (ISO-639).

Currently, Ukrainian translations in Payload are provided under the wrong code `ua` in the file `ua.json`  (which follows ISO-3166 code, but this code is for the country "**Ukraine**", not for the language "**Ukrainian**").

Why is it wrong?
For example, it's like storing English language under `us.json` or `gb.json` files (with codes, which follow ISO-3166 country codes).

### To Reproduce

1. Create any collection with any field
2. Set `label` property of the field to `{ en: 'Title', uk: 'Заголовок' }`
3. Open admin panel
4. Set user language to Ukrainian (Українська) under "Payload settings" section
5. Open create view of the created collection

### Payload Version

3.0.0-alpha.59

### Adapters and Plugins

@payloadcms/translations

**Comment by JarrodMFlesch** [comment]
This has been adjusted, `ua` -> `uk` thanks for bringing it to our attention!

You can achieve this with the following:

```ts
import { en } from '@payloadcms/translations/languages/en'
import { uk } from '@payloadcms/translations/languages/uk'

const config = {
  // ... your config
  i18n: {
    supportedLanguages: {
      en,
      uk,
    }
  }
  // ... your config
}

**Comment by BohdanK-W32** [comment]
Thank you!
