### ISSUE TITLE
Postgres: deleting last element in text field with hasMany: true not working

### ISSUE THREAD

**Issue by Janisvb** [payloadcms/payload#5741]
### Link to reproduction

https://github.com/Janisvb/payload-reproduction/tree/delete-hasmany

### Describe the Bug

In a text field with hasMany: true, deleting the last element is not setting the value to `[]` or `null`

![CleanShot 2024-04-09 at 14 21 59](https://github.com/payloadcms/payload/assets/7983986/bcf9ce53-00a2-490a-89b3-43cbea87580e)

### To Reproduce

```typescript
const post = await payload.create({ collection: postsSlug, data: { text: ['test'] } })

await payload.update({ collection: postsSlug, id: post.id, data: { text: [] } }) // not working
await payload.update({ collection: postsSlug, id: post.id, data: { text: null } }) // not working
```

Works as expected with MongoDB.

### Payload Version

2.12.1

### Adapters and Plugins

db-posgres

**Comment by paulpopus** [comment]
This has been fixed in the latest of v3 beta
