### ISSUE TITLE
API key remains in the DB and is not actually disabled

### ISSUE THREAD

**Issue by franciscolourenco** [payloadcms/payload#5742]
### Link to reproduction

https://github.com/franciscolourenco/payload/commits/reproduce-api-key-not-being-disabled/

### Describe the Bug

When disabling an API key, `enabledAPIKey` is set to false, but the `apiKey` property is not removed for the user document, so it's still possible to authenticate using it.

### To Reproduce

1. `pnpm dev _community`
2. Manually enable API key
3. Copy the API key
4. Save the user document
5. Disable the API key
6. Save the user document
7. Test if API key is still working, with eg. `curl 'http://localhost:3000/api/users/me' -H "Authorization: users API-Key [replace-with-api-key]" | jq`

### Payload Version

2.12.1

**Comment by franciscolourenco** [comment]
There was an attempt to fix this in https://github.com/payloadcms/payload/pull/5145/files, however the fix doesn't seem to be working.

The tests passe because authentication isn't actually working, even if the API Key is enabled.

**Comment by denolfe** [comment]
Thank you for the report @franciscolourenco . We'll look into this.

**Comment by franciscolourenco** [comment]
```typescript
const encryptKey: FieldHook = ({ req, value }) =>
  value ? req.payload.encrypt(value as string) : null
```
The change in [line 10](https://github.com/payloadcms/payload/blob/d954ceb744844e26802b0ad0c42d8ba17a7178df/packages/payload/src/auth/baseFields/apiKey.ts#L10) also had an unexpected side effect: If the apiKey property is not provided in data (for example because it was removed in a hook), the ke will set to null. This deviates from the normal behavior which is that undefined properties are left unchanged.

**Comment by DanRibbens** [comment]
@franciscolourenco Thanks to your comment I investigated a little further and made more improvements.

First off, I added a test specifically for the thing you called out. It wasn't broken because behind the scenes payload makes an index field for looking up the API key user in a secure encrypted way so that separation meant it was not removing the ability to login. I left the test in though as a safeguard for any future issues with this.

Then I did make changes to the index hook to make it copesetic. Now an update with `apiKey: null` or `enableAPIKey: false` will strip the index back to null so that a user cannot login with that key any longer.

Cheers!

**Comment by franciscolourenco** [comment]
>First off, I added a test specifically for the thing you called out. It wasn't broken because behind the scenes payload makes an index field for looking up the API key user in a secure encrypted way so that separation meant it was not removing the ability to login. I left the test in though as a safeguard for any future issues with this.

@DanRibbens not completely sure which of the things you are referring to in this one.

I gave the PR a try, and can confirm that the apiKey is correctly disabled 👍 

-----------------

However the [issue with the key being set to null when not present](https://github.com/payloadcms/payload/issues/5742#issuecomment-2066589561) still exists.

Here is some [reproduction code](https://github.com/payloadcms/payload/compare/main...franciscolourenco:payload:reproduce-null-api-key).

Integration Test:
```
 FAIL  test/_community/int.spec.ts (7.782 s)
  _Community Tests
    ✓ the hook should prevent further changes to the username (5 ms)
    ✕ should not delete API key when updating other fields (4 ms)

  ● _Community Tests › should not delete API key when updating other fields

    expect(received).not.toBeNull()

    Received: null

      66 |     })
      67 |
    > 68 |     expect(foundUser.apiKey).not.toBeNull()
         |                                  ^
      69 |
      70 |     const updatedUser = await payload.update({
      71 |       collection: 'users',

      at Object.toBeNull (test/_community/int.spec.ts:68:34)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        7.803 s
```

Manual test:


https://github.com/payloadcms/payload/assets/208149/6741ee75-a512-44c8-8172-3de43a9b84d9

Returning undefined in [this line](https://github.com/payloadcms/payload/blob/d954ceb744844e26802b0ad0c42d8ba17a7178df/packages/payload/src/auth/baseFields/apiKey.ts#L10) seems to be sufficient to solve the issue and make all tests pass:
```
const encryptKey: FieldHook = ({ req, value }) =>
  value ? req.payload.encrypt(value as string) : undefined
```
