### ISSUE TITLE
node 21 error

### ISSUE THREAD

**Issue by Tcoding12** [payloadcms/payload#5751]
### Describe the Bug

had some issue with using node version 21 when accessing the admin panel  .. kept getting a styling  error  but it's working totally fine now  using   node version 20

### To Reproduce

![imagess](https://github.com/payloadcms/payload/assets/78769953/7c1bef0c-5416-48e9-b733-2e7f90eca9a8)

### Payload Version

2.12.1

**Comment by AlessioGr** [comment]
Looks like this was an issue in Node.JS and has been fixed! See: https://github.com/sass/dart-sass/issues/2127

If this is still an issue with the latest Node 22 version, please open up a **new** issue and include a minimal reproduction following our [reproduction guide](https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md). Thank you!
