### ISSUE TITLE
With plugin-nested-docs, I cannot save the page when editing a locale other than the default.

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload#5764]
alpha 55, postgres

I can edit my default locale's page fine, with `@payloadcms/plugin-nested-docs` and save it.

If I switch locales to a locale other than my default, I get an error in the parent field, saying that it is invalid.

![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/38236585/b2c63f41-be7b-4919-a1cc-9ae3294f74df)

Reselecting the parent document doesn't do anything.

It simply makes it impossible to use different locales.

**Comment by jmikrut** [comment]
Fixed in #5778

Will backport to 2.x if needed
