### ISSUE TITLE
Public assets (fonts) are not added with beta init script

### ISSUE THREAD

**Issue by osterkraft** [payloadcms/payload#5785]
### Describe the Bug

The `/public/payload` assets folder doesn't get created or populated when adding Payload to an existing Next project, and as a result the default fonts are missing.

Copying the folder from https://github.com/payloadcms/payload-3.0-demo/tree/main/public/payload resolves the issue

### To Reproduce

Install blank Next project
`npx create-next-app@"14.2.0-canary.23"` (needed to use this version otherwise init crashed)

Init Payload
`npx create-payload-app@v3.0.0-beta.3`

### Payload Version

v3.0.0-beta.3

**Comment by paulpopus** [comment]
I don't think this issue is still applicable since it was submitted. We will also change the default font out to websafe fonts with fallbacks instead of enforcing any one particular font for the admin panel.
