### ISSUE TITLE
Duplicating a published version-enabled document results in a published copy

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#5786]
### Link to reproduction

https://github.com/hdodov/payload/tree/mcve-duplicate-published

### Describe the Bug

When you have a document that is version-enabled and you duplicate it, you'd expect the resulting document to always be a draft, since you probably want to modify something, hence duplicating it.

### To Reproduce

1. Clone the repo https://github.com/hdodov/payload/tree/mcve-duplicate-published
2. Start MongoDB
3. `npm run dev _community`
4. Open the admin
5. Publish a post
6. Duplicate it
7. You'll see that the duplicated post is already published

### Payload Version

2.11.2

### Adapters and Plugins

None

**Comment by DanRibbens** [comment]
In v3 I made it so that duplicate will make it as a draft. I agree with this. The question is do we go back and change it for main, now?

It would be a minor change. In a similar issue, I also want to make restore always make a draft.
