### ISSUE TITLE
Non-translated word "document" when creating a record

### ISSUE THREAD

**Issue by CherryDT** [payloadcms/payload#5796]
### Describe the Bug

Creating a new record in a collection in the admin shows this screen, with the untranslated word "document". I can't find it in the i18n file either.

In fact I believe this would better be the singular of the collection name anyway and not statically "document".

![image](https://github.com/payloadcms/payload/assets/6010463/4ae872e9-a04a-4741-8c6c-2fe0676325ac)

### To Reproduce

Change admin language to German, create a record in a collection.

### Payload Version

2.12.1

### Adapters and Plugins

db-mongodb, bundler-webpack

**Comment by JessChowdhury** [comment]
Hi @CherryDT I have opened a PR [here](https://github.com/payloadcms/payload/pull/5889) to add a translation for the word `document`. 

You can absolutely render the collection name here instead by providing a `label` within your collection config. Your screenshot appears to be from the default users collection - you can still add a label to this collection by passing your own collection config with the slug `users`.

**Comment by CherryDT** [comment]
@JessChowdhury Hm, it doesn't seem to work though. My collections all do have a `label` and it works elsewhere such as in the page title and in the deletion confirmation (both of which show the singular label), but here is keeps saying just "document".

**Comment by CherryDT** [comment]
@JessChowdhury Could please reopen this issue? It's not solved.

**Comment by CherryDT** [comment]
Nvm, perhaps it's best to put this second part into a new issue.
