### ISSUE TITLE
Default value not selected by default when creating a new user

### ISSUE THREAD

**Issue by RATIU5** [payloadcms/payload#5810]
### Describe the Bug

I just noticed when creating a new user, the default selection for my user collection's role is all lowercase. I didn't think much of it, but when I pressed save, I got an unclear error. I then noticed that there was no selection highlighted brightly. When I select an option, it's background highlights brightly. Then I pressed save and it worked. I tried going back and adding the required property to the object and it still gave me the same error "Something went wrong" and the field was not highlighted red like the others.

### To Reproduce

1. `npx create-payload-app@beta`
2. Add the following as one of the user's fields:
```js
{
  name: "role",
  access: {
    create: hasAdminAccess,
    update: hasAdminAccessButNotFirstUser,
  },
  defaultValue: ["editor"],
  hasMany: false,
  hooks: {
    beforeChange: [ensureFirstUserIsAdmin],
  },
  options: [
    {
      label: "Admin",
      value: "admin",
    },
    {
      label: "Editor",
      value: "editor",
    },
    {
      label: "Viewer",
      value: "viewer",
    },
  ],
  type: "select",
},
```
3. `npm run dev`
4. Navigate to `http://localhost:3000/admin/collections/users/create` to see the error

### Payload Version

v3.0.0-beta.6

### Adapters and Plugins

db-postgres

**Comment by paulpopus** [comment]
Hey @RATIU5 based on my testing here it looks like your default value `type` is wrong, because your field is not expecting an array it should be `defaultValue: "editor",` just the string on its own

This worked in my testing, can you confirm? I'll reopen the issue if it's reproduced in a different manner
