### ISSUE TITLE
[3.0 Beta] Wrong @payload-config path in create-payload-app

### ISSUE THREAD

**Issue by janus-reith** [payloadcms/payload#5812]
### Describe the Bug

When using `create-payload-app` on an existing nextjs application, the `tsconfig.json` is updated to add
```
 "@payload-config": [
        "./src/payload.config.ts"
]
```

to your `compilerOptions.paths`.
This seems to always assume a `"compilerOptions.baseUrl": "."` (Or none set, didn't check).

In my case, `baseUrl` was set to `src`, so the correct path would be:
```
"@payload-config": [
        "./payload.config.ts"
]
```

The setup script should try to get the path to `payload.config.ts` relative to your `baseUrl`.

### To Reproduce

1. Create a new nextjs application, set "compilerOptions.baseUrl": "src" in your `tsconfig.json`
2. Run `pnpm dlx create-payload-app@beta` (pnpm is what I used, probably same with npx)
3. Start dev mode, observe `Module not found: Can't resolve '@payload-config'`

### Payload Version

3.0.0-beta.6

**Comment by ilai-tro-dev** [comment]
Same thing using npx with version of payload: 2.12.1, i think it could be related to this [ticket](https://github.com/payloadcms/payload/issues/5230) and it's definitely a bug.
