### ISSUE TITLE
[3.0 Beta] Plugin-SEO has "exports": null in package.json

### ISSUE THREAD

**Issue by janus-reith** [payloadcms/payload#5815]
### Describe the Bug

Not sure how this happens since exports are present in the branch:
https://github.com/payloadcms/payload/blob/c70dcb6a598911117dd2824a0288376ca5e7502b/packages/plugin-seo/package.json#L49-L54

For some reason, the installed module's `package.json` has:
`"exports": null,`

### To Reproduce

1. (p)`npm init`
2. (p)`npm install @payloadcms/plugin-seo@3.0.0-beta.6 `
3. `cat node_modules/@payloadcms/plugin-seo/package.json | grep exports`

Tried with both npm and pnpm to rule out any package manager conflict.

### Payload Version

3.0.0-beta.6

**Comment by paulpopus** [comment]
Hey @janus-reith On the latest `beta.10` I'm not seeing this occur at all, neither in npm or pnpm

```json
"exports": {
    ".": {
      "import": "./dist/index.js",
      "require": "./dist/index.js",
      "types": "./dist/index.d.ts"
    }
  },
```

I'm going to assume it's been fixed in one of the versions but will re-open if you see this again on the latest version

**Comment by janus-reith** [comment]
> I'm going to assume it's been fixed in one of the versions but will re-open if you see this again on the latest version

Indeed, just checked and its was fixed in beta.10:
https://github.com/payloadcms/payload/commit/80496aa94cb2980a84b04dc784a132a1e97a4209
