### ISSUE TITLE
Nested Docs URL conflicts when using same slug with different parents

### ISSUE THREAD

**Issue by truthseekers** [payloadcms/payload#5879]
### Describe the Bug

I am allowed to use the same slug with different parents, but the front end does not pull the correct page when following your nested-docs examples. Creating these parent-child relationships causes problems:

/service-one/
/service-one/location-one
/service-two/
/service-two/location-one

Visiting localhost:3001/service-two/location-one displays the /service-one/location-one page.

### To Reproduce

Follow these steps to setup payload: https://github.com/payloadcms/payload/tree/main/examples/nested-docs/payload

Follow these steps to setup next with app router: https://github.com/payloadcms/payload/tree/main/examples/nested-docs/next-app

Create parent and child pages with same slug but different parents to experience problem. Example:

/plumbing/
/plumbing/dallas/
/roofing/
/roofing/dallas

And The app will not pull the correct page when trying to visit /roofing/dallas or /plumbing/dallas

### Payload Version

"latest" (says 2.4 in node_modules)

**Comment by sarfarazsiddiquii** [comment]
can i work on this issue?

**Comment by truthseekers** [comment]
> can i work on this issue?

If you are talking to me then absolutely. I don't see why the owner would mind either.

**Comment by DanRibbens** [comment]
I assigned you @sarfarazsiddiquii so we don't duplicate efforts on our end.

Thanks for offerring you help!

**Comment by sarfarazsiddiquii** [comment]
@DanRibbens , I've submitted a pull request that addresses this issue. 
I'd appreciate your feedback and any suggestions for improvement. 
Thanks!
