### ISSUE TITLE
Can't install new project on M1 Mac

### ISSUE THREAD

**Issue by loremipson** [payloadcms/payload#589]
# Bug Report

Dependencies fail to install. Seems to hang up and die on `node-sass` and/or `libsass` dependencies. Looks like there's known issues with `node-sass` support for M1? The errors thrown aren't particularly clear or seemingly helpful.

https://github.com/sass/node-sass/issues/3033

## Possible Solution

Not sure yet, I've tried different versions of `node` (14, 16, and 18) with no difference. 

## Steps to Reproduce

On an M1 Mac, try to run `npm i` or `yarn` in a newly created project via `create-payload-app`, or `npm init -y && npm i --legacy-peer-deps payload` in a blank directory.

**Comment by jmikrut** [comment]
Hey @loremipson — we're on this. Looks like we might need to move away from `node-sass` and / or `libsass` but it should be doable. We're gonna get our hands on an M1 to test with so we can ensure support appropriately. Will try and have a fix out for this ASAP.

Thanks for the report!

**Comment by accuser** [comment]
Not just M1 Mac - `node-sass` fails to build on Intel Mac too (I've tried both).

**Comment by PegasisForever** [comment]
I solved this by:

1. Install [nvm](https://github.com/nvm-sh/nvm)
2. (optionally) remove your old system wide node to let nvm take control all node installations to avoid confusion
3. Install node 16 (arm): `nvm install 16`
4. Install node 14 which is x64 only: `arch -x86_64 nvm install 14 --shared-zlib`
5. Switch your node version by `nvm use <14 or 16>`, if you switch to node 14, every time you run node or npm, you are running node in x64 emulation and will be compatible with `node-sass`. Similarly, switch to node 16 to use the arm version of node and npm.
6. Delete old `node_modules`
7. With node version set to 14, try install payload again.

**Comment by limegorilla** [comment]
Can confirm @PegasisForever's answer seems to work - I was already using `nvm` on my M1 Pro equipped MacBook and had no issues installing on running Payload

**Comment by limegorilla** [comment]
I was able to run this fine in on my M1 Pro equipped Mac - I do use `nvm` but I installed it with it's default settings (via homebrew) and installed Node with `nvm install lts` for Node 16.13

No issues or anything!

**Comment by Catdaemon** [comment]
My team had this issue. The fix was to ensure `python` (not `python3`) is configured in `$PATH`, then everything worked fine.

**Comment by DanRibbens** [comment]
Great feedback from all the others who have resolved various issues with M1 compatibility!

We're working on removing node-sass as a dependency: https://github.com/payloadcms/payload/pull/605

**Comment by frankievalentine** [comment]
Builds fine with Node 14.9.3, but doesn't build with current Node LTS 16.15.1 & previous build 16.15.0.

```
env: python: No such file or directory
gyp ERR! node -v v16.15.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
```

**Comment by etmartinkazoo** [comment]
I had difficulties with my M1 Mac but can confirm all worked flawlessly with Node 14 LTS.

**Comment by wiesson** [comment]
Pnpm can do things such as 

```Javascript
function readPackage(pkg) {
  if (pkg.dependencies && pkg.dependencies['node-sass']) {
    pkg.dependencies['node-sass'] = 'npm:sass@^1.52.3'
  }
  return pkg
}

module.exports = {
  hooks: {
    readPackage
  }
}
```

to monkey-patch certain packages but then I get runtime errors such as 

```
payload-cms/node_modules/.pnpm/payload@0.17.3_qrmjd43x4wacb3epwy4isvwony/node_modules/payload/components/forms.ts:1
export {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
```

😅

**Comment by loremipson** [comment]
> I had difficulties with my M1 Mac but can confirm all worked flawlessly with Node 14 LTS.

I'm happy to see others are having luck with this, but it did not work for me. I could easily be wrong here, but it looks like those with success are using `nvm`, which I don't use. I tried installing `node@14` with brew and had the same results.

Just clarifying, for anyone coming this way from Google.

**Comment by wiesson** [comment]
> We're working on removing node-sass as a dependency: https://github.com/payloadcms/payload/pull/605

Has this already been released?

**Comment by jmikrut** [comment]
@wiesson — thank you for confirming! I am going to close this issue for now, but for everyone else in this thread, please give `0.18.0` a shot.

Thank you!
