### ISSUE TITLE
Payload-Lexical: link tooltip pops up on selecting a decorator node

### ISSUE THREAD

**Issue by vibhor-web-headout** [payloadcms/payload#5909]
### Describe the Bug

Upon selecting a custom Decorator node, the tooltip for LinkNode displays and positions itself next to the Decorator node.
This does not happen for plain text present in lexical.

The selection seen in the Link Editor plugin, for this scenario, is a `NodeSelection`. It bypasses the flow mentioned [here](https://github.com/payloadcms/payload/blob/6186493246157b4d4b33c8c47378f08581315942/packages/richtext-lexical/src/field/features/Link/plugins/floatingLinkEditor/LinkEditor/index.tsx#L102) and relies on window selection to display the tooltip.

https://github.com/payloadcms/payload/assets/114465851/8d2ff46d-4893-42e9-bc08-d1ff88ce8c6d

### To Reproduce

1. Create a decorator node. This node should will not be editable.
2. Add a command to mark the node as selected if anywhere inside the node is clicked.
3. This should display the link tooltip below the decorator node.

### Payload Version

2.11.2

### Adapters and Plugins

@payloadcms/richtext-lexical: 0.7.0

**Comment by AlessioGr** [comment]
Fixed this in #6241 - will be available in the next 3.0 release! Do note that this likely won't get backported to 2.0
