### ISSUE TITLE
[3.0] JSON Field crashes if no default value provided

### ISSUE THREAD

**Issue by sahasprajapati** [payloadcms/payload#5913]
### Describe the Bug

When no default value is provided to a json field, it crashes the system.

version: 3.0.0-beta.11

Error:
![image](https://github.com/payloadcms/payload/assets/19515458/4b8a18c8-179b-412a-8f0f-897bcac933c9)

### To Reproduce

1. Install the beta version of payload
2. Add JSON field with no default value

```
    {
      type: 'json',
      name: 'test',
    }
```
3. Run `pnpm dev`

### Payload Version

3.0.0-beta.11

**Comment by denolfe** [comment]
I believe this was caught and fixed in this open PR: https://github.com/payloadcms/payload/pull/5898

**Comment by kendelljoseph** [comment]
Yep - we made a separate PR:
https://github.com/payloadcms/payload/pull/5876

**Comment by denolfe** [comment]
Fix will be in next beta release.
