### ISSUE TITLE
[3.0 CLI] Mongodb used when Postgres is selected

### ISSUE THREAD

**Issue by RATIU5** [payloadcms/payload#5918]
### Describe the Bug

When using the CLI to install a new project, I selected a PostgresDB and when it installed the dependencies, there was no postgres adapter. I had to install it manually to fix it.

### To Reproduce

1. `npx create-payload-app@beta`
2. Select Postgres as the database
3. After the install, notice the Postgres adapter is missing

### Payload Version

v3.0.0-beta.11

### Adapters and Plugins

db-postgres

**Comment by brianFrizzera** [comment]
How did you manually install?

**Comment by brianFrizzera** [comment]
Thanks

> > How did you manually install?
> 
> Added
> 
> ```json
> "@payloadcms/db-postgres": "beta",
> ```
> 
> as a dep in my `package.json` and ran `npm i`.

**Comment by denolfe** [comment]
Closed by #5921
