### ISSUE TITLE
table names changed updating from 2.11.2 to 2.13.0

### ISSUE THREAD

**Issue by DanRibbens** [payloadcms/payload#5938]
I've run into this without having changed names myself updating from 2.11.2 to 2.13.0.

> ✔ Warnings detected during schema push: 
> 
> · You're about to change version__status column type from enum__interests_v_version_status to _enum__interests_v_version_status_v with 2 items
> · You're about to change version_country column type from enum__organisations_v_version_country to _enum__organisations_v_version_country_v with 1 items
> · You're about to change version__status column type from enum__news_posts_v_version_status to _enum__news_posts_v_version_status_v with 17 items
> · You're about to change version_authorisation column type from enum__members_v_version_authorisation to _enum__members_v_version_authorisation_v with 100 items
> · You're about to change version_personTitle column type from enum__members_v_person_title to _enum__members_v_person_title_v with 100 items
> 
> DATA LOSS WARNING: Possible data loss detected if schema is pushed.
> 
> Accept warnings and push schema to database? … yes
> error: column "version__status" cannot be cast automatically to type _enum__interests_v_version_status_v
>     at /data/projects/ac/payload/node_modules/pg-pool/index.js:45:11
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at DrizzleORMPgClient.query (/data/projects/ac/payload/node_modules/drizzle-kit/payload.js:34498:21)
>     at apply (/data/projects/ac/payload/node_modules/drizzle-kit/payload.js:36648:9)
>     at Object.connect (/data/projects/ac/payload/node_modules/@payloadcms/db-postgres/src/connect.ts:124:3)
>     at BasePayload.init (/data/projects/ac/payload/node_modules/payload/src/payload.ts:359:7)
>     at getPayload (/data/projects/ac/payload/node_modules/payload/src/payload.ts:430:22)
>     at initHTTP (/data/projects/ac/payload/node_modules/payload/src/initHTTP.ts:33:19)
>     at Payload.init (/data/projects/ac/payload/node_modules/payload/src/index.ts:17:21)

Example before and after column type names:
```
enum__interests_v_version_status
_enum__interests_v_version_status_v
```

I'm guessing the new types/type names are caused by https://github.com/payloadcms/payload/pull/5045 ?

Edit: I've now nuked the database in dev allowing Payload to recreate the tables upon running, and column type name is now:
```
_enum__interests_v_version_status_v
```

_Originally posted by @DavidOliver in https://github.com/payloadcms/payload/issues/4677#issuecomment-2066931438_

**Comment by DanRibbens** [comment]
Thanks @DavidOliver for the comment on the other issue. I think this is unrelated to #4677 so I made this new issue to track it.

**Comment by DavidOliver** [comment]
@DanRibbens , thanks! I'll look out for a new release and then recreate the database to get the correct names.
