### ISSUE TITLE
Incorrect collection displayed in list deletion toast

### ISSUE THREAD

**Issue by CherryDT** [payloadcms/payload#5966]
### Describe the Bug

When deleting items from the list view, an incorrect collection name is displayed in the toast.

![image](https://github.com/payloadcms/payload/assets/6010463/105138df-8f1b-4152-889a-fc8f85531ad5)

I'm on the articles list ("Artikel") but the toast talks about media files being deleted "1 Mediendatei erfolgreich gelöscht".

Note that the only link between articles and media files would be the `image` field which is a relationship to the media collection.

The articles collection has labels as follows (nothing related to media here):

```
  slug: 'articles',
  labels: {
    singular: {
      de: 'Artikel',
      en: 'Article'
    },
    plural: {
      de: 'Artikel',
      en: 'Articles'
    }
  },
```

### To Reproduce

(I'm not sure if all of this is necessary.)

Create an article collection and a media collection. Add an upload field related to the media collection into the article collection. Make the whole thing with i18n in two languages. Delete an article from the list view.

### Payload Version

2.12.1

### Adapters and Plugins

db-mongodb, bundler-webpack

**Comment by JessChowdhury** [comment]
Hi @CherryDT, please provide a minimal production of this issue. I have tried to recreate with a basic setup and have not been able to reproduce the incorrect toast message.

**Comment by JessChowdhury** [comment]
@CherryDT still cannot replicate this behavior so I will close this for now - if you can provide a reproduction, feel free to re-open. Thanks!
