### ISSUE TITLE
Server runtime error when importing images for front-end

### ISSUE THREAD

**Issue by PegasisForever** [payloadcms/payload#600]
# Bug Report

If you import images in [Custom Components](https://payloadcms.com/docs/admin/components),
After compiling, the image is copied to `build` (for front-end) but not `dist` (for back-end)
When running the back-end server, it tries to import the non-existent image from `dist`, causing error.

## Expected Behavior

The imported image should also be copied to `dist`.

## Current Behavior

The imported image is not copied to `dist`.

## Steps to Reproduce

1. use an imported image in [Custom Components](https://payloadcms.com/docs/admin/components)
2. `yarn build`
3. `yarn serve`
4. Error

## Detailed Description

Payload version: v0.17.2

**Comment by jmikrut** [comment]
Hey @PegasisForever — this is actually something that affects most all TypeScript projects. Typically the package `copyfiles` is used to copy all non-TS files that are still necessary into a `/dist` folder or similar.

Here are our build scripts that we typically use at TRBL:

```
    "copyfiles:src": "copyfiles -u 1 src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png} dist/",
    "copyfiles": "yarn copyfiles:src",
    "build:payload": "PAYLOAD_CONFIG_PATH=src/payload.config.ts payload build",
    "build:server": "tsc",
    "build": "yarn build:server && yarn build:payload && yarn copyfiles"
```

You'll just need to make sure that `copyfiles` is installed locally via NPM and then boom - you're set.
