### ISSUE TITLE
Upload collection path infinite redirects when empty

### ISSUE THREAD

**Issue by BraianPita** [payloadcms/payload#6013]
### Describe the Bug

When I create an upload collection as shown on the 'website template' where they do:

```ts
  upload: {
    staticDir: path.resolve(__dirname, '../../../media'),
  },
```
It creates an endpoint for the collection that lets me fetch the files (e. g. /media/my-file).

However, if I am hosting on example.ltd, and I go to `https://example.ltd/media`, it starts redirecting infinitely between /media and /media/.
![image](https://github.com/payloadcms/payload/assets/54162188/bbbd22f6-aef5-464a-bdbc-9512ff55632c)

Resulting in `ERR_TOO_MANY_REDIRECTS`.

### To Reproduce

Create a collection with slug 'media', that allows uploads, and go to /media on your site frontend using the 'website template' found on this repo.

### Payload Version

2.11.1

### Adapters and Plugins

Website Template Fresh Install

**Comment by JessChowdhury** [comment]
Hi @BraianPita, I cannot replicate this behavior -  have you made any other changes to the template that might be causing this?

Using the live demo, we have an uploads collection with `/media` as the the static directory. So, you can access the files as 
 you'd expect here: https://demo.payloadcms.com/media/project-eng-4.jpg
Then I added a temporary page with the slug `media`, navigating here works as expected: https://demo.payloadcms.com/media. Hitting the url with a trailing `/` correctly redirects to the `/media` page.

I'm going to close this issue for now, if you're able to provide a reproduction of this behavior we can re-open and investigate.
