### ISSUE TITLE
I created the project and this is showing up related to nodemon

### ISSUE THREAD

**Issue by AyaanMAG** [payloadcms/payload#602]
# Bug Report

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

![Screenshot_7](https://user-images.githubusercontent.com/63659414/170441203-bbb8e7d9-3057-4313-bff6-a3138c39a6e6.png)

**Comment by jmikrut** [comment]
Hey @AyaanMAG — this error is telling you that you do not have `express` installed. Please make sure that you install it in your project. `yarn add express` should be what you need. 

This is not an issue with Payload, so I am going to close it. Thank you!

**Comment by AyaanMAG** [comment]
Hey I'm again facing a different error and I have a feeling there'll be more, is there somewhere where we can chat about this perhaps signal or Instagram or your email you have on your profile
