### ISSUE TITLE
After the payload is upgraded, the graphql type changes

### ISSUE THREAD

**Issue by blueMountain007** [payloadcms/payload#6022]
### Link to reproduction

https://payloadcms.com/

### Describe the Bug

After upgrading the payload from 1.11.1 to 2.3.1, I encountered the following error: Variable "$category" of type "String" Variable "$tags" of type "[String] " used in position expecting type "[JSON]".

```typescript
{
    slug: 'seo-resource-template-pages',
    labels: {
      singular: 'Template Page',
      plural: 'Template Pages',
    },
    fields: [
        {
            name: 'category',
            label: 'Category',
            type: 'relationship',
            relationTo: 'categories',
            index: true,
            required: true,
            filterOptions: {
              id: { equals: 'car-insurance' },
            },
            admin: {
              position: 'sidebar',
              description: 'For now, we only support car-insurance.',
            },
        },
        ...
    ]
}
```

### To Reproduce

**When the payload version is 1.11.1**
<img width="1199" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/d0bdbe6e-73f9-41d3-ad57-db3fc687e24d">

**After the payload is upgraded to v2.3.1**
<img width="1203" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/bbe1c4e1-fbc9-482b-a33d-60ba26352b79">

### Payload Version

2.3.1

**Comment by jmikrut** [comment]
Hey @blueMountain007 — this is expected as a breaking change from v1 to v2. If it was not documented in the migration guide, it should have been. But we did indeed intend on this.

Looking forward, moving from v2 to v3 will keep the same behavior as v2, so if you can adjust your queries to match the new shape on v2, that is what we would recommend.

Let me know if you need a hand!

**Comment by blueMountain007** [comment]
@jmikrut  Got it, thank you. Can you send me a PR related to this change? Quite curious
