### ISSUE TITLE
(db-postgres): localized group and localized fields inside of group are broken.

### ISSUE THREAD

**Issue by r1tsuu** [payloadcms/payload#6029]
### Link to reproduction

https://github.com/r1tsuu/payload/tree/postgres-reproduction

### Describe the Bug

Given the collection config:
```ts
import type { CollectionConfig } from 'payload/types'

export const localizedSlug = 'localized '

export const Localized: CollectionConfig = {
  slug: localizedSlug,
  fields: [
    {
      name: 'groupLocalized',
      localized: true,
      type: 'group',
      fields: [
        {
          name: 'title',
          type: 'text',
        },
      ],
    },
    {
      name: 'group',
      type: 'group',
      fields: [
        {
          localized: true,
          name: 'title',
          type: 'text',
        },
      ],
    },
  ],
}
```
In both cases (localized inside and localized group itself) data is not saved to the database for properly, from my [integration test](https://github.com/r1tsuu/payload/blob/postgres-reproduction/test/_community/int.spec.ts) i have this (null data for last row with en locale): 
<img width="423" alt="image" src="https://github.com/payloadcms/payload/assets/64744993/7d6c8148-4da2-4320-a604-0dc1b98040f3">
In the admin ui it just shows you the data in wrong language

Found this while was writing integration test for my PR https://github.com/payloadcms/payload/pull/5942 

### To Reproduce

Run
`pnpm test int:postgres _community` - doesnt pass
`pnpm test int _community` - passes with mongodb, which should confirm that something is wrong.

### Payload Version

2 and 3

### Adapters and Plugins

db-postgres

**Comment by r1tsuu** [comment]
i think i could handle it, can assign to me

**Comment by sebastianpulak** [comment]
Any progress on this issue? We just ran into this problem as well.

**Comment by r1tsuu** [comment]
> Any progress on this issue? We just ran into this problem as well.

I opened a PR https://github.com/payloadcms/payload/pull/6158

**Comment by DanRibbens** [comment]
The PR looks great! Good work @r1tsuu, are you able to resolve the merge conflict and we'll take it from there? We should be able to get this merged and ready for the next release.

**Comment by DanRibbens** [comment]
I am closing this. It will be out in the next release of 3.0 beta.

I may do a backport of all the database changes made in beta back to 2.x based on demand.

Thanks @r1tsuu for this fix.
