### ISSUE TITLE
Bulk publish not doing anything 

### ISSUE THREAD

**Issue by rymate1234** [payloadcms/payload#6055]
### Link to reproduction

https://github.com/rymate1234/payload-draft-reprod

### Describe the Bug

Although bulk editing now works great, there's still a minor issue whereby the bulk publish option doesn't work

Quite minor as bulk editing allows you to also bulk publish and this all works fine

### To Reproduce

https://github.com/payloadcms/payload/assets/581104/17cb1688-24f6-4782-95ce-76f2770c3a66

### Payload Version

2.14.0

**Comment by DanRibbens** [comment]
Hey @rymate1234,

I really appreciate you opening this issue. It was a simple fix for something we missed. Thanks for being patient while we iron out these cases that didn't have proper tests.

**Comment by rymate1234** [comment]
@DanRibbens thank you for all of the assistance with this! :)

Will look out for a 2.x release with this fix in 🙏
