### ISSUE TITLE
there is no parameter $1

### ISSUE THREAD

**Issue by thedevdavid** [payloadcms/payload#6094]
### Describe the Bug

If Payload v3 is added to an existing app with data in the DB, it fails to initialize payload tables.

```
error: there is no parameter $1
    at /node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (/node_modules/drizzle-kit/payload.js:34498:21)
    at async /node_modules/drizzle-kit/payload.js:2259:46
```

### To Reproduce

- set up a nextjs app with a postgres DB
- add any random table to the DB
- install Payload v3
- start dev server and open `/admin`

### Payload Version

3.0.0-beta.18

**Comment by jmikrut** [comment]
If there is an existing database with its own schema / data, you would need to write a Payload config to match its shape perfectly before starting up. It’s not expected that Payload will instantly work with any existing database - at least not right now.

**Comment by thedevdavid** [comment]
@jmikrut could you explain this a bit more, please?

Assuming I have a DB schema with 30+ tables and complex relationships (and it's possibly evolving), how (and why) would I have to add this to the Payload config?

**Comment by thedevdavid** [comment]
> Does this make sense?

Ah, this makes sense. Is it possible to specify a separate Postgres schema for Payload to use? So, I keep my core app DB in the `public` schema, and Payload would use something like `content`?

> why you're interested in bringing 30+ pre-existing tables into Payload? What would your best-case scenario look like here? What would you like to have the result look like / function like after having Payload connect to your existing DB?

Sure. So, I have an existing app where I'd like to integrate Payload as a CMS. It would be used mainly to edit a couple of articles a month and handle some files.
The app has already been using Postgres for the core business functionality, so I thought it would make sense to use the DB I already have instead of creating a separate one for Payload. 

I also plan to customize Payload admin so the admin user would be able to use some fields to query data from the core app database.
Example: App DB has an 'artists' table and in Payload admin, when editing the artists subpage, the admin would be able to choose "featured artists" from the core app DB.

**Comment by jmikrut** [comment]
>  Is it possible to specify a separate Postgres schema for Payload to use? 

Yes - pass `schemaName` to the Postgres adapter and you'll be golden! This defaults to `public` but can be changed. Payload will then use the schema you set.
 
https://payloadcms.com/docs/database/postgres#options

Everything else you mentioned should then work perfectly there!

**Comment by thedevdavid** [comment]
> Yes - pass `schemaName` to the Postgres adapter and you'll be golden! This defaults to `public` but can be changed. Payload will then use the schema you set.

Hmmm.. I tried this right now but still getting the same error.
<img width="947" alt="image" src="https://github.com/payloadcms/payload/assets/15244882/a921dda1-2496-4667-bb8d-703a039bc779">

<img width="685" alt="image" src="https://github.com/payloadcms/payload/assets/15244882/4a0d1702-1e7d-44f8-ac6b-3a8efd650e1b">

**Comment by thedevdavid** [comment]
> The error might actually be related to your connection string then, in that case. Have you double-checked that your connection string is valid?

Yes, and I tried multiple databases. I tried a local postgres running in Docker, and with 2 Supabase projects. The only time I was able to get through this was when trying a completely new DB.

**Comment by thedevdavid** [comment]
@jmikrut I just updated to the latest beta (24) and still having the same issue.

```
⨯ unhandledRejection: error: there is no parameter $1
    at /app/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DrizzleORMPgClient.query (/app/node_modules/drizzle-kit/payload.js:34498:21)
    at async /app/node_modules/drizzle-kit/payload.js:2259:46 {
  length: 95,
  severity: 'ERROR',
  code: '42P02',
  detail: undefined,
  hint: undefined,
  position: '175',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_expr.c',
  line: '838',
  routine: 'transformParamRef'
}
```

```
{
  length: 95,
  name: 'error',
  severity: 'ERROR',
  code: '42P02',
  position: '175',
  file: 'parse_expr.c',
  line: '838',
  routine: 'transformParamRef'
}
```

**Comment by thomaslittle** [comment]
Can confirm this is an issue when trying to setup payload into an already existing supabase project - I tried adding a new `payload` schema and passing `  db: postgresAdapter({
    pool: {
      connectionString: process.env.DATABASE_URI || "",
      schemaName: "payload",
    },
  }),`
  
  still results in `Error: there is no parameter $1` when attempting to access `/admin`.
