### ISSUE TITLE
Custom React components page uses incorrectly capitalized field names

### ISSUE THREAD

**Issue by CherryDT** [payloadcms/payload#6105]
# Documentation Issue

At https://payloadcms.com/docs/admin/components#base-component-overrides, apparently some field names are incorrectly capitalized, such as `BeforeDashboard`, which should actually be `beforeDashboard` (using `BeforeDashboard` with capital `B` has no effect).

**Comment by jmikrut** [comment]
This is because “beforeDashboard” is an _array_ of React components and not a single React component like other spots in our code which have title-case naming conventions.

**Comment by CherryDT** [comment]
Yes, I know, but the documentation still incorrectly shows it with capital `B`!
