### ISSUE TITLE
Preferences API route is translated

### ISSUE THREAD

**Issue by MrFriggo** [payloadcms/payload#6124]
### Describe the Bug

Payload preferences API route are translated and it might cause some problems afterwards.

`GET /api/payload-preferences/collapsed-Globální-groups 200 in 114ms`
`GET /api/payload-preferences/collapsed-Kolekce-groups 200 in 144ms`
_The route is translated in the same way as in the sidebar, but it should not (Refer to the picture)_
![EDzqmV0](https://github.com/payloadcms/payload/assets/29260719/ef980040-62f1-49ad-80ae-4636431b8ef7)

I believe that the translated name for collections and globals is getting into this function.:
[packages/ui/src/elements/NavGroup/index.tsx#L26C3-L26C53](https://github.com/payloadcms/payload/blob/2e77bdf11e325935bb6be0ebc5cfef5cfb8f08f7/packages/ui/src/elements/NavGroup/index.tsx#L26C3-L26C53)

### To Reproduce

* Switch to any language other than English.
* Run the application on localhost
* Try changing user preferences

### Payload Version

3.0.0-beta.19

**Comment by r1tsuu** [comment]
I just tested and it looks like it's not an issue on the latest Payload version - `3.11.0`.

The API route no longer depends on these labels, but rather only on `global`, `collection` and `collectionSlug` / `globalSlug`.
https://github.com/payloadcms/payload/blob/cf8c0ae95943535039951b2e6f8d4efcfff9918c/packages/next/src/views/Document/getDocPreferences.ts#L22-L27
<img width="620" alt="Image" src="https://github.com/user-attachments/assets/7540eb93-4789-4012-aa69-2c0dfa2e975d" />
