### ISSUE TITLE
Description Function not working in 3.0

### ISSUE THREAD

**Issue by dmnkl** [payloadcms/payload#6133]
### Describe the Bug

I am trying to follow the documentation on adding a function that returns a string for a description field but it does not seem to work in the 3.0 beta. It's working without issues in the stable release.

```typescript
admin: {
  description: ({ path, value }) =>
      `${typeof value === 'string' ? 20 - value.length : '20'} characters left (field: ${path})`,
}
```
gives the following error
```
Type '({ path, value }: { path: any; value: any; }) => string' is not assignable to type 'Description | undefined'.
  Type '({ path, value }: { path: any; value: any; }) => string' is not assignable to type 'LabelFunction'.
    Types of parameters '__0' and '__0' are incompatible.
      Type '{ t: TFunction; }' is missing the following properties from type '{ path: any; value: any; }': path, value
```
The only parameter being passed to the function is the translation? function.

### To Reproduce

Add a function to the description field in any collection

### Payload Version

3.0.0-beta.20

### Adapters and Plugins

db-postgres

**Comment by davelsan** [comment]
I can confirm that this happens on `3.0.0-beta.29`, with one caveat, the description component works, it's just the types that seem to be broken.

The `admin.description` signature points to the  `Description` type. I think it's just a matter of adding the `DescriptionComponent` to the union.

```ts
export type DescriptionFunction = LabelFunction;
export type DescriptionComponent = CustomComponent<FieldDescriptionProps>;
export type Description = DescriptionFunction | Record<string, string> | string;
export type FieldDescriptionProps = {
    CustomDescription?: React.ReactNode;
    className?: string;
    description?: Record<string, string> | string;
    marginPlacement?: 'bottom' | 'top';
    payload?: Payload;
};
```

@dmnkl, in 3.0 there is a new signature for the component type (see previous types), which is what you probably want to use. For example, this is one way you can extract the path and value now.

```ts
import React, { ComponentProps } from 'react';
import { DescriptionComponent } from 'payload/types';
import { FieldDescription } from '@payloadcms/ui/forms/FieldDescription';
import { useFieldProps } from '@payloadcms/ui/forms/FieldPropsProvider';
import { useFormFields } from '@payloadcms/ui/forms/Form';

export function CustomDescription(props: ComponentProps<DescriptionComponent>) {
  const { path } = useFieldProps();
  const { value } = useFormFields(([fields]) => fields[path]);

  const description = `${typeof value === 'string' ? 20 - value.length : '20'} characters left (field: ${path})`;

  return <FieldDescription {...props} description={description} />;
}
```

**Comment by davelsan** [comment]
I just saw the `beta.29` release announcement, so disregard the above. The new way to add custom descriptions works like a charm, HMR too!

https://discord.com/channels/967097582721572934/1215659716538273832/1238242171627245652
https://github.com/payloadcms/payload/releases

@dmnkl, I think this is now fixed.

**Comment by AlessioGr** [comment]
Closing this as it should be solved now! Previously, admin.description accepted both functions and Components, which are very hard to discern, as both are, in the end, functions. Caused some issues.

In beta.29, components now have to be added to admin.components.Description
