### ISSUE TITLE
"add block" button for richText lexical disappears if viewport width <= 1024px

### ISSUE THREAD

**Issue by timotgl** [payloadcms/payload#6137]
### Link to reproduction

https://demo.payloadcms.com/

### Describe the Bug

In a window with width 1024px or less the "+" button to insert a new block element into the lexical editor disappears. The button is not hidden via CSS, it's simply not in the DOM at all. It seems to be unrelated to the width of the richText textarea.

I could reproduce this on the official demo and also in our own project using payload 2.13.0.

This button is the only way to insert certain block nodes into lexical (relationship for example), so it shouldn't ever disappear.

### To Reproduce

Go to any edit viewing that displays a richText lexical field, like https://demo.payloadcms.com/admin/collections/posts/6630cf522af18a7500ef850a and reduce the browser window width to 1024px or less. Observe that the little "+" button that is normally shown on the left side of empty new lines is not shown at all.

### Payload Version

2.13.0

### Adapters and Plugins

the default ones (lexical for richText, not slate)

**Comment by AlessioGr** [comment]
Hey @timotgl 

I've partially resolved this in https://github.com/payloadcms/payload/pull/6144 by reducing the width at which the handles disappear.

For screen sizes smaller than 768px, it's not possible to keep those handles, as they do not fit in - instead, right now, the slash menu should be used to insert nodes like relationship nodes.

To further improve the UX on mobile, a sticky toolbar would help - which we're building right now (related: https://github.com/payloadcms/payload/discussions/3977 ). The goal is to have the sticky toolbar auto-appear for screen sizes smaller than 768px
