### ISSUE TITLE
Lexical: Floating select toolbar caret incorrectly positioned when selecting second line of text

### ISSUE THREAD

**Issue by timotgl** [payloadcms/payload#6139]
### Link to reproduction

https://demo.payloadcms.com/admin/collections/posts/6630dd6648cc4c160078c81f

### Describe the Bug

Select any word in the second line of text in the editor. The caret (little upside down triangle normally positioned on the floating toolbar) seems to be misplaced.

From the official demo:
<img width="1695" alt="Screenshot 2024-04-30 at 14 51 37" src="https://github.com/payloadcms/payload/assets/366377/dce4d023-8f41-47f0-902c-bbd7ead525da">

From our own project (payload 2.13.0):
<img width="147" alt="Screenshot 2024-04-30 at 14 55 27" src="https://github.com/payloadcms/payload/assets/366377/9df4ca54-e58e-4a9a-a3ac-7bdf4869849c">

For us, the first line is affected, the caret is positioned on top of the first icon in the toolbar.

Maybe related to https://github.com/payloadcms/payload/issues/4041

### To Reproduce

Select any word in the second line of text in the editor. The caret (little upside down triangle normally positioned on the floating toolbar) seems to be misplaced.

### Payload Version

2.13.0

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/6149
