### ISSUE TITLE
I have update the payload version from 1.15.0 to 2.13.0. After that when  run my project

### ISSUE THREAD

**Issue by komal1220** [payloadcms/payload#6174]
I have update the payload version from 1.15.0 to 2.13.0. After that when  run my project 
1. I can't see existing data of one of my collection in Admin UI.
2.I can see old collection data and version collection data in database. 
3. i have already versions:{drafts: true} property added in my collection file. when i comment out that code or set   versions: {
    drafts: false,
  },
  then I can see all the previously added data and new data.
  can you help me to solve this issue?

_Originally posted by @komal1220 in https://github.com/payloadcms/payload/discussions/6170_

**Comment by AlessioGr** [comment]
Closing this as I don't think this is an issue within payload. Check out this payload v1 => v2 migration guide, especially the section about migrating your data for versions. That will likely fix your issues: https://github.com/payloadcms/payload/releases/tag/v2.0.0
