### ISSUE TITLE
[3.0] Stripe package missing /types exports

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#6214]
### Describe the Bug

In the 2.0 stripe package, types were exported from `'@payloadcms/plugin-stripe/types'`, this should also work in the 3.0 update of the package.

### To Reproduce

Attempt to import a type from '@payloadcms/plugin-stripe/types'` in `test/plugin-stripe/config.ts`

### Payload Version

3.0-beta.24

**Comment by denolfe** [comment]
@paulpopus Let's do a few small updates here to get this package to follow our subpath exports pattern. See payload package for a good example.

Some items that will need to happen:

- [ ] Remove the types.* pointer files those are no longer used
- [ ] Add a src/exports/types.ts file
- [ ] Add a key to the exports and publishConfig exports. 
    "./*": {
      "import": "./src/exports/*.ts",
      "require": "./src/exports/*.ts",
      "types": "./src/exports/*.ts"
    }

**Comment by paulpopus** [comment]
This should be resolved now
