### ISSUE TITLE
v3 create-payload-app function incorrectly detects yarn

### ISSUE THREAD

**Issue by paulpopus** [payloadcms/payload#6231]
### Describe the Bug

When running `npx create-payload-app@beta` with a fresh setup it will sometimes install using `yarn` even though it hasn't been specified and you install using `npx`

### To Reproduce

Run `npx create-payload-app@beta` in a fresh directory and it should install using yarn instead of npm

### Payload Version

3-beta

### Adapters and Plugins

create-payload-app

**Comment by denolfe** [comment]
Closed by #6546
