### ISSUE TITLE
schemaName property is not respected in postgres adapter

### ISSUE THREAD

**Issue by thedevdavid** [payloadcms/payload#6266]
### Describe the Bug

It looks like the `schemaName` property is not respected. No matter what I type, the DB adapter wants to wipe my `public` schema when first opening the `/admin` route.

### To Reproduce

See similar: #5822 #6094

### Payload Version

3.0.0-beta.26

### Adapters and Plugins

db-postgres

**Comment by DanRibbens** [comment]
Fixed in https://github.com/payloadcms/payload/pull/7453
