### ISSUE TITLE
[Usability] Content writers couldn't figure out how to select an existing image in Page collection

### ISSUE THREAD

**Issue by grvk** [payloadcms/payload#6267]
# Steps to Reproduce
1. Clone [payload-3.0-demo-bugs](https://github.com/grvk/payload-3.0-demo-bugs)
_Note: it's based of the latest demo code + upgraded to `beta.25`_
2. `npm install` (node version `v18.20.2`)
3. `./start-database.sh`
4. `npm run dev`
5. Log in
6. Click on Media
7. Upload an image
8. Go back to Main Dashboard
9. Select Page collection
10. Choose an existing media
11. Select an existing image from the list (via checbox)

# Expected Result
"Save" button appears to select an image (or some other way)

# Actual Result
After selecting checkbox of the target image, UI doesn't really change. User can't easily select an existing image

# Recording

https://github.com/payloadcms/payload-3.0-demo/assets/4755076/802f8f57-31be-46b4-8994-093887c46919

**Comment by denolfe** [comment]
Moved to main repo as this is not unique to 3.0.

**Comment by jmikrut** [comment]
I think that what should be done here is to disable the ability to multi-select images in the `ListDrawer` in some contexts, such as the one demonstrated in the video in this issue.

**Comment by paulpopus** [comment]
I just checked and in v3 we hide the multi-select in the ListDrawer there and both the thumbnail and the title of the image/media are clickable to insert it.


https://github.com/user-attachments/assets/353ba5c6-6087-4a88-a80c-5d92ff711fa8
