### ISSUE TITLE
db-postgres: relationship field filterOptions returning unexpected results

### ISSUE THREAD

**Issue by JPrisk** [payloadcms/payload#6274]
### Link to reproduction

https://github.com/JPrisk/payload/tree/postgres-relationships

### Describe the Bug

This is a repeat of this [issue](https://github.com/payloadcms/payload/issues/5248) except i've created a new reproduction because @PatrikKozak was having difficulty reproducing the issue

### To Reproduce

The following steps require you to run `pnpm dev _community` with your `PAYLOAD_DATABASE` environment set for the following options:

MongoDB

1. navigate to `http://localhost:3000/admin/collections/posts`
2. navigate to the post titled "example post 2 [published]"
3. click the "Related Posts" dropdown
4. observe `[draft]` posts being filtered from the results

Postgres

1. navigate to `http://localhost:3000/admin/collections/posts/2`
2. click the "Related Posts" dropdown
3. observe `[draft]` posts being included in the results

### Payload Version

latest

### Adapters and Plugins

db-postgres

**Comment by JPrisk** [comment]
very likely a duplicate of [#5151](https://github.com/payloadcms/payload/issues/5151)

**Comment by PatrikKozak** [comment]
Hey @JPrisk - issue #5151 has been closed with this [PR](https://github.com/payloadcms/payload/pull/6358).

And thank you for the above reproduction! With your reproduction and using the `postgres` adapter, I'm observing that `drafts` are being filtered out.

Can you confirm with latest if you are still experiencing this?

**Comment by JPrisk** [comment]
Hey @PatrikKozak - thanks for releasing the fix, yes this can now be closed ✅
