### ISSUE TITLE
Payload not working anymore after upgrade to newest version

### ISSUE THREAD

**Issue by jonisapp** [payloadcms/payload#6313]
### Describe the Bug

Probably same as here : https://github.com/payloadcms/payload/issues/6062
I did nothing other than upgrade payload to the most recent version (2.16.1) before reverting to the previous version (2.11.0). The problem that appeared with the upgrade remains. 
![image](https://github.com/payloadcms/payload/assets/31998774/5da7a874-bd85-4824-b981-0e2ef568c9db)

### To Reproduce

Upgrade from 2.11.0 to 2.16.1.
If you revert to 2.11.0, the issue remains. 

### Payload Version

2.16.1

**Comment by paulpopus** [comment]
Hey @jonisapp can you show us your package.json?

Between upgrades have you tried removing the lock file and the node_modules folder in case there's a different version of react being cached?

**Comment by jonisapp** [comment]
> Hey @jonisapp can you show us your package.json?
> 
> Between upgrades have you tried removing the lock file and the node_modules folder in case there's a different version of react being cached?

Yes, i've tried both things but that didn't solve the problem. 

```json
{
  "name": "lepitre-admin",
  "description": "Payload project created from blank template",
  "version": "1.0.0",
  "main": "dist/server.js",
  "license": "MIT",
  "scripts": {
    "dev": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts nodemon",
    "build:payload": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload build",
    "build:server": "tsc",
    "build": "yarn copyfiles && yarn build:payload && yarn build:server",
    "serve": "cross-env PAYLOAD_CONFIG_PATH=dist/payload.config.js NODE_ENV=production node dist/server.js",
    "copyfiles": "copyfiles -u 1 \"src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png}\" dist/",
    "generate:types": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload generate:types",
    "generate:graphQLSchema": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload generate:graphQLSchema"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.325.0",
    "@aws-sdk/lib-storage": "^3.325.0",
    "@payloadcms/bundler-webpack": "^1.0.6",
    "@payloadcms/db-mongodb": "^1.5.1",
    "@payloadcms/plugin-cloud-storage": "^1.1.2",
    "@payloadcms/richtext-lexical": "^0.10.0",
    "@payloadcms/richtext-slate": "^1.5.2",
    "docker-secret": "^2.0.6",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "payload": "^2.16.1"
  },
  "devDependencies": {
    "@types/express": "^4.17.9",
    "copyfiles": "^2.4.1",
    "cross-env": "^7.0.3",
    "nodemon": "^2.0.6",
    "ts-node": "^9.1.1",
    "typescript": "^4.8.4"
  }
}

```

**Comment by jonisapp** [comment]
After reinstalling the latest version of payload today, the problem has been solved for me. The only parameter that has changed since yesterday is that the session has expired. Last time I didn't try clearing the cache, so I don't know if it could be related to that. On the other hand, it was very annoying yesterday because I was completely stuck with these very uninformative errors. So I suggest keeping the issue open in case it happens to someone else.
