### ISSUE TITLE
(db-postgres): Current method for counting rows in findMany / count operations is very heavy for tables with high amount of records.

### ISSUE THREAD

**Issue by r1tsuu** [payloadcms/payload#6321]
### Link to reproduction

https://github.com/r1tsuu/payload/tree/heavy-count-postgres

### Describe the Bug

Current method for getting count of rows  is _very heavy_ when dealing with a large amount of rows.

From [here](https://github.com/payloadcms/payload/blob/4f0ddcf632742eb1b38828a22a28acf38bf0c0b1/packages/db-postgres/src/find/findMany.ts#L142):
```ts
  const countResult = await chainMethods({
      methods: selectCountMethods,
      query: db
        .select({
          count: sql<number>`count
              (DISTINCT ${adapter.tables[tableName].id})`,
        })
        .from(table)
        .where(where),
    })
``` 

It should be represented as the following SQL query:
```sql
SELECT COUNT(DISTINCT id) from public.tests
```

Running this in pgAdmin results in 403! ms waiting (with 1.7kk docs)
![image](https://github.com/payloadcms/payload/assets/64744993/1e5b4bca-de05-4366-9319-3ae644689de8)

For compare:
Retrieving the latest 100 rows, which is a not bad amount is only 43 ms
![image](https://github.com/payloadcms/payload/assets/64744993/ef817b18-ad59-4700-a81c-bf2e160b8557)
 
Isn't it a huge amount of time just for COUNT? What if you don't need count, it's a good question too?

However, there's a trick SQL query that gives us at least 167 ms for count
```sql
SELECT COUNT(*) FROM (SELECT DISTINCT id FROM public.tests) AS temp;
```
![image](https://github.com/payloadcms/payload/assets/64744993/40935fa3-4026-415a-b9d4-8eaf60adece5)
I don't know drawbacks of this. Though it's still 3x times slower than just the latest 100 rows query.

Discord thread https://discord.com/channels/967097582721572934/1238410124775915530 originally created from user that compared Payload and Directus, i just did some additional research on that.

### To Reproduce

Configure the amount of docs that will be generated, by default it's 2kk (line 47 community config)
`pnpm dev:postgres _community`
...wait while docs will be created, should be fast as i'm using here raw sql insert many
 

### Payload Version

3.0

### Adapters and Plugins

db-postgres

**Comment by jmikrut** [comment]
I am way down to do some experimentation here. We will crack this open on Monday and post back with our findings! Thanks for the recon, as always, it’s very much appreciated!

**Comment by r1tsuu** [comment]
Opened a PR https://github.com/payloadcms/payload/pull/7749

**Comment by r1tsuu** [comment]
Fixed there 👍
