### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by sangrepura** [payloadcms/payload#6336]
# Documentation Issue

The README for the shadcn-ui tailwind example has a link to a tutorial that points to a non-existent blog post and 404s:
See: https://github.com/payloadcms/payload/tree/beta/examples/tailwind-shadcn-ui

**Comment by PatrikKozak** [comment]
@sangrepura Is this still happening for you? 

I just tested this and it is sending me to the blog post as expected.

**Comment by PatrikKozak** [comment]
@sangrepura Going to close as it seems to be working - will reopen if you are still experiencing the issue
