### ISSUE TITLE
Illustrator file is not uploadable

### ISSUE THREAD

**Issue by patricsgamma** [payloadcms/payload#6348]
### Link to reproduction

-

## Setup
Adobe Illustrator files come with 1 of 2 mimeType's, where pdf one is the recent one.
`application/vsn.adobe.illustrator`, `application/pdf`

## Error
Configuring an upload collection allowing both, still doesn't let me upload an Illustrator `.ai` file.

We receive a
`ValidationError: The following field is invalid: mimeType`

Out of some reason the file is interpreted as a 'application/postscript' even though getting File infos tells us its a pdf
```
file --mime-type -b my_illustrator_file.ai 
application/pdf
```

### To Reproduce

Configure a upload collection with
 ```
 upload: {
    mimeTypes: [
      'application/vsn.adobe.illustrator',
      'application/pdf',
    ],
  },
```

Try to upload an illustrator file.

### Payload Version
2.16.1

### Adapters and Plugins
"@payloadcms/bundler-webpack": "^1.0.6", 
"@payloadcms/db-mongodb": "^1.5.1",
"@payloadcms/plugin-cloud-storage": "^1.1.2",
"@payloadcms/plugin-sentry": "^0.0.6",
"@payloadcms/richtext-lexical": "^0.10.0",

**Comment by patricsgamma** [comment]
With the knowledge that 'application/postscript' works we can arround the issue.
But its still strange and misleading when the OS tells you a file is a certain `mimeType` and then it turns to something different on upload into the CMS.

**Comment by paulpopus** [comment]
We use Busboy to help determine the mimeType which in this case it seems consistent with Adobe's documentation that `application/postscript` is the expected mimeType for AI files: https://experienceleague.adobe.com/en/docs/experience-manager-65/content/assets/administer/assets-formats#supported-mime-types
