### ISSUE TITLE
Can't Filter by Related Field? Postgres Bug?

### ISSUE THREAD

**Issue by JeremyEnglert** [payloadcms/payload#6375]
### Describe the Bug

When we try to filter by a related field in the Payload dashboard, we never get any results back (or an error). It just sits on the loading screen as seen in the screenshot.

We're using Postgres (if that makes a difference). Is this a known bug or do I not have the collection(s) setup right?

![ezgif-1-55d6346bda](https://github.com/payloadcms/payload/assets/6110968/56db9d27-8d6a-44a1-8ecb-b7f24e7fdf00)

### To Reproduce

- Setup a related field between two collections
- Go to a collection screen and open the filters
- Create a filter trying to filter on a related field

### Payload Version

2.16.1

### Adapters and Plugins

db-postgres

**Comment by JeremyEnglert** [comment]
I switched to MongoDB and I'm now able to filter as expected - so I believe this is related to Postgres.

**Comment by paulpopus** [comment]
This has been fixed in the latest beta!
