### ISSUE TITLE
[3.0.0-beta.34] incorrect import of `isHotkey` in richtext-slate plugin

### ISSUE THREAD

**Issue by kpkonghk01** [payloadcms/payload#6421]
### Link to reproduction

https://github.com/AoiYamada/unclaimed-store

### Describe the Bug

`isHotkey` is not a function:

<img width="856" alt="Screenshot 2024-05-18 at 11 56 39 PM" src="https://github.com/payloadcms/payload/assets/57888887/ce7d4815-9791-4e13-a9b7-7cbd4c411ce7">

https://github.com/payloadcms/payload/blob/beta/packages/richtext-slate/src/field/RichText.tsx#L18

maybe

```ts
import isHotkey from 'is-hotkey'
```

should be changed to

```ts
import { isHotkey } from 'is-hotkey'
```

after upgrade to payload 3

### To Reproduce

Install deps,

then
`docker compose up -d`

go to
`http://localhost:3000/admin/collections/pages`

create new page

type anything in the rich text editor will trigger this error like this:

<img width="1304" alt="Screenshot 2024-05-19 at 12 09 44 AM" src="https://github.com/payloadcms/payload/assets/57888887/f55b6cff-7f26-4421-b1b0-efe0083b247d">

### Payload Version

3.0.0-beta.34

### Adapters and Plugins

db-mongodb, richtext-slate

**Comment by denolfe** [comment]
Closed by #6466
