### ISSUE TITLE
Resend for /api/users/forgot-password over REST in Vercel

### ISSUE THREAD

**Issue by peterjunsworth** [payloadcms/payload#6457]
Resend does not receive email request on Vercel. Locally no issues.

Version:
```
"@payloadcms/email-resend": "3.0.0-beta.25"
```

payload.config.ts
```
import { resendAdapter } from '@payloadcms/email-resend'

export default buildConfig({
    email: resendAdapter({
        defaultFromAddress: '****@****.****.com',
        defaultFromName: 'Payload CMS',
        apiKey: '**********',
    }),
    ....
```
REST Call
```
await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/users/forgot-password`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      email: '****@****.****.com',
    }),
  });
```

Users: CollectionConfig
```
...
  auth: {
    forgotPassword: {
      generateEmailSubject: () => 'Reset your password',
      generateEmailHTML: async ({ req, token, user }: any) => {
        const resetPasswordURL = `${process.env.NEXT_PUBLIC_BASE_URL}/verify?token=${token}`
        return `
          <!doctype html>
          <html>
            <body>
              <h1>Here is my custom email template!</h1>
              <p>Hello, ${user.email}!</p>
              <p>Click below to reset your password.</p>
              <p>
                <a href="${resetPasswordURL}">${resetPasswordURL}</a>
              </p>
            </body>
          </html>
        `
      },
    },
  },
```

**Comment by denolfe** [comment]
@peterjunsworth Could you simplify your reproduction?

**Comment by peterjunsworth** [comment]
@denolfe - ye - I will do but under the gun right now so haven't had the opportunity yet

**Comment by peterjunsworth** [comment]
ok @denolfe - finally got round to it. Just added you to the repo (let me know if didn't receive invite). I forked this repo from: https://github.com/payloadcms/payload-3.0-demo

You will see the resend dependencies in the package.json file.
Locally I receive email, deployed to Vercel 'nothing', just a success message in network. Same even using the admin forgot password functionality: https://payloadtestingemail.vercel.app/admin/forgot

Very simple setup using Mongo Atlas and @payloadcms/email-resend": "^3.0.0-beta.40"
Nothing much else configured apart from what was in the original repo.

Cheers

**Comment by peterjunsworth** [comment]
![Screenshot](https://github.com/payloadcms/payload/assets/1275513/d54606a6-8ad6-4f06-a944-1ceecd5f95ba)

No error messages in Vercel or browser
No logs at all in resend - double check env vars

**Comment by peterjunsworth** [comment]
awesome - thanks. glad it wasn't just me being daft

**Comment by denolfe** [comment]
@peterjunsworth These email calls should now be awaited. Try it out on beta.46 and let me know 👍 

https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.46
