### ISSUE TITLE
`defaultColumns` has no effect in collections

### ISSUE THREAD

**Issue by iamlinkus** [payloadcms/payload#6458]
Pulled the latest [payload-3.0-demo](https://github.com/payloadcms/payload-3.0-demo) repo, modified the default users collection like so: 

```js
    {
      slug: 'users',
      auth: true,
      access: {
        delete: () => false,
        update: () => false,
      },
      admin: {
        defaultColumns: ['email', 'createdAt'],
      },
      fields: [
        {
          name: 'date',
          type: 'date',
        },
      ],
    },
 ```
 
Nothing changed in the admin panel. Seems like defaultColumns get completely ignored. Tried rebuilding, cleaning out cache... nada.

On a fresh and clean db, no preferences set anywhere.

**Comment by JarrodMFlesch** [comment]
The recommended change has been made, now column preferences will not set until they are adjusted. The ability to reset preferences would be a future feature request as it would require some design effort. Thanks for the feedback!

[Related PR](https://github.com/payloadcms/payload/pull/6774)
