### ISSUE TITLE
POTENTIAL BUG - Updating your own user document in the admin panel either logs you out or hangs if in a hook

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload#6459]
Hello I've noticed when building out some functionality that if I update the user who I am currently logged in as's object then it either hangs if it is in a hook or logs me out if I am updating the user record itself.

I am working on 3.0.0-beta.32.

Steps to recreate log out:
 - Login as a user
 - Update your own record
 - You will be logged out

Steps to recreate hanging on a hook:
- Login as a user
- Create a hook on a separate collection (I know infinite calls can be a risk if it's the same collection)
- Update a user that you are not signed in as - it will go through fine
- Update your own user - it will hang indefinitely

**Comment by JarrodMFlesch** [comment]
Closing, no reproduction given.
