### ISSUE TITLE
Unable to delete record from admin in postgres if collection has array field type

### ISSUE THREAD

**Issue by aymanson** [payloadcms/payload#6485]
### Describe the Bug

I am using the postgresdb adapter. and update the Users collection with following additional field:

```
        {
            name: 'roles', // required
            type: 'select', // required
            hasMany: true,
            admin: {
                isClearable: true,
                isSortable: true, // use mouse to drag and drop different values, and sort them according to your choice
            },
            options: [
                {
                    label: 'Super Admin',
                    value: 'superadmin',
                },
                {
                    label: 'Owner',
                    value: 'owner',
                },
                {
                    label: 'Admin',
                    value: 'admin',
                },
                {
                    label: 'Instructor',
                    value: 'instructor',
                }
            ],
        },
```
        
        I can save the document successfully and I notice payload create an additional table user_roles to track that. When I try to delete the record from admin. It looks like the user_roles record are not removed first nor the cascade delete is executed when delete from user. That cause the fk_constraint error in user_roles table which block the delete operation.

I noticed there are some discussion about cascade in relationship but there is no conclusion there. I want to know if there are some existing workaround for that using hook but I am not able to find such information in the documentation as well.

### To Reproduce

Create a new project using the default user schema.
Modify Users.ts with additional field

```
   fields: [
        {
            name: 'roles', // required
            type: 'select', // required
            hasMany: true,
            admin: {
                isClearable: true,
                isSortable: true, // use mouse to drag and drop different values, and sort them according to your choice
            },
            options: [
                {
                    label: 'Super Admin',
                    value: 'superadmin',
                },
                {
                    label: 'Owner',
                    value: 'owner',
                },
                {
                    label: 'Admin',
                    value: 'admin',
                },
                {
                    label: 'Instructor',
                    value: 'instructor',
                },
                {
                    label: 'Student',
                    value: 'student',
                },
                {
                    label: 'VIP',
                    value: 'vip',
                },
            ],
        },
    ],
```

Create a user through the payload cms admin page.
Try delete the user through the payload cms admin page and error toast occured.

### Payload Version

2.18.3

### Adapters and Plugins

db-postgres

**Comment by ikenox** [comment]
Due to this issue, collection data that has select-hasMany field cannot be deleted on admin panel.
The API returns 500 error.

<img width="1608" alt="image" src="https://github.com/payloadcms/payload/assets/7638989/79b8c70c-5ca1-4ac3-ad35-dda42ee16135">
