### ISSUE TITLE
Number field has wrong min/max validation

### ISSUE THREAD

**Issue by wojciechkrol** [payloadcms/payload#650]
# Bug Report

I have created field with Number type and set min and max value between 0 and 1. When I send request with value of this field ex. 1.5 record is successfully saved. When I send value 2 or more, then validation appear

## Expected Behavior

Validation should consider decimal values and display validation for values greater than 1.00.

## Current Behavior

When I send value 1.25, 1.5 or 1.99 etc. validation does not appear and record is properly saved. When I send value greater or equal 2 than validation appear:

```
{
    "errors": [
        {
            "name": "ValidationError",
            "message": "The following field is invalid: tax",
            "data": [
                {
                    "message": "\"2\" is greater than the max allowed value of 1.",
                    "field": "tax"
                }
            ]
        }
    ]
}
```

**Comment by HopeFaith2012** [comment]
{
    "errors": [
        {
            "name": "ValidationError",
            "message": "The following field is invalid: tax",
            "data": [
                {
                    "message": "\"2\" is greater than the max allowed value of 1.",
                    "field": "tax"
                }
            ]
        }
    ]
}
