### ISSUE TITLE
CLI: when select `postgress` docker is setup with `mongo`

### ISSUE THREAD

**Issue by AugustinMauroy** [payloadcms/payload#6502]
### Payload Version

BETA

### Node Version

20-alipine

### Next.js Version

15.0.0-rc.0

### Describe the Bug

See title

### Reproduction Steps

Do instruction on README

### Adapters and Plugins

 db-postgres, docker, CLI

**Comment by denolfe** [comment]
Closed by #6536 . Added commented postgres section to docker-compose. This will need to be uncommented manually.
