### ISSUE TITLE
"Not-found.tsx" file not working in "src/app/(app)" folder

### ISSUE THREAD

**Issue by dmvdven** [payloadcms/payload#6511]
### Payload Version

3.0.0-beta.32

### Node Version

20.13.1

### Next.js Version

14.3.0-canary.37

### Describe the Bug

Hi,

I tried adding a "not-found.tsx" file inside my "src/app/(app)" folder, but this doesn't seem to work. It still shows me the default 404 NextJS page.

Am I missing something or putting the file in the wrong directory?

![Scherm­afbeelding 2024-05-26 om 12 05 32](https://github.com/payloadcms/payload/assets/38183441/5c7363b0-142c-424a-b1dc-d2eeaff2879a)

### Reproduction Steps

Put a "not-found.tsx" file in the "src/app/(app)" folder.

**Comment by domenico-ruggiano** [comment]
this is a problem related to next.js multi layout: https://github.com/vercel/next.js/discussions/50034

**Comment by jacobsfletch** [comment]
Hey @dmvdven I went ahead and tested this just now and @domenico-ruggiano is right in that this is a Next.js issue. There is, however, a workaround posted in that [discussion](https://github.com/vercel/next.js/discussions/50034) which worked for me as a temporary solution.

From [victorandree](https://github.com/victorandree):

> You can add a dynamic catch-all route to catch all and in this route you can call notFound. This triggers the closest not-found.tsx.

> ```plaintext
> app
> ├── (app1)
> │   ├── [...not-found]
> │   │   └── page.tsx
> │   ├── layout.tsx
> │   ├── not-found.tsx
> │   └── page.tsx
>└── (app2)
>    ├── admin
>    │   └── page.tsx
>    └── layout.tsx
>```
>
> In `(app1)/[...not-found]/page.tsx`:
>
> ```ts
> import { notFound } from 'next/navigation';
>
> export default function NotFoundDummy() {
>  notFound();
> }
> ```
