### ISSUE TITLE
Collections with Draft Versions cannot be Access filtered when they have Hidden Fields

### ISSUE THREAD

**Issue by mckinley** [payloadcms/payload#6515]
### Link to reproduction

https://github.com/mckinley/payload/commit/9c189e4fb1e14e71adc75f61596bf928d91592f3

### Describe the Bug

Hi there! Thanks for Payload! Seems like a great project!

I think I've found a problem. I'm happy to work through it and contribute a PR if folks don't mind taking a look and agree that it's an issue. This is for the latest stable release, 2.18.3.

When a collection has `versions: { drafts: true }` set, and there is an access control also set like:
```
access: {
    read: () => {
      return {
        hiddenField: {
          equals: "value",
        },
      };
    },
  },
```
the admin panel no longer works when listing the relevant resources.

The error thrown is something like: `[16:15:37] ERROR (payload): QueryError: The following path cannot be queried: version.hiddenField`

There is no error message that shows in the UI.
![Screenshot 2024-05-26 at 8 22 41 PM](https://github.com/payloadcms/payload/assets/6520/28b210bf-18ae-4a9e-acf3-a0eaaa4ef547)

The admin panel uses a URL similar to "http://localhost:3000/api/posts?depth=0&draft=true&limit=10&invoke=a3293979-b657-429c-a55a-860ad750d0c1". As long as `draft=true' is present in a request in this situation, it fails.

The error is identified by payload at this line:
https://github.com/payloadcms/payload/blob/4c832ad98440e5f56a490e5f884a218cbfd2056d/packages/payload/src/database/getLocalizedPaths.ts#L78
And relates to logic here:
`packages/payload/src/database/queryValidation`

I found the bug while combining [payload tenancy](https://github.com/joas8211/payload-tenancy) with draft versioning. Payload tenancy uses a hidden `tenant` field to filter access to collections.

I've walked through the code and done a fair amount of debugging. I am happy to add more details about why this is happening if desired. I also created a demonstration repo that has two commits. The first generates a new payload app from the command line. The second adds the setup to demonstrate the issue. I also have a test written in a [forked payload repo](https://github.com/mckinley/payload/tree/version-test) that demonstrates the issue.

Hopefully I've followed the reproduction guide well and everything is clear. 

### To Reproduce

First of all, review [this collection configuration](https://github.com/mckinley/payload/blob/9c189e4fb1e14e71adc75f61596bf928d91592f3/test/_community/collections/Posts/index.ts#L7). Determine if this makes sense as a common use case that Payload would like to support.

Then there are a few ways to reproduce.

## Using Payload Reproduction Guide Strategy

```
git clone git@github.com:mckinley/payload.git
cd payload
pnpm install
git switch version-test
node 'node_modules/jest/bin/jest.js' 'test/_community/int.spec.ts' -t '_Community Tests allows Collections to be Access filtered when Draft Versions are enabled'
```

1) Notice failing test.

## Using Basic Demo

```
git clone git@github.com:mckinley/versions-test.git
cd versions-test
npm install
npm run dev
```

1) Go to [http://localhost:3000](http://localhost:3000)
2) Create your user etc.
3) Go to [http://localhost:3000/admin](http://localhost:3000/admin)
4) Click on "Resources"
5) Notice that the page is broken

## DIY

1) Add the following to any collection definition:
```
  fields: [
    {
      name: 'hiddenField',
      type: 'text',
      hidden: true,
    },
  ],
  access: {
    read: () => {
      return {
        hiddenField: {
          equals: 'value',
        },
      }
    },
  },
  versions: {
    drafts: true,
  },
```
2) Go to that admin dashboard and click on the resource to get a list.
3) Observe that the page is broken. 

### Payload Version

2.18.3

**Comment by jmikrut** [comment]
Hey @mckinley — this is an interesting find. We do indeed restrict querying on fields unless you have public access to the field because this prevents security vulnerabilities. But I guess that if field queries are passed via access control, querying on those fields does not present a security vuln because your backend code is what's responsible for filtering on them and _you_ define them.

It's possible that we could resolve this. @kendelljoseph let's look into this!

**Comment by kendelljoseph** [comment]
@mckinley we've dug into this a bit and here is what we're thinking.

We don't want to introduce any security risks by adding a flag that would allow for a field that is `hidden` to behave differently via the API and the local API. Any flag that partially change access behavior is too subtle and could have catastrophic behaviors.

Options we think could be used as an alternative to this approach:
- use an [afterRead](https://payloadcms.com/docs/hooks/collections#afterread) hook.
- the `doc` is available in the `read` access function where data can be passed and used by the to determine access conditions.

**Comment by mckinley** [comment]
Thanks so much @kendelljoseph. Ok I had put my payload project on hold for a bit, but when I jump back in Ill continue to see if there is anything I can do to work around the problem.

Thanks again!
