### ISSUE TITLE
CPA script doubles up on withPayload import in next.config

### ISSUE THREAD

**Issue by paulpopus** [payloadcms/payload#6517]
### Payload Version

beta.36

### Node Version

20

### Next.js Version

15-canary.0

### Describe the Bug

When installing payload via the CPA script in an existing project, the nextjs config doubles up on the `withPayload` import so the output becomes the following

```ts
import { withPayload } from '@payloadcms/next/withPayload'
/** @type {import('next').NextConfig} */
import { withPayload } from "@payloadcms/next/withPayload";

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
};

export default withPayload(withPayload(nextConfig));
```

### Reproduction Steps

Run the cpa script in a project that already has payload initiliased `pnpm dlx create-payload-app@beta`

### Adapters and Plugins

create-payload-app

**Comment by denolfe** [comment]
Closed by #6193
