### ISSUE TITLE
Css is not loading in existing next js project

### ISSUE THREAD

**Issue by priya-jain-dingg** [payloadcms/payload#6526]
### Payload Version

beta

### Node Version

20.2.5

### Next.js Version

14.2.3

### Describe the Bug

Any existing Next Js Project added - payload by this command -`npx create-payload-app@beta`.
Then Css is not loading on UI - when I saw .next/static/css/app/(payload)/layout.css file CSS there is different from what I have in when I cone [https://github.com/payloadcms/payload-3.0-demo](payload 3.0 demo).
When I change content of `layout.css` or `admin/page.css` then  css is working fine.
In below image one side when searching - `loading-overlay` nothing found... on other its working.
<img width="1772" alt="Screenshot 2024-05-28 at 3 01 25 PM" src="https://github.com/payloadcms/payload/assets/109344846/138cd36a-3f1c-446b-98c3-a43a5d3c4b5a">

Please help!

### Reproduction Steps

1. Any existing next js prject with `tailwind, next-purgecss, postcss`.
postcss.config.js file
```
module.exports = {
  plugins: [
    "tailwindcss",
    "autoprefixer",
    [
      "@fullhuman/postcss-purgecss",
      // process.env.NODE_ENV === "production"
      {
        // the paths to all template files
        content: [
          "./src/app/**/**/*.{js,jsx,ts,tsx}",
          "./src/pages/**/*.{js,jsx,ts,tsx}",
          "./src/components/**/*.{js,jsx,ts,tsx}",
          "./node_modules/aos/dist/aos.css",
          "./node_modules/react-multi-carousel/lib/styles.css",
          "./node_modules/@splidejs/splide/dist/css/splide.min.css",
        ],
        keyframes: true,
        // function used to extract class names from the templates
        defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
      },
      // : false,
    ],
  ],
}
```
2. Add payload to project.
3. Run project - `rm -rf .next && cross-env NODE_OPTIONS=--no-deprecation next dev`

### Adapters and Plugins

db-postgres, tailwind, next-purgecss, postcss

**Comment by JarrodMFlesch** [comment]
Hey @priya-jain-dingg please provide a reproduction repository so we can look into this, thanks! I will re-open once you have one.
