### ISSUE TITLE
Argument of type 'SQL<unknown>' is not assignable to parameter of type 'SQLWrapper'.

### ISSUE THREAD

**Issue by ainsleyclark** [payloadcms/payload#6538]
### Link to reproduction

https://github.com/ainsleydev/go-payloadcms/tree/main/dev

### Describe the Bug

When creating a migration, errors occur within the TS migration files:

```
➜  dev git:(main) ✗ pnpm run payload migrate:create

> test@1.0.0 payload dev
> cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload "migrate:create"

[09:23:55] INFO (payload): Starting Payload...
[09:23:55] INFO (payload): Migration created at /dev/src/migrations/20240528_082355.ts
[09:23:55] INFO (payload): Done.
```

It then creates the migration files, but the Typscript it generates doesn't look quite right (screenshot attached)
So when pnpm run build is ran I get this:

```
11.86 src/migrations/20240528_081744.ts(107,35): error TS2345: Argument of type 'SQL<unknown>' is not assignable to parameter of type 'SQLWrapper'.
11.88  ELIFECYCLE  Command failed with exit code 2.
11.89  ELIFECYCLE  Command failed with exit code 2.
------
```

![image](https://github.com/payloadcms/payload/assets/34712954/8b0298a6-4876-40d8-a5e9-e9829babe12f)

### To Reproduce

Run `pnpm run payload migrate:create` from the repo provided.

### Payload Version

2.18.3

### Adapters and Plugins

Postgres DB

**Comment by TomDo1234** [comment]
You guys can close this, because its not actually a payloadcms issue but a VS code configuration issue or IDE configuration issue.

You have to make sure your IDE like VScode is using the workspace TS version as its language server, not the global language server, I had my VSCode set to TS 5.5 and it causes this error. Make sure it uses the workspace ts server.

**Comment by ainsleyclark** [comment]
Thanks for the explanation @TomDo1234

**Comment by r1tsuu** [comment]
@TomDo1234 is right, it's recommended to use a TS version from the workspace, closing this as seems like resolved.
