### ISSUE TITLE
Error on edit image action

### ISSUE THREAD

**Issue by denishpateltheapplabb** [payloadcms/payload#6545]
### Describe the Bug

We found errors while editing media("Edit media -> Apply Changes button"). It occurs when we put the "upload" field under the global component only, it is working fine under the collections. 

In addition, it gives different errors in local and production 

Local: https://app.screencast.com/vBIWO8ULVqSHk?conversation=AUbsGOVJHPNmWI3O3I4Y36
TypeError: setFormQueryParams is not a function

Prod: https://app.screencast.com/lSMmGUmrWsWvq?conversation=qCJUGk6Fm79VbxUO8L7tvt
TypeError: y is not a function

### To Reproduce

Please have a look in below screencast for reproduce the issue 

https://app.screencast.com/lSMmGUmrWsWvq?conversation=qCJUGk6Fm79VbxUO8L7tvt

### Payload Version

Latest: 2.18.3

**Comment by JarrodMFlesch** [comment]
@denishpateltheapplabb I have a [PR](https://github.com/payloadcms/payload/pull/6664) incoming for this issue!

**Comment by denishpateltheapplabb** [comment]
@JarrodMFlesch Great! Please let me know once it is deployed on production with an updated version.

**Comment by JarrodMFlesch** [comment]
@denishpateltheapplabb Released https://github.com/payloadcms/payload/releases/tag/v2.19.3

**Comment by denishpateltheapplabb** [comment]
@JarrodMFlesch 

Error that i mentioned above is resolved.  
**But, now when we are going to save the updated image, it gives an error and not uploading.** 

Please have a look in below screencast 
https://app.screencast.com/TeENLFKaL51SV?conversation=bo0AWOHpVgOcSqG4b4SLtu 

Note: Image uploading correctly in case of ADD action. It does not in case of EDIT action

**Comment by JarrodMFlesch** [comment]
@denishpateltheapplabb can you provide me with an example config so I can recreate this? I attempted to but was unable to reproduce.

**Comment by denishpateltheapplabb** [comment]
@JarrodMFlesch 

Please have a look in below files. 
Not able to attach .ts files, so pasted below. 

**// \src\payload\globals\Footer.ts**

import type { GlobalConfig } from "payload/types"
import { validateLink } from "../utils"

export const Footer: GlobalConfig = {
  slug: "footer",
  access: {
    read: () => true,
  },
  fields: [
    {
      name: "socialLinks",
      type: "array",
      maxRows: 50,
      fields: [
        {
          type: "row",
          fields: [
            {
              name: "name",
              type: "text",
            },
            {
              name: "icon",
              type: "upload",
              relationTo: "media",
              required: true,
            },
          ],
        },
      ],
    },
  ],
}

**// \src\payload\collections\Media.ts**

import { slateEditor } from "@payloadcms/richtext-slate"
import type { CollectionConfig } from "payload/types"
import { ValidationError } from "payload/errors"

export const Media: CollectionConfig = {
  slug: "media",
  upload: {
    disableLocalStorage: true,
  },
  access: {
    read: () => true,
  },
  hooks: {
    beforeValidate: [
      async ({ data, req, operation }) => {
        if (operation === "create" || operation === "update") {
          if (req.files && req.files.file) {
            const { name: originalname } = req.files.file
            if (/\s/.test(originalname)) {
              const errorMsg = "Media name should not contain spaces"
              throw new ValidationError([
                {
                  field: `Media Error: ${errorMsg}`,
                  message: errorMsg,
                },
              ])
            }
          }
        }
        return data
      },
    ],
  },
  fields: [
    {
      name: "alt",
      type: "text",
      required: true,
    },
    {
      name: "caption",
      type: "richText",
      editor: slateEditor({
        admin: {
          elements: ["link"],
        },
      }),
    },
  ],
}

**Comment by denishpateltheapplabb** [comment]
Hi @JarrodMFlesch 

Any update?

**Comment by JarrodMFlesch** [comment]
@denishpateltheapplabb Can you open a new issue, I'll look into it first thing today

**Comment by denishpateltheapplabb** [comment]
@JarrodMFlesch  Created new issue, please have a look https://github.com/payloadcms/payload/issues/6802
