### ISSUE TITLE
[3.0.0-beta.36] generate:types fails when nestedDocs plugin is installed

### ISSUE THREAD

**Issue by sriechersrc** [payloadcms/payload#6548]
### Payload Version

v3 beta

### Node Version

v20.10.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

When including the nestedDocs plugins `payload generate:types` throws `TypeError: nestedDocs is not a function`. If 
 I comment out the plugin, it works as expected.

The Plugin config looks like this:
<img width="692" alt="Bildschirmfoto 2024-05-29 um 16 12 20" src="https://github.com/payloadcms/payload/assets/155533497/26016db0-3d10-4b9c-8228-1d32951c5562">

### Reproduction Steps

1. Install the plugin
2. Add it to the plugins field in the payload config
3. Run `npm payload generate:types`

### Adapters and Plugins

nestedDocs, db-postgres

**Comment by HarleySalas** [comment]
How does your import statement look? It was recently changed.

This is what it should look like:
```
import { nestedDocsPlugin } from '@payloadcms/plugin-nested-docs'
```

**Comment by sriechersrc** [comment]
My Import looks like this `import nestedDocs from '@payloadcms/plugin-nested-docs'` 

However if i change it to the import statement you have provided I'm getting `Module '"@payloadcms/plugin-nested-docs"' has no exported member 'nestedDocsPlugin'. Did you mean to use 'import nestedDocsPlugin from "@payloadcms/plugin-nested-docs"' instead?`

I have `"@payloadcms/plugin-nested-docs": "3.0.0-beta.36"` installed

**Comment by sriechersrc** [comment]
Nevermind, the TS Server in VSCode silently crashed... `import { nestedDocsPlugin } from '@payloadcms/plugin-nested-docs'` works like a charm! Thanks!

I am closing the issue
