### ISSUE TITLE
Postgres v2 to v3 migration script fails type-checking

### ISSUE THREAD

**Issue by tomparkp** [payloadcms/payload#6581]
### Payload Version

3.0.0-beta.39

### Node Version

18

### Next.js Version

15rc

### Describe the Bug

When following the instructions in the [3.0.0-beta.39](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.39) release notes for migrating a Postgres database the resulting migration fails Typescript type checking with the following error:

> Type 'Partial<PayloadRequestWithData> | undefined' is not assignable to type 'PayloadRequestWithData'.
  Type 'undefined' is not assignable to type 'PayloadRequestWithData'.
    Type 'undefined' is not assignable to type 'Partial<Request>'.

This is due to mismatched types between `req` in `MigrateUpArgs` (which can be undefined) and `req` in the `migratePostgresV2toV3` function (which is required).

### Reproduction Steps

1. Setup a Payload project
2. Run `payload migrate:create --file @payloadcms/db-postgres/relationships-v2-v3`
3. Run `tsc`

**Comment by jmikrut** [comment]
Hey @tomparkp — just checking quick, did you update Payload as well? We'll check into this ASAP

**Comment by tomparkp** [comment]
@jmikrut Yes Payload and all related packages are at 3.0.0-beta.39, thanks!

**Comment by tomparkp** [comment]
Just a random point of feedback, but I think it would be nice if Payload could lean into the default behavior of Drizzle and generate `.sql` migrations rather than using a wrapper which would feel more in the spirit of Payload as open-source and deeply customizable. I'm sure there are technical reasons I haven't had a chance to investigate but it might be nice to make that part of the payload CLI or a migration script similar to how Drizzle does it if possible.

**Comment by r1tsuu** [comment]
> Just a random point of feedback, but I think it would be nice if Payload lean3e into the default behavior of Drizzle and generated `.sql` migrations rather than using a wrapper, which would feel more in the spirit of Payload as open and deeply customizable - and also make for less potential points of failure. I'm sure there are technical reasons I haven't had a chance to investigate, but just a thought.

maybe just generate drizzle schema so then you can use drizzle CLI to run migrations?

**Comment by jmikrut** [comment]
Hey @tomparkp the reason why we opted for a TS wrapper is because migrations often need to _**move data**_ from one spot to another alongside of running DDL transformations. Having that done in TypeScript is much easier than full SQL. 

It was a pretty deliberate decision to take the generated Drizzle SQL but allow you to inject your own logic into your migration file, in TypeScript, as well. Does that make sense?

**Comment by tomparkp** [comment]
@jmikrut Yes I imagined it was something like that. It would be nice if it was a bit clearer/more explicit what Payload was doing, just because one of the selling points for us is that if for some reason we ever needed an "out" we could take direct control of the database.

**Comment by jmikrut** [comment]
You could definitely do that! Nothing super special with Payload in that sense. I'd imagine that by ejecting Payload, you'd already have your DB set up how you want it and then could just wipe the slate clean and create a new Drizzle migration in raw SQL from that point on

**Comment by r1tsuu** [comment]
@jmikrut Hey, have you guys done some research on this? [Generating Drizzle types (Discord link to my solution)](https://discord.com/channels/967097582721572934/967097582721572937/1161393807414268025)

**Comment by jmikrut** [comment]
@r1tsuu yes! We added a feature that we've needed to do this nicely. You can now add `bin` scripts to the Payload config, and I think introspecting the types from Payload should be done similarly to how we generate types in the first place. A CLI command.

However... it could also become part of the build process. There are a few things I want to do here but thank you for reminding me. I'm gonna bring this up with the team next week and I think we need to get this in there by 3.0.

Good call!

**Comment by r1tsuu** [comment]
> @r1tsuu yes! We added a feature that we've needed to do this nicely. You can now add `bin` scripts to the Payload config, and I think introspecting the types from Payload should be done similarly to how we generate types in the first place. A CLI command.
> 
> However... it could also become part of the build process. There are a few things I want to do here but thank you for reminding me. I'm gonna bring this up with the team next week and I think we need to get this in there by 3.0.
> 
> Good call!

Nice!
With this change of relationships it become i can't tell you how much easier to have custom drizzle / raw SQL calls, i have them quite many, especially for aggregations

**Comment by jmikrut** [comment]
Nice, so you're saying you like the new relationship column changes? 

We do too!

Bi-directional relationships coming up next.

**Comment by AlessioGr** [comment]
Closing as this issue has been resolved in one of the latest versions
