### ISSUE TITLE
search plugin fields being omitted in `beforeSync` 

### ISSUE THREAD

**Issue by stoddabr** [payloadcms/payload#6590]
### Describe the Bug

Hi all, I noticed a weird behavior with the search plugin. I was trying to make multiple fields searchable efficiently by combining them into a single field in the created search collection. However, custom fields are removed and fields inside of doc are not searchable. 

I'd be happy to help write a fix (or maybe a feature to build a similar, more optimized use case into the plugin). I just want to make sure this is a proper bug and not an implementation issue first.

### To Reproduce

Here's a simplified version the search parameters I was using which hopefully illustrates my goal of combining multiple fields from different collections into a single searchable string field in the search collection:

```ts
        search({
            collections: ["article", "glossary"],
            defaultPriorities: {
                article: 10,
                glossary: 30,
            },
            beforeSync: ({ originalDoc, searchDoc }) => {
                const collectionSlug = searchDoc.doc.relationTo;
                const columnsToIndexForCollections = {
                    collectionA: ["title", "subtitle", "content"],
                    glossary: ["title", "tooltip"],
                };
                if (!columnsToIndexForCollections[collectionSlug]) {
                    console.warn(
                        `Collection '${collectionSlug}' not recognized in columns to index.`
                    );
                    return searchDoc;
                }
                let search_string = originalDoc.title;
                const body = {};
                columnsToIndexForCollections[collectionSlug].forEach(
                    (column) => {
                        body[column] = originalDoc[column];
                        search_string += ` ${originalDoc[column]}`;
                    }
                );

                const newSearchDoc = {
                    ...searchDoc,
                    search_string,
                    doc: {
                        ...searchDoc.doc,
                        body,
                    },
                };
            },
```

With this, I noticed two issues:
1. The additional field `search_string` disappears from the search documents and cannot be queried.
2. Documents inside of `doc` cannot be queried. I think this is related to this: https://github.com/payloadcms/payload/issues/2150#issuecomment-1440213166

Workarounds include:
* setting `title:search_string`
* moving the `search_string` inside of `body` and querying on that

### Payload Version

2.0.0

### Adapters and Plugins

(related) plugin-search v1.1.1, (probably unrelated) bundler-webpack, db-mongodb, plugin-cloud, richtext-slate

**Comment by paulpopus** [comment]
Before I dive deeper into this, @stoddabr  can you double check the following for me please?

1. That in your `searchOverrides` you add this new field you created `search_string`
2. That you return `newSearchDoc` from your `beforeSync` function

**Comment by paulpopus** [comment]
Closing this for now but happy to re-open if there's a reproduction repo offered!

**Comment by stoddabr** [comment]
Hi @paulpopus , what's the best way to setup a quick reproduction repo? Is there a template floating around? I've skimmed all over the contribution and main docs but I don't see one. I'd love to help drill down into this issue 

(I think I've found the problem in code but want to get some guidance before I waste time on a contribution that may not be well received)

**Comment by paulpopus** [comment]
@stoddabr If you create a blank payload repo with `npx create-payload-app`, make sure the packages are all on the latest versions and add the configuration that breaks it, then we can check that more easily

Basically distil it down to the simplest setup that still causes the bug
