### ISSUE TITLE
Frequent casting errors when renaming columns with db-postgres

### ISSUE THREAD

**Issue by tomparkp** [payloadcms/payload#6595]
### Payload Version

3.0.0-beta.39

### Node Version

18

### Next.js Version

15rc

### Describe the Bug

I've noticed an issue that comes up frequently when developing with Postgres is that anytime you rename a column that appears to have an underlying enum type (e.g. radio) and tell drizzle the column has been renamed it seems to break with a `cannot cast automatically` error.

This seems like it may be an [upstream issue](https://github.com/drizzle-team/drizzle-orm/issues/930) and I commented there as well.

Given this seems to result in a bad `db push` and potentially bad migrations based on the linked issue definitely seems like something worth pushing them to address.

### Reproduction Steps

1. Create a Payload collection with an enum based field (e.g. radio)
2. Rename the field
3. Tell drizzle-kit the column has been renamed (vs added)
4. Observe `Error: column [Name] cannot be cast automatically to type [Enum] error` when running the application.

![2024-06-02-00 53 57](https://github.com/payloadcms/payload/assets/2266762/74d05d2b-cb3a-4e38-a950-47b69dcddcf3)

**Comment by jmikrut** [comment]
Hey @tomparkp — thanks for the report. We will track this issue on the linked Drizzle issue and work with their team to try and resolve accordingly.

I imagine there might not be a way to do this automatically - if you have data in your rows, for the adjusted column, Drizzle would need to convert that existing data into the new format which might be a challenge. You may need to handle cases like that yourself with a custom migration script. But we'll see what we can do.

**Comment by tomparkp** [comment]
@jmikrut I believe this happens even when there is no data in the rows. I was running into it frequently simply because I'd decide to adjust a name slightly while prototyping. Even if its not possible to resolve automatically I think any selection of an option within drizzle-kit resulting in a broken db should be considered a bug (at a minimum I'd expect the CLI to report on the inability to automatically resolve rather than breaking the application).

**Comment by tomparkp** [comment]
The upstream issue while a similar error also a more complex example - this occurs with something as simple as a column rename with no data, even if the values are the exact same - in the linked issue the user was trying to change from text based columns to enums, which I think would be a much less frequent need with something like Payload.

**Comment by tomparkp** [comment]
Since this seems to be an issue within Drizzle I'll try to investigate and open an issue there, since this example is much more common than the one in the linked issue.
