### ISSUE TITLE
V3 is currently incompatible with Payload Cloud Storage?

### ISSUE THREAD

**Issue by m-reidy** [payloadcms/payload#6603]
### Payload Version

3.0.0-beta.36

### Node Version

v20.13.1

### Next.js Version

15.0.0-rc.0

### Describe the Bug

v3 appears to be incompatible with the latest version of the official Cloud Storage Plugin -  "@payloadcms/plugin-cloud-storage": "^1.1.2". Installation as per the docs throws a type error on admin.webpack.

Unless there's a corresponding beta package I've missed? Give me a shout if so.

I thought I'd post a workaround for v3 until the Cloud Storage plugin is upgraded to remove the webpack config key:

Workaround
```
export const s3CloudStoragePlugin = (incomingConfig: Config) => {
  const modifiedConfig = cloudStorage({
    collections: {
      // Any relevant collections, e.g. Media as an example here 
      media: {
        adapter: getS3Adapter(), // Your adapter as per the docs
        // Other options
      },
    },
  })(incomingConfig);

  return {
    ...modifiedConfig,
    admin: {},
  };
};
```

Tested this and it seems happy enough.

### Reproduction Steps

- Install Payload v3
- Add the official Cloud Storage plugin as per the docs for that package

### Adapters and Plugins

@payloadcms/plugin-cloud-storage

**Comment by AlessioGr** [comment]
Hey @m-reidy this is not the latest version of @payloadcms/plugin-cloud-storage. In v3, you have to make sure ALL payload packages are on the exact same version. So for plugin-cloud-storage, you will have to install version `3.0.0-beta.36`

**Comment by m-reidy** [comment]
Awesome thanks @AlessioGr
