### ISSUE TITLE
Default sort is not working, and sort preferences are not being stored in the new V3 list view

### ISSUE THREAD

**Issue by 58bits** [payloadcms/payload#6617]
### Link to reproduction

https://github.com/payloadcms/payload-3.0-demo

### Payload Version

3.0.0-beta.38

### Node Version

20

### Next.js Version

15 rc.0

### Describe the Bug

The default sort setting for a collection, and any changes in sorting of columns in the list view of a collection are not working. Leaving the view, and returning and any sort preferences that have been set are lost.

### Reproduction Steps

In the Payload 3 Demo repo - create several pages, with different titles, and the set a default sort for the collection, and / or change sort preferences on any column. The default sort is not respected, and preferences in sort are not stored in user preferences for the collection.

https://github.com/payloadcms/payload/assets/405612/c3e4828d-dc57-4d78-a668-236aa57472e4

**Comment by JarrodMFlesch** [comment]
This will be fixed in the next beta release.

[Related PR](https://github.com/payloadcms/payload/pull/6731)

**Comment by 58bits** [comment]
> This will be fixed in the next beta release.
> 
> [Related PR](https://github.com/payloadcms/payload/pull/6731)

Nice - thanks @JarrodMFlesch
