### ISSUE TITLE
User locale / language is not respected when restoring a user session - loaded content and locale do not agree

### ISSUE THREAD

**Issue by 58bits** [payloadcms/payload#6619]
### Payload Version

3.0.0-beta.38

### Node Version

20

### Next.js Version

15 rc.0

### Describe the Bug

In the video below, you'll see that if a user does not log out completely, but closes the browser window and then reopens the browser and restores their session in admin, the language loaded for any content is the default language - in our case English - even if the user's last locale / language session was another language (i.e. not the default).

Unless the user notices that the current locale and the language of the content loaded is no longer the same (i.e. they don't agree) - and they inadvertently edit and save the document - then all of the language content for that locale will be overwritten with the default language content.

### Reproduction Steps

1. Create a document in two languages - 1 - default, 2- other lang. 
2. Stay in the other lang, and close the browser window (do not log out).
3. Open the browser window again and rejoin the session. The language / locale indicator in the top right will show 'other lang' while the content loaded in the admin collection list view will be the default language (i.e., the locale and loaded content do not agree).
4. Make any change to the content / title etc., while the loaded language and current locale for 'other lang' do not agree, and all 'other lang' content for the document will be overwritten. (Note that I've not actually done this in the video, as this is a 'live' document - however, it's happed on a couple of occasions now, and we've needed to restore a previous version ). 

https://github.com/payloadcms/payload/assets/405612/d4d0fa72-0862-4393-8fbb-4af787f85b0d

NOTE: If the user completely logs out before closing the browser window, and then logs in with a fresh session - this problem does not occur.

**Comment by kurt-waizmann** [comment]
Same issue on my end.
English is our default locale... I'm guessing it keeps falling back to the default instead of the locale I want.

For example, on the french locale I made a page called "french".
![Screenshot_2024-06-12_at_10 10 41_AM](https://github.com/payloadcms/payload/assets/99677488/acd73985-b180-40fb-88d9-48b24f467e62)
But when I click on it, it sends me to the english locale's data while claiming to be in the french locale.
![Screenshot_2024-06-12_at_10 12 14_AM](https://github.com/payloadcms/payload/assets/99677488/5e159a8d-0a51-4cbf-9c05-217e6fbfda8f)


so we land on this url
http://localhost:3000/admin/collections/pages/6669abe1c1cd3c7540a85ecf
when I think we should be landing on this url??
http://localhost:3000/admin/collections/pages/6669abe1c1cd3c7540a85ecf?locale=fr




```json
"dependencies": {
    "@faker-js/faker": "^8.4.1",
    "@miza-react/miza-react-components": "^6.7.0",
    "@payloadcms/db-mongodb": "3.0.0-beta.43",
    "@payloadcms/email-nodemailer": "3.0.0-beta.43",
    "@payloadcms/live-preview-react": "3.0.0-beta.43",
    "@payloadcms/next": "3.0.0-beta.43",
    "@payloadcms/plugin-cloud": "3.0.0-beta.43",
    "@payloadcms/plugin-form-builder": "3.0.0-beta.43",
    "@payloadcms/plugin-nested-docs": "^1.0.12",
    "@payloadcms/plugin-redirects": "^1.0.2",
    "@payloadcms/plugin-search": "3.0.0-beta.43",
    "@payloadcms/plugin-seo": "3.0.0-beta.43",
    "@payloadcms/richtext-lexical": "3.0.0-beta.43",
    "@payloadcms/ui": "3.0.0-beta.43",
    "@react-email/components": "0.0.18",
    "@react-email/render": "0.0.15",
    "cross-env": "^7.0.3",
    "escape-html": "^1.0.3",
    "graphql": "^16.8.1",
    "next": "14.3.0-canary.28",
    "nodemailer": "^6.9.13",
    "payload": "3.0.0-beta.43",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-email": "2.1.4",
    "sharp": "0.32.6",
    "slate": "^0.103.0",
    "tailwind-merge": "^2.3.0"
  },
  "devDependencies": {
    "@commitlint/cli": "^19.3.0",
    "@commitlint/config-conventional": "^19.2.2",
    "@tailwindcss/forms": "^0.5.7",
    "@tailwindcss/typography": "^0.5.13",
    "@types/escape-html": "^1.0.4",
    "@types/node": "^20.11.25",
    "@types/nodemailer": "^6.4.15",
    "@types/react": "^18.2.64",
    "@types/react-dom": "^18.2.21",
    "@typescript-eslint/eslint-plugin": "^7.9.0",
    "@typescript-eslint/parser": "^7.9.0",
    "autoprefixer": "^10.4.19",
    "dotenv": "^16.4.5",
    "eslint": "^8",
    "eslint-config-next": "14.2.3",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-simple-import-sort": "^12.1.0",
    "husky": "^9.0.11",
    "lint-staged": "^15.2.2",
    "postcss": "^8.4.38",
    "prettier": "^3.2.5",
    "standard-version": "^9.5.0",
    "tailwindcss": "3.3.2",
    "tsx": "^4.7.1",
    "typescript": "^5.4.2"
  },
  "engines": {
    "node": ">=18.19.0"
  }
```

**Comment by JarrodMFlesch** [comment]
I was able to recreate this in an easier fashion after watching the recording.

1. Select non default locale in list view
2. Go to /admin
3. Go back to list view, locale is still set but data is populated with default locale

**Comment by 58bits** [comment]
> I was able to recreate this in an easier fashion after watching the recording.
> 
> 1. Select non default locale in list view
> 2. Go to /admin
> 3. Go back to list view, locale is still set but data is populated with default locale

Same here. locale is missing from the query string. A little surprised I didn't see that. Thanks for the update @JarrodMFlesch

**Comment by JarrodMFlesch** [comment]
Will be fixed in next release!

[Related PR](https://github.com/payloadcms/payload/pull/6761)

**Comment by 58bits** [comment]
> Will be fixed in next release!
> 
> [Related PR](https://github.com/payloadcms/payload/pull/6761)

Nice. Thanks.
