### ISSUE TITLE
Lexical blocks with tabs don't save

### ISSUE THREAD

**Issue by matteo-naif** [payloadcms/payload#6631]
### Link to reproduction

-

### Payload Version

3.0.0-beta.40

### Node Version

20

### Next.js Version

14.3.0-canary.68

### Describe the Bug

When I declare a block with tabs in the lexicalEditor features BlocksFeature don't save the data when I use it in the UI Admin.

### Reproduction Steps

```ts
const TestBlock: Block = {
  slug: 'Test',
  fields: [
    {
      type: "tabs",
      tabs: [
        {
          label: "Header",
          name: "header",
          fields: [{
            name: 'quoteHeader',
            type: 'text',
          }],
        },
        {
          label: "Text",
          name: "text",
          fields: [{
            name: 'quoteText',
            type: 'text',
          }]
        }
      ]
    }
  ]
}

export default buildConfig({
  editor: lexicalEditor({
    features: ({ defaultFeatures }) => [
      ...defaultFeatures,
      HTMLConverterFeature({}),
      BlocksFeature({
        blocks: [ TestBlock ],
      }),
    ]
  }),

  collections: [
    Pages
  ],
  secret: process.env.PAYLOAD_SECRET || '',
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
  db: mongooseAdapter({
    url: process.env.MONGODB_URI || '',
  }),
  i18n: {
    supportedLanguages: { it, en },
  },
  debug: true,
  sharp,
  plugins: [
    cloudStoragePluginConfig,
    nestedDocsPluginConfig,
    seoPluginConfig
  ]
})
```

### Adapters and Plugins

     "@payloadcms/db-mongodb": "beta",     "@payloadcms/next": "beta",     "@payloadcms/plugin-cloud-storage": "beta",     "@payloadcms/plugin-nested-docs": "beta",     "@payloadcms/plugin-seo": "beta",     "@payloadcms/richtext-lexical": "beta",     "@payloadcms/storage-s3": "beta",     "@payloadcms/ui": "beta",

**Comment by AlessioGr** [comment]
This has been fixed in https://github.com/payloadcms/payload/pull/6782. Thank you for reporting this!
