### ISSUE TITLE
[3.0.0-beta.40] req.cookies.get("payload-token") is undefined in NextJS API Route

### ISSUE THREAD

**Issue by sriechersrc** [payloadcms/payload#6632]
### Payload Version

3.0.0-beta.40

### Node Version

v20.10.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

I am trying to implement a live preview, that displays draft changes only inside the payload backend live preview window while the actual frontend only displays published changes. 

I used the code from [https://github.com/payloadcms/website/blob/main/src/app/api/preview/route.ts](https://github.com/payloadcms/website/blob/main/src/app/api/preview/route.ts) to implement an api route that enables the next js draft mode. However in version 3 the line 
```typescript 
const token = req.cookies.get(payloadTokenName)?.value
```
returns undefined, which results in a 403 Error.

My call to the API route looks like this:

```typescript
const activateDraftMode = async (slug: string) => {
  await fetch(
    `http://localhost:3000/api/preview?url=http://localhost:3000/${slug}&secret=${process.env.NEXT_PRIVATE_DRAFT_SECRET}`,
    {
      credentials: 'include',
      cache: 'no-cache',
    },
  )
}
```

Are there some modification for Version 3 I need to make or is this an actual bug?

### Reproduction Steps

1. Add an API route under "/api/preview" with the following code 
```typescript 
import { draftMode } from 'next/headers'
import { redirect } from 'next/navigation'

export async function GET(
  req: Request & {
    cookies: {
      get: (name: string) => {
        value: string
      }
    }
  },
): Promise<Response> {
  const token = req.cookies.get("payload-token")?.value
  const { searchParams } = new URL(req.url)
  const url = searchParams.get('url')
  const secret = searchParams.get('secret')

  if (!url) {
    return new Response('No URL provided', { status: 404 })
  }

  if (!token) {
    new Response('You are not allowed to preview this page', { status: 403 })
  }

  // validate the Payload token
  const userReq = await fetch(`${process.env.NEXT_PUBLIC_URL}/api/users/me`, {
    headers: {
      Authorization: `JWT ${token}`,
    },
  })

  const userRes = await userReq.json()

  if (!userReq.ok || !userRes?.user) {
    draftMode().disable()
    return new Response('You are not allowed to preview this page', { status: 403 })
  }

  if (secret !== process.env.NEXT_PRIVATE_DRAFT_SECRET) {
    return new Response('Invalid token', { status: 401 })
  }

  draftMode().enable()

  redirect(url)
}
```
2. Call the endpoint from a server component using 
```typescript
  await fetch(
    `${process.env.NEXT_PUBLIC_URL}/api/preview?url=${process.env.NEXT_PUBLIC_URL}/${slug}&secret=${process.env.NEXT_PRIVATE_DRAFT_SECRET}`,
    {
      credentials: 'include',
      cache: 'no-cache',
    },
  )
```
3. check that
```typescript
const token = req.cookies.get("payload-token")?.value
``` 
does not return undefined

### Adapters and Plugins

db-postgres

**Comment by SimYunSup** [comment]
It is related NextJS error related in vercel/next.js#60552, vercel/next.js#52209 . I think `next/headers`, `next/cookies`, `next/cache`... is not working properly in RSC with itself server API.

**Comment by jmikrut** [comment]
Hey @sriechersrc — you should try and retrieve cookies with `next/cookies`. Does that work?

https://nextjs.org/docs/app/api-reference/functions/cookies

If there is indeed an issue, it seems to be an issue with Next.js though. We do indeed have access to cookies within Payload 3.x and our patterns work accordingly, so I will close this issue and we should track this on the above Next.js issues instead to de-duplicate.

One other note would be that if you are trying to authenticate, you can do that with `payload.auth({ headers })`. That might simplify things.

**Comment by sriechersrc** [comment]
Retrieving the cookies via `next/cookies` in an API Route seems also to be bugged. But I managed to move the logic to my main page component and dynamically enable draftMode like this:

```typescript
  const isPreview = slugs[slugs.length - 1] === 'preview' // im redirecting to /my-path/preview so I am checking if "preview" exits on the slug

  const payload = await getPayload({
    config: configPromise,
  })

  if (isPreview) {
    const { headers } = await import('next/headers')

    const auth = await payload.auth({ headers: headers() })

    if (auth.user) {
      draftMode().enable()
      slugs.pop() // remove "preview" from the slugs
    } else {
      draftMode().disable()
    }
  }
```
