### ISSUE TITLE
Changing field type results in migration error with postgres

### ISSUE THREAD

**Issue by chrisvanmook** [payloadcms/payload#6633]
### Payload Version

beta.40

### Node Version

v20.11.1

### Next.js Version

15.0.0-rc.0

### Describe the Bug

When I change the type `text` of a field in a collection to `richText`, I get a migration error like `Error running migration 20240605_112852 column "another_field" cannot be cast automatically to type jsonb.`.

### Reproduction Steps

1. Clone https://github.com/payloadcms/payload-3.0-demo and run `pnpm install`
2. In `payload.config.ts` replace the `db` value:
```ts
db: postgresAdapter({
    pool: {
      connectionString: process.env.POSTGRES_URI || '',
    },
  }),
```
3. Create DB by running `start-database.sh` and add `POSTGRES_URI=postgresql://postgres:password123@127.0.0.1:5432/next-payload-3` to `.env`
4. Run `payload migrate:create` and `payload migrate`
5. In `payload.config.ts` replace the type of the `title` field in `pages` to `richText`
6. Repeat step 4 and read the error
 
Also note that I also get the same error if I do not run the migrations manually, but just have my dev environment running.

### Adapters and Plugins

db-postgres

**Comment by SimYunSup** [comment]
I think it is `drizzle-kit` error in `@payloadcms/db-postgres`. I raised an issue with drizzle-kit, but since drizzle-kit is closed source, I think it would be better to change the migration code temporarily.

```sql
ALTER TABLE "pages" ALTER COLUMN "title" SET DATA TYPE jsonb USING to_jsonb("title");
```

You can fix this by adding an `USING to_jsonb("title")` after `SET DATA TYPE jsonb`.

**Comment by DanRibbens** [comment]
I agree with @SimYunSup. This is a drizzle-kit concern. I looked for an existing issue in https://github.com/drizzle-team/drizzle-kit-mirror/issues, can you provide a link?

@AndriiSherman is it expected that drizzle-kit should handle this kind of column change or is it a user requirement to handle in migrations?

**Comment by SimYunSup** [comment]
It is on drizzle-team/drizzle-kit-mirror#458 with example in [here](https://github.com/SimYunSup/example-list/tree/drizzle-kit/jsonb-error).

**Comment by jmikrut** [comment]
OK - let's track this issue on Drizzle instead of Payload to consolidate. 👍 thanks for the report!
