### ISSUE TITLE
export useNav() to use in custom Nav components

### ISSUE THREAD

**Issue by genox** [payloadcms/payload#6635]
### Payload Version

3.0.0-beta40

### Node Version

20

### Next.js Version

15 rc0

### Describe the Bug

useNav() can't be imported right now. When creating slightly modified Nav components, this can come in handy, e.g. cloning and extending the original Nav component.

See: https://discord.com/channels/967097582721572934/1242356912633151498

### Reproduction Steps

try to import useNav() and notice that there is no module resolution.

**Comment by JarrodMFlesch** [comment]
`useNav` can now be imported like so:

```ts
import { useNav } from '@payloadcms/ui'
```
