### ISSUE TITLE
Can't create a new draft in v2.19.0

### ISSUE THREAD

**Issue by wkentdag** [payloadcms/payload#6671]
### Link to reproduction

https://github.com/wkentdag/payload-draft-test/commit/6dc361458e2e29f6f271dd41427b3c06d74a4068

### Describe the Bug

When creating a new versioned document in v2.19.0, the "save draft" button stays disabled until you hit "publish", effectively preventing users from creating a new draft document.

Before (v2.18.3):
https://github.com/payloadcms/payload/assets/3254957/91332a41-5a5e-4a3d-83a9-5e12444515d3

After (v2.19.0):
https://github.com/payloadcms/payload/assets/3254957/7df3ab7f-11e1-4503-b7d3-1bb4c7c86f87

### To Reproduce

To repro, just run `npx create-payload-app`, add a versioned collection, and try to create a draft in the admin panel. 

You can check out my repo where I successively update the deps and narrow in on `payload@2.19.0` as the culprit.

```ts
import { CollectionConfig } from "payload/types";

const Posts: CollectionConfig = {
  slug: "posts",
  versions: {
    drafts: true,
  },
  admin: {
    useAsTitle: "title",
  },
  fields: [
    {
      name: "title",
      type: "text",
    },
  ],
};

export default Posts;
```

### Payload Version

2.19.0

**Comment by wkentdag** [comment]
I think this change needs to get reverted: https://github.com/payloadcms/payload/commit/8f03cd7c789eda7613ddced0d45a32afe49b1e01#diff-b7c978f47b1f3beff95c78ad95078e600624cbcd7ac10f9378cc4ad6803db244L75-R79

**Comment by javierlinked** [comment]
@denolfe @JessChowdhury this regression breaks our workflow for content editor. I see there's a https://github.com/payloadcms/payload/pull/6672 PR waiting for approval, is there any due to date on this, it looks minor, and we don't want to downgrade Payload version? Highly appreciated.

**Comment by javierlinked** [comment]
Great, thanks!
