### ISSUE TITLE
Cannot add property shouldBreakOutOnEnter, object is not extensible

### ISSUE THREAD

**Issue by italodr** [payloadcms/payload#6674]
### Link to reproduction

https://github.com/italodr/test-payload3

### Payload Version

3.0.0-beta.36

### Node Version

v20.10.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

When running on Payload 3.0 I receive the following TypeError: 
`TypeError: Cannot add property shouldBreakOutOnEnter, object is not extensible`

I followed Payload's documentation on how to build a custom Slate rich text element:
https://payloadcms.com/docs/rich-text/slate#shouldbreakoutonenter. 

I copied the code from Payload's website CMS:
https://github.com/payloadcms/website-cms/blob/main/src/fields/richText/largeBody/plugin.ts

```tsx
export const withLargeBody = (incomingEditor) => {
  const editor = incomingEditor
  const { shouldBreakOutOnEnter } = editor

  editor.shouldBreakOutOnEnter = (element) =>
    element.type === 'large-body' ? true : shouldBreakOutOnEnter(element)

  return editor
}
```

### Reproduction Steps

Use the repo I posted in the Link reproduction. It's a copy from Payload 3.0 Beta Demo

- Clone the repo to your computer `git clone git@github.com:italodr/test-payload3.git`
- cd into the new folder by running `cd ./test-payload3`
- Install dependencies with whatever package manager you use (yarn, npm install, pnpm i, etc.)
- Start your database. For local postgresql use `.\start-database.sh` to start it in docker container.
- Fire it up (yarn dev, npm run dev, pnpm dev, etc.)
- Visit https://localhost:3000/admin and log in with the user created within the config's onInit method

### Adapters and Plugins

db-postgres, richtext-slate

**Comment by paulpopus** [comment]
Hey @italodr in 3.0 the slate elements have to be wrapped slightly differently due to the structure of RSCs so your plugin needs to be inside a `'use client'` component.

See this for an example of how a plugin is structured in our 3.0 slate package https://github.com/payloadcms/payload/blob/beta/packages/richtext-slate/src/field/elements/relationship/plugin.tsx

We have a few elements there so you can see how they've been restructured

**Comment by italodr** [comment]
Thanks a lot @paulpopus
