### ISSUE TITLE
GraphQLJSON type not exposed for use in custom endpoints

### ISSUE THREAD

**Issue by geisterfurz007** [payloadcms/payload#6683]
### Link to reproduction

https://github.com/geisterfurz007/payload-3.0-graphql-repro

### Payload Version

3.0.0-beta.43

### Node Version

20.14.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

It's not possible to use a JSON type in custom GraphQL endpoints because payload uses an internal class that is not exposed. Using either of these imports (the upper one being what had worked in previous (stable) versions of payload) will lead to the same error:

```ts
import GraphQLJSON from "graphql-type-json";
import {GraphQLJSON} from 'graphql-scalars';
```

The error being:

```
 ⨯ Error: Schema must contain uniquely named types but contains multiple types named "JSON".
    at new GraphQLSchema (E:\Projects\Private\payload-3.0-graphql-repro\node_modules\graphql\type\schema.js:219:15)
    at configToSchema (webpack-internal:///(rsc)/./node_modules/@payloadcms/graphql/dist/index.js:101:20)
    at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/next/dist/routes/graphql/handler.js:68:95)
    at new Promise (<anonymous>)
    at getGraphql (webpack-internal:///(rsc)/./node_modules/@payloadcms/next/dist/routes/graphql/handler.js:67:26)
[...snip]
```

Poking about, it seems that `graphql-type-json` was copied over [here](https://github.com/payloadcms/payload/tree/beta/packages/graphql/src/packages/graphql-type-json) but it's not exposed anywhere for users to consume when building custom endpoints.

### Reproduction Steps

1. Clone the repo `git clone git@github.com:geisterfurz007/payload-3.0-graphql-repro`
2. Install dependencies `yarn`
3. Start the database `./start-database.sh`
4. Launch next: `yarn dev`
5. Send a POST request to the endpoint to trigger a build of the schema: `curl -X POST http://localhost:3000/api/graphql`

**Comment by JarrodMFlesch** [comment]
@geisterfurz007 a fix will be available in the next beta release. Check out this PR for more details: https://github.com/payloadcms/payload/commit/a26d03190e16fed3f526821f91ce998c1c2d4e99
