### ISSUE TITLE
Unable to create custom view with custom path

### ISSUE THREAD

**Issue by benjosua** [payloadcms/payload#6686]
### Payload Version

3.0.0-beta.43

### Node Version

20.9.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Overwriting the default account view works.
```
admin: {
    components: {
      views: {
        Account: Component,
      },
  },
},
```
But setting a custom path and then going to the url returns undefined.

```
admin: {
    components: {
      views: {
        "custom-path": Component,
      },
  },
},
```

### Reproduction Steps

1. Create a payload beta app
2. Create a custom view
3. Link it in the payload config via a custom path

**Comment by PatrikKozak** [comment]
Hey @benjosua - to add a custom view with a custom path, you'll need to add the `path` and `Component` property to your key in the `views` object - like this:

```
admin: {
    components: {
      views: {
        MyCustomView: {
          Component: MyCustomView,
          path: '/my-custom-view',
        },
      },
    },
  },
```

This should resolve your issue - let me know if you have any other questions! Going to close for now, if you're still experiencing any issues with this, I'll reopen and we can diagnose further.
