### ISSUE TITLE
Cropping with sharp blows up

### ISSUE THREAD

**Issue by geisterfurz007** [payloadcms/payload#6694]
### Link to reproduction

https://github.com/geisterfurz007/payload-3.0-graphql-repro/tree/issue/crop-true-metadata-undefined

### Payload Version

3.0.0-beta.43

### Node Version

20.14.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Cropping is enabled by default. Passing sharp in the configuration and making changes to an image makes it impossible to save the image.

### Reproduction Steps

1. Clone the repository `git clone --branch issue/crop-true-metadata-undefined git@github.com:geisterfurz007/payload-3.0-graphql-repro.git`
2. Install dependencies `yarn`
3. Start the database `./start-database.sh`
4. Start the dev server `yarn dev`
5. Login at http://localhost:3000/admin, start creating a new Media entity, select a file, click edit image, then apply changes
6. Try to save the entity
7. *poof*

### Adapters and Plugins

sharp is passed in the payload-config

**Comment by geisterfurz007** [comment]
Shot in the dark is that this `&& sharp` should have been `&& sharpFile` as in the guard a couple lines above:

https://github.com/payloadcms/payload/blob/1bd91b23caab08046e31a1696bcfa9b0d32254fc/packages/payload/src/uploads/generateFileData.ts#L203-L205

But since I would have expected there to be a sharpFile if cropping was requested, so I didn't want to make a PR if there was more stuff to do on that front.

**Comment by tylandavis** [comment]
I ran into this as well last night on `beta-41` or newer. Noticed its only happening for me with certain image files. WebP/GIF has errors, PNG/JPG/SVG uploads fine. I think it might be related to the changes in #6623

**Comment by PatrikKozak** [comment]
@geisterfurz007 @tylandavis 

thanks for reporting this! The issue has been fixed with this [PR](https://github.com/payloadcms/payload/pull/6708).

**Comment by tylandavis** [comment]
@PatrikKozak Looks like non-animated WebP's are still running into issues. Animated WebP's are fine.

**Comment by geisterfurz007** [comment]
I haven't gotten around to testing yet but it does strike me as suspicious that `cropData` is not listed for `fileHasAdjustments`; could that be the possible culprit for non-animated webps still causing issues (if they do)?

**Comment by PatrikKozak** [comment]
@tylandavis good catch, appreciate it - just merged a fix for this on both [v3](https://github.com/payloadcms/payload/pull/6728) and [v2](https://github.com/payloadcms/payload/pull/6729).

@geisterfurz007 the culprit to the above is when we are calculating the `height` for animated images we need to take the images incoming `height` and divide it by it's `pages`. 

`pages` comes from the images `metadata`. However, if an image is not animated and of mimetype `gif`, `webp`, etc we need to make sure not to calculate its `height` using `metadata.pages`.

We were previously not making this check, but I have just went ahead and updated - should be all set now.
