### ISSUE TITLE
Unable to have global layout - custom "not-found" 404 page and global Metadata

### ISSUE THREAD

**Issue by todor0v** [payloadcms/payload#6695]
### Payload Version

3.0.0-beta.43

### Node Version

20.13.1

### Next.js Version

15.0.0-rc.0

### Describe the Bug

@jacobsfletch This is related to https://github.com/payloadcms/payload/issues/6511, however I believe that it is about more than just 404 pages, so I am creating a new issue. Let me know if you do not approve and I will comment there instead.

I have three main problems that I cannot solve with the current `layout.tsx` logic:

- I want to have global Metadata
- I want to have one global `layout.tsx`
- I want to have a custom global 404 page

First I read the [blog post](https://payloadcms.com/blog/30-beta-install-payload-into-any-nextjs-app-with-one-line) on the beta install and as I understood, if I have `layout.tsx` file inside of `app/(app)`, that should work globally (I should be able to have the same `metadata` for all pages for example (and then have individual ones if I want to). The more I read through the Demo code, however, the more I don't see how would this be possible. The layout file in `app/(app)` is not a global layout file. Which means that I cannot use it for meta, or 404. This has the additional problem that every time I create a new page, Next.js generates a `layout.tsx` automatically for that path. I end up with multiple layout files that are essentially the same thing, because the main one cannot be used. 

At the same time I cannot just create a `layout.tsx` directly inside of `app`. This clashes with the Payload `/admin` page. This is understandable, but as of now I cannot find a good way to solve my problems. What I was able to do so far is this:

src/app/layout.tsx:
```ts
import type { Metadata } from "next";
import "@/css/index.css";
import { getPathname } from "@nimpl/getters/get-pathname";

export const metadata: Metadata = {
	title: "My Website",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const pathname = getPathname();

	if (pathname?.includes("/admin")) {
		return children;
	} else {
		return (
			<html lang="en">
				<body>
					<div>{children}</div>
				</body>
			</html>
		);
	}
}

```
Ideally Next.js should provide a way for me to check the `pathname` on the server, however as per [this issue](https://github.com/vercel/next.js/issues/43704), it currently does not. I had to use [third party solution](https://github.com/vordgi/nimpl-getters) to reliably get the `pathname` and based on that either return the children directly (thus not affecting the admin panel) or the page (thus being able to have a custom layout.

Would you please advise me if there is or there will be a better way to do this in the future?

Thank you!

cc: @jmikrut since you assigned the original issue

### Reproduction Steps

- use the [Demo repo of Payload 3](https://github.com/payloadcms/payload-3.0-demo/) or `npx create-payload-app@beta`
- use the `layout.tsx` inside `app/(app)` as advised
- you cannot have global layout this way or a global 404 page

### Adapters and Plugins

db-mongodb, babel-plugin-react-compiler

**Comment by bryanjhickey** [comment]
@todor0v Why can't you define global metadata in `app/(app)/layout.tsx`? I've been doing this for years.

**Comment by todor0v** [comment]
@bryanjhickey I could if I have the other pages in `app/(app)` as well. I believe that I wrongly interpreted the [Payload 3.0 Demo](https://github.com/payloadcms/payload-3.0-demo/tree/main/src/app) and though that they should be placed in `app` (outside of `(app)`. Once you do that, Next.js will start creating "Generated by Next.js" `layout.tsx` files and the meta that is in `app/(app)/layout.tsx` will be ignored. However, what they did is just use that place for a `route.ts` file that is not a page. So you are correct. If I have for example: `app/(app)/about`, that could use the `layout.tsx` with its metadata. This still doesn't fix the global 404 page problem though, because `not-found.tsx` would have to live outside of `app/(app)/` and will lack a layout file.

**Comment by todor0v** [comment]
I also found another weird behavior that I cannot debug so far. 
With my current setup (a global `layout.tsx` file in `src/app` that checks for `pathname?.includes("/admin")`), if you go to a 404 page (for example `https://domain.com/wsdfawdf`), the latest content from Payload CMS displays as it should. You can update it and see the changes. However if you go to `https://domain.com/404` specifically, the content is whatever it was after the last build process. I tried different variations of `revalidatePath` with an `afterChange` hook with no luck so far.

**Comment by todor0v** [comment]
I believe that I found a better solution

So to summarize, the solutions are as follows:

- I want to have global Metadata - use `export const metadata` inside of `app/(app)/layout.tsx`
- I want to have one global layout.tsx - use `app/(app)/layout.tsx`
- I want to have a custom global 404 page - create an `app/laout.tsx` with the following content:
```ts
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return children;
}
```
Then create an `app/not-found.tsx` file that should contain a whole page (`<html>, `<body>` etc.).

This will solve all of the problems without resolving to checking pathname.

@jacobsfletch If you believe this to be an acceptable approach, this issue can be closed.

**Comment by jacobsfletch** [comment]
@todor0v first of all, thank you for the details here. Great to see and very helpful. I went ahead and took a quick pass at #6511 just now and found a temporary workaround. Check out [my comment here](https://github.com/payloadcms/payload/issues/6511#issuecomment-2256546884) for details.

Let me address a few of your points directly:

> I want to have global Metadata
> I want to have one global layout.tsx
> I want to have a custom global 404 page

When you say "global" I assume you mean throughout every page within your own application, i.e. not including the admin panel. So for example, you can control metadata for your "home" page and your "about" page from the same location. 

This should already work as-is.

In your application you should have a `(app`) route group directly alongside `(payload)`. In there, you can add a `layout.tsx` file which manages all metadata for that route group, just as @bryanjhickey suggested. Same with the error page—a workaround has been posted to [this Next.js discussion](https://github.com/vercel/next.js/discussions/50034). 

Here's the setup:

```plaintext
app
├── (app)
│   ├── [...not-found]
│   │   └── page.tsx
│   ├── layout.tsx
│   ├── not-found.tsx
│   └── page.tsx
── (payload)
   ├── admin
   └── layout.tsx
```

In `(app)/[...not-found]/page.tsx`:

```ts
import { notFound } from 'next/navigation';

export default function NotFoundDummy() {
 notFound();
}
```

In `(app)/layout.tsx`:

```ts
export const metadata = {
  title: 'This is global metadata for your app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
```

**Comment by todor0v** [comment]
@jacobsfletch Thank you so much for the help! This solution works for me and I can have a global 404 page without the workaround with returning different code structure for the panel and the global layout.

I only have one problem with this approach that I discovered. If you go to `/404` specifically, you will see the default 404 page and not the custom one. Any other URL that triggers a 404 is fine, but `/404` for some reason is not. Can I fix that?
