### ISSUE TITLE
Token expiration has an undocumented upper limit

### ISSUE THREAD

**Issue by GeorgeyB** [payloadcms/payload#670]
# Bug Report

It is currently not possible to use an `auth.tokenExpiration` value of more than 2147484.

## Expected Behavior

The user should be authenticated for the length of time provided.

## Current Behavior

After authenticating, the user is immediately logged out and redirected to the `/admin/logout-inactivity` page.

## Steps to Reproduce

1. Initialise a new Payload instance using a "blank" template and a local MongoDB instance.
2. In `./src/collections/User.ts`, set the `auth.tokenExpiration` to 2147485 or more
3. Start the instance with `yarn dev`
4. Complete first registration page

## Detailed Description

Tested with Payload 0.18.0

**Comment by jmikrut** [comment]
Hey @GeorgeyB — I just went through and evaluated where this limit would be imposed and can't see anything that would impose a limit at all. I haven't replicated your issue yet, but at first glance, this is strange.

We use the package `jsonwebtoken` to sign JWTs, and the `tokenExpiration` is passed directly to that package's `expiresIn` property. We also use the `tokenExpiration` to expire cookies, but I can't see anything that would limit the cookie `expires` property either.

I assume that through testing this, you have set the long `expires` and seen a cookie indeed expire after your ~25 day window? Tough thing to test! 

PS - how'd you come up with the exact `2147484` number? 

Let me know. We'll remedy in any case!

**Comment by GeorgeyB** [comment]
Hi @jmikrut, very weird!

I haven't tested whether or not the cookie does expire after a long (2147484-second) expiry option, though I've no reason to believe it wouldn't.

Here's a video to try and demonstrate the issue:

https://user-images.githubusercontent.com/13889255/175009287-0bb45003-5aac-4d56-975f-224485fe5b4d.mp4

This was done on a brand new Payload installation as of an hour or so ago (so now v0.18.1)

I was attempting to provide an expiry time of 30 days and this error started occuring, I then went on to find the issue only occured for 2147485 seconds or more by process of elimination.

**Comment by jmikrut** [comment]
Well, figured it out @GeorgeyB. Good catch. Check out the commit above for the fix. Turns out `setTimeout` has a max upper timeout limit, and you found it.

> Browsers including Internet Explorer, Chrome, Safari, and Firefox store the delay as a 32-bit signed integer internally. This causes an integer overflow when using delays larger than 2,147,483,647 ms (about 24.8 days), resulting in the timeout being executed immediately.

TIL! Thank you!

Fix released in `0.18.3`.

**Comment by GeorgeyB** [comment]
TIL too. Thanks for looking into it.
