### ISSUE TITLE
Password reset form responds with forbidden status

### ISSUE THREAD

**Issue by GeorgeyB** [payloadcms/payload#671]
# Bug Report

As a user, I cannot reset my password using the password reset form that ships with Payload.

## Expected Behavior

My password should be successfully changed.

## Current Behavior

The form responds with the message "You are not allowed to perform this action" and a 401 Forbidden status.

## Possible Solution

N/A

## Steps to Reproduce

1. Initialise a new Payload instance using a "blank" template and a local MongoDB instance.
2. Set a working email transport
3. Start the instance with `yarn dev`
4. Register a first user and logout
5. Navigate to the `/admin/forgot` page and complete the form
6. Recieve the "Reset your password" email and navigate to the link contained within
7. Complete the form on the `/admin/reset/:token` page
8. Receive forbidden error

## Detailed Description

Tested on Payload 0.18.0

**Comment by jmikrut** [comment]
Ahh good catch @GeorgeyB and @sawariz0r — this was related to some large simplifications and cleanup we did when we released `0.18.0`. 

Released a patch version `0.18.1` that fixes the issue. Also, we're adding more tests around this for our upcoming `1.0.0` release. 

Thank you!
