### ISSUE TITLE
Missing descriptive error when running without "build" directory

### ISSUE THREAD

**Issue by mryellow** [payloadcms/payload#6713]
# Documentation Issue

There is no indication of what the problem is when attempting to run without the `build` directory.

## Additional Details

There should be a descriptive error thrown.

**Comment by mryellow** [comment]
See https://github.com/payloadcms/payload/issues/6609

**Comment by paulpopus** [comment]
When building it's important to keep the `build` directory available for the app to run in addition to dist.

Closing this as it will not be a problem in 3.0 where Nextjs will return an error when trying to start the app without a production build available.

**Comment by mryellow** [comment]
Will 2.0 have no further improvement?
