### ISSUE TITLE
When using role based user fields, /create-first-user form always returns "passwords do not match"

### ISSUE THREAD

**Issue by sriechersrc** [payloadcms/payload#6720]
### Payload Version

3.0.0-beta.40

### Node Version

v20.10.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

I tried adding role based auth fields to my Users collection, then deleted my database and started from scratch. However when I try to create my first user the form always shows an error that the passwords do not match. If I remove the role fields I can create a User as expected.

My Users collection looks like this:

```typescript
import type { CollectionConfig } from 'payload/types'

export const Users: CollectionConfig = {
  slug: 'users',
  admin: {
    useAsTitle: 'email',
  },
  auth: true,
  fields: [
    {
      name: 'role',
      type: 'select',
      options: [
        { label: 'Admin', value: 'admin' },
        { label: 'User', value: 'user' },
      ],
      required: true,
      defaultValue: 'user',
    },
  ],
}
```

I've used this [tutorial](https://payloadcms.com/blog/build-your-own-rbac)

### Reproduction Steps

1. Add role field to the Users collection 
```typescript
    {
      name: 'role',
      type: 'select',
      options: [
        { label: 'Admin', value: 'admin' },
        { label: 'User', value: 'user' },
      ],
      required: true,
      defaultValue: 'user',
    }
```
3. create new database and add it to the project
4. go to /admin and try to create a new user
5. on submit the form will show an error with "Passwords do not match"

### Adapters and Plugins

db-postgres

**Comment by paulpopus** [comment]
Hey @sriechersrc I just tested this with both postgres and mongodb and I'm not able to reproduce this. I can enter the password and choose a role to create a user just fine.

Can you make sure all of your payload packages are on the latest beta? In 3.0 payload package versions should all be the same.

Otherwise are you able to provide a repo? I'll gladly re-open this issue with a reproduction

**Comment by sriechersrc** [comment]
I updated all the packages and now its working as expected. Thank you for your help!
