### ISSUE TITLE
Non-default admin.avatar renders nothing

### ISSUE THREAD

**Issue by khlieng** [payloadcms/payload#6725]
### Payload Version

3.0.0-beta.44

### Node Version

v20.12.2

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Setting `admin.avatar` to anything other than `'default'` renders nothing, broken since 14e2a6b.

### Reproduction Steps

1. Set `admin.avatar` to a custom component
2. Observe lack of avatar

**Comment by denolfe** [comment]
Closed by #6765

**Comment by denolfe** [comment]
Thanks for the report @khlieng !
