### ISSUE TITLE
WebP Upload Issue with undefined height

### ISSUE THREAD

**Issue by kirillminiaev** [payloadcms/payload#6727]
### Describe the Bug

When uploading a WebP image to a collection that is defined as an "uploadable" collection, if no `height` is defined in an `imageSizes` array child (as per the documentation to keep aspect ratio), a `NaN` is provided to the sharp "resize" function (for the `top` value) which causes Sharp to send an error message.

More details:

In my `imageSizes` array I have entries formatted as follows:
```
{
        name: 'large',
        width: 900,
        height: undefined
},
...
```
When I attempt to upload a WebP file, I get the following Sharp error: `Expected integer for top but received NaN of type number`. This is stack traced to `/node_modules/sharp/lib/resize.js:476:16` & `/node_modules/payload/src/uploads/imageResizer.ts:312:19`

After reviewing the source code, it looks like all WebP images for Payload are hardcoded as animated images (`/node_modules/payload/dist/uploads/imageResizer.js:179`)  (even though in my case my WebP image is a static file) which then forces the first condition of the ternary conditional on line 219. `resizeHeight` is not defined in the `imageSizes` array entry so we get `undefined - safeResizeHeight` which causes the `NaN`. My fix was to modify line 219 and check for a value on `resizeHeight`:

Original : `const maxOffsetY = fileIsAnimated ? resizeHeight - safeResizeHeight : scaledImageInfo.height - safeResizeHeight;`

Fixed: `const maxOffsetY = fileIsAnimated && resizeHeight ? resizeHeight - safeResizeHeight : scaledImageInfo.height - safeResizeHeight;`

### To Reproduce

1. Create a STATIC WebP file (i.e. export JPG as WebP with Photoshop)
2. Create uploadable collection in Payload
3. Define `imageSizes` array with `undefined` in height values
4. Attempt to upload WebP file

### Payload Version

2.19.3

### Adapters and Plugins

npx create-payload-app@latest with Postgres

**Comment by todor0v** [comment]
I have the exact same issue on Payload `3.0.0-beta.43` and Sharp `0.33.4`. 

If I do not specify the height at all, I get:
```ERROR: FileUploadError: There was a problem while uploading the file. at generateFileData (webpack-internal:///(rsc)/./node_modules/payload/dist/uploads/generateFileData.js:232:15)```

If I specify the height as any number or `undefined`, I get:
``` ERROR: ValidationError: media validation failed: sizes.image.height: Cast to Number failed for value "NaN" (type number) at path "height"```

**Comment by kirillminiaev** [comment]
> I have the exact same issue on Payload `3.0.0-beta.43` and Sharp `0.33.4`.
> 
> If I do not specify the height at all, I get: `ERROR: FileUploadError: There was a problem while uploading the file. at generateFileData (webpack-internal:///(rsc)/./node_modules/payload/dist/uploads/generateFileData.js:232:15)`
> 
> If I specify the height as any number or `undefined`, I get: ` ERROR: ValidationError: media validation failed: sizes.image.height: Cast to Number failed for value "NaN" (type number) at path "height"`
> 
> For me the suggested `maxOffsetY` fix did not work.

@todor0v can you post a full error stack-trace. Seems you may need to adjust the code pertaining to the specific `Cast to Number failed for value "NaN" (type number) at path "height"` error for a fix for your version of Payload.

**Comment by todor0v** [comment]
@kirillminiaev Of course:
![image](https://github.com/payloadcms/payload/assets/84301735/d8c86826-1e65-46e0-82d4-48b7fc366bc2)

**Comment by kirillminiaev** [comment]
> @kirillminiaev Of course: ![image](https://private-user-images.githubusercontent.com/84301735/338690170-d8c86826-1e65-46e0-82d4-48b7fc366bc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMjgwNDksIm5iZiI6MTcxODEyNzc0OSwicGF0aCI6Ii84NDMwMTczNS8zMzg2OTAxNzAtZDhjODY4MjYtMWU2NS00NmUwLTgyZDQtNDhiN2ZjMzY2YmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE3NDIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZWRjZDM1ZjMwMzBkZDc3MDk1ODE3ZGNkOWQ5M2I3YWM5MjdjN2YzNDZhZTdhZjQzMWM1OWU5MGU2NjI0NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rptEMHEziRwypQXw_Jh_QhIr4_Y9orIqLt8dhkDP-kY)

@todor0v your error seems to be related more to your database: MongoDB. It's as if the database model expects there to be a "height" value for your resizing and when a `NaN` value is passed, the internal Model validation kicks in and spews the error. So in your case, I would think either a height is `required` (and the Payload team needs to address a workaround) or code needs to ensure that a `NaN` is not passed to the model. Ultimately, it could be that whatever data is passed to the `Next Ctea.js:20:17` line needs to be pre-processed to validate the `height` parameter. At least that is where I would start my debugging process if I were you.

**Comment by denolfe** [comment]
Fairly certain this is the fix https://github.com/payloadcms/payload/pull/6729

**Comment by kirillminiaev** [comment]
> Fairly certain this is the fix #6729
> 
> Let's verify in the next 2.x release.

@denolfe thank you. Looking forward to the next release with the fix implemented.

**Comment by kirillminiaev** [comment]
@PatrikKozak, just upgraded to 2.20.0 and the issues persists. Not sure if you were planning to push the fix with this next release. My original fix patched the issue in 2.20.0

**Comment by PatrikKozak** [comment]
Hey @kirillminiaev 

I have a fix for the issue [here](https://github.com/payloadcms/payload/pull/6733).

V3 fix is [here](https://github.com/payloadcms/payload/pull/6757)

We'll get these merged either today or tomorrow!

**Comment by kirillminiaev** [comment]
Thank you @PatrikKozak@
