### ISSUE TITLE
Jsonschema requires uri and filematch despite schema being directly defined

### ISSUE THREAD

**Issue by TomDo1234** [payloadcms/payload#6737]
### Describe the Bug

```

{
      name: 'product_photos',
      type: 'json',
      required:true,//[{url: string},{url : string}]
      jsonSchema: {
        uri: '_',
        fileMatch: ['_'],
        schema: {
          type: 'array',
          items: {
            type: "object",
            properties: {
              url: {
                type: "string"
              }
            }
          }
        }
      }
    }
```
    
    
when defining a json schema, uri and fileMatch are somehow required even when I define the schema directly into the collection config
Payload 2.19
If I choose to omit uri and fileMatch, then it will reject every time, nothing becomes valid

### To Reproduce

1. Create a collection
2. Make a json field, basically copy paste what I have above, make sure its a json field and define a jsonschema directly, BUT dont include uri and fileMatch as I have above

3. Observe everything getting rejected, json will get rejected even if it follows schema

### Payload Version

2.19

### Adapters and Plugins

db-postgres

**Comment by kendelljoseph** [comment]
Hi @TomDo1234, I'm taking a look into this today!

**Comment by kendelljoseph** [comment]
`uri` and `fileMatch` are indeed requirements in a valid schema structure right now.  

**Solution:**
If you don't have a URI or file to match, you can use one like the one used in the documentation for [Local JSON Schemas](https://payloadcms.com/docs/fields/json#local-json-schema).

This attributes are currently a requirement to use JSON schemas as required by the [JSON schema org](https://json-schema.org/).
