### ISSUE TITLE
Locale switch sometimes shows wrong locale

### ISSUE THREAD

**Issue by yobottehg** [payloadcms/payload#6739]
### Payload Version

3.0.0-beta.41

### Node Version

20.12.x

### Next.js Version

15.0-rc.0

### Describe the Bug

After navigating and using the browser back button the shown locale is wrong and persisted on hard page reloads. Only a manual set of the locale is correct.

Here a video where i showcase the issue with the browser back button.

locales are: de, en, hu
default locale is: de

https://github.com/payloadcms/payload/assets/12897717/3b169000-6d1a-4143-8c09-c410f174fbd9

### Reproduction Steps

- Go to a entity detail page
- Switch the locale
- Use the browser back button

Locale is not reset or set back to the default.

### Adapters and Plugins

db-postgres

**Comment by JarrodMFlesch** [comment]
@yobottehg this is actually working as intended.

When you set your locale, it sets a preference for your user in the database with the selected locale. When you navigate back to the list view it will use your preference if it is set.

It is possible that we might set the locale query param in the list view if it is not present, which would be prioritized over the preference setting. But for now we are going to keep it as is.
