### ISSUE TITLE
type SelectFieldProps onChange props is typed incorrectly

### ISSUE THREAD

**Issue by tophermurphy** [payloadcms/payload#6753]
### Payload Version

   "@payloadcms/ui": "3.0.0-beta.45", "payload": "3.0.0-beta.45",

### Node Version

20.14

### Next.js Version

15.0.0-rc.0

### Describe the Bug

```ts
// file: @payloadcms/ui/dist/fields/Select/index.d.ts

export type SelectFieldProps = FormFieldBase & {
    hasMany?: boolean;
    isClearable?: boolean;
    isSortable?: boolean;
    name?: string;
    onChange?: (e: string) => void;
    options?: Option[];
    path?: string;
    value?: string;
    width?: string;
};
```

onChange should be typed something like below to reflect the type of parameter the SelectInput onChange event.

```ts
onChange: (e: string | {  value: string, label: string }) => void
```

### Reproduction Steps

Use the <SelectInput /> component with options that are an array of objects { value: string, label: string }. Then console log or try to use the onChange method event parameter.

**Comment by AlessioGr** [comment]
Thank you! Fixed by https://github.com/payloadcms/payload/pull/6785
