### ISSUE TITLE
CollapsibleProvider's withinCollapsible is never true. Missing withinCollapsible related CSS classes.

### ISSUE THREAD

**Issue by franciscolourenco** [payloadcms/payload#6760]
### Link to reproduction

https://github.com/payloadcms/payload/compare/franciscolourenco:reproduce-within-collapsible-missing

### Describe the Bug

All CSS classes related to CollapsibleProvider's `withinCollapsible` are missing. It. looks like CollapsibleProvider's `withinCollapsible` is not working as expected. It causes some visual bugs in the `tabs` field when nested inside a `collapsible`.

Related: [withinCollapsible's default value was changed to default in v.2.20.0](https://github.com/payloadcms/payload/pull/6666)

### To Reproduce

1. Nest a `collapsible`, `group`, or `tabs` field inside a `collapsible` or `array` field.
2. Verify that the CSS classes associated with `withinCollapsible` are missing.

![image](https://github.com/payloadcms/payload/assets/208149/77883763-c94f-41bb-ba59-607d7b161a30)

### Payload Version

2.20.0

**Comment by JessChowdhury** [comment]
Hey @franciscolourenco - thanks for raising this! The previous issue fix did indeed introduce this bug - we have corrected it now and will go out in the next release.
