### ISSUE TITLE
app not response when use payload local api in hook like afterRead

### ISSUE THREAD

**Issue by jesse996** [payloadcms/payload#6788]
### Payload Version

3.0.0-beta.47

### Node Version

20.14.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

app not response when use payload local api in hook like afterRead

### Reproduction Steps

in collection afterRead hook, i want to use payload.find ,but then the app crushed

**Comment by paulpopus** [comment]
Hey, happy to take a closer look if you can provide a reproduction. I'll close this issue until we have further information.
