### ISSUE TITLE
Nodemailer Email Adapter: skipVerify=true does not skip verification

### ISSUE THREAD

**Issue by sroaam** [payloadcms/payload#6789]
### Payload Version

3.0.0-beta.47

### Node Version

20.10.0

### Next.js Version

15.0.0-canary.29

### Describe the Bug

The `skipVerify` option of the `NodemailerAdapterArgs` has exactly the opposite effect.

`skipVerify: true` > Verifies the nodemailer transport
`skipVerify: false` > Does not verify the nodemailer transport

```ts
import { nodemailerAdapter } from "@payloadcms/email-nodemailer";
...
export default buildConfig({
...
  email: nodemailerAdapter({
      ...
      skipVerify: true,
      ...
  }),
...
}
```

### Reproduction Steps

1. Add the `@payloadcms/email-nodemailer `package to your Next.js/Payload project
2. Configure the adapter according to the docs [Nodemailer Email Adapter Docs](https://www.npmjs.com/package/@payloadcms/email-nodemailer?activeTab=readme)
3. Set the `skipVerify` option to `true`
4. Run/Build your Next.js/Payload project

Result: Nodemailer transporter.verify will be executed

### Adapters and Plugins

@payloadcms/email-nodemailer, nodemailer

**Comment by denolfe** [comment]
Closed by https://github.com/payloadcms/payload/pull/6790
