### ISSUE TITLE
#6718 generate:types Fails with Endpoint in Collection Configuration reproduction

### ISSUE THREAD

**Issue by peterkunsay** [payloadcms/payload#6791]
### Link to reproduction

https://github.com/peterkunsay/payload-3.0-demo-generate-types-issue/tree/master

### Payload Version

3.0.0-beta.45

### Node Version

v20.9.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Hello,

As requested by @AlessioGr, I have created a reproduction repository for issue #6718. I have completely stripped down my original project, and the issue persists. When I include any endpoint in my `./src/admin/collections/admin_media.ts` file, the `generate:types` command fails with the following error:
```
pnpm run generate:types

> next-latest-starter@0.1.0 generate:types D:\Projects\reproduction\new-semi
> payload generate:types

Error resolving path: [Error: ENOENT: no such file or directory, lstat 'D:\Projects\reproduction\new-semi\node_modules\D:\Projects\reproduction\new-semi\node_modules\.pnpm\next@15.0.0-rc.0_babel-plugin-react-compiler@0.0.0-experimental-938cd9a-20240601_react-dom@19_u5g2i42qnvpr6u6rbf5n5egehi\node_modules\next\server.js'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'D:\\Projects\\reproduction\\new-semi\\node_modules\\D:\\Projects\\reproduction\\new-semi\\node_modules\\.pnpm\\next@15.0.0-rc.0_babel-plugin-react-compiler@0.0.0-experimental-938cd9a-20240601_react-dom@19_u5g2i42qnvpr6u6rbf5n5egehi\\node_modules\\next\\server.js'
}

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:406:5)
    at validateString (node:internal/validators:162:11)
    at pathToFileURL (node:url:1024:3)
    at resolve (file:///D:/Projects/reproduction/new-semi/node_modules/.pnpm/payload@3.0.0-beta.45_@swc+core@1.5.29_@swc+helpers@0.5.11__@swc+types@0.1.8_graphql@16.8.2_typescript@5.4.5/node_modules/payload/dist/bin/loader/index.js:79:18)
    at async nextResolve (node:internal/modules/esm/hooks:833:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:278:24)
    at async handleMessage (node:internal/modules/esm/worker:168:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.9.0
 ELIFECYCLE  Command failed with exit code 1.
```

My system specs: 
![image](https://github.com/payloadcms/payload/assets/76409016/1445c956-8a13-4d99-9569-5cc8367b45e3)

I hope the reproduction repo is correct and will be helpful. Thank you again for your hard work!

### Reproduction Steps

- Stripped down my original project
- Did clean install
- Issue is persistent

### Adapters and Plugins

db-mongodb

**Comment by AlessioGr** [comment]
Thank you! This has been fixed in https://github.com/payloadcms/payload/pull/6804 and will be available in the next beta release (today) :)

Also, make sure to remove that require statement you have. This will not work anymore, require is not a thing in esm. You can use await import's instead
