### ISSUE TITLE
UseField() with custom select field not functioning inside of an array field

### ISSUE THREAD

**Issue by mikecebul** [payloadcms/payload#6793]
### Link to reproduction

https://github.com/mikecebul/payload/tree/custom-select

### Payload Version

3.0.0-beta.47

### Node Version

20.11.1

### Next.js Version

15.0.0-rc.0

### Describe the Bug

I created a list of services I can easily reorder. Doing so looks best inside an array field. I created a custom select field so I can select Icons for each service. This custom IconSelect field works great outside of an array. But inside of an array, any one of the custom select fields update the state among all the other rows of services. And the state isn't saved to the db and is lost with a refresh.

I also get a type error on the onChange method on the `<SelectInput />` making me unsure if I'm calling it correctly. I tried a lot of different ways but `onChange={(e) => setValue(e.value)}` seems like the best way.
_Type Error: Property 'value' does not exist on type 'string'. Did you mean 'valueOf'?_

Sorry in advance if I missed something simple. 

### Reproduction Steps

I followed the new instructions on how to create a reproduction by Jarrod Flesch. In the repo, under the _community folder, I added two globals. The single Service should be working fine. I am just showing a `<p>` to represent the icon. The List of Services will show all the issues I mentioned above. 

### Adapters and Plugins

db-mongo

**Comment by mikecebul** [comment]
As I was looking for a work around I found I can put my services in a collection, then in a global, create an array with a relationship field. This actually works better as I can control what type of services to be available in the global array. But, I can't figure out how to control the RowLabel component. I can use useRowLabel() and get the data.id of the relationship, but that useRowLabel can only be used in a client component. It would be nice to be able to use the payload.findById() somewhere after getting the id from useRowLabel().

**Comment by malewis5** [comment]
Hey @mikecebul could you share how you set this up? I ran into the same issue when setting up a custom select inside of an array field. I think this would be great to document. Thanks!

**Comment by mikecebul** [comment]
Hey @malewis5, I worked completely around it. I was basically trying to make a collection inside of a global, so I moved it into its own collection instead of an array. I settled with using the built in chip UI for now. I'm too lazy to create my own. There also is a nice plugin to reorder collections, but I prefer not to use plugins while there are breaking changes in V3 every 3 days.
