### ISSUE TITLE
Payload Settings Language No other language found

### ISSUE THREAD

**Issue by sao-coding** [payloadcms/payload#6794]
### Payload Version

3.0.0-beta.47

### Node Version

v20.11.1

### Next.js Version

15.0.0-rc.0

### Describe the Bug

No other languages ​​shown

```ts
export default buildConfig({
  admin: {
    user: Users.slug
  },
  collections: [Users, Media],
  editor: lexicalEditor(),
  secret: process.env.PAYLOAD_SECRET || "",
  typescript: {
    outputFile: path.resolve(dirname, "payload-types.ts")
  },
  db: mongooseAdapter({
    url: process.env.DATABASE_URI || ""
  }),
  sharp,
  localization: {
    locales: ["en", "zh-TW"],
    defaultLocale: "en",
    fallback: true
  },
  // 繁體中文
  i18n: {
    fallbackLanguage: "zh-TW"
  },
  plugins: [
    // storage-adapter-placeholder
  ]
})
```

https://github.com/payloadcms/payload/assets/58339015/5beab146-e1fb-45bc-aa2c-bbdc919f14db

There is also an error here
![image](https://github.com/payloadcms/payload/assets/58339015/33852849-f21c-45fe-90a0-fe58610526be)
![image](https://github.com/payloadcms/payload/assets/58339015/97db7e55-da09-487c-8a11-6d3f98527295)
In some places, the type
zh,zh-Hant
zh,zh-TW
zh-CN,zh-TW

### Reproduction Steps

Enter http://localhost:3000/admin/account

**Comment by sao-coding** [comment]
There is also an error here
![image](https://github.com/payloadcms/payload/assets/58339015/33852849-f21c-45fe-90a0-fe58610526be)
![image](https://github.com/payloadcms/payload/assets/58339015/97db7e55-da09-487c-8a11-6d3f98527295)
In some places, the type
zh,zh-Hant
zh,zh-TW
zh-CN,zh-TW

**Comment by JarrodMFlesch** [comment]
Hey @sao-coding you should actually not be able to clear the language selection in the account view. I have [a PR](https://github.com/payloadcms/payload/pull/6803) out that will fix this.

As for adding more languages you will need to import them from `payload/i18n` like so:

```ts
import { de } from 'payload/i18n/de'
import { en } from 'payload/i18n/en'
import { es } from 'payload/i18n/es'
```

and then define them in the config like so:
```ts
i18n: {
  supportedLanguages: {
    de,
    en,
    es,
  },
}
```

See example in our test suite: https://github.com/payloadcms/payload/blob/e7159c033e5b80dcbdc3f3f2f56b7b5e30d8dc2b/test/buildConfigWithDefaults.ts#L172-L177
