### ISSUE TITLE
Hydration error on dates

### ISSUE THREAD

**Issue by heggemsnes** [payloadcms/payload#6796]
### Payload Version

beta

### Node Version

18

### Next.js Version

15.0.0-rc.0

### Describe the Bug

On i.e. this URL: http://localhost:3000/admin/collections/users?limit=10

Causes an hydration error

![CleanShot 2024-06-16 at 23 01 52@2x](https://github.com/payloadcms/payload/assets/36757859/850b9f35-3146-4252-956a-3656a6ada78f)

### Reproduction Steps

Create fresh payload project with beta

**Comment by paulpopus** [comment]
I've not been able to reproduce this on the latest beta version and a supported version of node.

I'll gladly reopen this issue if there's a reproduction.

**Comment by paulpopus** [comment]
Yeah I can see it now, makes sense @jancbeck

**Comment by paulpopus** [comment]
Will be fixed in the next beta release
