### ISSUE TITLE
PaginatedDocs<TypeWithID & Record<string, unknown>>

### ISSUE THREAD

**Issue by szpolny** [payloadcms/payload#6799]
### Payload Version

3.0.0-beta.47

### Node Version

v22.3.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

```typescript
// app/(app)/page.tsx

...
import { getPayload } from 'payload';
import configPromise from '@payload-config';
import { type News } from '~~/payload-types';

const getArticles = async () => {
  const payload = await getPayload({
    config: configPromise,
  });

  const newsCollection = await payload.find<'news'>({
    collection: 'news',
    sort: '-createdAt',
    pagination: false,
    where: {
      _status: {
        equals: 'published',
      },
    },
  });


  return newsCollection;
};

...
```

In this code im quering 'news' collection from local api. Property docs, inside response object should be Type from generated:types but it is not.

### Adapters and Plugins

db-postgres, storage-uploadthing, richtext-lexical

**Comment by szpolny** [comment]
Ok, it turns out that this is problem with vscode. I opened project in webstorm and it returns correct type.

**Comment by ydemetriades** [comment]
I am experiencing the same issue (VS Code).

Tried it on beta.40 and beta.53

**Comment by RyanScarbrough** [comment]
Same issue, woke up today and suddenly had it.

Payload version 2.22.0
VS Code version 1.91.1

```
const { docs: orders } = await payload.find({
     collection: "orders",
     where: {
          id: {
               equals: orderId,
          },
     },
});
```

orders is now of type: (TypeWithID & Record<string, unknown>)[]

**Comment by RyanScarbrough** [comment]
I believe this is due to a Duplicate identifier 'GeneratedTypes' in payload-types.ts

Issues:
https://github.com/payloadcms/payload/issues/6958
https://github.com/payloadcms/payload/issues/6896

This appears to be a VS Code problem, as WebStorm doesn't have this problem.

**Comment by AlessioGr** [comment]
> I believe this is due to a Duplicate identifier 'GeneratedTypes' in payload-types.ts
> 
> Issues: #6958 #6896
> 
> This appears to be a VS Code problem, as WebStorm doesn't have this problem.
> 
> Using TypeScript version 5.4.5 did not fix the issue for me.

VC Code by default often uses an incorrect typescript version. You will have to set it to the workspace typescript version (5.4.5): https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript

**Comment by RyanScarbrough** [comment]
> > I believe this is due to a Duplicate identifier 'GeneratedTypes' in payload-types.ts
> > Issues: #6958 #6896
> > This appears to be a VS Code problem, as WebStorm doesn't have this problem.
> > Using TypeScript version 5.4.5 did not fix the issue for me.
> 
> VC Code by default often uses an incorrect typescript version. You will have to set it to the workspace typescript version (5.4.5): https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-the-workspace-version-of-typescript

Yup this fixed the issue for me, thank you! For whatever reason VS Code decided to switch to an incompatible version of TypeScript. Switching back to the workspace version fixed it just as you said.

![ts-fix](https://github.com/user-attachments/assets/62abdd7c-c62a-47f8-ba47-09e4bd30bd3a)

**Comment by AlessioGr** [comment]
> Same issue and yet no solutions , payload@2.25.0 & typescript@5.5.4

Payload v2 does not and will never support TypeScript 5.5+. Please switch to TypeScript `5.4.5`

**Comment by toximate** [comment]
> > Same issue and yet no solutions , payload@2.25.0 & typescript@5.5.4
> 
> Payload v2 does not and will never support TypeScript 5.5+. Please switch to TypeScript `5.4.5`

Thank you
