### ISSUE TITLE
Custom textarea field components can't be saved within a block

### ISSUE THREAD

**Issue by genox** [payloadcms/payload#6801]
### Link to reproduction

https://github.com/netzwerk-schweizer-paerke/ims-tool

### Payload Version

beta.47

### Node Version

20.12

### Next.js Version

15.rc0

### Describe the Bug

I have a schema that defines blocks with custom textarea components. Meaning, using textarea as schema type but custom editing components.

When I use these custom components in the top-level of the schema information is being saved, e.g. copying a field, `first` or `second` of the block definition to the schema containing the blocks array. As soon as they are within a block, nothing is being saved, also no error messages to note.

The data is not saved to the db.

See the linked repo, everything should be included.

<img width="1363" alt="Screenshot 2024-06-17 at 13 01 49" src="https://github.com/payloadcms/payload/assets/5611407/9b797631-f95a-4305-a3ec-77b29ef69169">

edit: When using the same kind of structure within an array field, I get the same result. the content of the custom fields are not persisted on save.

### Reproduction Steps

prepping:

1. checkout the repo
2. `docker compose -f docker-compose.dev.yml up` to start postgres
3. `yarn run dev` to start nextjs/payload

once logged in:

1. create a new "process"
4. add a block (there's only one to choose from)
5. fill in some random text
6. save
7. reload page
8. notice empty textareas

**Comment by paulpopus** [comment]
The `path` you get from `props` appears to be incorrect, I will look into that to make sure we're passing the right path but to fix your particular issue you should use the `path` from `useFieldProps` as it's the real path for updating data


This worked for me when testing with your components
```ts
import { useFieldProps } from '@payloadcms/ui/forms/FieldPropsProvider';
// ...
const { path } = useFieldProps();
const { value, setValue } = useField<string>({ path });
```

**Comment by genox** [comment]
@paulpopus Thank you, this works. I was using the original blueprint for custom fields which is using props to get the path value.
