### ISSUE TITLE
Issues with crop dimensions

### ISSUE THREAD

**Issue by denishpateltheapplabb** [payloadcms/payload#6802]
### Describe the Bug

When we are going to save the updated image, it gives an error and not uploading.

Please have a look in below screencast
https://app.screencast.com/TeENLFKaL51SV?conversation=bo0AWOHpVgOcSqG4b4SLtu

Query string params:
depth: 0
fallback-locale: null
uploadEdits%5Bcrop%5D%5Bunit%5D: %25
uploadEdits%5Bcrop%5D%5Bx%5D: 0
uploadEdits%5Bcrop%5D%5By%5D: 0
uploadEdits%5Bcrop%5D%5Bwidth%5D: 100
uploadEdits%5Bcrop%5D%5Bheight%5D: 100
uploadEdits%5BfocalPoint%5D%5Bx%5D: 50
uploadEdits%5BfocalPoint%5D%5By%5D: 50

Form Data:
{"alt":"word1234567","url":"[https://helen-dev.payloadcms.app/media/wordthump1.jpg","width":1280,"height":720,"focalX":50,"focalY":50,"filename":"wordthump1.jpg","mimeType":"image/jpeg","filesize":101720,"updatedAt":"2024-06-08T13:02:13.019Z","createdAt":"2024-06-08T13:02:13.019Z"}](https://helen-dev.payloadcms.app/media/wordthump1.jpg%22,%22width%22:1280,%22height%22:720,%22focalX%22:50,%22focalY%22:50,%22filename%22:%22wordthump1.jpg%22,%22mimeType%22:%22image/jpeg%22,%22filesize%22:101720,%22updatedAt%22:%222024-06-08T13:02:13.019Z%22,%22createdAt%22:%222024-06-08T13:02:13.019Z%22%7D)

Note: Image uploading correctly in case of ADD action. It does not in case of EDIT action

--------------------------------------
Please have a look in below files which we are using for upload media image

**// \src\payload\globals\Footer.ts**

```ts
import type { GlobalConfig } from "payload/types"
import { validateLink } from "../utils"

export const Footer: GlobalConfig = {
  slug: "footer",
  access: {
    read: () => true,
  },
  fields: [
    {
      name: "socialLinks",
      type: "array",
      maxRows: 50,
      fields: [
        {
          type: "row",
          fields: [
            {
              name: "name",
              type: "text",
            },
            {
              name: "icon",
              type: "upload",
              relationTo: "media",
              required: true,
            },
          ],
        },
      ],
    },
  ],
}
```

**// \src\payload\collections\Media.ts**

```ts
import { slateEditor } from "@payloadcms/richtext-slate"
import type { CollectionConfig } from "payload/types"
import { ValidationError } from "payload/errors"

export const Media: CollectionConfig = {
  slug: "media",
  upload: {
    disableLocalStorage: true,
  },
  access: {
    read: () => true,
  },
  hooks: {
    beforeValidate: [
      async ({ data, req, operation }) => {
        if (operation === "create" || operation === "update") {
          if (req.files && req.files.file) {
            const { name: originalname } = req.files.file
            if (/\s/.test(originalname)) {
              const errorMsg = "Media name should not contain spaces"
              throw new ValidationError([
                {
                  field: `Media Error: ${errorMsg}`,
                  message: errorMsg,
                },
              ])
            }
          }
        }
        return data
      },
    ],
  },
  fields: [
    {
      name: "alt",
      type: "text",
      required: true,
    },
    {
      name: "caption",
      type: "richText",
      editor: slateEditor({
        admin: {
          elements: ["link"],
        },
      }),
    },
  ],
}
```

### To Reproduce

https://app.screencast.com/TeENLFKaL51SV?conversation=bo0AWOHpVgOcSqG4b4SLtu

### Payload Version

2.19.3

**Comment by JarrodMFlesch** [comment]
@denishpateltheapplabb Can you try recreating this issue on v2.21.0

**Comment by denishpateltheapplabb** [comment]
@JarrodMFlesch Appreciating your help. 

Those errors are resolved **but there are many issues with crop feature. 
I am trying to crop image size 1280X720 to 1200X700, but it is not working correctly.** 

please check in this screencast 
https://app.screencast.com/l9rRMEkR0zrRy?conversation=8dKGxebJZXAqRBAU2wgIHt

**Comment by JarrodMFlesch** [comment]
@denishpateltheapplabb I opened a new issue with your discoveries. https://github.com/payloadcms/payload/issues/6824
