### ISSUE TITLE
Uploads report UI success when failure occurs

### ISSUE THREAD

**Issue by aus** [payloadcms/payload#6812]
### Payload Version

3.0.0-beta.47

### Node Version

v20.12.2

### Next.js Version

15.0.0-rc.0

### Describe the Bug

When experiencing the behavior in #6811, the UI reports upload success although the upload failed.

### Reproduction Steps

1. Reproduce steps in #6811 
2. See the UI success message, but see the S3 logs report failure.

### Adapters and Plugins

@payloadcms/storage-s3

**Comment by PatrikKozak** [comment]
Hey @aus - going to close this issue as it's a duplicate of this discussion [here](https://github.com/payloadcms/payload/discussions/7655).
