### ISSUE TITLE
Nav links in Custom View using DefaultTemplate mismatch after page refresh

### ISSUE THREAD

**Issue by tomashco** [payloadcms/payload#6823]
### Payload Version

3.0.0-beta.50

### Node Version

v20.10.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

I can correctly import my Custom View component wrapped inside DefaultTemplate, but the Navbar is not populated if you link directly to the Custom View page.

This is what I found after digging a bit:
The navigation context lives in the client and for what I understood there is no way to get it from server side.
Thus if you do the navigation adding your link to the custom view through the afterNavLinks array of components, there will not be a full refresh of the page, thus the navigation context will be preserved and you will be able to continue to see the nav links.

On the other hand, hitting directly the custom-view route you will not have the navigation, thus you will be able to see only the afterNavLinks components, but not all the other links.
The same happens if you navigate to the Custom View using the afterNavLinks and then you refresh the page, as described in the Reproduction Steps.

### Reproduction Steps

in payload repo run ```pnpm dev admin```
1. go to default template in the left navbar
2. refresh the page
3. all the nav items are lost, except the custom ones

before refresh:
![Screenshot 2024-06-18 at 09 50 36](https://github.com/payloadcms/payload/assets/8522430/f713e973-99d1-4ffe-9cd7-219ba9fa721f)

after refresh:
![Screenshot 2024-06-18 at 09 50 46](https://github.com/payloadcms/payload/assets/8522430/7aaa575d-1301-49a5-9aee-609a36b10148)

**Comment by benjosua** [comment]
I have exactly the same issue.

**Comment by elliott-w** [comment]
Oops realised this issue is the same as https://github.com/payloadcms/payload/issues/6823

**Comment by JarrodMFlesch** [comment]
Fixed in https://github.com/payloadcms/payload/pull/7545

Will be available after next beta release
