### ISSUE TITLE
Date fields causing "Dynamic require of react is not supported"

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#6828]
### Payload Version

beta.50

### Node Version

18

### Next.js Version

15

### Describe the Bug

Adding a date field and loading the collection in the admin causes the following error:

**Note: this does not happen in the monorepo dev suite**

<img width="993" alt="CleanShot 2024-06-18 at 09 35 35" src="https://github.com/payloadcms/payload/assets/65888/78f02c19-bcef-48ce-9bd7-59ee7b42c352">

### Reproduction Steps

- Add collection with date field
- Attempt to create new in admin

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/6833
