### ISSUE TITLE
SEO plugin broken in v3 beta > 48

### ISSUE THREAD

**Issue by andershermansen** [payloadcms/payload#6850]
### Link to reproduction

https://github.com/andershermansen/payload-3.0-issues/tree/seo-issue

### Payload Version

3.0.0-beta.52

### Node Version

v22.2.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

SEO plugin has been working fine up until beta 48. After that it shows error:
`TypeError: Cannot read properties of undefined (reading 'replace')`
when entering the SEO tab.

<img width="982" alt="Skjermbilde 2024-06-18 kl  20 20 58" src="https://github.com/payloadcms/payload/assets/2082176/c5ec6187-a1a2-4b6d-925e-057d3c3b422a">

### Reproduction Steps

1. Install SEO plugin
2. Go to SEO page in admin panel
3. See the error message

See minimal reproduction repo: https://github.com/andershermansen/payload-3.0-issues/tree/seo-issue
Diff against demo project: https://github.com/payloadcms/payload-3.0-demo/compare/main...andershermansen:payload-3.0-issues:seo-issue

### Adapters and Plugins

plugin-seo

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/6854
