### ISSUE TITLE
unable to use @payloadcms/plugin-cloud-storage after upgrade to payload@3.0.0-beta.52

### ISSUE THREAD

**Issue by jomapps** [payloadcms/payload#6863]
### Payload Version

payload@3.0.0-beta.52

### Node Version

21.6.2

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Internal error: Error: Mismatching payload dependency versions found: payload@3.0.0-beta.52, @payloadcms/plugin-cloud-storage@3.0.0-beta.29. All payload and @payloadcms/* packages must have the same version.

### Reproduction Steps

payload beta.45 was working fine. after upgrade to beta.52 I am unable to work the plugin.

**Comment by jomapps** [comment]
hmm might be connected to something else. Doing more research

**Comment by jomapps** [comment]
Just a reconfirmation. I rolled back to beta.45 and it all works. upgrading to bata.52 I had issue as reported.

**Comment by AlessioGr** [comment]
We do not allow the use of mismatching dependency versions. Can you upgrade @payloadcms/plugin-cloud-storage to beta.52, as well as any other payload dependencies?

**Comment by jomapps** [comment]
I updated all to same beta and it worked. It seems to be a new requirement. Thanks
