### ISSUE TITLE
Select field does not show options when state is updated

### ISSUE THREAD

**Issue by andershermansen** [payloadcms/payload#6869]
### Link to reproduction

https://github.com/andershermansen/payload-3.0-issues/tree/select-issue

### Payload Version

3.0.0-beta.53

### Node Version

v22.2.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Found this regression after updating from beta48 to beta53 in a project.

Using a Select field where data is loaded async with a useEffect. The select field does not update with the values in beta53 project. Same code works fine with beta48.

Working version with beta48: https://github.com/payloadcms/payload-3.0-demo/commit/6a73b7797213e021ed518215e0b11ae55858c359
Changes to update to beta53 (non-working version): https://github.com/payloadcms/payload-3.0-demo/commit/c32c24a87a7eed82fa558a9bf0b8863c2e55f436

Comparison against demo project: https://github.com/payloadcms/payload-3.0-demo/compare/main...andershermansen:payload-3.0-issues:select-issue

Note that console.log which outputs the options after updating the state, shows correct values in the browser in both working and non-working version.

### Reproduction Steps

1. Add new field to a collection
2. Use a customer Select component to render a select field
3. Load the values which can be selected with a useEffect

Expected: Select component updated with the values after state updated

Actual: Select component options is empty

**Comment by JarrodMFlesch** [comment]
@andershermansen this will be fixed in the next beta release!

[Related PR](https://github.com/payloadcms/payload/pull/6878)
