### ISSUE TITLE
Live preview in SSR mode keeps jumping on top

### ISSUE THREAD

**Issue by galcsikgyozo** [payloadcms/payload#6870]
### Payload Version

3.0.0-beta.53

### Node Version

20.9.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

I'm using Live Preview in "SSR" mode, following the instructions from [here](https://github.com/payloadcms/payload/pull/6239).

If specify the URL structure – I need it for localization –, in the `payload-config.ts`, then the refreshed iframe keeps jumping on the top of the page.

When only a string is given as an URL, this problem does not occur.

https://github.com/payloadcms/payload/assets/60744669/22c0d9cf-03cb-402d-8bc1-5b3e6b84125d

### Reproduction Steps

Problem does not occur:
```
export default buildConfig({
  admin: {
    livePreview: {
       url: process.env.NEXT_PUBLIC_PAYLOAD_URL || '',
[...]
```

Problem does occurs:
```
export default buildConfig({
  admin: {
    livePreview: {
      url: ({ data, locale }) => `${process.env.NEXT_PUBLIC_PAYLOAD_URL || ''}/${locale.code}/${data.slug}`,
[...]
```

### Adapters and Plugins

@payloadcms/live-preview, @payloadcms/live-preview-react

**Comment by JarrodMFlesch** [comment]
@galcsikgyozo does this happen locally or deployed or both?

**Comment by galcsikgyozo** [comment]
Actually, never mind @JarrodMFlesch 

I tried reproducing this for hours, by starting from scratch and rebuilding the whole project package by package, component by component, and then everything worked a normal. Then I went back to my original project, and everything worked normal there as well.

If it appears again ever, I'll post an issue about it one more time.
