### ISSUE TITLE
Missing Custom Field Creation in PayloadCMS 3.0 Beta

### ISSUE THREAD

**Issue by DaDoRiNZaNyA** [payloadcms/payload#6876]
### Payload Version

3.0.0-beta.52

### Node Version

v21.7.1.

### Next.js Version

14.2.1

### Describe the Bug

In PayloadCMS 3.0, the ability to create custom form fields is absent. In previous versions, components and hooks for creating custom components were available in the admin/components/form folder. However, after updating to the new version 3.0 beta.52, these features are no longer available.

![image](https://github.com/payloadcms/payload/assets/123072513/2c237a7d-adc3-4ad3-8466-54db5f9fa3d3)

![image](https://github.com/payloadcms/payload/assets/123072513/7c3562a5-f229-47ad-8808-6011ca26c9fe)

### Reproduction Steps

Try creating a custom field in PayloadCMS 3.0.

### Adapters and Plugins

db-mongodb

**Comment by JarrodMFlesch** [comment]
@DaDoRiNZaNyA how are you importing things in your custom component? A code snippet will help.

**Comment by DaDoRiNZaNyA** [comment]
In the old version, I did it like in this examples, but in the new version, I can't find these hooks like useField.
https://github.com/payloadcms/custom-field-guide/blob/master/src/color-picker/InputField.tsx
https://payloadcms.com/blog/how-to-create-a-custom-select-field-in-payload-a-step-by-step-guide

**Comment by JarrodMFlesch** [comment]
You now need to import those from `@payloadcms/ui`

```ts
import { useField } from '@payloadcms/ui'
```

**Comment by DaDoRiNZaNyA** [comment]
![image](https://github.com/payloadcms/payload/assets/123072513/4bf92227-9601-48c9-96d2-8525a2f0cc1b)

**Comment by JarrodMFlesch** [comment]
Oh I did not realize what version you were on. Just update `payload` and all `@payloadcms` packages to the latest, `3.0.0-beta.53`

**Comment by DaDoRiNZaNyA** [comment]
where can I find information about the latest version, here https://github.com/payloadcms/payload-3.0-demo the latest version is 52?

**Comment by JarrodMFlesch** [comment]
You can always find them in the [releases tab](https://github.com/payloadcms/payload/releases). But you need to look for the pre-release tag, not the `draft` tag.

So the one you are looking for is [here](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.53).

**Comment by DaDoRiNZaNyA** [comment]
Thanks a lot, i try this tomorrow

**Comment by DaDoRiNZaNyA** [comment]
@JarrodMFlesch 
Hi, I updated to the latest version 53, but I still have exactly the same problem
![image](https://github.com/payloadcms/payload/assets/123072513/e831f30c-09ad-40f7-82ac-662a876db716)

**Comment by DaDoRiNZaNyA** [comment]
`import { useField } from "@payloadcms/ui";
import { Field } from "payload";
import * as React from "react";

const CustomSelectComponent: React.FC<{ path: string }> = ({ path }) => {
  const { value, setValue } = useField<string>({ path });

  return (
    <div>
      <label className="field-label">Custom Select - Countries</label>
    </div>
  );
};

export const CustomSelectField: Field = {
  name: "customSelectField",
  type: "text",
  admin: {
    components: {
      Field: CustomSelectComponent,
    },
  },
};
`

After the update, the useField hook appeared in @payloadcms/ui, but when I try to use it, an error occurs.
![image](https://github.com/payloadcms/payload/assets/123072513/c249ac70-22a5-4434-b39e-3381936cc6ec)
I tried logging it to the console and received {} as a response.
![image](https://github.com/payloadcms/payload/assets/123072513/53ae5a5e-1f24-4445-8fbf-a6e8f89323cc)

**Comment by JarrodMFlesch** [comment]
@DaDoRiNZaNyA Id be happy to look at your repo if you can link it!

**Comment by DaDoRiNZaNyA** [comment]
@JarrodMFlesch I cannot make the repository public, but I can provide the necessary information

**Comment by JarrodMFlesch** [comment]
@DaDoRiNZaNyA you could create a public repository that only contains code to reproduce your error. That is what I would recommend.

**Comment by DaDoRiNZaNyA** [comment]
@JarrodMFlesch 
https://github.com/DaDoRiNZaNyA/payloadcms-test
I downloaded this repository https://github.com/payloadcms/payload-3.0-demo with a Payload 3.0 example, updated it to version 53, added a custom component, and encountered the same error.

**Comment by ydemetriades** [comment]
same here

**Comment by paulpopus** [comment]
In order to use react hooks you need `'use client'` at the very top of your file.

Your imports should also come from the UI package

```ts
import { TextInput } from '@payloadcms/ui'
import { useField, useFieldProps } from '@payloadcms/ui'
```

**Comment by DaDoRiNZaNyA** [comment]
@paulpopus If I use 'use client', I get a different error: 'Cannot access admin.components on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.'
```
'use client';
import { useField } from "@payloadcms/ui";
import { Field } from "payload";
import * as React from "react";

const CustomComponent: React.FC<{ path: string }> = ({ path }) => {
  const { value, setValue } = useField<string>({ path });

  return (
    <div>
      <label className="field-label">Custom Select - Countries</label>
    </div>
  );
};

export const CustomField: Field = {
  name: "customSelectField",
  type: "text",
  admin: {
    components: {
      Field: CustomComponent,
    },
  },
};
```
![image](https://github.com/payloadcms/payload/assets/123072513/db7626c7-1540-44d9-b9c2-6a12e48715bf)

**Comment by DaDoRiNZaNyA** [comment]
Thank you everyone, I needed to move the field config to a separate server file, and then everything worked. Please update the documentation for these changes.

**Comment by JarrodMFlesch** [comment]
@DaDoRiNZaNyA yep we are working through the docs currently. Here is a starting point for migrations. Step 7 talks a bit about how this needs to be structured 👍 

https://github.com/payloadcms/payload/blob/beta/docs/migration-guide/overview.mdx

**Comment by mewtwo0719** [comment]
In my project i had similar issue. When I checked the `node_modules/@payloadcms/ui` the ui was missing. I was using turborepo in that project (and in root node modules, ui is present). My solution was to manually install ui lib: `pnpm add @payloadcms/ui` and then (even tho, autoimport is missing) I could add what I needed with ` import { useDocumentInfo } from '@payloadcms/ui/providers/DocumentInfo'` It could take some time to find the exact location of what you need but the problem can be solved like this.
