### ISSUE TITLE
Can't get VSCode debugging to work

### ISSUE THREAD

**Issue by adamczykjac** [payloadcms/payload#6882]
### Link to reproduction

https://github.com/payloadcms/payload-3.0-demo

### Payload Version

3.0.0-beta.52

### Node Version

20.15.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Out of the box, I can't possibly get VS Code debugging to work, resulting in unbound breakpoints:
<img width="1130" alt="obraz" src="https://github.com/payloadcms/payload/assets/2134248/253a4a1f-a68f-42ab-956c-2f587327a9fb">

With the help of [this comment](https://github.com/vercel/next.js/issues/56702#issuecomment-1913443304), I only managed to prove that there are indeed no project sourcemaps visible in the Debug Diagnostic view (available when in Debugging mode from Command Palette):
<img width="617" alt="obraz" src="https://github.com/payloadcms/payload/assets/2134248/e33df793-7393-4d37-b6e2-c26c0e462686">

Tried almost everything from [this topic](https://github.com/vercel/next.js/issues/56702) - with `sourceMapPathOverrides` in `launch.json`, changing `cwd`. Nothing worked.

### Reproduction Steps

1. Clone Payload 3 [demo repo](https://github.com/payloadcms/payload-3.0-demo)
2. Go into VSCode debugging view
3. Put a breakpoint in `src/app/(app)/page.tsx:7` or in `src/app/my-route/route.ts:13`
4. Run debug session
5. Reach `localhost:3000` or `localhost:3000/my-route`, respectively to point no. 3
6. Observe no breakpoint to kick in

**Comment by JamesCaldon** [comment]
If you're using the default package.json dev script with cross-env, you may need to pass down the NODE_OPTIONS that VSCode would typically inject when a debugging session is started.
e.g.
`"dev": "cross-env NODE_OPTIONS=\"${NODE_OPTIONS} --no-deprecation\" next dev`"

**Comment by adamczykjac** [comment]
it works as a charm! Would you mind if I create a PR to the Payload 3.0 demo repo with that line changed? I'm stunned that people are not experiencing that too. How do y'all debug your apps at all :D ?

**Comment by JamesCaldon** [comment]
yea, go for it :)

**Comment by JarrodMFlesch** [comment]
@adamczykjac any update on this?

**Comment by JarrodMFlesch** [comment]
Fixed in newest demo by https://github.com/payloadcms/payload-3.0-demo/commit/51bd3508db697742ed8f3ed21c22078d64c0edb6
