### ISSUE TITLE
Missing /wrong collection parameter in access control functions

### ISSUE THREAD

**Issue by markusahrweileramcon** [payloadcms/payload#6883]
### Describe the Bug

I have implemented a simple access control via a collection of slugs on the user which he can edit.
Now I have a function which handles the access to all of my collections.

```typescript
export const editor: Access = ({req: {user, collection}}) =>
    user && user.editor && user.editor.indexOf(collection.config.slug) != -1
```

In version 2.10,0, I encountered a situation, where in on one of my collections, the received slug was wrong and was set to a collection, the wanted collection has a field of (releationship).

I've updated to 2.22.0 and now the complete parameter `collection` is missing, when I visit the overview of a collection.

Is this intended now?
I have a workaround to change the function to receive the slug, it's checking, but this required a static variable which contains the slug, which is not so smooth than to have the slug in the request

### To Reproduce

* Install version 2.22.0 and fetch the req.collection.config.slug, when you are on the collection overview page

and
* Install version 2.10.0 and create two collections.
* add the one collection as required relationship with a queried defaultValue

Some of the fields in the mentioned collection use filterOptions, admin.disableBulkEdit, access.read : !!req.user, admin.components.Cell.

This collection also has two custom endpoints, a beforeDuplicate hook, a beforeRead hook and a livePreview.

I'm not calling the access function myself

### Payload Version

2.10.0 / 2.22.0

### Adapters and Plugins

payloadCloud (unused), oAuthPlugin

**Comment by jmikrut** [comment]
Hey @JarrodMFlesch I think this is now resolved on v3 but I would like to verify before closing. Can you take a look?
