### ISSUE TITLE
Doesn't show popup when adding a new document on relationship field with autosave enabled

### ISSUE THREAD

**Issue by tigersoft6084** [payloadcms/payload#6887]
### Describe the Bug

If a collection has relationship field, it shows Select input with `+` button attached in the edit view. When we are to add a new relationship item by clicking `+` button, the expected behavior would be showing popup to create a new document.
But when the related collection is configured with autosave enabled, the popup quickly disappears and the page is navigated to the new document page of the related collection.

### To Reproduce

Define a `category` collection with autosave enabled:
```
    ...
    versions: {
        drafts: {
            autosave: true,
        },
    },
    fields: [
        {
            name: 'title',
            label: 'Title',
            type: 'text',
            required: true,
        },
    ],
    ...
```
And define `category` field in `pages` collection
```
{
    name: 'category',
    label: 'Category',
    type: 'relationship',
    relationTo: 'category',
};
```
In Pages edit view, click `+` button in `Category` field.

### Payload Version

2.19.3

**Comment by JarrodMFlesch** [comment]
@tigersoft6084 the fix for this will be available in the next 2.x release.
