### ISSUE TITLE
db-postgres: `is like` filter condition does case-insensitive text search and the result is equivalent to `contains` filter

### ISSUE THREAD

**Issue by ikenox** [payloadcms/payload#6898]
### Describe the Bug

Both of `is like` and `contains` filter does case-insensitive search by postgres `ILIKE` operator, and the issued SQL and search results are idential.
I guess that `is like` should do case-sensitive search by postgres `LIKE` operator.

### To Reproduce

You can reproduce the problem by `_community` app:

## Filter by `is like` condition

<img width="978" alt="image" src="https://github.com/payloadcms/payload/assets/7638989/a10f5bea-7191-4249-b082-d9bee42cc8a6">

### SQL

```sql
select "posts"."id", "posts"."text", "posts"."title", "posts"."updated_at", "posts"."created_at", "posts__rels"."data" as "_rels" from "posts" left join lateral (select coalesce(json_agg(json_build_array("posts__rels"."order", "posts__rels"."path", "posts__rels"."media_id") order by "posts__rels"."order" asc), '[]'::json) as "data" from (select * from "posts_rels" "posts__rels" where "posts__rels"."parent_id" = "posts"."id" order by "posts__rels"."order" asc) "posts__rels") "posts__rels" on true where "posts"."text" ilike $1 order by "posts"."title" asc limit $2
```

## Filter by `contains` condition

<img width="985" alt="image" src="https://github.com/payloadcms/payload/assets/7638989/37322164-cabf-4ebf-a14a-3e68bbd2fb90">

### SQL

```sql
select "posts"."id", "posts"."text", "posts"."title", "posts"."updated_at", "posts"."created_at", "posts__rels"."data" as "_rels" from "posts" left join lateral (select coalesce(json_agg(json_build_array("posts__rels"."order", "posts__rels"."path", "posts__rels"."media_id") order by "posts__rels"."order" asc), '[]'::json) as "data" from (select * from "posts_rels" "posts__rels" where "posts__rels"."parent_id" = "posts"."id" order by "posts__rels"."order" asc) "posts__rels") "posts__rels" on true where "posts"."text" ilike $1 order by "posts"."title" asc limit $2
```

### Payload Version

2.22.0 (db-postgres: 0.8.5)

**Comment by DanRibbens** [comment]
This was intentionally done. We did this to match the functionality of the MongoDB adapter. We could potentially add an additional operator for case-likeness queries, but this is not planned.
