### ISSUE TITLE
No additional image sizes are generated on image upload while using "imageSizes"

### ISSUE THREAD

**Issue by dmvdven** [payloadcms/payload#6916]
### Payload Version

3.0.0-beta.32

### Node Version

20.13.1

### Next.js Version

14.3.0-canary.37

### Describe the Bug

Hi,

I'm using the code below to enable additional image sizes. Images get uploaded successfully, but no additional image sizes are created on upload.

I do have the `sharp` dependency installed. Am I doing something wrong?

```
import type { CollectionConfig } from "payload/types";

export const Media: CollectionConfig = {
  slug: "media",
  upload: {
    staticDir: "docker/media",
    imageSizes: [
      {
        name: "thumbnail",
        width: 150,
        height: 150,
      },
      {
        name: "medium",
        width: 300,
        height: undefined,
      },
      {
        name: "large",
        width: 1024,
        height: undefined,
      },
      {
        name: "full_size",
        width: undefined,
        height: undefined,
      },
    ],
    adminThumbnail: "thumbnail",
    mimeTypes: ["image/*"],
  },
};
```

### Reproduction Steps

Use the code as shown above.

**Comment by jmikrut** [comment]
@dmvdven did you also pass Sharp to your config? You need to both install it _**and**_ provide it to your Payload config in order for image sizes to be generated. 

See here:
https://github.com/payloadcms/payload-3.0-demo/blob/main/payload.config.ts#L121

**Comment by dmvdven** [comment]
Thanks @jmikrut. Couldn't find this in the docs. It's working now!
