### ISSUE TITLE
[UI] Document deletion modal: Content misalignment

### ISSUE THREAD

**Issue by AF111** [payloadcms/payload#6936]
### Link to reproduction

https://github.com/payloadcms/payload-3.0-demo

### Payload Version

3.0.0-beta.54

### Node Version

20.12.2

### Next.js Version

15.0.0-rc.0

### Describe the Bug

The delete document modal's content is not properly centered in v3 beta. It should be aligned both vertically and horizontally.

![image](https://github.com/payloadcms/payload/assets/30418824/2d7a8593-9509-4a55-9233-19530c2b4f8d)

Possible fix:
Add ``justify-content: center;`` to the modal dialog elements in:
1: https://github.com/payloadcms/payload/blob/beta/packages/ui/src/elements/DeleteDocument/index.scss
2: https://github.com/payloadcms/payload/blob/beta/packages/ui/src/elements/DeleteMany/index.scss

### Reproduction Steps

1. Install Payload v3 beta and configure project name and db: `npx create-payload-app@beta`
2. Start dev server and try to delete any record.
3. A delete confirmation modal should popup similar to the one in the bug description.

**Comment by paulpopus** [comment]
Will be fixed in the next beta release!
