### ISSUE TITLE
Relationship field is of type number | MyType

### ISSUE THREAD

**Issue by sriechersrc** [payloadcms/payload#6937]
### Payload Version

3.0.0-beta.46

### Node Version

v20.10.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

When i try to access a field of type relationship, it is either a number or the actual collection type. I was wondering if the number type is even needed since I always get back the actual object from the collection. 

My Collection has this field in it:

```typescript

export const Tags: CollectionConfig = {
  slug: 'tags',
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      unique: true,
      localized: true,
    },
  ],
}

// somewhere in another collection
export const Events: CollectionConfig = {
  slug: 'events',
{
      name: 'tags',
      type: 'array',
      required: true,
      fields: [
        {
          name: 'tag',
          type: 'relationship',
          relationTo: 'tags',
          required: true,
          index: true,
        },
      ],
}
}
````

When I query the collection the tags field contains tags typed as `number | Tag` even though the actual tag always is an object of this form: 
```typescript
{
  createdAt: "2024-06-26T12:41:40.270Z"
  id: 1
  title: "test"
  updatedAt: "2024-06-26T12:41:40.270Z"
}
```

### Reproduction Steps

1. Create Collection
2. Create another collection with a field of type "relationship" and reference the other collection
3. the relationship field will be typed as number | NameOfYourType

### Adapters and Plugins

db-postgres

**Comment by paulpopus** [comment]
This is intended actually and you need to narrow down the type in your code when dealing with this by checking if it's a string/number or your object.

The reason it's this way is because depending on `depth` when fetching the data or access permissions, you may not receive back the full object and just the ID which can be a string or a number depending on your DB settings.
