### ISSUE TITLE
Payload interface language

### ISSUE THREAD

**Issue by vince93290** [payloadcms/payload#694]
Hi,

is it possible to modify the language of  payload interface and put it in French for example?

or edit the interface text (buttons, input form, ect...)?

Thanks

**Comment by denolfe** [comment]
Hey @vince93290 , great suggestion! This is not possible currently, but the good news is that we already have this on our roadmap. Feel free to head over to the dedicated discussion to add an upvote/comment: https://github.com/payloadcms/payload/discussions/300

**Comment by vince93290** [comment]
Good news I'm really looking forward to this function should implement.  payload is really the tool I needed.

**Comment by dandelior** [comment]
Why this doesn't work on production

**Comment by jmikrut** [comment]
Hey @vince-x-studio — this has now been released actually!

You can change languages by going to your Account (bottom left user icon) in the dashboard. From there, scroll to the bottom and choose your language that you'd like to use.

Should be all set!

**Comment by vince-x-studio** [comment]
Very great news thanks!!!
