### ISSUE TITLE
Image metadata stripped from image when using upload.imageSizes

### ISSUE THREAD

**Issue by hjbugajski** [payloadcms/payload#6951]
### Link to reproduction

https://github.com/hjbugajski/payload-3.0-stripped-metadata

### Payload Version

3.0.0-beta.55

### Node Version

20.14.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

When `imageSizes` is set in the collection `upload` config, all metadata is stripped from all image sizes, including the original image. When `imageSizes` is removed from the collection `upload` config, the metadata is preserved in the image since no transformations are done.

I believe this is due to `sharp` stripping all metadata by default, and when uploading multiple image sizes, the "original" image is recreated with sharp with no formatting or transformations applied, thus stripping the metadata.

Possible solutions may be to use [`keepMetadata`](https://sharp.pixelplumbing.com/api-output#keepmetadata) or [`withMetadata`](https://sharp.pixelplumbing.com/api-output#withmetadata) to preserve the metadata for images, or upload the original image without using `sharp`.

### Steps

1. Clone the [reproduction repository](https://github.com/hjbugajski/payload-3.0-stripped-metadata).
2. Start a MongoDB container and run the Payload application.
3. Go to the Media collection and upload a new image (example image provided in repository).
4. Metadata should be displayed after save.
5. Uncomment lines [41–47 in `Media.ts`](https://github.com/hjbugajski/payload-3.0-stripped-metadata/blob/main/src/collections/Media.ts#L41-L47)
6. Create a new upload with the example image.
7. Metadata should not be displayed after save.

### Video

https://github.com/payloadcms/payload/assets/22182454/6b755386-fa34-489f-a6d0-06dc2c28e60c

**Comment by PatrikKozak** [comment]
@hjbugajski thanks for bringing this to our attention! This [PR](https://github.com/payloadcms/payload/pull/7293) will fix this issue.

**Comment by hjbugajski** [comment]
Thank you for getting the issue resolved!
