### ISSUE TITLE
Type collision with generated types

### ISSUE THREAD

**Issue by bajzarpa** [payloadcms/payload#6958]
### Describe the Bug

The `payload-types.ts` exports an interface like this:
```ts
export interface GeneratedTypes extends Config {}
```

but the `node_modules/payload/dist/index.d.ts` also declares a `GeneratedTypes` which collides with the `GeneratedTypes` above. 

Sometimes the ts uses the `payload-types.ts` other times it uses `node_modules/payload/dist/index.d.ts`

And this what cause the `TypeWithID & Record<string, unknown>` errors when using local api.

### To Reproduce

Its random, sometimes one `GeneratedTypes` has been referenced instead of the other 

### Payload Version

2.22.2

**Comment by neslob** [comment]
Getting the same error. 

No idea, where this came from. Sadly I did not throughly committed while testing. 

For me, even `pnpm run dev` broke. 
But, I without turbo, it works.

```
    "start": "next dev",
    "dev": "next dev --turbo",
```

Breaking production builds could be solved by removing/commenting the generate code

```

// declare module 'payload' {
//   export interface GeneratedTypes extends Config {}
// }

```

**Comment by AlessioGr** [comment]
Are you on TypeScript 5.5 or 5.4? If you are on TypeScript 5.5, can you make sure the issue still appears on 5.4? (We do not support TypeScript 5.5 on 2.0)

**Comment by neslob** [comment]
Oh! sorry, I have missed details (added above).

For me, it is happening on 3.0.0-beta.53.
Yes, it happens on TypeScript 5.5. But downgrading, did not solve it. 

I am happy to open a separate issue.

**Comment by bajzarpa** [comment]
> Are you on TypeScript 5.5 or 5.4? If you are on TypeScript 5.5, can you check if this issue still appears on 5.4? (We do not support TypeScript 5.5 on 2.0)

Downgrading TS to 5.4 fized this issue indeed. Thank you Alessio

**Comment by carstenblt** [comment]
> Oh! sorry, I have missed details (added above).
> 
> For me, it is happening on 3.0.0-beta.53. Yes, it happens on TypeScript 5.5. But downgrading, did not solve it.
> 
> I am happy to open a separate issue.

Check if ts is really downgraded. If you use ^5.4.5, pnpm will still install/keep 5.5.

Had the same problem, keeping 5.4.5 worked.

**Comment by paulpopus** [comment]
Closing, we will support ts 5.5 on 3.0 but 2.0 will be compatible with 5.4.5 only.
