### ISSUE TITLE
Disabling auth local strategy causes /api/users/me to no longer work

### ISSUE THREAD

**Issue by riley-pearce-airteam** [payloadcms/payload#6969]
### Payload Version

3.0.0-beta.55

### Node Version

20.15.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

In v2 I created a custom OAuth2.0 flow to generate a `payload-token` cookie. This was the only source of authentication so I would set `disableLocalStrategy: true`, everything worked as expected.

In v3, if I set `disableLocalStrategy: true`, the `/api/users/me` endpoint will return user as `null` when using the OAuth2.0 generated cookie. If I omit `disableLocalStrategy: true`, that same cookie will return as expected from `/api/users/me`.

Please note I'm not using `strategies` in the `auth` object; this wasn't necessary in v2.

### Reproduction Steps

- Set `disableLocalStrategy: true`.
- Generate a `payload-token` cookie using an OAuth2.0 flow and sign it with the payload secret.
  - Using this as an example: https://github.com/WilsonLe/payload-oauth2
- `/api/users/me` will return user as `null`.
- Omit `disableLocalStrategy: true`.
- `/api/users/me` will return the user as expected.

### Adapters and Plugins

@payloadcms/db-postgres, @payloadcms/next, @payloadcms/richtext-lexical

**Comment by jmikrut** [comment]
Hey @riley-pearce-airteam — can you open this issue on the repository of the plugin that you're using? It does look like the plugin supports v3 but we're not the authors of it so the Payload team can't comment on how it works or why it would be functioning differently in v3 vs. v2. 

Taking a quick look though, the `/api/users/me` endpoint just returns the `req.user`, so for some reason, it seems to me like the plugin's `authenticate` method is not properly returning a `user` any longer. Might not be a problem with the `/me` endpoint itself, but rather, the `authenticate` method of the auth strategy.
