### ISSUE TITLE
Image resize bug - filename conflicts when two `imageSizes` configs are of the same dimensions

### ISSUE THREAD

**Issue by jeremy8883** [payloadcms/payload#6971]
### Describe the Bug

For the image upload resize feature, there is a filename conflict bug when two `imageSizes` configs are of the same dimensions.

### Use case:
When saving jpg images, we want to have the lowest possible image quality, which isn't noticeable to the end user, and that quality value can be lower on 2x screens. For 1x pixel densities, we generally want the compression quality at around 85%. But for 2x screens, we can get away with reducing the quality to around 70%, therefore saving on network bandwidth.

Following this principle, there ends up being a filename conflict between the 1x and 2x screen density variants. See the "To reproduce" section for a detailed example.

### Possible fixes
* Provide an optional function config like `getImageFilename`, or a `beforeUpload` hook, to allow us to use a custom filename instead. I've tried using the `beforeOperation` hook, but I couldn't figure it out from there.
* Use `-${name}` as the filename suffix, instead of `-${width}x${height}`.

Thanks for all the great work! I'm really liking Payload so far!

### To Reproduce

In a media upload config, include the following:

```
export const Media: CollectionConfig = {
  slug: 'media',
  upload: {
    // ...
    imageSizes: [
        { name: '64dpw@1x', width: 64, formatOptions: { format: 'jpg', options: { quality: 85 } } },
        { name: '128dpw@1x', width: 128, formatOptions: { format: 'jpg', options: { quality: 85 } } },
        { name: '64dpw@2x', width: 64 * 2, formatOptions: { format: 'jpg', options: { quality: 70 } } },
        { name: '128dpw@2x', width: 128 * 2, formatOptions: { format: 'jpg', options: { quality: 70 } } },
    ],
  },
}
```

This will cause the derived `128w@1x` and `64w@2x` filenames to conflict. The stored doc content for `sizes` is:

```
{
  '64w@1x': {
    // ...
  },
  '128w@1x': {
    // ..
    width: 128,
    height: 128,
    filename: 'test-image-resize-128x128.jpg',
  },
  '64w@2x': {
    // ..
    width: 128,
    height: 128,
    filename: 'test-image-resize-128x128.jpg',
  },
  '128w@2x': {
    // ...
  },
}
```

### Payload Version

2.22.2

### Adapters and Plugins

db-mongodb, redirects, payload-cloud, search, sentry

**Comment by paulpopus** [comment]
Hey @jeremy8883 we've solved this by adding a new function on the sizes config that allows you to fully customise it with some parameters. This will be available in the next v2 release but here's the PR for it https://github.com/payloadcms/payload/pull/7637

Here's the docs for how it will work https://payloadcms.com/docs/upload/overview#custom-file-name-per-size
