### ISSUE TITLE
Uploads with "%" in filename fail to show (s3Adapter)

### ISSUE THREAD

**Issue by carstenblt** [payloadcms/payload#6985]
### Describe the Bug

When uploading a file like "test%test.jpg", it can't be viewed, because the URL is not encoded.

This could be solved by using `encodeURIComponent` on the filename.

### To Reproduce

- Upload file that contains a %-character in the filename
- try to view the file. Both thumbnail and download fail

### Payload Version

2.22.2

### Adapters and Plugins

payload-cloud-storage, s3Adapter

**Comment by rafalnawojczyk** [comment]
I've came across the same issue in my codebase. Already created a PR that resolved this problem on my end.

**Comment by smoothdvd** [comment]
Same as local storage. The filename saved in ascii code.
<img width="223" alt="Screenshot 2024-07-04 at 10 40 41 PM" src="https://github.com/payloadcms/payload/assets/22420/84840cc1-52cb-4c37-9ac8-c994238e173e">
The original filename is in Chinese: 橙柿App文章202406.xlsx

**Comment by smoothdvd** [comment]
> Same as local storage. The filename saved in ascii code. <img alt="Screenshot 2024-07-04 at 10 40 41 PM" width="223" src="https://private-user-images.githubusercontent.com/22420/345870499-84840cc1-52cb-4c37-9ac8-c994238e173e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTMwMTksIm5iZiI6MTcyMjE1MjcxOSwicGF0aCI6Ii8yMjQyMC8zNDU4NzA0OTktODQ4NDBjYzEtNTJjYi00YzM3LTlhYzgtYzk5NDIzOGUxNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA3NDUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3OTAzZWNlZTdiYWFkYThkZWZlYTk4MDZmZDgzNGIxYjA0NGViZWYyZmZkZTQ4ZTJlMmUxYTkwYzZkZTIwYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLBBT28gSaTr1QtQ1HG1KCMBc2ESlXcN0Yx-AN-pPUs"> The original filename is in Chinese: 橙柿App文章202406.xlsx

I resolve this issue by setting upload option in payload.config.ts

```
{
    defCharset: 'utf8',
    defParamCharset: 'utf8'
}
```

Explains from here: 
* https://payloadcms.com/docs/upload/overview#payload-wide-upload-options
* https://stackoverflow.com/a/72908480/623260
