### ISSUE TITLE
Missing request property in ListView payload.find calls

### ISSUE THREAD

**Issue by wishrd** [payloadcms/payload#6989]
### Payload Version

3.0.0-beta.56

### Node Version

20.10.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

I'm building a multitenant CMS with PayloadCMS. To restrict the data being shown by an user, I'm checking the request host in the access control functions of the collections.

For ListView component, the host is fake due to the [attachFakeURLProperties method](https://github.com/payloadcms/payload/blob/ef21182eac6aac9bf52c9c0777bea93d8add743d/packages/payload/src/utilities/createLocalReq.ts#L46), so when the access control function is being called for this request, it is always getting `localhost` and I can't check the host properly. Returning `false` in the access control for this use case just breaks the view with an exception about permissions.

I think the request property should be passed from the `iniPageResult` object to both `payload.find` calls but I'm not sure about the side-effects it could have as I'm not an expert on React/Next.js or PayloadCMS core.

https://github.com/payloadcms/payload/blob/ef21182eac6aac9bf52c9c0777bea93d8add743d/packages/next/src/views/List/index.tsx#L103-L115
https://github.com/payloadcms/payload/blob/ef21182eac6aac9bf52c9c0777bea93d8add743d/packages/next/src/views/List/index.tsx#L51-L63

If I add the request property to both calls as described, the view starts working properly, receiving the host and being able to filter the data based on it.

UPDATE:
It is happening also in the Edit view of a collection item. In this case, adding the request object in the calls of the [buildFormState](https://github.com/payloadcms/payload/blob/v3.0.0-beta.53/packages/ui/src/utilities/buildFormState.ts) function, fix the issue for the Edit view.

### Reproduction Steps

1. Configure a host in `/etc/hosts` (or wherever depending on your OS) with a fake domain poniting to 127.0.0.1
2. Create a `read` access control function for a collection:
```
export const readTest: Access = async ({ req }) => {
  const host = req.headers.get('X-Forwarded-Host') || req.host;
  console.info('readTest', host, req.url); // It should print "localhost" for ListView calls
  return true;
}
```
```
export const Tenants: CollectionConfig = {
  slug: 'tenants',
  access: {
    read: readTest,
  },
  ...
```
3. Access with this domain to the admin panel and load the collection list view

**Comment by JarrodMFlesch** [comment]
@wishrd this was fixed in [3.0.0-beta.58](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.58)
