### ISSUE TITLE
Can't assign a relationship to the default User collection

### ISSUE THREAD

**Issue by jmikrut** [payloadcms/payload#7]
## Expected Behavior
Should be able to set the `relationTo` property of a `relationship` field equal to the default user collection.

## Current Behavior
The field will fail validation because `users` is not added to the `validRelationships` properly during collection and global sanitization.  

## Possible Solution
If Payload is relying on the default user collection, `users` should be added to the list of valid relationships.

## Steps to Reproduce
1. Create an empty config that will automatically add the default `User` collection.
1. Create a Posts collection or similar with one `relationship` field pointing to `users`
1. Attempt to start the server (RIP)

**Comment by denolfe** [comment]
Closed with b2d05c781d7751bbede9e37996cbdc0736d07a66
