### ISSUE TITLE
Using svgr webpack with Payload

### ISSUE THREAD

**Issue by pcarillion** [payloadcms/payload#7008]
### Payload Version

v3@beta.56

### Node Version

20

### Next.js Version

15

### Describe the Bug

Use SVGR with webpack as described here 
https://blog.logrocket.com/import-svgs-next-js-apps/#import-svgs-next-js-using-svgr

Running dev or build fails

`./node_modules/.pnpm/@payloadcms+ui@3.0.0-beta.56_monaco-editor@0.38.0_next@15.0.0-rc.0_@babel+core@7.24.7_react-d_6btuzme2v3pjqg2bytl3nrltfa/node_modules/@payloadcms/ui/dist/assets/payload-favicon.svg
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <svg width="260" height="260" viewBox="0 0 260 260" fill="none" xmlns="http://www.w3.org/2000/svg">
|   <style>
|     path {

Import trace for requested module:
./node_modules/.pnpm/@payloadcms+ui@3.0.0-beta.56_monaco-editor@0.38.0_next@15.0.0-rc.0_@babel+core@7.24.7_react-d_6btuzme2v3pjqg2bytl3nrltfa/node_modules/@payloadcms/ui/dist/assets/payload-favicon.svg`

### Reproduction Steps

- install payload beta
- install @svgr/webpack@8.1.0
- modify next config
- build project

### Adapters and Plugins

"@svgr/webpack": "^8.1.0"

**Comment by rilrom** [comment]
Add this whole thing to your next.config.js, this is what resolved it for me.

https://react-svgr.com/docs/next/#usage

**Comment by paulpopus** [comment]
Hey @pcarillion can you confirm if the above fixes this issue for you please? I'll close the issue for now unless there's further problems confirmed
