### ISSUE TITLE
Cannot override default Cell component

### ISSUE THREAD

**Issue by mulfyx** [payloadcms/payload#7013]
### Describe the Bug

It is currently impossible to set a custom Cell component. The documentation at https://payloadcms.com/docs/admin/components#cell-component does not provide clear instructions on how to achieve this.

```
ERROR (payload): There were 1 errors validating your Payload config
ERROR (payload): 1: Collection "reproduce" > "admin.components.Cell" is not allowed
```

### To Reproduce

```ts
import { type CollectionConfig } from "payload/types";

export const Reproduce: CollectionConfig = {
	slug: "reproduce",
	admin: {
		components: {
			Cell: (props) => JSON.stringify(props),
		},
	},
	fields: [],
};
```

### Payload Version

2.23.1

**Comment by paulpopus** [comment]
Hey a Cell component is for fields only and it won't be valid on a collection component.

What are you trying to achieve? If you just want a custom component in your collection fields, then the UI field is best suited for this https://payloadcms.com/docs/fields/ui#example and you'll need to provide a React component

**Comment by mulfyx** [comment]
> Hey a Cell component is for fields only and it won't be valid on a collection component.
> 
> What are you trying to achieve? If you just want a custom component in your collection fields, then the UI field is best suited for this https://payloadcms.com/docs/fields/ui#example and you'll need to provide a React component

I need to modify the behavior to display the number 0 instead of "no {label}".
