### ISSUE TITLE
CLI not working when HMR is reloading frontend

### ISSUE THREAD

**Issue by sriechersrc** [payloadcms/payload#7016]
### Payload Version

3.0.0-beta.46

### Node Version

v20.10.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

When I open the frontend page i.e. http://localhost:3000 and the server is restarting due to manually running `npm run dev` or HMR and there are any schema changes, I cannot interact with the CLI. When I open the admin backend and HMR or `npm run dev` happens, the CLI works as expected.

Same thing happens when I manually reload the browser while HMR is in progress

### Reproduction Steps

1. open htttp://localhost:3000
2. make some schema changes that the CLI asks you questions about
3. Cannot interact with the CLI

### Adapters and Plugins

db-postgres

**Comment by sriechersrc** [comment]
I switched out the database adapter from postgres to mongo db. Now the error is gone

**Comment by denolfe** [comment]
I attempted to recreate this using your steps, but I did not have any issue interacting with the CLI at any point.

This may have to do with which terminal or operating system you're using. I tested successfully with macOS and iTerm2. Can reopen if you can narrow it down.
