### ISSUE TITLE
`REST` api throws `NotFound` if custom `id` contains `/` symbol

### ISSUE THREAD

**Issue by Fitch24** [payloadcms/payload#7021]
### Describe the Bug

When [custom id](https://payloadcms.com/docs/fields/overview#customizable-id) contains `/` symbol all id-specified operations `/api/{collection-slug}/{id}` throws `NotFound` error in REST-api.

### To Reproduce

- Create a collection with [customizable id](https://payloadcms.com/docs/fields/overview#customizable-id) where field `type` is `text`
- Create a new element in that collection with `id` containing `/` symbol. Like `foo/bar`
- Try `Find By ID`, `Update By ID` or `Delete by ID` operation

### Payload Version

2.23.1

### Adapters and Plugins

db-mongodb

**Comment by rafalnawojczyk** [comment]
I'm not sure, but it looks like it can be pretty hard to fix. It's a part of URL, so next API route is catching it as a separate routes and is looking for handlers for foo(it's an ID for API) and bar(it's a separate route inside foo).

It's kind of agains REST API rules to have any ID's for routes with `/` when it is not the last route.

Maybe you could try to rewrite your logic to use underscore or hyphen with a help of a conversion util.

**Comment by Fitch24** [comment]
Thanks for your reply.
I'm not using `/` in id. I just find out it accidentally when create element with `/` in id via admin UI and then got NotFound page. So I created the issue because it's unexpected and undocumented behavior.
I agree, it's hard to fix (and unnecessary). You can close this issue.
And may be, you can add a note to the cusmozible id documentation (about some symbols in id can break some REST-api operations).

**Comment by paulpopus** [comment]
Thanks both! We'll make sure this is documented for v2 and v3
