### ISSUE TITLE
Array field `components.RowLabel` doesn't receive expected arguments

### ISSUE THREAD

**Issue by jancbeck** [payloadcms/payload#7029]
### Payload Version

3.0.0-beta.57

### Node Version

>=20

### Next.js Version

15.0.0-rc.0

## https://payloadcms.com/docs/fields/array#example

> components.RowLabel | Function or React component to be rendered as the label on the array row. Receives ({ data, index, path }) as args
> -- | --

**However, `payload` does not export type `RowLabelArgs` nor does `RowLabel` receive index or path as args.**

### Reproduction Steps

Use the example code mentioned in the array field documentation:

> ```tsx
>      admin: {
>         components: {
>           RowLabel: ({ data, index }: RowLabelArgs) => {
>             return data?.title || `Slide ${String(index).padStart(2, '0')}`
>           },
>         },
>       },
> ```

**Comment by paulpopus** [comment]
Hey actually I double checked the breaking changes, we will need to update those docs there but RowLabel no longer accepts a function in v3 and you should use a custom component instead.

From https://github.com/payloadcms/payload/blob/beta/docs/migration-guide/overview.mdx ctrl f for "admin.components.RowLabel"

```ts
// file: payload.config.ts
import { buildConfig } from 'payload'
import  { ServerRenderedArrayRowLabel } from './components/ServerRenderedArrayRowLabel.tsx'

export default buildConfig({
  // ...
  collections: [
    {
      slug: 'posts',
      fields: [
        {
          name: 'people',
          type: 'array',
          admin: {
            components: {
              RowLabel: ServerRenderedArrayRowLabel
            }
          },
          fields: [
            {
              name: 'name',
              type: 'text',
            }
          ]
        }
      ]
    }
  ]
  // ...
})


// file: components/ServerRenderedArrayRowLabel.tsx
import React from 'react'
import { ClientRowLabel } from './ClientRowLabel.tsx'

export const ServerRenderedArrayRowLabel = () => <ClientArrayRowLabel />


// file: components/ClientArrayRowLabel.tsx
'use client'
import React from 'react'
import { useRowLabel } from '@payloadcms/ui'

export const ClientArrayRowLabel = () => {
  const { data } = useRowLabel()

  return <div>{data?.name || 'No Name'}</div>
}
```
