### ISSUE TITLE
Migrations not returning proper error code to terminal

### ISSUE THREAD

**Issue by tomekwlod** [payloadcms/payload#7031]
### Payload Version

v3 beta 55

### Node Version

20.9.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

I have an issue with the migrations scripts. The command `bun run payload migrate` runs well unless a migration cannot be applied for some reason (it doesn't really matter, but in my case the sample error is: `cannot drop table xxxx because other objects depend on it`). 
As far as I understand, this attempt should return an error code (for example =1) so that the following migrations will not be applied as well. Another reason why this should return an error is to tell the Ci/Cd pipeline (Github Actions for instance) to stop releasing immediately.

It may be that I am doing something wrong or I don't understand the concept, but I have been using migrations methodology in some other languages and they were always returning errors if a migration couldn't be applied.

Obviously, as a workaround, I could wrap my queries with try catch and return process.exit(1) in the catch statement but that's something everyone who runs migrate:create script would need to remember about.

Stack:
MacOS, Docker, Postgres 

Thanks in advance for any help

### Reproduction Steps

- create a new migration using `bun/yarn run payload migrate:create`
- throw an error in the up() function
- apply that migration `bun/yarn run payload migrate`
- run `echo $?`  to see the code that the previous command returned

**Comment by denolfe** [comment]
Thanks for report @tomekwlod. I agree, this should follow normal exit code conventions. Will be looking into it 👍

**Comment by denolfe** [comment]
Fixed on main. v3 PR incoming.
