### ISSUE TITLE
Cannot update image at media

### ISSUE THREAD

**Issue by AdamZajler** [payloadcms/payload#7032]
### Payload Version

3.0

### Node Version

22

### Next.js Version

15rc

### Describe the Bug

When I have already uploaded image, for ex. `image.svg` => hit save => click to edit media to change the file to `image.png` i'm getting error :thinking:

Saving is successful, but there is no minature and no image at `/public/media/`

I'm targeting `staticDir: 'public/media',` to hold images on nextjs

### Reproduction Steps

```ts
import { slateEditor } from '@payloadcms/richtext-slate';
import { CollectionConfig } from 'payload';

export const Media: CollectionConfig = {
  slug: 'media',
  upload: {
    staticDir: 'public/media',
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
      required: true,
    },
    {
      name: 'caption',
      type: 'richText',
      editor: slateEditor({
        admin: {
          elements: ['link'],
        },
      }),
    },
  ],
};

```

**Comment by JarrodMFlesch** [comment]
@PatrikKozak this sounds familiar. Did you resolve this?
