### ISSUE TITLE
Attempted import error : 'Lexical Error Boundary'

### ISSUE THREAD

**Issue by poofy25** [payloadcms/payload#7036]
### Payload Version

3.0.0-beta.55

### Node Version

20.6.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

After i updated from payload V3 version 3.0.0-beta.26 to 3.0.0-beta.55 I ran my application and this error showed up 
![image](https://github.com/payloadcms/payload/assets/117314241/44338738-0315-42fe-8b18-9b4de11275df)

I had to switch from lexicalEditor() to slateEditor({}) to get rid of the error.

### Reproduction Steps

Update a project version from 3.0.0-beta.26 to 3.0.0-beta.55

**Comment by AlessioGr** [comment]
I can't reproduce this, the lexical editor loads up fine on beta.55 for me. Please open up a new issue with a minimal repository which reproduces this.
