### ISSUE TITLE
Retaining the nested fields that are not defined in payload collection

### ISSUE THREAD

**Issue by adarsh279** [payloadcms/payload#7038]
### Describe the Bug

**Issue Summary:**

When we try to update any nested field on Payload UI its overwriting the fields that are not defined on the Payload schema

**Background:**
Our team is working on the migration from existing CMS (KeystoneJS v4) to Payload, as it is not happening in KeystoneJS
when we migrate our application to Payload this issue will impact our data and can cause other impacts on the application that consuming those datas.

### To Reproduce

**Steps to Reproduce:**

Step 1:

Create a collection as below structure

const Sample: CollectionConfig = {
slug: 'sample',
fields: [
{
name: 'name',
type: 'text',
},
{
name: 'address',
type: 'group',
fields: [
{
name: 'field1',
type: 'text',
},
{
name: 'field2',
type: 'text',
},
],
},
],
}

Step 2:

Create a sample data as mentioned below in the collection.
Ex. Sample data in a collection
{
"name": "",
"age": 20,
"address": {
"field1": "YYY",
"field2": "TTTTT",
"field3": "RRRRR"
}
}

Step 3:
On payload UI try to update the field "address.field1" OR "address.field2" and observe the data updated into the collection.

Updating a collection record(Ex. Sample) is overwriting nested fields that present in that db but that are not defined in the payload schema.

**Tried Solution**

We have tried the [flattening](https://urldefense.com/v3/__https:/www.npmjs.com/package/flat__;!!PxNGlQK5RbneE5k!TQs3iwkti3Yg0-4-2mI0Zkzq-oDdyvM2DfITJ7OC3UCBRF8S029zUyERo_TzD8djllYvhauieMI477ihtg$) module to modify the object before update query gets executed.

This way it will not impact any data that we update.

Refer the below code snippet modified on the file [https://github.com/payloadcms/payload/blob/main/packages/db-mongodb/src/updateOne.ts](https://urldefense.com/v3/__https:/github.com/payloadcms/payload/blob/main/packages/db-mongodb/src/updateOne.ts__;!!PxNGlQK5RbneE5k!TQs3iwkti3Yg0-4-2mI0Zkzq-oDdyvM2DfITJ7OC3UCBRF8S029zUyERo_TzD8djllYvhauieMInWqKRmQ$)

try {
// TODO: Remove this
if (options.flatten) {
const flat = require('flat')
data = flat.flatten(data);
}
const flat = require('flat');
data = flat.flatten(data);
result = await Model.findOneAndUpdate(query, data, options);
} catch (error) {
}

Also, ‘Options.flatten’ key comes as parameter that we set in the payload config object like below,

db: mongooseAdapter({
url: process.env.MONGO_URI,
flatten: true
})

We would like to know if this solution which we tried is acceptable and has no impact. Any other solutions using a different approach will be helpful.

Feedbacks are appreciated.

### Payload Version

^2.18.3

### Adapters and Plugins

@payloadcms/db-mongodb @payloadcms/plugin-relationship-object-ids

**Comment by paulpopus** [comment]
Hi @adarsh279 this is pretty much how the admin panel works as it pushed up the entire form state of the collection when editing.

Is there a particular reason the other data can't also exist in the payload schema?

As a worst case scenario you could put all of your external/old data in a JSON field with `admin.hidden` set to true so that you can then store it properly and retrieve it from your payload API.

Let us know if you need further guidance on dealing with this
