### ISSUE TITLE
[v3] Cannot save json field to database

### ISSUE THREAD

**Issue by shuowu** [payloadcms/payload#7052]
### Payload Version

3.0.0-beta.58

### Node Version

v20.15.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

When create a new document with JSON field from admin portal, no data is added to db after clicking save button.

### Reproduction Steps

1. create collection with any json type field in `fields`
```
{
      name: 'file',
      type: 'json',
},
```
2. connect to local mongodb with moogseAdapter
```
"@payloadcms/db-mongodb": "3.0.0-beta.58",
```
3. create document in admin portal and add form information with json field populated
4. click save

Expected res:
json field data is saved and present in form

Actual res:
file field stay empty

Other info:

mongodb (no file field):
 ```
[
  {
    "_id": "668a87281e3a01d1d7af803e",
    "name": "test",
    "type": "pdf",
    "creator": "668a86fc1e3a01d1d7af7f90",
    "tenant": "668a87061e3a01d1d7af7fc0",
    "createdAt": "2024-07-07T12:16:40.280Z",
    "updatedAt": "2024-07-07T12:23:46.240Z",
    "__v": 0
  }
]
```

har:
[payload_bug.har.zip](https://github.com/user-attachments/files/16119369/payload_bug.har.zip)

**Comment by paulpopus** [comment]
I've not been able to reproduce this, can you provide a reproduction repo please?

**Comment by shuowu** [comment]
@paulpopus issue is reproducible if field is named specific as `file`


https://github.com/user-attachments/assets/8e78d0b7-9554-4737-bfb0-fe9869f26cba

![Screenshot 2024-07-11 at 11 38 19 PM](https://github.com/user-attachments/assets/ac4582a4-ebb1-4a6d-97d4-a91d6d660a8f)

**Comment by paulpopus** [comment]
Thanks for this, I recommend you use a different field name as certain names are protected, see: https://payloadcms.com/docs/beta/fields/overview#field-names

I made a PR that will validate the name and throw an error if it's one of the protected ones going forward
