### ISSUE TITLE
Payload Admin Webpage not Loading?

### ISSUE THREAD

**Issue by joecaraccio** [payloadcms/payload#707]
# Bug Report

I simply have an instance of payload running in an express server running on a doctor container. Virtually nothing special on the setup.

When I load the webpage, it seems like the background of the panel renders.. but nothing else

![image](https://user-images.githubusercontent.com/966352/177005348-0d5a5769-9f32-4fb3-bd29-f8d40c6a38e2.png)

I noticied some react related errors in the console, but have no other useful information in the command line.

Few of the errors:

![image](https://user-images.githubusercontent.com/966352/177005387-920caf01-f32e-43d0-8677-28aa2fa401aa.png)

That uncaught promise at the bottom looks like its the culprit.. any idea why?

Thanks!

**Comment by ayusshrathore** [comment]
Hey!
I faced this issue too recently, try checking the versions for react and react-dom. They might be mismatching. And share your code if possible, there might be some error while importing the component in payload config.

**Comment by akanshSirohi** [comment]
Hey! @joecaraccio 
These are the basic errors that sometimes occur if you are using `npm`, always use yarn with payload. This might solve your issue.

**Comment by DanRibbens** [comment]
@joecaraccio could you share your repo for me to take a look at it? We have other discussions that include working docker configs and I'm happy to help with that if it is the cause.

You can check the react versions using `npm view react versions`. 

It shouldn't matter whether you're using `npm` or `yarn`, either _should_ work, but if there are differences between the two we want to address them. In the last patch we have support `pnpm` also.

**Comment by joecaraccio** [comment]
@DanRibbens 
Thanks for the reply!  @ayusshrathore  pointed out my exact issue.. but I'll use that command in the feature!

**Comment by joecaraccio** [comment]
Mismatching react versions

**Comment by joecaraccio** [comment]
![image](https://user-images.githubusercontent.com/966352/179126930-f234268d-49d4-4bcd-9189-273e59984df5.png)

**Comment by joecaraccio** [comment]
"In order for Hooks to work, the react import from your application code needs to resolve to the same module as the react import from inside the react-dom package.

If these react imports resolve to two different exports objects, you will see this warning. This may happen if you accidentally end up with two copies of the react package."

I'm trying to make sense of this, but wondering if these conflicting versions is part of the issue?

**Comment by joecaraccio** [comment]
so I just used yarn and added a dependency:

  "resolutions": {
    "react": "18.2.0"
  },

which seemed to solve it!

**Comment by jmikrut** [comment]
Ahh nice. Yeah @joecaraccio in my experience, this is almost 100% of the time caused by having more than one copy of React installed, which your `resolutions` fix.

I will move this to a discussion so we keep it around in case anyone else runs into this!
