### ISSUE TITLE
revalidatePath in payload config does not purge cached data

### ISSUE THREAD

**Issue by masonyekta** [payloadcms/payload#7073]
### Payload Version

3.0.0-beta.58

### Node Version

v22.3.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

I am trying to use `revalidatePath()` [function](https://nextjs.org/docs/app/api-reference/functions/revalidatePath) in the payload config file with a collection hook to purge the cache after an item in the collection is deleted. 

```ts
// payload.config.ts
import { revalidatePath } from 'next/cache'

collections: [
 ...
hooks: {
    afterDelete: [
        async () => {
             revalidatePath('/')
	},
    ],
},
```

However, the path is not re-validated after the item is deleted. 

@paulpopus tagging you here as we discussed. 

### Reproduction Steps

Call `revalidatePath('/')` in a collection hook, update/delete item in the collection but page is not re-validated. Must build first and then start the server to replicate the issue.

**Comment by paulpopus** [comment]
This works for me, the revalidate functions from Next will not throw you any errors or success message if the revalidation itself succeeds or fails, it can only track the function itself.

My inclination is that the way you're caching your data is what's affecting revalidation here.

Have a look in our website template to see this working: https://github.com/payloadcms/payload/tree/beta/templates/website

**Comment by masonyekta** [comment]
@paulpopus I tried using the website template, you can follow these steps to reproduce this issue: 
- Create 4-5 sample posts 
- Create a page 
- In the content / Layout selection, add Archive
- Select individual selection
- Add the sample posts to it
- run `pnpm run build` and `pnpm run start`
- Visit the page and you should see the posts, now go to the dashboard and remove one of the posts
- Visit the page again and removed items are still showing up

**Comment by paulpopus** [comment]
Yeah in that case you need to adjust your validation functions to revalidate the pages where this content is referenced. This isn't a payload issue.

You could set up your data cache to [use tags](https://nextjs.org/docs/app/building-your-application/caching#fetch-optionsnexttags-and-revalidatetag) instead in combination with [unstable cache](https://nextjs.org/docs/app/api-reference/functions/unstable_cache) and that way your data should revalidate across the site fully.

**Comment by masonyekta** [comment]
@paulpopus Thanks! I discovered that something was acting up on my local machine. I deployed the changes to prod, and after deleting the record, the homepage was revalidated and updated with the recent changes. Thank you again for looking into the issue.
