### ISSUE TITLE
field validate function not translatable 

### ISSUE THREAD

**Issue by sriechersrc** [payloadcms/payload#7078]
### Payload Version

3.0.0-beta.46

### Node Version

v20.10.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

I have the following field with a validate function:

```typescript
{
  name: 'link',
  type: 'text',
  required: true,
  label: {
    en: "Link",
    de: "Verlinkung"
  },
  validate: (value) => {
    try {
      z.string().url().parse(value)
      return true
    } catch {
      return 'Please enter a valid URL' // make this translatable
    }
  },
}
```

The return needs to be either a `string` or `true`, but i would like to be able to use a translation record like in label, so the message automatically gets translated in the admin ui

### Reproduction Steps

see above

### Adapters and Plugins

db-mongodb

**Comment by JarrodMFlesch** [comment]
@sriechersrc you could use the secondary options object supplied to the validation function and use `req.i18n.language` and return a response based on that.

```ts
{
  name: 'link',
  type: 'text',
  required: true,
  label: {
    en: "Link",
    de: "Verlinkung"
  },
  validate: (value, { req }) => {
    try {
      z.string().url().parse(value)
      return true
    } catch {
      return {
        'en': 'Please enter a valid URL',
      }?.[req.i18n.language] || 'Please enter a valid URL'
    }
  },
}
```
