### ISSUE TITLE
Routes are not configured properly for globals when creating a custom component in the admin

### ISSUE THREAD

**Issue by ccapndave** [payloadcms/payload#7081]
### Payload Version

3.0.0-beta.59

### Node Version

v20.11.1

### Next.js Version

14.2.4

### Describe the Bug

Custom components in the admin work for collections, but not for globals.

### Reproduction Steps

In the Payload config file add the following to a *collection*:

```
  admin: {
    components: {
      views: {
        Edit: {
          CrowdIn: {
            path: "/crowdin",
            Component: CrowdinView,
            Tab: {
              label: "CrowdIn",
              href: "/crowdin"
            }
          }
        }
      }
    }
  },
```

where `CrowdinView` is some basic component like:

```
export const CrowdinView: EditViewComponent =() => {
  return <div>Hello world</div>;
};
```

This will add a button to the tab called "CrowdIn", and will set up a route at `/admin/collections/<slug>/<id>/crowdin`.  Clicking the tab will navigate to this route and "Hello world" will be displayed.

Now do the same thing for a global; the button is added to the tab, and clicking it will navigate to `admin/globals/<slug>/crowdin`.

However, the normal global edit page is displayed instead of "Hello world"; it seems that the route isn't being set up properly for the global.

**Comment by paulpopus** [comment]
This will be fixed in the next beta, thanks for the report!

https://github.com/payloadcms/payload/pull/7148

**Comment by ccapndave** [comment]
Thanks very much 🙂
