### ISSUE TITLE
Searching in a collection and navigating to another collection adds the search value to the new collection

### ISSUE THREAD

**Issue by Bobeta** [payloadcms/payload#7085]
### Payload Version

beta v58

### Node Version

v21

### Next.js Version

v15-rc

### Describe the Bug

Using v3 beta 58. If I search something in a collection and navigate to another collection, that search is added to that collection as well and I can see in the address bar "&search=test".

### Reproduction Steps

Open up a collection, in the bar "Search by name" search for something, navigate to another collection.

**Comment by paulpopus** [comment]
This will be fixed in the next beta release, thanks a lot!

**Comment by BhargavSuthar99** [comment]
I see changes are already merged with [v3.0.0-beta.66](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.66) but I'm still facing this issue with 3.0.0-beta.68

https://github.com/user-attachments/assets/1688f4d7-c6f7-4491-9d93-ec37ed5ffb40

**Comment by paulpopus** [comment]
@BhargavSuthar99 Thanks for the video but I've not been able to reproduce this at all on my end. Neither in our test suites nor a standalone payload project. We have an automated test for this behaviour too which has been passing


Tested with:

```
"next": "15.0.0-canary.77",
"payload": "3.0.0-beta.71",
```

If you can provide a reproduction repo that would help a lot in isolating this problem!

**Comment by paulpopus** [comment]
Reopening as it has situations where it's not fixed

**Comment by paulpopus** [comment]
This will be fixed in https://github.com/payloadcms/payload/pull/8081 where I went through and made a wider set of changes
