### ISSUE TITLE
Doubled / malformed querystring params in Image Edit modal cause errors when saving image properties

### ISSUE THREAD

**Issue by lynndylanhurley** [payloadcms/payload#7101]
### Payload Version

v3.0.0-beta.59

### Node Version

21.4.0

### Next.js Version

14.3.0-canary.28

### Describe the Bug

When trying to save updates to images, for example changing the focal point, the API throws the following error:

```
ERROR: Expected integer for width but received NaN of type number
```

After some digging, we discovered that the request was sending duplicates of every form value, which the API was interpreting as arrays instead of integers.

For example, this is what the submit request looks like when saving images:

```
PATCH http://localhost:3000/api/images/52?depth=0&fallback-locale=null&fallback-locale=null&locale=en-US&locale=en-US&uploadEdits[crop][height]=100&uploadEdits[crop][height]=100&uploadEdits[crop][heightPixels]=526&uploadEdits[crop][heightPixels]=526&uploadEdits[crop][unit]=%&uploadEdits[crop][unit]=%&uploadEdits[crop][width]=100&uploadEdits[crop][width]=100&uploadEdits[crop][widthPixels]=800&uploadEdits[crop][widthPixels]=800&uploadEdits[crop][x]=0&uploadEdits[crop][x]=0&uploadEdits[crop][y]=0&uploadEdits[crop][y]=0&uploadEdits[focalPoint][x]=33.08541679382324&uploadEdits[focalPoint][x]=33.08541679382324&uploadEdits[focalPoint][y]=31.79024235830561?depth=0&uploadEdits[focalPoint][y]=31.79024235830561
```

Notice that every value is duplicated, and that there's an additional `?depth=0` param thrown in randomly toward the end, which is being interpreted as part of the `uploadEdits[focalPoint][y]` value because of the extra questionmark.

When the API receives this request, it's interpreting the values as arrays. So `uploadEdits[crop][width]` is being read as `[100, 100]` instead of just `100`, and this is causing `sharp` to throw an error.

The `action` param on the form itself looks correct (see attached image).

<img width="1300" alt="Screenshot 2024-07-10 at 3 51 59 PM" src="https://github.com/payloadcms/payload/assets/468037/aa62d324-094a-4e7d-b331-12e5d31cde25">

### Reproduction Steps

1. Create a collection with a nested `Image` upload field.
2. Upload a new image, and try to change the focal point.
3. Save the image.

This will throw the error described above.

### Adapters and Plugins

storage-vercel-blob, db-postgres, @payload-enchants/translator, redirects

I did try disabling the `@payload-enchants/translator` plugin but that did not resolve the issue.

**Comment by PatrikKozak** [comment]
Hey @lynndylanhurley - can you please send over a reproducible config with your nested `Upload` field?

**Comment by lynndylanhurley** [comment]
Hi @PatrikKozak , I'll put together a reproducible config today

**Comment by lynndylanhurley** [comment]
@PatrikKozak [here's a reproducible example](https://github.com/payloadcms/payload-3.0-demo/pull/240) based on the `payload-3.0-demo` repo with only the following field added to the `pages` collection:

```
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media'
        }
```

To reproduce the issue:

1. create a new `Page` and upload an image
2. edit the image by changing one of the cropping values
3. try to save

The request will fail.

Here is what the querystring params look like in the web inspector:

<img width="2053" alt="Screenshot 2024-07-11 at 10 18 08 AM" src="https://github.com/payloadcms/payload/assets/468037/c4ee5a07-d02f-4471-9eb5-425be64f04f7">

Notice how every value is an array instead of a singular value.

**Comment by PatrikKozak** [comment]
@lynndylanhurley ahh I see the problem now - thank you for the details, we'll get a fix out for this asap!

**Comment by lynndylanhurley** [comment]
Thank you @PatrikKozak !

**Comment by PatrikKozak** [comment]
Fixed with this [PR](https://github.com/payloadcms/payload/pull/7117).
