### ISSUE TITLE
Admin dashboard infinite loop in ListView when filtering on relation

### ISSUE THREAD

**Issue by akhrarovsaid** [payloadcms/payload#7103]
### Describe the Bug

Refreshing the page after filtering on a relation field via the "Filter" pill causes an infinite loop on the page. It will continuously request the query until the server errors out with a 429 error.  My main project experiencing this issue is using v2.22.0.
### To Reproduce

1. Use `npx` to create a new Payload v2 project using one of the templates (website, ecommerce, etc...)
2. Install deps and run dev
3. Navigate to /admin, login, and select a collection with a relationship field
4. Open devtools, click the filter pill and filter on the relation
5. Refresh the page with devtools open to the network tab 

I used the eCommerce template in the video below.

https://github.com/payloadcms/payload/assets/36972061/84926005-c830-4b38-ab80-80d04460c9c4

### Payload Version

v2.22.0

### Adapters and Plugins

db-postgres, bundler-webpack, plugin-nested-docs, plugin-redirects, plugin-seo, richtext-slate

**Comment by akhrarovsaid** [comment]
What is interesting is if I fork the payload project and run the community version with pnpm to reproduce - the issue doesn't occur... However, if you use npx to create any of the templates, I can reproduce the issue every time.

**Comment by JarrodMFlesch** [comment]
@akhrarovsaid the reason you were unable to repro this in the _community folder is by default it is using MongoDB, but this issue is PG specific.
