### ISSUE TITLE
Postgres: Group field with camelCase name cannot save array field 

### ISSUE THREAD

**Issue by ClementCardonnel** [payloadcms/payload#7109]
### Description
- Using PostgreSQL,
- if you have a group field with an uppercased letter,
- and that group field contains an array field,
- then the content of the array field won't be correctly saved or read by the front-end using the local API.

### Example
```typescript
import type { Field } from "payload/types";
import { activity } from "./activity";

export const mustDoActivities: Field = {
  name: "mustDo", // ❌ Failure occurs here: mustDo being written in camel case leads to unexpected behaviors
  label: false,
  type: "group",
  fields: [
    {
      name: "title",
      label: {
        en: "Title > Must do activities",
        fr: "Titre > Activités incontournables",
      },
      type: "text", // 🆗 This will be read and saved correctly
      localized: true,
    },
    {
      name: "paragraph",
      label: {
        en: "Paragraph > Must do activities",
        fr: "Paragraph > Activités incontournables",
      },
      type: "richText", // 🆗 This will be read and saved correctly
      localized: true,
    },
    {
      name: "list",
      label: {
        en: "Must do activities list",
        fr: "Liste des activités incontournables",
      },
      type: "array", // ❌ This will be inconsistently saved and will never appear on the front-end
      fields: activity,
    },
  ],
};
```

### Discussion

This was a nasty issue to diagnose. Thankfully, we had multiple tabs other than mustDo. Some single-words, and two written in camel case. We came to the realization that the only tabs that were working inconsistently were the ones written in camel case. Also, I'm not sure of this, but this issue could show up only when using the Local API to populate the data. We're doing custom CSV importing and we're using the local API to populate the data.

### Quick fix
Do not include any uppercased character in your field names. 

### Related
This issue could be related to: https://github.com/payloadcms/payload/issues/5377

### Reproducing the issue
1. Create a group field
2. Name that field with two camel-cased words, like "mustDo"
3. Add a title field
4. Add an array field
5. Use the Local API to populate data
6. Notice that the data can appear in one of the generated table, but it is not consistent between the v_version tables and the standard table
7. Notice that your data never shows up on the front-end

### Reproducing the normal behavior
1. Create a group field
2. Name that field without including any uppercased character, like "mustdo"
3. Add a title field
4. Add an array field
5. Use the Local API to populate data
6. Notice that everything is fine.

### Payload Version

2.23.1

### Adapters and Plugins

db-postgres

**Comment by r1tsuu** [comment]
Other point: it only happens if you have a localized field inside of camelCase group -> array. I'm down to fix it.

**Comment by r1tsuu** [comment]
3.0 fix - https://github.com/payloadcms/payload/pull/8009
2.0 fix - https://github.com/payloadcms/payload/pull/8010
