### ISSUE TITLE
richtext-lexical slash menu does not render option titles on Safari

### ISSUE THREAD

**Issue by mattwelson** [payloadcms/payload#7123]
### Describe the Bug

![image](https://github.com/user-attachments/assets/bcdc260f-0ff3-4e93-b804-170411f8b08c)
When running on Safari the Lexical slash dropdown menu does not render the option title, however this does seem to work fine on Chrome.
![image](https://github.com/user-attachments/assets/61863078-555a-46f7-b927-b13a8a33c67b)

### To Reproduce

I had this issue just using the basic installation steps from @payloadcms/richtext-lexical
`import { lexicalEditor } from "@payloadcms/richtext-lexical";`

This only happens on Safari

### Payload Version

3.0.0-beta.60 and 2.23.1

### Adapters and Plugins

@payloadcms/richtext-lexical

**Comment by rafalnawojczyk** [comment]
@AlessioGr  I can reproduce this error on my website:
![image](https://github.com/user-attachments/assets/54bd1091-6c28-4909-9a50-e50f72d39cb3)

Here is link to my repo:
https://github.com/rafalnawojczyk/Personal-Portfolio-Website

I will try to work on that today, maybe I could contribute on that If I will find what's wrong

**Comment by rafalnawojczyk** [comment]
Funny enough is a fact, that when I will select this element:
![image](https://github.com/user-attachments/assets/37e8ad88-ce2f-43c6-a685-1b2210278124)

and uncheck and check again `align-items: center` - it will work properly.

**Comment by mattwelson** [comment]
I can no longer replicate this issue either, I have been updating my versions as I go (though I'm a few behind this morning, I'm currently on 65 not 67) - it is now looking good on Safari. 

Thanks for the help here, I appreciate it.

Can I just quickly ask, can I get the Lexical toolbar to show in a block?
