### ISSUE TITLE
label of document in hasMany relation field displays "Untitled"

### ISSUE THREAD

**Issue by genox** [payloadcms/payload#7124]
### Payload Version

beta.60

### Node Version

20.12

### Next.js Version

payload-demo

### Describe the Bug

I have a hasMany relation field  within a block type that links documents to the block.

The labels, both in the dropdown and once selected, display "Untitled" instead of the document name.

I assume this broke with some of the most recent versions, it used to work before :)

<img width="461" alt="Screenshot 2024-07-12 at 08 17 48" src="https://github.com/user-attachments/assets/e5fa88f2-3801-407a-ade4-9ec5d85ca823">

<img width="445" alt="Screenshot 2024-07-12 at 08 15 20" src="https://github.com/user-attachments/assets/b4334975-6e14-4f96-a343-64d0e9bb956b">

### Reproduction Steps

- use a multilingual instance and edit content in the non-default language
- create two document types
- create a block type and add a relation field:

```
          {
            name: 'flowRelation',
            type: 'relationship',
            label: I18nCollection.fieldLabel.taskFlows,
            relationTo: 'task-flows',
            hasMany: true,
          },

```

- add the block to a document and make sure the relations are technically correct
- add dummy content
- see missing labels when trying to select in the UI

### Adapters and Plugins

postgres

**Comment by genox** [comment]
Additional information: 

The labels are also not updated when the target document's name/title has been changed.

I tried to add a new document in place, e.g. modal, and the document title seems to not have been saved, thus leading to Untitled being shown as label.

However, once the document name has been changed, the label is not being updated.

So I think there are 2 issues here:

- Labels are not being updated when the related document was changed
- Some fields are not being saved when content is added via modal

**Comment by genox** [comment]
related to https://github.com/payloadcms/payload/issues/7125

**Comment by paulpopus** [comment]
Hey @genox I feel like you have a few issues outlined here without clear reproduction

I've handled this direct issue where the label comes back undefined as locale was not being passed through before https://github.com/payloadcms/payload/pull/7178

This will be released in the next beta. If the other two reported issues are still a problem could you provide a reproduction config for me please? If not you can open a separate issue for each as well

I will close this ticket for now but happy to re-open if my PR above doesn't solve it for your use case!
