### ISSUE TITLE
Time select has wrong background color in dark-mode.

### ISSUE THREAD

**Issue by PP-Tom** [payloadcms/payload#7127]
### Payload Version

Beta 60

### Node Version

20

### Next.js Version

19 RC

### Describe the Bug

![image](https://github.com/user-attachments/assets/0d0f62b6-b390-43ee-b23e-6a96c8f8b83e)

### Reproduction Steps

Create a date field and display time selector, in dark mode the time selector is illegible.

**Comment by paulpopus** [comment]
I can't replicate this in Firefox or Chrome on linux even when emulating prefers light mode. Can you provide more information about reproducing this please?

**Comment by PP-Tom** [comment]
Hey @paulpopus,

I'm on Chrome on MacOSX and I can either do prefers dark mode and setting dark mode in user settings to see this.

![image](https://github.com/user-attachments/assets/365a9575-687e-445f-be34-e72687aa5b42)

It looks like the correct CSS attributed are being overwritten by a higher priority selector. It could be related in which order things have been pulled in at build time?
