### ISSUE TITLE
Custom Types not working for `getNextRequestI18n({ config })` via generics

### ISSUE THREAD

**Issue by tobiasiv** [payloadcms/payload#7137]
### Link to reproduction

-

### Payload Version

3.0.0-beta.63

### Node Version

20.13.1

### Next.js Version

15.0.0-canary.58

### Describe the Bug

I'm getting a type error when trying to use custom translations on the server.
I know you must merge your custom translations with the default translations via generics like:

`const { t } = useTranslation<CustomTranslationObject, CustomTranslationKeys>()`

But these generics aren't available for `getNextRequestI18n({ config })` 

### Reproduction Steps

1. Create a custom translation entry in buildConfig

```javascript
i18n: {
  supportedLanguages: { en },
  translations: {
    en: {
      custom: {
        newTranslation: "New Translation",
      },
    },
  },
},
```

2. Create a custom server component

```javascript
export default async function CustomTranslation() {
    const config = await payloadConfig;
    const payload = await getPayloadHMR({ config });
    const { t } = await getNextRequestI18n({ config });

    return (
        <div>
            <p>{t("custom:newTranslation")}</p>
        </div>
    );
}
```

### Adapters and Plugins

-

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/7157
