### ISSUE TITLE
Attempted import error: 'reduceFieldsToValues' is not exported from 'payload/shared' (imported as 'reduceFieldsToValues').

### ISSUE THREAD

**Issue by sharpsteelsoftware** [payloadcms/payload#7138]
### Link to reproduction

https://github.com/sharpsteelsoftware/muf-tao

### Payload Version

3.0.0-beta.63

### Node Version

v20.12.2

### Next.js Version

14.2.5

### Describe the Bug

'Failed to compile'
./node_modules/@payloadcms/next/dist/views/LivePreview/Preview/index.js
Attempted import error: 'reduceFieldsToValues' is not exported from 'payload/shared' (imported as 'reduceFieldsToValues').

### Reproduction Steps

Initialized a new nextjs project with npx create-next-app
Run the 3.0 beta npx create-payload-app@beta
Go to http://localhost:3000/admin

**Comment by jacobsfletch** [comment]
@sharpsteelsoftware are all of your Payload dependencies in sync? All Payload packages need to share the same version number. This change was shipped in the last beta version of `payload`, so if your `ui` pkg was updated, but not `payload`, this error will throw.

**Comment by jacobsfletch** [comment]
Closing for now, since this is likely an issue with version inconsistencies and not core functionality. @sharpsteelsoftware if you can show me the dependencies listed in your package.json, I can try and help further. Feel free to keep the conversation in this issue going.

**Comment by asbhogal** [comment]
Hi @jacobsfletch I seem to be encountering a similar error. Have double checked versions and re-installed packages but no luck. Would you be able to take a quick look below and see if I've missed anything? Many thanks.

`{
  "name": "fyrre-magazine",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_OPTIONS=--no-deprecation next dev",
    "build": "cross-env NODE_OPTIONS=--no-deprecation next build",
    "payload": "cross-env NODE_OPTIONS=--no-deprecation payload",
    "start": "next start",
    "lint": "next lint",
    "format": "npx prettier **/*.{js,jsx,ts,tsx} --write",
    "test:e2e": "playwright test",
    "prepare": "husky install",
    "generate:types": "payload generate:types",
    "generate:schema": "payload-graphql generate:schema"
  },
  "dependencies": {
    "@payloadcms/db-mongodb": "3.0.0-beta.67",
    "@payloadcms/db-postgres": "3.0.0-beta.67",
    "@payloadcms/next": "3.0.0-beta.67",
    "@payloadcms/richtext-lexical": "3.0.0-beta.67",
    "@payloadcms/richtext-slate": "3.0.0-beta.67",
    "@payloadcms/ui": "3.0.0-beta.67",
    "@axe-core/playwright": "latest",
    "@hookform/resolvers": "latest",
    "@radix-ui/react-dialog": "latest",
    "@radix-ui/react-separator": "latest",
    "@radix-ui/react-slot": "latest",
    "babel-plugin-react-compiler": "^0.0.0-experimental-592953e-20240517",
    "class-variance-authority": "latest",
    "clsx": "latest",
    "cross-env": "^7.0.3",
    "graphql": "^16.9.0",
    "gsap": "latest",
    "lucide-react": "latest",
    "next": "15.0.0-rc.0",
    "payload": "3.0.0-beta.58",
    "react": "19.0.0-rc-f994737d14-20240522",
    "react-dom": "19.0.0-rc-f994737d14-20240522",
    "react-hook-form": "latest",
    "shadcn-ui": "^0.2.3",
    "sharp": "0.32.6",
    "tailwind-merge": "latest",
    "tailwindcss-animate": "latest",
    "zod": "latest"
  },
  "engines": {
    "node": "^18.20.2 || >=20.9.0"
  },
  "devDependencies": {
    "@payloadcms/graphql": "3.0.0-beta.67",
    "@playwright/test": "latest",
    "@types/node": "^20.14.9",
    "@types/react": "npm:types-react@19.0.0-beta.2",
    "@types/react-dom": "npm:types-react-dom@19.0.0-beta.2",
    "autoprefixer": "latest",
    "eslint": "^8.57.0",
    "eslint-config-next": "15.0.0-rc.0",
    "husky": "latest",
    "postcss": "latest",
    "tailwindcss": "latest",
    "lint-staged": "^15.2.7",
    "prettier": "^3.3.2",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-jsx-a11y": "^6.9.0",
    "eslint-plugin-prettier": "^5.1.3",
    "typescript": "latest",
    "@typescript-eslint/eslint-plugin": "^7.16.0",
    "@typescript-eslint/parser": "^7.16.0"
  },
  "overrides": {
    "@types/react": "npm:types-react@19.0.0-beta.2",
    "@types/react-dom": "npm:types-react-dom@19.0.0-beta.2"
  }
}`

**Comment by stuartmitchelhill** [comment]
I'm having the same issue as well, can confirm ass versions are matching

`{
  "name": "payload-demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@payloadcms/db-postgres": "^3.0.0-beta.69",
    "@payloadcms/next": "^3.0.0-beta.69",
    "@payloadcms/plugin-cloud": "^3.0.0-beta.69",
    "@payloadcms/richtext-lexical": "^3.0.0-beta.69",
    "clsx": "^2.1.1",
    "graphql": "^16.8.1",
    "next": "14.2.5",
    "payload": "^3.0.0-beta.69",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@svgr/webpack": "^8.1.0",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.5",
    "include-media": "^2.0.0",
    "sass": "^1.77.8",
    "sharp": "^0.33.4",
    "typescript": "^5"
  }
}
`

**Comment by stuartmitchelhill** [comment]
Hey @jacobsfletch i've encountered the same issue as well, for reference here is my package.json

```
{
  "name": "payload-demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@payloadcms/db-postgres": "^3.0.0-beta.69",
    "@payloadcms/next": "^3.0.0-beta.69",
    "@payloadcms/plugin-cloud": "^3.0.0-beta.69",
    "@payloadcms/richtext-lexical": "^3.0.0-beta.69",
    "clsx": "^2.1.1",
    "graphql": "^16.8.1",
    "next": "14.2.5",
    "payload": "^3.0.0-beta.69",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@svgr/webpack": "^8.1.0",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.5",
    "include-media": "^2.0.0",
    "sass": "^1.77.8",
    "sharp": "^0.33.4",
    "typescript": "^5"
  }
}
```

**Comment by AdvithShetty** [comment]
@jacobsfletch Even i got the same issue i have all payload packages at beta .70

**Comment by jacobsfletch** [comment]
Ok I will take a closer look into this asap, thanks for the report everyone 👍

**Comment by jacobsfletch** [comment]
> Hi @jacobsfletch I seem to be encountering a similar error. Have double checked versions and re-installed packages but no luck. Would you be able to take a quick look and see if I've missed anything? Many thanks.

@asbhogal I see in your package.json that you in fact have version inconsistencies:

```json
{
    "@payloadcms/next": "3.0.0-beta.67",
    "@payloadcms/ui": "3.0.0-beta.67",
    "payload": "3.0.0-beta.58"
}
```

Update `payload` to match the others (at least `^3.0.0-beta.60`) and this error should go away for you. Let me know if not.

**Comment by iiskakov** [comment]
<img width="565" alt="Screen Shot 2024-08-05 at 09 34 32" src="https://github.com/user-attachments/assets/148f96d5-724d-417f-a3e3-5bc0b81a5200">


Hi, I believe all my versions are in sync. Still getting the error though.

**Failed to compile.

./node_modules/@payloadcms/next/dist/views/LivePreview/Preview/index.js
Attempted import error: 'reduceFieldsToValues' is not exported from 'payload/shared' (imported as 'reduceFieldsToValues')**


And here is my package.json

`
{
  "name": "2d-pro",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@payloadcms/db-postgres": "^3.0.0-beta.71",
    "@payloadcms/next": "^3.0.0-beta.71",
    "@payloadcms/plugin-cloud": "^3.0.0-beta.71",
    "@payloadcms/richtext-lexical": "^3.0.0-beta.71",
    "@payloadcms/ui": "3.0.0-beta.71",
    "@supabase/ssr": "latest",
    "@supabase/supabase-js": "^2.43.4",
    "babel-plugin-react-compiler": "^0.0.0-experimental-334f00b-20240725",
    "framer-motion": "12.0.0-alpha.0",
    "graphql": "^16.8.1",
    "next": "15.0.0-rc.0",
    "next-video": "^1.1.0",
    "payload": "^3.0.0-beta.71",
    "react": "19.0.0-rc-f994737d14-20240522",
    "react-dom": "19.0.0-rc-f994737d14-20240522",
    "react-player": "3.0.0-canary.0",
    "sharp": "^0.33.4",
    "swr": "^2.2.5"
  },
  "devDependencies": {
    "@types/react": "18.3.3",
    "eslint": "^8",
    "eslint-config-next": "15.0.0-rc.0",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "5.4.5"
  }
}

`

**Comment by valentindiehl** [comment]
It seems to me that could be a MacOS-specific problem! I have a Beta project running perfectly on Windows, but it fails with exactly the same error also on my MacBook. Version numbers are all in sync, but I can't get it to work on the Mac. Maybe that has something to do with it?

@iiskakov What are you running the project on, if I may ask?

**Comment by MisterCommand** [comment]
Same issue, resolved it by deleting the `payload` folder in `node_modules` and reinstalling the package.

**Comment by jacobsfletch** [comment]
> It seems to me that could be a MacOS-specific problem

@valentindiehl, either that or this is related to your package manager (see below).

> Same issue, resolved it by deleting the payload folder in node_modules and reinstalling the package.

@MisterCommand, great to hear it's working for you 👍 Removing your lock file and reinstalling might also produce the same results, i.e. `package-lock.json`, `yarn.lock`, `pnpm-lock.yaml`. Your package manager have resolved dependencies in an unexpected way.

**Comment by ceyhun-yildiz** [comment]
I'm having the same issue here... Just installed the beta version and getting the same error on admin page 

Build Error
Next.js (15.0.0-canary.104) is outdated [(learn more)](https://nextjs.org/docs/messages/version-staleness)
Failed to compile

./src/app/(payload)/admin/importMap.js
Attempted import error: 'emptyComponent' is not exported from '@payloadcms/ui/shared' (imported as 'emptyComponent_0').
This error occurred during the build process and can only be dismissed by fixing the error.



Here's my package.json file

{
  "name": "payload-gucluyasa-wp-migration",
  "version": "1.0.0",
  "description": "A blank template to get started with Payload 3.0",
  "license": "MIT",
  "type": "module",
  "scripts": {
    "build": "cross-env NODE_OPTIONS=--no-deprecation next build",
    "dev": "cross-env NODE_OPTIONS=--no-deprecation next dev",
    "devsafe": "rm -rf .next && cross-env NODE_OPTIONS=--no-deprecation next dev",
    "lint": "cross-env NODE_OPTIONS=--no-deprecation next lint",
    "start": "cross-env NODE_OPTIONS=--no-deprecation next start",
    "payload": "payload",
    "generate:types": "payload generate:types",
    "generate:importmap": "payload generate:importmap"
  },
  "dependencies": {
    "@payloadcms/db-postgres": "beta",
    "@payloadcms/next": "beta",
    "@payloadcms/plugin-cloud": "beta",
    "@payloadcms/richtext-lexical": "beta",
    "cross-env": "^7.0.3",
    "graphql": "^16.8.1",
    "next": "15.0.0-canary.104",
    "payload": "3.0.0-beta.82",
    "react": "19.0.0-rc-06d0b89e-20240801",
    "react-dom": "19.0.0-rc-06d0b89e-20240801",
    "sharp": "0.32.6"
  },
  "devDependencies": {
    "@types/node": "^20.14.9",
    "@types/react": "npm:types-react@19.0.0-rc.0",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.0",
    "eslint": "^8",
    "eslint-config-next": "15.0.0-canary.104",
    "typescript": "5.5.4"
  },
  "engines": {
    "node": "^18.20.2 || >=20.9.0"
  },
  "pnpm": {
    "overrides": {
      "@types/react": "npm:types-react@19.0.0-rc.0",
      "@types/react-dom": "npm:types-react-dom@19.0.0-rc.0"
    }
  },
  "overrides": {
    "@types/react": "npm:types-react@19.0.0-rc.0",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.0"
  }
}
