### ISSUE TITLE
ValidationError missing `data` property in production.

### ISSUE THREAD

**Issue by alponet** [payloadcms/payload#7140]
### Payload Version

3.0.0-beta.60

### Node Version

20.13.1

### Next.js Version

15.0.0-canary.64

### Describe the Bug

In dev mode, when a ValidationError is thrown, it contains a `data` property with valuable info:

```json
{
  "errors": [
    {
      "name": "ValidationError",
      "data": [
        {
          "field": "email",
          "message": "A user with the given email is already registered."
        }
      ],
      "message": "The following field is invalid: email"
    }
  ]
}
```

In production, `data` is missing:

```json
{
  "errors": [
    {
      "message": "The following field is invalid: email"
    }
  ]
}
```

### Reproduction Steps

For the default User collection (blank template will do), try to create a new user with a taken email address.
Compare the responses of dev mode vs build.

### Adapters and Plugins

db-mongodb

**Comment by jacobsfletch** [comment]
@alponet I was able to recreate this, will look into it.

**Comment by jacobsfletch** [comment]
Got to the bottom of this @alponet, will go out in the next release.
