### ISSUE TITLE
CollectionAfterMeHook mentioned in the documentations does not exist.

### ISSUE THREAD

**Issue by itzaks** [payloadcms/payload#7145]
### Describe the Bug

Trying to import `import { CollectionAfterMeHook } from 'payload/types';` throws an error that it's not exported, looking through the code I could see that it's not even in the code but it's mentioned to exist here: https://payloadcms.com/docs/hooks/collections#afterme 🙃

### To Reproduce

`import { CollectionAfterMeHook } from 'payload/types'`

### Payload Version

2.23.1

**Comment by itzaks** [comment]
The famous 1 minute later I realized it's called `CollectionMeHook`. The same goes for `CollectionAfterRefreshHook` which is called `CollectionRefreshHook` in the code. So probably just outdated docs then.

**Comment by jacobsfletch** [comment]
@itzaks there is in fact an [`afterMe`](https://github.com/payloadcms/payload/blob/84d214f99207ad78a466b8c16eb36e29f57cd0e3/packages/payload/src/auth/operations/me.ts#L86) and [`afterRefresh`](https://github.com/payloadcms/payload/blob/84d214f99207ad78a466b8c16eb36e29f57cd0e3/packages/payload/src/auth/operations/refresh.ts#L136) hooks. Looks like the _types_ are wrongly named  here, they are exported as `AfterMe` and `AfterRefresh`.

**Comment by itzaks** [comment]
Yes the types are correct there, but the collections hook are called `CollectionMeHook`, `CollectionRefreshHook`.

**Comment by jacobsfletch** [comment]
No those are entirely _different_ hooks with different types, i.e. there is the `me` and `refresh` hooks, different from the `afterMe` and `afterRefresh` hooks. That page documents both. The imported types are correct for the former. The latter has improperly documented imports. I'll leave this comment on your PR, too.

**Comment by jacobsfletch** [comment]
I've gone ahead and pushed an update to your PR, and merged it in. I'll make sure this change is made to beta as well. Thank you for reporting this and for your efforts here 🙏
