### ISSUE TITLE
Switching locale doesn't update field UI based on certain access

### ISSUE THREAD

**Issue by chrisvanmook** [payloadcms/payload#7163]
### Link to reproduction

https://github.com/chrisvanmook/payload/commit/c0be6a12eb7bc17b906f88832253e9d28c0a1fe6

### Payload Version

3.0.0-beta.60

### Node Version

v20.11.1

### Next.js Version

15.0.0-canary.58

### Describe the Bug

When switching locale, and you have an access method (update) that should disable the field based on a language, it doesn't update the UI. Only after a full refresh the expected result is visible (see video).

https://github.com/user-attachments/assets/ed029167-fc44-4016-933e-e93af0486475

### Reproduction Steps

1. Add code in reproduction url
2. Switch from english to NL
3. Note that the field is not disabled
4. Refresh
5. Note that the field is now disabled as it should

### Adapters and Plugins

db-postgres

**Comment by paulpopus** [comment]
This will be fixed in the next beta release!
