### ISSUE TITLE
Search filter in admin panel doesn't reset page number

### ISSUE THREAD

**Issue by jcarloslopez** [payloadcms/payload#7188]
### Payload Version

3.0.0-beta.65

### Node Version

20.11

### Next.js Version

15.0.0-canary.53

### Describe the Bug

I have a collection with a relationship field linked to another collection. In the admin panel, I try to add a filter for that field, but the select element that performs the search doesn't reset the page parameter in the request every time I change something in the field, causing it to miss the results.

https://github.com/user-attachments/assets/c2226e3f-4958-4b07-93c0-af0fdefacaae

### Reproduction Steps

Create one collection with a relationship to another collection
On the admin panel try to filter for that relationship field

**Comment by JarrodMFlesch** [comment]
Fixed with https://github.com/payloadcms/payload/pull/7243
