### ISSUE TITLE
cannot use `rootFeatures` in nested lexical editor (BlocksFeature)

### ISSUE THREAD

**Issue by linobino1** [payloadcms/payload#7193]
### Payload Version

v3.0.0-beta.65

### Node Version

v21.7.1

### Next.js Version

15.0.0-canary.58

### Describe the Bug

When nesting lexical editors via the `BlocksFeature`, the `rootFeatures` argument that is being passed to the nested `lexicalEditor` is empty, whereas the documentation said it should contain the features of the root editor.

https://payloadcms.com/docs/beta/lexical/overview#integrating-new-features

### Reproduction Steps

use this config and the Error will be thrown.

```ts
export default buildConfig({
  editor: lexicalEditor({
    features({ defaultFeatures, rootFeatures }) {
      return [
        ...defaultFeatures,
        BlocksFeature({
          blocks: [
            {
              slug: 'my-block',
              fields: [
                {
                  name: 'content',
                  type: 'richText',
                  editor: lexicalEditor({
                    features({ defaultFeatures, rootFeatures }) {
                      if (!rootFeatures.length) {
                        throw new Error('Root features are empty')
                      }
                      return [
                        ...rootFeatures,
                        BlocksFeature({
                          blocks: [],
                        }),
                      ]
                    },
                  }),
                },
              ],
            },
          ],
        }),
      ]
    },
  }),
  ```

### Adapters and Plugins

richtext-lexical

**Comment by AlessioGr** [comment]
This is expected and effectively an issue with the way your code is structured. Using `rootFeatures` WITHIN the root editor config would infinitely, recursively reference itself. `rootFeatures` being empty here is preventing Node.js from throwing a `Maximum call stack exceeded` error.

**Comment by linobino1** [comment]
I know, but I find it a bit unpractical, it would be nice if above example would work, it's a very common use case. and the docs are a bit misleading:

"If this field is the root richText editor, or if the root richText editor is not a lexical editor, this array will be empty."
-> is it the really the root richText editor or a nested richText editor defined inside the root editor? ...
