### ISSUE TITLE
Filter by ID on a collection not working as expected

### ISSUE THREAD

**Issue by eliuAtFanatics** [payloadcms/payload#7194]
### Describe the Bug

While trying to work with the `useListDrawer` function, I wanted to filter out those documents in the collection based on a list of doc IDs using the `filterOptions` parameter.  However, whether using the `not_in` or `not_equals` operator, the filtering out was not working, ie. just doing nothing.  I worked with @jacobsfletch to try a direct URL query for the filtering, and still nothing happened.  Only when trying a custom field, such as a self-introduced Name field, did the filtering work as intended.

I also tried filtering by ID for a collection in the admin UI directly, and it was broken there too.

@jacobsfletch confirmed on his end that this filtering by ID was broken in Payload 2.x, but works fine in 3.x.  So there is an issue with filtering by ID in Payload 2.x, preventing documents from being filtered out in a ListDrawer specifically.

### To Reproduce

* Open up any collection page
* Open the filters section
* Create a filter with ID as the property, and try any condition to see that the filter doesn't work as expected
* Create a filter with any other property, especially a custom field, and see that the filter does work as expected

### Payload Version

2.21.0

**Comment by JarrodMFlesch** [comment]
Fixed by https://github.com/payloadcms/payload/pull/6773

Just need to update to 2.22.0 or later.
