### ISSUE TITLE
Filter options creates mongodb transaction issue when using atlas mongodb

### ISSUE THREAD

**Issue by andershermansen** [payloadcms/payload#7196]
### Link to reproduction

https://github.com/andershermansen/payload/tree/filter-options-mongodb-transactions-issue

### Payload Version

3.0.0-beta.65

### Node Version

v22.4.0

### Next.js Version

15.0.0-canary.69

### Describe the Bug

When using filter options to restrict which items can be selected on a collection, it will throw exceptions with errors regarding mongodb transactions when reading back/validating. Saving works fine first time, but reading/validating fails.

Note: It works fine using local mongodb setup, the error only occurs when using remote mongodb on mongodb.com

![Skjermbilde_2024-06-26_kl _21 07 13](https://github.com/user-attachments/assets/703d8305-da17-4b5d-98ed-30795c115de6)
![Skjermbilde_2024-06-26_kl _21 07 26](https://github.com/user-attachments/assets/f03dbd34-0e44-46a1-b358-735c5b78974c)

Repro tree: https://github.com/andershermansen/payload/tree/filter-options-mongodb-transactions-issue
Repro tree changes: https://github.com/payloadcms/payload/compare/beta...andershermansen:payload:filter-options-mongodb-transactions-issue

### Reproduction Steps

1. Set up a mongodb instance on mongodb.com
2. Run the repo repository against the new mongodb instance
3. Create entries in Category, some with parent not set and some with.
4. Create a Post, and select a main category and subcategory
5. Save Post
6. See the error appear when reading Post back.

**Comment by andershermansen** [comment]
I had some hopes for this issue when I saw PR #7395 because it disabled transactions for the read only scenario.

And it did fix it. I can not reproduce this scenario anymore with beta 72.

Thanks @DanRibbens !

**Comment by osterkraft** [comment]
Can confirm beta 72 fixed the issue for my case as well!

**Comment by tsemachh** [comment]
For me I still get some of the errors on this version , will open another issue for it
