### ISSUE TITLE
Mutual relationships won't display in both entries

### ISSUE THREAD

**Issue by mo7orh3ad** [payloadcms/payload#72]
# Bug Report

Hi, i followed the given examples in the demo for relationship A and relationship B. I currently have 2 collections having one relationship field each. If i got this right it should be possible to set a mutual relation this way. Now, when i save one entry of collection A ("Profile") with a relation to an entry of collection B ("Meta") it would save and display the relation after reopening the entry int the editor. Doing the same with entry B would save the relation as well (at least according to the record in the db) but it won't get displayed in the relationship field and the API's json response.

## Expected Behavior

The relationship fields should keep the values when re-opening an entry in the editor and return the relation in the API's repsonse.

## Current Behavior
see above.

## Steps to Reproduce
see above.

## Detailed Description

**Relationship field in collection A (Profile)**

```
name: 'relatedMeta', 
type: 'relationship',
label: 'Select related meta entry',
relationTo: ['meta'],
hasMany: false,
access: {
    create: () => true,
    read: () => true,
    update: () => true,
},
```

**Relationship field in collection B (Meta)**

```
name: 'relatedEntry',
label: 'Related entry',
type: 'relationship',
relationTo: ['profiles'],
localized: true,
hasMany: false,
access: {
    create: () => true,
    read: () => true,
    update: () => true,
},
```

**Comment by jmikrut** [comment]
Hi @mo7orh3ad — I have confirmed this bug and it has to do with the fact that this field is localized. We have a few improvements to our localization implementation coming out for issue #71 shortly, and this fix will resolve both this issue and that issue. 

Thank you for logging this! Give us a bit here and we'll have a new version published for you!

**Comment by DanRibbens** [comment]
Everything should be working in v0.2.13 that was just released. Feel free to reopen and let us know if your problem remains after updating.

**Comment by CiprianSpiridon** [comment]
> @DanRibbens @jmikrut Hey guys, i'm running into the same issue in v0.14.0. Should I open a new issue?

I am facing the same issue in v0.15.1

**Comment by CiprianSpiridon** [comment]
@DanRibbens @jmikrut I'm running into the same issue in v1.0.34

**Comment by thgh** [comment]
Would love to see documentation on how to handle relational data that can be queried from both ends.

I'm also looking for an example UI implementation of Organization<--Member-->User.

**Comment by roydigerhund** [comment]
Is there any solution to query/filter a relation on both documents? I have a collection `Articles` which has relationship to the collection `Categories` and I would like to query all categories with a count for the related articles.
