### ISSUE TITLE
Upload collection using storage adapter does not fetch from cloud when deployed

### ISSUE THREAD

**Issue by makunoia** [payloadcms/payload#7200]
### Payload Version

3.0.0-beta.63

### Node Version

v20.14.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug
I used the S3 Storage Adapter. Images properly load locally but break when my app is deployed to Vercel.

### Reproduction Steps
1. create an Asset collection
2. Modify Payload config to use storage adapter

```
 plugins: [
    s3Storage({
      disableLocalStorage: true,
      collections: {
        assets: true,
      },
      bucket: process.env.CLOUDFLARE_BUCKET_NAME || "",
      config: {
        credentials: {
          accessKeyId: process.env.CLOUDFLARE_ACCESS_KEY_ID || "",
          secretAccessKey: process.env.CLOUDFLARE_SECRET_ACCESS_KEY || "",
        },
        region: process.env.CLOUDFLARE_REGION,
        endpoint: `https://${process.env.CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com`,
      },
    }),
  ],
```

3. Use an uploaded image in the app
```
<Image
src={showcaseImage.url}        //  value is /api/assets/file/sample-file.webp,
alt={showcaseImage.alt}
fill />
```

4. Works locally
<img width="1286" alt="image" src="https://github.com/user-attachments/assets/8336bc50-b3ed-4224-813a-7be12e2ec44c">

5. Breaks in my Vercel deployment
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/202571f2-dde9-4dcb-8eec-6b34f121e442">

Notes:
I'm sure my env variables are set up right.

### Adapters and Plugins
S3 Storage Adapter
_No response_

**Comment by makunoia** [comment]
Manage to resolve the issue on my end. Instead of using hooks to modify URLs so my app can point to the correct URL, I tried implementing the S3 Storage Adapter

**Solution**
1. Install and update config to use preferred adapter (in this case an s3 storage)

```
 plugins: [
    s3Storage({
      disableLocalStorage: true,
      collections: {
        assets: true,
      },
      bucket: process.env.CLOUDFLARE_BUCKET_NAME || "",
      config: {
        credentials: {
          accessKeyId: process.env.CLOUDFLARE_ACCESS_KEY_ID || "",
          secretAccessKey: process.env.CLOUDFLARE_SECRET_ACCESS_KEY || "",
        },
        region: process.env.CLOUDFLARE_REGION,
        endpoint: `https://${process.env.CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com`,
      },
    }),
  ],
```

2. Pointing to `/collectionSlug/staticURL/filename` in my app with a storage adapter setup in payload.config automatically makes the app retrieve files from the cloud storage

works as mentioned here: [https://payloadcms.com/docs/beta/upload/storage-adapters#payload-access-control](url)

**Comment by makunoia** [comment]
P.S
I noticed on that page that the words "Vercel Blob adapter" appear under other sections, which might be a result of unchecked copy-paste.

**Comment by makunoia** [comment]
I deployed my app from local to my staging environment, the images are not being fetched from the cloud since I see all images are broken. Am I missing something here?

<img width="603" alt="image" src="https://github.com/user-attachments/assets/088015aa-bf78-49ef-bf61-3659e3c58b32">

**Comment by denolfe** [comment]
Are there errors in terminal or console when the image load is attempted?

**Comment by makunoia** [comment]
I think I've pieced together the issue, it seems that there's a problem with authentication

When logged out of Payload CMS, 
<img width="605" alt="image" src="https://github.com/user-attachments/assets/050e318b-c82d-44d0-b254-44c153f6edff">

I fetched the collection doc with my user API key but the app has trouble accessing the asset with the default link so
the console throws me an error.
_ERROR: Forbidden: You are not allowed to perform this action._

Definitely an issue with authenticating access to the asset during runtime. Any chance you can point me to the right direction?

**Comment by makunoia** [comment]
I saw issue https://github.com/payloadcms/payload/issues/4096
so I worked around the issue by disabling Payload Access Control, Local Storage, and generating a direct URL to my bucket. My app now loads the images directly from there.

```
 s3Storage({
      collections: {
        assets: {
          generateFileURL: ({ filename }) => {
            return `${process.env.CLOUDFLARE_BUCKET_PUBLIC_LINK}/${filename}`;
          },
          disableLocalStorage: true,
          disablePayloadAccessControl: true,
        },
      },
     // ... other config
    }),
```

I'm curious to know whether this is really the way to go since I kinda want to know how to make that auth check work

**Comment by denolfe** [comment]
@makunoia Judging from the errors you were getting, this is likely just a misconfiguring of Payload's access control. I would expect a different error if it were due to your bucket's permission policies.

While your workaround works for public assets, you obviously would not want to use that method if it were private files of some sort.

I don't have anyone else reporting similar issues, and quite a few projects are deployed and working as expected with S3.

Happy to re-open if you have a solid reproduction that I can follow.
