### ISSUE TITLE
Search results entry fields are not updated correctly when collection entry fields are updated across multiple languages

### ISSUE THREAD

**Issue by tiagom-m** [payloadcms/payload#7203]
### Payload Version

beta.63

### Node Version

20 LTS

### Next.js Version

15.0.0-canary.58

### Describe the Bug

When the Search Plugin is enabled for a collection, publishing changes in multiple languages for an entry from that collection do not update the fields for all languages in the respective search entry. 

When changes across languages are published for an entry, only the values for the selected language are stored in the respective search entry. The values for the other languages are not saved in that search entry.

The current beta app (version 63) was used for testing and the following changes were added to the `payload.config.ts`:

- Localization was enabled for English (EN) and French (FR) languages
```ts
localization : {
    locales: ['en','fr'],
    defaultLocale: 'en',
    fallback: true
}
```
- The Search Plugin was enaled for the `pages` collection, and a localized slug field was added
```ts
searchPlugin({
    collection: ['pages'],
    defaultPriorities: {
        pages: 10
    },
    searchOverrides: {
        fields: ({defaultFields}) => [
            ...defaultFields,
            {
                name: 'slug',
                required: false,
                type: 'text',
                localized: true
            },
        ] as Field[]
    },
    beforeSync: ({originalDoc, searchDoc}) => {
        return {
            ...searchDoc,
            slug: originalDoc.slug
        } as DocToSync
    }
})
```

After updating the title and slug fields for a new page for both EN and FR, several issues are visible in the search results entry when those changes are published:

- If the EN language was the one selected when publishing the changes, only the title and slug values for EN are updated correctly. Switching to the FR language reveals that the title remains unchanged (since it's not a localized field) and the slug field appears empty (meaning that the entry slug inFR was not stored). 
- If the slug value is updated again and the FR language is selected before publishing changes, the slug field in the search result entry is updated but the slug field in EN is now empty (meaning that the entry slug in EN was not stored). 
- I think that it would also be beneficial for the title field to the possible to be localized in order to avoid confusion when changing across different languages in the same entry.

I was not able to find a lot of documentation (or a working example) on how to setup the search plugin for multiple locales were it worked properly, so maybe I might be missing some more configurations. 

### Reproduction Steps

- Created a new project with the npx `create-payload-app@beta` command and followed the setup instructions.
- Modified the `payload.config.ts` file to enable localization and the search plugin, as shown above.
- Executed the database migration commands.
- Created a new page with different title and slug values for the FR and EN languages and published the changes, ensuring that the EN language is the one currently active.
- Checked the Search results collection for the search entry for the new page.
- Confirmed that the title and slug values matched those from the page for EN, while the slug value for FR is empty. The title field also does not change between languages.
- Updated again the slug value for the same page but ensured that the FR language was the one active when publishing the changes.
- Checked the search result entry again. The field and slug values matched those from the page in FR, but for EN the title did not changed and the slug value was empty.

### Adapters and Plugins

plugin-search

**Comment by JarrodMFlesch** [comment]
@tiagom-m I think I am following, but could you upload a quick screen capture of this process?

**Comment by mskec** [comment]
I think the problem is in the url linking to a related doc. It doesn't take into an account the current locale of the CMS. 

https://github.com/payloadcms/payload/blob/main/packages/plugin-search/src/Search/ui/index.tsx#L38

**Comment by JarrodMFlesch** [comment]
I can attempt to recreate the search issue you are having. 

One thing to note, when you switch between locales, it does not store your current document data. So I think you were losing it when you switched from FR to EN which made it seem like it was not saving.

If you update to the latest beta, I made a change to make this clearer and it will ask you if you want to leave without saving. Can you try that out and see if it clears up some of the initial confusion you were having?

**Comment by JarrodMFlesch** [comment]
@tiagom-m thank you for the screen recording, this is so helpful. I should have time to look into this today.

**Comment by JarrodMFlesch** [comment]
So to recreate this issue:
- create DRAFT version of `es` doc
- create PUBLISHED version of `en` doc
- the search collection will only have the `en` data

This stems from afterRead hooks only having access to the data of the requested locale. The search plugin allows you to tie into afterRead, but the doc will only have the `en` data. Therefore the search doc will not have access to other localized content when it creates/updates its entry.
