### ISSUE TITLE
Preview broken for localization EN when creating from FR with Postgres

### ISSUE THREAD

**Issue by Rheaparks** [payloadcms/payload#7210]
### Describe the Bug

When I use payload.create() with Postgres
```
      await payload.create({
        collection: collectionSlug,
        data: newPage,
        locale: locale,
      });
```

…with locale FR, it automatically creates a content for the EN version. But the EN version looks like this : 

<img width="1292" alt="Capture d’écran 2024-07-18 à 10 36 18" src="https://github.com/user-attachments/assets/0a9178ad-4078-46c1-af2c-4e106fde344e">

The english line stays empty and there is no way to recognize what content it is.

When I use payload.create() with locale EN, it automatically creates an FR content that looks like this:
<img width="1289" alt="Capture d’écran 2024-07-18 à 10 40 16" src="https://github.com/user-attachments/assets/7ece01cb-2105-4035-bb18-92190c54306f">

The generated french line gets preview title, slug, etc. in english so we can recognize it (but fields inside stay empty). 

### To Reproduce

1. Add content with payload.create() and Postgres with locale : FR
2. Add content with payload.create() and Postgres with locale : EN
They are not treated the same. And the preview is different.

### Payload Version

2.23.1

### Adapters and Plugins

db-postgres

**Comment by JarrodMFlesch** [comment]
@Rheaparks can you provide a reproduction so we can use your config when looking into this. Thanks!

**Comment by paulpopus** [comment]
Closing until theres a reproduction
