### ISSUE TITLE
Cannot publish a single locale and keep other locales in draft

### ISSUE THREAD

**Issue by Rheaparks** [payloadcms/payload#7211]
### Describe the Bug

When we create a content with :
```
payload.create({
        collection: collectionSlug,
        data: newPage,
        locale: locale,
      });
```
it create a content for every locales configured. So far, not amazing, but ok… 

But when I try to **publish** an FR content for example, the EN content will be published too (even if the content is empty and we want to keep it in draft). 
Also, if I want to **delete** the EN content, it will delete the FR content too.

### To Reproduce

1. Configure multiple locales
2. Create a script to add content with payload.create({ locale: locale})
3. Try to publish only one of the locale content OR try to delete only one of the locale content

### Payload Version

2.23.1

### Adapters and Plugins

db-postgres

**Comment by JarrodMFlesch** [comment]
Hey @Rheaparks these are not bugs, what you are asking for would be features that add on to the current state of localization. 

For now you could probably come up with a way to get around this for your use cases. You could try to add 2 checkboxes (localized fields), 1 for localeIsPublished and 1 for localeIsDeleted. And then you could adjust your queries to incorporate those two fields if you would like.

You can follow along and contribute to the discussion we have open here https://github.com/payloadcms/payload/discussions/4195!

We plan to move back over to P1 tasks after v3 is stable.
