### ISSUE TITLE
Toast shows generic message from list view in admin panel

### ISSUE THREAD

**Issue by wrobson-lllow** [payloadcms/payload#7214]
### Describe the Bug

We have a "CustomeAPIError" class used to throw custom error toasts from hooks:
```ts
import {APIError} from "payload/errors";

class CustomAPIError extends APIError {
    constructor(message: string) {
        super(message, 400, undefined, true)
    }
}

export default CustomAPIError
```

These are used mainly for displaying descriptive error messages to the user when deleting records from a collection.  It works as expected when deleting a record from the individual record view.

However, when deleting from the list view the custom error message is not displayed. Instead a generic "Unable to delete n out of n records" is displayed.
![image](https://github.com/user-attachments/assets/20d14ca7-12cf-4d45-9deb-09a869b39862)
![image](https://github.com/user-attachments/assets/5c7e9752-89a6-4238-ac18-528900bfbba7)

### To Reproduce

Throw a CustomAPIError from a beforeDelete hook. 

Currently using v2.22.0 but this has been an issue in all v2 versions.

### Payload Version

2.22.0

### Adapters and Plugins

bundler-webpack, db-mongodb, plugin-cloud, richtext-slate

**Comment by JarrodMFlesch** [comment]
@wrobson-lllow could you throw together a simple reproduction so we can drop in some code to replicate? Will make looking into it a lot easier.

**Comment by wrobson-lllow** [comment]
> @wrobson-lllow could you throw together a simple reproduction so we can drop in some code to replicate? Will make looking into it a lot easier.

Sure thing. Is there a simple starter repo anywhere that I can use?

**Comment by wrobson-lllow** [comment]
[reproduction branch custom-API-error-list-view-bug](https://github.com/wrobson-lllow/payload/tree/custom-API-error-list-view-bug)

One thing I've noticed and wondered about before, is there a reason the beforeDelete hook doesn't include 'doc' in the args object?

**Comment by paulpopus** [comment]
Coming out with a fix for both v2 and v3. In v3 it will look a bit like this and in v2 it will just be appended to the end of the error.

![image](https://github.com/user-attachments/assets/d7f88363-d2e9-4cf7-a7e7-1255a3d252bf)
