### ISSUE TITLE
Changing the cookie prefix prevents login in Next.js standalone mode

### ISSUE THREAD

**Issue by youst-gradiant** [payloadcms/payload#7225]
### Payload Version

65

### Node Version

18.20.3

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Changing the cookie prefix prevents login in Next.js standalone mode

### Reproduction Steps

Changing the cookie prefix prevents login in Next.js standalone mode

**Comment by JarrodMFlesch** [comment]
Closing, stale, no info given when requested. More than happy to re-open if more information is provided.
