### ISSUE TITLE
rowLabel for array field does not return {data, index} attributs

### ISSUE THREAD

**Issue by exoer** [payloadcms/payload#7269]
### Payload Version

3.0.0-beta.65

### Node Version

v22.2.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

In the docs for the Array field type there is an example with
```
...
admin: {
        components: {
          RowLabel: ({ data, index }) => {
            return data?.title || `Slide ${String(index).padStart(2, '0')}`
          },
        },
      },
```

`data` and `index` are undefined

When I do 

```
   {
      name: 'teams',
      type: 'array',
      admin: {
        components: {
          RowLabel: (data: object) => {

            const keys = Object.keys(data)
            return data?.name || `${keys}`
          },
        },
      },
  
      fields: [
        {
          type: 'row',
          fields: [
            {
              name: 'name',
              type: 'text',
            },
            {
              name: 'default',
              type: 'checkbox',
            },
          ],
        },
      ],
    },
```
the `keys` values returned are `label, required, shemaPaht, i18n, payload`. So it appears that `{data, index}` is not in the object returned from the `RowLabel`

### Reproduction Steps

A payload 3.0.0.beta65 project

**Comment by tomekwlod** [comment]
I used to struggle with this as well. Try to separate the RowLabel component from a collection, and put the code into a separate file with 'use client' statement, like so:

```
'use client'

import { useRowLabel } from '@payloadcms/ui'
import { RowLabelComponent } from 'payload'
import React from 'react'

export const TitleRowLabel: RowLabelComponent = () => {
  const { data, rowNumber } = useRowLabel<{ title: string }>()

  return (
    <div>
      [{rowNumber}] {data.title || ''}
    </div>
  )
}
```

Let me know if that helps

**Comment by exoer** [comment]
@tomekwlod Fantastic! It works beautifully. Makes sense now that it needed to be a separate `use client`-component.
