### ISSUE TITLE
Loading admin page with relationship filters ends up in infinite loop

### ISSUE THREAD

**Issue by jcarloslopez** [payloadcms/payload#7271]
### Payload Version

3.0.0-beta.67

### Node Version

20.11

### Next.js Version

15.0.0-canary.53

### Describe the Bug

When loading a page with a filter on a relationship field, it attempts to load the related entity but ends up in an infinite loop trying to fetch it and never filling up the select

### Reproduction Steps

https://github.com/user-attachments/assets/6fcd503c-0120-4c44-b2a0-67288582f6bf

**Comment by akhrarovsaid** [comment]
I have the exact same issue in v2 - [see duplicate issue in v2](https://github.com/payloadcms/payload/issues/7103)

Incredibly frustrating as for many of my collections, the feature to filter on documents with relations is crucial.

**Comment by JarrodMFlesch** [comment]
@jcarloslopez @akhrarovsaid fixes coming in for both issues.
