### ISSUE TITLE
Array field row labels cannot be customized

### ISSUE THREAD

**Issue by jankvapil** [payloadcms/payload#7273]
### Payload Version

3.0.0-beta.63

### Node Version

v22.4.1

### Next.js Version

15.0.0-canary.53

### Describe the Bug

Using docs example: 

https://payloadcms.com/docs/fields/array#example

This example of customizing an array field row label doesn't seem to work

It displays `Slide undefined`

### Reproduction Steps

Just try this example

**Comment by paulpopus** [comment]
In 3.0 you need to provide a custom component for it, like this https://github.com/payloadcms/payload/blob/f1b043ba57ee1ea04189185600b8db7f2cfd7015/templates/ecommerce-3/src/payload/collections/Products/ui/RowLabels/VariantLabel.tsx

Which you can then include in your field

```ts

{
  name: 'variants',
  type: 'array',
  admin: {
    components: {
      RowLabel: VariantLabel,
    },
  },
  fields: []
}
```
