### ISSUE TITLE
unique field property is not working

### ISSUE THREAD

**Issue by llezhava** [payloadcms/payload#7274]
### Describe the Bug

when I am setting `unique: true` on a field property, I expect, that this field will be unique in collection

### To Reproduce

- add field:
```
    {
      name: 'slug',
      label: 'Slug',
      type: 'text',
      required: true,
      unique: true,
    },
```

- add an entry to the database with "slug" set to 'slug-val"
- add another entry with the same value for "slug"
- you will be able to add another entry with the same value

You shall see error message instead.

### Payload Version

2,3

**Comment by DanRibbens** [comment]
The database enforces the unique constraint and this can happen when you have an index on a field, but then change it to a `unique: true`. The db adapter will not remove any existing indexes even if the config has changed. The best way is to connect to your database using MongoDB Compass and then delete the index on the collection or drop the collection entirely if you don't have data you're worried about.
