### ISSUE TITLE
Focal point crop does work differently then expected.

### ISSUE THREAD

**Issue by yobottehg** [payloadcms/payload#7275]
### Payload Version

3.0.0-beta.67

### Node Version

20 LTS

### Next.js Version

15 canary 58

### Describe the Bug

Since the release of https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.67 and the merge of https://github.com/payloadcms/payload/pull/7117 the images are not cropped out of the center anymore but out of the focal point provided.

However this works differently then i expected and also differently then I and my authors know this feature out of other CMS systems (Drupal, Storyblok, ...)

**What payload is doing is the following**

- Given an image collection with a 500 x 500 imageSize
- A user uploads a 5000 x 2000 image
- User sets the focal point to some place
- Payload crops the image exactly at that position +/- imageSize / 2 in all directions. This can result in very bad results (See attached screenshot)

![Bildschirmfoto 2024-07-22 um 16 13 43](https://github.com/user-attachments/assets/2e48e2cd-1661-4961-9313-aa3d05ba9d4a)

**What i would expect as an author and what other CMSs are doing**

- Given an image collection with a 500 x 500 imageSize
- A user uploads a 5000 x 2000 image
- User sets the focal point to some place
- Payload resizes the image to 500 width
- Payload recalculates the focal point position based on the resize
- Payload crops the image based on the new calculated focal point.

--> This will result in a good quality image with the same content which the user would expect to see.

### Reproduction Steps

1. Create an uploads collection with an imageSize which is small
2. Upload a very big image
3. Check the generated derivate of the image which has only very limited content of the original image because it was not resized before cropping.

**Comment by PatrikKozak** [comment]
Hey @yobottehg - thanks for bringing this to our attention - I fully agree with you, we should be resizing the image before applying the focal point.

I'm working on a fix for this right now - we'll have a fix for this merged asap.

**Comment by PatrikKozak** [comment]
This [PR](https://github.com/payloadcms/payload/pull/7277) will fix this issue - just merged.

**Comment by abernh** [comment]
Well, I think I had last week pushed a PR for the same issue (https://github.com/payloadcms/payload/pull/7183) . But without focus on V3. I guess that's not needed anymore after the release of 2.24.1?
