### ISSUE TITLE
Can't build on Netlify because of React issues

### ISSUE THREAD

**Issue by kolyasya** [payloadcms/payload#7280]
### Payload Version

v3 beta

### Node Version

18

### Next.js Version

15 rc.0

### Describe the Bug

I'm just trying to deploy the app after `npx create-payload-app@beta` and getting such error:

<img width="861" alt="image" src="https://github.com/user-attachments/assets/4fd03c70-17b8-4d6d-9916-4f0aa13b160e">

Locally build works if I use `--force` flag.

### Reproduction Steps

Just try to deploy v3 demo app to Netlify

### Adapters and Plugins

db-mongodb

**Comment by AlessioGr** [comment]
![CleanShot 2024-07-22 at 13 27 35](https://github.com/user-attachments/assets/b68c50e9-f1ed-495e-8cc1-5a3ddae48307)

The minimum Next.js version we support is `canary.53` - cannot use `rc.0` with the latest payload.

Once you upgrade that, you might still get peer dependency warnings from React 19. That's normal, I'd either pass `--force` / `--legacy-peer-deps,` or switch to pnpm which is faster, more stable and works out-of-the-box with payload. Nothing we can do about these warnings right now, will have to wait for React 19 stable, and for the other packages to upgrade their peer dependencies.

These warnings (other than the Next.js rc.0 one) can be safely ignored though

**Comment by kolyasya** [comment]
@AlessioGr I haven't installed next by myself. This version (rc.0) is a result of `npx create-payload-app@beta` which I run today.

**Comment by AlessioGr** [comment]
> @AlessioGr I haven't installed next by myself. This version (rc.0) is a result of `npx create-payload-app@beta` which I run today.

Thank you, fixed this in https://github.com/payloadcms/payload/pull/7283! New projects now install the correct next version, if you install them with `npm install --legacy-peer-deps`
