### ISSUE TITLE
hasMany not assignable to field type 'upload'

### ISSUE THREAD

**Issue by mo7orh3ad** [payloadcms/payload#73]
# Bug Report

hasMany does not seem to be assignable to to the field type "upload".

## Expected Behavior

According to the docs (https://payloadcms.com/docs/fields/upload) hasMany should be available for the uploads field.

## Current Behavior

Error: Object literal may only specify known properties, and 'hasMany' does not exist in type 'UploadField'.

## Detailed Description

```
{
    label: 'Gallery',
    name: 'gallery',
    type: 'group',
    fields: [
        {
            label: 'Add images',
            name: 'galleryImage',
            type: 'upload',
            relationTo: 'gallery-images',
            hasMany: true,
        } 
    ]
}, 
```

**Comment by jmikrut** [comment]
Hey @mo7orh3ad — this is actually just an error with the docs. Uploads are not meant to support multiple, but this could potentially be a future enhancement if you would find value out of it.

If you want to support multiple uploads, you could nest an `upload` field within an `array` field and that would also do the trick. That's what we do when we need data like sliders of images, galleries, etc. 

Thoughts?

**Comment by mo7orh3ad** [comment]
Hi @jmikrut, thanks for getting back - using an array field would have been my next approach. I agree, it would be great if this enhancement would find its way into a future release.

**Comment by jmikrut** [comment]
Docs have been updated. We'll keep this one open for now until we publish our roadmap—at which time we will be moving all enhancement issues to the Roadmap instead of tracking them here.
