### ISSUE TITLE
Unable to install live-preview-vue

### ISSUE THREAD

**Issue by PhantasWeng** [payloadcms/payload#7303]
# Documentation Issue
According to the description on `https://payloadcms.com/docs/live-preview/frontend`, to use the live preview feature, you need to first install `@payloadcms/live-preview-vue`. However, this package is not available in the [npmjs registry](https://www.npmjs.com/~payloadjs).

## Additional Details

``` bash
➜  app npm install @payloadcms/live-preview-vue
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@payloadcms%2flive-preview-vue - Not found
npm error 404
npm error 404  '@payloadcms/live-preview-vue@*' is not in this registry.
```

**Comment by jacobsfletch** [comment]
Thanks for bringing this up @PhantasWeng 👍 looks like we just need to publish that package. In the meantime, you could paste the source code directly into your own app: https://github.com/payloadcms/payload/tree/main/packages/live-preview-vue

**Comment by jacobsfletch** [comment]
Hey @PhantasWeng a canary has just been published for this package 👍 you can now download this through the NPM registry: https://www.npmjs.com/package/@payloadcms/live-preview-vue. I also have an open PR which will get this into the regular release schedule.
