### ISSUE TITLE
Default values from field config not being set on DB schema in postgres

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload#7350]
### Payload Version

3.0.0-beta.67

### Node Version

20.13.1

### Next.js Version

15.0.0-canary.63

### Describe the Bug

When creating a checkbox field in payload 3.0 default values are not respected. 

The field config:

```js
{
	type: "checkbox",
	name: "active",
	defaultValue: true,
	required: true,
}
```

The message shown when attempting to push the schema change:

> ✖ Warnings detected during schema push: 
> 
> · You're about to set not-null constraint to active column without default, which contains 37 items
> 
> DATA LOSS WARNING: Possible data loss detected if schema is pushed.

### Reproduction Steps

1. Create a checkbox field with a default value
2. The default value will not be respected when creating records in the DB

### Adapters and Plugins

db-postgres

**Comment by paulpopus** [comment]
I think this is particular issue is related to postgres. The payload UI functionality correctly sets default values but we're not setting default values in the DB schema. I'll update the title and then see what we can do here

**Comment by r1tsuu** [comment]
> I think this is particular issue is related to postgres. The payload UI functionality correctly sets default values but we're not setting default values in the DB schema. I'll update the title and then see what we can do here

There's a PR for it from me https://github.com/payloadcms/payload/pull/6983 and as well 2 discussions already https://github.com/payloadcms/payload/discussions/6691 https://github.com/payloadcms/payload/discussions/6048

**Comment by paulpopus** [comment]
> > I think this is particular issue is related to postgres. The payload UI functionality correctly sets default values but we're not setting default values in the DB schema. I'll update the title and then see what we can do here
> 
> There's a PR for it from me #6983 and as well 2 discussions already #6691 #6048

Thanks for those resources, I knew we covered this topic somewhere!

I'll close this ticket and if you have any further thoughts or feedback @mcornielje090404 we can track that in these discussions
