### ISSUE TITLE
Hooks hanging indefinitely on create operation to collection with relation back to triggering collection

### ISSUE THREAD

**Issue by mcornielje090404** [payloadcms/payload#7352]
### Link to reproduction

https://github.com/mcornielje090404/payload-3.0-demo/tree/main

### Payload Version

3.0.0-beta.67

### Node Version

20.13.1

### Next.js Version

15.0.0-canary.58

### Describe the Bug

When attempting to run a payload "create" operation from within a hook on a collection that has a relation *back* to the original collection calling the hook the create operation hangs indefinitely. 

If I remove the relation back to "posts" on the "posts-audits" collection in that repo the hook will run fine.

### Reproduction Steps

1. Spin up the repo linked
2. Create a post
3. The hook only runs on update so the initial creation will run fine
4. Update the same post
5. The hook will hang indefinitely at the create operation

Note: I have sometimes noticed the record is created but the promise never resolves. 

### Adapters and Plugins

db-postgres

**Comment by mcornielje090404** [comment]
I believe #6459 is related (an issue I previously raised) but I hadn't narrowed down the cause of the issue to being relations back to the triggering collection.

**Comment by mcornielje090404** [comment]
I also suspect this happens on update operations

**Comment by jmikrut** [comment]
@JessChowdhury — please try and reproduce this with the example repo above - at first glance I suspected that this was an infinite loop caused by hook recursion but it does not appear to be so after looking at the code.

Not sure what exactly is causing this but it should be relatively easy to spot once you have this pulled up and reproducing reliably.

**Comment by JarrodMFlesch** [comment]
@mcornielje090404 does it finish if you pass the `req` through to your second payload.create operation?

**Comment by JarrodMFlesch** [comment]
@mcornielje090404 yeah, you just need to thread the `req` through as I did in the example above, tested and it updated as expected without hanging.
