### ISSUE TITLE
Mismatching payload dependency versions found: payload@3.0.0-beta.68, @payloadcms/plugin-sentry@0.0.6

### ISSUE THREAD

**Issue by italodr** [payloadcms/payload#7353]
### Link to reproduction

https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md

### Payload Version

3.0.0-beta.68

### Node Version

v20.12.2

### Next.js Version

15.0.0-canary.53

### Describe the Bug

I cannot use the [reproduction-guide](https://github.com/payloadcms/payload/blob/beta/.github/reproduction-guide.md) to reproduce an error —without, manually, changing the plugin version. Even though I'm not using this plugin on my code.
The version of @payloadcms/plugin-sentry (0.0.6) is not updated to the new beta version (3.0.0-beta.68).

### Reproduction Steps

Follow the steps below. Change your branch to `beta`

https://github.com/payloadcms/payload/blob/beta/.github/reproduction-guide.md

**Comment by tsemachh** [comment]
I am not sure it passed Unit Test , this is the checked list:
`      const resolvedDependencies = await getDependencies(dirname, [
        '@payloadcms/ui/shared',
        'payload',
        '@payloadcms/next/utilities',
        '@payloadcms/richtext-lexical',
        '@payloadcms/richtext-slate',
        '@payloadcms/graphql',
        '@payloadcms/plugin-cloud',
        '@payloadcms/db-mongodb',
        '@payloadcms/db-postgres',
        '@payloadcms/plugin-form-builder',
        '@payloadcms/plugin-nested-docs',
        '@payloadcms/plugin-seo',
        '@payloadcms/plugin-search',
        '@payloadcms/plugin-cloud-storage',
        '@payloadcms/plugin-stripe',
        '@payloadcms/plugin-zapier',
        '@payloadcms/plugin-redirects',
        '@payloadcms/plugin-sentry',
        '@payloadcms/bundler-webpack',
        '@payloadcms/bundler-vite',
        '@payloadcms/live-preview',
        '@payloadcms/live-preview-react',
        '@payloadcms/translations',
        '@payloadcms/email-nodemailer',
        '@payloadcms/email-resend',
        '@payloadcms/storage-azure',
        '@payloadcms/storage-s3',
        '@payloadcms/storage-gcs',
        '@payloadcms/storage-vercel-blob',
        '@payloadcms/storage-uploadthing',
      ])
`
You need to make sure that you have only packages with published beta versions

**Comment by tsemachh** [comment]
@jmikrut - As a temp workaround can you please just update:
**_packages/plugin-stripe/package.json_**
To have the version :
**`"version": "3.0.0-beta.71",`**
So we will have at least 1 version which can work with sentry

**Comment by tsemachh** [comment]
@jmikrut  - sorry I see the plugin is not upgraded to use next.js it still works with express , will integrate directly using next.js integration they have there

**Comment by paulpopus** [comment]
Hi @tsemachh , this plugin will not be updated for v3 because Sentry has a direct to Nextjs integration https://docs.sentry.io/platforms/javascript/guides/nextjs/ that's now the recommended way to be setup.
