### ISSUE TITLE
Integer field (e.g. ID) with contains filter on postgres breaks/crashes the application completely. 

### ISSUE THREAD

**Issue by chinmay-mehta** [payloadcms/payload#7354]
### Payload Version

3.0.0-beta.43

### Node Version

v20.13.1

### Next.js Version

^14.3.0-canary.28

### Describe the Bug

1. On selecting any integer field and applying the contains filter on that breaks the app when using postgres db. It works well with Mongo as the ids are a string.
2. Also, there is no provision to hide the auto-generated fields from the filter using the disableListFilter which we can use to remove the column from being selected into the filter.  

### Reproduction Steps

1. Navigate to any collection
2. Click on the filter -> add filter
3. Add and integer column (e.x.: ID) -> select contains -> add a value 
4. Application crashes

![bug](https://github.com/user-attachments/assets/f22b5ecc-d531-4638-a854-552aaa334fd5)

### Adapters and Plugins

"@payloadcms/db-postgres": "3.0.0-beta.43"

**Comment by chinmay-mehta** [comment]
@PatrikKozak  any updates on this?

**Comment by PatrikKozak** [comment]
Hey @chinmay-mehta - We are looking into this, we'll get a fix out for this asap

**Comment by chinmay-mehta** [comment]
Hey @PatrikKozak  - Thanks a lot for the prompt action!

**Comment by PatrikKozak** [comment]
Fixed with #7416
