### ISSUE TITLE
Lexical editor RelationshipFeature ignoring enabledCollections and disabledCollections

### ISSUE THREAD

**Issue by gigaSproule** [payloadcms/payload#7379]
### Payload Version

3.0.0-68

### Node Version

v20.12.2

### Next.js Version

15.0.0-canary.53

### Describe the Bug

I'm trying to filter down what collections can be used in a rich text field. I have set the `RealtionshipFeature` to have `enabledCollections` and I've also tried `disabledCollections`, but neither seems to be applied.

For example, I've tried `RelationshipFeature({ enabledCollections: ['link'] })` and `RelationshipFeature({ disabledCollections: ['users'] })`, but in both cases, I'm seeing `users` as a valid collection to use. `link` in this context is a custom collection, not anything built in.

I can disable collections globally, by setting `admin.enableRichTextRelationship` to `false`, but I can't do it on a per field level.

I tried debugging the `RealtionshipFeature` and it's corresponding `RelationshipFeatureClient`, but only the server feature seems to have the `enableCollections` or `disableCollections` props available.

### Reproduction Steps

1. Create a collection
2. Create another collection with a lexical rich text field
3. Configure the rich text field to have the `RelationshipFeature` with either `enabledCollections` or `disabledCollections` defined blocking the collection created in step 1
    1. e.g. `editor: lexicalEditor({features: () => [RelationshipFeature({enabledCollections: ['users']})]})`
4. Load up the admin UI and try to create a relationship to the collection created in step 1
    1. You should be able to, which is obviously not what is wanted

### Adapters and Plugins

db-mongodb, richtext-lexical

**Comment by gigaSproule** [comment]
Just to add to this, I've tried using a different collection other than `link`, in case something was conflicting with it and it still doesn't work. I also checked the `LinkFeature`, to see if it was a wider issue, but the `LinkFeature` is working perfectly fine.

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/7926
