### ISSUE TITLE
Wrong validation of Password field & New Password should be matched with Confirm Password before creating a new User in Payload

### ISSUE THREAD

**Issue by RiteshMRI** [payloadcms/payload#7380]
### Payload Version

3.0.0-beta.68

### Node Version

v20.15.0

### Next.js Version

15.0.0-canary.53

### Describe the Bug

I am facing some issues regarding to the New Password & Confirm Password while creating new user in Payload Version 3.0.0-beta.68. Issues are mentioned as below.

1) When I enter email and leave both New Password & Confirm Password fields blank, it will show a validation error on "Confirm Password" field rather than showing it on "New Password" field.

2) Once I enter password in New Password field and again leave the Confirm Password field blank and click on "save" button at that time it will save the user without comparison of "New Password" & "Confirm Password".  And it will show "user successfully created."

### Reproduction Steps

**For Issue 1:**

1) Open the User Collection
2) Click on 'Create New" at the top 
3) Creating new User" screen will be opened.
4) Now Enter email and leave both New Password & Confirm Password fields blank, it will show a validation error on "Confirm Password" field rather than showing it on "New Password" field.
5)  It will show a validation error on "Confirm Password" field rather than showing it on "New Password" field.

This issue is shown in below screenshot.

![user_bug_screenshot1](https://github.com/user-attachments/assets/1b2f1985-848c-4378-bd7e-3e6f716c891c)

**For Issue 2:**

1) Open the User Collection
2) Click on 'Create New" at the top 
3) Creating new User" screen will be opened.
4) Now Enter email and New Password. But leave Confirm Password field blank. and click on "save" button as shown in below screenshot 1.
5) It will save the user without comparison of "New Password" & "Confirm Password".  And it will show "user successfully created." message as shown in below screenshot 2

![user_bug_screenshot2](https://github.com/user-attachments/assets/bdb9abc9-bbbf-4d07-994d-0e6c75b322f4)
![user_bug_screenshot3](https://github.com/user-attachments/assets/e0e384fa-3ce7-4f9e-b304-de89678c896b)

**Comment by JarrodMFlesch** [comment]
Was able to replicate the second issue, but not the first one. Looking into it.

**Comment by RiteshMRI** [comment]
Thanks

**Comment by JarrodMFlesch** [comment]
Will be fixed in next beta release. Thanks for reporting!

**Comment by RiteshMRI** [comment]
Any Solution ?

Any Update ?

**Comment by carlcs** [comment]
Solution is to update to latest beta.

**Comment by RiteshMRI** [comment]
Thanks
