### ISSUE TITLE
Data missing from version comparison when using localization

### ISSUE THREAD

**Issue by JessChowdhury** [payloadcms/payload#7381]
### Link to reproduction

https://github.com/justcoding9/versioning-payload

### Payload Version

v3.0.0-beta.69

### Node Version

v20.4.0

### Next.js Version

15.0.0-canary.53

### Describe the Bug

Version comparison displays no data when localization is enabled. Reported in Discord [here](https://discord.com/channels/967097582721572934/1255948668729692281). 

![Screenshot_2024-07-22_at_11 50 10_PM](https://github.com/user-attachments/assets/8a0db553-a984-4bb1-834a-41cf85a72100)

### Reproduction Steps

Use repo provided

**Comment by ars3nicum** [comment]
same here

**Comment by pmeske** [comment]
I have the same Issue on 2.23.1 and 2.25.0.
