### ISSUE TITLE
Locale switching in collection missing ?locale for the documents

### ISSUE THREAD

**Issue by ars3nicum** [payloadcms/payload#7407]
### Payload Version

3.0.0-beta.70

### Node Version

22.5.1

### Next.js Version

15.0.0-canary.87

### Describe the Bug

Locale selection resets to default when clicking to a document from a collection view with a non-default locale chosen

### Reproduction Steps

- Open a collection (will be default locale in locale switcher)
- Change locale to a non-default - you get a list with a chosen locale and in Url appends ?locale=some
- Click any document - you go to a page editing a default locale, not a chosen one, and in Url ?locale is missing

### Adapters and Plugins

db-postgres

**Comment by JarrodMFlesch** [comment]
I was unable to recreate your issue. Yes the url does not always have the locale in it, the pages are served initially from the server which knows the locale of the user bc it is stored in preferences. So when the page loads it loads with the one stored in prefs and falls back to the default locale. 

What locale is set for your user in your preferences table in PG?

https://github.com/user-attachments/assets/0ea92877-9d29-49ee-86e1-19aa600c44cb
