### ISSUE TITLE
Email Missing in Drawer

### ISSUE THREAD

**Issue by tobiasiv** [payloadcms/payload#7428]
### Payload Version

3.0.0-beta.71

### Node Version

v20.9.0

### Next.js Version

15.0.0-canary.77

### Describe the Bug

When editing a related document within a drawer, if a relationship field has auth set to `true`, the email is missing and an error appears: `TypeError: Cannot read properties of undefined (reading 'length')`

### Reproduction Steps

1. Clone the [payload 3.0 demo](https://github.com/payloadcms/payload-3.0-demo)
2. Add a user relationship field to the pages collection:

```js
    {
      slug: 'pages',
      admin: {
        useAsTitle: 'title',
      },
      fields: [
        {
          name: 'title',
          type: 'text',
        },
        {
          name: 'content',
          type: 'richText',
        },
        {
          name: 'user',
          type: 'relationship',
          relationTo: 'users',
        },
      ],
    },
```
3. Run `pnpm dev`
4. Select a user within the pages document
5. Open the drawer to edit the user
6. The user’s email is missing and the error appears in the console

**Comment by JarrodMFlesch** [comment]
Will be fixed in next beta release by https://github.com/payloadcms/payload/pull/7520
