### ISSUE TITLE
Where string is carried over when navigating from one collection to another

### ISSUE THREAD

**Issue by chelaru-artur** [payloadcms/payload#7431]
### Payload Version

3.0.0-beta.71

### Node Version

20.16.0

### Next.js Version

15.0.0-canary.53

### Describe the Bug

Often  when you use filter some data using ui filter in one collection and after navigate through navbar to another collection the 'where' queryString is applied to the navigated collection.

### Reproduction Steps

Create a blank payload v3 application ( or use any v3 that has two collections)

1.  Go to collection No. 1
2. Apply filter to any field
3. Go to collection  No. 2
4. Apply filter to any field
5. Go to collection  No. 1
6. Check the query string in url bar.

![media_filter](https://github.com/user-attachments/assets/20b2a4c0-5699-43c9-a8d6-e6077fae679a)
![users_filter](https://github.com/user-attachments/assets/6af23e1a-6373-4b3d-ac63-be7b3e12ddf3)
![media_after_user_filter](https://github.com/user-attachments/assets/44f5d33a-b6c6-4958-9ab7-46a41d418ea8)

**Comment by paulpopus** [comment]
Going to track this in the original issue here: https://github.com/payloadcms/payload/issues/7085

@chelaru-artur if you can provide a reproduction there it would be really appreciated since I've not been able to reproduce this

**Comment by chelaru-artur** [comment]
> Going to track this in the original issue here: #7085
> 
> @chelaru-artur if you can provide a reproduction there it would be really appreciated since I've not been able to reproduce this

Hello @paulpopus  due to corporate policy I am not able to run playwright to write an e2e test.
But repro steps that I've described in the issue are reproducing the problem. I have testes on my app, on a new blank app and also in  the app from _/test/_community_ folder.

**Comment by paulpopus** [comment]
@chelaru-artur Did you clear your node_modules, nextjs and any other cache? This issue remains not reproducible for me on the latest beta

**Comment by paulpopus** [comment]
I was just shown a reproduction on this, will work on a fix

**Comment by chelaru-artur** [comment]
@paulpopus Hello, any news on this one?
