### ISSUE TITLE
Favicon not generating correctly in admin dashboard

### ISSUE THREAD

**Issue by nlvogel** [payloadcms/payload#7441]
### Payload Version

beta.71

### Node Version

22.0.0

### Next.js Version

15.0.0-canary.59

### Describe the Bug

I'm unable to get my favicon to overwrite the default Payload favicons. I've tried both a URL from Cloudflare R2 (which has worked before and is my preference) and a relative path, shown below. The code below was copied from an earlier example, which seems to work for some.

```
meta: {
      titleSuffix: '...',
      description: '...',
      icons: [
        {
          url: '/graphics/cropped-Untitled-2-01.png',
        },
      ],
...
}
```

I've attached images to the relevant file path and the results I see in `<head>`. 

![image](https://github.com/user-attachments/assets/ce68b73f-f7de-4e61-9ead-08998bb0e7c9)

![image](https://github.com/user-attachments/assets/f65588db-6780-4dc4-9338-d9cd0b47937c)

### Reproduction Steps

The issue is produced when using `admin.meta.icons` as prescribed here: https://github.com/payloadcms/payload/commit/8e56328?diff=unified&w=0

**Comment by jacobsfletch** [comment]
@nlvogel looks like you need to add `rel: 'link'` to your icon config. Here's an example from our test suite: https://github.com/payloadcms/payload/blob/beta/test/admin/config.ts#L94

**Comment by nlvogel** [comment]
@jacobsfletch this didn't work for me. First, wouldn't favicon _need_ to be `rel: 'icon'`? Even so, I tried `rel: 'link'`, and it didn't work Second, `rel="icon"` is the default as my original `<head>` screenshot shows, and that matches the PayloadCMS favicons. Third, putting that all together in the `meta.icons` config, I still can't overwrite Payload's favicon. I even tried using the same method in the test config you linked (importing my image and using .src).

Filling in all fields other than `color` and `media` doesn't work

```
icons: [
        {
          fetchPriority: 'high',
          url: '/graphics/cropped-Untitled-2-01.png',
          sizes: '32x32',
          type: 'image/png',
          rel: 'icon',
        },
      ],
```

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/b6a3a643-79be-48c5-a1b1-1a8862708b3a">


Using `rel: 'link'` doesn't work:

```
icons: [
        {
          url: '/graphics/cropped-Untitled-2-01.png',
          rel: 'link',
        },
      ],
```
<img width="1038" alt="image" src="https://github.com/user-attachments/assets/b73f20ab-dc0c-4c0c-b6e8-77b89333fdea">


Importing the image and using .src doesn't work

```
import { default as favicon } from './public/graphics/cropped-Untitled-2-01.png'

...

icons: [
        {
          url: favicon.src,
          rel: 'icon',
        },
      ],
```

<img width="1087" alt="image" src="https://github.com/user-attachments/assets/f40409f2-4c44-4ba2-9ab3-c76a19a0409c">

And just to make sure, I checked that localhost:3000/graphics/cropped-Untitled-2-01.png was a valid path - it is.

**Comment by jacobsfletch** [comment]
Yes @nlvogel I misspoke on that, it's `rel: 'icon'` just as the linked example shows:

```ts
{
  type: 'image/png',
  rel: 'icon',
  url: '/path-to-icon',
},
```

If payload detects an `icons` array in your config, it merges them with the one that payload provides. If the Payload favicons are taking precedence over your own, you likely need to add more specificity to your config so that the browser chooses yours over the others, i.e. `media`, `sizes`, etc.

**Comment by nlvogel** [comment]
@jacobsfletch using every field available to me in my Payload config still doesn't give me enough specificity to cause the browser to choose my favicon:

```
icons: [
        {
          fetchPriority: 'high',
          url: favicon.src,
          sizes: '32x32',
          media: '(prefers-color-scheme: light)',
          color: 'red',
          type: 'image/png',
          rel: 'icon',
        },
      ],
```

<img width="1240" alt="image" src="https://github.com/user-attachments/assets/6946847f-0cba-4cab-9ba1-7499dd0b7e37">

Changing the image name to include -favicon also doesn't work. Is there a way for me to disable the Payload favicons instead of trying to overwrite them?

**Comment by jacobsfletch** [comment]
Ok thanks for your patience on this one @nlvogel, I'm going to re-open this issue now and we'll take a closer look

**Comment by JessChowdhury** [comment]
Hi @nlvogel - this issue has been resolved [here](https://github.com/payloadcms/payload/pull/7466) and will go out in the next release.

**Comment by JarrodMFlesch** [comment]
Related PR https://github.com/payloadcms/payload/pull/7466
