### ISSUE TITLE
admin memory leak after beta.68

### ISSUE THREAD

**Issue by WilsonLe** [payloadcms/payload#7443]
### Link to reproduction

https://github.com/WilsonLe/payload-reproduce/tree/1-payload-admin-freeze

This commit breaks things: cb1cd51e5d3f75d615b168c6fc2871e4af0ae3ed
This commit works: 431f007f0775e16560e24b2de571e0b938f2a0cb

### Payload Version

beta.68

### Node Version

20

### Next.js Version

canary.67

### Describe the Bug

Couple of observation leading to this bug:
- Using `3.0.0-beta.68` works fine
- `3.0.0-beta.69` doesn't build due to a bug that was fixed in `3.0.0-beta.70` (https://github.com/payloadcms/payload/pull/7383)
- `3.0.0-beta.70` doesn't build due to a bug that was fixed in `3.0.0-beta.71` (https://github.com/payloadcms/payload/pull/7403)
- `3.0.0-beta.71`  builds fine, but when I open `/admin` causes the following error (keep in mind that I have already increase memory allocation to 16GB).

```sh
<--- Last few GCs --->

[1100057:0x6b660d0]   134603 ms: Mark-Compact 15935.5 (16231.8) -> 15925.5 (16236.8) MB, 2146.96 / 0.00 ms  (average mu = 0.599, current mu = 0.007) allocation failure; scavenge might not succeed
[1100057:0x6b660d0]   138738 ms: Mark-Compact 15941.3 (16236.8) -> 15931.2 (16242.6) MB, 4113.88 / 0.00 ms  (average mu = 0.329, current mu = 0.005) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xb80c98 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [next-server (v15.0.0-canary.67)]
 2: 0xeede90 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [next-server (v15.0.0-canary.67)]
 3: 0xeee177 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [next-server (v15.0.0-canary.67)]
 4: 0x10ffd15  [next-server (v15.0.0-canary.67)]
 5: 0x1117b98 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [next-server (v15.0.0-canary.67)]
 6: 0x10edcb1 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [next-server (v15.0.0-canary.67)]
...
Aborted
```

### Reproduction Steps

Existing project that works on `beta.68` no longer works when upgrading to `beta.71`.

**Comment by jmikrut** [comment]
Hey @WilsonLe I have a sneaking suspicion that this is related to the Next.js canary that we shipped with beta 71 but we will do some digging and report back. Thanks for the report! 👍

**Comment by WilsonLe** [comment]
No, still got heap limit allocation failed (canary 53 and canary 94)

**Comment by WilsonLe** [comment]
next@15.0.0-rc.0 is also not working.

**Comment by jmikrut** [comment]
OK - is it possible that you could provide us with a minimal reproduction? There is little that we can do to test this without being able to reproduce, unfortunately. Going to keep poking around, but it would dramatically expedite this process if we could see how you are reproducing this issue.

**Comment by WilsonLe** [comment]
https://github.com/WilsonLe/payload-reproduce/tree/1-payload-admin-freeze

This commit breaks things: cb1cd51e5d3f75d615b168c6fc2871e4af0ae3ed
This commit works: 431f007f0775e16560e24b2de571e0b938f2a0cb

**Comment by jmikrut** [comment]
Hey @WilsonLe — we've cloned down your repo and discovered the culprit. Working on a fix now. Thank you for the reproduction! Made everything easy to spot the issue.

**Comment by jmikrut** [comment]
OK - this should now be resolved with the most recent beta. We are actually going to be doing _more_ here as well, to reduce overall memory consumption and initial html size, but this was indeed a result of a bug which should now be resolved. Can you update and give it a shot? If you still have issues, I'll re-open!

**Comment by WilsonLe** [comment]
It works now, arguably faster too! Thank you!
