### ISSUE TITLE
Searching in a collection and navigating to another collection adds the search value to the new collection

### ISSUE THREAD

**Issue by BhargavSuthar99** [payloadcms/payload#7445]
### Payload Version

beta v68

### Node Version

20.12.5

### Next.js Version

15.0.0-canary.53

### Describe the Bug

Issue has been fixed with [v3.0.0-beta.66](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.66) but I'm still facing this issue with 3.0.0-beta.68 version.

Reference: [7085](https://github.com/payloadcms/payload/issues/7085)

https://github.com/user-attachments/assets/315a1473-8c94-4a62-9e72-ee37df24c720

### Reproduction Steps

Open up a collection, in the bar "Search by name" search for something, navigate to another collection.

**Comment by paulpopus** [comment]
Tracking this issue in https://github.com/payloadcms/payload/issues/7431
