### ISSUE TITLE
Can't Filter for Boolean Fields (in German)

### ISSUE THREAD

**Issue by tobiasiv** [payloadcms/payload#7447]
### Payload Version

3.0.0-beta.71

### Node Version

v20.9.0

### Next.js Version

15.0.0-canary.77

### Describe the Bug

When filtering for a boolean field in German (and possibly other non-English languages), the filter either returns an error `Error: invalid input syntax for type boolean: "Wahr"` or produces incorrect filter results.

### Reproduction Steps

1) Clone the [payload 3.0 demo](https://github.com/payloadcms/payload-3.0-demo)
2) Add German to supported languages:

```js
  i18n: {
    supportedLanguages: { en, de },
  }
```

3) Add new collection with checkbox field:

```js
    {
      slug: 'test',
      fields: [{ name: 'isChecked', type: 'checkbox' }],
    },
```

4) Run `pnpm dev`
5) Create test documents with isChecked set to `true` and `false`
6) Try to filter the isChecked field
7) Either an error occur or the filter results are incorrect

**Comment by paulpopus** [comment]
This will be fixed in the next release, thanks for the report!
