### ISSUE TITLE
UI/UX issue when searching for an option in a multi relationship field

### ISSUE THREAD

**Issue by radudevit** [payloadcms/payload#7452]
### Payload Version

3.0.0-beta-71

### Node Version

20.15.1

### Next.js Version

15.0.0-canary.53

### Describe the Bug

There is an UI/UX issue when searching for an option in a relatationship field, with hasMany property set to true.

### Reproduction Steps

1. Create a relationship field with the hasMany property set to true.
2. Select an option from the available list.
3. Search for another option (fill in some text in the select element).
4. While the data is being fetched from the database, the selected option dissapears, the dropdown section is hidden, and after that they appear back.

This is looking weird.

**Comment by jacobsfletch** [comment]
Hey @radudevit thanks for reporting on this one, should be fixed with #8063.
