### ISSUE TITLE
Confirm Password Field is Ignored

### ISSUE THREAD

**Issue by tobiasiv** [payloadcms/payload#7461]
### Payload Version

3.0.0-beta.71

### Node Version

v20.9.0

### Next.js Version

15.0.0-canary.77

### Describe the Bug

It is possible to create a new user without confirming the password

### Reproduction Steps

1) Clone the [payload 3.0 demo](https://github.com/payloadcms/payload-3.0-demo)
2) Run `pnpm dev`
3) Create a new user by filling in only the email and new password fields
4) Save the document
5) No error message appears when the confirm password field is left empty

**Comment by JarrodMFlesch** [comment]
This will be fixed in the next beta release.

Fixed in https://github.com/payloadcms/payload/pull/7480
