### ISSUE TITLE
zlib: unexpected end of file

### ISSUE THREAD

**Issue by devmoatassem** [payloadcms/payload#7463]
### Payload Version

Latest Beta

### Node Version

20.x

### Next.js Version

14.2

### Describe the Bug

Getting the` zlib: unexpected end of file` Error no matter how I try to create a payload project
I have tried adding it to existing next.js project
Creating new blank project
Creating new website template project. I've always got the same error. 
Please note I have tried after cleaning the cache it still gives the same error.

![image](https://github.com/user-attachments/assets/0655d34e-8762-4f4a-a7b8-37b1c12cfbf6)

### Reproduction Steps

 npx create-payload-app@beta

**Comment by denolfe** [comment]
Related to degit's issue here: https://github.com/Rich-Harris/degit/issues/313

The workaround until this is resolved is to delete the `.degit` directory in your home directory. Depending on your operating system this will likely be `~/.degit` or something like `C:/Users/username/.degit`.

**Comment by devmoatassem** [comment]
It solved the earlier error, but I still can't add it to an existing Next.js project.
It doesn't even detect the existing Next.js project.
![image](https://github.com/user-attachments/assets/81f65c16-59ad-4de3-93bc-16fd639d2f53)
