### ISSUE TITLE
Original image not preserved when imageSizes key is set (filesize difference)

### ISSUE THREAD

**Issue by sdjnes** [payloadcms/payload#7465]
### Link to reproduction

https://github.com/sdjnes/payload-png-bug

### Describe the Bug

An Upload collection that accepts images does not preserve the original image when `imageSizes` key is present, even when `formatOptions` is not set.

Sometimes file size is larger when uploaded, other times smaller

This is most apparent with PNGs because the file sizes seem to vary a lot. This also occurs with JPEGs, but the filesize difference is minimal.

Without imageSize key (size is correct)
![image](https://github.com/user-attachments/assets/b5420c8f-fe89-4004-b0d6-323ae45c9efb)

With imageSize key (size is incorrect in Payload)
![image](https://github.com/user-attachments/assets/fde04733-5cd8-4d0b-8b4b-9dbd915b2da9)

**Payload is not misreporting the filesize** - the original image has been modified. If you download, it indeed has the 895KB filesize.

### To Reproduce

* Create a collection with upload enabled
* Allow upload of images/*
* Do not set a key/value for `imageSizes` property
* Upload an image (PNG seems to show the most variance) 
* Observe the correct file size (comparing from your filesystem to the uploaded file size)
* Set the imageSizes key/value to anything (I used `imageSizes: []`)
* Upload the same image as before
* Observe the incorrect file size on the uploaded image

### Payload Version

Observed on 2.22 and 2.25

### Adapters and Plugins

None

**Comment by JarrodMFlesch** [comment]
Here is a sample image for testing - leaving this here for the team.

![sample-image](https://github.com/user-attachments/assets/bb016bf8-7709-414c-9495-4596c7cd6b00)
