### ISSUE TITLE
Lexical Richtext LinkFeature prevents valid URLs

### ISSUE THREAD

**Issue by smoores-dev** [payloadcms/payload#7477]
### Payload Version

3.0.0-beta.68

### Node Version

20.12.2

### Next.js Version

15.0.0-canary.76

### Describe the Bug

When adding a link to text in a Lexical editor field, using the built-in LinkFeature, relative URLs with query strings are considered invalid. e.g. `/donate?refcode=123` is invalid, but `https://test.com/donate?refcode=123` is valid.

The URL field should allow relative URLs with query strings.

### Reproduction Steps

Create a collection that uses a `richText` field, using the `lexicalEditor`.
Create a doc in that collection
Type some content into the rich text field
Select some text and click the Link icon in the toolbar to add a link
Type a relative path with a query string into the "Enter a URL" field
Click "Save changes"

**Comment by cbratschi** [comment]
A problem with Lexical is the missing support of anchor links. Would like to be able to use #target too for internal links.

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/7870
