### ISSUE TITLE
Table Elements of Lexical Richtext Editor does not show in Lexical generated Html 

### ISSUE THREAD

**Issue by vaibhav0524** [payloadcms/payload#7483]
### Payload Version

3.0.0-beta.68

### Node Version

18.19.0

### Next.js Version

15.0.0-canary.53

### Describe the Bug

I have a Pages collection in that we are using Richtext Lexical Editor. To see the content, we added in Richtext editor in html format we have used Lexical Html converter. When we add Table in Richtext editor it is added but when we see the output of generated HTML in the API tab the table Element is not present it just shows <span>unknown node</span> instead of table elements.

![image](https://github.com/user-attachments/assets/262b28d2-ae7c-491e-8626-cbf451c1b767)
![image](https://github.com/user-attachments/assets/5368073b-2d03-4e01-82dd-cc541def157f)
![image](https://github.com/user-attachments/assets/6892a6e3-710e-47a6-a02f-b22845ec8cc7)

Below is the Richtext Lexical editor code that we are using in Page Collection.

`{ 
      name: 'content',
      type: 'richText',     
      editor: lexicalEditor({
        features: ({ defaultFeatures }) => [
          ...defaultFeatures,  
          EXPERIMENTAL_TableFeature(),                             
          HTMLConverterFeature({}),
        ],
      }),
      defaultValue: pagesPlaceholder,
    },
    lexicalHTML('content', { name: 'generatedHtml' }),`
    
    How we can have that HTML table elements in the generatedHTML string?

### Reproduction Steps

Create a new collection say 'Pages'
Add Richtext Lexical Editor in the collection as a field like I mentioned above code of Lexical Editor.
On UI side, add Table element in the Richtext editor and some text fields or media's.
Save the page.?
Go to the API tab, scroll to down and see the genereatedHTML string all the elements are present except the Table element. In place of that it will show <span>unknown node</span> instead of Table elements.

**Comment by jmikrut** [comment]
Hey @vaibhav0524 — we're on it!

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/7521
