### ISSUE TITLE
Google OAuth is not functioning in the admin panel.

### ISSUE THREAD

**Issue by D0nte53** [payloadcms/payload#7485]
### Link to reproduction

https://github.com/D0nte53/auth_payload

### Describe the Bug

Hi,
I reproduce the code from the [step-by-step guide](https://10x-media-gmbh.notion.site/Payload-CMS-Google-Auth-Next-js-875f01a99e3d46c2b7c24936a4f1db29) with PostgreSQL (connect-pg-simple) in [my repository](https://github.com/D0nte53/auth_payload), but it doesn't work as shown in the video.

## Expected behavior:
- After the OAuth authentication, `admin/collections` should be accessible.

## Current behavior:
- After the OAuth authentication, `admin/collections` redirects to `admin/login`.

### To Reproduce

- Clone the GitHub repository.
- Add .env variables (GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, and DATABASE_URI).
- Run npm run dev.
- Navigate to http://localhost:3000/admin and perform OAuth

### Payload Version

2.0.0

### Adapters and Plugins

postgresAdapter

**Comment by r1tsuu** [comment]
I can't see Payload guarantees that provided by you guide will work.. People have definetely done oAuth to work, so you should rather message to the post's author, or try a different method / plugin, this is the most popular https://github.com/thgh/payload-plugin-oauth for 2.0

**Comment by D0nte53** [comment]
Yes, you're absolutely right, it's very strange that it doesn't work in my case. I've already tested this plugin and the behavior is the same; I am redirected every time to the login page. I initially thought it was due to my Google application, but i think that’s not the case because the token is generated correctly. 
Thank you very much for your prompt response.

**Comment by jmikrut** [comment]
Hey @D0nte53 yes, you should open this issue on the plugin repository. Thanks for the shout r1tsuu!

**Comment by D0nte53** [comment]
> Hey @D0nte53 yes, you should open this issue on the plugin repository. Thanks for the shout r1tsuu!

Hello, thank you for getting back to me. Alright, even though I’m not using the plugin, I will go ahead and post the message there!

**Comment by D0nte53** [comment]
If you could please reopen this issue, as I believe it is related to PayloadCMS and its handling of authentication tokens, which I do not understand, rather than the plugin, which I am not using. It would help me a lot. Thank you!
