### ISSUE TITLE
(plugin-form-builder) Fields added with formOverrides and formSubmissionOverrides are not acessible for email customization 

### ISSUE THREAD

**Issue by tiagom-m** [payloadcms/payload#7491]
### Payload Version

beta.71

### Node Version

20 LTS

### Next.js Version

15.0.0-canary.58

### Describe the Bug

Hello. I'm not entirely sure if this is already possible in Payload v3 and the documentation just needs to be updated. 

According to the documentation available, it does not seem possible to access form fields added with `formOverrides` and `formSubmissionOverrides` in the `beforeEmail` function. This would be helpful when customizing the content of an email with form/submission data. 

### Reproduction Steps

For example, if I want a form to have an upload field with a PDF document that should be sent in the email with every form submission, this does not seem possible because the `beforeEmail` function only allows access to the `FormattedEmail` fields and not the form or submission data.

Since sending attachments in emails seems pretty standard behaviour, that's why I'm not sure if there's already a solution for this issue. 

I found that this was discussed here and it seems that this would fix this issue, but this is still open with no explanation/update: https://github.com/payloadcms/payload/pull/4038

Thanks for any help possible.

### Adapters and Plugins

plugin-form-builder

**Comment by paulpopus** [comment]
Going to ship this for v3 in this branch, I'm not sure about `main` right now as I'll need to review that PR first: https://github.com/payloadcms/payload/pull/7626
