### ISSUE TITLE
Invalid next.config.mjs options detected: Unrecognized key(s) in object: 'outputFileTracingExcludes' at "experimental"

### ISSUE THREAD

**Issue by christianfullstack** [payloadcms/payload#7501]
### Payload Version

v3.0.0-beta.73

### Node Version

v20.9.0

### Next.js Version

15.0.0-canary.102

### Describe the Bug

 when starting dev mode or production build i get following Error:
 
 ⚠ Invalid next.config.mjs options detected: 
 ⚠     Unrecognized key(s) in object: 'outputFileTracingExcludes' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ⚠ `experimental.outputFileTracingExcludes` has been moved to `outputFileTracingExcludes`. Please update your next.config.mjs file accordingly.

### Reproduction Steps

start dev mode or production build

**Comment by jmikrut** [comment]
Hey @christianfullstack I wonder if the Next.js canary you're using has moved that property / renamed the property out of `experimental`. 

Can you try and go back to Next.js canary 58? We will leave this open until we do some testing tho. @paulpopus let's take a look

**Comment by paulpopus** [comment]
Yep, it has been changed in this https://github.com/vercel/next.js/pull/68464 since canary.101

**Comment by paulpopus** [comment]
Next release will bump next canary to 104 so we'll be fixing this issue in that

**Comment by smoothdvd** [comment]
nextjs 15.0.0 rc.0:
 ⚠ Invalid next.config.mjs options detected: 
 ⚠     Unrecognized key(s) in object: 'outputFileTracingExcludes', 'outputFileTracingIncludes'
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
