### ISSUE TITLE
QueryPath error path empty when querying relationship fields

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#7524]
### Payload Version

3.0.0.beta-73

### Node Version

v20.12.2

### Next.js Version

15.0.0-canary.77

### Describe the Bug

When querying a nonexistent path inside a relationship field, Payload does not return the erroneous path and instead returns an empty path.

The error will read:

```
{
    "errors": [
        {
            "name": "QueryError",
            "data": [
                {
                    "path": ""
                }
            ],
            "message": "The following path cannot be queried: "
        }
    ]
}
```

### Reproduction Steps

1. Setup a collection with a Relationship field.
2. Query against it using an incorrect path:

```
GET http://localhost:3000/api/items?where[owner.relationTo][equals]=users&where[owner.id][equals]=1
```

(notice `owner.id` which is incorrect)

**Comment by jmikrut** [comment]
@tyteen4a03 we will look into this immediately. Does it happen for any relationship? Can you provide a config and an example of the query you ran?

**Comment by tyteen4a03** [comment]
> @tyteen4a03 we will look into this immediately. Does it happen for any relationship? Can you provide a config and an example of the query you ran?

Should be any relationship. You can see the example query I ran in the issue.
