### ISSUE TITLE
Wrong payload-preferences are fetched in list view

### ISSUE THREAD

**Issue by chelaru-artur** [payloadcms/payload#7530]
### Payload Version

3.0.0-beta.73

### Node Version

20.16.0

### Next.js Version

15.0.0-canary.53

### Describe the Bug

In the list view are fetched first preference-settings that are stored in DB. This happens because WHERE query doesn't contain user ID. 
https://github.com/payloadcms/payload/blob/beta/packages/next/src/views/List/index.tsx#L52-L64
![image](https://github.com/user-attachments/assets/8fc20729-9cf8-4164-8fce-8d61f4e814da)
Guess it should be something like this:
![image](https://github.com/user-attachments/assets/0ff8a867-c476-4cda-8c54-4a956942469f)

### Reproduction Steps

1. Login with user #1
2. Go to some collection
3. Hide some manipulations with columns (hide all columns for example)
4. Login with user #2
5. Go to the same collection
6. Check the columns.

**Comment by JarrodMFlesch** [comment]
Fixed in https://github.com/payloadcms/payload/pull/7534 and will be in next beta release.
