### ISSUE TITLE
User Password update doesn't respect to beforeChangeHooks (and others)

### ISSUE THREAD

**Issue by soapwong703** [payloadcms/payload#7531]
### Describe the Bug

When user update the password from console, we have a beforeChangeHooks to modify the user input password, however we found that the modification doesn't work and payload updated to the original user input password.

After investigation, we found that the password is already assigned before the beforeChangeHooks run, therefore the modification doesn't work.  Currently only beforeOperationHooks can modify the password.
https://github.com/payloadcms/payload/blob/1a0ef4824b3d6548d36e7f28a2030640361c0655/packages/payload/src/collections/operations/updateByID.ts#L94

### To Reproduce

1. Create a collection with auth
2. Create a new user with password '123456Aa'
3. Create a beforeChangeHooks: if(operation === "update") data.password = data.password + "abcd"
4. Login to that user and modify the password to '12345678Aa'
5. Logout
6. Login with password '12345678Aaabcd' is failed
7. Login with password '12345678Aa' is succeed

### Payload Version

2.12.1

**Comment by JarrodMFlesch** [comment]
@soapwong703 I have [this PR](https://github.com/payloadcms/payload/pull/7537) open. But I am wondering, what is the use case here? 

Are you going to inform the user that their password is not what they typed in?

**Comment by soapwong703** [comment]
@JarrodMFlesch Thanks for the quick update!  We are integrating payload with our own user system and the actual password are stored there, all the authenticate performs in our system before user login, thus the password on payload is not the user's actual password.
