### ISSUE TITLE
Conditional fields aren't working correctly

### ISSUE THREAD

**Issue by ammi1378** [payloadcms/payload#7553]
### Link to reproduction

https://github.com/ammi1378/astrowind-payloadcms

### Payload Version

3.0.0-beta.74

### Node Version

v18.20.4

### Next.js Version

15.0.0-canary.106

### Describe the Bug

i have a link field which has two conditional fields. changing the type of link between 'Internal link' which is a reference to 'page' collection and 'Custom URL' which is a text input should show corresponding input.
https://www.loom.com/share/0a7a88607f90471e84a18f646816ce26?sid=b18e4289-2dec-4539-8f08-0708a3f85f42

### Reproduction Steps

just install dependencies and create a new page. then switch between link types.
please see 'src/modules/pages/model/index.ts' => 'HeroBlockModel'

**Comment by ammi1378** [comment]
After running test/live-preview it doesn't seem to be an issue with payload
https://www.loom.com/share/34684338213142518bbd4818a8b0bc0a?sid=7d58d1b6-c8f5-44b6-a5fd-27f97e3da04d

**Comment by ammi1378** [comment]
![image](https://github.com/user-attachments/assets/26dac6c8-41fa-47ef-a7d4-38777ab8f6e9)
While autosave is enabled and specially in lower interval this issue happens. I dont know if its a bug or intended to be like this.
Hearing from the core team about this would be helpful. I'm eager to work on this if somebody give me a clue.

**Comment by paulpopus** [comment]
We'll be fixing this in https://github.com/payloadcms/payload/pull/8434
