### ISSUE TITLE
Issues selecting lexical rich text in drawer

### ISSUE THREAD

**Issue by wkentdag** [payloadcms/payload#7576]
### Describe the Bug

When a lexical rich text editor is rendered within a drawer, you can't click and drag your mouse to select text. If you double click and drag your mouse, it breaks the existing selection instead of extending it. This is unique to Lexical rich text fields in a drawer (ie not an issue for plain text fields in a drawer, or lexical fields in the regular non-drawer editor).

You can still use shift+arrows to alter the selection, so IMO it's a minor issue. But I have had several non-technical content editors complain about not being able to select text in the editor, so figured I'd log the bug and see if there's an easy fix to be had. I'm guessing that there's some interference between the mouse event listeners on the drawer and within the lexical rich text field... happy to submit a PR if anybody can point me in the right direction 🙂 

https://github.com/user-attachments/assets/16050561-2f66-45e9-9f30-b6b30ba28528

nb: in the video at 0:15 I switch to a new tab that has the drawer document open in the main editor, and demo how the text selection works as expected there.

### To Reproduce

1. In the Payload admin demo, open one of the [demo posts](https://demo.payloadcms.com/admin/collections/posts/66b40a977447fd8c55b6af9c)
2. 
3. Under Hero > Links > Related Posts, hit the "edit" icon to open a different post in a drawer
4. Under Content > 01, click twice, without releasing the second click, drag the mouse
5. Note that the current text selection is broken
6. Open the same document in a new tab (no drawer)
7. Repeat step 4, note that the current text selection extends along with your cursor until you release

### Payload Version

2.23.1

**Comment by GermanJablo** [comment]
I can confirm that this bug does not occur in v3, and our recommendation is that you upgrade.
We are usually only addressing critical issues in v2, such as vulnerabilities.
