### ISSUE TITLE
Multi rich-text fields with inline-blocks

### ISSUE THREAD

**Issue by ChannKan** [payloadcms/payload#7579]
### Link to reproduction

https://github.com/shefing/payload/tree/multi_rich_text_fields_with-_inline_blocks

### Payload Version

3.0.0-beta.73

### Node Version

"^18.20.2 || >=20.9.0"

### Next.js Version

15.0.0-canary.59

### Describe the Bug

When I have one rich-text field  with inline-blocks it works perfectly.
If I add another rich-text field  with inline-blocks below the first one - It overwrites the inline-blocks from the field  above it, and if I add a inline-block into the text of the first rich-text field  - it is saved into the second rich-text field .
(Before adding a inline-block to the second rich-text field I cannot add inline-block to the first rich-text field)

### Reproduction Steps

**This bug has 2 affective scenarios:**

**First issue** - _Cannot create an inline block in the top rich-text field before inserting an inline-block into the second  rich-text field:_

**Steps for reproduce:**

1. Open reproduction link and launch payload
2. Open a new post
3. Try to add an inline-block in the first rich-text field

**Expected:**
Inline-block can be added

**Actual:**
Inline-block can not be added

**Second issue** _- Overwrite and mismatched saving inline-blocks in first rich-text field after inserting an inline-block into the second rich-text field :_

**Steps for reproduce:**

1. Open reproduction link and launch payload
2. Open a new post
3. Add an inline-block to the second rich-text field
4. Try to add an inline-block to the first  rich-text field 

**Expected:**
Any inline-block can be added

**Actual:**
Last inline-block added to the second  rich-text field  is the only one that can be added to the first  rich-text field 

5. Save added inline-block in the first  rich-text field 

**Expected:**
Inline-block saved in the first  rich-text field 

**Actual:**
Inline-block saved into the second  rich-text field 

### Adapters and Plugins

db-mongodb

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/7665
