### ISSUE TITLE
Closure Component is not server-side

### ISSUE THREAD

**Issue by GeorgeHulpoi** [payloadcms/payload#7589]
### Link to reproduction

https://github.com/GeorgeHulpoi/payload-closure-function

### Payload Version

3.0.0-beta.76

### Node Version

20.9.0

### Next.js Version

15.0.0-canary.53 / 15.0.0-canary.104

### Describe the Bug

When the following Component is used in `admin.components.Field` is the function below, it receives the arguments for a server-side component:

```ts
export default function Component(args) {}
```

When the Component is a closure in the same property, it receives different arguments (I think client-side):

```ts
export default function Component() {
    return (args) => {};
}
```

Instead, it should receive the server-side arguments.

### Reproduction Steps

1. Open the server.
2. Render the Users collection page.
3. You will see in console that the args are not for server-side (it should include details about i18n, payload, etc).

### Adapters and Plugins

-

**Comment by jmikrut** [comment]
Hey @GeorgeHulpoi — good eye. I don't think a functional way exists for us to be able to know that the `Component` you assign to the `Field` property acts as a closure. 

We would need to be able to identify that, call the closure for you, and then pass server props to the enclosed function.  Rather, I think your closure should be responsible for passing its props through to the enclosed function. You'd just do something like this:

```
export default function Component(rscProps) {
    return (args) => {
      // do something with rscProps here
    };
}
```

Am i following? I am curious - what props does the closure end up receiving? I think they might be built-in React rendering props (the closure is technically _rendering_ the sub-function - we are not passing anything to it I believe).

Let me know what you think!

**Comment by GeorgeHulpoi** [comment]
Hi @jmikrut. I'm passing a plugin config object (serialisable object). In the previous version many plugins used this approach.

I think I can pass the plugin config in 'custom' property to prevent the issue in my scenario. Still, I think that there should be some warnings about this.

I will think for some potential solutions for this and I will comment later.

**Comment by jmikrut** [comment]
Yep, passing props via the custom property should work.

We actually have a better pattern for passing custom props to custom components which will be rolling out shortly - you'll be able to handle that type of thing MUCH easier. It's the PR that resolves this discussion:

https://github.com/payloadcms/payload/discussions/6938

Coming soon. Should resolve for the use case you're mentioning. I think we'll close this until then but once that PR lands, we will be de-briefing everyone on it and will showcase how to pass custom props to components more easily.
