### ISSUE TITLE
Creating Related Item Redirects away from Account Page, Losing Edits

### ISSUE THREAD

**Issue by SuyashVoid** [payloadcms/payload#7593]
### Link to reproduction

(Blank template with 3 lines of change as noted below is enough)

### Payload Version

3.0.0-beta.77

### Node Version

20.12.0 (LTS)

### Next.js Version

15.0.0-canary53 (repro), 15.0.0-canary104 (personal)

### Describe the Bug

When attempting to create a new item via a relationship or upload field while editing an account page, the user is redirected to the newly created item's page upon confirming its creation. This redirection occurs immediately, causing the loss of any unsaved changes on the account page. 

The original editing session is effectively abandoned, leading to potentially significant data loss and user frustration.

### Expected Behavior:
After confirming the creation of the new related item, the user should remain on the account page, with all previously entered data preserved and ready to continue editing.

### Actual Behavior:
The user is redirected away from the account page to the newly created item's page, causing the loss of any unsaved changes made on the account page.
- This does not happen when editing User by first going to Users Collection, selecting a user to edit, and adding new item to related field from there.

### Reproduction Steps
1. Start with `npx create-payload-app@beta -n unintendedRedirectRepro -t blank --use-pnpm`
2. Have a relationship/upload field relating to a different collection in users collection.
```js
{
    name: 'profilePic',
    type: 'upload',
    relationTo: 'media',
}
```

3. Navigate to the account page (clicking gravatar icon on top right) in admin panel and begin editing.
4. In a relationship or upload field, initiate the creation of a new related item.
5. Complete the creation process and Save.
6. Observe that the user is redirected to the newly created item's page instead of remaining on the account page.

### Adapters and Plugins

db-mongodb

**Comment by paulpopus** [comment]
Thanks this will be fixed in the next release!
