### ISSUE TITLE
Images size configurations with same width and height uses same filename causing conflict

### ISSUE THREAD

**Issue by andershermansen** [payloadcms/payload#7601]
### Payload Version

3.0.0-beta.76

### Node Version

v22.4.0

### Next.js Version

15.0.0-canary.104

### Describe the Bug

[createImageName in imageResizer](https://github.com/payloadcms/payload/blob/81e7355ee0f47954b2ffaad5d36e3d6faa0f8779/packages/payload/src/uploads/imageResizer.ts#L61C2-L87) does not create a unique image name for resizing when mulitple configurations are using the same width/height, but other params are different.

One of the two images will be used for both defintions.

This also creates a situation where metadata (size) and actual image loaded is different, and downloading the image can cause infinite loading because browser/client is expecting more data, but server is done sending the file.

Sample defintion which causes this issue:
```
    upload: {
        imageSizes: [
            {
                name: 'square',
                width: 800,
                height: 800,
                position: 'centre',
                withoutEnlargement: false,
            },
            {
                name: 'anotherSquare',
                width: 800,
                height: 800,
                fit: 'contain',
                background: {
                    r: 255,
                    g: 255,
                    b: 255,
                    alpha: 1,
                },
                withoutEnlargement: false,
            },
        ],
    },
```

### Reproduction Steps

1. Create an upload colletion with two different imageSizes configurations where width and height is same but other configuration is different
2. Upload image

Actual:
Same image/filenames is shown for both sizes

Expected:
Two different images/filenames should be used

**Comment by paulpopus** [comment]
In order to avoid breaking changes here we're going to expose a new function on each image size in the next release that lets you fully customise what the file name should be: https://github.com/payloadcms/payload/pull/7634

**Comment by andershermansen** [comment]
@paulpopus Thanks, that is great!

I think we in addition to this should make some error in the scenario where somebody does the same mistake as me. It had a lot of side effects which was hard to track down. I wasted a lot of time on this, and don't want anybody else to do the same. It's better to fail, than to make that mess.
