### ISSUE TITLE
Blocks disappear when you collapse them

### ISSUE THREAD

**Issue by carlcs** [payloadcms/payload#7607]
### Link to reproduction

https://github.com/carlcs/payload/tree/repro/block-disappears

### Payload Version

3.0.0-beta.76

### Node Version

v20.15.1

### Next.js Version

15.0.0-canary.104

### Describe the Bug

Collapsing blocks will sometimes cause the block to disappear. It seems to have something to do with saving the doc and adding or deleting blocks. It can’t be reproduced when you simply open a doc and start collapsing/expanding the blocks.
 
At first we thought the blocks got deleted, but they simply don’t show on screen. When you refresh the edit page, they will reappear.

Same issue also happen when you delete a block. This is not shown in repro video.

### Reproduction Steps

Please see video https://github.com/user-attachments/assets/f089c14f-4ac1-4048-a59b-c1fc102f68e6

### Adapters and Plugins

db-mongodb

**Comment by Timothylp** [comment]
Experiencing the same issue with Payload 3.0.0-beta.74 / 3.0.0-beta.73 and Next.js 15.0.0-canary.77.

**Comment by robinscholz** [comment]
Can confirm, ran into the same problem. Also had live preview render blocks in the wrong order sometimes.

**Comment by heytyler** [comment]
Still working through my migration but so far I don't seem to be experiencing this issue anymore in beta.81

**Comment by carlcs** [comment]
@heytyler yep nice, it does seem to be fixed in beta 79 and up. Can probably close the issue.
