### ISSUE TITLE
vercel times out on deployment

### ISSUE THREAD

**Issue by jomapps** [payloadcms/payload#7610]
### Payload Version

beta.76

### Node Version

21.6.2

### Next.js Version

15.0.0-canary.104

### Describe the Bug

I had my app working fine beta.36
It is deployed on Vercel with MongoDB using Atlas cloud
I just upgraded to beta.76 and the /admin is timing out:

This Serverless Function has timed out.
Your connection is working correctly.
Vercel is working correctly.
504: GATEWAY_TIMEOUT
 
 It does work on local development server.

### Reproduction Steps

well just upgrade the package json and install the packages.

### Adapters and Plugins

mongodb, storage

**Comment by jomapps** [comment]
duplicate. Was raised earlier by someone else.

**Comment by edtorba** [comment]
@jomapps could you please drop a link to the original issue?
