### ISSUE TITLE
Migrations in production not being executed automatically.

### ISSUE THREAD

**Issue by ansbr** [payloadcms/payload#7612]
Hello! I need some help with handling migrations in production - they're not being executed automatically when deploying on Vercel.

I set up a new project using:

```
npx create-payload-app@beta
```
I chose SQLite, and on my local machine, the .env file looks like this:
```
DATABASE_URI=file:./local.db
PAYLOAD_SECRET=...
```
For production I add AUTH_TOKEN to config:
```
  ...
  db: sqliteAdapter({
    client: {
      url: process.env.DATABASE_URI || '',
      authToken: process.env.DATABASE_AUTH_TOKEN 
    },
  })
  ...
```

Then I ran the following command:
```
payload migrate:create
```
Now, it's time to deploy to production on Vercel. I set up the following .env variables:
```
DATABASE_URI=libsql://here-turso-link
DATABASE_AUTH_TOKEN=...
PAYLOAD_SECRET=...
```
But the problem is that Vercel doesn't automatically run migrations during the build. I searched for tutorials on the site, for example, this one: https://payloadcms.com/docs/database/migrations, but it doesn't mention anything about automatic migrations during deployment.

However, if I work directly with the production database on my local machine, everything works fine during deployment because no migrations are needed - the database is already up to date.

**Comment by r1tsuu** [comment]
Have you added `prodMigrations` property into your database config? You should import the value for that from your migrations folder I believe

**Comment by smoothdvd** [comment]
I put the CMD line in Dockerfile

```
CMD pnpm cross-env PAYLOAD_CONFIG_PATH=dist/payload.config.js payload migrate; node dist/server.js
```

**Comment by jmikrut** [comment]
Hey all, yes, @r1tsuu is correct! 

You can pass `prodMigrations` to the `postgresAdapter` now. This is not yet documented (we added it last week) but this will execute your migrations on startup in production.

You should now have an `index.ts` file in your migrations folder which will automatically be generated when you run `migrate:create` next time.

Import it like this:

```
import { migrations } from './migrations'
```

Then pass it to your `postgresAdapter`. Migrations will be executed upon first boot.

Docs coming soon!
