### ISSUE TITLE
Update serverExternalPackages for next dev --turbo

### ISSUE THREAD

**Issue by christianfullstack** [payloadcms/payload#7628]
### Payload Version

v3.0.0-beta.77

### Node Version

v20.9.0

### Next.js Version

tested with current ^15.0.0-canary.111 and ^15.0.0-canary.104

### Describe the Bug

While executing `next dev --turbo` i get following Error:
but this is just in the turbo Mode.

`⨯ ./node_modules/.pnpm/mongodb@4.17.1_@aws-sdk+client-sso-oidc@3.598.0/node_modules/mongodb/lib/index.js
Package mongodb (serverExternalPackages or default list) can't be external
The request mongodb matches serverExternalPackages (or the default list), but it can't be external:
The request could not be resolved by Node.js from the project directory.
Packages that should be external need to be installed in the project directory, so they can be resolved from the output files.
Try to install the package into the project directory.

./node_modules/.pnpm/mongoose@6.12.3_@aws-sdk+client-sso-oidc@3.598.0/node_modules/mongoose/index.js
Package mongoose (serverExternalPackages or default list) can't be external
The request mongoose matches serverExternalPackages (or the default list), but it can't be external:
The request could not be resolved by Node.js from the project directory.
Packages that should be external need to be installed in the project directory, so they can be resolved from the output files.
Try to install the package into the project directory.

./node_modules/.pnpm/pino@9.3.1/node_modules/pino/pino.js
Package pino (serverExternalPackages or default list) can't be external
The request pino matches serverExternalPackages (or the default list), but it can't be external:
The request could not be resolved by Node.js from the project directory.
Packages that should be external need to be installed in the project directory, so they can be resolved from the output files.
Try to install the package into the project directory.

./node_modules/.pnpm/pino-pretty@11.2.1/node_modules/pino-pretty/index.js
Package pino-pretty (serverExternalPackages or default list) can't be external
The request pino-pretty matches serverExternalPackages (or the default list), but it can't be external:
The request could not be resolved by Node.js from the project directory.
Packages that should be external need to be installed in the project directory, so they can be resolved from the output files.
Try to install the package into the project directory.
`

### Reproduction Steps

execute `next dev --turbo`

**Comment by neslob** [comment]
I have the same issue with these versions.

```
    "@lexical/headless": "0.17.0",
    "@lexical/html": "0.17.0",
    "@lexical/link": "0.17.0",
    "@lexical/list": "0.17.0",
    "@lexical/mark": "0.17.0",
    "@lexical/markdown": "0.17.0",
    "@lexical/react": "0.17.0",
    "@lexical/rich-text": "0.17.0",
    "@lexical/selection": "0.17.0",
    "@lexical/utils": "0.17.0",
    "@payloadcms/db-postgres": "3.0.0-beta.77",
    "@payloadcms/email-nodemailer": "3.0.0-beta.77",
    "@payloadcms/next": "3.0.0-beta.77",
    "@payloadcms/plugin-cloud": "3.0.0-beta.77",
    "@payloadcms/richtext-lexical": "3.0.0-beta.77",
    "@payloadcms/storage-s3": "3.0.0-beta.77",
    "@payloadcms/ui": "3.0.0-beta.77",
    "next": "15.0.0-canary.104",
    "react": "19.0.0-rc-06d0b89e-20240801",
    "react-dom": "19.0.0-rc-06d0b89e-20240801",
```

**Comment by jmikrut** [comment]
Hey all, this broke with Next.js and I opened an issue to track here:

https://github.com/vercel/next.js/issues/68805

Let's consolidate feedback on that issue!
