### ISSUE TITLE
Unable to save draft before publishing - Customisable ID breaks autosave

### ISSUE THREAD

**Issue by rhinoella** [payloadcms/payload#7650]
### Describe the Bug

When I create a new item in a collection, there is no 'save' button, only a 'publish' button. I suspect this is because I have overridden the 'id' field, so the autosave feature breaks, as it cannot save without an id.

There are a few possible ways to provide a solution:

- Don't autosave until an id is provided
- Allow for an id to be default generated even if it is overridden by a custom id

### To Reproduce

Have a collection with a customisable ID field, with the version settings as:
```
  versions: {
    drafts: {
      autosave: true,
    },
  },
```

Customisable id:
```
    {
      name: "id",
      label: "Slug",
      type: "text",
      required: true,
    }
```

### Payload Version

2.26.0

### Adapters and Plugins

db-mongodb, autosave, versions

**Comment by mejjjor** [comment]
Hello, same problem with postgres adaptater
