### ISSUE TITLE
API still returns defaultLocale value even when fallback is set to false

### ISSUE THREAD

**Issue by PP-Tom** [payloadcms/payload#7663]
### Payload Version

3.0.0-beta.78

### Node Version

10.2.4

### Next.js Version

15.0.0-canary.53

### Describe the Bug

The defaultLocale value for localized fields is still returned even when the fallback value is set to false.

### Reproduction Steps

1. Create a collection.
2. Add a localized field such as:
```js
{
    name: 'excerpt',
    type: 'textarea',
    localized: true,
},
```
3. In your `payload.config.ts` add:
```js
localization: {
    locales: [
        { label: 'English', code: 'en-GB' },
        { label: 'Spanish', code: 'es' },
        { label: 'Dutch', code: 'nl' },
        { label: 'American', code: 'en-US', fallbackLocale: 'en-GB' },
    ],
    fallback: false,
    defaultLocale: 'en-GB',
},
```

In the frontend create a new page from your collection, give the defaultLocale a value, save and then switch to a different locale, check the API tab, you'll see the excerpt in the response.

### Adapters and Plugins

mongo-db

**Comment by paulpopus** [comment]
Thanks for your report! Fixed in this PR https://github.com/payloadcms/payload/pull/7689

**Comment by PP-Tom** [comment]
Hey @paulpopus, running the latest version (3.0.0-beta.95), fallback: false is still is showing the defaultLocale.

**Comment by r1tsuu** [comment]
New issue: https://github.com/payloadcms/payload/issues/8443
