### ISSUE TITLE
Error while getting different payload configs

### ISSUE THREAD

**Issue by zelenovsky** [payloadcms/payload#7700]
### Payload Version

3.0.0-beta.29

### Node Version

v20.11.0

### Next.js Version

14.3.0-canary.37

### Describe the Bug

Hello, I am trying to get different configs depending on user lang, but I face this error:
`DuplicateCollection: Collection slug already in use: "payload-preferences, payload-migrations, payload-preferences, payload-migrations"`

Why does this happen? I use completely different databases, here is my code:
```ts
const ru_config = {
    ...config,
    db: postgresAdapter({
        pool: {
            connectionString: process.env.RU_DATABASE_URL || "",
        },
    }),
};

const en_config = {
    ...config,
    db: postgresAdapter({
        pool: {
            connectionString: process.env.EN_DATABASE_URL || "",
        },
    }),
};

export const localized_payload_config = {
    "ru-RU": buildConfig(ru_config),
    "en-US": buildConfig(en_config),
};
```

### Reproduction Steps

1. create the config example described above
2. import it somewhere in next page 
    ```
    const payload = await getPayload({
		config: localized_payload_config[params.lang],
	});
	```

**Comment by jmikrut** [comment]
Hey @zelenovsky — this is not supported. Payload is a singleton pattern, so once Payload initializes with a given config, it stays initialized. We can't change this. You'll need to adapt your pattern to run separate servers / node processes per config or something similar.
