### ISSUE TITLE
Can't create migration with beta 81

### ISSUE THREAD

**Issue by rikrose** [payloadcms/payload#7703]
### Link to reproduction

https://github.com/rikrose/payload-3b81-bug-demo

### Payload Version

3.0.0-beta.81

### Node Version

v21.5.0

### Next.js Version

15.0.0-canary.104

### Describe the Bug

❯ pnpm run payload migrate:create initial  

> cms@1.0.0 payload C:\Users\rikro\repos\startover\apps\cms
> payload "migrate:create" "initial"

C:\Users\rikro\repos\startover\node_modules\.pnpm\react-datepicker@6.9.0_react-dom@19.0.0-rc-06d0b89e-20240801_react@19.0.0-rc-06d0b89e-20240801\node_modules\react-datepicker\dist\react-datepicker.css:1
@charset "UTF-8";
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1287:20)
    at Module._compile (node:internal/modules/cjs/loader:1339:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Object.transformer [as .js] (file:///C:/Users/rikro/repos/startover/node_modules/.pnpm/tsx@4.17.0/node_modules/tsx/dist/register-B_eFQvfc.mjs:2:878)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at <anonymous> (C:\Users\rikro\repos\startover\node_modules\.pnpm\@payloadcms+ui@3.0.0-beta.81_monaco-editor@0.50.0_next@15.0.0-canary.104_payload@3.0.0-beta.8_w7kmbia6b7rfbioyh22fcqxtdm\node_modules\@payloadcms\ui\dist\exports\client\chunk-HR5HEGNB.js:14:102589)

Node.js v21.5.0
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction Steps

Easy setup: Clone the repo at https://github.com/rikrose/payload-3b81-bug-demo 

What I did to generate the setup:
pnpm dlx create-payload-app@3.0.0-beta.81 --use-pnpm
pnpm install @payloadcms/ui@3.0.0-beta.81
pnpm install @t3-oss/env-nextjs zod
pnpm install payload-auth-plugin

Add the following to `payload.config.ts`:
```typescript
import AuthPlugin from 'payload-auth-plugin'
// import 'payload-auth-plugin/styles'
import { GoogleAuthProvider } from 'payload-auth-plugin/providers'

import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  server: {
    PAYLOAD_SECRET: z.string().min(24),
    DATABASE_URI: z.string(),
    GOOGLE_ID: z.string(),
    GOOGLE_SECRET: z.string(),
  },
  runtimeEnv: {
    PAYLOAD_SECRET: process.env.PAYLOAD_SECRET,
    DATABASE_URI: process.env.DATABASE_URI,
    GOOGLE_ID: process.env.GOOGLE_ID,
    GOOGLE_SECRET: process.env.GOOGLE_SECRET,
  }
})
```

Update `buildConfig` to read as follows:
```typescript
export default buildConfig({
  admin: {
    user: Users.slug,
    importMap: {
      baseDir: path.resolve(dirname),
    },
  },
  collections: [Users, Media],
  editor: lexicalEditor(),
  secret: env.PAYLOAD_SECRET,
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
  db: postgresAdapter({
    pool: {
      connectionString: env.DATABASE_URI,
    },
  }),
  sharp,
  plugins: [
    AuthPlugin({
      providers: [
       GoogleAuthProvider({
          client_id: env.GOOGLE_ID,
          client_secret: env.GOOGLE_SECRET, 
        })
      ]
    })
    // storage-adapter-placeholder
  ],
})
```

Populate the .env file with a PAYLOAD_SECRET, DATABASE_URI (must be valid), and GOOGLE_ID and GOOGLE_SECRET (unvalidated by the time failure happens)

Generate the error:
pnpm run payload migrate:create initial

### Adapters and Plugins

payload-auth-plugin db-postgres lexicalEditor

**Comment by DanRibbens** [comment]
I tested on mine as I noticed you're on Windows. I don't get an error in my test project using the same depedency versions as you showed. I believe this problem is something in your situation that isn't able to build and not just a problem with creating migrations. 

Can you verify that your able to run and build the project otherwise? Start by removing payload-auth-plugin as that might not have been updated with the newer breaking changes from the component import map changes.

Please tag me if you wish to reopen the issue or you can always create a new one if you can norrow down the cause and reproduction more.

Thanks!

**Comment by rikrose** [comment]
Removed payload-auth-plugin, and it built. Re-add and it fails again. Confirmed that it's the auth plugin.

**Comment by rikrose** [comment]
Fun fact, it doesn't stop pnpm run dev from running, but, obviously, it can't get to the database.

**Comment by DanRibbens** [comment]
That makes sense. I would open an issue on that auth plugin since it isn't compatible with the breaking changes in beta.

Cheers @rikrose!
