### ISSUE TITLE
Allow for a Global to be accessed from generateTitle or generateDescription [SEO Plugin]

### ISSUE THREAD

**Issue by joedawson** [payloadcms/payload#7708]
### Payload Version

n/a

### Node Version

n/a

### Next.js Version

n/a

### Describe the Bug

It would be great if it was possible to access data from a Global via the `generateTitle` or `generateDescription` functions when using the SEO Plugin.

`doc` and `locale` are currently available, having access to a global (or payload in general?), where information such as a company name or tagline may be included would be helpful as part of automatically generated titles/descriptions.

cc @paulpopus 

### Reproduction Steps

n/a

**Comment by paulpopus** [comment]
After this PR is released you'll be able to use the `req.payload` local API to fetch whatever you need https://github.com/payloadcms/payload/pull/7711

**Comment by joedawson** [comment]
Appreciate you @paulpopus!
