### ISSUE TITLE
Unable to submit forms in Demo

### ISSUE THREAD

**Issue by dhammikab** [payloadcms/payload#771]
# Bug Report

User is not able to submit forms 

## Expected Behavior

The user should be able to select a form  to submit.

## Steps to Reproduce

0. Login to the demo app using the credentials provided.
1. Define a form on the demo site using: https://demo.payloadcms.com/admin/collections/forms/create
2. Navigate to https://demo.payloadcms.com/admin/collections/form-submissions/create
3. Note that the "FROM" is disabled and you can not select a form .

**Comment by denolfe** [comment]
Hey @dhammikab , thanks for the report. The Form Submissions were really meant to only be populated via the API, so this is by design. I agree that this could be clearer. We can look at improving this.
