### ISSUE TITLE
Cannot import `richText` field (lexicalEditor)

### ISSUE THREAD

**Issue by AdamZajler** [payloadcms/payload#7715]
### Payload Version

3.0.0-beta.74

### Node Version

22.2.0

### Next.js Version

15rc

### Describe the Bug

When I'm trying to add `richText` field I'm getting such error:
![Screenshot from 2024-08-16 10-40-28](https://github.com/user-attachments/assets/8304d6a5-c958-4a65-aad6-79ae02c1e9df)

I have only the default import of the lexicalEditor at `payload.config.ts`
```tsx
export default buildConfig({
  editor: lexicalEditor(),
```

Code for the block: 
```tsx
import { Block } from 'payload';
import { titleWithUnderline } from '@/payload/fields/titleWithUnderline';

export const TextSection: Block = {
  slug: 'textSection',
  labels: {
    singular: { en: 'Section with title and text', pl: 'Sekcja z tytułem i tekstem' },
    plural: { en: 'Sections with title and text', pl: 'Sekcje z tytułem i tekstem' },
  },
  imageURL: '/blocks/textSection.png',
  interfaceName: 'TextSectionBlock',
  fields: [
    titleWithUnderline(),
    {
      name: 'description',
      type: 'richText',
    },
  ],
};

```

### Reproduction Steps

Just adding `richText` field to any block :|

**Comment by AlessioGr** [comment]
The Next.js version you're using is not supported anymore in recent payload versions. Please switch to payload `3.0.0-beta.84` these versions:

    "next": "15.0.0-canary.104",
    "react": "19.0.0-rc-06d0b89e-20240801",
    "react-dom": "19.0.0-rc-06d0b89e-20240801",
