### ISSUE TITLE
Linux build pipeline failing due to "/usr/bin/env: ‘node --no-deprecation’: No such file or directory"

### ISSUE THREAD

**Issue by mschinis** [payloadcms/payload#7717]
### Payload Version

3.0-beta.82

### Node Version

v20.16.0

### Next.js Version

15.0.0-canary.104

## The Issue
I want to run a script with `payload run` bin with a "prebuild" package.json script, but this fails on both Netlify/Vercel build environment.

**My package.json scripts:**
```
  "scripts": {
    "build": "cross-env NODE_OPTIONS=--no-deprecation next build",
    ... other scripts
    "prebuild": "payload run ./src/build/generate-config.ts"
  },
```

**Netlify output**
<img width="1101" alt="Screenshot 2024-08-16 at 5 03 47 PM" src="https://github.com/user-attachments/assets/b3504bb6-bd86-460b-ab75-dc3b069ba43d">

## Debugging the issue
Looking further into the issue, [it looks like Linux treats everything after the shebang](https://unix.stackexchange.com/questions/399690/multiple-arguments-in-shebang) in the [cli bin here](https://github.com/payloadcms/payload/blob/beta/packages/payload/bin.js#L1), as a single command, rather than separate arguments.

## The fix
To test this theory, I did the following which fixes the issue:
1. Copied the contents of the `payload/bin.js` to the root of my content
2. Modified the imports to import the correct js files
3. Removed the "--no-deprecation"
4. Change the prebuild script to use the payload bin from the root of my project.

**payload-bin.js**
```js
#!/usr/bin/env node
// **^ Removed --no-deprecation**

import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const useSwc = process.argv.includes("--use-swc");
const disableTranspile = process.argv.includes("--disable-transpile");

if (disableTranspile) {
  // Remove --disable-transpile from arguments
  process.argv = process.argv.filter((arg) => arg !== "--disable-transpile");

  const start = async () => {
    const { bin } = await import("payload/bin.js"); // **Updated import path**
    await bin();
  };

  void start();
} else {
  const filename = fileURLToPath(import.meta.url);
  const dirname = path.dirname(filename);
  const url = pathToFileURL(dirname).toString() + "/";

  if (!useSwc) {
    const start = async () => {
      // Use tsx
      let tsImport = (await import("tsx/esm/api")).tsImport;

      const { bin } = await tsImport(
        "./node_modules/payload/dist/bin/index.js", // **Updated import path**
        url,
      );
      await bin();
    };

    void start();
  } else if (useSwc) {
    const { register } = await import("node:module");
    // Remove --use-swc from arguments
    process.argv = process.argv.filter((arg) => arg !== "--use-swc");

    try {
      register("@swc-node/register/esm", url);
    } catch (_) {
      console.error(
        "@swc-node/register is not installed. Please install @swc-node/register in your project, if you want to use swc in payload run.",
      );
    }

    const start = async () => {
      const { bin } = await import("payload/index.js"); // **Updated import path**
      await bin();
    };

    void start();
  }
}
```

**package.json**
```
  "scripts": {
    "build": "cross-env NODE_OPTIONS=--no-deprecation next build",
    ... other scripts
    "prebuild": "node ./payload-bin run ./src/build/generate-config.ts"
  },
```

### Reproduction Steps

Try deploy the payload 3.0 demo repo to either "Netlify" or "Vercel", with a prebuild script that uses "payload run".

**Comment by yobottehg** [comment]
I have the same issue locally with beta 82 when running the command `docker compose exec cms npm run payload generate:importMap`

```
docker compose exec cms npm run payload generate:importMap

> babu-cms@1.0.0 payload
> payload generate:importMap

env: can't execute 'node --no-deprecation': No such file or directory
```

Are there new dependencies for the docker containers to be installed?

**Comment by mschinis** [comment]
Hi @yobottehg - there's no new dependencies to be installed. The issue you are facing is caused by the same issue as I posted above.

My [pull-request](https://github.com/payloadcms/payload/pull/7718) should solve this issue, once merged and a new version of payload is released.

**Comment by paulpopus** [comment]
This should be fixed in https://github.com/payloadcms/payload/pull/7721 and will roll out in the next release
