### ISSUE TITLE
Unknown script: "generate:graphqlschema".

### ISSUE THREAD

**Issue by matart15** [payloadcms/payload#7737]
### Payload Version

3.0.0-beta.82

### Node Version

v20.12.2

### Next.js Version

15.0.0-canary.104

### Describe the Bug

```sh
pnpm payload generate:graphQLSchema

> payload-test@1.0.0 payload /Users/matar/workplace/github/temp/payload-test
> payload "generate:graphQLSchema"

Unknown script: "generate:graphqlschema".
```

### Reproduction Steps

npx create-payload-app@beta
pnpm payload generate:graphQLSchema

**Comment by AlessioGr** [comment]
The command has changed - you can now run it using `pnpm payload-graphql generate:schema` - see https://payloadcms.com/docs/beta/graphql/graphql-schema#schema-generation-script
