### ISSUE TITLE
Undecipherable error in `generate:types` if a Blocks field with no blocks is specified

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#7748]
### Payload Version

3.0.0.beta-78

### Node Version

20.12.2

### Next.js Version

15.0.0-canary.107

### Describe the Bug

`generate:types` fails to account for a collection configuration where a blocks field has no `blocks` defined. Example error:

```
SyntaxError: '=>' expected. (440:17)
  438 | deletedAt?: (string | null)
  439 | equipped?: (boolean | null)
> 440 | attributes?: (()[] | null)
      |                 ^
```

### Reproduction Steps

Create a Blocks field with no Blocks:

```

        {
            name: "test",
            type: "blocks",
            blocks: [],
        },
```

**Comment by paulpopus** [comment]
This will be fixed in this PR, thanks for your report! https://github.com/payloadcms/payload/pull/7765
