### ISSUE TITLE
double extract the field from field props (TextField)

### ISSUE THREAD

**Issue by dominikzogg** [payloadcms/payload#7751]
### Payload Version

3.0.0-beta.84

### Node Version

20.16.0

### Next.js Version

14.2.5

### Describe the Bug

I am using the beta with some custom fields and i recognized a lot of changes between 77 and 84 (its a beta, that's fine). Those changes made me read the payload source for a field that i based a custom one of.

I've seen that code and it looks wrong to me, having extracted field and then override it in the next line.

```ts
  const {
    field,
    field: {
      ....
      } = {},
    ...
    },
   ...
  } = props;
```

### Reproduction Steps

Check code at: https://github.com/payloadcms/payload/blob/2d6e7f8a37b90b1acee45943e037b7554372f2b0/packages/ui/src/fields/Text/index.tsx#L22

**Comment by paulpopus** [comment]
Are you getting any errors related to this or is this more of a coding patterns question?

**Comment by dominikzogg** [comment]
@paulpopus assign a property twice normally means its overriden, so removing the first `field,`.

**Comment by paulpopus** [comment]
In that specific object what's happening is just that as part of the destructuring assignment we take `field` out and then we also further destructure `field` for it's separate values. You can do this with javascript.

It's the equivalent of

```
const { field } = props
const { name } = field
```

except in one line. If you inspect the destructured values you should see them resolve to their correct parts
