### ISSUE TITLE
Bug with uploading video/image between production and development

### ISSUE THREAD

**Issue by vuquangpham** [payloadcms/payload#7760]
### Payload Version

3.0

### Node Version

22

### Next.js Version

15.0.0-canary.120

### Describe the Bug

Hey team, I noticed a bug with upload medias field, when in development mode, it works correctly to upload a file, but in production, when I put a video/image, it's showing a message with file is too large 🙂 (file is the same in both dev and prod)

### Reproduction Steps

https://github.com/user-attachments/assets/32dbaf15-5636-41ef-b04c-f78a5f99a6b4

### Adapters and Plugins

supabase postgresql, storage-s3

**Comment by MinSomai** [comment]
https://payloadcms.com/docs/upload/overview#payload-wide-upload-options

**Comment by nvti** [comment]
This may be a Vercel error.
https://vercel.com/guides/how-to-bypass-vercel-body-size-limit-serverless-functions
