### ISSUE TITLE
Locale switched without notice when using locale switcher on collection overview page

### ISSUE THREAD

**Issue by yobottehg** [payloadcms/payload#7762]
### Payload Version

3.0.0-beta.78

### Node Version

20 LTS

### Next.js Version

15.0.0-104

### Describe the Bug

Our setup looks the following:
locales : de, en, hu
default : de

If I'm on the collection overview page and I'm on the german locale and I click a link to go to a detail page of that entry i get the english version of that entry without any notice.

Here a video of that behaviour:

https://github.com/user-attachments/assets/d48c18b5-bb4e-4b3f-8b88-50827f6ac2c7

This shown collection has 2 localised fields: alt and caption

### Reproduction Steps

- Use the locale switcher on the collection overview page
- Access a collection entry
- locale is switched to english without any notice (unsure why english because DE is the default)

### Adapters and Plugins

db-postgres

**Comment by yobottehg** [comment]
I'll close this one as I can't reproduce this anymore on beta 87. I think this was some buggy behaviour with Next.js 15.0.0-canary.104 and payload pre 3.0.0-beta.79.

**Comment by yobottehg** [comment]
Sorry I need to repoen this as I encountered more of these issues even on beta 87. There is a really strange behaviour in the UI regarding the displayed content and the locale switch. They do not allways display the same locale. Even on the detail page.

Here an additional video where i click on a collection entry and the UI tells me that DE is displayed but EN is displayed. I can not even get the DE content directly when i click on DE i need to switch to EN before switching to DE.

https://github.com/user-attachments/assets/7d44861f-c0eb-44b3-a4f2-1b994cd04056

**Comment by yobottehg** [comment]
Okay i found out that this is due to the switch at the top beeing "ignored"

- Api returns "okay" and says preference was saved but it was not.
- My user has multiple entries inside preferences for locale, unsure why this happened or how but it is the case also for multiple users.
- Because there were multiple entries inside the preferences the `updateOne` with try / catch did not work.
- Because the code then assumes that there is no entry it will create another.

As soon as i removed all locale entries from my user except one the locale update did work again.

**Comment by yobottehg** [comment]
Okay an update here how this is reproducable:

1. have a multi-locale setup where english is not the default locale e.g german.
2. Create a german page and translate it to english.
3. Look at the german page in the pages collection overview
4. Click on the user avatar
5. Inside the locale dropdown there is only the engliush language (I guess this is because the Admin UI is only in english)
6. After I visited my user profile my user now has 2 entries for the locale inside the preferences and no matter what i do with the locale switcher the "prefered locale" stays english.

**Comment by paulpopus** [comment]
Looks like this also is fixed now!
