### ISSUE TITLE
Impossible to override plugin-search collection labels

### ISSUE THREAD

**Issue by BohdanK-W32** [payloadcms/payload#7771]
### Payload Version

3.0.0-bea.86

### Node Version

20.12

### Next.js Version

15.0.0

### Describe the Bug

For now, it's impossible to override search collection labels (without overriding the return value of `searchPlugin(...)`).
It's need to work out of the box

![image](https://github.com/user-attachments/assets/39311105-b990-4944-a9b7-f64f1b07ed47)

Link to line in the plugin config generation:
https://github.com/payloadcms/payload/blob/3a91deb0a4fde9550cfa9b6eeeedfc5062598da3/packages/plugin-search/src/Search/index.ts#L47

Lines of code need to be placed on top of the config (before user overrides):
https://github.com/payloadcms/payload/blob/3a91deb0a4fde9550cfa9b6eeeedfc5062598da3/packages/plugin-search/src/Search/index.ts#L70

### Reproduction Steps

1. Create blank payload project
2. Install @payloadcms/plugin-seo
3. Try to override labels with your own

### Adapters and Plugins

plugin-search

**Comment by paulpopus** [comment]
Will be fixed in https://github.com/payloadcms/payload/pull/7775
