### ISSUE TITLE
Cannot null / empty a number field

### ISSUE THREAD

**Issue by joedawson** [payloadcms/payload#7780]
### Payload Version

3.0.0-beta.87

### Node Version

22.4

### Next.js Version

15.0.0-canary.104

### Describe the Bug

When adding a `number` field to a collection or global, and it is also **not** required (optional), its value cannot be emptied / nulled.

### Reproduction Steps

1. Add a `number` field to a collection (ensuring `required` is `false`
2. Add a value and save
3. Attempt to delete the value and save, it will save it with its value before attempting to delete

### Adapters and Plugins

db-postgres

**Comment by PatrikKozak** [comment]
@joedawson Thanks for your patience here - we have a fix for this incoming!
