### ISSUE TITLE
richtext-lexical SerializedUploadNode value type seems to be wrong

### ISSUE THREAD

**Issue by neverether** [payloadcms/payload#7808]
### Payload Version

3.0.0-beta.90

### Node Version

20

### Next.js Version

15.0.0-canary.120

### Describe the Bug

While working on serializing a lexical rich text field it looks like the SerializedUploadNode's type `value: string | number` is incorrect based on output from the LocalAPI:

![ss](https://github.com/user-attachments/assets/b69ae889-d686-4323-8083-b06410b7c365)

### Reproduction Steps

Simplest way to reproduce is to use the website template and modify the [serializer](https://github.com/payloadcms/payload/blob/beta/templates/website/src/app/components/RichText/serialize.tsx) to add a:

```tsx
case "upload": {
  const value = node.value;
  return (
  //..
```

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/7822
