### ISSUE TITLE
Collection search removes the locale parameter searching in the wrong language

### ISSUE THREAD

**Issue by yobottehg** [payloadcms/payload#7813]
### Payload Version

3.0.0-beta.90

### Node Version

20 LTS

### Next.js Version

15.0.0-canary.104

### Describe the Bug

When a collection is searched the search is done in a different locale then the selected one because the locale parameter is removed from the url.

Please see the attached video demonstrating the issue where a search does not yield any results but it should. After changing the locale again it shows the wanted results because the parameter is appended again.

https://github.com/user-attachments/assets/ab6acc75-4975-4a5f-8954-86ac7ff7e9bc

### Reproduction Steps

See the video.

### Adapters and Plugins

db-postgres

**Comment by yobottehg** [comment]
The wrong results were a side effect of #7762 .
The parameter is still removed - unsure if this issue should be closed or not.

**Comment by JarrodMFlesch** [comment]
@yobottehg I think we need to fix the other issue first and then attempt to recreate it here. I can see how having a table full of the same preference could cause issues. But I don't want to close it just yet.

**Comment by JarrodMFlesch** [comment]
Waiting for review/release of changes from https://github.com/payloadcms/payload/pull/7828

**Comment by paulpopus** [comment]
Looks like this is now fixed in https://github.com/payloadcms/payload/pull/8100 based on my testing, will be available in the next release
