### ISSUE TITLE
relationship field causes no such table error

### ISSUE THREAD

**Issue by aniljbhatia** [payloadcms/payload#7823]
### Payload Version

3.0.0-beta.90

### Node Version

21.2.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

Using the SQLite adaptor I added a relationship field to another collection. The field shows correctly in the UI but when I try to save data in the field I get "Something went wrong". The console says "LibsqlError: SQLITE_ERROR: no such table: main.__old_push_tags"

### Reproduction Steps

Tags Collection
```typescript
import type { CollectionConfig } from 'payload';

export const Tags: CollectionConfig = {
  slug: 'tags',
  access: {
    read: () => true,
  },
  admin: {
    useAsTitle: 'tag',
  },
  fields: [
    {
      name: 'tag',
      type: 'text',
      required: true,
    },
    {
      name: 'section',
      type: 'select',
      required: true,
      options: [
        { value: 'skills', label: 'Skills' },
        { value: 'interests', label: 'Interests' },
        { value: 'learning', label: 'Learning' },
      ],
    },
    {
      name: 'displayOrder',
      type: 'number',
      required: true,
      defaultValue: 1
    },
  ]
}
```
Jobs Collection Field
```typescript
{
        name: 'tags',
        type: 'relationship',
        relationTo: 'tags',
        hasMany: true,
        required: true,
        admin: {
            sortOptions: 'tag',
        },
}
```

### Adapters and Plugins

db-sqlite

**Comment by aniljbhatia** [comment]
Just updated to Payload version 3.0.0-beta.107 and Next.js 15.0.0-canary.104 and this is still happening.

**Comment by r1tsuu** [comment]
Hey @aniljbhatia. I can't reproduce this on latest beta, I'm assuming this was gone since we updated version of drizzle, which included some SQLite fixes.
