### ISSUE TITLE
Postgres Adapter: Build Error - Module not found: Can't resolve 'payload/versions'

### ISSUE THREAD

**Issue by pat-mw** [payloadcms/payload#7824]
### Payload Version

3.0.0-beta.90

### Node Version

v20.12.2

### Next.js Version

^15.0.0-rc.0

### Describe the Bug

./node_modules/@payloadcms/db-postgres/dist/createGlobalVersion.js:12:1

```
Module not found: Can't resolve 'payload/versions'
  10 | });
  11 | const _drizzleorm = require("drizzle-orm");
> 12 | const _versions = require("payload/versions");
     | ^
  13 | const _tosnakecase = /*#__PURE__*/ _interop_require_default(require("to-snake-case"));
  14 | const _upsertRow = require("./upsertRow");
  15 | function _interop_require_default(obj) {

https://nextjs.org/docs/messages/module-not-found
```

Import trace for requested module:
```
./node_modules/@payloadcms/db-postgres/dist/index.js
./payload.config.ts
./src/app/(payload)/admin/[[...segments]]/page.tsx
```

The issue is a missing export in the `package.json` file for the latest payload dist
I tried to add it below but this didn't work for me.

![image](https://github.com/user-attachments/assets/202aff1f-8d50-4d23-917b-7893a7c753c4)

Any ideas?

### Reproduction Steps

Set up boilerplate t3 stack project
Upgrade to Next15
Install payload dependencies / use the cli
Set up DB Connection :

```
// payload.config.ts

// storage-adapter-import-placeholder
import { postgresAdapter } from '@payloadcms/db-postgres' // database-adapter-import
import { lexicalEditor } from '@payloadcms/richtext-lexical'
import path from 'path'
import { buildConfig } from 'payload'
import { fileURLToPath } from 'url'
import sharp from 'sharp'

import { env } from '@/env'


import { Users } from './src/collections/Users'
import { Media } from './src/collections/Media'

const filename = fileURLToPath(import.meta.url)
const dirname = path.dirname(filename)

import { PostgresAdapterResult } from '@payloadcms/db-postgres/dist/types' // Adjust the import path as necessary
import { DatabaseAdapterResult } from 'node_modules/payload/dist/database/types'

const dbConfig = postgresAdapter({
  pool: {
    connectionString: env.DATABASE_URL,
  },
});

export default buildConfig({
  admin: {
    user: Users.slug,
    importMap: {
      baseDir: path.resolve(dirname),
    },
  },
  collections: [Users, Media],
  editor: lexicalEditor(),
  secret: process.env.PAYLOAD_SECRET || '',
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
  db: dbConfig,
  sharp,
  plugins: [
    // storage-adapter-placeholder
  ],
});
```

NOTE: Here I am seeing another error: Type 'PostgresAdapterResult' is not assignable to type 'DatabaseAdapterResult'.ts(2322)
types.d.ts(580, 5): The expected type comes from property 'db' which is declared here on type 'Config'

![image](https://github.com/user-attachments/assets/2e74ef57-1707-4b11-a8bf-a26d41ca4510)

I tried to manually typecast but they dont overlap
![image](https://github.com/user-attachments/assets/fad2731a-e8b4-4227-987f-c55bd96ee5d3)

```
(alias) type PostgresAdapterResult = (args: {
    payload: Payload;
}) => any


(alias) type DatabaseAdapterResult<T = BaseDatabaseAdapter> = {
    defaultIDType: "number" | "text";
    init: (args: {
        payload: Payload;
    }) => T;
}
```

### Adapters and Plugins

none

**Comment by macamp0328** [comment]
I am experiencing the same issue. Working to add payload to an existing NextJS project, and followed the [manual steps in docs](https://payloadcms.com/docs/beta/getting-started/installation).

**Comment by pat-mw** [comment]
any luck @macamp0328 ?

**Comment by macamp0328** [comment]
> any luck @macamp0328 ?

Hey @pat-mw, since I was hitting a wall, I had put the personal project down for a bit.  I will spin it back up in the next few days and see what I can figure out.

**Comment by r1tsuu** [comment]
This possibly could have happened because you installed `@payloadcms/db-postgres` for 2.0 which uses old import `payload/versions`, you need to install with the `beta` tag
`pnpm add @payloadcms/db-postgres@beta`.
