### ISSUE TITLE
Depth is ignored when querying hasMany uploads

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#7831]
### Payload Version

3.0.0.beta-90

### Node Version

20.12.2

### Next.js Version

15.0.0-canary.107

### Describe the Bug

When trying to `find` on a collection's `upload` field with `hasMany: true`, the `depth` field is ignored and the result contains only the IDs of the uploads, not its content.

### Reproduction Steps

1. Create an upload field with `hasMany: true`
2. Create an entity with multiple values in the upload field
3. Execute `payload.find()` on the collection (I used where ID equals the entity's ID)

### Adapters and Plugins

db-postgres

**Comment by bmamouri** [comment]
I have the same issue. This is my collection config:

```js
import { CollectionConfig, CollectionSlug } from 'payload'

export const Product: CollectionConfig = {
  slug: 'product',
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
    },
    {
      name: 'variants',
      type: 'array',
      fields: [
        {
          name: 'code',
          type: 'text',
        },
        {
          name: 'name',
          type: 'text',
        },
        {
          name: 'gallery',
          type: 'upload',
          relationTo: 'media',
          hasMany: true,
          required: true,
        },
      ],
    },
  ],
}
```

This is how I am fetchint the data using local API:

```js
  const data = await payload.find({
    collection: 'product',
    depth: 10,
    pagination: true,
    sort: '-title',
  })
```

**Comment by paulpopus** [comment]
This has been fixed in the latest beta, should be out in the next release!
