### ISSUE TITLE
Local api findByID  not working as expected with fields having access control limitations

### ISSUE THREAD

**Issue by mah-alawad** [payloadcms/payload#7836]
### Payload Version

Beta

### Node Version

node:20-slim

### Next.js Version

15.0.0-canary.53

### Describe the Bug

Using findByID local api in server component return always the result of the collection including fields even if that collection fields have access limitations on read    

### Reproduction Steps

I have added to user collection role property it's a select field with roles 
```
const checkUserRole = (allRoles: Array<User['role']>, user: User): boolean =>
  user && allRoles?.some((role) => user?.role === role)

{
      name: 'role',
      type: 'select',
      options: [
        { label: 'Admin', value: 'admin' },
        { label: 'User', value: 'user' },
      ],
      required: true,
      defaultValue: 'user',
    },
```
and i have another collection pages which has the following:

```
const collectionOvens: CollectionConfig = {
  slug: 'pages',
  fields: [
    {
      name: 'title',
      label: 'Title',
      access: {
        read: (args) => checkUserRole(['admin'], args?.req?.user as User),
      },
      type: 'text',
      localized: true,
      required: true,
    },
]

```
in my  nextjs app in server component importing payload local api from getPayloadHMR 

```
  const req: PayloadRequest = {
    context: {},
    fallbackLocale: locale,
    locale,
    user: null,
  }
  const payload = await getPayloadHMR()
  const { user } = await payload.auth({ headers: headers(), req })
  if (user) {
    req.user = user
  }

 const entity = await payload.findByID({
    collection,
    id: resolved.entity.id,
    locale,
    req,
  })
```
if user is authenticated with role different from admin we can  see the title. 
the expcted behavior the title shouldn't be included in the findByID result

**Comment by JarrodMFlesch** [comment]
@mah-alawad with local operations, you need to pass the user and overrideAccess: false to the operation.

```ts
const entity = await payload.findByID({
  collection,
  id: resolved.entity.id,
  locale,
  req,
  user: req.user,
  overrideAccess: false,
})

**Comment by mah-alawad** [comment]
Thanks a lot 
is there a way to set   overrideAccess: false as default for each local api used like in nextjs app on frontend?
