### ISSUE TITLE
plugin-stripe / plugin-seo: do not depend on @payloadcms/next for endpoints

### ISSUE THREAD

**Issue by r1tsuu** [payloadcms/payload#7840]
### Payload Version

3.0.0-beta.90

### Node Version

20

### Next.js Version

15rc

### Describe the Bug

Example:
Instead of https://github.com/payloadcms/payload/blob/4bbc593dc5936d0f53e036488680c968df20bc2c/packages/plugin-seo/src/index.tsx#L136
we should just do 
```ts
 const data = await req.json!()
```

Reason: the Payload config depends on `@payloadcms/next` and so its peer dependencies. You may want to import the config outside of Next.js, like into a separate Astro website in a monorepo.

### Reproduction Steps

.

### Adapters and Plugins

plugin-stripe, plugin-seo

**Comment by paulpopus** [comment]
Fixed in https://github.com/payloadcms/payload/pull/7879
