### ISSUE TITLE
Virtual Field creates real column in PostgreSQL

### ISSUE THREAD

**Issue by henk23** [payloadcms/payload#7855]
### Describe the Bug

When creating a virtual field "fullName" like in the example, when using PostgreSQL, a column in the database `full_name varchar`will be created. It's not really a critical bug, but it bothered me when I saw it, and since it's still in beta, I hope it's okay to report it.

Also: The syntax for Virtual Fields seems a bit verbose. This probably belongs into improvements / feature requests rather than bug reports, but doing something like:

```
{
  name: 'fullName',
  type: 'virtual',
  return: ({ data }) => `${data.firstName} ${data.lastName}`,
}
```

would feel a bit easier, the `access` and `hooks` settings could then have sensible defaults. And it would probably be easier to not create a table column for this type of field?

### To Reproduce

```
{
  name: 'fullName',
  type: 'text',
  admin: {
    hidden: true,
  },
  access: {
    create: () => false,
    update: () => false,
  },
  hooks: {
    beforeChange: [
      ({ siblingData }) => {
        delete siblingData.fullName;
     },
    ],
    afterRead: [
      ({ data }) => `${data.firstName} ${data.lastName}`,
    ],
  },
},
```

### Payload Version

2.26.0

### Adapters and Plugins

db-postgres

**Comment by r1tsuu** [comment]
Hi @henk23
a PR is here https://github.com/payloadcms/payload/pull/7621 !

**Comment by henk23** [comment]
Thanks :) Did not see the PR or the Discussion. I guess this can be closed then.
