### ISSUE TITLE
Richtext field read-only in a modal.

### ISSUE THREAD

**Issue by FiniteVoid** [payloadcms/payload#7856]
### Link to reproduction

(Only 2 steps needed from Blank Template)

### Payload Version

Beta 91

### Node Version

20 LTS

### Next.js Version

Canary 104

### Describe the Bug

When opened in a modal Richtext field becomes read-only (even when no access control is implemented). 
It essentially happens when editing/creating a new item for a related collection in 'relationship' or 'upload' field.
This only happens to richText field, rest of the fields in model work fine.

### Reproduction Steps

Start off with Blank Template:
- Add a richtext field to the media collection.
- Add a relationship field for media in users collection.
- Notice the read-only richText when adding a new media from users collection in the modal.

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/8774
