### ISSUE TITLE
Filter text disappears in Media selection drawer

### ISSUE THREAD

**Issue by tsemachh** [payloadcms/payload#7865]
### Payload Version

3.0.0-beta.90

### Node Version

v22.5.1

### Next.js Version

15.0.0-canary.59

### Describe the Bug

When choosing Media from existing and filtering for some text the filtered list appears but the filtered text is removed so we don't see what we were keying in the filter.
I must say that the performance is not optimal , but clearing the search filter is not acceptable

### Reproduction Steps

Open the Web Template with seed data
- Open the Pages -> Contact -> Seo Tab 
![image](https://github.com/user-attachments/assets/e6d4071e-efa4-4bae-9946-4bbf25d5eaaa)
- Go to the meta image press choose from existing
- Filter for hero , one image with name hero appear but the search box is empty
![image](https://github.com/user-attachments/assets/937c23cc-5fd2-4774-b750-983aeab94da5)

Expected behavior, filter text stays

**Comment by philjoseph** [comment]
Moreover, when filtering to find an existing media, the search will take place after one or two characters entered, without any search button and it is totally unclear that those are search results

**Comment by tsemachh** [comment]
I think it's o.k. now - however the re-render of results is flickering , need to think of better UX here
