### ISSUE TITLE
Attempted import error: 'LexicalErrorBoundary' is not exported from '@lexical/react/LexicalErrorBoundary.js' (imported as 'It').

### ISSUE THREAD

**Issue by zelenovsky** [payloadcms/payload#7885]
### Payload Version

3.0.0-beta.91

### Node Version

v20.11.0

### Next.js Version

15.0.0-canary.104

### Describe the Bug

I get the following error after [migration](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.79)

### Reproduction Steps

-

### Adapters and Plugins

richtext-lexical

**Comment by AlessioGr** [comment]
Hey, I will need a reproduction in order to look into this. E.g. a repository I can clone down and run a command on, which will give me this error

**Comment by zelenovsky** [comment]
@AlessioGr Hi! I have just created a new project using your template for beta and copied all project files into this new project and everything works as expected) sorry for interruption
