### ISSUE TITLE
Relationship in the admin UI only shows the first 20 items

### ISSUE THREAD

**Issue by bmamouri** [payloadcms/payload#7892]
### Payload Version

3.0.0-beta.91

### Node Version

18.20.4

### Next.js Version

15.0.0-canary.104

### Describe the Bug

The admin shows only the first 20 records of a relationship.

I have a collection called Product with the following fields:

```js
export const Product: CollectionConfig = {
  slug: 'product',
  admin: {
    group: 'Products',
    useAsTitle: 'title',
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
      unique: true,
    },
    {
      name: 'categories',
      type: 'relationship',
      relationTo: 'category' as CollectionSlug,
      hasMany: true,
      admin: {
        allowCreate: false,
        sortOptions: 'code'
      }
    }
  ]
}
```

### Reproduction Steps

1. Create a collection named "Product" and "Category" which many to many relationship.
2. Create 21 category
3. Create a new product. You will observe that the cateogry 21 cannot be selected.

**Comment by Wiz1991** [comment]
Have the same issue, what's more if i keep closing and opening the select again and then just scroll up and down, at some point it loads everything.

**Comment by paulpopus** [comment]
As of the latest beta this doesn't seem to happen, happy to reopen if it does with a reproduction.

As for your other issue @Wiz1991 what's likely happening is that the lazy loading is slower and we don't show a loading indicator for which I made a new UX feature request here: https://github.com/payloadcms/payload/discussions/8147
