### ISSUE TITLE
filtering a collection with a relationship-field with an array as its relationTo results always in empty list.

### ISSUE THREAD

**Issue by vincentvandijck** [payloadcms/payload#790]
# Bug Report

Filtering a collection with a relationship-field seems to be not working at the moment, as it always returns an empty list and not the required elements. Filtering a collection with fields which are not a relationship do seem to work. 

## Expected Behavior

![image](https://user-images.githubusercontent.com/10504064/180099117-a8469800-e3b6-48c2-85c1-66751b8fdfbc.png)

in the following example I expect the post with title 'Eastern European White Hands Having Brunch in a Van' to be shown when I 

![image](https://user-images.githubusercontent.com/10504064/180099259-b5015161-1492-4b79-a35c-d4ac5eb471ce.png)

## Current Behavior

nevertheless at the moment this results in
![image](https://user-images.githubusercontent.com/10504064/180099307-5b397618-a12f-45e9-891a-ed65b9dac1a3.png)
an empty list

## Possible Solution

I could look into the source code later, but I thought I mentioned it immediately

## Steps to Reproduce

1. create a collection X that will be used as relation
2. add element to collection X called X1
3. create another collection Y with a relationship-field to X
4. add element to collection Y with a relationship to X1
5. try to filter collection Y with X -> exists -> X1
6. witness there is no element shown instead of the one element you added

**Comment by JarrodMFlesch** [comment]
If you hit the rest endpoint: `/api/posts?where[category][equals]=ID_OF_CATEGORY_HERE`

Do your results come back properly?

The issue you are describing seems to function correctly on the demo site [here](https://demo.payloadcms.com/admin/collections/posts?page=1&where%5Bor%5D%5B0%5D%5Band%5D%5B0%5D%5Bauthor%5D%5Bequals%5D=62d888f0c13f6a1b2df390c6)

**Comment by vincentvandijck** [comment]
Mm, no I still get an empty list

![image](https://user-images.githubusercontent.com/10504064/180209372-7b91522d-56dc-4b14-9513-7bbbd27aa1b6.png)
![image](https://user-images.githubusercontent.com/10504064/180209431-85e70efd-35af-43f8-b6f1-efdab4ef68dd.png)

And I agree, it does seem to work properly on the demo site.

It also looks a bit different:
![image](https://user-images.githubusercontent.com/10504064/180209625-5ca72325-046d-498b-b28a-aa24206d2fb8.png)
![image](https://user-images.githubusercontent.com/10504064/180209672-9b0b10cf-52dd-4287-9411-789574f25394.png)
as you can see, with my version it is a dropdown where I can select only 1 category, but with the demo I can select multiple categories.

**Comment by vincentvandijck** [comment]
ok, I think I found the culprit.

I defined the schema for the category-field as follows:
![image](https://user-images.githubusercontent.com/10504064/180211107-24b2368a-294b-49ba-9924-bc06bd48600a.png)
I think there are some examples in your docs that follow this patter too.
Nevertheless if i remove the square brackets:
![image](https://user-images.githubusercontent.com/10504064/180211390-66a706e5-a61d-4be9-ad53-813b4e55c2c4.png)

it does look a bit weird in the list-view
![image](https://user-images.githubusercontent.com/10504064/180211528-a724f7e6-4f28-48f2-a824-46a7f1009530.png)
but I am able to filter the category
![image](https://user-images.githubusercontent.com/10504064/180211633-7d2d187c-aae4-4ac7-9933-4f47c586ad04.png)

**Comment by vincentvandijck** [comment]
Also, tangentially related, when I removed the brackets, the category-fields from the already entered data became corrupted.
![image](https://user-images.githubusercontent.com/10504064/180212868-33b093fa-63a4-41af-840b-0e0c1bc9d0f3.png)
I suppose this is expected behavior in a way, but a bit frustrating right now the only way to fix it is to enter the database and correct the data directly in mongodb.

**Comment by vincentvandijck** [comment]
the weird list-view was solved once I manually adjusted the data in mongodb (from category as an object with a name- and an id-key to category as a single id-string)
![image](https://user-images.githubusercontent.com/10504064/180214099-35917534-d8d5-4d0c-a1df-4d71ba8b217a.png

**Comment by vincentvandijck** [comment]
So a more correct title would be:
filtering a collection with a relationship-field with an array as its value results always in empty list.

**Comment by jmikrut** [comment]
OK - here's the issue here.

You're trying to ask Payload for posts where `category` EQUALS `id`. But, a `hasMany` category will never _equal_ and ID specifically, because it's an array.

So, you need to use `category` IN `id`, like this:

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/6651896/180270539-f88e1817-7996-4405-a6b9-311c51b5f263.png">

This works on demo and I'm sure it's the issue. If you want to use `equals`, you'd need to pass in an array of categories, which is currently not possible in the admin UI. But it is certainly possible with GraphQL / REST / Local Node API queries. So I'm going to close this one as there is no issue per se, more of a feature enhancement to allow `equals` queries on `hasMany` relationship fields from the admin UI.

Does that make sense?
