### ISSUE TITLE
when publishing from a draft, only 10 were published

### ISSUE THREAD

**Issue by xxarupakaxx** [payloadcms/payload#7905]
### Link to reproduction

https://github.com/payloadcms/payload/commit/4e855bd9a59b518cb2c7000c11703bf591376825

### Describe the Bug

When more than 10 collections were selected for publication, only 10 were published.
This is because I set a limit when updating.

### To Reproduce

For example, suppose there were over 100 collections in BOOK
They are in draft form.
Select 100 books to be updated.
When you publish them, only 10 will be published.

### Payload Version

2.23.1

### Adapters and Plugins

db-postgres

**Comment by DanRibbens** [comment]
Closed with https://github.com/payloadcms/payload/pull/7906
