### ISSUE TITLE
Server side live preview is never turned off

### ISSUE THREAD

**Issue by hannanilsson** [payloadcms/payload#7907]
### Link to reproduction

payload website template

### Environment Info

```text
Payload: 3.0.0-beta.91
Node: v20.14.0
next: 15.0.0-canary.104

(Completely new payload website template, used "npx create-payload-app@beta my-project -t website"
```

### Describe the Bug

Hi, I keep getting stuck on the fact that I think live preview seems wonky. If you once use live preview, you will always be served draft versions since next.js draft-mode has been enabled but never disabled. 
Am I missing something here? This does seem very prone to having users that will panic because they will think they have published the draft changes.

Other than this, that next.js draft mode is supposed to be used to enable live preview is not at all mentioned in the documentation, it does not even mention that you need to turn on versions in payload.

### Reproduction Steps

1. Login
2. Edit a page using live preview
3. Do NOT publish the changes
4. Logout
5. Go to the page (and see the draft version)

**Comment by paulpopus** [comment]
So strictly speaking it's not up to Payload to manage next's draftMode in this case so it's a manual task to exit out of it.

As of https://github.com/payloadcms/payload/pull/7991 we now display "exit preview mode" in the admin toolbar when navigating around the site to help you exit draft mode
