### ISSUE TITLE
Rich text field is broken in drawer when adding a new relationship item

### ISSUE THREAD

**Issue by radudevit** [payloadcms/payload#7912]
### Environment Info

```text
Payload: v3.0.0-beta.94
Node: v20.15.1
Next: 15.0.0-canary.104
```

### Describe the Bug

The richText field from a relationship collection is broken when creating a new item from the edit page, and the current collection also has a richText field.

### Reproduction Steps

1. Create a collection -> `Collection_1` with a richText field - `richText1`
2. Create another collection -> `Collection_2` with a richText field - `richText2`
3. Add a `relationship` field to `Collection_2`, which relates to `Collection_1`
4. Open the Edit page of `Collection_2`
5. Click the plus button from the relationship field to create a new `Collection_1` item
6. **The richText1 field is broken.**

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/8774
