### ISSUE TITLE
Wrong block indication when an error occurred

### ISSUE THREAD

**Issue by ChannKan** [payloadcms/payload#7914]
### Link to reproduction

https://github.com/shefing/PayloadSplitBug

### Environment Info

```text
New instance of payload website template
```

### Describe the Bug

When I have a content page that contains many blocks one after the next (**More then 10 blocks**),
and I have an issue with one of the blocks (For example : a required field is empty ),
I get a red error indication frame on the second block and on the block with the issue.

Attached screenshot’s (I have a problem in block number 11 and get red indication frame for block 2 and block 11)

Second block:
<img width="1097" alt="Screenshot 2024-08-28 at 13 07 23" src="https://github.com/user-attachments/assets/feb653de-4307-4060-9024-f86f9c48e5f0">

Block with the issue: 
<img width="1153" alt="Screenshot 2024-08-28 at 13 07 38" src="https://github.com/user-attachments/assets/3dd7f714-2f8d-410f-a5ef-ac533b790c41">

 

### Reproduction Steps

**Step for reproduction:**

1. Clone the reproduction repo **or** create a new payload website template
2. Create a new Page instance
3. In the Content tab:
       - Add 10 Archive blocks
       - Add a media block and don’t  fill it in

4. Try to publish the page

**Expected :**
A red error indication frame only on block 11 (media block)

**Actual:**
A red error indication frame on block 11 (media block) _and on the second block (an ok archive block)_

**Comment by tsemachh** [comment]
![image](https://github.com/user-attachments/assets/7d655af9-065f-4bcc-bfdf-c8300848ac33)

This demonstrates the issue in web template env

**Comment by denolfe** [comment]
Agree this could be improved and confusing because it is using the array index.

**Comment by GermanJablo** [comment]
Thanks for reporting it @ChannKan.
Fix coming with https://github.com/payloadcms/payload/pull/7963
