### ISSUE TITLE
Lexical features don't indicate that they are selected

### ISSUE THREAD

**Issue by adameli22** [payloadcms/payload#7925]
### Environment Info

```text
Next.js (15.0.0-canary.132)
Payload 3 beta.94
```

### Describe the Bug

When selecting different writing features, the new FixedToolbarFeature does not indicate that what features are in use. 
The floating editor for highlighted text does also not show used feature on highlighted text.

this video is from a new blank project.

https://github.com/user-attachments/assets/bd1259cd-86d2-4cf4-a396-a2ccb10d2dd3

### Reproduction Steps

create a new project
use the editor anywhere

**Comment by GermanJablo** [comment]
Thanks for the report @adameli22! I can reproduce it with the floating/inline toolbar, but not with the fixed toolbar. 🤔

Could you please elaborate a bit more on the steps to reproduce this? Is this happening with a fresh clone? Exactly what commands do you use and how do you access the editor you are testing?

**Comment by adameli22** [comment]
ok so I was half way through writing a detailed replay on the whole process on how I recreated this, but then I went back into the project and tested it again, but this time with a twist 😎 ... Im guessing you are using dark mode?

So I found out the FixedToolbar is only a problem in light mode but is fine in dark mode and the floating toolbar is a problem in both light and dark.
But I can still write the whole process if you still have a problem recreating 😃

**Comment by GermanJablo** [comment]
Ok, this should be fixed in PR #7936.

I've tested it with both toolbars, dark mode and light mode, and it works fine.

Thank you!

**Comment by adameli22** [comment]
awesome, thank you for the super fast responses and fix 😃
