### ISSUE TITLE
Unknown file extension ".svg" error when running generate:types

### ISSUE THREAD

**Issue by tophermurphy** [payloadcms/payload#7927]
### Environment Info

```text
Payload: 3.0.0-beta.94
Nextjs: 15.0.0-canary.104
Node: v18.20.3
```

### Describe the Bug

Unable to generate:types when having .svg files in the src directory. I am able to import the images with no problem. I even tried adding a custom module declaration and added it to ts.config

### Reproduction Steps

Add a folder with an .svg file in the src directory. Run `pnpm generate:types`

**Comment by JarrodMFlesch** [comment]
I am not sure this is a real issue. Have you migrated all your custom component imports so they are referenced via the string path to the file? Components, metadata, icons, etc, should be referenced via a string path.

Going to close, if you have a reproduction link that you would like to share we can look at re-opening this.

**Comment by tophermurphy** [comment]
@JarrodMFlesch 
Thanks for looking into this.
What is the correct way to reference the path? I'm trying to add imageUrl to blocks. I was able to get it to work by importing the SVG and then referencing Image.src, but then the generate:type issue happens.

See below. I tried a few different variations of the just the image path in the imageUrl field.

```
import { Block } from "payload";
import SectionOptions from "../options/SectionOptions";
import { SectionBlocks } from "../blocks/BlockList";
import Image from "../assets/block-icons/Section.svg";

export const Section: Block = {
  slug: "section",
  interfaceName: "SectionSection",
  imageURL: Image.src,
```
Thanks for your help

**Comment by tophermurphy** [comment]
@JarrodMFlesch Disregard the last post. I figured it out. Static assets in the "public" directory in the root. Ignore public in the file path. Maybe you can add this to the docs. 

Thanks for the time.
