### ISSUE TITLE
Error: Mismatching "payload" dependency versions found: @payloadcms/ui/shared@3.0.0-beta.94 (Please change this to 3.0.0-beta.95).

### ISSUE THREAD

**Issue by zelenovsky** [payloadcms/payload#7955]
### Environment Info

```text
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: 9.5.0
Relevant Packages:
  payload: 3.0.0-beta.95
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.95
  @payloadcms/graphql: 3.0.0-beta.95
  @payloadcms/next/utilities: 3.0.0-beta.95
  @payloadcms/richtext-lexical: 3.0.0-beta.95
  @payloadcms/translations: 3.0.0-beta.95
  @payloadcms/ui/shared: 3.0.0-beta.95
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 12
```

### Describe the Bug

I am getting this error:
`Error: Mismatching "payload" dependency versions found: @payloadcms/ui/shared@3.0.0-beta.94 (Please change this to 3.0.0-beta.95).`
but I have 95 version of ui package

### Reproduction Steps

1. pnpm update
2. pnpm dev (the same issue with pnpm devsafe)

**Comment by tylandavis** [comment]
I would suggest you try removing your `node_modules` directory and `pnpm.lock` file, and then try reinstalling packages. Perhaps there is something being cached with pnpm.

**Comment by zelenovsky** [comment]
@tylandavis thanks, removing node_modules solved the issue
