### ISSUE TITLE
richtext-lexical (Table) - Expected CellNode to have a RowNode parent

### ISSUE THREAD

**Issue by rilrom** [payloadcms/payload#7961]
### Environment Info

```text
Binaries:
  Node: 20.16.0
  npm: 10.8.1
  Yarn: 1.22.22
  pnpm: 9.9.0
Relevant Packages:
  payload: 3.0.0-beta.95
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.95
  @payloadcms/email-nodemailer: 3.0.0-beta.95
  @payloadcms/graphql: 3.0.0-beta.95
  @payloadcms/live-preview: 3.0.0-beta.95
  @payloadcms/live-preview-react: 3.0.0-beta.95
  @payloadcms/next/utilities: 3.0.0-beta.95
  @payloadcms/plugin-cloud: 3.0.0-beta.95
  @payloadcms/plugin-form-builder: 3.0.0-beta.95
  @payloadcms/plugin-nested-docs: 3.0.0-beta.95
  @payloadcms/plugin-redirects: 3.0.0-beta.95
  @payloadcms/plugin-seo: 3.0.0-beta.95
  @payloadcms/richtext-lexical: 3.0.0-beta.95
  @payloadcms/translations: 3.0.0-beta.95
  @payloadcms/ui/shared: 3.0.0-beta.95
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
  Available memory (MB): 25582
  Available CPU cores: 16
```

### Describe the Bug

When selecting multiple cells in a richtext-lexical table and attempting to click the three dots, the following error occurs:

_"Expected CellNode to have a RowNode parent"_

### Reproduction Steps

1. Create a fresh repo using the [reproduction guide](https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md).
2. Add `EXPERIMENTAL_TableFeature` to `@payloadcms/richtext-lexical`.
3. Add a table to rich text content.
4. Select two cells.
5. Attempt to click the three dots button.
6. Error is shown.

### Adapters and Plugins

db-postgres, richtext-lexical

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/7964
