### ISSUE TITLE
Node 22.7.0 Compatibility issues

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#7965]
### Link to reproduction

https://github.com/payloadcms/payload/tree/build/bump-nodejs

### Environment Info

```text
Payload: monorepo
Next.js: monorepo
Node.js: 22.7.0
```

### Describe the Bug

There appears to be some sort of utf-8 related compatibility issue with Node 22

Branch: https://github.com/payloadcms/payload/tree/build/bump-nodejs
PR with failing action: #7935

**MongoDB**
<img width="859" alt="CleanShot 2024-08-28 at 19 54 42" src="https://github.com/user-attachments/assets/57a7033f-d886-4fc4-8eea-28baa296a648">

**Postgres**
<img width="988" alt="CleanShot 2024-08-28 at 19 52 53" src="https://github.com/user-attachments/assets/8677e4f5-ad2f-4f35-b5ef-1a44eb945578">

### Reproduction Steps

Run `pnpm test:int` on Node 22 with either postgres or mongodb

**Comment by andershermansen** [comment]
Regression in node 22.7.0
https://github.com/nodejs/node/issues/54543

**Comment by denolfe** [comment]
Good find @andershermansen ! 🙏

**Comment by denolfe** [comment]
Bug with Node.js, not Payload 👍
