### ISSUE TITLE
ACL: data and id is undefined when called via local api

### ISSUE THREAD

**Issue by Wiz1991** [payloadcms/payload#7972]
### Environment Info

```text
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.96
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.96
  @payloadcms/email-nodemailer: 3.0.0-beta.96
  @payloadcms/graphql: 3.0.0-beta.96
  @payloadcms/next/utilities: 3.0.0-beta.96
  @payloadcms/plugin-redirects: 3.0.0-beta.96
  @payloadcms/plugin-search: 3.0.0-beta.96
  @payloadcms/richtext-lexical: 3.0.0-beta.96
  @payloadcms/richtext-slate: 3.0.0-beta.96
  @payloadcms/translations: 3.0.0-beta.96
  @payloadcms/ui/shared: 3.0.0-beta.96
  react: 19.0.0-rc-fb9a90fa48-20240614
  react-dom: 19.0.0-rc-fb9a90fa48-20240614
Operating System:
  Platform: linux
  Arch: x64
  Version: #202405300957~1721174657~22.04~abb7c06 SMP PREEMPT_DYNAMIC Wed J
  Available memory (MB): 15922
  Available CPU cores: 6
```

### Describe the Bug

Calling findByID() does not populate id and data on read access function. 
If i do a regular REST API call, the ID only is available. 

### Reproduction Steps

1. create a collection with any number of fields
2. define read access function
3. log id and data
4. call payload.findByID()

**Comment by r1tsuu** [comment]
It's not expected to have `data` there, since the access function is executed _before_ the document is retrieved from the database (unlike for create/update/delete operations). You need to return a `Where` query from there.
