### ISSUE TITLE
Dev mode prompt during pnpm start

### ISSUE THREAD

**Issue by zelenovsky** [payloadcms/payload#7986]
### Environment Info

```text
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: 9.5.0
Relevant Packages:
  payload: 3.0.0-beta.95
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.95
  @payloadcms/graphql: 3.0.0-beta.95
  @payloadcms/next/utilities: 3.0.0-beta.95
  @payloadcms/richtext-lexical: 3.0.0-beta.95
  @payloadcms/translations: 3.0.0-beta.95
  @payloadcms/ui/shared: 3.0.0-beta.95
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 12
```

### Describe the Bug

When I build my app and start it using `pnpm start` command I face this prompt:
`It looks like you've run Payload in dev mode, meaning you've dynamically pushed changes to your database.
If you'd like to run migrations, data loss will occur. Would you like to proceed?`

Due to this prompt I can't migrate inside a docker container. So why payload says that I am in dev mode when I actually in prod mode? and how to change it to prod or disable the prompt?

### Reproduction Steps

1. use this db config
```js
db: postgresAdapter({
		pool: {
			connectionString: process.env.DATABASE_URI || "",
		},
		prodMigrations: migrations,
		push: false,
	}),
```

2. pnpm build
3. pnpm start

**Comment by denolfe** [comment]
If you've connected to the database when in dev mode and then try to run a production migration against it. This is expected.

If you want to avoid this message, delete the `dev` migration inside your `payload_migrations` table.
