### ISSUE TITLE
/api/users/me timeout

### ISSUE THREAD

**Issue by nexflo** [payloadcms/payload#8012]
### Environment Info

```text
Payload beta 96
```

### Describe the Bug

I log in via an api call users/me.
First time it works, after refresh the command takes AGES and at some stage idles out?

<img width="288" alt="image" src="https://github.com/user-attachments/assets/91c6b1d4-28f2-4ef3-adc8-224e3a5908d9">

### Reproduction Steps

Login once, refresh pages multiple times.

**Comment by paulpopus** [comment]
All of my requests are sub 100ms, can you provide a reproduction here please?

Do you have any hooks or something blocking/slowing down this request? Are other requests in the admin panel better?

**Comment by JarrodMFlesch** [comment]
Closing, no repro provided.
