### ISSUE TITLE
React version is being checked when using the local API only

### ISSUE THREAD

**Issue by linobino1** [payloadcms/payload#8013]
### Environment Info

```text
Binaries:
  Node: 21.7.1
  npm: 10.5.0
  Yarn: 1.22.21
  pnpm: 8.15.7
Relevant Packages:
  payload: 3.0.0-beta.97
  @payloadcms/db-mongodb: 3.0.0-beta.97
  @payloadcms/live-preview: 3.0.0-beta.97
  @payloadcms/live-preview-react: 3.0.0-beta.97
  @payloadcms/translations: 3.0.0-beta.97
  react: 18.3.1
  react-dom: 18.3.1
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
```

### Describe the Bug

I want to use the local API in a Remix project using React 18, but payloads `dependencyChecker` throws an error because of the React version.

```
Error: Dependency react is on version 18.3.1, but >=19.0.0-rc-06d0b89e-20240801 or greater is required. Please update this dependency.
```

Expected behaviour: no React version mismatch error, since I don't need React in the local API.

### Reproduction Steps

install only the `payload` module in a React 18 app, and initialize payload.

**Comment by AlessioGr** [comment]
Good catch, thanks for reporting! I'll move the react dependency checker from our `payload` package to our `ui` or `next` package.

For now, you can set the `PAYLOAD_DISABLE_DEPENDENCY_CHECKER` environment variable to `true` in order to disable the dependency checker

**Comment by linobino1** [comment]
> For now, you can set the `PAYLOAD_DISABLE_DEPENDENCY_CHECKER` environment variable to `true` in order to disable the dependency checker

That's great!

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/8323
