### ISSUE TITLE
Meta Image SEO Plugin Issue

### ISSUE THREAD

**Issue by erwin-gapai** [payloadcms/payload#8016]
### Environment Info

```text
Payload: v3 beta 97
Node: v20.12.2
NextJs: 15.0.0-canary.104
```

### Describe the Bug

I freshly installed Payload CMS v3 beta 97, and tried to add/update the meta image of a post/page. It successfully add the media to Media collection, using `Create new` or `Choose from existing`, but don't update the Meta Image field.
No error shown in the client or console.
The only error shown is on server side when I click on `Create new`.
```
[14:19:31] ERROR: aborted
    err: {
      "type": "Error",
      "message": "aborted",
      "stack":
          Error: aborted
              at abortIncoming (node:_http_server:794:17)
              at socketOnClose (node:_http_server:788:3)
              at Socket.emit (node:events:530:35)
              at TCP.<anonymous> (node:net:337:12)
              at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
      "code": "ECONNRESET"
    }
[14:19:31] ERROR: There was an error building form state
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'length')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'length')
```

### Reproduction Steps

1. Install Payload v3, then upgrade to the latest beta version.
2. Go to `/admin` and create new admin user.
3. Login
4. Seed the database
5. Go to one of pages/posts and go to SEO tab
6. Try to add/update the SEO image

### Adapters and Plugins
- "@payloadcms/plugin-seo": "3.0.0-beta.97",

**Comment by paulpopus** [comment]
Fixing in https://github.com/payloadcms/payload/pull/8024

I haven't been able to replicate the server side error so it might be unrelated to this. You can let me know and we can re-open this issue after this is released

**Comment by erwin-gapai** [comment]
Hi thanks for the fix. I'm now in beta 97, how to apply this change?

**Comment by paulpopus** [comment]
It will be available in the next beta release today
