### ISSUE TITLE
Postgres column name for select fields are not snake_case

### ISSUE THREAD

**Issue by willviles** [payloadcms/payload#8027]
### Environment Info

```text
Binaries:
  Node: 18.20.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: 9.1.0
Relevant Packages:
  payload: 3.0.0-beta.97
  next: 15.0.0-canary.104
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 12
```

### Describe the Bug

Postgres column names for select fields are not converted to snake case, unlike all other fields.

For example, an _input_ field with the name `fooBar` will result in a pg column name of `foo_bar`. 
However, a _select_ field named `fooBar` will create a column called `fooBar`.

The offending logic may be here, where the `fieldName` argument should instead be `columnName`: https://github.com/payloadcms/payload/blob/9bcdf0dc81012ea045fad126892f54963b792b20/packages/drizzle/src/postgres/schema/traverseFields.ts#L337

### Reproduction Steps

1. Configure the Postgres db adapter
2. Create a collection (e.g. Foo)
3. Create an input field with a camelCase name (e.g. `fooInput`)
4. Create a select field with a camelCase name (e.g. `fooSelect`)
5. Run `payload migrate:create`
6. Open the migration output file.

Expected output:
```SQL
CREATE TABLE IF NOT EXISTS "foos" (
  "foo_input" varchar,
  "foo_select" "enum_foos_foo_select",
);
```

Actual output:
```SQL
CREATE TABLE IF NOT EXISTS "foos" (
  "foo_input" varchar,
  "fooSelect" "enum_foos_foo_select",
);
```

### Adapters and Plugins

db-postgres

**Comment by r1tsuu** [comment]
Looks like it doesn't break anything, but a patch could be potentially breaking because of needed migration, need to think here a bit

**Comment by willviles** [comment]
I imagine this is something that will need to be documented as a breaking change, but won't prompting the user to generate a new migration automatically solve this with `RENAME COLUMN` statements for any affected fields?

**Comment by r1tsuu** [comment]
> I imagine this is something that will need to be documented as a breaking change, but won't prompting the user to generate a new migration automatically solve this with `RENAME COLUMN` statements for any affected fields?

Yes, it will work, just you'd need to make sure to not push the update to the prod without creating a migration. There could be few more possible changes that change the db schema, I think it's reasonable to put them in a 1 version. Anyway, we need to discuss it

**Comment by r1tsuu** [comment]
@willviles PR is here https://github.com/payloadcms/payload/issues/8027

**Comment by r1tsuu** [comment]
Merged
