### ISSUE TITLE
richtext-lexical: indent CSS not working

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#8038]
https://github.com/user-attachments/assets/cf3e27dc-b5bf-42ee-8296-d472fbb2c47b

This seems to only affect the styling after pressing the indent button. If I indent, then save, then reload the page, the item appears correctly indented.

Also we should check if indenting and aligning nodes such as relationship or upload nodes is working

**Comment by GermanJablo** [comment]
Fixed in #8138
