### ISSUE TITLE
Search for media from an upload field doesn't work.

### ISSUE THREAD

**Issue by radudevit** [payloadcms/payload#8039]
### Environment Info

```text
Node: 20.15.1
Payload: 3.0.0-beta.97
Next: 15.0.0-canary.104
```

### Describe the Bug

Search for media from an upload field doesn't work.

### Reproduction Steps

1. Open a collection with an upload field
2. Click on Choose from existing button to select an existing image
3. Search for a file in the drawer
4. After you've typed something in the search field, the list is updated, but also the entire component is re-rendered, and the value from the search field is lost. You cannot reset the search field anymore

**Comment by paulpopus** [comment]
This will be fixed in this PR https://github.com/payloadcms/payload/pull/8081 !
