### ISSUE TITLE
payload-3.0-demo repo env and config content and readme inconsistent

### ISSUE THREAD

**Issue by vectorkovacspeter** [payloadcms/payload#8040]
### Environment Info

```text
Payload: 3.0.0-beta.90
nextJS: v15.0.0-canary.104
Node: v20.10.0
```

### Describe the Bug

If you try to run the cloned code with the steps on the readme with local postgres using the .\start-database.sh script
1. Clone the repo to your computer (`git clone git@github.com:payloadcms/payload-3.0-demo.git`)
2. `cd` into the new folder by running `cd ./payload-3.0-demo`
3. Copy the `.env.local.example` by running `cp .env.local.example .env.local` in the repo, then fill out the values including the connection string to your DB
4. Install dependencies with whatever package manager you use (`pnpm i`, `npm install`, `yarn`, etc.). `pnpm` is highly recommended. The usage of yarn v1 is discouraged.
5. Start your database. For local postgresql use `.\start-database.sh` to start it in docker container.
6. Fire it up (`pnpm dev`, `npm run dev`, `yarn dev`, etc.)
7. Visit https://localhost:3000 and log in with the user created within the config's `onInit` method

Its not gona work, because in the **.env.local.example** file a MONGODB_URI is provided, not the POSTGRES_URI, and also the **payload.config.ts** uses mongooseAdapter. 

So to fix this, you must change these to postgre, or the demo should provide a mongo container commands in the `.\start-database.sh` file

### Reproduction Steps

1. Clone the repo to your computer (`git clone git@github.com:payloadcms/payload-3.0-demo.git`)
2. `cd` into the new folder by running `cd ./payload-3.0-demo`
3. Copy the `.env.local.example` by running `cp .env.local.example .env.local` i
4. Install dependencies with whatever package manager you use `pnpm i`
5. Start your database with `.\start-database.sh` 
6. Fire it up `pnpm dev`
7. Visit https://localhost:3000

**Comment by denolfe** [comment]
The demo repo was made with the understanding that you'll need to adjust a few values manually in order to switch between the databases.

If you're wanting something that will adjust the config for you, try using `pnpx create-payload-app@beta` and go through the steps.
