### ISSUE TITLE
richtext-lexical: cmd+A within a block sub-field selection is incorrect

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#8047]
https://github.com/user-attachments/assets/fdf3f842-efa4-4eac-9884-641b39b8ab4f

1. create a lexical block with a text sub-field
2. Type in that text field
3. press CMD+A and then CMD+X

**Expected:** the text within the text field is selected, and then deleted

**Reality:** nothing is selected (visually), and upon pressing CMD+X, the entire lexical parent editor is deleted, not just the contents of the text field.

Should add an e2e test to ensure this works as expected as well

**Comment by GermanJablo** [comment]
I was able to reproduce this in the Lexical playground. Apparently it's a bug that doesn't update the selection inside DecoratorNodes.

I have opened https://github.com/facebook/lexical/issues/6632 so I am closing this one. Let me know if you think we should fix this ourselves and we'll reopen it.
