### ISSUE TITLE
cannot scroll while mouse is hovering over code field

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#8051]
https://github.com/user-attachments/assets/22a9fdea-f99f-4ec9-9f23-d2d7eb5e2931

While scrolling down, if the mouse is over a code field (probably json fields as well), you can't scroll. While it makes sense for it to behave that way, such an aggressive scroll lock is extremely annoying.

I would very much prefer one or some of the following solutions:
- only scroll code field if it's focused / if you click on it
- make the scroll lock less aggressive, so the mouse has to be hovering without movement over that code block for longer until it locks the scroll to itself. For example, GitHub code blocks are way less aggressive
- Only make it scroll lock if there is code to scroll through. Currently, scroll is locked even if there is no scrollbar

**Comment by GermanJablo** [comment]
PR is done, waiting review

**Comment by Harsha707** [comment]
Hi @AlessioGr and @GermanJablo,

I’ve made the changes based on the suggestions from @AlessioGr. Please review the updated PR. You may consider this if you still want to maintain the height and scroll functionality.

Thanks!

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/8209
