### ISSUE TITLE
Collection search not working as intended

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#806]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/70709113/180650115-3fa4329f-aae1-490f-9eef-92298857b8cc.png">

<img width="678" alt="image" src="https://user-images.githubusercontent.com/70709113/180650124-60c82842-0e1e-49a9-a7da-ab28fb6e0207.png">

Images should be self-explanatory. "Kö" gives the correct results, but "Kös" does not even though the name is "Köstekci".

**Comment by jmikrut** [comment]
Good catch - reproduced - we're going to deploy a fix to this shortly!
