### ISSUE TITLE
richtext-lexical: merging cells onto already merged cells throws errors

### ISSUE THREAD

**Issue by rilrom** [payloadcms/payload#8062]
### Environment Info

```text
Binaries:
  Node: 20.16.0
  npm: 10.8.1
  Yarn: 1.22.22
  pnpm: 9.9.0
Relevant Packages:
  payload: 3.0.0-beta.98
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.98
  @payloadcms/email-nodemailer: 3.0.0-beta.98
  @payloadcms/graphql: 3.0.0-beta.98
  @payloadcms/live-preview: 3.0.0-beta.98
  @payloadcms/live-preview-react: 3.0.0-beta.98
  @payloadcms/next/utilities: 3.0.0-beta.98
  @payloadcms/plugin-cloud: 3.0.0-beta.98
  @payloadcms/plugin-form-builder: 3.0.0-beta.98
  @payloadcms/plugin-nested-docs: 3.0.0-beta.98
  @payloadcms/plugin-redirects: 3.0.0-beta.98
  @payloadcms/plugin-seo: 3.0.0-beta.98
  @payloadcms/richtext-lexical: 3.0.0-beta.98
  @payloadcms/translations: 3.0.0-beta.98
  @payloadcms/ui/shared: 3.0.0-beta.98
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Wed Mar 2 00:30:59 UTC 2022
  Available memory (MB): 25582
  Available CPU cores: 16
```

### Describe the Bug

When you have some merged cells, then attempt to merge another cell into those merged cells, errors are thrown.

![lexical-error](https://github.com/user-attachments/assets/7b33484a-e4b5-438e-8af4-b8106ea4cc0f)

### Reproduction Steps

1. Create a lexical rich text table (default 5x5).
2. Merge 4 of the 5 top row cells.
3. Attempt to merge the last cell into the other merged cells.
4. Errors are thrown.

![lexical-error-1](https://github.com/user-attachments/assets/2b5b78d0-5b0a-4864-9764-1389100cd8b2)

### Adapters and Plugins

db-postgres, richtext-lexical

**Comment by rilrom** [comment]
Upon further inspection I am able to replicate this in lexical playground.

**Comment by GermanJablo** [comment]
That would be great @rilrom, thanks a lot!

**Comment by GermanJablo** [comment]
I see this is going to be fixed in the next release of Lexical. Thanks @rilrom!

https://github.com/facebook/lexical/pull/6607
