### ISSUE TITLE
Local API returns `draft` documents with null fields in production

### ISSUE THREAD

**Issue by PlagueFPS** [payloadcms/payload#8077]
### Environment Info

```text
"payload": "^3.0.0-beta.97",
"next": "^15.0.0-canary.136",
"node": 21.0.0
```

### Describe the Bug

In production, the local API returns draft documents with the `id`, `_status`, `updatedAt`, and `createdAt` fields filled in correctly while all other fields are returned as null. The local API shouldn't return drafts at all unless `draftMode` is enabled in production.

### Reproduction Steps

1. setup payload
2. enable versions and drafts
3. create a draft
4. query that collection with the `draft` property in the query, passing true if in `draftMode` or in development and false anywhere else
5. console.log() the result to find the draft document returned with mostly null fields except the ones explained above.

**Comment by paulpopus** [comment]
I tried to reproduce this but couldn't. I'm getting the draft data as expected with my fields filled in.

If you're still encountering this on the latest beta, could you provide a reproduction please?

**Comment by PlagueFPS** [comment]
> I tried to reproduce this but couldn't. I'm getting the draft data as expected with my fields filled in.
> 
> If you're still encountering this on the latest beta, could you provide a reproduction please?

What? That's even worse, the issue I was stating is that there shouldn't be any drafts being returned at all. It's a production environment why are drafts being returned via the local API if we are not in `draftMode`

**Comment by Collexi-Dev** [comment]
> sounds like it could be the same issue as this one: #6813
> 
> I provided some repro steps there

Commented on that issue but linking here for visibility: https://github.com/payloadcms/payload/issues/6813#issuecomment-2358997794

Also experiencing the same where I am getting draft docs while explicitly specifying `drafts: false` using the Local API

**Comment by JarrodMFlesch** [comment]
I am going to close this issue as I do not think it is real. 

When querying with draft: false, currently this means the returned documents will be the last published version of a doc **or** the last saved version if no **published** versions exist for a document.

If you are looking to query **only** published documents you will need to constrain your query with 

```ts
payload.find({
  collections: 'posts',
  where: {
    status: {
      equals: 'published'
    }
  }
})
```

The current draft argument is more of a "latest" query, as in, give me the newest updates on a document. I hope this helps!
