### ISSUE TITLE
Query Strings removed upon navigation in admin

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#8086]
### Environment Info

```text
Binaries:
  Node: 22.6.0
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 9.7.1
Relevant Packages:
  payload: 3.0.0-beta.99
  next: 15.0.0-canary.104
```

### Describe the Bug

Query strings in the URL are being stripped from the URL when using the back button in the Admin

https://github.com/user-attachments/assets/88d6fa92-4df0-4781-b0ba-fcbbf5090226

### Reproduction Steps

1. Navigate to List view of a collection
2. Type in a filter, note the query strings added
3. Click on any document
4. Press back button in browser
5. Note the query strings that were there previously are no longer there.

**Comment by denolfe** [comment]
Likely related to the query string rework you're doing @paulpopus . Just needed it tracked.

**Comment by paulpopus** [comment]
Can confirm it's fixed in https://github.com/payloadcms/payload/pull/8081
