### ISSUE TITLE
Blocks field type: issue sync drag and drop

### ISSUE THREAD

**Issue by pcarillion** [payloadcms/payload#8090]
### Environment Info

```text
"payload": "3.0.0-beta.74",
    "react": "19.0.0-rc-4f604941-20240830",
    "node": "20.x",
    "next": "15.0.0-canary.130",
```

### Describe the Bug

In my Page collection, I have a `blocks` type field
```
...
  {
      name: 'layout',
      type: 'blocks',
      minRows: 1,
      maxRows: 20,
      blocks: [
        QuoteBlock,
       ...
      ],
    },
...
```
When adding blocks to this field, I have several side effects:

1/ When clicking "save", blocks uncollapse randomly:
Before "Save"
![Screenshot 2024-09-06 at 14 35 17](https://github.com/user-attachments/assets/a9545c08-f39a-49f6-88ff-186ab2708721)
On "Save" click
![Screenshot 2024-09-06 at 14 35 28](https://github.com/user-attachments/assets/b0e9bd64-0800-4609-a1a4-966c7f77e7fa)

2/ when clicking "save", blocks order is sometimes modified and deleted blocks reappear, in a complete unstable way
Before "Save"
![Screenshot 2024-09-06 at 14 38 19](https://github.com/user-attachments/assets/b90d62de-76b9-413f-a65d-440d376bf7ae)
On "Save" click (not doing anything else)
![Screenshot 2024-09-06 at 14 38 35](https://github.com/user-attachments/assets/daf4a294-a25a-42b3-a88d-8f58ba82894f)
=> note that database is correct but ux is very confusing 

### Reproduction Steps

- create a blocks field 
- add blocks to your blocks field
- play with blocks, adding, removing, changing order
- press "save" and see result

**Comment by paulpopus** [comment]
Can you test this on the latest beta please? We've since pushed quite a few fixes to the UI

**Comment by pcarillion** [comment]
Yes thanks it is fixed wit `beta.99`.
