### ISSUE TITLE
Getting Unwated Redirect on Openning The website

### ISSUE THREAD

**Issue by gujral1997** [payloadcms/payload#8093]
### Environment Info

```text
Payload: 3.0.0-beta.78
Next.js: ^15.0.0-rc.0
Node.js: v20.9.0
```

### Describe the Bug

Getting unwanted redirect on opening the payload website template

<img width="1428" alt="Screenshot 2024-09-06 at 9 39 19 PM" src="https://github.com/user-attachments/assets/46457e4e-baf8-4848-b241-9a17686fefff">

### Reproduction Steps

Run website template using `create-payload-app`

**Comment by paulpopus** [comment]
Hey, it's not clear from your screenshot what you're referring to here. Can you elaborate please?

**Comment by gujral1997** [comment]
This is not due to HMR @paulpopus , I have created a production build and running it locally. I am also getting the same on my vercel deployment. Internal redirects can trick the crawlers and impact the SEO performance.

**Comment by paulpopus** [comment]
Ok I just tested this and I'm not able to replicate with blank or the website template.

Note that you should be running next canary 104 (or higher but 104 is the one we pin to) and the latest beta of Payload with React 19.

See our template's package.json here https://github.com/payloadcms/payload/blob/beta/templates/website/package.json

**Comment by gujral1997** [comment]
@paulpopus, I was able to reproduce it on chrome. When I fire up incognito window, the first request has the redirect

**Comment by gujral1997** [comment]
I am able to reproduce it on Next Canary 104, I have cloned the latest template and tried it out on the local machine. Sharing the curls for both the cases. 

Case 1:  which causes redirect

```
curl 'http://localhost:3000/' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'Accept-Language: en-GB,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: none' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"'
```

Case 2: Doesnt cause redirect, after I reload
```
curl 'http://localhost:3000/' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'Accept-Language: en-GB,en;q=0.9' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'sec-ch-prefers-color-scheme: dark' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"'
```
`Sec-Fetch-Site` header is `none` in the first request and `same-origin` in the second, not sure if it is causing the issue for me. If this is the reason, then is there any way to fix it?

**Comment by paulpopus** [comment]
Can you try a different browser perhaps? I just wonder if its something specific to your setup here. Either some configuration in chrome, some extensions. Can you test it with a browser that you don't regularly use and with default settings?

Technically guest window in Chrome should be enough but just in case

**Comment by gujral1997** [comment]
It's happening in the guest window as well. Specific to Chrome as of now. I am not getting the issue on Firefox or Safari. I was concerned as I got one warning on the search console about the redirect. We can close this issue for the time being. I will reopen and tag you if I get the error on GSC again. Thanks a lot for the quick help. Payload has been a boon for me. Keep up the good work :)
