### ISSUE TITLE
Unusual indentation behavior

### ISSUE THREAD

**Issue by drewbo** [payloadcms/payload#8098]
### Environment Info

```text
Binaries:
  Node: 20.9.0
  npm: 10.1.0
  Yarn: 1.22.22
  pnpm: 9.7.0
Relevant Packages:
  payload: 3.0.0-beta.98
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.98
  @payloadcms/email-nodemailer: 3.0.0-beta.98
  @payloadcms/graphql: 3.0.0-beta.98
  @payloadcms/next/utilities: 3.0.0-beta.98
  @payloadcms/plugin-cloud: 3.0.0-beta.98
  @payloadcms/richtext-lexical: 3.0.0-beta.98
  @payloadcms/translations: 3.0.0-beta.98
  @payloadcms/ui/shared: 3.0.0-beta.98
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
```

### Describe the Bug

I'm using `@payloadcms/richtext-lexical` along with `FixedToolbarFeature`. The increase and decrease indent buttons appear enabled at unexpected times:
- enabled when the cursor is on non-indentable items
- the decrease indent button is non enabled for indentable items like lists

video attached in the reproduction steps

### Reproduction Steps

(The decreasing indent shown in the video is accomplished via undo keyboard command)

https://github.com/user-attachments/assets/4c38d665-1bc2-48dc-b965-20fde466f01a

### Adapters and Plugins

@payloadcms/richtext-lexical: 3.0.0-beta.98

**Comment by GermanJablo** [comment]
Duplicated of https://github.com/payloadcms/payload/issues/8038
