### ISSUE TITLE
Bulk Upload left thumbnail broken

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#8099]
### Environment Info

```text
Binaries:
  Node: 22.6.0
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 9.7.1
Relevant Packages:
  payload: 3.0.0-beta.100
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.100
  @payloadcms/live-preview-react: 3.0.0-beta.100
  @payloadcms/translations: 3.0.0-beta.100
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
```

### Describe the Bug

<img width="904" alt="image" src="https://github.com/user-attachments/assets/67d89a35-985d-4e02-8d83-e43c6e7a8595">

### Reproduction Steps

- Start bulk upload on media collection
- Drag MP4 file
- See broken image thumbnail on left

**Comment by paulpopus** [comment]
Can confirm this is fixed by Tylan's PR
