### ISSUE TITLE
File names turn into gibberish when uploading via the Uploads interface (Media)

### ISSUE THREAD

**Issue by roi-polisave** [payloadcms/payload#8107]
### Environment Info

```text
PayloadCMS: 3.0.0-beta.100 (but the issue also happens on older versions)
Browser versions: Tested on Chrome (version 126) and Firefox (version 130).
Operating System: MacOS
Node.js: v20.17.0
Next.js: 15.0.0-canary.104 (but the issue also happens on older versions)
```

### Describe the Bug

I’ve encountered an issue where file names turn into gibberish when uploading files through the Payload CMS Uploads interface. This happens with files that have non-ASCII characters (e.g., Hebrew or Japanese file names). I have tested this on both Chrome and Firefox browsers on a MacOS system.

I found that there was a similar issue in Postman (issue reference: [Postman GitHub Issue #5912](https://github.com/postmanlabs/postman-app-support/issues/5912)), where multipart/form-data requests with non-ASCII file names were being altered. This might indicate a similar encoding issue in Payload CMS and could be related to how the encoding is handled in the request headers.

**Examples:**

1. Original file name: フェニックス.png (Japanese)
After upload: ãã§ããã¯ã¹.png

2. Original file name: בדיקה.png (Hebrew)
After upload: ××××§×.png

3. Original file name: 検査.png (Japanese)
After upload: æ¤æ».png

### Reproduction Steps

1. Navigate to the Uploads section (Media Collection) in the Payload CMS admin interface.
2. Upload a file with a name containing non-ASCII characters (e.g., Hebrew or Japanese).
3. After the file is uploaded, check the file name – it appears as gibberish instead of the original name.

**Comment by r1tsuu** [comment]
https://github.com/payloadcms/payload/pull/8157

For now, you can define in your root config:
```ts
upload: {
  defParamCharset: "utf8"
}
```
