### ISSUE TITLE
Consider removing `find-up`

### ISSUE THREAD

**Issue by benmccann** [payloadcms/payload#8113]
### Link to reproduction

https://github.com/payloadcms/payload/blob/08fdbcacc02c1768770516c2dd2e22df7bc48843/packages/payload/package.json#L98

### Environment Info

```text
beta.100
```

### Describe the Bug

The functionality of `find-up` is pretty simple and could probably be replicated directly within the project, which would remove 7 dependencies

### Reproduction Steps

https://github.com/payloadcms/payload/blob/08fdbcacc02c1768770516c2dd2e22df7bc48843/packages/payload/package.json#L98

https://npmgraph.js.org/?q=find-up

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/8195
