### ISSUE TITLE
Import Maps not generated in proper directory when admin route is changed.

### ISSUE THREAD

**Issue by FiniteVoid** [payloadcms/payload#8115]
## Link to reproduction

Steps mentioned below

## Environment Info

```text
Pnpm, Bun beta.100 (been happening since 79)
```

### Current
- When the route for admin panel is changed to let's say 'account,' the importMap is generated only in the default src/(payload)/admin. It does not respect the route set in root payload config.
- Since changing admin route means renaming 'admin' folder (Next JS's app router thing) to 'account,' admin folder doesn't exist anymore and I get:
```ts
importMapFolderPath = path.resolve(rootDir, 'src/app/(payload)/admin/');
  95 |     } else {
> 96 |         throw new Error(`Could not find the payload admin directory. Looked in ${path.resolve(rootDir, 'app/(payload)/admin/')} and ${path.resolve(rootDir, 'src/app/(payload)/admin/')}`);
     | ^
  97 |     }
```

### Expected
Payload automatically picks up which folder to overwrite importMap in based on payload config.

### Workaround
Duplicate the 'account' folder in app router directories to 'admin,' then whenever a new importMap is generated, manually copy its content over to the importMap in my custom route's folder.

## Reproduction Steps

1. Create-payload-app@beta
2. Create a custom component somewhere in the project. Mine's in: `./app/customActions/home`
3. Change the admin path in root config:
```ts
...
export default buildConfig({
  routes: {
    admin: '/account',
  },
...
```
4. Rightfully rename the `admin` folder in ./app/(payload)/admin to `account` to make admin panel work.
5. Add a component to root config and save.
```ts
...
export default buildConfig({
  routes: {
    admin: '/account',
  },
  admin: {
    components: { actions: ['./app/customActions/home'] },
...
```
6. Notice the failure to generate Import Maps.

## Adapters and Plugins

sqlite, mongo

**Comment by BlainMaguire** [comment]
This is a duplicate of: #7803 

I had the same issue, I created a PR for it here:
https://github.com/payloadcms/payload/pull/8085

**Comment by FiniteVoid** [comment]
Ahh, definitely true, thank you for noticing this. Happy to close this one. Sorry for not doing my due diligence before posting. I looked for issues when it first started happening around 79, but then revisited proj 2 weeks later and assumed things were same when there was no fix.
