### ISSUE TITLE
Lexical Render Issues

### ISSUE THREAD

**Issue by impondesk** [payloadcms/payload#8120]
### Environment Info

```text
Payload: beta
```

### Describe the Bug

@payload/lexical uses v0.11 whereas client is updated with v0.17 as latest version, where data is not displayed on client side.

### Reproduction Steps

Display content from payload beta to client with latest lexical editor.

**Comment by GermanJablo** [comment]
I don't understand the issue or how to reproduce it. Please open a new issue with more details and I will be happy to help you.
