### ISSUE TITLE
Multi Edit not working for upload (image) field

### ISSUE THREAD

**Issue by robinscholz** [payloadcms/payload#8127]
### Environment Info

```text
Payload: "3.0.0-beta.84",
Next: 15.0.0-canary.120
Node: v20.17.0
```

### Describe the Bug

When selecting and editing a field of multiple entries in a collection from the table view, the data is not saved.

### Reproduction Steps

1. Go to Collection
2. Select multiple entries
3. Click Edit 
4. Select image (upload) field to edit
5. Add image
6. Save

**Comment by robinscholz** [comment]
Bug persists with [v3.0.0-beta.100](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.100)

**Comment by paulpopus** [comment]
Your video and steps read a bit contradictory to me. In the video you're trying to drag an item from one field to another which is currently not possible. Is this what you mean?

**Comment by robinscholz** [comment]
Sorry, wrong video!


https://github.com/user-attachments/assets/b94163a3-3065-4895-9735-9ea1b7d25618
