### ISSUE TITLE
Incorrect package reference for Vercel Postgres database adapter

### ISSUE THREAD

**Issue by hampusolsen** [payloadcms/payload#8139]
### Environment Info

```text
Payload: `payload@beta` at time of writing, so `beta.100`?
Node.js: v21.6.1
Next.js: 15.0.0-rc.0
```

### Describe the Bug

Thanks for a great product you guys -- absolute ballers! 🍻 Thought I'd help out a bit with a small issue report.

## tl;dr

`create-payload-app@beta` gets stuck installing dependencies because of incorrect package (`@payloadcms/db-vercelPostgres@beta`) reference, most likely caused by the [incorrect value defined in `select-db.ts`](https://github.com/payloadcms/payload/blob/6b82196f01f478a40ad7979a6d445819f241c2f7/packages/create-payload-app/src/lib/select-db.ts#L33).

## Solution

I haven't spent too much time looking at this, but I'd imagine just changing the `value` to `'vercel-postgres'` at the line linked above rather than `'vercelPostgres'` would solve the issue~

Though, unsure what kind of repercussions, if any, that might have elsewhere.

## Logs

```shell
$ pnpx create-payload-app@beta                                                                                        main

...

■  Command failed with exit code 1: pnpm add payload@beta @payloadcms/next@beta @payloadcms/richtext-lexical@beta @payloadcms/plugin-cloud@beta @payloadcms/db-vercelPostgres@beta graphql@^16.8.1
│  Progress: resolved 0, reused 1, downloaded 0, added 0
│   ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@payloadcms%2Fdb-vercelPostgres: Not Found - 404

...

◐  Installing Payload and dependencies.. # <---- stuck here
```

### Reproduction Steps

- Run `pnpm create-payload-app@beta`
- Select _Vercel Postgres (beta)_ as database provider

### Adapters and Plugins

db-vercel-postgres

**Comment by paulpopus** [comment]
Closing as the above has been merged, thanks for your PR!
