### ISSUE TITLE
Preview button not routing correctly for Pages collection despite working Live Preview

### ISSUE THREAD

**Issue by danielkoller** [payloadcms/payload#8156]
### Environment Info

```text
Payload: 3.0.0-beta.102
Next: 15.0.0-canary.139
Node: 22.7.0
```

### Describe the Bug

In my Payload CMS project using next-intl for internationalization (with middleware), I'm experiencing an issue with the preview button routing for the Pages collection. Here's the situation:

1. Live Preview functionality is working correctly, showing real-time updates.
2. I can access draft posts by visiting the page manually with the correct locale and slug.
3. However, clicking the preview button in the admin panel always routes to "/", regardless of the page being previewed.

My current preview configuration in the Pages collection is as follows:

```
  livePreview: {
      url: ({ data, locale }) => {
        const path = `/${locale}/${typeof data?.slug === 'string' ? data.slug : ''}`
        return `${process.env.NEXT_PUBLIC_SERVER_URL}${generatePreviewPath({ path })}`
      },
    },
    preview: (doc, { locale }) => {
      const slug = typeof doc?.slug === 'string' ? doc.slug : ''
      return generatePreviewPath({ path: `/${locale}/${slug}` })
    },
```

Here is also my matcher for my next-intl middleware:

```
export const config = {
  matcher: ['/((?!api|_next|admin|next/preview|.*\\..*).*)'],
}
```

### Reproduction Steps

When clicking on the Preview Button in my Pages Collection, I always get routed to "/" instead of getting routed to the correct slug.

**Comment by paulpopus** [comment]
Can you provide a few extra details here about your setup please?

Can you compare for me the difference in the strings returned by the two functions? And where they actually go?

I assume you're going to a next endpoint that enables draftMode? 

What's supposed to happen is that you hit a custom endpoint such as this one https://github.com/payloadcms/payload/blob/beta/templates/website/src/app/(frontend)/next/preview/route.ts

Which then enables draftMode in nextjs and directs you to the right page which then renders the draft version of the requested endpoint

**Comment by danielkoller** [comment]
Hi, 

thanks for your reply! :) 

I actually used the website template as a kickstarter, so I hit the exact same route. 

I've added logging to my code as suggested, and here are the results:

1. Comparing the strings:

Preview Path: /next/preview?path=%2Fde%2F
LivePreview URL: http://localhost:3000/next/preview?path=%2Fde%2Ftestpage

2. Where they actually go:
Both strings are pointing to the same Next.js preview endpoint (/next/preview), but with some differences:

- The Preview Path is a relative path, while the LivePreview URL includes the full server URL (http://localhost:3000).
- The LivePreview URL includes the page slug (testpage) in the path parameter, while the Preview Path doesn't include the slug (it ends with just %2Fde%2F, which decodes to /de/).

The LivePreview URL looks correct and includes the slug, which is why Live Preview is working as expected.

Here is the generatePreviewPath-function, btw. It is also from the website template. 

`export const generatePreviewPath = ({ path }) => `/next/preview?path=${encodeURIComponent(path)}`
`

**Comment by danielkoller** [comment]
Hi @paulpopus,

I've been debugging the issue further and found that the `doc` object never includes the slug when the preview function is called. However, the slug is available in the `doc` object as soon as I publish the document. Here are the details:

### Key Finding
- The `doc` object in the preview function always has the slug as `null` when the document is in draft mode.
- The slug is available in the `doc` object as soon as the document is published.

### Example `doc` Object in Draft Mode

```
{
"id": 19,
"title": null,
"meta": {},
"publishedAt": null,
"slug": null,
"slugLock": true,
"updatedAt": "2024-09-11T07:14:03.179Z",
"createdAt": "2024-09-11T07:14:03.179Z",
"status": "draft",
"layout": []
}
```

### Summary
- The slug is always `null` in the `doc` object when the preview function is called in draft mode.
- The slug becomes available in the `doc` object as soon as the document is published.
- This causes the preview URL to be incomplete, missing the slug when the document is in draft mode and always routing to /
