### ISSUE TITLE
GraphQL collection `id` field should be non-nullable

### ISSUE THREAD

**Issue by VictorWinberg** [payloadcms/payload#8172]
### Environment Info

```text
payload: 3.0.0-beta.58
next: 15.0.0-rc.0
node: 20.16.0
```

### Describe the Bug

The `id` field in the GraphQL schema is currently marked as nullable, which is incorrect. This field should be non-nullable as every resource is expected to have a unique, non-nullable identifier, especially when UUIDs are used as primary keys.

### Reproduction Steps

- Set up a project using Payload CMS with a PostgreSQL adapter and UUID as the primary key.
- Generate the GraphQL schema.
- Inspect the schema for any resource where the `id` field is marked as nullable.

Expected behavior: The `id` field should be non-nullable across all resources.

**Comment by paulpopus** [comment]
Closing as that PR has been merged

**Comment by denolfe** [comment]
🚀 This is included in version [v3.0.0-beta.105](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.105)
