### ISSUE TITLE
Cannot add custom logo

### ISSUE THREAD

**Issue by oliviermtl** [payloadcms/payload#8178]
### Environment Info

```text
payload: 3.0.0-beta.103
Node: 20.9.0
next: 15.0.0-canary.104
```

### Describe the Bug

In payload.config.ts I add a custom logo : 
`import Logo from './components/payload/Logo'
...
export default buildConfig({
 admin: {
  components: {
      graphics: {
        Logo,
      },
    },
  }
})
`

I get the console message : 
`getComponent: Component not found in importMap {
  identifier: 'config.admin.components.graphics.Logo',
  key: 'undefined#default',
  payloadComponent: [Function: Logo]
} You may need to run the `payload generate:importmap` command to generate the importMap ahead of runtime.`

if I try to run payload generate:importmap I get : 

`Error: addToImportMap > Payload component must be an object or a string`

### Reproduction Steps

Follow the  [White Label the Admin UI article](https://payloadcms.com/blog/white-label-admin-ui)

**Comment by n-a-t-j-b** [comment]
Hi, Have you tried something like this? This Logo is for the Login page vs the Icon in the dashboard but the principle is the same (this code works in beta.91 so should still be valid). Hope it helps.

src/components/shared/Logo.tsx:
```javascript
import Image from "next/image"
import myLogo from '../../../public/assets/logo.svg'

const Logo: React.FC = () => {
  return (
    <div className="flex flex-col w-full justify-center">
      <div className="flex justify-center">
        <Image src={myLogo} alt="My Logo" priority className="items-center"/>
      </div>
    </div>
  )
}

export default Logo
``` 
payload.config.ts:

```javascript
const logoPath = 'src/components/shared/Logo.tsx'
const iconPath = 'src/components/shared/Icon.tsx'

  admin: { 
    user: Users.slug,
    components: {
       graphics: {
        Icon: {
          path: iconPath,
        },
        Logo: {
          path: logoPath,
        },
      },
    },
  },
```

**Comment by oliviermtl** [comment]
Yes it works. I can now run payload generate:importmap and see my logo.
Thanks !

**Comment by oliviermtl** [comment]
Yes it works. I can now run payload generate:importmap and see my logo.
Thanks !

**Comment by oliviermtl** [comment]
Yes it works. I can now run payload generate:importmap and see my logo.
Thanks !
