### ISSUE TITLE
 Adding custom cell to a field makes default filter component to render as TextFilter

### ISSUE THREAD

**Issue by chelaru-artur** [payloadcms/payload#8187]
### Link to reproduction

https://github.com/chelaru-artur/broken_standart_filter_component

### Environment Info

```text
payload: 3.0.0-beta.103
  next: 15.0.0-canary.104
  Node: 20.17.0
```

### Describe the Bug

When you add a custom cell component to a select or relationship field  the standard filter component is rendered as text filter

- without custom cell:
![image](https://github.com/user-attachments/assets/d7e483d8-74e5-4f86-a9c2-5a7ca5f80fde)
-with custom cell:
![image](https://github.com/user-attachments/assets/74642846-f99d-4c3b-9598-6dbd1d93301d)

Root cause is here: code expects type as: relationship, select, text, etc but the type is now: 'client' or 'server'
![image](https://github.com/user-attachments/assets/09d62ff9-a3b0-4f24-812b-4ea4cb57f2df)

### Reproduction Steps

1. go to users collection
2. check  filter component for 'role' field
3. uncomment the line :22 in users collection to use custom cell
4. check the filter again

**Comment by paulpopus** [comment]
Thanks for the report! Fixed in https://github.com/payloadcms/payload/pull/8211
