### ISSUE TITLE
Can't open document from list view if first column is rich text field / rich text cell is not clickable

### ISSUE THREAD

**Issue by franciscolourenco** [payloadcms/payload#8197]
### Environment Info

```text
Payload: 3.0.0-beta.104
Node: v21.6.2
Next: 15.0.0-canary.104
```

### Describe the Bug

When a rich text field is set as the first column in the list view, it's not possible to open the document, because the cell is not clickable. This is a regression from v2.

https://github.com/user-attachments/assets/972a5ffc-cc13-4ca1-9158-990340e134f8

Perhaps the [WrapElement](https://github.com/payloadcms/payload/blob/db29e1ec98a8b63a4c3c5c49d7bdd54edf0b2045/packages/ui/src/elements/Table/DefaultCell/index.tsx#L56) that provides this functionality, should be moved to the parent Table component, so that any cell component that is in the first column gets wrapped, even if they are custom components. Otherwise not only rich text fields, but any custom cell component will not have this functionality when used as the first column in the list view.

### Reproduction Steps

1. Move a rich text column to the first position
2. Try to open the document by clicking the first cell

**Comment by paulpopus** [comment]
Thanks for reporting this! Fixed in https://github.com/payloadcms/payload/pull/8212

**Comment by franciscolourenco** [comment]
@paulpopus thank you for fixing it! A couple of questions: 
1. The slate cell seems to also be missing the link wrapper. Shouldn't we fix that one too?
2. Wouldn't it be a good idea to move this wrapper to the Table itself, so that any custom cell that is moved to the first place becomes clickable? That way we wouldn't have to implement this in every cell either.
