### ISSUE TITLE
Error when accessing the Versions page

### ISSUE THREAD

**Issue by radudevit** [payloadcms/payload#8199]
### Environment Info

```text
Node: 20.15.1
Payload: 3.0.0-beta.102
Next: 15.0.0-canary.104
```

### Describe the Bug

There is an issue when opening the Versions page of a collection with labels set as LabelFunction.

### Reproduction Steps

1. For a collection, configure the labels as LabelFunction
```
{
    slug: 'users',
    auth: true,
    labels: {
      singular: ({ t }) => t('fields:block'),
      plural: ({ t }) => t('fields:blocks'),
    },
...
}
```

2. Open the versions page
3. An error occurs:
![image](https://github.com/user-attachments/assets/97c50269-a5c5-4f36-a686-3316a6388a1b)

**Comment by paulpopus** [comment]
This will be fixed in https://github.com/payloadcms/payload/pull/8213
