### ISSUE TITLE
useTableColumns.setActiveColumns doesn't allow column order to be set

### ISSUE THREAD

**Issue by franciscolourenco** [payloadcms/payload#8205]
### Environment Info

```text
Paylaod: 3.0.0-beta.104
Next: 15.0.0-canary.104
```

### Describe the Bug

In v2, [useTableColumns.setActiveColumns](https://payloadcms.com/docs/beta/admin/hooks#usetablecolumns) respected the order of the columns that were passed to the function. In v3, the function only toggles columns on and off, but leaves the columns in it's previous order. This is a breaking change, and there is no longer a easy way to reset the columns to it's initial state.

It would be nice if the functionality of the function was kept as v2, or in alternative, we could add a function to reset the columns to the default state?

### Reproduction Steps

```ts
"use client";

import { Pill, useListInfo, useTableColumns } from "@payloadcms/ui";

function ResetDefaultColumnsButton() {
  const { collectionConfig } = useListInfo();
  const { setActiveColumns } = useTableColumns();

  function handleOnClick() {
    if (collectionConfig?.admin?.defaultColumns) {
      setActiveColumns(collectionConfig.admin.defaultColumns);
    }
  }

  return <Pill onClick={handleOnClick}>Reset to default columns</Pill>;
}

export { ResetDefaultColumnsButton };

```

**Comment by r1tsuu** [comment]
Will be added with https://github.com/payloadcms/payload/pull/8296
