### ISSUE TITLE
Wrong props passed to custom cell

### ISSUE THREAD

**Issue by mattiaz9** [payloadcms/payload#8207]
### Environment Info

```text
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: 9.10.0
Relevant Packages:
  payload: 3.0.0-beta.104
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 12
```

### Describe the Bug

I'm building a custom field with a custom cell, but I can't access `cellData` because it's undefined.
These are the props passed to the cell: `collectionConfig`, `collectionSlug`, `data`, `hasCreatePermission`, `i18n`, `limit`, `listPreferences`, `listSearchableFields`, `locale`, `newDocumentURL`, `params`, `payload`, `permissions`, `searchParams`, `user`, `clientField`, `field`.

### Reproduction Steps

This is the link to my custom field: 
- field: https://github.com/Etherna/etherna-website/blob/payload/apps/cms/src/fields/color/index.ts
- field component: https://github.com/Etherna/etherna-website/blob/payload/apps/cms/src/fields/color/field.tsx
- cell component: https://github.com/Etherna/etherna-website/blob/payload/apps/cms/src/fields/color/cell.tsx

**Comment by tyteen4a03** [comment]
The way cell data can be accessed has changed - can you try the `useTableCell()` hook? https://payloadcms.com/docs/beta/admin/fields#the-cell-component

**Comment by mattiaz9** [comment]
@tyteen4a03 thank you, that worked!
