### ISSUE TITLE
GeneratePreviewURL doc does not return draft data

### ISSUE THREAD

**Issue by Collexi-Dev** [payloadcms/payload#8215]
### Environment Info

```text
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.104
  next: 15.0.0-canary.104
  @payloadcms/db-mongodb: 3.0.0-beta.104
  @payloadcms/email-nodemailer: 3.0.0-beta.104
  @payloadcms/graphql: 3.0.0-beta.104
  @payloadcms/live-preview: 3.0.0-beta.104
  @payloadcms/live-preview-react: 3.0.0-beta.104
  @payloadcms/next/utilities: 3.0.0-beta.104
  @payloadcms/plugin-seo: 3.0.0-beta.104
  @payloadcms/richtext-lexical: 3.0.0-beta.104
  @payloadcms/translations: 3.0.0-beta.104
  @payloadcms/ui/shared: 3.0.0-beta.104
  react: 19.0.0-rc-206df66e-20240912
  react-dom: 19.0.0-rc-206df66e-20240912
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:54 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6031
  Available memory (MB): 36864
  Available CPU cores: 14
```

### Describe the Bug

There are multiple examples, like the 3.0 demo project, as well as in the docs, where the preview link (not live previews) for drafts are generated like this:

```javascript
    preview: (doc) => {
      return generatePreviewPath({ path: `/${typeof doc?.slug === 'string' ? doc.slug : ''}` })
    },
``` 

When adding this in a Page collection for example, it seems that whenever you want to preview a page without ever publishing it, the `doc` doesn't return the slug or other information, i.e.:

```
***** DEBUG: Preview doc {
  id: '66e46b45b8eae04fd6a137eb',
  hero: {},
  meta: {
    index: true,
    follow: true,
    googleBotIndex: true,
    googleBotFollow: true
  },
  _status: 'draft',
  layout: [],
  createdAt: '2024-09-13T16:41:41.667Z',
  updatedAt: '2024-09-13T16:41:41.667Z'
}
```

But for example when the draft page is fetched using the id, all of the draft data is returned:

```
{
  id: '66e46b45b8eae04fd6a137eb',
  title: 'Home',
  hero: { uptitle: 'hello', title: 'this is a title' },
  layout: [],
  meta: {
    index: true,
    follow: true,
    googleBotIndex: true,
    googleBotFollow: true
  },
  slug: 'home',
  updatedAt: '2024-09-13T16:42:27.504Z',
  createdAt: '2024-09-13T16:41:41.667Z',
  _status: 'draft'
}
```

The `doc` only seems to return published data instead of the draft data, which I don't expect when trying to see a preview.

### Reproduction Steps

1. Setup demo project: https://github.com/payloadcms/payload-3.0-demo
2. Go to admin panel
3. Create new page
4. Enter some data + slug, do not publish
5. Open Preview link
6. Expect to see draft preview

**Comment by danielkoller** [comment]
They are already aware. :)

https://github.com/payloadcms/payload/issues/8077

**Comment by Collexi-Dev** [comment]
> They are already aware. :)
> 
> #8077

That bug to me reads more as if they are getting incomplete draft data while they are not expecting it at all, whereas this is more so about not getting the draft data when I am expecting it, although the root cause might indeed be the same where the fields are null

**Comment by paulpopus** [comment]
This will be fixed in https://github.com/payloadcms/payload/pull/8245

The preview URL wasn't properly requesting draft documents, thanks for the report!
