### ISSUE TITLE
UI Pagination: Switching pages displays some values incorrectly

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#822]
https://youtu.be/NkdkchHJzrk

Video should show the problem. Each entry has a group "A" and "B". When navigating from Page 1 to 2, some entries show `<No Group>` even though they do have a group. Also, every time I reload & switch pages, it shows something different.

Maybe some issue with lazyloading?

**Comment by jmikrut** [comment]
Hey @AlessioGr — thanks for the report! We'll look into this ASAP.

**Comment by DanRibbens** [comment]
Hey @AlessioGr, we released the fix for this one. Thank you for reporting it!
