### ISSUE TITLE
Getting 'fetch is not defined' error when creating project with 'npx create-payload-app@beta'

### ISSUE THREAD

**Issue by QYongHao** [payloadcms/payload#8227]
### Environment Info

```text
N/A
```

### Describe the Bug

![image](https://github.com/user-attachments/assets/f2b31b58-3228-4880-b37c-1a7e8fe3072e)

### Reproduction Steps

npx create-payload-app@beta

**Comment by QYongHao** [comment]
For reference `npx create-payload-app` works just fine. Only beta is failing to create the project.
![image](https://github.com/user-attachments/assets/bf920171-0aa5-48c6-9456-d52e110a0f70)

**Comment by denolfe** [comment]
create-payload-app@beta uses the native Node.js `fetch`. 

My guess is that you're using an old Node.js version which does not have `fetch`. Can you provide this info? (Worth noting, this is what the Environment Info section of the issue template is for)

**Comment by QYongHao** [comment]
You're right. Was using node 16. Node 20 works.

**Comment by QYongHao** [comment]
Thanks for the help!
