### ISSUE TITLE
4.5MB Upload Limit when deployed on Vercel

### ISSUE THREAD

**Issue by iiskakov** [payloadcms/payload#8231]
### Link to reproduction

https://github.com/iiskakov/is-it-really-one-click-though

### Environment Info

```text
"payload": "3.0.0-beta.68"
"next": "15.0.0-canary.77"
```

### Describe the Bug

When deploying a Payload v3 project on Vercel using the S3 plugin for file uploads, Vercel’s 4.5MB file upload limit still applies. This severely restricts media-heavy projects, as file uploads beyond this size fail, even though external storage (S3) is configured. This limitation isn’t documented, and it's critical for projects relying on large file uploads, especially given Payload’s “Next.js-first” marketing for v3. 

### Reproduction Steps

1. Deploy a Payload v3 project using the Vercel quick-deploy template.
2. Configure S3 storage for file uploads.
3. Attempt to upload a file larger than 4.5MB (e.g., 30MB video).
4. The upload will fail due to Vercel’s default upload limit, even though S3 is integrated.

### Adapters and Plugins

@payloadcms/storage-s3

**Comment by robinscholz** [comment]
We ran into the same issue earlier. Here’s a bit more info: https://vercel.com/docs/errors/FUNCTION_PAYLOAD_TOO_LARGE

**Comment by iiskakov** [comment]
> We ran into the same issue earlier. Here’s a bit more info: https://vercel.com/docs/errors/FUNCTION_PAYLOAD_TOO_LARGE

Yup, thanks, I've seen this. If I understood it correctly - vercel functions are not supposed to be used to transfer data basically, and current way of how uploads are implemented uses them (not by design though) 🤔

**Comment by ChristopherNowlan** [comment]
Is there any movement on this?  Or work arounds.

**Comment by drewlonious** [comment]
> ### Link to reproduction
> https://github.com/iiskakov/is-it-really-one-click-though
> 
> ### Environment Info
> ```
> "payload": "3.0.0-beta.68"
> "next": "15.0.0-canary.77"
> ```
> 
> ### Describe the Bug
> When deploying a Payload v3 project on Vercel using the S3 plugin for file uploads, Vercel’s 4.5MB file upload limit still applies. This severely restricts media-heavy projects, as file uploads beyond this size fail, even though external storage (S3) is configured. This limitation isn’t documented, and it's critical for projects relying on large file uploads, especially given Payload’s “Next.js-first” marketing for v3.
> 
> ### Reproduction Steps
> 1. Deploy a Payload v3 project using the Vercel quick-deploy template.
> 2. Configure S3 storage for file uploads.
> 3. Attempt to upload a file larger than 4.5MB (e.g., 30MB video).
> 4. The upload will fail due to Vercel’s default upload limit, even though S3 is integrated.
> 
> ### Adapters and Plugins
> @payloadcms/storage-s3

would love to hear more about this too

**Comment by drewlonious** [comment]
Hey @JarrodMFlesch is there a current recommended workaround to just upload directly to s3 or s3 compatible storage like supabase, r2, while still integrating with the admin media collection?

**Comment by denolfe** [comment]
Now available in v3.25.0 https://github.com/payloadcms/payload/releases/tag/v3.25.0

@iiskakov @drewlonious

**Comment by lynndylanhurley** [comment]
@denolfe just updated to `v3.25.0`, now getting this error:

```
getFromImportMap: PayloadComponent not found in importMap
```

It seems to be missing a reference to the new `VercelBlobClientUploadHandler` component.

I ran `payload generate:importMap` but it didn't resolve the issue.

<img width="913" alt="Image" src="https://github.com/user-attachments/assets/13084706-8951-4add-8519-3bc0c32fc815" />

**Comment by denolfe** [comment]
This looks to be a separate issue. Looking into it.

**Comment by lynndylanhurley** [comment]
Thank you @denolfe !!

**Comment by tjazsilovsek** [comment]
I also updated to 3.25.  Works fine for regular cases.

It breaks when using custom generateFileURL:

```
    s3Storage({
      clientUploads: true,
      collections: {
        media: {
          disablePayloadAccessControl: true,
          generateFileURL: (file) => {
            return `${env.R2_PUBLIC_URL}${file.prefix ? `/${file.prefix}` : ''}/${file.filename}`;
          },
        },
      }

```
The signed url is generated successfully, also file is uploaded to R2, but than callback to nextjs route fails:
```
POST /api/media
[10:59:05] [31mERROR[39m: [36mExpected response from the upload handler.[39m
err: {
"type": "a",
"message": "Expected response from the upload handler.",
"stack":
a: Expected response from the upload handler.
at Y (/var/task/.next/server/chunks/9538.js:224:21175)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async includes.e.handler (/var/task/.next/server/chunks/9538.js:218:50039)
at async td (/var/task/.next/server/chunks/1957.js:1:101762)
at async /var/task/.next/server/chunks/1957.js:1:104559
at async /var/task/.next/server/chunks/2765.js:19:60450
at async te.do (/var/task/node_modules/.pnpm/next@15.0.4_@babel+core@7.26.0_@opentelemetry+api@1.9.0_babel-plugin-macros@3.1.0_babel-plugi_zq5vx5oyotndr5e2kiaomnjrxa/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:17826)
at async te.handle (/var/task/node_modules/.pnpm/next@15.0.4_@babel+core@7.26.0_@opentelemetry+api@1.9.0_babel-plugin-macros@3.1.0_babel-plugi_zq5vx5oyotndr5e2kiaomnjrxa/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:18:22492)
at async eB (/var/task/node_modules/.pnpm/next@15.0.4_@babel+core@7.26.0_@opentelemetry+api@1.9.0_babel-plugin-macros@3.1.0_babel-plugi_zq5vx5oyotndr5e2kiaomnjrxa/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:2871:21083)
at async el (/var/task/node_modules/.pnpm/next@15.0.4_@babel+core@7.26.0_@opentelemetry+api@1.9.0_babel-plugin-macros@3.1.0_babel-plugi_zq5vx5oyotndr5e2kiaomnjrxa/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:2872:1548)
"data": null,
"isOperational": true,
"isPublic": false,
"status": 500,
"name": "a"
}
```

**Comment by mitchellston** [comment]
@tjazsilovsek I created a new issue for the issue you're having with ```generateFileURL``` and ```clientUploads```. [#11473](https://github.com/payloadcms/payload/issues/11473)
