### ISSUE TITLE
PayloadCMS instance completely freezes when opening a lot of things at once

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#824]
https://youtu.be/Rvn2SM4_EqE

See video. There are no console errors, and the only way to restore it is to re-start the server. It does not unfreeze itself.

This only seems to happen locally and not in production.

**Comment by jmikrut** [comment]
Hey @AlessioGr — thanks for the issue! I just recreated, and you're right, it's only in _**dev mode**_. Running Payload in production does not reproduce the issue.

That said, some further testing has shown that this is related to `webpack-hot-middleware`, and not necessarily Payload itself. 

I've opened an issue on that repo and am going to close this one for now. Will follow up here when there is an actionable fix or suggestion from `webpack-hot-middleware`.

Thank you!!
