### ISSUE TITLE
Textarea labels missing

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#8247]
### Link to reproduction

pnpm dev _community

### Environment Info

```text
Binaries:
  Node: 22.6.0
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 9.7.1
Relevant Packages:
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.104
  @payloadcms/live-preview-react: 3.0.0-beta.104
  @payloadcms/translations: 3.0.0-beta.104
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
```

### Describe the Bug

Custom labels are broken on textarea fields and possibly others. 

Sounds like caused by this PR released in beta 105: https://github.com/payloadcms/payload/pull/8190. Brought up by @mykz.

![CleanShot 2024-09-16 at 18 27 31](https://github.com/user-attachments/assets/42ea4f2b-2674-46c5-a67c-b844a710d5bc)

### Reproduction Steps

1. `pnpm dev _community`
2. Add textarea field with label

```ts
        {
          name: 'textarea',
          type: 'textarea',
          label: 'Custom Textarea Label',
        },
   ```
   
   3. Load admin and see that label is missing

**Comment by paulpopus** [comment]
Fixed in https://github.com/payloadcms/payload/pull/8248
