### ISSUE TITLE
plugin-form emails ignore defaultFromaddress and defaultFromName from nodemailerAdapter

### ISSUE THREAD

**Issue by yobottehg** [payloadcms/payload#8250]
### Environment Info

```text
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.106
  next: 15.0.0-canary.106
  @payloadcms/db-postgres: 3.0.0-beta.106
  @payloadcms/email-nodemailer: 3.0.0-beta.106
  @payloadcms/graphql: 3.0.0-beta.106
  @payloadcms/next/utilities: 3.0.0-beta.106
  @payloadcms/plugin-form-builder: 3.0.0-beta.106
  @payloadcms/plugin-redirects: 3.0.0-beta.106
  @payloadcms/plugin-search: 3.0.0-beta.106
  @payloadcms/plugin-seo: 3.0.0-beta.106
  @payloadcms/richtext-lexical: 3.0.0-beta.106
  @payloadcms/translations: 3.0.0-beta.106
  @payloadcms/ui/shared: 3.0.0-beta.106
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
Operating System:
  Platform: linux
  Arch: arm64
  Version: #1 SMP Mon Aug 12 08:47:01 UTC 2024
  Available memory (MB): 15975
  Available CPU cores: 8
```

### Describe the Bug

If an email is send via the form plugin and no from email is set the default from address and name of the nodemailer transport could / should be used.

Current case is that nothing of that is used and the email can not be send.

Perhaps it would also be enough to make this field required and preset it with the default from address if one is provided?

```
nodemailerAdapter({
  defaultFromAddress: process.env['SMTP_FROM_ADDRESS'] ?? '',
  defaultFromName: process.env['SMTP_FROM_NAME'] ?? '',
  ...
})
```

### Reproduction Steps

Submit any form without a provided "from-email". Sending this via a transaction email provider will fail because of the missing from header.

### Adapters and Plugins

plugin-form plugin email-nodemailer

**Comment by paulpopus** [comment]
Added this in https://github.com/payloadcms/payload/pull/8271

You can now provide a `defaultToEmail` in the plugin configuration and if this is missing too, then it will fallback to the transport config `defaultFromAddress`.
