### ISSUE TITLE
UploadField > Layout problems due to available space

### ISSUE THREAD

**Issue by robinscholz** [payloadcms/payload#8278]
### Environment Info

```text
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 9.5.0
Relevant Packages:
  payload: 3.0.0-beta.100
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
```

### Describe the Bug

When an upload field is used on a more confined space, the upload field is collapsing.

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/86a03bd2-73d5-437c-8aa7-140bc7a7a990">

Ideally a gap should be added between text and button and the text inside the buttons should not break. Instead the second button should wrap underneath. A container query would probably be a nice, simple solution.

### Reproduction Steps

```ts
import type { UploadField } from 'payload'

export const imageField: UploadField = {
  name: 'image',
  type: 'upload',
  relationTo: 'image',
  admin: {
    position: 'sidebar',
  },
}
```

**Comment by tylandavis** [comment]
Hey @robinscholz, update to at least `beta.101`. This was fixed here #8101
