### ISSUE TITLE
richtext-lexical: bold link markdown conversion not working

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#8279]
Example: 

```md
[**Link**](/docs/test) – Test
```

This should be a bold link, but currently it gets converted to just bold text without the link. Can be reproduced in the lexical playground as well

**Comment by GermanJablo** [comment]
> Can be reproduced in the lexical playground as well

Shouldn't the issue be reported there instead of here then?

If it's a priority for us I can address it regardless of that

**Comment by AlessioGr** [comment]
> Shouldn't the issue be reported there instead of here then?

Generally yeah - but it's an important issue for us to fix and opening it here makes it easier to track & not forget about it. We can open an issue in lexical as well

**Comment by GermanJablo** [comment]
Related:
https://github.com/facebook/lexical/issues/6337
https://github.com/facebook/lexical/issues/5148 - PR open (https://github.com/facebook/lexical/pull/5149)
https://github.com/facebook/lexical/issues/2632
https://github.com/facebook/lexical/issues/2303 - PR closed (https://github.com/facebook/lexical/pull/2304)
https://github.com/facebook/lexical/issues/3764

**Comment by AlessioGr** [comment]
Opened PR in lexical repo: https://github.com/facebook/lexical/pull/7004
