### ISSUE TITLE
Array field inside localized group field is not saved

### ISSUE THREAD

**Issue by ivankyrpa** [payloadcms/payload#8283]
### Environment Info

```text
Binaries:
  Node: 20.17.0
Relevant Packages:
  payload: 3.0.0-beta.107
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.107
  @payloadcms/email-nodemailer: 3.0.0-beta.107
  @payloadcms/graphql: 3.0.0-beta.107
  @payloadcms/next/utilities: 3.0.0-beta.107
  @payloadcms/plugin-cloud: 3.0.0-beta.107
  @payloadcms/richtext-lexical: 3.0.0-beta.107
  @payloadcms/translations: 3.0.0-beta.107
  @payloadcms/ui/shared: 3.0.0-beta.107
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
```

### Describe the Bug

When I try to save array field inside localized group field, it doesn't get saved. The same behavior for globals and collections.

### Reproduction Steps

Test global looks like that:
 ```js
 export const TestGlobal: GlobalConfig = {
  slug: 'testGlobal',
  fields: [
    {
      name: 'group',
      localized: true,
      type: 'group',
      fields: [
        {
          name: 'innerArray',
          type: 'array',
          maxRows: 1,
          fields: [
            {
              type: 'row',
              fields: [
                {
                  name: 'field1',
                  type: 'text',
                },
                {
                  name: 'field2',
                  type: 'text',
                },
              ],
            },
            ...
          ],
        }
      ]
    }
  ],
}
```

Payload config:
```js
...
import { TestGlobal } from './globals/TestGlobal'

export default buildConfig({
  ...
  globals: [TestGlobal],
  ...
  }),
  localization: {
    defaultLocale: 'en',
    locales: ['en', 'de'],
    fallback: true,
  },
  ...
})

```
The video below demonstrates that other fields behave as expected. The problem is only in array field inside localized group field

https://github.com/user-attachments/assets/f386f3db-8b50-429a-83ed-ccad50583332

### Adapters and Plugins

db-postgres

**Comment by jmikrut** [comment]
Hey @ivankyrpa — this appears to be fixed on the newest beta. Just tried to reproduce with your config in a test and it works.

What version are you on? Let me know if it still happens after you update, and if so, please re-open with a reproduction repository.

Thank you!

**Comment by ivankyrpa** [comment]
Hi @jmikrut ! Thanks for your quick response.

I specified version 3.0.0-beta.107 in the description. Isn't it the latest version?
