### ISSUE TITLE
Localized group Field breaks Postgres

### ISSUE THREAD

**Issue by italodr** [payloadcms/payload#8308]
### Link to reproduction

https://github.com/italodr/test-payload-19092024

### Environment Info

```text
Binaries:
  Node: 20.12.2
  npm: 10.5.0
  Yarn: 1.22.22
  pnpm: 9.1.2
Relevant Packages:
  payload: 3.0.0-beta.107
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.107
  @payloadcms/email-nodemailer: 3.0.0-beta.107
  @payloadcms/graphql: 3.0.0-beta.107
  @payloadcms/next/utilities: 3.0.0-beta.107
  @payloadcms/plugin-cloud: 3.0.0-beta.107
  @payloadcms/richtext-lexical: 3.0.0-beta.107
  @payloadcms/translations: 3.0.0-beta.107
  @payloadcms/ui/shared: 3.0.0-beta.107
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:31 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11
```

### Describe the Bug

I am trying to create a collection with some fields. When I add a field of type upload, there is no problem. But if I try to put this field inside a field of type group, the terminal stops with the following error:

```bash
ERROR: Error: cannot connect to Postgres: Cannot read properties of undefined (reading 'notNull')
```

![Screenshot 2024-09-19 at 16 25 15](https://github.com/user-attachments/assets/1e79f7f5-42a0-4b59-83dc-04f818a5ba70)

### Reproduction Steps

To reproduce the bug:

1. Clone the repository
2. Run `dev` script
3. Open: http://localhost:3000/admin
4. Check the console

----

To verify that it works if it is applied to the field instead of to the group:
1. Go to `src > globals > header.ts` 
2. Move line 16 inside the upload field config
3. Run `dev` script
4. Open: http://localhost:3000/admin

----

The reproduction repository has been created with:

```bash
npx create-payload-app@beta
```

And the following configuration has been added to `payload.config.ts` file:
```js
{
  ...
  localization: {
    locales: [
      { code: 'de', label: 'Deutsch' },
      { code: 'es', label: 'Español' },
    ],
    defaultLocale: 'de',
    fallback: false,
  },
  globals: [Header],
  ...
}
```

### Adapters and Plugins

db-postgres

**Comment by r1tsuu** [comment]
Hey @italodr, thank you! Fix is here: https://github.com/payloadcms/payload/pull/8355, should be in the next release.
