### ISSUE TITLE
Uploading files from Apple Photos fails

### ISSUE THREAD

**Issue by max-degterev** [payloadcms/payload#8317]
### Describe the Bug

Currently trying to upload a photo picked from Apple Photo Gallery fails with an error:

```
err: {
      "type": "Error",
      "message": "extract_area: bad extract area",
      "stack":
          Error: extract_area: bad extract area
    }
```

would it be possible to pass `failOnError: false` to sharp? I see that you construct the options object but there is no way to pass props down to it.

### To Reproduce

Try uploading a photo made with an iPhone

### Payload Version

payload@2.28.0

**Comment by max-degterev** [comment]
might be related: https://github.com/lovell/sharp/issues/4077

**Comment by max-degterev** [comment]
confirmed, using https://www.npmjs.com/package/jpeg-autorotate before uploading fixes the issue. still would be great to have this patched in payload itself

**Comment by max-degterev** [comment]
![IMG_0298](https://github.com/user-attachments/assets/3f17bc6e-f7b2-4e92-801b-6084119ce446)
image for testing

**Comment by max-degterev** [comment]
[IMG_9160.jpeg.zip](https://github.com/user-attachments/files/17197618/IMG_9160.jpeg.zip)
Attached a test image, archive to avoid github compressing

**Comment by PatrikKozak** [comment]
Hey @max-degterev - thank you for the test image! I've opened a PR that should fix your issue here - can you confirm though that this is happening on your end because you have some defined `imageSizes` that are not necessarily of the same aspect ratio as the original image?

**Comment by max-degterev** [comment]
Hey yeah basically crop is applied without respecting the orientation, I quickly checked your PR and it seems to do the right thing, if orientation > 4 need to swap width and height. See the same in sharp doc: https://sharp.pixelplumbing.com/api-input (Look for `getNormalSize`)
