### ISSUE TITLE
Open redirect vulnerability in templates

### ISSUE THREAD

**Issue by stephtr** [payloadcms/payload#8319]
### Describe the Bug

First of all, I want to express my happiness that I stumbled across Payload. I’m just experimenting with it, and it seems to be a close-to-perfect match.

While playing around with live preview, I found an open redirect vulnerability in the website template v3.
[next/preview/route.ts](https://github.com/payloadcms/payload/blob/c6a7ad28171f0ace735e4d9828ed374e35c758d3/templates/website/src/app/(frontend)/next/preview/route.ts#L46C12-L46C16) redirects to `path`, which gets read from `searchParams`, without being checked. This leads to open redirects like http://example.com/next/preview?path=http://evil.com.

NextJS prevents it [in the docs](https://nextjs.org/docs/app/building-your-application/configuring/draft-mode#step-2-access-the-route-handler-from-your-headless-cms) by checking/rebuilding the path before redirecting.

I know, it's just a template, but I would at least add a comment that this should be solved in a better way in production. Or add a `path.startsWith('/')` check.

### Reproduction Steps

Start the website template, visit http://example.com/next/preview?path=http://evil.com

**Comment by paulpopus** [comment]
Added additional checks in /preview in https://github.com/payloadcms/payload/pull/8454

Thanks!
