### ISSUE TITLE
plugin-form-builder should have more sensible access defaults

### ISSUE THREAD

**Issue by janus-reith** [payloadcms/payload#8328]
### Environment Info

```text
Payload v3.0.0-beta.107
```

### Describe the Bug

The Form collection has public read enabled by default: 
https://github.com/payloadcms/payload/blob/main/packages/plugin-form-builder/src/collections/Forms/index.ts#L70

That includes the email configuration:
https://github.com/payloadcms/payload/blob/28a065072fcad2dc768e44d79609eb5ab8a3fdfd/packages/plugin-form-builder/src/collections/Forms/index.ts#L150

For most common contact form usecases, public read access to the email sender and receiver address is not desired.

While it's possible to override this by passing custom `formConfig.formOverrides`, practically many people might just use it as-is.
The reverse makes more sense to me: additional efforts should be made to make this public, not to prevent it.

I would either:
1. Don't make the Form Collection public by default at all
2. Field level access control for the emails

I think a combination of both would make sense to account for use cases where some client-facing code should be able to fetch form configs and thus that collection would be made public, to still prevent that email config from being shown if not explicitly enabled. 

### Reproduction Steps

1. Create a new form
2.  Make an unauthenticated request to the form collection
3. Observe that whole form config including email receivers is returned by default.

### Adapters and Plugins

plugin-form-builder

**Comment by paulpopus** [comment]
Thanks for reporting this. I made the emails field readable by authenticated users only now out of the box and added a note in the docs to remind people to double check permissions here.

You'll still need to override access control for either the emails field or for the collection itself if users can be from the public as well for example.

https://github.com/payloadcms/payload/pull/8338
