### ISSUE TITLE
Re: error on forgot-password route

### ISSUE THREAD

**Issue by hristokoev** [payloadcms/payload#8349]
### Environment Info

```text
Payload: beta.108
Node.js: 22.8.0
Next.js: 15.0.0-canary.160
```

### Describe the Bug

This is related to my previous reported issue, #8155.

It was fixed in the latest release - [v3.0.0-beta.108](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.108) with #8244.

This now works when the user is logged out, but there's the edge case for when the user is logged in, it shows this error:

![image](https://github.com/user-attachments/assets/9dca63ec-3345-400e-b541-4d40dc9f1e6b)

The log from the terminal:

![image](https://github.com/user-attachments/assets/6d0675a6-b07c-40fc-9731-d03872f22e68)

Other routes such as `create-first-user` are correctly redirecting to the main admin dashboard if the user is logged in.

### Reproduction Steps

- Install a new instance of the blank template using `npx create-payload-app@beta test`
- Select the `blank` template
- Run it and create a user
- While logged in, go to `/admin/forgot`

No customizations or changes to the config have been made. Run the template as-is.

**Comment by akhrarovsaid** [comment]
I believe the error is originating from [here](https://github.com/payloadcms/payload/blob/v3.0.0-beta.108/packages/next/src/views/ForgotPassword/index.tsx#L36-L51). 

I'm investigating, definitely a RSC issue, will hopefully write up a PR with a fix for this later today. Hang tight!

**Comment by paulpopus** [comment]
Fixed in https://github.com/payloadcms/payload/pull/8374
