### ISSUE TITLE
Join field doesn't work for relationships that are nested within a tab field

### ISSUE THREAD

**Issue by willviles** [payloadcms/payload#8356]
### Environment Info

```text
Binaries:
  Node: 18.20.2
  npm: 10.5.0
  Yarn: N/A
  pnpm: 9.1.0
Relevant Packages:
  payload: 3.0.0-beta.108
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030
  Available memory (MB): 36864
  Available CPU cores: 12
```

### Describe the Bug

The new join field doesn't work for relationships that are nested within a tab field.

The docs mention dot notation can be used to reference relationship fields nested within groups. However because tab fields only have a label property and no name, this isn't practicable.

It appears the `traverseFields` fn within `sanitizeJoinField` isn't smart enough to traverse through the tab array (or row arrays) to resolve nested relationship fields:
https://github.com/payloadcms/payload/blob/c3bc2ba4a450931f2f67347289d41a68b27ebf9a/packages/payload/src/fields/config/sanitizeJoinField.ts#L42-L67

### Reproduction Steps

Create two collections like so:

```ts
export const FooCollection: CollectionConfig = {
  slug: 'foos',
  fields: [{
    type: 'tabs',
    tabs: [{
      label: 'Relationships',
      fields: [{
        type: 'row',
        fields: [{
          name: 'bar',
          type: 'relationship',
          relationTo: 'bars',
        }]
      }]
    }] 
  }]
}

export const BarCollection: CollectionConfig = {
  slug: 'bars',
  fields: [{
    type: 'tabs',
    tabs: [{
      label: 'Related',
      fields: [{
        name: 'relatedFoos',
        type: 'join',
        collection: 'foos',
        on: 'bar'
      }]
    }]
  }]
}
```

The expected behaviour is that the `bar` relationship field would be able to be referenced by the  `relatedFoos` join field.

However, instead, the following error occurs:

```bash
Internal error: InvalidFieldJoin: Invalid join field relatedFoos. The config does not have a field 'bar' in collection 'bars'.
    at sanitizeJoinField
```

**Comment by DanRibbens** [comment]
I made a canary for this `3.0.0-canary.c696728`

It will be released in `beta-108`.

**Comment by willviles** [comment]
@DanRibbens nice hustle on a Sunday! Cheers.
