### ISSUE TITLE
Bad UX: number field in UI changes when scrolling

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#836]
https://user-images.githubusercontent.com/70709113/181278649-bd57a9ed-a96d-4331-bc1a-a1d323ff31d1.mov

Scrolling over a number field changes the number. Took a while for me to realize while my input was being changed around. I think that behaviour should be disabled, it didn't feel good at all (see video)

**Comment by jmikrut** [comment]
Ahh yeah I can see how this would be annoying. Fixing would be trivial:

https://stackoverflow.com/a/51076231/13175633

We will take care of it!
