### ISSUE TITLE
Write conflict error when deleting a document in afterChange hook

### ISSUE THREAD

**Issue by anassfiqhi** [payloadcms/payload#8363]
### Describe the Bug

**Description:**

I'm experiencing a `MongoServerError` when attempting to delete a document within an `afterChange` hook in Payload CMS. Specifically, when updating an invoice's payment status to `'payed'`, the hook is designed to archive the invoice and then delete it from the original collection. However, this process results in a write conflict error, preventing the transaction from completing successfully.

### To Reproduce

**Steps to Reproduce:**

1. Update an invoice document's `payment` field to `'payed'` via the Payload CMS admin panel or API.
2. The `afterChange` hook triggers, attempting to:
   - Begin a transaction.
   - Create a new document in the `archive` collection with the invoice data.
   - Delete the original invoice from the `invoices` collection.
   - Commit the transaction.
3. Observe that a write conflict error occurs during this process.

**Expected Behavior:**

- The invoice should be archived by creating a new document in the `archive` collection.
- The original invoice should be deleted from the `invoices` collection.
- The transaction should commit successfully without errors.

**Actual Behavior:**

- A `MongoServerError` is thrown:

  ```
  ERROR (payload): MongoServerError: Caused by :: Write conflict during plan execution and yielding is disabled. :: Please retry your operation or multi-document transaction.
  ```

- The transaction fails, and the invoice is neither archived nor deleted.

**Code Snippet:**

```typescript
import payload from 'payload';
import type { CollectionConfig, AfterChangeHook } from 'payload/types';
import { Customer, Invoice } from '../../payload-types';

export const Invoices: CollectionConfig = {
  slug: 'invoices',
  // ... other configurations ...
  hooks: {
    afterChange: [
      (async ({ operation, doc, previousDoc, req }) => {
        if (operation === 'update' && doc.payment === 'payed') {
          req.transactionID = await payload.db.beginTransaction();
          try {
            const archiveData = {
              ...doc,
              customer: (doc.customer as Customer).id,
            };

            const archive = await payload.create({
              collection: 'archive',
              data: archiveData,
            });

            const deletedInvoice = await payload.delete({
              collection: 'invoices',
              id: `${doc.id}`,
            });

            if (req.transactionID) await payload.db.commitTransaction(req.transactionID);
          } catch (error) {
            if (req.transactionID) await payload.db.rollbackTransaction(req.transactionID);
            console.error('Error archiving invoice:', error);
          }
        }

        return doc;
      }) as AfterChangeHook<Invoice>,
    ],
  },
  // ... other configurations ...
};
```

**Error Stack Trace:**

```
ERROR (payload): MongoServerError: Caused by :: Write conflict during plan execution and yielding is disabled. :: Please retry your operation or multi-document transaction.
    at Connection.onMessage (.../node_modules/mongodb/src/cmap/connection.ts:449:20)
    at MessageStream.<anonymous> (.../node_modules/mongodb/src/cmap/connection.ts:241:56)
    at MessageStream.emit (node:events:515:28)
    at MessageStream.emit (node:domain:488:12)
    at processIncomingData (.../node_modules/mongodb/src/cmap/message_stream.ts:188:12)
    at MessageStream._write (.../node_modules/mongodb/src/cmap/message_stream.ts:69:5)
    at writeOrBuffer (node:internal/streams/writable:556:12)
    at _write (node:internal/streams/writable:490:10)
    at MessageStream.Writable.write (node:internal/streams/writable:494:10)
    at TLSSocket.ondata (node:internal/streams/readable:985:22)
```

**Environment:**

- **Payload CMS Version:** 2.28.0
- **Node.js Version:** 21.1.0

**Additional Context:**

- The error seems to occur when deleting the same document that is currently being updated in the `afterChange` hook.
- Wrapping the operations in a transaction does not prevent the error.
- The issue persists even when removing the transaction logic.

**Possible Solution:**

- Is there a recommended way to archive and delete a document within a hook without causing a write conflict?
- Should the deletion be deferred to a different hook or process?
- Any guidance on how to handle this scenario properly in Payload CMS would be appreciated.

---

Thank you for your assistance in resolving this issue.

### Payload Version

2.28.0

### Adapters and Plugins

"@aws-sdk/client-s3": "^3.654.0",     "@aws-sdk/lib-storage": "^3.654.0",     "@payloadcms/bundler-webpack": "1.0.7",     "@payloadcms/db-mongodb": "1.7.2",     "@payloadcms/plugin-cloud-storage": "^1.1.3",     "@payloadcms/richtext-slate": "1.5.2",

**Comment by r1tsuu** [comment]
Hey @anassfiqhi, your operations don't use the transaction. You need to pass `req` to them for it, see the doc https://payloadcms.com/docs/database/transactions#transactions
Can you do this and confirm that your issue is slved? Also, I would ensure that transactions are enabled in MongoDB with replica set.

**Comment by anassfiqhi** [comment]
Hi @r1tsuu 

Thank you for your response. I've updated my code to pass the `req` object to the operations as per the documentation you provided. However, I'm still encountering the same error.

I'm using MongoDB Atlas ([cloud.mongodb.com](https://cloud.mongodb.com/)) with a cluster of 3 nodes, so transactions should be supported and enabled by default.

**Here is my updated code:**

```typescript
import payload from 'payload';
import type { AfterChangeHook, PayloadRequest } from 'payload/types';
import { Customer, Invoice } from '../../payload-types';

export const Invoices = {
  // ... other configurations ...
  hooks: {
    afterChange: [
      (async ({ operation, doc, previousDoc, req }) => {
        console.log(`Invoice ${operation} - ID: ${doc.id} - ${previousDoc.payment} - ${doc.payment}`);

        // Begin the transaction using the existing `req` object
        req.transactionID = await payload.db.beginTransaction();

        if (operation === 'update' && doc.payment === 'payed') {
          try {
            const archiveData = {
              ...doc,
              customer: (doc.customer as Customer).id, // Use only the customer ID
            };

            // Pass `req` to ensure this operation is part of the transaction
            const archive = await payload.create({
              collection: 'archive',
              data: archiveData,
              req, // Include the request object here
            });
            console.log('Archived Invoice ID:', archive.id);

            // Pass `req` to ensure this operation is part of the transaction
            const deletedInvoice = await payload.delete({
              collection: 'invoices',
              id: doc.id,
              req, // Include the request object here
            });
            console.log('Deleted Invoice ID:', deletedInvoice.id);

            // Commit the transaction
            if (req.transactionID) await payload.db.commitTransaction(req.transactionID);

          } catch (error) {
            console.error('Error archiving invoice:', error);
            // Rollback the transaction in case of an error
            if (req.transactionID) await payload.db.rollbackTransaction(req.transactionID);
          }
        }

        return doc;
      }) as AfterChangeHook<Invoice>,
    ],
  },
  // ... other configurations ...
};
```

**Despite these changes, I'm still receiving the same error:**

```
ERROR (payload): MongoServerError: Caused by :: Write conflict during plan execution and yielding is disabled. :: Please retry your operation or multi-document transaction.
    at Connection.onMessage (.../node_modules/mongodb/src/cmap/connection.ts:449:20)
    at MessageStream.<anonymous> (.../node_modules/mongodb/src/cmap/connection.ts:241:56)
    at MessageStream.emit (node:events:515:28)
    at MessageStream.emit (node:domain:488:12)
    at processIncomingData (.../node_modules/mongodb/src/cmap/message_stream.ts:188:12)
    at MessageStream._write (.../node_modules/mongodb/src/cmap/message_stream.ts:69:5)
    at writeOrBuffer (node:internal/streams/writable:556:12)
    at _write (node:internal/streams/writable:490:10)
    at MessageStream.Writable.write (node:internal/streams/writable:494:10)
    at TLSSocket.ondata (node:internal/streams/readable:985:22)
```

**Additional Details:**

- I confirmed that transactions are enabled on my MongoDB cluster.
- The error occurs when trying to delete the same document that is being updated in the `afterChange` hook.
- I also tried removing the transaction logic to see if that would help, but the issue persists.

Is there anything else I might be missing or any other recommendations you might have to resolve this issue?

Thank you for your assistance!

**Comment by r1tsuu** [comment]
Can you try to move this part
```ts
 // Begin the transaction using the existing `req` object
        req.transactionID = await payload.db.beginTransaction();
```
to this block
```ts
if (operation === 'update' && doc.payment === 'payed') {
```
because now, if you condition doesn't pass - the transaction never gets commited / rolled back

**Comment by anassfiqhi** [comment]
Hi @r1tsuu,

Thanks for your recommendation! I implemented your suggestion, passing the `req` object to the operations and beginning the transaction inside the `if` block, but unfortunately, I'm still encountering the same issue.
