### ISSUE TITLE
Missing '.gitignore' with 'npx create-payload-app'

### ISSUE THREAD

**Issue by flaming-codes** [payloadcms/payload#837]
# Bug Report

When bootstrapping a new Payload CMS project via `npx create-payload-app`, no `.gitignore` with `node_modules` (and possible other sane defaults) gets created. This can confuse inexperienced developers, as they check-in the whole `node_modules` and wonder why their repo becomes so large.

I file this as a bug and not feature request, as imho `npx create-payload-app` can be considered to offer a full out-of-the-box experience, where I consider `.gitignore` to be part of. I couldn't find any issue or discuss related to this topic.

## Expected Behavior

`npx create-payload-app` also generates a `.gitignore`-file w/ `node_modules` and possibly other sane defaults.

## Current Behavior

No file gets created.

## Possible Solution

Update `create-payload-app`-script to generate file.

## Steps to Reproduce

1. run `npx create-payload-app`
2. see result

## Detailed Description

- payload: 1.0.9
- create-payload-app: create-payload-app

**Comment by denolfe** [comment]
Hey @flaming-codes , initially we decided not to include anything git-related because we didn't want to impose anything on the developer. However, I think you are correct. Including one is kind of expected on most starters these days. We'll add one 👍

**Comment by denolfe** [comment]
Sane .gitignore has been added.
