### ISSUE TITLE
Lexical custom block in new document (beta 108 regression)

### ISSUE THREAD

**Issue by andershermansen** [payloadcms/payload#8371]
### Link to reproduction

http://localhost:3000/admin/collections/rich-text-fields/create

### Environment Info

```text
payload: 3.0.0-beta.108
next: 15.0.0-canary.160
Node: 22.9.0
```

### Describe the Bug

Can not add custom blocks in lexical field in a new document.

This worked fine in beta 107, does not work in 108.

### Reproduction Steps

Can be reproduced in payload repo:
Run: `pnpm dev fields`
Go to `http://localhost:3000/admin/collections/rich-text-fields/create`
Add any of these custom blocks to the new document:
![Skjermbilde 2024-09-23 kl  14 55 19](https://github.com/user-attachments/assets/b88b2991-7519-4ba2-90bf-2651eeb50030)

**Expected:**
The block to show

**Actual:**
Just showing shimmer-effect/loader

**Comment by andershermansen** [comment]
@GermanJablo what do you mean you can not reproduce? The video is showing the shimmer-effect only and not the content in the block. 

Do the same thing in one of the existing documents, and you will see the difference.

**Comment by AlessioGr** [comment]
> How strange, I can't reproduce it:

Your video does seem to reproduce it though (the blocks are just shimmering)

**Comment by GermanJablo** [comment]
Oh yes, sorry, I don’t know what I’m saying! I'm going to work on this right now.

**Comment by GermanJablo** [comment]
Fixed in https://github.com/payloadcms/payload/pull/8378
