### ISSUE TITLE
Row Field > alignment issue

### ISSUE THREAD

**Issue by robinscholz** [payloadcms/payload#8390]
### Environment Info

```text
Binaries:
  Node: 18.19.0
  npm: 10.2.3
  Yarn: 1.22.19
  pnpm: 9.5.0
Relevant Packages:
  payload: 3.0.0-beta.108
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
```

### Describe the Bug

<img width="956" alt="image" src="https://github.com/user-attachments/assets/0355b53b-3442-4718-8708-a2961a247ec5">

If only one field inside a row field has a description, the remaining fields get spread.

### Reproduction Steps

``` js
{
      type: 'row',
      fields: [labelField, { ...badgeField, admin: { description: 'Displayed after the label' } }],
}
```

**Comment by paulpopus** [comment]
Closing in https://github.com/payloadcms/payload/pull/8421

We're gonna align to the top these fields and instead rely on end users to handle the alignment of the fields themselves.

I tested a few scenarios and there's no pragmatic fix that we can deploy to handle all possible edge cases, at least not with the current way that fields and the field row is setup. Maybe in the future we can make it smarter but for now I recommend devs use custom styles as needed using `admin.width` and `admin.style` as per: https://payloadcms.com/docs/beta/admin/fields (Beta) or https://payloadcms.com/docs/fields/overview#admin-config
