### ISSUE TITLE
API-Key Authorization returning 403

### ISSUE THREAD

**Issue by imatthewcollins** [payloadcms/payload#8426]
### Environment Info

```text
Binaries:
  Node: 21.5.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.106
  next: 15.0.0-canary.104
  @payloadcms/db-postgres: 3.0.0-beta.106
  @payloadcms/email-nodemailer: 3.0.0-beta.106
  @payloadcms/graphql: 3.0.0-beta.106
  @payloadcms/next/utilities: 3.0.0-beta.106
  @payloadcms/plugin-cloud: 3.0.0-beta.106
  @payloadcms/richtext-lexical: 3.0.0-beta.106
  @payloadcms/translations: 3.0.0-beta.106
  @payloadcms/ui/shared: 3.0.0-beta.106
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
```

### Describe the Bug

Behaviour: api-key is not recognised during cURL or fetch requests as req.user always returns as null. Response is 403 - You are not allowed to perform this action

### Reproduction Steps

API key enabled collection:
```
export const Keys : CollectionConfig = {
    slug: 'keys',
    auth: {
        useAPIKey: true,
        disableLocalStrategy: true,
    },
    access: {
        read: hasApiKey
    },
    fields: [
        {
            name: 'title',
            type: 'text',
            required: true
        }
    ]
}
```

Access control:
```
export const hasApiKey : Access = ({ req : { user }}) => {
    console.log('the user is', user)
    if (user) {
        return true
    }
    return false
}
```

cURL request (it's a test api key):

`curl -H "Authorization: keys API-Key 362d99e8-6bf8-461a-a55b-1a56c2843906" localhost:3000/api/keys`

fetch request:

```
const API_KEY = '362d99e8-6bf8-461a-a55b-1a56c2843906'

const response = await fetch('http://localhost:3000/api/keys', {
    method: 'GET',
    headers: {
        Authorization: `keys API-Key ${API_KEY}`
    }
})

const data = await response.json()

console.log(data)
```

**Comment by akhrarovsaid** [comment]
Adding these from the Discord in case others have the same issue. Here's what worked for some people:

- Removing access control
- Deleting the `.next` folder and restarting the server

Although, I think access controls should still work. In my mind, the API-Key strategy should authenticate you, populate the req with the user, and then the access controls should take over and run. It seems like this isn't the case?

**Comment by imatthewcollins** [comment]
@akhrarovsaid shouldn't I be able to define a collection in addition to 'users' that has an API-Key only authentication strategy? In this case, my collection 'keys' should be valid?

**Comment by JarrodMFlesch** [comment]
Here is an example POST request. You need to provide the API key, on the frontend we use [uuidv4](https://www.npmjs.com/package/uuid) to generate the key.

![Image](https://github.com/user-attachments/assets/bd7639f6-dce6-4610-8b64-222350ccaaea)
