### ISSUE TITLE
Upgrading to beta 108 causes duplicate entries when editing and drafts not working as expected

### ISSUE THREAD

**Issue by Collexi-Dev** [payloadcms/payload#8430]
### Environment Info

```text
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.108
  next: 15.0.0-canary.160
  @payloadcms/db-mongodb: 3.0.0-beta.108
  @payloadcms/email-nodemailer: 3.0.0-beta.108
  @payloadcms/graphql: 3.0.0-beta.108
  @payloadcms/live-preview: 3.0.0-beta.108
  @payloadcms/live-preview-react: 3.0.0-beta.108
  @payloadcms/next/utilities: 3.0.0-beta.108
  @payloadcms/plugin-redirects: 3.0.0-beta.108
  @payloadcms/plugin-seo: 3.0.0-beta.108
  @payloadcms/richtext-lexical: 3.0.0-beta.108
  @payloadcms/translations: 3.0.0-beta.108
  @payloadcms/ui/shared: 3.0.0-beta.108
  react: 19.0.0-rc-5dcb0097-20240918
  react-dom: 19.0.0-rc-5dcb0097-20240918
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:41 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6031
  Available memory (MB): 36864
  Available CPU cores: 14
```

### Describe the Bug

I am using mongo in my Payload setup. I have a pretty basic Pages collection and had a few page entries.
After updating from beta v107 to v108, when editing a pre-existing page a duplicate entry for the same ID is shown which both link to the same entry:

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/0972fb7a-131a-41a1-8382-6a7e93513132">

Some observations:

1. Draft data is correctly saved,
2. Publishing changes works and are shown as expected,
3. Latest draft is not shown in preview but it instead shows a different fixed previous version,
4. When creating a new entry in v108 no issues are observed.

### Reproduction Steps

I have not tried to reproduce it yet since I lack the time but if needed and if it would be useful I can try to do so on Monday, however reproduction steps would be:

1. Init project on beta.107
2. Create and publish pages
3. Update to beta.108
4. Edit a previously published page

**Comment by DanRibbens** [comment]
Thanks for opening an issue. This had to do with the move from string based id to ObjectIDs and it impacts collections with versions enabled.

We're looking into what should be done here. It was not something we caught in our QA testing upfront.

**Comment by Collexi-Dev** [comment]
> Thanks for opening an issue. This had to do with the move from string based id to ObjectIDs and it impacts collections with versions enabled.
> 
> We're looking into what should be done here. It was not something we caught in our QA testing upfront.

Cool, thanks for the quick update!

**Comment by Collexi-Dev** [comment]
@DanRibbens I had 1 old entry left created with v107, just updated from v108 to v109 and edited the page but it seems the issue still persists and I now have 3 duplicates:

<img width="1421" alt="image" src="https://github.com/user-attachments/assets/34fdebab-c2ee-4859-a0b2-0ce78ae75f3e">

```
Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: 1.22.22
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.109
  next: 15.0.0-canary.160
  @payloadcms/db-mongodb: 3.0.0-beta.109
  @payloadcms/email-nodemailer: 3.0.0-beta.109
  @payloadcms/graphql: 3.0.0-beta.109
  @payloadcms/live-preview: 3.0.0-beta.109
  @payloadcms/live-preview-react: 3.0.0-beta.109
  @payloadcms/next/utilities: 3.0.0-beta.109
  @payloadcms/plugin-redirects: 3.0.0-beta.109
  @payloadcms/plugin-seo: 3.0.0-beta.109
  @payloadcms/richtext-lexical: 3.0.0-beta.109
  @payloadcms/translations: 3.0.0-beta.109
  @payloadcms/ui/shared: 3.0.0-beta.109
  react: 19.0.0-rc-5dcb0097-20240918
  react-dom: 19.0.0-rc-5dcb0097-20240918
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:41 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6031
  Available memory (MB): 36864
  Available CPU cores: 14
  ```

**Comment by DanRibbens** [comment]
When you resave, it should go back to one. Can you confirm that you've tried that?

Can you share your _pagesversions collection data? I want to see what the parent IDs are for home.

**Comment by Collexi-Dev** [comment]
@DanRibbens After publishing Home the 3 entries have now reduced back to 2, here's an extract from `_pages_versions` for Home with id `66e46b45b8eae04fd6a137eb`:

```
{
  "_id": {
    "$oid": "66f298a93c3d926c5f14fe25"
  },
  "parent": "66e46b45b8eae04fd6a137eb",
  "createdAt": {
    "$date": "2024-09-13T16:41:41.667Z"
  },
  "updatedAt": {
    "$date": "2024-09-24T10:47:05.880Z"
  },
  "latest": true,
  "autosave": false,
  "__v": 0
},
{
  "_id": {
    "$oid": "66f646e8bca12e88ca03a3bc"
  },
  "parent": {
    "$oid": "66e46b45b8eae04fd6a137eb"
  },
  "createdAt": {
    "$date": "2024-09-13T16:41:41.667Z"
  },
  "updatedAt": {
    "$date": "2024-09-27T16:08:47.125Z"
  },
  "autosave": true,
  "__v": 0
},
```
