### ISSUE TITLE
Can't upload font file

### ISSUE THREAD

**Issue by artemszelenov** [payloadcms/payload#8465]
### Environment Info

```text
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: N/A
  pnpm: 9.5.0
Relevant Packages:
  payload: 3.0.0-beta.109
  next: 15.0.0-canary.160
  @payloadcms/db-postgres: 3.0.0-beta.109
  @payloadcms/graphql: 3.0.0-beta.109
  @payloadcms/next/utilities: 3.0.0-beta.109
  @payloadcms/richtext-lexical: 3.0.0-beta.109
  @payloadcms/translations: 3.0.0-beta.109
  @payloadcms/ui/shared: 3.0.0-beta.109
  react: 19.0.0-rc-5dcb0097-20240918
  react-dom: 19.0.0-rc-5dcb0097-20240918
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:12 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 12
```

### Describe the Bug

When I upload a font file I am getting the error of mime type

### Reproduction Steps

1. setting the mime type as `font/woff2` to upload collection type

```js
        upload: {
		staticDir: "fonts",
		mimeTypes: ["font/woff2"],
	},
```

2. Uploading the font file
<img width="545" alt="Screenshot 2024-09-28 at 21 10 00" src="https://github.com/user-attachments/assets/4d3d8c82-0277-4460-a99d-f31210777556">

3. Getting the error: `ValidationError: The following field is invalid: mimeType`

**Comment by paulpopus** [comment]
I just tested this on the latest beta with the merriweather font downloaded from google fonts as .ttf, then converted to woff2 via transfonter and successfully managed to upload it.

Can you verify tha your woff2 file has the mime type set as expected and can you test on the latest beta please? If it still happens please provide a reproduction repo so we can take a closer look at this

**Comment by denolfe** [comment]
Issue is stale. Closing as can't reproduce.
