### ISSUE TITLE
Redirects issue

### ISSUE THREAD

**Issue by Hemraj-tequity** [payloadcms/payload#8475]
# Documentation Issue

## Additional Details

I am using website template of payload version 3 but that are already have implemented redirect plugin collection but it is not working

**Comment by r1tsuu** [comment]
"Not working" is not clear, what's your issue with it. @paulpopus it should work?

**Comment by paulpopus** [comment]
Hey I just tested this on the latest version of the template and it seems to work fine for me. I assume it might've been fixed since so I'll close this issue for now but happy to take a deeper look if there's a reproduction
