### ISSUE TITLE
Monorepo runInit timed out after 4 seconds

### ISSUE THREAD

**Issue by akhrarovsaid** [payloadcms/payload#8482]
### Environment Info

```text
Payload: Monorepo commit #163f3c06
Node: v20.10.0
Next: 15.0.0-canary.160
```

### Describe the Bug

This issue only recently started to occur when I try to run anything in the `test` folder of the monorepo using `pnpm dev <folder>`. 

The logs are as follows:
```
> payload-monorepo@3.0.0-beta.109 dev <PATH>
> cross-env NODE_OPTIONS=--no-deprecation tsx ./test/dev.ts "_community"

Generating import map for config: <PATH>
Restarting process: runInit timed out after 4 seconds
```
This issue has made reproducing user issues on Github impossible, as the process does not get restarted, and there's seemingly nothing I can do to run the app.

Now, I've pinpointed the issue [here](https://github.com/payloadcms/payload/blob/beta/test/dev.ts#L47). 

I'd like to make a PR for this, in my mind an easy fix that could work is simply setting an .env variable named RUNINIT_TIMEOUT or a CLI arg similarly named, to some value that would override the default of 4 seconds if present. 

### Reproduction Steps

I imagine reproduction of this issue may be difficult due to being specific to certain machines and specs thereof. Here's what I did:
- Clone the monorepo
- Run `pnpm dev _community`
- Observe logs in console: "runInit timed out after 4 seconds"

**Comment by r1tsuu** [comment]
This shouldn't happen now as for https://github.com/payloadcms/payload/pull/8532

**Comment by akhrarovsaid** [comment]
Hey @r1tsuu,

Unfortunately I'm still experiencing this issue on the latest. Any thoughts?

**Comment by r1tsuu** [comment]
Not sure, can you try from a fresh pulled down repo? Works fine for me

**Comment by akhrarovsaid** [comment]
For sure - just tried a fresh pull. Unfortunately that didn't fix it. Still getting: `Restarting process: runInit timed out after 4 seconds` and then the process exits and I get the cmd line back.
