### ISSUE TITLE
Multiple query filters on array fields produce "Alias "x" is already used in this query" error

### ISSUE THREAD

**Issue by dsod** [payloadcms/payload#8517]
### Link to reproduction

https://github.com/dsod/payload-nested-docs-alias-bug

### Environment Info

```text
Payload: `3.0.0-beta.109`
NodeJs: 20x
Postgres: 15x
```

### Describe the Bug

When you add multiple query filters onto a array field, for example through access control functions and `filterOptions` using a Postgres server, Drizzle will throw an error like `Error: Alias "" is already used in this query`.

The reproduction repository I created is using the Nested docs core plugin to reproduce the error. The plugin adds `filterOptions` onto the parent field, this in combination with my access control function on the `users` collection is enough to trigger the error. 

### Reproduction Steps

When the `parent` dropdown is opened from the UI and the `filterOptions` is triggered, which filters on the breadcrumbs field in addition to my access control query, the error is triggered.  

More details can be found in the repo readme.

### Adapters and Plugins

db-postgres, nested-docs-plugin

**Comment by r1tsuu** [comment]
Hey @dsod, thank you for you issue! 
Fixed in https://github.com/payloadcms/payload/pull/8823
