### ISSUE TITLE
Fields in a ROW in a TAB doesn't work

### ISSUE THREAD

**Issue by chladog** [payloadcms/payload#853]
# Bug Report
Fields that are children of Row field that is a child of Tabs field doesn't work - they render empty and updates doesn't affect them.

## Expected Behavior

Row and Tab fields shouldn't affect fields child fields.

## Possible Solution

I removed Row altoghether so the fields are placed vertically in a tab, but they are working.

## Detailed Description
payload@1.0.11

**Comment by matthijs166** [comment]
I have got the same issue.
The page can be saved so that the block is created. After that, I open the tab and edit the field (don't switch it) Save the page and the field is set.

If I switch the tabs in the meantime the value of the field is gone.

**Comment by jmikrut** [comment]
Fixed in `1.0.12`!

**Comment by matthijs166** [comment]
I still got the issue that when I have 2 text fields in a tab that the values of the text fields are synced.

They don't have the same name only the same type.
