### ISSUE TITLE
disableBulkEdit doesn't work on ui fields

### ISSUE THREAD

**Issue by tpahore** [payloadcms/payload#8534]
### Environment Info

Payload: 3.0.0-beta.107

### Describe the Bug

Create any field with type: ui, add disableBulkEdit: true,
its still visible in bulk edit.

### Reproduction Steps

Create a ui field like this

```
    {
      name: 'customUiField',
      type: 'ui',
      admin: {
        components: {
          Field: '@/components/ui/placeholders.component',
        },
        disableListColumn: true,
        disableBulkEdit: true,
      },
    }
```

Expected: the "Custom Ui Field" should not be visible here
![Image](https://github.com/user-attachments/assets/4667849e-c609-4b95-9c92-311f7ec1f588)

**Comment by r1tsuu** [comment]
Fixed in https://github.com/payloadcms/payload/pull/8540, we disable them by default now in the bulk edit
