### ISSUE TITLE
'debug' does not exist in type 'I18nOptions<{}...

### ISSUE THREAD

**Issue by Because789** [payloadcms/payload#8562]
### Environment Info

Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.11.0
Relevant Packages:
  payload: 3.0.0-beta.111
  next: 15.0.0-canary.173
  @payloadcms/db-mongodb: 3.0.0-beta.111
  @payloadcms/email-nodemailer: 3.0.0-beta.111
  @payloadcms/graphql: 3.0.0-beta.111
  @payloadcms/next/utilities: 3.0.0-beta.111
  @payloadcms/plugin-cloud: 3.0.0-beta.111
  @payloadcms/plugin-nested-docs: 3.0.0-beta.111
  @payloadcms/plugin-seo: 3.0.0-beta.111
  @payloadcms/richtext-lexical: 3.0.0-beta.111
  @payloadcms/translations: 3.0.0-beta.111
  @payloadcms/ui/shared: 3.0.0-beta.111
  react: 19.0.0-rc-3edc000d-20240926
  react-dom: 19.0.0-rc-3edc000d-20240926
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
  Available memory (MB): 15841
  Available CPU cores: 8

### Describe the Bug

I'm working on i18n stuff and I tried to add `debug=true` to my configuration as described here: 
https://payloadcms.com/docs/beta/configuration/i18n#config-options 

When doing so, I'm getting this error:

`Object literal may only specify known properties, and 'debug' does not exist in type 'I18nOptions<{}...`

It seems to me, that there are other issues with the i18n docs, too. I tried to implement this example: https://payloadcms.com/docs/beta/configuration/i18n#typescript and wasn't able to get it to work.

### Reproduction Steps

Add `debug` to i18n configuration.

**Comment by JarrodMFlesch** [comment]
@Because789 This has been fixed, you can see the updated docs [here](https://payloadcms.com/docs/beta/configuration/i18n#typescript) and the [related PR here](https://github.com/payloadcms/payload/pull/8619).

Thanks for pointing it out!
