### ISSUE TITLE
richtext-lexical: HTML convert does not apply target _blank to new tab links

### ISSUE THREAD

**Issue by GeekPro101** [payloadcms/payload#8569]
### Describe the Bug

(Fixed in v3)
![Image](https://github.com/user-attachments/assets/abbccc21-b22b-453b-85ae-87932e42a88b)

Generates the following link:
`<a href="https://google.com" rel="noopener noreferrer">google.com</a>`

Issue lies in:

https://github.com/payloadcms/payload/blob/268e6c485e67440d8ce0dd7679705d8581a269c1/packages/richtext-lexical/src/field/features/Link/index.ts#L127

### To Reproduce

Create a document with a richtext-lexical richtext editor + htmlConverter
Create a link and tick new tab option (see above)
Observe no _blank attribute in <a>

### Payload Version

v2.15.0

### Adapters and Plugins

db-mongdb, bundler-webpack, richtext-lexical

**Comment by GermanJablo** [comment]
Thank you!
