### ISSUE TITLE
`useField` does not allow being called with no arguments

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#8577]
### Environment Info

Node.js v22.7.0

Binaries:
  Node: 22.7.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.9.0
Relevant Packages:
  payload: 3.0.0-beta.111
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10

### Describe the Bug

In https://payloadcms.com/docs/beta/admin/hooks#usefield, the documentation suggests `useField()` can be called with no arguments. But this isn't actually allowed by the type signature:

```
export const useField = <T,>(options: Options): FieldType<T> => {
```

I think this is a bug on the typing side.

### Reproduction Steps

N/A

**Comment by DanRibbens** [comment]
You're comparing `useField` having a type with a required object to `useFieldProps` which is a different hook. I'm not sure the purpose of having both with different signatures.

**Comment by tyteen4a03** [comment]
> You're comparing `useField` having a type with a required object to `useFieldProps` which is a different hook. I'm not sure the purpose of having both with different signatures.

I made an oopsie copying the link, here is the correct one: https://payloadcms.com/docs/beta/admin/hooks#usefield

**Comment by PatrikKozak** [comment]
Hey @tyteen4a03 - good catch.

You are correct that the `useField` hook should be able to be called without any arguments at the moment.

However, we have some changes coming in very soon that will be removing the `useFieldProps` hook completely so you'll be able to get `path` from props directly and be required to thread it through the `useField` hook.

I will leave this issue open for now and once those changes come through where an argument will be required again - I will close.

Is this issue blocking for you right now?

**Comment by tyteen4a03** [comment]
> Hey @tyteen4a03 - good catch.
> 
> You are correct that the `useField` hook should be able to be called without any arguments at the moment.
> 
> However, we have some changes coming in very soon that will be removing the `useFieldProps` hook completely and you'll be able to get `path` from props directly and be required to thread it through the `useField` hook.
> 
> I will leave this issue open for now and once those changes come through where an argument will be required again - I will close.
> 
> Is this issue blocking for you in any way right now?

Not in particular, since I can work around this by passing an empty object.

**Comment by akhrarovsaid** [comment]
Those aforementioned changes were merged. Path must be passed in object passed to `useField`. See [types here](https://github.com/payloadcms/payload/blob/beta/packages/ui/src/forms/useField/types.ts#L6) and [where it's used](https://github.com/payloadcms/payload/blob/beta/packages/ui/src/forms/useField/index.tsx#L31). I think this issue can be closed.

**Comment by PatrikKozak** [comment]
@akhrarovsaid You are ON TOP of things! Love to see it. 

@tyteen4a03 Going to close this issue - as @akhrarovsaid has mentioned - we just pushed some changes, one of them being that `path` will be required to be passed to the `useField` hook.

We'll get a beta release out with these changes this week.
