### ISSUE TITLE
Custom View

### ISSUE THREAD

**Issue by zainaliyt** [payloadcms/payload#8587]
### Environment Info

payload: 3.0.0-beta.107
next: 15.0.0-canary.104
Node: 20.11.1

### Describe the Bug

Hi! i am trying to create custom view for admin page, as i want to show statistics in /admin/stats but i am unable to create a view.  I get error Type '() => React.JSX.Element' is not assignable to type 'AdminViewComponent'.ts(2322)

### Reproduction Steps

Creating Custom View

**Comment by r1tsuu** [comment]
Refer to the docs https://payloadcms.com/docs/beta/admin/views#root-views, you need to pass the path of the component instead

```ts
import { buildConfig } from 'payload'

const config = buildConfig({
  // ...
  admin: {
    components: {
      views: {
        customView: {
          Component: '/path/to/Stats#Stats', 
          path: '/stats',
        }
      },
    },
  },
})
```

**Comment by zainaliyt** [comment]
Thanks alot, works. How can i edit the nav as i want to add buttons to these views.
