### ISSUE TITLE
`VipsJpeg` error when trying to uploading certain jpeg images i.e from a samsung

### ISSUE THREAD

**Issue by PatrikKozak** [payloadcms/payload#8606]
### Describe the Bug

There's a bug in Samsung firmware that prevents it from producing valid JPEG files. See more here: https://github.com/lovell/sharp/issues/1578

![Image](https://github.com/user-attachments/assets/3e69b4b9-d45e-4df4-95a4-f203f0ed9538)

Need to explicitly pass `failOn: 'none'` to `sharpOptions` to read these buggy Samsung images.

### To Reproduce

Upload a samsung based jpeg image

### Payload Version

`v3.0.0-beta.111` or `v2.30.1`

**Comment by PatrikKozak** [comment]
@max-degterev tagging you here for visibility - will have a PR out for this asap

**Comment by PatrikKozak** [comment]
Hi @max-degterev, 

I’ve discussed this issue with the team again, and I wanted to follow up.

In V3, we’ve introduced the ability to customize `sharp` options by defining the module directly in the root config. You can address the issue by adding the following in your root config after importing `sharp`:

`sharp: (inputFile, options) => sharp(inputFile, { ...options, failOn: 'none' }),`

This gives you full control over which options to pass, allowing for greater flexibility.

For V2, I'd recommend advising your users to save the corrupted files to another device or use an online service to compress the image, as this should strip the problematic metadata. At this time, we don’t feel comfortable enabling this option globally for all users.

Thank you for bringing this up - if there is anything else we can assist with - let us know!

**Comment by max-degterev** [comment]
I'm curious what was the downside of allowing poorly formatted JPEGs to pass? Security? I was running this exact setup in prod for many years.
