### ISSUE TITLE
defaultValue is ignored when creating a doc from "Add new" on a join field.

### ISSUE THREAD

**Issue by energee** [payloadcms/payload#8612]
### Environment Info

  Node: 22.9.0
  npm: 10.8.3
  Yarn: 1.22.22
  pnpm: 9.10.0
Relevant Packages:
  payload: 3.0.0-beta.111
  next: 15.0.0-canary.173
  @payloadcms/db-mongodb: 3.0.0-beta.111
  @payloadcms/graphql: 3.0.0-beta.111
  @payloadcms/next/utilities: 3.0.0-beta.111
  @payloadcms/richtext-lexical: 3.0.0-beta.111
  @payloadcms/translations: 3.0.0-beta.111
  @payloadcms/ui/shared: 3.0.0-beta.111
  react: 19.0.0-rc-3edc000d-20240926
  react-dom: 19.0.0-rc-3edc000d-20240926

### Describe the Bug

defaultValue setting appears to not work when generating a new doc from a join field.

### Reproduction Steps

Set a defaultValue on a collection -> Test by creating a new item -> Try creating a new item from a join field ("Add New" or "Create New <collectionName>" button), field will be blank.

### Adapters and Plugins

db-mongodb

**Comment by akhrarovsaid** [comment]
Hey @energee,

Thanks for your patience - I have a [PR up for this](https://github.com/payloadcms/payload/pull/8791).

**Comment by akhrarovsaid** [comment]
Hey @energee,

I've closed my PR as I'm no longer able to reproduce this issue in the monorepo as of `beta.128`. Try updating your Payload packages and test if you're still experiencing default values not populating?

**Comment by jacobsfletch** [comment]
> I'm no longer able to reproduce this issue in the monorepo as of beta.128.

Same. Thanks again for confirming @akhrarovsaid 🙏
