### ISSUE TITLE
GraphQL Playground is not working with the latest beta release (v3.0.0-beta.111)

### ISSUE THREAD

**Issue by mykz** [payloadcms/payload#8616]
### Link to reproduction

N/A

### Environment Info

payload-1  |  GET /api/graphql 405 in 940ms
payload-1  |  GET /api/graphql 405 in 20ms

### Describe the Bug

The GraphQL Playground is not working with the latest beta release (v3.0.0-beta.111).

**The Playground shows the following error:**
```json
{
  "error": "Expected property name or '}' in JSON at position 4 (line 2 column 3)"
}
``` 
It also displays the message: "Server cannot be reached."

I encountered this issue on both a current installation and a fresh setup, using the following configuration:

**Database**: MongoDB
**Template**: Blank Template

The results were the same in both cases.

### Reproduction Steps

- Install Blank Template for latest beta release (v3.0.0-beta.111) with MongoDB
- Run local install via docker-compose & pnpm
- Navigate to http://localhost:3000/api/graphql-playground

**Comment by akhrarovsaid** [comment]
Hey @mykz,

I'm unable to reproduce your issue via the monorepo or using create-payload-app with the latest beta version (beta.112) with the blank template option and mongodb. You mention docker-compose but I'm unsure of where docker-compose fits into this? Can you post a reproduction link?

**Comment by mykz** [comment]
@akhrarovsaid Thanks for looking into it. Annoyingly, it turned out that a Chrome extension I had installed was causing the problem. Everything is working now, so I'll go ahead and close this issue.

Just a heads-up: I was running the environment using the docker-compose configuration provided in the template repository, which should answer your question about why docker-compose is being used.
