### ISSUE TITLE
Value of field type "ui" not being persisted

### ISSUE THREAD

**Issue by glappsi** [payloadcms/payload#8626]
### Environment Info

Payload: 3.0.0-beta.109
Next.js: 15.0.0-canary.171
node.js: 22.9.0

### Describe the Bug

When creating a custom field with the ui type, the selected value won't be persisted on save. It is submitted correctly to the API, I checked in the network manager.

### Reproduction Steps

1. Create a ui field
```
{
  name: 'icon',
  type: 'ui',
  admin: {
    components: {
      Field: '/components/payload/icon-select#IconSelectComponent',
      Cell: '/components/payload/icon-select#IconUIComponent',
    },
  },
},
```

2. Create the custom component
```
'use client';

import * as React from 'react';
import { Button, useField } from '@payloadcms/ui';
import Icons, { IconKeys } from '@/components/ui/icon';

type WidgetSelectProps = {
  field: { name: string };
};

export const IconSelectComponent: React.FC<WidgetSelectProps> = ({
  field: { name },
}) => {
  const { value, setValue } = useField<string>({ path: name });

  const _setValue = React.useCallback(
    (value: string) => {
      setValue(value);
    },
    [setValue],
  );

  return (
    <div className='icon-select'>
      <label className='field-label'>Select an icon</label>
      <div style={{ display: 'flex', gap: '5px', flexWrap: 'wrap' }}>
        {IconKeys.map((iconKey) => {
          const IconComp = Icons[iconKey];
          return (
            <Button
              key={iconKey}
              buttonStyle={value === iconKey ? 'primary' : 'secondary'}
              icon={<IconComp />}
              onClick={() => _setValue(iconKey)}
            ></Button>
          );
        })}
      </div>
    </div>
  );
};

export const IconUIComponent: React.FC<WidgetSelectProps> = ({
  field: { name },
}) => {
  const { value } = useField<string>({ path: name?.substring(1) });

  return value;
};
```

3. Select an icon and try to save the value, reload, nothing is selected. There is no icon field sent by the API either, not even `null`.

### Adapters and Plugins

`@payloadcms/storage-s3`
`@payloadcms/db-postgres`

**Comment by akhrarovsaid** [comment]
Hey @glappsi,

The `UI` field in Payload is considered a "presentation only" field as can be seen from the[ first few lines of the docs](https://payloadcms.com/docs/beta/fields/ui). What you are experiencing is technically expected behaviour.

I think to fix your issue, you should switch to a tradition `Text` field, implement your custom component with icons, and you should have a working implementation of the behavior you wish to see where your data is persisted. Hope this helps!

**Comment by glappsi** [comment]
Hi @akhrarovsaid,

I tend just scroll to the code part in documentations. Sometimes it helps to read the rest, too :D 
Thanks for you friendly answer.

Have a nice day.
