### ISSUE TITLE
`db-mongodb`: id parsing issues

### ISSUE THREAD

**Issue by Fitch24** [payloadcms/payload#8652]
### Link to reproduction

https://github.com/Fitch24/payload/blob/mongodb-id-parsing-issue/test/_community/int.spec.ts

### Describe the Bug

`db-mongodb` adapter produces some bugs when passing non-standard `id` (non `ObjectId` values or `ObjectId` with uppercase symbols) in local/rest (and probably GraphQL) API

- Server returns `500 InternalServerError` if it's failed to parse (cast to `ObjectId`) id in REST-API queries. I think, it must be a client error, because of passing correct `id type` is part of validation and not a server problem.
- When filling any relationship fields with `id` that contains upper case symbols, field population will be broken. Also admin UI in collection list view will be infinitely trying to populate broken field without success (I have no reproduction for this)

### To Reproduce

1. Use collection with relationship field
2. Add item to collection with relationship field in uppercase (via REST-API for example, because of you can't pass raw id directly in Admin-UI)
3. Try to query this collection and see that relationship field is not populated

Please see reproduction link for more detailed example

### Payload Version

2.30.1

### Adapters and Plugins

db-mongodb

**Comment by DanRibbens** [comment]
This PR should address your issue: https://github.com/payloadcms/payload/pull/8395/files
