### ISSUE TITLE
TypeError: Cannot create property 'digest' on string when using next version >= 15.0.0-canary.184

### ISSUE THREAD

**Issue by mattiaz9** [payloadcms/payload#8663]
### Environment Info

node: 22.9.0
next: 15.0.0-canary.184
payload: 3.0.0-beta.113

### Describe the Bug

After signing in I get a client side error: `Cannot create property 'digest' on string` when next version is >= 15.0.0-canary.184
Downgrading to canary 183 fixed the issue.

### Reproduction Steps

1. `pnpm i next@15.0.0-canary.184 payload@3.0.0-beta.113`
2. `pnpm run dev`
3. sign in

**Comment by ChrisB1123** [comment]
I found this from Google - I think this might be a NextJS issue, I had the same problem with NextJS v 14.2.15, and I don't have payload CMS installed. It's fine after downgrading to v14.1

**Comment by mattiaz9** [comment]
It looks like it has been fixed with the latest canary!
