### ISSUE TITLE
Inline block with a relationship field (that contains a rich-text ) is not working

### ISSUE THREAD

**Issue by ChannKan** [payloadcms/payload#8676]
### Link to reproduction

https://github.com/shefing/payload_Inline_block_with_relationship/tree/Inline_block_with_relationship

### Environment Info

Output from 'pnpm payload info':
Binaries:
  Node: 20.9.0
  npm: 10.2.5
  Yarn: 1.22.21
  pnpm: 9.10.0
Relevant Packages:
  payload: 3.0.0-beta.104
  next: 15.0.0-canary.104
  @payloadcms/db-mongodb: 3.0.0-beta.104
  @payloadcms/graphql: 3.0.0-beta.104
  @payloadcms/live-preview: 3.0.0-beta.104
  @payloadcms/next/utilities: 3.0.0-beta.104
  @payloadcms/plugin-cloud-storage: 3.0.0-beta.104
  @payloadcms/plugin-redirects: 3.0.0-beta.104
  @payloadcms/plugin-seo: 3.0.0-beta.104
  @payloadcms/richtext-lexical: 3.0.0-beta.104
  @payloadcms/storage-s3: 3.0.0-beta.104
  @payloadcms/translations: 3.0.0-beta.104
  @payloadcms/ui/shared: 3.0.0-beta.104
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801

### Describe the Bug

When creating an inline-block with a relationship field to a collection that contains a rich-text field,
The following scenario is problematic:
When inserting the inline-block and clicking the **'+'** button of the relationship field - the new instance of the collection that is created has disabled rich-text field. 

### Reproduction Steps

**Steps to reproduce:** 

1. Clone the link to reproduction ripo and launch Payload
2. Create a new Post instance 
3. Add the inline-block in the rich-text field 
4. In the pop-up window click on the **'+'** of the relationship field 
5. Go to the rich-text field in the new Post opened 
6. Try to type 

**Expected:** 
Rich-text field is responsive 

**Actual:**
Rich-text field is disabled 

### Adapters and Plugins

 db-mongodb

**Comment by tsemachh** [comment]
Looks like it was resolved in latest version @ChannKan you can close it
