### ISSUE TITLE
Date field looks messed up in beta-113

### ISSUE THREAD

**Issue by Because789** [payloadcms/payload#8683]
### Link to reproduction

https://github.com/Because789/date-field-test

### Environment Info

Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.11.0
Relevant Packages:
  payload: 3.0.0-beta.113
  next: 15.0.0-canary.173
  @payloadcms/email-nodemailer: 3.0.0-beta.113
  @payloadcms/graphql: 3.0.0-beta.113
  @payloadcms/next/utilities: 3.0.0-beta.113
  @payloadcms/plugin-cloud: 3.0.0-beta.113
  @payloadcms/richtext-lexical: 3.0.0-beta.113
  @payloadcms/translations: 3.0.0-beta.113
  @payloadcms/ui/shared: 3.0.0-beta.113
  react: 19.0.0-rc-3edc000d-20240926
  react-dom: 19.0.0-rc-3edc000d-20240926

### Describe the Bug

Date field looks messed up in beta-113, at least in dark mode:

![Image](https://github.com/user-attachments/assets/8fe1f7d6-a210-4ae7-8b4d-e31f3f27bb70)

### Reproduction Steps

See repository for minimal reproduction.

**Comment by paulpopus** [comment]
The PR has been merged and the fix will be available in the next release!
