### ISSUE TITLE
Lexical editor richtext field is not editable collection gets created through an relation field.

### ISSUE THREAD

**Issue by ckruppe** [payloadcms/payload#8691]
### Environment Info

Binaries:
  Node: 20.11.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.113
  next: 15.0.0-canary.173
  @payloadcms/db-mongodb: 3.0.0-beta.113
  @payloadcms/graphql: 3.0.0-beta.113
  @payloadcms/live-preview: 3.0.0-beta.113
  @payloadcms/live-preview-react: 3.0.0-beta.113
  @payloadcms/next/utilities: 3.0.0-beta.113
  @payloadcms/plugin-nested-docs: 3.0.0-beta.113
  @payloadcms/plugin-seo: 3.0.0-beta.113
  @payloadcms/richtext-lexical: 3.0.0-beta.113
  @payloadcms/richtext-slate: 3.0.0-beta.113
  @payloadcms/translations: 3.0.0-beta.113
  @payloadcms/ui/shared: 3.0.0-beta.113
  react: 19.0.0-rc-3edc000d-20240926
  react-dom: 19.0.0-rc-3edc000d-20240926
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32488
  Available CPU cores: 16

### Describe the Bug

If i have an relation field to another collection and create an new entry in the connected collection while i create the parent entry, the richtext field is not editable inside the "Modal".
Its neather clickable nor reachable by tab navigation.
![Image](https://github.com/user-attachments/assets/280d9122-7470-45b3-a732-07eec9ac212a)

### Reproduction Steps

1) Create an collection with an relation to another one.
2) The second collection has an richtext field.
3) Create an new entry in the first collection and try to create an new entity of the second one through the relation field.
4) Every field is editable except the richtext field.

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/issues/8691
