### ISSUE TITLE
Not found is being displayed within the admin panel styling for non authenticated users

### ISSUE THREAD

**Issue by karlapsite** [payloadcms/payload#8716]
### Link to reproduction

https://github.com/karlapsite/payload/tree/fix/create-user-redirection-issue-reproduction

[diff](https://github.com/payloadcms/payload/compare/payloadcms:payload:beta...karlapsite:payload:fix/create-user-redirection-issue-reproduction)

### Environment Info

Should be latest n' greatest:

Payload: v3.0.0-beta.114
Node.js: 22.6.0
Next.js: 15.0.0-canary.17

### Describe the Bug

I'm playing around with the blank and website templates with a coworker. We're a little confused why navigating in browser to `/admin/foobar` doesn't forward us to `/admin/create-first-user`  like it does in other cases... I haven't created my first account yet... it seems a little weird to be able to peek at the public collections (or render any semblance of the admin portal at all yet) Clicking on anything does redirect me to `/admin/create-first-user`

Is this intentional behavior?

If we don't want users to peak the unauthed admin page... is there an easy way to modify the admin not-found template to redirect us somehow? or is there a cleaner place to catch/forward this case? 

A similar issue seems to exist _after_ the first account has been created... my expectation was to see the admin portal redirect the user to the login component and prevent them from seeing the admin portal/sidebar.

To my knowledge this isn't a security issue, as the user can only see the names of collections that are public read. Authorized collections won't appear in the sidebar... So this is only disorienting at best

### Reproduction Steps

1. Comment out the `devUser` in the _community template.
2. _Before creating an account, or logging in:_
3. Navigate to `/admin/foobar`
![Image](https://github.com/user-attachments/assets/cae58368-f7aa-4143-ac63-72d61abd9413)

**Comment by akhrarovsaid** [comment]
Hey @karlapsite,

So I actually reproduced your issue using the `_community` folder in the monorepo. You can avoid the default login by commenting out [these lines](https://github.com/payloadcms/payload/blob/beta/test/_community/config.ts#L154-L160). I don't believe there's an issue there as this is done for a smoother dev experience while working with the test folders.

**Comment by karlapsite** [comment]
Thanks for the tip @akhrarovsaid! The specific issue with the dev credentials in my third point is a little nitty-gritty.

I didn't have too much trouble commenting out the devUser to play around with the `/create-first-user` flow... but once I made my devUser... I wanted to make sure that payload would properly redirect users to the login page... and _there was some trouble there._

When using default credentials, **I couldn't logout**. manually navigating to `/admin/logout` indicated that I _did_ logout in a toast, but I suspect something in the `_community` folder auto-logs in the devUser if those specific dev credentials are present. I worked around this by removing the devUser account, and manually creating an account with different credentials. That seems to let me play around with login/logout just fine...

When navigating to `/admin/foobar` when there _is a dev account_ but the user just isn't logged in... the same issue is present.

After some playing around, It would seem a change like the [one I tinkered with](https://github.com/karlapsite/payload/commit/b3f366221ff0a12d3a291ddf99a8f14349796f37) could address both sides of this issue.

Separately, my change does appear to tinker with some sort of login redirection, but it _does not appear_ to function yet... which sounds out-of-scope to me... perhaps a good candidate for a follow-up issue.

**Comment by paulpopus** [comment]
Hey all, thanks for all the investigations here, I wouldnt touch the default login and such. The issue here is actually just that the notFound page is visible within the layout of the admin panel if you are not authenticated. It's not isolated to the create first user flow, so I updated the title

**Comment by paulpopus** [comment]
Thanks guys for the report here, went down a rabbithole with more functionality around this tested. This will be fixed in https://github.com/payloadcms/payload/pull/8820

Non authorised users should be redirected to /login as per v2 behaviour in this situation.
