### ISSUE TITLE
UI: Lexical Fixed Toolbar z-index: 2 style leads to covering of select values in field above

### ISSUE THREAD

**Issue by n-a-t-j-b** [payloadcms/payload#8728]
### Describe the Bug

The class involved is "fixed-toolbar" and is located in @payloadcms\richtext-lexical\dist\field\bundled.css.

Not sure if the toolbar was intentionally given a z-index of 2 to combat another issue (possibly when it is a popup?), but removing the style or setting it to 0, fixes the UI problem for the Select above it.  Obviously not an issue if the FixedToolbarFeature() is not configured for the field.

Apologies, having not noticed this previously I'm unsure when the issue started.

### **z-index:2**
![Image](https://github.com/user-attachments/assets/329ea93d-4eb5-4f03-8db1-4a1af539f300)

### **z-index:0**
![Image](https://github.com/user-attachments/assets/3ced91c0-480b-4899-b519-c7063ca79078)

### Link to the code that reproduces this issue

n/a

### Reproduction Steps

Include any select field directly above a richText field type in the collection config.  Enable "FixedToolbarFeature()" in lexicalEditor features e.g. for the above images this is a simplified fields[] config:

```typescript
  {
    name: 'size',
    type: 'select',
    defaultValue: 'oneThird',
    options: [
      {
        label: 'One Third',
        value: 'oneThird',
      },
      {
        label: 'Half',
        value: 'half',
      },
      {
        label: 'Two Thirds',
        value: 'twoThirds',
      },
      {
        label: 'Full',
        value: 'full',
      },
    ],
  },
  {
    name: 'richText',
    type: 'richText',
    editor: lexicalEditor({
      features: ({ rootFeatures }) => {
        return [
          ...rootFeatures,
          FixedToolbarFeature(),
        ]
      },
    }),
  },

``` 

### Which area(s) are affected? (Select all that apply)

plugin: richtext-lexical

### Environment Info

payload: 3.0.0-beta.114
Node: 20.15.0
next: 15.0.0-canary.173

Other relevant versions
@payloadcms/richtext-lexical: 3.0.0-beta.114
lexical: 0.18.0

**Comment by r1tsuu** [comment]
Hey @n-a-t-j-b, your issue is valid, I opened a PR https://github.com/payloadcms/payload/pull/8735 @denolfe will likely re-look into how we handle these!

**Comment by RichiePowell** [comment]
I can also see this issue, so I'm following.

**Comment by r1tsuu** [comment]
Fixed here https://github.com/payloadcms/payload/pull/8735!
