### ISSUE TITLE
[plugin-seo] `minLength` and `maxLength` are referenced from defaults and cannot be changed

### ISSUE THREAD

**Issue by maciej-uxmachina** [payloadcms/payload#8745]
[updated with a forked repo]

**Reproduction fork**
https://github.com/maciej-uxmachina/payload-plugin-seo-length-overrides-issue/tree/beta

**Reproduction changes made**
https://github.com/maciej-uxmachina/payload-plugin-seo-length-overrides-issue/commit/3e42d06cb13c6c435f5c763b8776bb9b4566a380

**Reproduction steps**
1. `pnpm dev _community`
2. Go to http://localhost:3000/admin/globals/LandingPage
3. Switch to the `SEO` tab
4. In the `Title` field, enter text longer than or equal to `10` characters
5. Observe the `plugin-seo:tooShort` is still displayed below the field and the progress bar is still red, indicating there's more characters that still should be entered

Please note in the field config:
```
MetaTitleField({
  hasGenerateFn: true,
  overrides: {
    localized: true,
    minLength: 10,
  },
}),
```

P.S. I haven't investigated why translations are not being pulled when testing via `pnpm dev _community` but it should not prevent reproducing this issue

**Expected outcome**
The progress bar and all informational texts should reflect the value `10` as the `minLength` rather than the default `50`.

**Comment by akhrarovsaid** [comment]
Hey @maciej-uxmachina,

I'd love nothing more than to help you and the devs in getting this issue sorted. However, it's really hard to do that since you did not follow the [standard issue template](https://github.com/payloadcms/payload/blob/main/CONTRIBUTING.md#opening-issues).

Despite this, I have tried to reproduce your issue with the `plugin-seo` test folder in the monorepo to no avail. I am able to edit `maxLength` and `minLength` for both fields via the `fieldsOverrides` [option passed directly into the plugin](https://payloadcms.com/docs/plugins/seo#options).

Can you format your issue to follow the template and include the relevant information (such as Payload version, adapter version, node version, etc.)?

**Comment by maciej-uxmachina** [comment]
Thanks for the reply @akhrarovsaid and apologies for not following the guide.
**I'll work on the fork that reproduces this issue.**

Meanwhile, in case it helps, I isolated this issue to be specifically related to the `LengthIndicator` and `lengthTipTitle`. The actual validation (ability to publish a collection for example) does respect the `minLength` and `maxLength` overrides.

Here are two screenshots showing the behaviour with `minLength` set to `10`.
In both cases the `lengthTipTitle` and `LengthIndicator` show the default `minLength` of `50`, while only the error message shows the correct `10`:
![Image](https://github.com/user-attachments/assets/7dc1bb6a-f094-4f08-a496-bbe4c2a81de1)

![Image](https://github.com/user-attachments/assets/4edc4a8b-01da-4bef-b166-d93172fa1190)

Still as mentioned, I'll create a fork to reproduce this issue. Thank you for your support.

**Comment by maciej-uxmachina** [comment]
**Reproduction fork**
https://github.com/maciej-uxmachina/payload-plugin-seo-length-overrides-issue/tree/beta

**Reproduction changes made**
https://github.com/maciej-uxmachina/payload-plugin-seo-length-overrides-issue/commit/3e42d06cb13c6c435f5c763b8776bb9b4566a380

**Reproduction steps**
1. `pnpm dev _community`
2. Go to http://localhost:3000/admin/globals/LandingPage
3. Switch to the `SEO` tab
4. In the `Title` field, enter text longer than or equal to `10` characters
5. Observe the `plugin-seo:tooShort` is still displayed below the field and the progress bar is still red, indicating there's more characters that still should be entered

Please note in the field config:
```
MetaTitleField({
  hasGenerateFn: true,
  overrides: {
    localized: true,
    minLength: 10,
  },
}),
```

P.S. I haven't investigated why translations are not being pulled when testing via `pnpm dev _community` but it should not prevent reproducing this issue

**Expected outcome**
The progress bar and all informational texts should reflect the value `10` as the `minLength` rather than the default `50`.

**Comment by paulpopus** [comment]
Thanks for adding a repro!
