### ISSUE TITLE
Duplicate index error with similar field names

### ISSUE THREAD

**Issue by ars3nicum** [payloadcms/payload#8752]
### Describe the Bug

Collection with the following fields:

```
{
      name: 'blocks',
      type: 'array',
      localized: true,
      label: 'Blocks',
      fields: [
        
        {
          name: 'image',
          type: 'upload',
          relationTo: 'media',
          localized: true,
        },
      ],
    },
    
    {
      name: 'blocksImage',
      type: 'upload',
      relationTo: 'media',
    }

```
will cause an error
`Warning  We've found duplicated index name across public schema. Please rename your index in either the ... table or the table with the duplicated index name`

because of similarity of names blocks.image and blocksImage

### Link to the code that reproduces this issue

https://github.com/ars3nicum/payload-bug

### Reproduction Steps

written above

### Which area(s) are affected? (Select all that apply)

db-postgres

### Environment Info

Payload: beta 114
Node.js: 22.9.0
Next.js: 15.0.0-canary.173

**Comment by r1tsuu** [comment]
Fixed in https://github.com/payloadcms/payload/pull/8754
