### ISSUE TITLE
Next.js Dependency not fulfilled for RC 2 in beta branch

### ISSUE THREAD

**Issue by motz0815** [payloadcms/payload#8761]
### Describe the Bug

The current beta version of payload only requires Next.js canary version 173, which the new RC 2 version of Next.js satisfies. (15.0.0-rc.1)

```
 ⨯ Error: Dependency next is on version 15.0.0-rc.1, but >=15.0.0-canary.173 or greater is required. Please update this dependency.
    at checkDependencies (/Users/motz/Documents/Entwicklung/darta/.next/server/chunks/ssr/node_modules_payload_dist_ec74b9._.js:14578:31)
    at async RootLayout (/Users/motz/Documents/Entwicklung/darta/.next/server/chunks/ssr/node_modules_@payloadcms_c70ccb._.js:3166:9)
```

### Link to the code that reproduces this issue

package.json-related (follow the steps below)

### Reproduction Steps

1. Create a blank payload beta repo.
2. Update Next.js to the RC 2 using `npx @next/codemod@canary upgrade rc`
3. Run the app and access the payload admin panel at `/admin` 

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

Binaries:
  Node: 20.18.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  payload: 3.0.0-beta.115
  next: 15.0.0-rc.1
  @payloadcms/db-mongodb: 3.0.0-beta.115
  @payloadcms/email-nodemailer: 3.0.0-beta.115
  @payloadcms/graphql: 3.0.0-beta.115
  @payloadcms/next/utilities: 3.0.0-beta.115
  @payloadcms/plugin-cloud: 3.0.0-beta.115
  @payloadcms/richtext-lexical: 3.0.0-beta.115
  @payloadcms/translations: 3.0.0-beta.115
  @payloadcms/ui/shared: 3.0.0-beta.115
  react: 19.0.0-rc-cd22717c-20241013
  react-dom: 19.0.0-rc-cd22717c-20241013
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:25 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6030
  Available memory (MB): 18432
  Available CPU cores: 11

**Comment by r1tsuu** [comment]
[117 beta](https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.117) supports stable Next.js version 15.0.0 so it's not relevant anymore
