### ISSUE TITLE
"Functions cannot be passed directly to Client Components" when trying to use `cloudStorage`

### ISSUE THREAD

**Issue by jonathanelmgren** [payloadcms/payload#8762]
### Describe the Bug

Hi I'm getting:
```
Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server". Or maybe you meant to call this function rather than return it.
  {avatar: ..., components: {}, custom: ..., dateFormat: ..., dependencies: ..., disable: ..., importMap: ..., meta: ..., routes: ..., theme: ..., user: ..., webpack: function}
  ^^^^^^^^                                                                                                                                                                     
```

When I'm trying to use `cloudStorage` from `@payloadcms/plugin-cloud-storage`. No matter what adapter I use.

### Link to the code that reproduces this issue

https://github.com/jonathanelmgren/payload-cms-pcs

### Reproduction Steps

1. Clone repo
2. Start dev server
3. Try go to /admin

### Which area(s) are affected? (Select all that apply)

plugin: cloud-storage, db-postgres

### Environment Info

Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 9.7.1
Relevant Packages:
  payload: 3.0.0-beta.116
  next: 15.0.0-canary.173
  @payloadcms/db-postgres: 3.0.0-beta.116
  @payloadcms/email-nodemailer: 3.0.0-beta.116
  @payloadcms/graphql: 3.0.0-beta.116
  @payloadcms/next/utilities: 3.0.0-beta.116
  @payloadcms/plugin-cloud: 3.0.0-beta.116
  @payloadcms/plugin-cloud-storage: 1.2.0
  @payloadcms/richtext-lexical: 3.0.0-beta.116
  @payloadcms/translations: 3.0.0-beta.116
  @payloadcms/ui/shared: 3.0.0-beta.116
  react: 19.0.0-rc-3edc000d-20240926
  react-dom: 19.0.0-rc-3edc000d-20240926
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 10

**Comment by akhrarovsaid** [comment]
Hey @jonathanelmgren,

[It seems](https://github.com/jonathanelmgren/payload-cms-pcs/blob/main/package.json#L21) like you're trying to use the cloud storage plugin for v2 yet are using Payload v3. Can you try installing the beta version of the cloud storage plugin?

**Comment by paulpopus** [comment]
As above, you can see a list of our beta adapters https://payloadcms.com/docs/beta/upload/storage-adapters#s3-storage

In v3 beta we moved away from one package to having specific adapters and their beta version should always match with the installed payload version.
