### ISSUE TITLE
Dropdown menus sometimes cause page hangs on Chromium Edge

### ISSUE THREAD

**Issue by thunder-red-star** [payloadcms/payload#877]
# Bug Report

I am currently trying to test out a relationship field, and have an Opportunity collection with a single-choice relationship field Category, and a multi-choice relationship field named Tags, as well as a title, rich text field and two date selections.

When choosing relationships either Category or Tags on Edge, sometimes my page hangs, nothing is clickable, and I have to delete the tab. Notably, this only happens #1 on Chromium Edge, and #2 sometimes, I can't figure out a pattern as to why it is crashing.
## Expected Behavior

Page should allow me to select without crashing.
## Current Behavior

Page sometimes hangs and I have to close the tab out.
## Steps to Reproduce
1. Create a Payload app with `npx create-payload-app`.
2. Create these files:
Categories.js
```js
import {CollectionConfig} from 'payload/types';
import {MediaType} from './views/Media';
import formatSlug from '../utilities/formatSlug';

export const Categories = {
	slug: 'categories',
	admin: {
		useAsTitle: 'category',
	},
	access: {
		read: boolean => true, // Everyone can read Pages
	},
	fields: [
		{
			name: 'category',
			label: 'Category Name',
			type: 'text',
			required: true,
		},
		{
			name: 'description',
			label: 'Category Description',
			type: 'richText',
			required: true,
		}
	],
};

export default Categories;
```

Tags.js
```js
import {CollectionConfig} from 'payload/types';
import {MediaType} from './views/Media';
import formatSlug from '../utilities/formatSlug';


export const Categories = {
	slug: 'tags',
	admin: {
		useAsTitle: 'tag',
	},
	access: {
		read: boolean => true, // Everyone can read Pages
	},
	fields: [
		{
			name: 'tag',
			label: 'Tag Name',
			type: 'text',
			required: true,
		},
		{
			name: 'description',
			label: 'Tag Description',
			type: 'richText',
			required: true,
		}
	],
};

export default Categories;
```

Opportunities.js
```js
import {CollectionConfig} from 'payload/types';
import {MediaType} from './views/Media';
import formatSlug from '../utilities/formatSlug';


export const Opportunity = {
	slug: 'opportunities',
	admin: {
		useAsTitle: 'opportunity',
	},
	access: {
		read: boolean => true, // Everyone can read Pages
	},
	fields: [
		{
			name: 'opportunity',
			label: 'Opportunity Name',
			type: 'text',
			required: true,
		},
		{
			name: 'category',
			label: 'Opportunity Category',
			type: 'relationship',
			relationTo: 'categories',
		},
		{
			name: 'category',
			label: 'Opportunity Tags',
			type: 'relationship',
			relationTo: 'tags',
			hasMany: true,
		},
		{
			name: 'description',
			label: 'Opportunity Description',
			type: 'richText',
			required: true,
		},
		{
			name: 'startDate',
			label: 'Start Date',
			type: 'date',
			required: false,
			defaultValue: new Date().toISOString(),
			admin: {
				date: {
					pickerAppearance: 'dateOnly',
				}
			}
		},
		{
			name: 'endDate',
			label: 'End Date',
			type: 'date',
			required: false,
			defaultValue: new Date().toISOString(),
			admin: {
				date: {
					pickerAppearance: 'dateOnly',
				}
			}
		},
	],
};

export default Opportunity;
```
3. Add these collections to the payload.config.js file
4. Run the app
5. Go to the admin panel, and try to create an opportunity. When you select a tag or category, the website may hang the renderer.

## Detailed Description

* Browser: 103.0.1264.77
* OS: Windows 11 Home, 22H2
* Node version: 16.11.0

**Comment by DanRibbens** [comment]
Thanks for reporting this. I was able to reproduce it and we're looking into the cause.

![image](https://user-images.githubusercontent.com/6434612/182657900-a0eafabe-744a-49d4-afb4-22b47f4808ae.png)

**Comment by jmikrut** [comment]
Hey @thunder-red-star — this looks to be caused by the fact that you have two fields with the same name, on the same level. Both of your fields are called `category` on your Opportunity collection. They have different labels, but the same exact name. This is impossible, because the database will save only one of these values, and the admin UI will create an infinite loop because one field is updating, causing the other field to re-render, causing the other field to re-render, etc.

We can add some sanitization to our configs to prevent against this but you will need to rename one of your fields (or both) to make them more explicit. 

Does this make sense?
