### ISSUE TITLE
Adding new block popup with large imageURL goes through the header

### ISSUE THREAD

**Issue by matthijs166** [payloadcms/payload#878]
# Bug Report

I use Payload for a big project at the moment and there is one annoying thing happening every time I make a new page and want to add a new block I can't use the popup correctly

## Expected Behavior

That the popup will go downwards or will overlap the header

## Current Behavior

The pop-up goes upward instead of downwards and the header is overlapping the popup
![2022-08-03 12_57_34-Editing - Page - Payload](https://user-images.githubusercontent.com/31346561/182592561-8002e989-20e6-42ac-9f4f-951f89a11352.png)

## Steps to Reproduce
1. Create blocks with large image URLs
2. Create a new collection
3. Try adding the block

## Detailed Description

After resizing the window the popup will go downward and is usable

**Comment by matthijs166** [comment]
I got the same issue with duplicating blocks

![2022-08-03 16_12_24-Creating - Page - Payload](https://user-images.githubusercontent.com/31346561/182630103-8fe93f4f-f7d0-4282-b267-7522a16806ff.png)
s

**Comment by jmikrut** [comment]
Hey @matthijs166 — great catch. There was a little bug with our `Popup` component.

Fixed now, will be released shortly!

**Comment by DanRibbens** [comment]
This was fixed in v1.0.13 yesterday.
