### ISSUE TITLE
Creating migrations not working in latest v2

### ISSUE THREAD

**Issue by max-degterev** [payloadcms/payload#8782]
### Describe the Bug

Last version of v2 is incompatible with previous migrations:

```
 ~/Projects/bldry-db │ master !1  npm run payload migrate:create noTextIndex                                                                                                

> bldry-db@1.0.0 payload
> cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload migrate:create noTextIndex

[15:30:12] INFO (payload): Starting Payload...

/Volumes/Data/Projects/bldry-db/node_modules/payload/src/bin/migrate.ts:88
        throw new Error(`Error creating migration: ${err.message}`)
              ^
Error: Error creating migration: [
  {
    "received": "5",
    "code": "invalid_literal",
    "expected": "7",
    "path": [
      "version"
    ],
    "message": "Invalid literal value, expected \"7\""
  },
  {
    "received": "pg",
    "code": "invalid_literal",
    "expected": "postgresql",
    "path": [
      "dialect"
    ],
    "message": "Invalid literal value, expected \"postgresql\""
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "admins",
      "indexes",
      "admins_created_at_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "admins",
      "indexes",
      "admins_email_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "users_parameters",
      "indexes",
      "users_parameters_order_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [
      "tables",
      "users_parameters",
      "indexes",
      "users_parameters_parent_id_idx",
      "columns",
      0
    ],
    "message": "Expected object, received string"
  },
// ... lots of similar errors
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "object",
    "path": [
      "enums",
      "enum_email_format",
      "values"
    ],
    "message": "Expected array, received object"
  }
]
    at migrate (/Volumes/Data/Projects/bldry-db/node_modules/payload/src/bin/migrate.ts:88:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### To Reproduce

I am running agains a system with existing migrations. Initially the change in enum behavior has forced me to re-create my dev DB to start the project. Now I am unable to create migrations (same enum issue again). Any idea how to patch the old schema so the new system is able to diff it correctly?

### Payload Version

current v2

**Comment by r1tsuu** [comment]
It may be possible for you to clean up all your migrations and create a new one from the latest version

**Comment by r1tsuu** [comment]
Another note, if you have drizzle-orm / kit installed in your project you need to bump them, may be not related to this

**Comment by max-degterev** [comment]
> It may be possible for you to clean up all your migrations and create a new one from the latest version

Yes but I would need to seed some sort of pre-migration migration to not have it run. Not great.

**Comment by r1tsuu** [comment]
> > It may be possible for you to clean up all your migrations and create a new one from the latest version
> 
> Yes but I would need to seed some sort of pre-migration migration to not have it run. Since it will create a new initial migration. Not great. 

You could "simulate" that it's ran by adding it to the payload_migratoons table manually, not ideal but may work
@DanRibbens did we encounter issues like this on beta?

**Comment by max-degterev** [comment]
Yeah that was my initial reaction too but I thought to ask here for a better fix perhaps

**Comment by DanRibbens** [comment]
I just spoke with @r1tsuu 
We missed the piece of code that migrates drizzle snapshot schemas. That will handle the versioning error you are seeing here.

We're going to include a test for this and release the updated patch later today.

Thanks for reporting this @max-degterev!

**Comment by max-degterev** [comment]
Awesome, lmk when it's live I will test for you 👍

**Comment by max-degterev** [comment]
Works, thanks!

**Comment by r1tsuu** [comment]
Nice, thank you! My bad that I missed this important thing.
