### ISSUE TITLE
apiKey field not fully customizable

### ISSUE THREAD

**Issue by mikecebul** [payloadcms/payload#8785]
### Describe the Bug

Paul had an improvement with [#7591](https://github.com/payloadcms/payload/pull/7591), but I am unable to apply read access control on `enableAPIKey` and `apiKey`. I can prevent use if I set
```javascript
{
      name: 'enableAPIKey',
      type: 'checkbox',
      access: {
        update: () => false,
      },
    },
    {
      name: 'apiKey',
      type: 'text',
      access: {
        update: () => false,
      },
    },
```
but the fields are still there and it looks like you can save, but it just immediately reverts. I would prefer to completely hide from all users accept my superAdmin.

### Link to the code that reproduces this issue

n/a

### Reproduction Steps

1. add 
```javascript
  auth: {
    useAPIKey: true,
  },
```
2. attempt to hide fields with access control.

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.7.0
Relevant Packages:
  payload: 3.0.0-beta.116
  next: 15.0.0-canary.173
  @payloadcms/email-resend: 3.0.0-beta.116
  @payloadcms/graphql: 3.0.0-beta.116
  @payloadcms/live-preview: 3.0.0-beta.116
  @payloadcms/live-preview-react: 3.0.0-beta.116
  @payloadcms/next/utilities: 3.0.0-beta.116
  @payloadcms/plugin-cloud-storage: 3.0.0-beta.116
  @payloadcms/plugin-form-builder: 3.0.0-beta.116
  @payloadcms/plugin-redirects: 3.0.0-beta.116
  @payloadcms/plugin-seo: 3.0.0-beta.116
  @payloadcms/plugin-stripe: 3.0.0-beta.116
  @payloadcms/richtext-lexical: 3.0.0-beta.116
  @payloadcms/storage-s3: 3.0.0-beta.116
  @payloadcms/translations: 3.0.0-beta.116
  @payloadcms/ui/shared: 3.0.0-beta.116
  react: 19.0.0-rc-3edc000d-20240926
  react-dom: 19.0.0-rc-3edc000d-20240926
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64
  Available memory (MB): 8192
  Available CPU cores: 8

**Comment by kendelljoseph** [comment]
PR is open that addresses this.  You can now use the `read` permission or the `update` permission and expect admin visuals to match.
