### ISSUE TITLE
Cannot update locale in upload field inside blocks

### ISSUE THREAD

**Issue by itsaalexk** [payloadcms/payload#8827]
### Describe the Bug

Issue: Localized Media in Blocks Fallbacks to Default Locale

Description:

When using localized content within a page collection that contains block fields, there is an issue with uploading images to a media collection in non-default locales. Specifically, within blocks (e.g., a CTA block that contains an Upload component for images), the image set for any locale other than the default one falls back to the image from the default locale (Spanish in this case).

Expected Behavior:

When setting an image in a non-default locale (e.g., English), the image for that specific locale should render, without falling back to the default locale’s image.

Actual Behavior:

	1.	Setting an image in a non-default locale displays a success toast (Image updated correctly).
	2.	Debugging the beforeChange or afterChange hooks shows that the correct image ID is stored for the localized field.
	3.	However, the frontend renders the image from the default locale (Spanish), even though the image ID for the current locale is correct.
	4.	The issue only occurs within blocks. Outside of blocks, localized media works as expected.
	
     This issue seems to be only inside blocks field , because otherwise it works perfectly.

Environment:

	•	Localization: Enabled for blocks (localized: true)
	•	Default Locale: Spanish
	•	Affected Locale(s): All non-default locales
	•	The issue occurs only within block fields (e.g., CTA block with Upload).

Let me know if you need further details or edits!

### To Reproduce

Steps to Reproduce:

	1.	Enable localized: true for the block field in a page collection.
	2.	Create a block (e.g., CTA block) that includes an Upload component tied to a media collection.
	3.	Upload an image for the default locale (Spanish) and verify that it renders correctly.
	4.	Switch to another locale (e.g., English), upload a different image, and check the frontend rendering.
	5.	Observe that the image from the default locale (Spanish) is displayed, even though the correct image ID is set for the non-default locale.

### Payload Version

^2.19.3

### Adapters and Plugins

@payloadcms/plugin-cloud-storage

https://github.com/user-attachments/assets/c4eced92-07b9-4d1d-bb80-a53a22ea6fd4

**Comment by r1tsuu** [comment]
I see you are using Postgres and on outdated version 2.19.3. We ported _a lot_ of Postgres fixes from 3.0 to 2.0 here https://github.com/payloadcms/payload/pull/8468 which includes fixes for this. Try the latest version https://github.com/payloadcms/payload/releases/tag/v2.30.3

**Comment by itsaalexk** [comment]
Could you please clarify? We updated to the latest version of payload cms and still have the same problem. What postgres version should be used? We use a postgres adapter for payloadCMS

**Comment by itsaalexk** [comment]
Since we use the caret version of PayloadCMS , it should work with all the minor versions

**Comment by r1tsuu** [comment]
`@payloadcms/db-postgres` specifically should be on 0.8.9

**Comment by r1tsuu** [comment]
>Since we use the caret version of PayloadCMS , it should work with all the minor versions

I'd recommend to pin it explicitly, it's not necessary that your actual version is latest from the caret.

**Comment by itsaalexk** [comment]
Yes, that solved our problem. Thanks!
