### ISSUE TITLE
Title not rendered in Collection ListView when join is added.

### ISSUE THREAD

**Issue by energee** [payloadcms/payload#8836]
### Describe the Bug

When a join is added to a collection, Cells in the ListView where this is displayed do not render properly:
![Image](https://github.com/user-attachments/assets/01a9fc39-835c-4e8c-9858-d5bd2cbddf0c)

**Comment out join on collection containing "test"**
![Image](https://github.com/user-attachments/assets/cee73d95-afbc-4145-bc95-961569b447bd)

### Link to the code that reproduces this issue

https://github.com/energee/payload/pull/1/files

### Reproduction Steps

Added collectionsConfig for quick reproduction:

**Collection A**
```
import type { CollectionConfig } from 'payload'

export const RelationshipDocs: CollectionConfig = {
  slug: 'relationship-docs',
  admin: {
    useAsTitle: 'title',
    description: 'A collection with a relationship to a collection with a join field',
  },
  fields: [
    {
      name: 'title',
      type: 'text',
    },
    {
      name: 'relationship',
      type: 'relationship',
      relationTo: 'join-docs',
      hasMany: true,
      admin: {
        position: 'sidebar',
      },
    },
  ],
}
```

**Collection** B
```
import type { CollectionConfig } from 'payload'

export const JoinDocs: CollectionConfig = {
  slug: 'join-docs',
  admin: {
    useAsTitle: 'title',
    description: 'A collection with a join to relating collection',
  },
  fields: [
    {
      name: 'title',
      type: 'text',
    },
    {
      name: 'relationship',
      type: 'join',
      collection: 'relationship-docs',
      on: 'relationship',
    },
  ],
}
```

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

Binaries:
  Node: 22.9.0
  npm: 10.8.3
  Yarn: 1.22.22
  pnpm: 9.10.0
Relevant Packages:
  payload: 3.0.0-beta.117
  next: 15.0.0
  @payloadcms/db-mongodb: 3.0.0-beta.117
  @payloadcms/graphql: 3.0.0-beta.117
  @payloadcms/next/utilities: 3.0.0-beta.117
  @payloadcms/plugin-cloud-storage: 3.0.0-beta.117
  @payloadcms/richtext-lexical: 3.0.0-beta.117
  @payloadcms/storage-vercel-blob: 3.0.0-beta.117
  @payloadcms/translations: 3.0.0-beta.117
  @payloadcms/ui/shared: 3.0.0-beta.117
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021

**Comment by JessChowdhury** [comment]
Thank you for reporting this! It opened a can of worms - so I have created 2 sub-issues ([here](https://github.com/payloadcms/payload/issues/8900) and [here](https://github.com/payloadcms/payload/issues/8901)), this will be resolved when we get both of those fixed and merged in.
