### ISSUE TITLE
Reduce merge conflicts for importMap

### ISSUE THREAD

**Issue by DanRibbens** [payloadcms/payload#8841]
### Describe the Bug

The generated import map creates index numbers to uniquely name all imports. This strategy results can result in nasty merge conflicts that need to be resolves as the importMap file should be checked into source control in general.

### Link to the code that reproduces this issue

npx create-payload-app

### Reproduction Steps

![Image](https://github.com/user-attachments/assets/e00b76ea-2064-4af9-aeb3-a20a045d69a5)

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

payload >v3.0.0-beta.79

### Proposed Solution

1. Sort the imports by name
2. Add a hash to the end of the import name using the file path. For example:
`import { default as default_19 } from 'src/fields/Selector.tsx'` -> `import { default as default_48A1B9E } from 'src/fields/Selector'.

**Comment by AlessioGr** [comment]
+1 for the proposed solution
