### ISSUE TITLE
@payloadcms/plugin-search: searchOverrides slug not working

### ISSUE THREAD

**Issue by louisnt** [payloadcms/payload#8842]
### Describe the Bug

Hello,

I am using the latest version of payload:

```
"@payloadcms/db-mongodb": "3.0.0-beta.117",
"@payloadcms/next": "3.0.0-beta.117",
"@payloadcms/plugin-cloud": "3.0.0-beta.117",
"@payloadcms/plugin-cloud-storage": "3.0.0-beta.117",
"@payloadcms/plugin-search": "3.0.0-beta.117",
"@payloadcms/richtext-lexical": "3.0.0-beta.117",
"payload": "3.0.0-beta.117",
```

And trying to customize the slug of the search:
```
 searchPlugin({
      searchOverrides: {
        labels: {
          singular: 'Location Search',
          plural: 'Locations Search',
        },
        slug: 'locations',
      },
   ...
```

But the slug 'search' is hard coded in the plugin (syncWithSearch):

```
 if (operation === 'create') {
            if (doSync) {
                await payload.create({
                    collection: 'search',
                    data: {
                        ...dataToSave,
                        priority: defaultPriority
                    },
                    req
                });
            }
        }
```

How can we solve this, please?

Thank you

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload/blob/main/packages/plugin-search/src/Search/hooks/syncWithSearch.ts

### Reproduction Steps

Check the code source of the plugin: 
https://github.com/payloadcms/payload/blob/main/packages/plugin-search/src/Search/hooks/syncWithSearch.ts

### Which area(s) are affected? (Select all that apply)

plugin: search

### Environment Info

Binaries:
  Node: 22.9.0
  npm: 10.8.3
  Yarn: 1.22.21
  pnpm: 9.8.0
Relevant Packages:
  payload: 3.0.0-beta.117
  next: 15.0.1
  @payloadcms/db-mongodb: 3.0.0-beta.117
  @payloadcms/email-nodemailer: 3.0.0-beta.117
  @payloadcms/graphql: 3.0.0-beta.117
  @payloadcms/next/utilities: 3.0.0-beta.117
  @payloadcms/plugin-cloud: 3.0.0-beta.117
  @payloadcms/plugin-cloud-storage: 3.0.0-beta.117
  @payloadcms/plugin-search: 3.0.0-beta.117
  @payloadcms/richtext-lexical: 3.0.0-beta.117
  @payloadcms/translations: 3.0.0-beta.117
  @payloadcms/ui/shared: 3.0.0-beta.117
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:13 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8112
  Available memory (MB): 24576
  Available CPU cores: 8

**Comment by paulpopus** [comment]
Fixing in https://github.com/payloadcms/payload/pull/8847

Thanks for your report!
