### ISSUE TITLE
Unable to edit existing documents with custom ids as of beta 114

### ISSUE THREAD

**Issue by jeffreylouden** [payloadcms/payload#8848]
### Describe the Bug

As of beta 114, I'm no longer able to edit existing documents with a string IDs in the admin. Almost all of my project's collections use custom ids generated with nanoid -- the simple logic of which is included in the linked repository --  and I am able to successfully create new records with custom IDs, but all individual document pages in the admin present with a title of `NaN` and seems to trigger the create new collection route. 

![Image](https://github.com/user-attachments/assets/f96f3494-a43e-4ab7-8230-ea63e5076188)

Everything seems to work as expected in beta 113 or earlier (at least back until 80+).

### Link to the code that reproduces this issue

https://github.com/jeffreylouden/payload-uneditable-collections

### Reproduction Steps

- Start the associated repository with a fresh database
- Log into the admin panel and create a new item in the Test collection
- The page should switch to editing the document, but display no information and display a title of 'NaN'

### Which area(s) are affected? (Select all that apply)

db-postgres

### Environment Info

payload: 3.0.0-beta.117
next: 15.0.0
@payloadcms/db-postgres: 3.0.0-beta.117
@payloadcms/email-nodemailer: 3.0.0-beta.117
@payloadcms/graphql: 3.0.0-beta.117
@payloadcms/next/utilities: 3.0.0-beta.117
@payloadcms/plugin-cloud: 3.0.0-beta.117
@payloadcms/richtext-lexical: 3.0.0-beta.117
@payloadcms/translations: 3.0.0-beta.117
@payloadcms/ui/shared: 3.0.0-beta.117
react: 19.0.0-rc-65a56d0e-20241020
react-dom: 19.0.0-rc-65a56d0e-20241020

**Comment by rilrom** [comment]
I believe you need to set idType to 'uuid' in postgresAdapter() to resolve this.

**Comment by d717an** [comment]
we are also encountering this with SQLite which has no `idtype` option

**Comment by d717an** [comment]
We're able to work around this issue by hashing our string id into a positive integer. Docs should be updated though if it's indeed not intended to be able to use text for ids.

**Comment by rilrom** [comment]
> we are also encountering this with SQLite which has no `idtype` option

Looking in the SQLite package code it does have an idType, the docs needs to be updated to reflect this.

**Comment by jeffreylouden** [comment]
Thanks! setting `idType` in the `postgresAdapter` fixed things for me. I guess I missed this setting earlier in my upgrades and it was more strict in beta 114 and broke things for me. Closing this as fixed.
