### ISSUE TITLE
Fix for form-builder bug not yet published to npm

### ISSUE THREAD

**Issue by didierrothuizen** [payloadcms/payload#8849]
### Describe the Bug

About half a year ago, there was a fix for the form builder that correctly extended all hook overrides that are applied to the formSubmissions collection. See [this commit](https://github.com/payloadcms/payload/commit/b735d6aa169acca8cb638859d2c8ba43e315f02c)
Unfortunately, this fix has never been published to npm.

Can someone release and publish a version 1.2.3? (in [package.json](https://github.com/payloadcms/payload/blob/main/packages/plugin-form-builder/package.json))

### To Reproduce

Install latest version of the form builder plugin
Inspect files in the `node_modules` folder
note that in `node_modules/@payloadcms/plugin-form-builder/dist/collections/FormSubmissions/index.js` the file mismatches with how the source code is.

The code in the installed index.js:
```
        hooks: {
            beforeChange: [
                (data)=>(0, _createCharge.default)(data, formConfig),
                (data)=>(0, _sendEmail.default)(data, formConfig),
                ...formConfig?.formSubmissionOverrides?.hooks?.beforeChange || []
            ],
            ...formConfig?.formSubmissionOverrides?.hooks || {}
        }
```

The source code:
```
    hooks: {
      ...(formConfig?.formSubmissionOverrides?.hooks || {}),
      beforeChange: [
        (data) => createCharge(data, formConfig),
        (data) => sendEmail(data, formConfig),
        ...(formConfig?.formSubmissionOverrides?.hooks?.beforeChange || []),
      ],
    },
```

### Payload Version

2.30.3

### Adapters and Plugins

form-builder

**Comment by DanRibbens** [comment]
Thanks for bringing this to our attention! We'll make sure it is published.

**Comment by didierrothuizen** [comment]
@denolfe @DanRibbens What is the expected date that a new release will be published?

**Comment by didierrothuizen** [comment]
@denolfe @DanRibbens This issue is blocking a major release for me. Can you please give an estimate of how long this will take to be resolved?
Alternatively, could you propose a solution such that I can work with the fix in my project without publishing a release?

**Comment by denolfe** [comment]
Hey @didierrothuizen , thank you for your patience on this. [v1.2.3](https://www.npmjs.com/package/@payloadcms/plugin-form-builder/v/1.2.3) of plugin-form-builder was just published. You can also use the `payload-2` tag.
