### ISSUE TITLE
Relationship Field > Link to Globals

### ISSUE THREAD

**Issue by robinscholz** [payloadcms/payload#8854]
This is currently not supported, but seems like a bit of an oversight, since Globals appear to be what should be used for one-off data (i.e. a contact page with specific fields).

If for example you’d like to have some sort of a menu builder, it’d be crucial to pull in globals as an option in a relationship field.

There is already a related discussion here, though it seems stagnant: https://github.com/payloadcms/payload/discussions/2100.

Not sure how complicated this would be, but would be great if this could land with Payload V3.

**Comment by robinscholz** [comment]
https://github.com/payloadcms/payload/discussions/4650

Another related discusssion pointing out alot of the caveats that come with bending a “page” collection to include different sets of data.

**Comment by PatrikKozak** [comment]
Hey @robinscholz - had a discussion about this with the team and while we see the potential benefits, we’re not currently planning to add support for referencing `globals` in relationship fields in the immediate roadmap. 

The [discussion](https://github.com/payloadcms/payload/discussions/4650) you linked does dive into a few workarounds, which may help in some cases.

However, we completely understand the desire for flexibility and how this feature can extend that. So, while it’s not at the top of our priority list at the moment, we’d definitely welcome community PRs if this is something you’d like to explore further. And though there are no concrete plans for this at the moment, we're open to revisiting this down the line!

Thanks again for the feedback!
