### ISSUE TITLE
bulkUpload omits files with valid catchall mimetypes

### ISSUE THREAD

**Issue by akhrarovsaid** [payloadcms/payload#8867]
### Describe the Bug

The `bulkUpload` drawer doesn't accept files from valid catchall mimetypes such as 'image/*' as the current `onDrop` function doesn't account for it.

### Link to the code that reproduces this issue

npx create-payload-app@beta -t website

### Reproduction Steps

- Set `mimetypes` property in upload-enabled collection to a catchall such as `image/*`
- Navigate to collection and open `bulkUpload` drawer by clicking the pill labeled "Bulk Upload"
- Drag and drop a/many file(s) with a valid mimetype (such as a png)
- Observe that the file gets omitted from bulk upload

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

Payload: beta.118
Next: 15
Node: v20.10.0

**Comment by jmikrut** [comment]
This is now resolved!
