### ISSUE TITLE
"Module not found" Issue when using Form Builder Plugin with new v3 beta

### ISSUE THREAD

**Issue by Matx00** [payloadcms/payload#8885]
### Describe the Bug

After following the guide to set up a form with payload form builder plugin I get this error

https://nextjs.org/docs/messages/module-not-found
 ⨯ ./node_modules/@payloadcms/plugin-form-builder/dist/collections/Forms/DynamicFieldSelector.js
Module not found: Package path ./components/forms is not exported from package /payload-3.0-demo/node_modules/payload (see exports field in /home/mattia/payload-3.0-demo/node_modules/payload/package.json)

I tried looking at these guidelines without success 

- https://payloadcms.com/blog/create-custom-forms-with-the-official-form-builder-plugin
- https://www.youtube.com/watch?v=Fm4YaG__EHg

Probably I am not so experienced of Payload and there I am not fully aware of an already existing solution! 

### Link to the code that reproduces this issue

https://github.com/Matx00/payload-3.0-demo

### Reproduction Steps

1. Cloned last version 3.beta
2. installed plugin form builder (v.1.2.2)
3. follow guide https://payloadcms.com/blog/create-custom-forms-with-the-official-form-builder-plugin
4. launch dev (yarn dev)

### Which area(s) are affected? (Select all that apply)

plugin: form-builder

### Environment Info

Node: 20.12.0
npm: 10.5.0
Yarn: 1.22.22
pnpm: 9.1.1
Relevant Packages:
  payload: 3.0.0-beta.116
  next: 15.0.0-canary.104
  @payloadcms/db-mongodb: 3.0.0-beta.116
  @payloadcms/db-postgres: 3.0.0-beta.116
  @payloadcms/email-nodemailer: 3.0.0-beta.29
  @payloadcms/graphql: 3.0.0-beta.116
  @payloadcms/next/utilities: 3.0.0-beta.116
  @payloadcms/plugin-form-builder: 1.2.2
  @payloadcms/richtext-lexical: 3.0.0-beta.116
  @payloadcms/richtext-slate: 3.0.0-beta.116
  @payloadcms/translations: 3.0.0-beta.116
  @payloadcms/ui/shared: 3.0.0-beta.116
  react: 19.0.0-rc-06d0b89e-20240801
  react-dom: 19.0.0-rc-06d0b89e-20240801
Operating System:
  Platform: linux
  Arch: x64
  Version: #216-Ubuntu SMP Thu Aug 29 13:26:53 UTC 2024
  Available memory (MB): 7946
  Available CPU cores: 4

**Comment by jmikrut** [comment]
Hey @Matx00 this was caused because you had all sorts of version conflicts in your `package.json` file.

Here is a working copy:

```json
{
  "name": "payload-3.0-demo",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "cross-env NODE_OPTIONS=\"${NODE_OPTIONS} --no-deprecation\" next dev",
    "devturbo": "pnpm dev --turbo",
    "devsafe": "rm -rf .next && pnpm dev",
    "build": "cross-env NODE_OPTIONS=--no-deprecation next build",
    "start": "cross-env NODE_OPTIONS=--no-deprecation next start",
    "lint": "cross-env NODE_OPTIONS=--no-deprecation next lint",
    "ci": "payload migrate && pnpm build",
    "payload": "payload",
    "generate:types": "payload generate:types",
    "generate:schema": "payload-graphql generate:schema",
    "standalone-script": "payload run ./src/scripts/standalone-script.ts",
    "generate:importmap": "payload generate:importmap"
  },
  "engines": {
    "node": "^18.20.2 || >=20.9.0"
  },
  "dependencies": {
    "@payloadcms/db-mongodb": "3.0.0-beta.116",
    "@payloadcms/db-postgres": "3.0.0-beta.116",
    "@payloadcms/email-nodemailer": "^3.0.0-beta.116",
    "@payloadcms/next": "3.0.0-beta.116",
    "@payloadcms/plugin-form-builder": "^3.0.0-beta.116",
    "@payloadcms/richtext-lexical": "3.0.0-beta.116",
    "@payloadcms/richtext-slate": "3.0.0-beta.116",
    "@payloadcms/ui": "3.0.0-beta.116",
    "babel-plugin-react-compiler": "0.0.0-experimental-48eb8f4-20240822",
    "cross-env": "^7.0.3",
    "graphql": "^16.8.2",
    "next": "15.0.0-canary.104",
    "payload": "3.0.0-beta.116",
    "react": "19.0.0-rc-06d0b89e-20240801",
    "react-dom": "19.0.0-rc-06d0b89e-20240801",
    "sharp": "0.32.6"
  },
  "devDependencies": {
    "@payloadcms/graphql": "3.0.0-beta.116",
    "@types/node": "^20.14.9",
    "@types/react": "npm:types-react@19.0.0-rc.0",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.0",
    "eslint": "^8.57.0",
    "eslint-config-next": "15.0.0-canary.104",
    "typescript": "5.5.4"
  },
  "pnpm": {
    "overrides": {
      "@types/react": "npm:types-react@19.0.0-rc.0",
      "@types/react-dom": "npm:types-react-dom@19.0.0-rc.0"
    }
  },
  "overrides": {
    "@types/react": "npm:types-react@19.0.0-rc.0",
    "@types/react-dom": "npm:types-react-dom@19.0.0-rc.0"
  }
}

```

I just updated a few of the versions to `3.0.0-beta.116`. All of your Payload-provided packages should match versions.

In addition, you're importing the form builder plugin incorrectly. I changed that too:

```
import { formBuilderPlugin } from '@payloadcms/plugin-form-builder'
```

You'll get further after fixing these few things!
