### ISSUE TITLE
Payload 3 favicon

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#8887]
# Documentation Issue

https://payloadcms.com/docs/beta/admin/metadata#icons

Typescript expects `url`
Docs suggest `href`

```diff
{
  // ...
  admin: {
    meta: {
      title: 'My Admin Panel',
      description: 'The best admin panel in the world',
      icons: [
        {
          rel: 'icon',
          type: 'image/png',
-          href: '/favicon.png',
+          url: '/favicon.png',
        },
      ],
    },
  },
}
```
## Additional Details

Couldn't find a way to set the favicon, so maybe it's not docs but code issue after all.

**Comment by akhrarovsaid** [comment]
Hey @thgh,

Yeah, this seems like a docs issue. You can see the types for `IconConfig` directly from the source [here](https://github.com/payloadcms/payload/blob/beta/packages/payload/src/config/types.ts#L179).

**Comment by paulpopus** [comment]
The above has been merged, thanks both!
