### ISSUE TITLE
Join field throws 'Error: $lookup with 'pipeline' may not specify 'localField' or 'foreignField''

### ISSUE THREAD

**Issue by JessChowdhury** [payloadcms/payload#8900]
### Describe the Bug

Join field throws the following error, only related to `mongodb`.

![Image](https://github.com/user-attachments/assets/533bba3f-1704-46d5-b347-479418749d78)

The code causing the error is in `packages/db-mongodb/src/utilities/buildJoinAggregation.ts`

From what I have read, this could be caused by version incompatibility. Read [here](https://www.mongodb.com/community/forums/t/lookup-with-pipeline-may-not-specify-localfield-or-foreignfield/201793).

### Link to the code that reproduces this issue

pnpm dev joins

### Reproduction Steps

- setup with `mongodb` 
- run `joins` test suite
- open `http://localhost:3000/admin` in browser
- see error immediately

### Which area(s) are affected? (Select all that apply)

db-mongodb

### Environment Info

Payload: beta@latest
Node.js: v20.9.0
Next.js: v15.0.0

**Comment by DanRibbens** [comment]
I'm not seeing this error @JessChowdhury. Are you still getting this error? I would like you to show me if so.

**Comment by JessChowdhury** [comment]
This error was caused by incompatibility with MongoDB version `v4.4.0`.

For anyone experiencing this in the future, check your version against the published MongoDB Software Lifecycle schedule found [here](https://www.mongodb.com/legal/support-policy/lifecycles). Payload does not support versions which have passed their End Of Life Date. 

If your version is outdated, follow instructions to upgrade to the latest stable MongoDB version. 

If your version is current and the issue persists, drop us a note here or open a new issue. Thanks!
