### ISSUE TITLE
form-builder-plugin, payment field, static value field hidden

### ISSUE THREAD

**Issue by mikecebul** [payloadcms/payload#8903]
### Describe the Bug

When using the form-builder-plugin payment field you can add price conditions. When creating a price condition you should be able to enter a static value. A input field should be dynamically added but it does not, so there is no way to add a static value to price conditions. 

### Link to the code that reproduces this issue

https://github.com/mikecebul/payload/tree/form-builder-plugin-issues

### Reproduction Steps

You don't need to use my reproduction. 

1. `pnpm dev form-builder-plugin`
2. create a form
3. add a payment field
4. attempt to add a static value

### Which area(s) are affected? (Select all that apply)

plugin: form-builder

### Environment Info

Binaries:
  Node: 20.14.0
  npm: 10.7.0
  Yarn: 1.22.22
  pnpm: 9.7.0
Relevant Packages:
  payload: 3.0.0-beta.118
  next: 15.0.0
  @payloadcms/db-mongodb: 3.0.0-beta.118
  @payloadcms/email-resend: 3.0.0-beta.118
  @payloadcms/graphql: 3.0.0-beta.118
  @payloadcms/live-preview: 3.0.0-beta.118
  @payloadcms/live-preview-react: 3.0.0-beta.118
  @payloadcms/next/utilities: 3.0.0-beta.118
  @payloadcms/plugin-cloud-storage: 3.0.0-beta.118
  @payloadcms/plugin-form-builder: 3.0.0-beta.118
  @payloadcms/plugin-redirects: 3.0.0-beta.118
  @payloadcms/plugin-seo: 3.0.0-beta.118
  @payloadcms/plugin-stripe: 3.0.0-beta.118
  @payloadcms/richtext-lexical: 3.0.0-beta.118
  @payloadcms/storage-s3: 3.0.0-beta.118
  @payloadcms/translations: 3.0.0-beta.118
  @payloadcms/ui/shared: 3.0.0-beta.118
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
  Available memory (MB): 15847
  Available CPU cores: 16

**Comment by jmikrut** [comment]
Thanks for the report - fixed and will be released in the next version!
