### ISSUE TITLE
Creating a new project using create-payload-app@latest causes beta packages to be installed

### ISSUE THREAD

**Issue by akhrarovsaid** [payloadcms/payload#8965]
### Link to reproduction

npx create-payload-app@latest

### Describe the Bug

Using the `npx create-payload-app@latest` and selecting ~~the website~~ a template causes `beta` packages to be installed as well as the pinned React 19 version and next15. There have been ~~two~~ ~~three~~ many other users report this in Discord as well, likely has something to do with the `beta` branch being set as default.

Sample dependencies directly from package.json:
![Image](https://github.com/user-attachments/assets/0a5832c6-2776-429a-b1bf-c39629489d93)

### To Reproduce

- `npx create-payload-app@latest`
- Select website or blank or ecommerce template
- Observe package.json

### Payload Version

2.30.3

**Comment by WingRa7** [comment]
encountered the same thing

**Comment by michel-jump** [comment]
This is not only happening for the website template. It is happening for the blank template as well.
I haven't tested the other templates.

**Comment by denolfe** [comment]
Should be all set, code changes were made - latest version just needed to be published.

**Comment by michel-jump** [comment]
Just tested it and it works.
Thanks for quickly resolving it!
