### ISSUE TITLE
TextField typedef is missing properties

### ISSUE THREAD

**Issue by JesperWe** [payloadcms/payload#8982]
### Describe the Bug

The 3.0 beta docs show that a Field of type 'text' should have `hasMany`, `minRows` and `maxRows`
These props are missing from the TextField type.

### Link to the code that reproduces this issue

https://gist.github.com/JesperWe/6faf38619967dd77fd7e7b084e18a342

### Reproduction Steps

For example the linked Collection definition causes

```
./collections/Stores.ts:138:7
Type error: Object literal may only specify known properties, and 'hasMany' does not exist in type 'TextField'.

  136 |         sv: 'Upptagningsområde tjänster (Postnr)',
  137 |       },
> 138 |       hasMany: true,
      |       ^
  139 |     },
  140 |     {
  141 |       name: 'serviceZipcodes',
```

But the code runs fine and works with hasMany, so it seems to be only a typedef issue.

### Which area(s) are affected? (Select all that apply)

Not sure

### Environment Info

Binaries:
  Node: 20.11.0
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 9.12.2
Relevant Packages:
  payload: 3.0.0-beta.123
  next: 15.0.1
  @payloadcms/db-mongodb: 3.0.0-beta.123
  @payloadcms/db-postgres: 3.0.0-beta.123
  @payloadcms/graphql: 3.0.0-beta.123
  @payloadcms/next/utilities: 3.0.0-beta.123
  @payloadcms/richtext-lexical: 3.0.0-beta.123
  @payloadcms/richtext-slate: 3.0.0-beta.123
  @payloadcms/translations: 3.0.0-beta.123
  @payloadcms/ui/shared: 3.0.0-beta.123
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Wed Jul 31 20:49:39 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10

**Comment by akhrarovsaid** [comment]
Hey @JesperWe,

I can't actually reproduce the type issue you're describing. I've pasted the parts of your gist where you're defining text fields with `hasMany` and I don't get anything. This is [the type definition](https://github.com/payloadcms/payload/blob/beta/packages/payload/src/fields/config/types.ts#L530-L538) directly from source. My only recommendation would be to maybe try restarting your TS server? (If you're using VSCode you can open the command pallet and type `Restart TS Server` and then select that option from the dropdown).

![Image](https://github.com/user-attachments/assets/de7f19fa-6975-4e39-b7f8-7fd419973b72)

**Comment by JesperWe** [comment]
The error transcript is from the `pnpm build` command so no TS Server involved (I am not using VSCode either)
I'll try to investigate more.

**Comment by akhrarovsaid** [comment]
Hey @JesperWe,

So I just tried again by copy + pasting your collection config and noticed a few things:

Can you try changing
```
import { CollectionConfig } from 'payload/types'
import { User } from 'payload-types'
```
to
```
import type { CollectionConfig, User } from 'payload'
```

And also that your `access: { admin: (...) => {...} }` is using the `data` argument which doesn't actually exist in that function according to the typedefs. See what I mean [here](https://github.com/payloadcms/payload/blob/beta/packages/payload/src/collections/config/types.ts#L360).

**Comment by JesperWe** [comment]
Yes that fixes it. I guess the IDE's automatic import insert played a trick on me here. The other `TextField` type that it imported had almost all the correct props so I was fooled.
Sorry.
