### ISSUE TITLE
Save button not correctly disabled when there's no changes

### ISSUE THREAD

**Issue by shangjieJayZhou** [payloadcms/payload#9000]
### Describe the Bug

When editing a collection, the "Save" button should be disabled upon no changes to this collection.

However, in my case, I have Block **Item Block** inside collection **Courses** and the block has a "type: 'relationship'" to another collection **Items,** when collection **Items** is edited directly inside **Courses**, the "Save" button on the **Courses** editing page becomes clickable and throws error "This relationship field has the following invalid relationships: [object Object] 0" upon clicking. 

![Image](https://github.com/user-attachments/assets/17eff9a8-e33f-42fe-bac2-c389aca0308f)
This bug was introduced after upgrading from beta.103 to beta.104.

### Link to the code that reproduces this issue

https://github.com/shangjieJayZhou/payload3.0-bug-report

### Reproduction Steps

1. run "pnpm i"
2. copy everything in ".env.local.example" into a file ".env"
3. Either tweak the DATABASE_URI in .env to fit your local db, or make sure you have a locally running postgres db on 5432 with database "lms" and schema "payload-content"
4. run "pnpm dev" 
5. (assume your payload is running on 3000) Log in to http://localhost:3000/admin
6. Go to collection **Courses**
7. Click "Create New" and you should be seeing this
![Image](https://github.com/user-attachments/assets/ec8275a9-0b5b-4584-9701-334a94ecf477)

8. Click "Add Content" and add an **Item Block**, and you should be seeing this
![Image](https://github.com/user-attachments/assets/d035706c-d48c-42e8-8cf0-58bbd6f0455c)

9. Click the "+" button on the right to add an item inside this newly created Item Block. Give it any name and price, should look something like this
![Image](https://github.com/user-attachments/assets/6c524d25-d7de-433f-b6c1-022f6651c4ae)

10. Click "Save" to add this item and close this item window, you should be back to the Course page and see this
![Image](https://github.com/user-attachments/assets/163da621-a3da-4326-9885-a9d47ce1d21b)

11. Click "Save" on the top right to save changes to this Course, after clicking "Save" there should be no error and you should see that the "Save" button now turns grey:
![Image](https://github.com/user-attachments/assets/a261f4fb-a284-452b-a6da-00e48f5a4710)

12. Go edit the item you just added by clicking on the edit icon on the item inside the Item Block, then change the name(or the price, doesn't matter) to something different and save, after saving you should see something like this:
![Image](https://github.com/user-attachments/assets/786951b0-18e6-45a7-8c2a-edd4476587d0)

14. Close the item window and you should be back to the course editing page, and you should see that the "Save" button is no longer greyed out and is clickable (while it SHOULD NOT be)
![Image](https://github.com/user-attachments/assets/d3dd467e-1df7-4c08-8496-de64b6f97d81)

15. Click on "Save" and you should see an error, like this
![Image](https://github.com/user-attachments/assets/d491c196-ea3b-4b9a-9a2b-55d46a713041)

### Which area(s) are affected? (Select all that apply)

area: ui, plugin: nested-docs

### Environment Info

Binaries:
  Node: 20.13.1
  npm: 10.5.2
  Yarn: 1.22.22
  pnpm: 9.7.0
Relevant Packages:
  payload: 3.0.0-beta.123
  next: 15.0.0
  @payloadcms/db-mongodb: 3.0.0-beta.123
  @payloadcms/db-postgres: 3.0.0-beta.123
  @payloadcms/graphql: 3.0.0-beta.123
  @payloadcms/next/utilities: 3.0.0-beta.123
  @payloadcms/richtext-lexical: 3.0.0-beta.123
  @payloadcms/richtext-slate: 3.0.0-beta.123
  @payloadcms/translations: 3.0.0-beta.123
  @payloadcms/ui/shared: 3.0.0-beta.123
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112
  Available memory (MB): 16384
  Available CPU cores: 8

**Comment by thgh** [comment]
Encountered the same bug (at least since v117)

1. Open document that has relationship
3. Click the edit icon of the relation
4. Make a change and click save
5. Close the modal
6. The save button lights up, clicking it shows this error:
`This relationship field has the following invalid relationships: [object Object] 0`

It seems that the relation modal passes down the complete object on save instead of just the id
