### ISSUE TITLE
docs: Incorrect Job Queue documentation on how to trigger tasks from within workflows

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#9003]
# Documentation Issue

The docs on authoring workflows in Job Queues is wrong - it uses an earlier syntax with the `runTasks` method but the current syntax (as shown in https://github.com/payloadcms/payload/blob/8970c6b3a6c75d2fd1968a19feee8697777c5bda/test/queues/runners/externalWorkflow.ts#L10) shows that you're supposed to `await tasks.theTaskId` instead.

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/9120
