### ISSUE TITLE
Old data in payload UI

### ISSUE THREAD

**Issue by stofolus** [payloadcms/payload#9012]
### Describe the Bug

The Payload UI will at times show old data which can cause users to make changes to an older version of a document and publish over a newer version.

### Link to the code that reproduces this issue

Website template

### Reproduction Steps

* Create a site from the website template. I used MongoDB 
* Start, create a user and seed the DB
* `npm run build`
* `npm start` (I guess dev:prod would probably have the same effect)
* Open two separate browsers and login.
* Go to the pages collection in both browsers
* Open a page in browser 1 and make a change. Publish and then open it in browser 2.
* If you see the latest data click on "Pages" in the bread crumbs and try again.

This is not an issue that is always reproducable. For some reason the cached versions of both the collection list and collection item page seem to refresh more often in the beginning. I recommend doing the above steps and trying to trigger the issue a few times on both sides and then having a coffee and trying again.

Here is a video of it happning to me and where I show that the fetch requests seem to get the latest data.
In this case Contact 6 was opened on the left screen and changed to 7. Then I made the change from 7 -> 8 on the right browser and then got the issue on the left browser. I was expecting version 8 but got 6. After going back and forth again it resolved itself. This is however not foolproof. It can show the wrong version for multiple times. The data on the collections list can also be stale at times.

https://github.com/user-attachments/assets/2ef584b8-3fac-431f-af3e-a7c2e565e2e3

If you need help with reproducing feel free to let me know on Discord.

IMO this is a huge issue that can cause editors to not trust Payload due to inconsistent data which can result in publishing old data over newer data

### Which area(s) are affected? (Select all that apply)

area: core, Not sure

### Environment Info

Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.0.2
Relevant Packages:
  payload: 3.0.0-beta.123
  next: 15.0.0
  @payloadcms/db-mongodb: 3.0.0-beta.123
  @payloadcms/email-nodemailer: 3.0.0-beta.123
  @payloadcms/graphql: 3.0.0-beta.123
  @payloadcms/live-preview: 3.0.0-beta.123
  @payloadcms/live-preview-react: 3.0.0-beta.123
  @payloadcms/next/utilities: 3.0.0-beta.123
  @payloadcms/payload-cloud: 3.0.0-beta.123
  @payloadcms/plugin-form-builder: 3.0.0-beta.123
  @payloadcms/plugin-nested-docs: 3.0.0-beta.123
  @payloadcms/plugin-redirects: 3.0.0-beta.123
  @payloadcms/plugin-search: 3.0.0-beta.123
  @payloadcms/plugin-seo: 3.0.0-beta.123
  @payloadcms/richtext-lexical: 3.0.0-beta.123
  @payloadcms/translations: 3.0.0-beta.123
  @payloadcms/ui/shared: 3.0.0-beta.123
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Mar 29 23:14:13 UTC 2024
  Available memory (MB): 15970
  Available CPU cores: 12

**Comment by jmikrut** [comment]
Hey @stofolus we're looking into this actively. 

One note - the fetch that you point to in your network panel is just an _additional_ fetch that the admin UI makes to retrieve the published version of the page.

The actual page data that is used for editing is going to come through one of the `?rsc` requests because the actual document data used for editing is fetched on the server in a server component.

I have a sneaking suspicion that this is related to Next.js' Router Cache.  For v15+ of Next.js, they have now disabled automatic router cache, but maybe there is still somewhere that is being cached incorrectly.

If / when you see this again, can you inspect the `?rsc` requests to see if there is stale data from a server component?

**Comment by stofolus** [comment]
Yeah i figured. I just wanted to show that the backend did actually know about the updated data. 

I managed to trigger the issue again and I'm actually missing the rsc request when it occurs which I would assume supports your theory.

I get a pre-fetched versions from the collection list page which I guess it for some reason deems good enough and therefore doesn't fetch the newest one. 

The green arrow is the prefetch and the red one is where I think I should have had a page load

![Image](https://github.com/user-attachments/assets/5122ff70-4a05-424d-96fd-74335ce3dd2d)


This is probably nothing. But I've noticed that I'm getting this message in the logs and It might be (accidentally?) happening when I get the error
`A locale object was not found for the provided string ["enUS"].`

I haven't setup anything with locales. Only a basic website template with as described in the original issue

**Comment by jmikrut** [comment]
Thanks for the info here. This does indeed support my theory.

We are thinking that we need to disable `prefetch` for ALL of our internal Next.js `Link` usage. Going to PR shortly and release a new version. If you can help us test when we release, that would be amazing! I really appreciate your recon here.

**Comment by stofolus** [comment]
Absolutely! And I'll push it to my users tomorrow and have them (unknowingly ^^) test it.
