### ISSUE TITLE
Plugin SEO: Issue with publishing collections by language

### ISSUE THREAD

**Issue by italodr** [payloadcms/payload#9017]
### Describe the Bug

An error occurs the first time you try to publish a single language. However, if you publish all the languages ​​at once and then unpublish them again, it does allow you to publish a single language.

![Image](https://github.com/user-attachments/assets/cad1b7e2-690a-4c49-b60a-441594a4366b)
![Image](https://github.com/user-attachments/assets/9370aadb-9b81-481e-93ea-d00560a3aa0b)

### Link to the code that reproduces this issue

https://github.com/italodr/payload-test/tree/issue-publishing-by-language-seo

### Reproduction Steps

1. Clone the [above repository](https://github.com/italodr/payload-test/tree/issue-publishing-by-language-seo)
2. Update the config file to add your postgres URL. Currently as "postgresql://postgres:password123@127.0.0.1:5430/postgres_db"
3. Run `pnpm install` to install dependencies
4. Run `pnpm dev _community` to start the admin panel
5. Access the admin panel
6. Add new post in all languages and save them as "Draft"
7. Change language to "Deutsch"
8. Click on "Publish in Deutsch"

### Which area(s) are affected? (Select all that apply)

plugin: seo, Not sure

### Environment Info

Payload: 3.0.0-beta.123
Node.js: v20.12.2
Next.js: 15.0.0

**Comment by paulpopus** [comment]
This will be fixed with https://github.com/payloadcms/payload/pull/8719
