### ISSUE TITLE
"min" field not working properly on "number" field type

### ISSUE THREAD

**Issue by EldenChris** [payloadcms/payload#902]
I can set a negative value to a number field even when the min property is set to 0

Here is the field configuration : 

`fields: [
                        {
                            name: 'stock',
                            label: 'Stock',
                            type: 'number',
                            required: true,
                            min:0,
                        },`

**Comment by DanRibbens** [comment]
Oh you are right @EldenChris. 
Thanks to you I found the bug and we'll release a fix soon. It has to do with our validation logic evaluating to false when `min` or `max` is `0`.
We'll get a fix out soon.

**Comment by DanRibbens** [comment]
Fix released in `v1.0.20`!
