### ISSUE TITLE
Deployment not working (cannot do any action on admin)

### ISSUE THREAD

**Issue by Vette1123** [payloadcms/payload#9029]
### Describe the Bug

Deployment not working (cannot do any action on admin view)

### To Reproduce

Deployment not working (cannot do any action on admin view)

### Payload Version

Deployment not working (cannot do any action on admin view)

**Comment by jmikrut** [comment]
Hey Vette, we need more information here to help you. This seems to be a problem with your configuration as well, so we'd suggest going to our [Discord Community Help](https://discord.gg/payload) or [GitHub Discussions ](https://github.com/payloadcms/payload/discussions/categories/q-a) to get help there!
