### ISSUE TITLE
500 Error on Jobs Queue Docs Page

### ISSUE THREAD

**Issue by nathanclevenger** [payloadcms/payload#9062]
# Documentation Issue

I'm seeing a 500 error when visiting the Jobs Queue Docs:  https://payloadcms.com/docs/beta/jobs-queue/overview

## Additional Details

![Image](https://github.com/user-attachments/assets/4663bf6e-01d7-4f6d-8245-491b2b8cdf75)

**Comment by akhrarovsaid** [comment]
Huh that's strange. For now I'll recommend just going to the mdx document in the `/docs` folder of the monorepo if you need access to the documentation here.

[See docs on Job Queues in the monorepo.](https://github.com/payloadcms/payload/blob/beta/docs/jobs-queue/overview.mdx)

**Comment by r1tsuu** [comment]
Should be fixed now
