### ISSUE TITLE
MongoServerError: E11000 duplicate key error has no keyValue item

### ISSUE THREAD

**Issue by EasonSoong** [payloadcms/payload#915]
# Bug Report

## Expected Behavior

When we create a document that has some invalid duplicate fields which should be unique in database, we will see an error on page.
![image](https://user-images.githubusercontent.com/57319837/184059246-ccba1097-5c34-4fde-8dd0-704dc90e0140.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/57319837/184059276-1781c711-9d66-4c23-b6f9-5cb51641acf9.png)

But we see this confusing error in our page now. We cannot conclude which field is wrong from this error messgae.

## Possible Solution

That error occurs because this code assume that error.keyvalue should be exist. But it doesn't exist in our environment. I think the reason could be different database version.

https://github.com/payloadcms/payload/blob/master/src/collections/operations/create.ts#L191

has no keyValue from a aws document db, it's compatible with mongo api
![image](https://user-images.githubusercontent.com/57319837/184059585-80959067-0ef2-4ef6-b479-cff8d913a88e.png)

has keyValue from another mongo-community version
![image](https://user-images.githubusercontent.com/57319837/184059634-e1d2db3e-7a41-4df1-8a46-6d9d8e0fca93.png)

## Steps to Reproduce

1. I think it's hard to reproduce because I cannot tell how to install a aws document db.

**Comment by DanRibbens** [comment]
@EasonSoong Thanks for finding and taking care of this one.

Released in `v1.0.20`!
