### ISSUE TITLE
join gives typerror when there are no elements

### ISSUE THREAD

**Issue by Stefan94V** [payloadcms/payload#9193]
### Describe the Bug

I can't create a new collection in the admin panel with collections that uses a join of a collection that presumably has no elements. 

I have added a simple reproduction, when you go to the admin panel and you want to create a customer the admin panel will crash:

`invalid input syntax for type integer: "NaN"`

I get a similair issue when using Guids as ID

Am I maybe using joins wrong? 

### Link to the code that reproduces this issue

https://github.com/Stefan94V/payload-joins-fail

### Reproduction Steps

1. Have a collection that has a relationship

````ts
import type { CollectionConfig } from 'payload'

export const Orders: CollectionConfig = {
  slug: 'orders',
  fields: [
    {
      name: 'amount',
      type: 'number',
      required: true,
    },
    {
      name: 'customer',
      type: 'relationship',
      relationTo: 'customers',
      required: true,
    },
  ],
}

````

2. Have the relationship collection join the other collection

````ts
import type { CollectionConfig } from 'payload'

export const Customers: CollectionConfig = {
  slug: 'customers',
  admin: {
    useAsTitle: 'email',
  },
  auth: true,
  fields: [
    {
      name: 'orders',
      label: 'Orders',
      type: 'join',
      collection: 'orders',
      on: 'customer',
    },
  ],
}
````

3. Go to the admin panel and create a new customer

4. Error
`TypeError: Cannot read properties of undefined (reading 'docs')`

````
ERROR: There was an error building form state
    err: {
      "type": "DatabaseError",
      "message": "invalid input syntax for type integer: \"NaN\"",
      "stack":
          error: invalid input syntax for type integer: "NaN"
....

````

### Which area(s) are affected? (Select all that apply)

db-postgres, area: core

### Environment Info

```text
Payload:3.0.0-beta.129
```

**Comment by alexanderbnelson** [comment]
Getting the same error in 130
