### ISSUE TITLE
Within & Intersects Queries Not Documented

### ISSUE THREAD

**Issue by ainsleyclark** [payloadcms/payload#9212]
# Documentation Issue

It seems the `within` and `intersects` query operators for the Point field is not documented on the site.

https://github.com/payloadcms/payload/blob/afd69c4d5432bb484a1c3a244c3db19fc6973aa9/test/collections-rest/int.spec.ts#L1185

https://github.com/payloadcms/payload/blob/afd69c4d5432bb484a1c3a244c3db19fc6973aa9/test/collections-rest/int.spec.ts#L1240

## Additional Details

- [Discord Thread
](https://discord.com/channels/967097582721572934/1215659716538273832/1306368990729211986)

**Comment by akhrarovsaid** [comment]
Hey @ainsleyclark,

I believe the docs for those are coming in the next release thanks to Ritsu. [See his PR ](https://github.com/payloadcms/payload/pull/9194)that got merged.

**Comment by ainsleyclark** [comment]
He's too quick 😂

**Comment by r1tsuu** [comment]
Right, they are now https://payloadcms.com/docs/fields/point#example
