### ISSUE TITLE
[Bug](Collections): Unique and Index fields are not properly created when residing in Collapsible type

### ISSUE THREAD

**Issue by hunghvu** [payloadcms/payload#922]
# Bug Report

Fields of `collapsible` are created in a database collection. However, their `unique` and `index` properties are not reflected.

## Expected Behavior

Fields of `collapsible` must be able to become unique and indexed when generating database schema, which can be seen using MongoDBCompass or other methods.

## Current Behavior

As of now, only top-level fields or fields inside a `group` can be unique and indexed.

## Possible Solution

N/a

## Steps to Reproduce

- Create a collection in Payload with the code below.
```ts
import { CollectionConfig } from 'payload/types';

const Test: CollectionConfig = {
  slug: 'test',
  fields: [
    {
      name: 'neitherInCollapsibleNorGroup',
      label: 'Neither in Collapsible nor Group',
      type: 'text',
      unique: true
    },
    {
      label: 'Collapsible - visual only',
      type: 'collapsible',
      fields: [
        {
          name: 'inCollapsible',
          label: 'In Collapsible',
          type: 'text',
          unique: true,
        },
      ],
    },
    {
      name: 'group',
      label: 'Group - both visual and in DB structure',
      type: 'group',
      fields: [
        {
          name: 'inGroup',
          label: 'In Group',
          type: 'text',
          unique: true,
        },
      ],
    },
  ],
  timestamps: true,
  versions: {
    drafts: true,
  },
};

export default Test;
```

- View the collection `tests` using MongoDBCompass and confirm `inCollapsible` field is not unique and indexed.

![image](https://user-images.githubusercontent.com/62678592/184267180-4b70984e-d6d9-4ffc-b622-99acdbfd74d4.png)

## Detailed Description

- This behavior was tested on MongoDB 5.0.9 and 6.0.0 Community, Payload 1.0.19, and 1.0.21.
- Related:
  - Issue #859
  - PR #867
  - Discussion #872

**Comment by jmikrut** [comment]
Resolved in `1.0.24`. Thank you for the report @hunghvu !
