### ISSUE TITLE
Join field 'create new' causing 303's and mass redirects resulting in multiple drafts being generated

### ISSUE THREAD

**Issue by akhrarovsaid** [payloadcms/payload#9242]
### Describe the Bug

Clicking the `Create new` on a join field table button causes drawer to open as expected with the loading overlay, however it also causes multiple POST requests to the collection and the creation of (in my testing) 3 drafts unintentionally. 

See the issue in action:
https://github.com/user-attachments/assets/f3f6845f-bad0-4dc4-ae26-7edb8dd31a7b

### Link to the code that reproduces this issue

https://github.com/akhrarovsaid/payload-beta.132-join-drafts-issue-on-create-new

### Reproduction Steps

1. Create a new website template with Postgres adapter
2. Create the first user as usual
3. Seed the database
4. Add the following field to `Categories`:
```
{
    type: 'join',
    on: 'categories',
    collection: 'posts',
    name: 'relatedPosts'
  }
```
5. `pnpm dev`
6. Navigate to categories
7. Select a category
8. Click `create new` on join table
9. Observe unexpected behavior and server stdout.

### Which area(s) are affected? (Select all that apply)

db-postgres, area: templates, area: core

### Environment Info

```text
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.11.0
Relevant Packages:
  payload: 3.0.0-beta.132
  next: 15.0.0
  @payloadcms/live-preview: 3.0.0-beta.132
  @payloadcms/richtext-lexical: 3.0.0-beta.132
  @payloadcms/translations: 3.0.0-beta.132
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Home
  Available memory (MB): 16268
  Available CPU cores: 4
```

**Comment by jmikrut** [comment]
Not sure why the GitHub action commented there (@denolfe might want to check on that). Thanks for providing a repro!

We're on it!

**Comment by akhrarovsaid** [comment]
Excellent, thank you!

As for the GH action... that one's on me - I technically created the issue without pasting my repro link in it originally. Came back and added my repro.

**Comment by denolfe** [comment]
Yep, he had a ninja edit on the repro link after initial creation :)

**Comment by jacob-williams14** [comment]
confirming that I'm also experiencing this behavior for collections with drafts/versions enabled
