### ISSUE TITLE
UI in programmatically-added rows do not render until interacted with

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#9264]
### Describe the Bug

When using `addFieldRow()` in `useForm()`, UI components defined in the array for the newly-added row will not render until another field in the array row has been interacted with.

I tested custom UI component and row labels and both seem to be affected by this bug. Both client and server components are affected.

### Link to the code that reproduces this issue

https://github.com/tyteen4a03/payload-array-ui-bug

### Reproduction Steps

The reproduction is in the Media collection of the reproduction repo.

1. Clone the repo
2. Navigate to Media collection
3. Click on the "Add Row" button that's underneath the array field (the browser default style one)
4. The UI components do not render. Type something in the Test text field then navigate away, and the UI will once again render.

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

```text
Node.js v22.11.0

Binaries:
  Node: 22.11.0
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.13.0
Relevant Packages:
  payload: 3.0.0-beta.133
  next: 15.0.0
  @payloadcms/db-mongodb: 3.0.0-beta.133
  @payloadcms/email-nodemailer: 3.0.0-beta.133
  @payloadcms/graphql: 3.0.0-beta.133
  @payloadcms/next/utilities: 3.0.0-beta.133
  @payloadcms/payload-cloud: 3.0.0-beta.133
  @payloadcms/richtext-lexical: 3.0.0-beta.133
  @payloadcms/translations: 3.0.0-beta.133
  @payloadcms/ui/shared: 3.0.0-beta.133
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
```

**Comment by jacobsfletch** [comment]
@tyteen4a03 you need to include the file extension on your component paths, here's the fix:

```diff
{
      name: "array",
      type: "array",
      fields: [
        {
          name: "test",
          type: "text",
        },
        {
          name: "testuiclient",
          type: 'ui',
          admin: {
            components: {
-             Field: '@/ClientTestComponent'
+             Field: '@/ClientTestComponent.tsx'
            }
          }
        },
        {
          name: "testuiserver",
          type: 'ui',
          admin: {
            components: {
-             Field: '@/ServerTestComponent'
+             Field: '@/ServerTestComponent.tsx'
            }
          }
        },
      ],
      admin: {
        components: {
-         RowLabel: '@/ClientTestComponent'
+         RowLabel: '@/ServerTestComponent.tsx',
        }
      }
    },
```

I see the docs are misleading on this. I will update those to include file extensions.

**Comment by jacobsfletch** [comment]
@tyteen4a03 ok you're right, here's what was tripping me up about your repro and what is potentially the issue. Your custom "add row" button does not include the `type="button"` attribute, and so clicking it triggers the form to submit. This throws an error at the request level, in your case, because it's a media-enabled collection and no upload has been selected. Because of this, new form-state is _not_ generated, which includes custom components.

```diff
    <button
     onClick={handleClick} 
+    type="button"
    >
      Add Row
    </button>
```

**Comment by tyteen4a03** [comment]
> [@tyteen4a03](https://github.com/tyteen4a03) ok you're right, here's what was tripping me up about your repro and what is potentially the issue. Your custom "add row" button does not include the `type="button"` attribute, and so clicking it triggers the form to submit. This throws an error at the request level, in your case, because it's a media-enabled collection and no upload has been selected. Because of this, new form-state is _not_ generated, which includes custom components.
> 
>     <button
>      onClick={handleClick} 
> +    type="button"
>     >
>       Add Row
>     </button>

@jacobsfletch I used the Media collection as an easy non-User collection to modify, and I don't think `upload` has anything to do with it.

I removed `upload: true` to the collection and applied your fix and the problem persists.

**Comment by jacobsfletch** [comment]
Ok. Yep. Finally able to reproduce. When you _already_ have a row in form state, adding a new one with your custom button _works_. It's only when the array does not yet have any rows that the `addFieldRow` method fails to render your custom components. I will re-open this and look into it. Thanks for bearing with me there.
