### ISSUE TITLE
Leave without saving modal upon saving new collection item in safari

### ISSUE THREAD

**Issue by dottemechy** [payloadcms/payload#930]
# Bug Report

I have tested this behavior with a brand new `yarn create payload-app`, on Payload version 1.0.22. No changes to the code were made. I have only tested this behavior in a development environment. I have not tested this behavior in production.

When creating a new item in a collection, clicking on the "Save" button will open the "Leave without saving" modal, as pictured below. After clicking "Leave anyway" the new collection item appears to have saved as normal.
![Screen Shot 2022-08-13 at 10 03 18 AM](https://user-images.githubusercontent.com/13079768/184498030-03c372b1-77ba-4177-a81c-15b190432f84.jpg)

I have tested this across a few browsers (Firefox, Safari, and Opera), and it only happens on Safari.

## Expected Behavior

Clicking the "Save" button should bring the notification that says "{{ Name of Collection }} saved successfully" without bringing up the modal. This is the current behavior in all browsers I have tested other than Safari.

## Current Behavior

In Safari:
Clicking "Save" when creating a new collection item brings a "Leave without saving" modal. (As per screenshot above)

In Other Browsers (Expected Behavior):
Clicking "Save" brings up a notification that says "{{ Name of Collection }} saved successfully"

## Steps to Reproduce

1.  `yarn create payload-app`
    a. Choose Language: `Typescript`
    b. Choose Project template: `blog`
2. `yarn dev`
3. Go to `localhost:3000/admin` (In Safari)
4. Create First Account
5. Create a new Category
    a. Give that Category a Name
6. Click the "Save" Button

## Detailed Description

Information about my machine if it is helpful:
Late 2020 (M1) Macbook Air
Payload Version 1.0.22
MacOS version 12.5
Safari Version 15.6

**Comment by jmikrut** [comment]
Hey @dottemechy — thank you very much for the report! This is fixed and released in `1.0.23`.
