### ISSUE TITLE
Hydration error on first install

### ISSUE THREAD

**Issue by sajadabedi** [payloadcms/payload#9354]
I just experimented with the `v3` using the new `npx create-payload-app` command, and on my first run, I encountered the NextJS hydration error. During the installation, I selected website and sqlite as the database. When I ran the app locally, this is the error I got.

![Image](https://github.com/user-attachments/assets/3323d930-58ab-449b-904a-907fe86dc065)

**Comment by tylandavis** [comment]
Hey @sajadabedi, I moved this to the `payload` repo. The `website` repo is for our website at [payloadcms.com](https://payloadcms.com).

You can find the source code for the website template and others in our [templates directory](https://github.com/payloadcms/payload/tree/main/templates)

**Comment by stuckinsnow** [comment]
Do you have colorpicker installed by any chance?

**Comment by vilmarfonseca** [comment]
@sajadabedi In my case, the issue was related to the Grammarly browser extension. Removing that extension removed the hydration I was getting.

**Comment by sajadabedi** [comment]
Yes, it turns out it was because of Grammarly. However, I still think it's weird that this happened, as I don't have this problem with React/Next.js.

**Comment by JarrodMFlesch** [comment]
Looks like you can follow along [here](https://github.com/facebook/react/issues/24430). I would see if you can reach out to grammarly (not sure how they accept feedback) about adding the `suppresshydrationwarning` to their script tag they inject.
