### ISSUE TITLE
`id` is not URI decoded before lookup

### ISSUE THREAD

**Issue by nathanclevenger** [payloadcms/payload#9373]
### Describe the Bug

In a collection with a `id` of type `text`, the `id` is not URI decoded before lookup, so it's impossible to view/edit the item as attempts to navigate result in a 404

### Link to the code that reproduces this issue

https://github.com/nathanclevenger/payload-repro

### Reproduction Steps

Create a document with an ID that would be URL Encoded (space/symbol/emoji,etc)
![Image](https://github.com/user-attachments/assets/e11f0bc8-4a79-4976-83f7-2b2e80e81df9)

On save, it redirects to a 404:
![Image](https://github.com/user-attachments/assets/e5752fbd-78bf-4262-aadc-22d09d6b43ab)

In the collection, all items are displayed, but links are invalid:
![Image](https://github.com/user-attachments/assets/a1179577-8b2a-4d33-961a-1aae0e85051c)
![Image](https://github.com/user-attachments/assets/5d7ab2bd-a9c8-4b72-9dfe-6d315b13b96c)

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

```text
Payload: 3.0.1
Nextjs: 15.0.0
Node: 20.13.1
```

**Comment by JarrodMFlesch** [comment]
Currently Payload does not allow for custom IDs that look like this. You will need to run sanitization on the ID's before the document gets created.

**Comment by JarrodMFlesch** [comment]
[PR](https://github.com/payloadcms/payload/pull/9407) to fix this regression.
