### ISSUE TITLE
generate:types works occasionally

### ISSUE THREAD

**Issue by seccentral** [payloadcms/payload#9378]
### Describe the Bug

As reported by multiple users on Discord (myself included) it seems to be a platform independent issue that whenever you attempt to `generate:types` manually, the command executes without error, without any sort of feedback, but does **not** generate the types. 
This has been tested on user code migrated from beta to 3.0 stable but I also tested it on the official payload default website template that comes with create-payload-app for the current 3.0.1 version just to be sure. 

### Link to the code that reproduces this issue

official payload 3 stable website template

### Reproduction Steps

run `generate:types` .
It - MAY - work from the 1st try, but usually it takes a random amount of tries. 
Original User reporting success after spamming the command multiple times (frustration saved the day?) here https://discord.com/channels/967097582721572934/1308797740087775232

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Binaries:
  Node: 20.18.1
  npm: 10.9.0
  Yarn: N/A
  pnpm: 9.14.2
Relevant Packages:
  payload: 3.0.1
  next: 15.0.3
  @payloadcms/db-postgres: 3.0.1
  @payloadcms/email-nodemailer: 3.0.1
  @payloadcms/graphql: 3.0.1
  @payloadcms/live-preview: 3.0.1
  @payloadcms/live-preview-react: 3.0.1
  @payloadcms/next/utilities: 3.0.1
  @payloadcms/payload-cloud: 3.0.1
  @payloadcms/plugin-form-builder: 3.0.1
  @payloadcms/plugin-nested-docs: 3.0.1
  @payloadcms/plugin-redirects: 3.0.1
  @payloadcms/plugin-search: 3.0.1
  @payloadcms/plugin-seo: 3.0.1
  @payloadcms/richtext-lexical: 3.0.1
  @payloadcms/translations: 3.0.1
  @payloadcms/ui/shared: 3.0.1
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: linux
  Arch: x64
  Version: #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024
  Available memory (MB): 7895
  Available CPU cores: 8
```

PS: the payload command should have some output, feedback, or at least throw something. as it is it has no --help, no list of commands no explanatory output accesible right away from the cli

**Comment by yonnic** [comment]
omg yes i had a fight with this bug the whole day when i was working with job tasks and all the TS types were missing.
I can confirm that it randomly works

**Comment by andershermansen** [comment]
`generate:types` 6 times with `v3.0.1`.
Result: 3 times with no output. 3 times executed ok.

`generate:types` 6 times with `v3.0.2`
Result: 6 times executed ok 👍

**Comment by DanRibbens** [comment]
Thanks for confirming @andershermansen!
