### ISSUE TITLE
Date field has worse appearance in the new version

### ISSUE THREAD

**Issue by bubacho** [payloadcms/payload#9383]
### Describe the Bug.

![Image](https://github.com/user-attachments/assets/3d2d12db-b960-4393-b06c-48141bbd71f5)

The date field now looks worse than in the previous version. The colors are not readable and make it difficult to use. In the previous version, this field had a much better design and was more user-friendly.

### Reproduction Steps

1.	Install the latest version of Payload CMS (3.0.1).
2.	Create a new project with the “Blank” or “Website” template.
3.	Open the admin panel and go to any collection with a date field.
4.	Observe the appearance of the date picker field.

### Environment Info

```text
Payload Version: 3.0.1
Node.js Version: 22.5.1
Operating System: MacOs Sonoma 14.6.1
Browser: Chrome 131.0.6778.69
```

**Comment by yonnic** [comment]
hm cannot confirm, i have 3.0.1 too and the dark mode looks fine here

![Image](https://github.com/user-attachments/assets/1d9d2def-b117-4b35-b8c3-4f611f247517)

**Comment by bubacho** [comment]
sorry, cache
