### ISSUE TITLE
[Bug] buildSchema is executed before mongoose set strictQuery to false in initSync function

### ISSUE THREAD

**Issue by EasonSoong** [payloadcms/payload#939]
# Bug Report

https://github.com/payloadcms/payload/blob/master/src/mongoose/connect.ts#L42
This line is executed before buildSchema in initAsync function. But after buildSchema in initSync function. And this makes the query api behavior different.

## Expected Behavior

Setting strictQuery to false should be executed before buildSchema in initSync function too.

## Current Behavior

Setting strictQuery to false  is executed after buildSchema in initSync.

## Possible Solution

Rearrange the execute order in initSync.

## Steps to Reproduce

1. Try initAsync and initSync function.

## Detailed Description

1.0.22

**Comment by Dropnspl87** [comment]
https://www.facebook.com/profile.php?id=100083307453380

**Comment by jmikrut** [comment]
Related discussion: https://github.com/payloadcms/payload/discussions/852
