### ISSUE TITLE
NPM `payload` package readme is still written for v2

### ISSUE THREAD

**Issue by nathanclevenger** [payloadcms/payload#9452]
# Documentation Issue

The readme on https://www.npmjs.com/package/payload still talks about upgrading Payload v1 to v2 and doesn't mention v3:

`Migrating from v1 to v2? Check out the [2.0 Release Notes](https://github.com/payloadcms/payload/releases/tag/v2.0.0) on how to do it.`

`🎉 Payload 2.0 is now available! Read more in the [announcement post](https://payloadcms.com/blog/payload-2-0).`

**Comment by denolfe** [comment]
Haha, wow, we thought it was some sort of caching issue. When in reality, we needed to update the README _in the payload package dir_. Thanks for bringing this up.
