### ISSUE TITLE
[Jobs/Tasks] SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by devcshort** [payloadcms/payload#9453]
### Describe the Bug

I've followed the [jobs/tasks guide](https://payloadcms.com/docs/jobs-queue/tasks) and am getting this error.
```
import type { TaskHandler } from 'payload';
^^^^^^
          
SyntaxError: Cannot use import statement outside a module
```

I've created a new project using `npx create-payload-app@latest` and recreated a minimal example in [this repo](https://github.com/devcshort/payload-task-issue)

### Link to the code that reproduces this issue

https://github.com/devcshort/payload-task-issue

### Reproduction Steps

`npm install`

`npm run dev`

`HTTP GET http://localhost:3000/my-route`

That should be it. The API route is configured to queue and run the job/task that I've set up.

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Payload: latest
Next.js: 15.0.0
Node.js: 20.12.2
NPM: 10.5.0
```

**Comment by AlessioGr** [comment]
Next.js cannot import task / workflow handlers from paths, as they won't be included in the Bundle. You will either have to provide the functions directly without using import paths, or execute your jobs from outside of Next.js.

If have clarified this in our docs / JS Docs in https://github.com/payloadcms/payload/issues/9453 - additionally, we now throw a proper error
