### ISSUE TITLE
Error uploading file when a file seems corrupted with sharp.

### ISSUE THREAD

**Issue by alexdieudonne** [payloadcms/payload#946]
# Bug Report
When trying to upload a file i face an errored which said that There was an problem trying to upload a file.

<img width="379" alt="Screenshot 2022-08-16 at 21 07 34" src="https://user-images.githubusercontent.com/59718717/184962663-cf4356de-e80a-4623-be2f-446260e092cc.png">

The file should upload even if i don't trust this one
## Current Behavior
it cause a throw 

## Possible Solution
You could edit the file https://github.com/payloadcms/payload/blob/78edac684e54d335b15303d8348c8abcb2bba716/src/uploads/imageResizer.ts#L54

And apply the following solution
https://github.com/lovell/sharp/issues/1859#issuecomment-528255648

<img width="637" alt="Screenshot 2022-08-16 at 21 07 26" src="https://user-images.githubusercontent.com/59718717/184962716-ef69699c-f8be-4b39-8466-f2864f5e60e4.png">

## Steps to Reproduce

1.
2.
3.
4.

**Comment by denolfe** [comment]
Thanks for the report @alexdieudonne . I have a few clarifying questions:

- Are you uploading from the Admin UI?
- Does this happen for any file you attempt or specific ones?
- What version of node?

**Comment by alexdieudonne** [comment]
Okay

> I'm not uploading from the Admin UI, it's through the API
> No i've found the solution. This occur when you want to upload a file and this one exceed the limit that you've chosen in your payload config file 
> v18.7.0
