### ISSUE TITLE
interfaceName does not work for named tabs.

### ISSUE THREAD

**Issue by ckruppe** [payloadcms/payload#9467]
### Describe the Bug

If i define an "interfaceName" for an named tab no extra type interface gets generated.

### Link to the code that reproduces this issue

https://github.com/ckruppe/Payload-issues-reproduction

### Reproduction Steps

1.) Clone the Repo
2.) Install dependencies with yarn
3.) Collection config can be found under "src/server/payload/collections/Stores.ts"
4.) Collection defines an group interfaceName (StoreAdress) in line 82 and an tab interfaceName (ReferringMedia) in line 195.
5.) Run yarn generate:types
6.) Generated file can be found under "types/payload-types.ts"
7.) StoreAdress got generated, ReferringMedia not.

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Binaries:
  Node: 22.11.0
  npm: 10.3.0
  Yarn: 1.22.19
  pnpm: 8.11.0
Relevant Packages:
  payload: 3.1.0
  next: 15.0.3
  @payloadcms/db-mongodb: 3.1.0
  @payloadcms/graphql: 3.1.0
  @payloadcms/live-preview: 3.1.0
  @payloadcms/live-preview-react: 3.1.0
  @payloadcms/next/utilities: 3.1.0
  @payloadcms/plugin-nested-docs: 3.1.0
  @payloadcms/plugin-seo: 3.1.0
  @payloadcms/richtext-lexical: 3.1.0
  @payloadcms/richtext-slate: 3.1.0
  @payloadcms/translations: 3.1.0
  @payloadcms/ui/shared: 3.1.0
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32488
  Available CPU cores: 16
```

**Comment by r1tsuu** [comment]
Hello @ckruppe! Indeed I can reproduce this on the current version, but I have a PR https://github.com/payloadcms/payload/pull/9299 where this is already fixed!

**Comment by ckruppe** [comment]
@r1tsuu very nice. Thank you! :)
