### ISSUE TITLE
On tabswitch the page get scrolled to the top

### ISSUE THREAD

**Issue by matthijs166** [payloadcms/payload#948]
# Bug Report

When I have a tab field in a block and switch the tab I get scrolled to the top.

## Expected Behavior

I expect to be on the same scroll position when I switch tabs

## Current Behavior

On tab switch the page get scrolled to the top

## Possible Solution

Lock scroll position on tab switch

## Steps to Reproduce

The configuration for the block field:
`{"slug":"usp-section","imageURL":"/media/block-previews/usp.jpg","fields":[{"type":"tabs","tabs":[{"label":"Content","fields":[{"name":"title","label":"Titel","type":"text","required":true,"defaultValue":"Header 1"},{"name":"subTitle","label":"Subtitel","type":"textarea","defaultValue":"Xerum sanihit od quis represt ianihil moditi dolecae natiaep taspelliqui sandis entioria ni optature volenest od excestiam rere, omnimpereium nobissi nctation excerem acest maxim quasitam, ommosam asperi officia con nullic te autemolecat dolorio nsequistio. "},{"name":"text","label":"Tekst","type":"richText","required":true}]},{"label":"Algemeen","fields":[{"name":"section-border-color","label":"Sectie rand kleur","type":"text","required":true,"defaultValue":"orange","admin":{"components":{}}}]},{"label":"Dropdown","fields":[{"name":"dropdownsBox","label":"Vragenlijst","type":"group","required":true,"fields":[{"name":"title","label":"Titel","type":"text"},{"name":"questions","label":"Vragen","type":"array","fields":[{"name":"title","label":"Titel","type":"text","required":true},{"name":"text","label":"Tekst","type":"richText","required":true}]},{"type":"collapsible","label":"Button","fields":[{"name":"button","label":"Button","type":"group","required":true,"fields":[{"type":"text","name":"text","label":"Tekst","required":true,"defaultValue":"Bekijken"},{"type":"relationship","name":"link","label":"Link","relationTo":"pages","maxDepth":1},{"name":"color","label":"Kleur","type":"text","required":true,"defaultValue":"orange","admin":{"components":{}}},{"type":"select","name":"iconType","label":"Icon Type","defaultValue":"empty","options":[{"value":"empty","label":"Geen icon"},{"value":"customer-support","label":"Customer support"},{"value":"home","label":"Home"},{"value":"user","label":"User"}]}]}]}]}]}]}]}`

## Detailed Description

Payload 1.0.24

**Comment by denolfe** [comment]
Thanks for the report @matthijs166 . I was able to recreate.


https://user-images.githubusercontent.com/65888/185178132-11bababa-fbfd-4280-9760-40e9238145da.mov

**Comment by jmikrut** [comment]
Hey all, this is actually because the "length" of the blocks field is _**taller**_ than the length of the array field. So, when you tab over to Arrays, the page gets shorter, and you are FORCED to scroll back up.

There's nothing that Payload can do about this one unfortunately. Or at least nothing that we _**should**_ do.

**Comment by denolfe** [comment]
Had a chat about this internally. Still an issue and can be recreated with `yarn dev fields`.

**Comment by matthijs166** [comment]
@jmikrut this was not the case in a previous version of payload.

It's very enjoying now when you have a large page with a lot of content blocks.

**Comment by jmikrut** [comment]
@matthijs166 — yes, we just talked about this and there may be something else happening here. It's still related to not having a "height" on a tab field, but we may be able to do something about it internally. Will get back to you shortly!

**Comment by DanRibbens** [comment]
The change we made to fix this didn't solve it. We thought that removing the lazy-loading of subfields would have an impact on the re-rendering and scrolling behavior. There is something else at play that we need to identify. We'll have to do more digging.

**Comment by jmikrut** [comment]
Hey @matthijs166 — thank you for this issue! We've just deployed a fix which will resolve the issue. It will be deployed in an upcoming version of Payload, probably either later today or tomorrow.

Thank you!!
