### ISSUE TITLE
Slovenian not allowed in i18n supported languages

### ISSUE THREAD

**Issue by gigaSproule** [payloadcms/payload#9504]
### Describe the Bug

Trying to pass in `sl` from `@payloadcms/translations/languages/sl` into `i18n.supportedLanguages`, a typescript error is thrown because `sl` is not a valid key. Looking into the `acceptedLanguages`, `sl` is not allowed.

Setting typescript to ignore the error allows Payload CMS to build, however setting the language to Slovenian, then throws an error:
```
Internal error: TypeError: Cannot read properties of undefined (reading 'default')
    at importDateFNSLocale (./node_modules/@payloadcms/translations/dist/importDateFNSLocale.js:102:16)
    at eval (./node_modules/@payloadcms/translations/dist/utilities/init.js:144:103)
    at memoized (./node_modules/@payloadcms/translations/dist/utilities/init.js:129:34)
    at getNextRequestI18n (./node_modules/@payloadcms/next/dist/utilities/getNextRequestI18n.js:19:82)
    at async generatePageMetadata (./node_modules/@payloadcms/next/dist/views/Root/meta.js:55:16)

```

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload/blob/main/packages/translations/src/utilities/languages.ts#L5

### Reproduction Steps

Try to include `sl` from `@payloadcms/translations/languages/sl` into the `i18n.supportedLanguages`, then go into your account and set your language to Slovenian.

### Which area(s) are affected? (Select all that apply)

plugin: other

### Environment Info

```text
Binaries:
  Node: 20.18.0
  npm: 10.8.2
  Yarn: 4.4.0
  pnpm: 9.1.2
Relevant Packages:
  payload: 3.0.0
  next: 15.0.0
  @payloadcms/db-mongodb: 3.0.0
  @payloadcms/email-nodemailer: 3.0.0
  @payloadcms/graphql: 3.0.0
  @payloadcms/next/utilities: 3.0.0
  @payloadcms/payload-cloud: 3.0.0
  @payloadcms/plugin-seo: 3.0.0
  @payloadcms/richtext-lexical: 3.0.0
  @payloadcms/translations: 3.0.0
  @payloadcms/ui/shared: 3.0.0
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:39:07 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 10
```

**Comment by JessChowdhury** [comment]
Hey @gigaSproule - thank you for opening this issue, I was running into issues with the `sl` translation files myself this morning. We have a PR open from @akanshSirohi, this will be merged shortly and resolved in the next release.

**Comment by JessChowdhury** [comment]
@akanshSirohi yes apologies that was a mistake!
