### ISSUE TITLE
Missing types in payload package

### ISSUE THREAD

**Issue by kolyasya** [payloadcms/payload#9539]
### Describe the Bug

Hello, I'm trying to upgrade my Payload 3.0 beta app to release (3.1.1) version and have type issues so I can't build.

![Image](https://github.com/user-attachments/assets/f60cd170-eba8-4f0b-9b22-15380a62987c)
![Image](https://github.com/user-attachments/assets/122b511e-6bc0-42de-aaec-37c47aafbe2c)

I double checked that the latest `payload` is installed
![Image](https://github.com/user-attachments/assets/83af407f-ac9c-4e7f-b114-82ab3fcab313)

### Link to the code that reproduces this issue

blank template from payload repo includes these lines

### Reproduction Steps

Just start from scratch with blank Payload 3 CMS.

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Binaries:
  Node: 18.20.5
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.14.2
Relevant Packages:
  payload: 3.1.1
  next: 15.0.0
  @payloadcms/db-mongodb: 3.1.0
  @payloadcms/email-nodemailer: 3.1.0
  @payloadcms/graphql: 3.1.0
  @payloadcms/next/utilities: 3.1.0
  @payloadcms/payload-cloud: 3.1.0
  @payloadcms/richtext-lexical: 3.1.0
  @payloadcms/translations: 3.1.0
  @payloadcms/ui/shared: 3.1.0
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
```

**Comment by denolfe** [comment]
A few thoughts here.

1. You'll want to be sure to update your `app\(payload)` directory from one of the templates. You can copy from [here](https://github.com/payloadcms/payload/tree/main/templates/blank/src/app/(payload))
2. I'd be absolutely sure to delete your lock file and `node_modules` locally, as this can cause issues of resolution like this.

I've confirmed that this is not an issue on a fresh 3.1.1 project, so this is likely something with your local repo.

**Comment by kolyasya** [comment]
@denolfe just did this two steps — didn't help. 

And I had the same issue on Coolify VPS server when trying to build the project. I don't think it is related to my local node_modules.

**Comment by kolyasya** [comment]
@denolfe I can confirm that I don't have such issue on freshly created project with `payload 3.2.1`.
But it didn't help to update existing project (which is basically a fresh one as well). :-/ Don't have an idea what is wrong, but will try to investigate.
