### ISSUE TITLE
Postgres migrations are broken

### ISSUE THREAD

**Issue by robbedekienbothrs** [payloadcms/payload#9560]
### Describe the Bug

I don't have time to post a proper issue with a reproduction repository so apologies if this is too unstructured.
Somewhere between `@payloadcms/db-postgres@3.1.0` and `@payloadcms/db-postgres@3.2.1` all our migrations started giving typing errors. See error below. I figured this is pretty self explanatory and doesn't require a reproduction url
Migrations are fine on version `3.1.0`

```
Argument of type 'SQL<unknown>' is not assignable to parameter of type 'string | SQLWrapper'.
  Type 'SQL<unknown>' is not assignable to type 'SQLWrapper'.
    The types returned by 'getSQL()' are incompatible between these types.
      Type 'import("/Users/robbe/Projects/<redacted>/node_modules/@payloadcms/db-postgres/node_modules/drizzle-orm/sql/sql").SQL<unknown>' is not assignable to type 'import("/Users/robbe/Projects/<redacted>/node_modules/@payloadcms/drizzle/node_modules/drizzle-orm/sql/sql").SQL<unknown>'.
        Types have separate declarations of a private property 'shouldInlineParams'.ts(2345)
```

### Link to the code that reproduces this issue

https://payloadcms.com/

### Reproduction Steps

1. Have at least one postgres migration
2. Make sure `@payloadcms/db-postgres` is on version `3.2.1`
3. View migration file with error

### Which area(s) are affected? (Select all that apply)

db-postgres

### Environment Info

```text
Payload: 3.2.1
@payloadcms/db-postgres: 3.2.1
```

**Comment by r1tsuu** [comment]
Right, I believe bumps of drizzle were also breaking changes and your installed version should always match what Payload uses. The same for example with Lexical
