### ISSUE TITLE
Failed to initialize git repository

### ISSUE THREAD

**Issue by supra-dheerajacharya** [payloadcms/payload#9609]
### Describe the Bug

![Image](https://github.com/user-attachments/assets/fe4ea62f-1c57-4ba4-9058-0c9a8c894913)
![Image](https://github.com/user-attachments/assets/be27054c-71b7-4273-983a-ce4259085083)

Getting error when trying to create new project with existing DB but in new DB it works fine.

What should I do now ?

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload/blob/main/.github/reproduction-guide.md

### Reproduction Steps

I cannot provide a link to the code that reproduces this issue because DB is In my local machine and due to safety concern I cannot expose it 

Create Payload app with existing DB in postgres 

### Which area(s) are affected? (Select all that apply)

area: core, db-postgres

### Environment Info

```text
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.22
  pnpm: 9.0.6
Relevant Packages:
  payload: 3.2.1
  next: 15.0.3
  @payloadcms/db-postgres: 3.2.1
  @payloadcms/email-nodemailer: 3.2.1
  @payloadcms/graphql: 3.2.1
  @payloadcms/live-preview: 3.2.1
  @payloadcms/live-preview-react: 3.2.1
  @payloadcms/next/utilities: 3.2.1
  @payloadcms/payload-cloud: 3.2.1
  @payloadcms/plugin-form-builder: 3.2.1
  @payloadcms/plugin-nested-docs: 3.2.1
  @payloadcms/plugin-redirects: 3.2.1
  @payloadcms/plugin-search: 3.2.1
  @payloadcms/plugin-seo: 3.2.1
  @payloadcms/richtext-lexical: 3.2.1
  @payloadcms/translations: 3.2.1
  @payloadcms/ui/shared: 3.2.1
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: linux
  Arch: x64
  Version: #136~20.04.1-Ubuntu SMP Thu Nov 14 16:38:05 UTC 2024
  Available memory (MB): 15877
  Available CPU cores: 4
```

**Comment by paulpopus** [comment]
What happens if you run `pnpm payload migrate:create` while pointing to the existing database?

**Comment by supra-dheerajacharya** [comment]
![Image](https://github.com/user-attachments/assets/545982da-6711-4945-a22e-b211604dd3c7)

@paulpopus No Luck

**Comment by paulpopus** [comment]
You've created your migrations so you should be able to run them with `payload migrate`...That said it should run automatically when developing locally if you haven't turned off `push` in the DB adapter

You can check out our docs for workflows with database migrations: https://payloadcms.com/docs/database/postgres#migration-workflows
