### ISSUE TITLE
Changing the project structure - Error 404

### ISSUE THREAD

**Issue by Mbensler** [payloadcms/payload#9630]
### Describe the Bug

_I have already tried getting help on the discord server, without any answers: https://discord.com/channels/967097582721572934/1312175693286608948._

I am creating a site that includes **next-intl** for i18n, which requires me to have this structure:
- src
-- app
--- [locale]
---- (frontend)
---- (payload)
The reason why this structure is required is because i am using no prefix for my default language and a prefix for my second language.
If i dont do this structure i can not get to the admin page due to this matcher from next-intl:
```js
export const config = {
  // Matcher entries are linked with a logical "or", therefore
  // if one of them matches, the middleware will be invoked.
  matcher: [
    // Match all pathnames except for
    // - … if they start with `/api`, `/_next` or `/_vercel`
    // - … the ones containing a dot (e.g. `favicon.ico`)
    '/((?!api|_next|_vercel|.*\\..*).*)',
    // However, match all pathnames within `/users`, optionally with a locale prefix
    '/([\\w-]+)?/users/(.+)'
  ]
};
```
I am using the above matcher, and the next-intl project structure to, like i said, be able to use no prefix for my default language but a prefix for my second. 

This matcher does not work with Payloads default project structure. I could not get to my admin panel, no matter how much i tried changing the matcher to include admin, therefore i decided to instead change Payloads structure to the one above and in my repro.

Now everything works smooth, except the most important part: **Whenever i try to post anything i get a 404 not found.**

XHRGET
http://localhost:3000/api/payload-preferences/locale
[HTTP/1.1 404 Not Found 175ms]

XHRGET
http://localhost:3000/api/payload-preferences/nav
[HTTP/1.1 404 Not Found 188ms]

Seeding my db also does not work anymore. 

Everything worked fine before changing the project structure.

I then found this:
`https://payloadcms.com/docs/admin/overview#customizing-routes`

I have tried all possible ways of changing to the correct routes, but whenever i change the admin and api routes in the paylod.config.ts i just get a white page and a 404 and this error: `⨯ Error: Could not find the payload admin directory. Looked in C:\Users\myUser\Documents\GitHub\payload3-nextintl-issuerepo\app\(payload).\[locale]\admin and C:\Users\myUser\Documents\GitHub\payload3-nextintl-issuerepo\src\app\(payload).\[locale]\admin`

It seems to be hardcoded to this: `\app\(payload)\` no matter what i try.

Example:

```js
  routes: {
    admin: '/app/admin',
    api: '/api/[locale]/',

 ⨯ Error: Could not find the payload admin directory. Looked in C:\Users\myUser\Documents\GitHub\payload3-nextintl-issuerepo\app\(payload)\app\admin and C:\Users\myUser\Documents\GitHub\payload3-nextintl-issuerepo\src\app\(payload)\app\admin
  },
```
I also started getting this a few times after changing the structure.
```js
Generating import map
[Function (anonymous)]
 ⨯ ..\..\node_modules\.pnpm\payload@3.2.1_graphql@16.9.0_monaco-editor@0.52.0_react-dom@19.0.0-rc-65a56d0e-20241020_react_jqjkbuafwviv24bimp3tgs6jda\node_modules\payload\dist\bin\generateImportMap\index.js (81:1) @ addToImportMap
 ⨯ Internal error: Error: addToImportMap > Payload component must be an object or a string
editor@0.52.0_next@15.0.3_@babel+core@7.25.8_bab_cqhr3ayhe2cureb5eipykt5j5q/node_modules/@payloadcms/next/dist/layouts/Root/index.js:66:21)
digest: "4148784728"
  79 |         if (typeof payloadComponent !== 'object' && typeof payloadComponent !== 'string') {
  80 |             console.error(payloadComponent);
> 81 |             throw new Error('addToImportMap > Payload component must be an object or a string');
     | ^
```

If you need anything else, please let me know.

### Link to the code that reproduces this issue

https://github.com/Mbensler/payload3-nextintl-issuerepo

### Reproduction Steps

1. download repo
2. add db in pgadmin/postgres with db name payload3-nextintl and pass which is in the .env
3. pnpm install
4. npm run dev
5. localhost:3000/admin
6. create user and login
7. try to post something

### Which area(s) are affected? (Select all that apply)

db-postgres, area: core

### Environment Info

```text
Binaries:
  Node: 23.3.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.14.4
Relevant Packages:
  payload: 3.2.2
  next: 15.0.3
  @payloadcms/db-postgres: 3.2.2
  @payloadcms/email-nodemailer: 3.2.2
  @payloadcms/graphql: 3.2.2
  @payloadcms/live-preview: 3.2.2
  @payloadcms/live-preview-react: 3.2.2
  @payloadcms/next/utilities: 3.2.2
  @payloadcms/payload-cloud: 3.2.2
  @payloadcms/plugin-form-builder: 3.2.2
  @payloadcms/plugin-nested-docs: 3.2.2
  @payloadcms/plugin-redirects: 3.2.2
  @payloadcms/plugin-search: 3.2.2
  @payloadcms/plugin-seo: 3.2.2
  @payloadcms/richtext-lexical: 3.2.2
  @payloadcms/translations: 3.2.2
  @payloadcms/ui/shared: 3.2.2
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
  Available memory (MB): 16312
  Available CPU cores: 24
```

**Comment by HarleySalas** [comment]
I've got an older payload 3 beta project that uses `next-intl`. The localization and routing parts should still be exactly the same, if you'd like to reference it.

https://github.com/conqdb/conqdb/tree/main/apps/web

You should not use `next-intl` with the payload dashboard; the Payload admin has it's own i18n solution.
Please reference the routing and middleware that you see in the project I linked.
