### ISSUE TITLE
Missing payload.auth from documentation

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload#9631]
# Documentation Issue

Local API does not document the `payload.auth` method.
https://payloadcms.com/docs/local-api/overview

This was brought to my attention when helping someone with custom components. They were able to figure out how to get the current user with the  `useAuth` hook in the client, but were unaware of how to get the current user on the server. Apparently they had been trying to figure it out all day, with no luck. Thus, while it is not necessary to document *everything* right now, I do think this is a common scenario where people will need this piece of information now.

**Comment by yonnic** [comment]
what you can do in such case is to check the sample projects. There is a lot of code which is not documented.
I also use https://grep.app/ to find code parts for payload across all github

**Comment by HarleySalas** [comment]
> what you can do in such case is to check the sample projects. There is a lot of code which is not documented.
> I also use https://grep.app/ to find code parts for payload across all github

I've been aware of the method for quite a long time. Its just clear to me that people aren't finding it and documenting it would help with that.  

Many features aren't documented, I agree. I consider this to be a very core necessity, hence the PR.
