### ISSUE TITLE
Block > tab > collapsible> field is not storing any data

### ISSUE THREAD

**Issue by matthijs166** [payloadcms/payload#976]
# Bug Report

When Im saving the page and have data in the field Block > tab > collapsible > field the data is not stored

## Expected Behavior

I expect that it saves the field

## Current Behavior

Fields stays empty

## Steps to Reproduce
Field configuration:

`{"slug":"quoteBanner","imageURL":"/media/block-previews/quote-banner.png","fields":[{"type":"tabs","tabs":[{"label":"Content","fields":[{"name":"sectionBorderColor","label":"Sectie rand kleur","type":"text","required":true,"defaultValue":"orange","admin":{"components":{}}},{"name":"quote","label":"Quote","type":"textarea","defaultValue":"Eigenlijk waren we helemaal super tevreden op het bezoek van NVT."},{"type":"collapsible","label":"Knop","fields":[{"name":"button","label":"Knop","type":"group","fields":[{"type":"text","name":"text","label":"Tekst","required":true,"defaultValue":"Bekijken"},{"type":"relationship","name":"link","label":"Link","relationTo":"pages","maxDepth":1},{"name":"color","label":"Kleur","type":"text","required":true,"defaultValue":"orange","admin":{"components":{}}},{"type":"select","name":"iconType","label":"Icon Type","defaultValue":"empty","options":[{"value":"empty","label":"Geen icon"},{"value":"customer-support","label":"Customer support"},{"value":"home","label":"Home"},{"value":"user","label":"User"}]}]}]}]},{"label":"Algemeen","fields":[{"name":"right","label":"Rechts uitgelijnd","type":"checkbox","defaultValue":true},{"name":"bgImage","label":"Achtergrond afbeelding","relationTo":"media","type":"upload","required":true}]}]}]}`

## Detailed Description

"payload": "^1.0.24",

**Comment by DanRibbens** [comment]
Thanks for reporting this!

I was able to reproduce it and it looks a problem with the frontend. The data sending from the create form in my test looks like this:

```json
{
   "blocks":[
      {
         "0":{
            "textInCollapsible":"gtest"
         },
         "id":"6308312cc6c9720dbcb66888",
         "blockType":"tabs"
      },
      {
         "id":"63083133c6c9720dbcb66889",
         "text":"test",
         "blockType":"text"
      }
   ]
}
```

This is based on the block set up here: https://github.com/payloadcms/payload/blob/fix/%23976-field-not-storing-data/test/fields/collections/Blocks/index.ts#L70

The extra keyed object "0" is causing the data to not match up with the schema.

Reproduced in branch `fix/#976-field-not-storing-data`.
