### ISSUE TITLE
Missing components from @payloadcms/ui exports

### ISSUE THREAD

**Issue by rilrom** [payloadcms/payload#9794]
### Describe the Bug

The components `EditUpload`, `SearchFilter`, `FileDetails` and `PreviewSizes` are missing from the `@payloadcms/ui` exports.

These components are needed if trying to create a custom upload component based off the official one.

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload/tree/main/packages/ui

### Reproduction Steps

Attempt to export any of the mentioned packages from `@payloadcms/ui`.

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

```text
Payload: 3.4.0
Next: 15.0.3
```

**Comment by cgilly2fast** [comment]
Can concur, when making custom components, I often find whole (unchanged) functions that I need to copy to my codebase because they are not exported. Will make another comment with list

**Comment by richadr** [comment]
If someone is working on a PR, please add `PreviewButton` to the list.  Otherwise, I will check later in the week and submit one.
