### ISSUE TITLE
Change user password works without validate anything

### ISSUE THREAD

**Issue by manutepowa** [payloadcms/payload#981]
# Bug Report
When click change password button, the first render of the two fields "Password and ConfirmPassword", values are undefined and you can save collection without type anything.

For ejample: Required validaton is ignored

## Expected Behavior
Two fields are required and have to validate and show error message

## Steps to Reproduce

1. Access to user profile, and click on change password.
2. without type anything, click on save.
3. Or type only password field and click on save.

Im trying to make a pull request but dont see the mistake.

Can you guide me to find the solution?

**Comment by jmikrut** [comment]
Hey @manutepowa — thank you very much for the issue report! We've handled this one but we really appreciate your willingness to PR. We will be releasing the fix shortly in an upcoming Payload patch version. Keep an eye out!
