### ISSUE TITLE
Client-side number field `min`/`max` validation shows raw translation key

### ISSUE THREAD

**Issue by Pyprohly** [payloadcms/payload#9836]
### Describe the Bug

When validating a number field with a min/max value constraint, there’s an inconsistency between the server-side and client-side error messages. The client-side message is incorrect.

### Current Behaviour

Server-side validation shows a descriptive message:

* E.g.: `1234 is greater than the max allowed Value of 100.`

Client-side validation shows a translation key as the message instead:

* `validation:greaterThanMax`

### Expected Behaviour

Both server and client validation should show the same error message.

---

Problem 2:

`1234 is greater than the max allowed Value of 100`

The error message shows “`Value`” instead of using the field’s `label`. E.g., a collection config with `label: 'SomeNumb'` should say:

`1234 is greater than the max allowed SomeNumb of 100`

Problem 3:

Feature request: When an invalid number, such as arbitrary text, is entered into a (non-required) number field, the value gets ignored just as if you hadn’t written anything. I would prefer if the raw text went through with the validation function and told the user that their number was invalid. Incorrectly entered data shouldn’t be discarded silently.

### Link to the code that reproduces this issue

https://github.com/Pyprohly/payload-number-field-validation

### Steps to Reproduce

* Create a new blank PayloadCMS application.
* Create a new collection with number field:

```typescript
import type { CollectionConfig } from 'payload'

export const Thing: CollectionConfig = {
  slug: 'thing',
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
    },
    {
      name: 'count',
      type: 'number',
      label: 'SomeNumb',
      max: 100,
    },
  ],
}

export default Thing
```

* Add collection to `payload.config.ts`.
* Navigate to create new item form.
* Enter a value greater than 100 in the number field.
* Click ‘Save’ to observe server message.
* Change the field value to observe client-side message.

### Which area(s) are affected? (Select all that apply)

Not sure

### Environment Info

```text
Payload: 3.5.0
Node.js: 23.3.0
Next.js: 15.0.4
```

**Comment by jmikrut** [comment]
Thanks for the report @Pyprohly — this is now fixed!
