### ISSUE TITLE
Infinite Redirect Loop on 404 Page in Production with Website Template

### ISSUE THREAD

**Issue by Daakey** [payloadcms/payload#9839]
### Describe the Bug

When visiting a non-existent page (404) in production, the page flickers continuously, suggesting an infinite redirect loop. This issue only appears in production mode.

https://github.com/user-attachments/assets/f97e7afd-a41e-460a-8b81-ea04e5bcda00

The issue is the same as in https://github.com/payloadcms/payload/issues/8306, which is why I felt free to copy the description ( hi @paulpopus ).

### Link to the code that reproduces this issue

https://github.com/Daakey/payload-404-bug

### Reproduction Steps

1. Use the latest website template.
2. Seed the database.
3. Remove the seed page redirect in [slug]/page.tsx.
4. Run "pnpm run build" and start with "pnpm run start"
5. Visit any non-existent page in production mode.

### Which area(s) are affected? (Select all that apply)

area: templates

### Environment Info

```text
Binaries:
  Node: 20.14.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.14.4
Relevant Packages:
  payload: 3.5.0
  next: 15.0.4
  @payloadcms/email-nodemailer: 3.5.0
  @payloadcms/graphql: 3.5.0
  @payloadcms/live-preview: 3.5.0
  @payloadcms/live-preview-react: 3.5.0
  @payloadcms/next/utilities: 3.5.0
  @payloadcms/payload-cloud: 3.5.0
  @payloadcms/plugin-form-builder: 3.5.0
  @payloadcms/plugin-nested-docs: 3.5.0
  @payloadcms/plugin-redirects: 3.5.0
  @payloadcms/plugin-search: 3.5.0
  @payloadcms/plugin-seo: 3.5.0
  @payloadcms/richtext-lexical: 3.5.0
  @payloadcms/translations: 3.5.0
  @payloadcms/ui/shared: 3.5.0
  react: 19.0.0
  react-dom: 19.0.0
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 16310
  Available CPU cores: 12
```

**Comment by Daakey** [comment]
I enabled and disabled every component inside of "src/app/(frontend)/layout.tsx" and the issue seems to be caused by <LivePreviewListener />. I'm not exactly sure why yet.

**Comment by paulpopus** [comment]
I've found it too, it's because it calls the given `refresh()` function in a useEffect, on 404 pages this is causing the infinite reload
