### ISSUE TITLE
Lexical Converter Missing

### ISSUE THREAD

**Issue by Sharlmagne** [payloadcms/payload#9879]
# Documentation Issue

https://payloadcms.com/docs/lexical/converters#lexical-jsx

The documentation states that the RichText component can be found here:
```
import { RichText } from '@payloadcms/richtext-lexical/react'
```
but this is not the case.

I am getting this error:
TS2307: Cannot find module @payloadcms/ richtext-lexical/ react or its corresponding type declarations.

**Comment by AlessioGr** [comment]
@Sharlmagne What payload version are you using?

**Comment by Sharlmagne** [comment]
@AlessioGr 

version v3.5.0

  "dependencies": {
    "@hookform/resolvers": "^3.9.1",
    "@payloadcms/db-postgres": "latest",
    "@payloadcms/next": "latest",
    "@payloadcms/richtext-lexical": "latest",
    "@payloadcms/storage-vercel-blob": "latest",
    "@radix-ui/react-aspect-ratio": "^1.1.0",
    "@radix-ui/react-avatar": "^1.1.1",
    "@radix-ui/react-dialog": "^1.1.2",
    "@radix-ui/react-icons": "^1.3.2",
    "@radix-ui/react-label": "^2.1.0",
    "@radix-ui/react-separator": "^1.1.0",
    "@radix-ui/react-slot": "^1.1.0",
    "@zapal/payload-lexical-react": "^1.6.0",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "cross-env": "^7.0.3",
    "embla-carousel": "^8.5.1",
    "embla-carousel-autoplay": "^8.5.1",
    "embla-carousel-react": "^8.5.1",
    "graphql": "^16.8.1",
    "lucide-react": "^0.460.0",
    "next": "15.0.4",
    "next-themes": "^0.4.3",
    "payload": "latest",
    "react": "19.0.0",
    "react-dom": "19.0.0",
    "react-hook-form": "^7.53.2",
    "sharp": "0.32.6",
    "sonner": "^1.7.0",
    "tailwind-merge": "^2.5.4",
    "tailwindcss-animate": "^1.0.7",
    "wikipedia": "^2.1.2",
    "zod": "^3.23.8"
  },

**Comment by AlessioGr** [comment]
Can you share a repository that reproduces this issue?

**Comment by Sharlmagne** [comment]
https://github.com/Sharlmagne/gsi-webapp 

There is a component titled "LexicalConverter", which is a copy of what I found in the docs.

**Comment by AlessioGr** [comment]
@Sharlmagne the issue is that you are not using the latest version of payload. You have 3.0.1 installed:

![Image](https://github.com/user-attachments/assets/0053f40d-4615-4c5f-bfbf-397e8142960a)

I recommend hardcoding the version numbers in your package.json. So, change "latest" to "3.5.0" and make sure not to use any `^` carets.
