### ISSUE TITLE
Only one file is saved when uploading multiple images in a multiple field.

### ISSUE THREAD

**Issue by manutepowa** [payloadcms/payload#9890]
### Describe the Bug

When configuring an image field with the <code>hasMany: true</code> option, attempting to upload multiple files at once results in only one of the files being saved correctly in the database.

### Link to the code that reproduces this issue

https://github.com/payloadcms/payload

### Reproduction Steps

Video
https://github.com/user-attachments/assets/3ed984c0-f958-4d36-8c8d-7c2400cfad66

Field config.
```ts
{
  type: "upload",
  name: "gallery",
  label: "Galería de imágenes",
  relationTo: "media",
  hasMany: true,
}
```

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Payload v3.5.0
```

**Comment by akhrarovsaid** [comment]
@manutepowa Yup. Reproduced in monorepo `_community` folder with the config you provided, authoring a fix. I'd like to test a few things with the bulk uploads before making a PR but should have one out soon!
