### ISSUE TITLE
"collections[2].admin.views" is not allowed

### ISSUE THREAD

**Issue by SuddenDev** [payloadcms/payload#99]
# Bug Report
So similar to the bug that was discovered and already fixed in #95, I just found the same bug for collections.

```
[nodemon] starting `node server.js`
[09:40:42] INFO (payload): Starting Payload...
[09:40:43] ERROR (payload): There were 1 errors validating your Payload config
[09:40:43] ERROR (payload): 1: "collections[2].admin.views" is not allowed
[nodemon] app crashed - waiting for file changes before starting...
```

## Expected Behavior
As referenced here: [https://payloadcms.com/docs/admin/components#collections](https://payloadcms.com/docs/admin/components#collections)

## Steps to Reproduce
My example code

```
const Users = {
  slug: "users",
  auth: true,
  admin: {
    useAsTitle: "email",
    views: {
      List: () => <div>My List</div>,
    },
  },
  access: {
    read: () => true,
    create: () => true,
  },
  hooks: {
    beforeRead: [onlyNameIfPublic],
  },
  fields: [
    // Email added by default
    {
      name: "name",
      label: "Name",
      type: "text",
    },
  ],
};

export default Users;
```

## Additional Bug in globals?
Also I found that the views.edit customization for globals does not seem to work either.  ([Docs](https://payloadcms.com/docs/admin/components#globals))

```
// file Navigation.js
...
  admin: {
    views: {
      Edit: () => <div>My Edit</div>,
    },
  },
...
```

**Comment by DanRibbens** [comment]
I think its actually an issue with our documentation. 
The typescript type and our config validation has `List` under `admin.components.views.List`. Your example is missing `components`.

https://payloadcms.com/docs/admin/components#collections could be more clear about this.

Maybe we review the structure of this at some point, as it is a lot of nesting.

**Comment by SuddenDev** [comment]
Oh thanks @DanRibbens!
`admin.components.views.List` works great!

I think we can close this then.
