### ISSUE TITLE
Missing Label + Description Fields in nested Lexical RichText Field

### ISSUE THREAD

**Issue by aschnebelext** [payloadcms/payload#9905]
### Describe the Bug

The Label and/or Description is not rendered when using the RichText Lexical Editor in a Block Field.

![Image](https://github.com/user-attachments/assets/33456adf-c68c-44b2-92b8-a44963698518)

### Link to the code that reproduces this issue

https://github.com/aschnebelext/payload-nested-richtext

### Reproduction Steps

Fork my reproduction Repository, create a user, create a new lesson, create a new "Quiz" Block and notice, that the Label and Descriptions are missing.

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Binaries:
  Node: 20.18.1
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 9.15.0
Relevant Packages:
  payload: 3.6.0
  next: 15.0.4
  @payloadcms/db-mongodb: 3.6.0
  @payloadcms/email-nodemailer: 3.6.0
  @payloadcms/graphql: 3.6.0
  @payloadcms/next/utilities: 3.6.0
  @payloadcms/payload-cloud: 3.6.0
  @payloadcms/richtext-lexical: 3.6.0
  @payloadcms/translations: 3.6.0
  @payloadcms/ui/shared: 3.6.0
  react: 19.0.0
  react-dom: 19.0.0
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Nov 14 18:15:21 PST 2024; root:xnu-11215.41.3~13/RELEASE_ARM64_T6041
  Available memory (MB): 65536
  Available CPU cores: 16
```

**Comment by GermanJablo** [comment]
Inside the Lexical editor, the way to put a Label to the blocks or to the fields of the blocks is like this:

```ts
admin: {
  components: {
    Label: '/path/to/your/LabelComponent.js',
  },
},
```

You can read the [documentation here](https://payloadcms.com/docs/fields/blocks#customizing-the-way-your-block-is-rendered-in-lexical).

Note that the blocks do not include a description property when they are rendered inside the Lexical editor.
