### ISSUE TITLE
is there anyway to hide livepreview button conditionally?

### ISSUE THREAD

**Issue by KBambharoliya** [payloadcms/payload#9947]
### Describe the Bug

is there anyway to hide live preview button conditionally? 
i want to hide livepreview button when i have one categoryData null

### To Reproduce

Live preview

### Payload Version

2.0

**Comment by jacobsfletch** [comment]
@KBambharoliya you should be able to use a custom tab component for this, `admin.views.Edit.LivePreview.Tab`. The exact path here has changed in 3.0, where it's now `admin.views.edit.livePreview.tab.Component`.

**Comment by KBambharoliya** [comment]
ok. Thank you for your suggestion!!
