### ISSUE TITLE
Duplicate button not copying other locale content

### ISSUE THREAD

**Issue by bardak-dev** [payloadcms/payload#995]
# Bug Report

Duplicate button not copying other locale content

## Expected Behavior

each locales content should duplicate

## Current Behavior

only one locale is duplicated

## Possible Solution

fetch data of all locales before save duplicated version and put to db on first save

## Steps to Reproduce

1. go to [public demo](https://demo.payloadcms.com/admin)
2. go to Pages collection
3. check that page Home has other locale content 
4. duplicate this page, publish and change locale, you wont see other locale content other than the one that has been duplicated

## Detailed Description

 Payload last version, browser any

**Comment by jmikrut** [comment]
Hey @bardak-dev — thank you for the report!

This has been fixed in https://github.com/payloadcms/payload/pull/1034.

A release will be published shortly!
