### ISSUE TITLE
Error after uploading a new item via the rich text editor

### ISSUE THREAD

**Issue by madebyjonny** [payloadcms/payload#9964]
### Describe the Bug

I am seeing an error with the rich text field where a new uploaded item is added to the content, the editor will error. In production I was able to save and refresh the page and continue editing, however locally it errors out and I am unable to save the current item I am working on. 

### Link to the code that reproduces this issue

https://github.com/madebyjonny/upload-error-payload-reproduction

### Reproduction Steps

I have provided a video of the error I am seeing on the repo provided

# steps to reproduce 

1. Navigate to a collection with a rich text field 
2. type /upload upload a new file 
3. once added the error accures 

### Which area(s) are affected? (Select all that apply)

Not sure

### Environment Info

```text
next: 15.1.0
node: v20.11.1
payload: 3.7.0
```

**Comment by GermanJablo** [comment]
Thanks for reporting! This will be in the next release
