### ISSUE TITLE
Join Field Forbids Default Access Control from Related Collections

### ISSUE THREAD

**Issue by davliang** [payloadcms/payload#9974]
### Describe the Bug

Related to #9930. Fixed by #9971.

Fetching a document in the admin panel with a `join` field with default access will result in a `doc` undefined on the client-side and `Forbidden` in the console logs on the client side and server side.

### Link to the code that reproduces this issue

https://github.com/davliang/payload/tree/issue/join-permissions

### Reproduction Steps

1. Run `pnpm install` to install dependencies
2. Run `pnpm dev _community` to start the admin panel
3. Go to `http://localhost:3000/admin`
4. Create a new `All Posts` (Just click save in the form.)

### Which area(s) are affected? (Select all that apply)

area: docs, area: ui

### Environment Info

```text
Payload: 3.7.0
Node.js: 22.6.0
Next.js: 15.1.0
```

**Comment by akhrarovsaid** [comment]
If I'm not mistaken here I believe this will be fixed by #9971 and the issue was not passing a `user` while `overrideAccess` is set to false to prevent users from reading data they technically shouldn't have access to.

**Comment by davliang** [comment]
> If I'm not mistaken here I believe this will be fixed by [#9971](https://github.com/payloadcms/payload/pull/9971) and the issue was not passing a `user` while `overrideAccess` is set to false to prevent users from reading data they technically shouldn't have access to.

You're right, patching it works correctly now. I should have looked closer at the previous pull requests. Thank you!

**Comment by DanRibbens** [comment]
Thanks for opening an issue. I caught this one too late yesterday to get it into the release. 

I also found that join field e2e tests were not running in CI which would have caught this. Now it is included and passing https://github.com/payloadcms/payload/actions/runs/12330014124/job/34415043646?pr=9971 as expected.

**Comment by tyteen4a03** [comment]
Can confirm - will have to downgrade to 3.6.0 while this is fixed.

**Comment by DanRibbens** [comment]
Closing this issue, we'll get it out soon!
